### ISSUE TITLE
Potential False Positive - Bitdefender Antivirus - Strawberry Uninstall Program

### ISSUE THREAD

**Issue by omoknen** [strawberrymusicplayer/strawberry#1002]
Windows 10 Pro - On two machines
Strawberry Version:  1.06

Bitdefender Antivirus marks only the "Uninstall" program for the windows version of Strawberry Music Player as a Trojan.
This is more than likely a False positive, but I am listing it so that others know that it might occur.  It got removed but the program still runs.

**Comment by jonaski** [comment]
https://www.virustotal.com/gui/file/f25cc0f0011b8ae2dd5e3f931399b56bcd8485779670e9be1be6128b27f35d41

https://www.virustotal.com/gui/file/3758ab4dd7e2e08919c66be24c609df90c59b34bf69e2b93d5655022e4044342

**Comment by jonaski** [comment]
uninstall.exe in the MinGW release is being detected as "virus" by many anti-virus scanners. I have reported it to Bitdefender here: https://www.bitdefender.com/consumer/support/answer/29358/
I don't know if they fix it or not it's usually hard to keep ani-virus companies from flagging the mingw compiled executables as virus.
An option is to use the MSVC version instead which is not currently detected as "virus" by anyone, and is more unlikely to be flagged as virus in the future.
