### ISSUE TITLE
Error popups with SQL message.

### ISSUE THREAD

**Issue by mhandze** [strawberrymusicplayer/strawberry#1003]
On start and everytime track is changed strawberry is showing SQL error popup.
It's fresh installation of ubuntu 22.04 + strawberry from PPA.

At first look it seems like it's missing some DB installation? But I dont see it in dependencies.

![strawberry_error](https://user-images.githubusercontent.com/984837/180665483-8c6ace65-ccc8-4f97-b014-4945eda216e2.png)

**Comment by jonaski** [comment]
Sounds like the database is corrupted,  more info: https://sqlite.org/howtocorrupt.html
Did you run an integrity check of the database?
https://wiki.strawberrymusicplayer.org/wiki/Database_integrity_check

**Comment by mhandze** [comment]
Yeah it could be. Where Strawberyy keep sql file to store all the data? I guess somewhere in home folder?

**Comment by jonaski** [comment]
`~/.local/share/strawberry/strawberry/strawberry.db`

**Comment by mhandze** [comment]
Deleting that file and restarting app solved problem.
