### ISSUE TITLE
Dark theme not applied after upgrade to Ubuntu 22.04

### ISSUE THREAD

**Issue by exptom** [strawberrymusicplayer/strawberry#1007]
**Describe the bug**
I was previously using Ubuntu MATE 21.10 with a dark theme. I had strawberry set to use the system defaults and it matched the dark colour scheme that I had applied to the system. However since recently upgrading to MATE 22.10 it no-longer matches and appears in a light colour scheme. I have used the appearance settings in strawberry to manually set a colour but it doesn't seem to change all elements of the interface and does not look as good as it used to before I upgraded my OS.

**System Information:**
 - Operating system: Ubuntu MATE 22.04
 - Strawberry Version: 1.0.7

**Comment by jonaski** [comment]
https://wiki.strawberrymusicplayer.org/wiki/FAQ#Strawberry_does_not_respect_Qt_style,_KDE_theme_or_icons_on_Linux.
