### ISSUE TITLE
Win32:MalOb-IJ detected

### ISSUE THREAD

**Issue by tlkw79** [strawberrymusicplayer/strawberry#1009]
Hi,

I am trying to upgrade the Strawberry music player from 1.0.5 to StrawberrySetup-1.0.7-mingw-x64.exe, Avast keeps detecting Win32:MalOb-IJ. Any idea?

Thanks.

**Comment by jonaski** [comment]
It is a false-positive. I already reported this to Avast, see also issue #1002
See FAQ: https://wiki.strawberrymusicplayer.org/wiki/FAQ#Setup_or_installed_files_being_detected_as_virus_on_Windows
If it's not resolved try using the MSVC setup instead.
