### ISSUE TITLE
Strawberry 1.07 for Windows x86/32bit ?

### ISSUE THREAD

**Issue by Cwpute** [strawberrymusicplayer/strawberry#1019]
Hi,
I wanted to upgrade my version of Strawberry from 1.01 to 1.07, as the software prompted me to. Unfortunately it downloaded the x64/64bit version of the .exe instead of the x86/32bit version, which would have been suited for my computer. Eager to report the issue, i went onto here to do so, but when i looked at the downloads, there were no x86/32bit Windows versions available for 1.07 although they are seemingly provided for Linux builds. I fact, non have been provided since Strawberry 1.04.
Have i missed something? Has support been silently dropped for Windows 32bit or is it a mistake for not having included them since then?

Either way, Strawberry should not prompt me to download an incompatible version when it knows my computers' specs.

**Comment by jonaski** [comment]
I removed them because I found it unlikely that anyone was using 32-bit Windows 10, but had no way of knowing for sure. So my plan was to add them back if anyone complained, so far you are the first one.
The updater was always incorrectly pointing to 64 bit release and no-one had complained about that either, it was fixed in a few versions ago.
Anyway, I've added back 32 bit, will be available next release.
In the meantime use this: https://builds.strawberrymusicplayer.org/windows/StrawberrySetup-1.0.7.29.g9c04ce66-msvc-x86.exe

**Comment by Cwpute** [comment]
> In the meantime use this: https://builds.strawberrymusicplayer.org/windows/StrawberrySetup-1.0.7.29.g9c04ce66-msvc-x86.exe

Thank you for the provided installer, but it unfortunately throws an error when trying to start Strawberry: 
![image](https://user-images.githubusercontent.com/80604512/185398850-c987892b-cb27-405f-9a10-e217b2ac5146.png)
No idea where this might come from. All i can see from browsing online is that it might be due to my laptop being old and maybe using an old version of Qt... or lacking one due to me previously uninstalling the incompatible x64 version of Strawberry.

**Comment by jonaski** [comment]
The Windows application log in event viewer usually give an idea of what's wrong, Control Panel / Administrative Tools / Event Viewer / Application.

My best guess is that you are either missing the Microsoft Visual C++ Runtime, or an older or incompatible version of `qwindows.dll` is picked up instead, the file should be in `c:\program files (x86)\strawberry music player\platforms`.

Try installing the latest version of the Microsoft Visual C++ Redistributable package:
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Direct link: https://aka.ms/vs/17/release/vc_redist.x86.exe

We use VS 2019, but this one is the latest for all supported versions 2015-2022.

If that doesn't help, uninstall Strawberry Music Player from the Control Panel. Make sure both `c:\program files (x86)\strawberry music player` and `c:\program files\strawberry music player` are empty, if not delete them manually. Then run the setup again to reinstall.

**Comment by Cwpute** [comment]
This is the error that's shown in the event viewer. I have no idea what i should be looking for!
```
[-](https://github.com/strawberrymusicplayer/strawberry/issues/1019#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/strawberrymusicplayer/strawberry/issues/1019#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-08-19T09:58:52.000000000Z" /> 
  <EventRecordID>16801</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Zombie</Computer> 
  <Security /> 
  </System>
[-](https://github.com/strawberrymusicplayer/strawberry/issues/1019#) <EventData>
  <Data>strawberry.exe</Data> 
  <Data>1.0.7.0</Data> 
  <Data>62f8bea2</Data> 
  <Data>ucrtbase.DLL</Data> 
  <Data>10.0.14393.2990</Data> 
  <Data>5caeb859</Data> 
  <Data>c0000409</Data> 
  <Data>000884cb</Data> 
  <Data>1810</Data> 
  <Data>01d8b3b2070c0ffa</Data> 
  <Data>D:\Strawberry Music Player\strawberry.exe</Data> 
  <Data>C:\Windows\SYSTEM32\ucrtbase.DLL</Data> 
  <Data>87217e2a-1fa5-11ed-976b-10c37bacc15e</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

> Try installing the latest version of the Microsoft Visual C++ Redistributable package: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
> 
> Direct link: https://aka.ms/vs/17/release/vc_redist.x86.exe

These are the informations shown for the `qtwindows.dll` file after i reinstalled the MVC++ package from the direct link you provided. Strawberry still wouldn't start.
![image](https://user-images.githubusercontent.com/80604512/185596292-0fbbf529-871e-4de7-833f-83a868ac74c7.png)

I unistalled Strawberry from the Control Pannel, and checked if the directories you mentionned contained files but they didn't even exist (as it thought: i installed Strawberry in a custom directory in `D:\Strawberry Music Player`).

This time i installed Strwaberry in the default directory. I checked `qtwindows.dll` in its Strawberry directory but it seems to be the same version as previously. And the application still fails to start, with the same error message :(

**Comment by jonaski** [comment]
I don't have a 32-bit machine to test on, but I tested on a clean Windows 10 64-bit installation in VirtualBox and it works.
Can you try the MinGW version instead:
https://builds.strawberrymusicplayer.org/windows/StrawberrySetup-1.0.7.34.g6562258d-mingw-x86.exe

**Comment by Cwpute** [comment]
> Can you try the MinGW version instead: https://builds.strawberrymusicplayer.org/windows/StrawberrySetup-1.0.7.34.g6562258d-mingw-x86.exe
Sorry i was on vacations and couldn't try the installer, and the link you provided seems dead now.

**Comment by jonaski** [comment]
https://files.strawberrymusicplayer.org/StrawberrySetup-1.0.8-mingw-x86.exe

**Comment by Cwpute** [comment]
> https://files.strawberrymusicplayer.org/StrawberrySetup-1.0.8-mingw-x86.exe

😬
![image](https://user-images.githubusercontent.com/80604512/187903039-69607392-b8d6-49f5-b309-2a15d8f4828e.png)
after clikcing OK it shows another window: 
![image](https://user-images.githubusercontent.com/80604512/187903385-cbc05898-8b71-4663-901b-90c5d277a1cb.png)

I'll try the workarounds you provided in [your previous answer](https://github.com/strawberrymusicplayer/strawberry/issues/1019#issuecomment-1219668135) in an hour or so.

**Comment by jonaski** [comment]
So basically the same issue as with the MSVC version?
Can you check if you have other qwindows.dll somewhere that conflicts with the Strawberry one.

**Comment by Cwpute** [comment]
There are 6 different versions of them...
1 for Strawberry, and 5 others for 5 different applications, one of them specifically being for the 32bit version of Shotcut. There might be a conflict yes. I will try deactivating the other `qwindows.dll` files later today see which one(s) may conflict with that of Strawberry.
