### ISSUE TITLE
Allow customizing Icecast Artist/Album/Title fields

### ISSUE THREAD

**Issue by bmillham** [strawberrymusicplayer/strawberry#1023]
I listen to an Icecast stream that sends its metadata info as Artist - Title - Album
But Strawberry picks that up as Artist - Title

[EDIT: I should have said that it shows in Strawberry as Artist - Album, not Artist - Title]

I haven't been able to find a way to customize Strawberry to handle this. Am I missing something?
And if I'm not this would be a nice option to allow people to customize Strawberry to the stream.
I just started using Strawberry and do like it other than that annoying glitch.
Thanks!
Brian

**Comment by jonaski** [comment]
Do you have a stream url?
All icecast streams I have tested only provide "artist - title".

**Comment by bmillham** [comment]
The stream is at http://rockitradio.space:8000/listen

**Comment by kernal64** [comment]
Hi,
I see this is closed, but I have the same issue with this stream

[United Radio - Metal](http://icy.unitedradio.it/um099.mp3)

and all other streams from "United Radio". "Artist" is exchanged with "Title".
kind regards
