### ISSUE TITLE
Strawberry 1.0.8 is not playing any track in Qobuz Plugin

### ISSUE THREAD

**Issue by ranquetat** [strawberrymusicplayer/strawberry#1027]
See the FAQ before opening an issue: https://wiki.strawberrymusicplayer.org/wiki/FAQ
Check the Changelog to see if the issue is already fixed: https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog
If it's already fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/
For technical issues, questions and discussion please use the forum on https://forum.strawberrymusicplayer.org/
Any issues related to feature requests will be closed. See the README for more details.

**Describe the bug**
Plugin is not working to play any track

**To Reproduce**
Steps to reproduce the behavior.
Enable Qobuz plugin, configure app id, app secret, user, password.
Add any track in playlist, click on play. 
A error occurs (see screenshot). 

Add any track to play. 

**Expected behavior**
Tracks playing

**Screenshots:**
If applicable, add screensho
![erroPluginQobuzPlay](https://user-images.githubusercontent.com/38974841/187545216-887d7ba1-9be6-4043-bbb1-590c0f7ec309.png)
ts to help explain your problem.

**System Information:**
 - Operating system: macOS Monterey/ Zorin OS 16.1 PRO
 - Strawberry Version: 1.0.8

**Additional context**

**Comment by jonaski** [comment]
QObuz streams works here.
The message means that QObuz does not accept the signature sent with the URL request. So either the app secret is wrong, revoked, or the signature needs to be sent differently for that app ID.
There are no changes in 1.0.8 related to QObuz streams. If it worked before, then QObuz might have done some changes to the way the signature needs to be sent for that particular App ID you are using.
