### ISSUE TITLE
[Request] Make the analyzer logarithmic instead of linear

### ISSUE THREAD

**Issue by octopushugger** [strawberrymusicplayer/strawberry#1033]
Would be easier to understand and make better use of the screen space. The analyzer confused me for a while since you never see linear audio graphs

Normal Logarithmic:
![image](https://user-images.githubusercontent.com/91927383/188413688-9b566ed0-d47f-4f06-9441-fba9a6c3d47e.png)
Stretched to look close to linear:
![image](https://user-images.githubusercontent.com/91927383/188423783-9891222e-9885-4135-9383-1017804c3819.png)

It's kinda funny when you see the bass is only displayed in the first 1% of the analyzer and the highest frequencies you can hear that are almost indiscernible from each other take up a massive 50%

**Comment by jonaski** [comment]
Feel free to do this. We don't have contributors to do it.
