### ISSUE TITLE
Device hw:1,0 is busy. No playback in strawberry

### ISSUE THREAD

**Issue by desputinski** [strawberrymusicplayer/strawberry#1034]
**Describe the bug**
I'm using strawberry with debian stable and an external USB audio device. So now when Firefox is running (no video turned on), I get this error message in strawberry:
`../ext/alsa/gstalsasink.c(869): gst_alsasink_open (): /GstBin:audiobin/GstAlsaSink:pipeline-5-alsasink: Device 'hw:1,0' is busy`

In the backend settings under "device" it is set to the usb audio device (not automatically select) and under "output" it is set to "Output to a sound card via ALSA" (in order to have the best possible audio quality)

So only if I close firefox, strawberry is working. but that is not a good solution...
Does anybody of you know a solution?

**To Reproduce**
Start firefox, play some videos, start other programs using pulse, then start strawberry and try to play back music

**Expected behavior**
Strawberry always plays music via alsa output, without getting in conflict with other programs

**System Information:** AMD Ryzen Desktop Computer with Teratec Aureon 5.1 audio card on usb port
 - Operating system: Debian 11
 - Strawberry Version: Version 1.0.7

**Comment by jonaski** [comment]
This is not a Strawberry bug, it's another program using the device.

> **To Reproduce** Start firefox, play some videos, start other programs using pulse, then start strawberry and try to play back music

PulseAudio will hold the device open. You need to disable PulseAudio if you use ALSA directly.
