### ISSUE TITLE
(Windows) Implement SystemMediaTransportControls

### ISSUE THREAD

**Issue by Professor-Paradox** [strawberrymusicplayer/strawberry#1035]
Hi, have been using the clementine for over 4 years, and strawberry for over a year.
i like this, but have a feature request from your team, to implement a way to play or pause the music from strawberry player from the windows volume popup menu it self.

Here is a screenshot showing a youtube video and the controls to play pause,a I want strawberry player to use  this also.
![image](https://user-images.githubusercontent.com/46624860/189311938-2548e3b2-202d-43c2-9483-cd6d1cbeebe6.png)

main reason being I can control the media playback with kdeconnect on my phone, this windows pop up works great because kde access that, and if strawberry player has an option to enable using windows volume interface.
Can any one show me how.
if not can this feature be added in the next version or so.
thanks for reading this far. have a nice day.

**Comment by jonaski** [comment]
We don't take feature requests. I don't what this is. Not even what OS it is.

**Comment by Jarfeh** [comment]
> We don't take feature requests. I don't what this is. Not even what OS it is.
It is the windows 10+ media control widget

**Comment by Professor-Paradox** [comment]
Hi, I wasn't clear then let me be a little clarity here.

https://www.reddit.com/r/kde/comments/owboiv/kde_connect_windows_10_media_controls_only_works/
https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols

This is what I am talking about, only the windows 10 groove music player and chrome and firefox browser show media controls like this.
![image](https://user-images.githubusercontent.com/46624860/203461021-938e77d1-9e18-41a1-86f2-da8cbc9c314e.png)

When I play music with strawberry it doesn't show this menu.

The only reason I want the windows system media transport API to be included in strawberry is, that I use disconnect and it can control the media play back of chrome using this API.
i like to have media control on kdeconnect on windows 10 for the strawberry player.

if this API is included in the application this would be possible. 

I know it is a feature request, but can you guys tell if it is possible? if so provide me some links or resources so I may implement it myself. I know a bit of python. may be I can learn to build or at least try it.

I really like this player for all its features and if this kdeconnect media control is included it would be the best music player in the windows ecosystem.

**Comment by jonaski** [comment]
Doesn't look to hard to implement. Here is the documentation for C++: https://learn.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols?view=winrt-22621
Create a class similar to mpris2.cpp that is used for Windows, you can look for how mpris2 is used various places in Strawberry to imform about play status, album cover, etc.
https://github.com/strawberrymusicplayer/strawberry/blob/master/src/core/mpris2.cpp
To see how buttons are updated look at Windows7ThumbBar that also uses the Windows API directly.
https://github.com/strawberrymusicplayer/strawberry/blob/master/src/core/windows7thumbbar.cpp
For building strawberry with Visual Studio: https://github.com/strawberrymusicplayer/strawberry-msvc

**Comment by jonaski** [comment]
Closing this as there isn't any update. I don't have chance to do this in the near future.

**Comment by matbc92** [comment]
It's quite a bummer that it does not have this feature, cause it causes the OS to go into sleep since it does not think there is media playing, and I have KDE connect working in my windows installation, but I cannot control the the media through my phone since the mediatransport stuff does not work properly, I think it is a bit of a usability issue not just a feature request.

**Comment by jonaski** [comment]
The new version 1.2.22 has this now, but it's only on the msvc version as it's not possible with mingw-w64
