### ISSUE TITLE
Synchronize volume with PulseAudio

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1037]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The slider of the sound applet that indicates the volume of Strawberry in KDE Plasma does not change when I adjust the volume level via Strawberry GUI,

**To Reproduce**
1. play a song with Strawberry installed in a linux distribution that runs KDE Plasma desktop environment
2. click on sound icon in the system tray and click on 'Applications' tab - there is a slider indicating the current volume of Strawberry
3. hover over the volume slider of Strawberry and adjust the volume by scrolling up/down

**Expected behavior**
the volume slider in 'Applications' tab of the sound applet should reflect the volume adjustment done in the step 3

**System Information:**
 - Operating system: can reproduce on both Arch Linux and neon unstable (based on ubuntu 20.04)
 - Strawberry Version: 1.0.9

**Additional context**
I think this is a Strawberry bug because I'm unable to reproduce with VLC player installed on the same systems.

**Comment by jonaski** [comment]
Strawberry using GStreamer has it's own independent software volume, unlike VLC, it implements synchronization to PA volume control. So I don't think this is possible.

**Comment by glaubersm** [comment]
Humm, I'm also unable to reproduce with Firefox. Is VLC backend still available for Strawberry?

**Comment by jonaski** [comment]
VLC is still available but still very incomplete and untested.

**Comment by glaubersm** [comment]
Thanks Jonas. I'm also unable to reproduce with these players:

Audacious
Qmmp
Lollypop
Exaile
Quod Libet
Pragha

**Comment by jonaski** [comment]
The volume in Strawberry synchronizes fine with kmix and the media player applet in KDE. This is done using MPRIS2.
But I assume you mean the Plasma PulseAudio Applet (this one: https://invent.kde.org/plasma/plasma-pa). That's PulseAudio. The volume in Strawberry (or gstreamer) doesn't synchronize with Pulse Audio, it has never done that and it has never been implemented. It's the same result with the PulseAudio volume control (pavucontrol).
I'm not familiar with most of the other music players you mention, but at least Pragha is using GStreamer, it uses GTK, so it's probably using some GLib API or the PulseAudio library directly, not through gstreamer. so I'm probably wrong, it is most likely possible to implement in Strawberry.

**Comment by jonaski** [comment]
The reason this worked in other GStreamer players, and not Strawberry is because Strawberry was creating it's own volume element, instead of using the pipeline/playbin or output/sink volume, mainly because of the fading features.
I have now fixed so that Strawberry uses the existing volume instead of creating it's own volume when it's detected that there is a volume for the output/sink, this now works when specifically selecting PulseAudio or any other output/sink that supports it, however it still doesn't work when output/sink is set to auto, because in that case it's not detected which output/sink GStreamer selects, maybe there is a solution to that.
The fader now creates it's own dedicated volume that works internally independent of the user volume if one or more of the fading options are enabled.

**Comment by jonaski** [comment]
With https://github.com/strawberrymusicplayer/strawberry/commit/b2073df3c3391d2db5645f2fc246eb785e76e956 it should now detect if there is a volume control when set to auto too.

**Comment by glaubersm** [comment]
Thank you again Jonas.
I have created another issue possibly related to this one:
https://github.com/strawberrymusicplayer/strawberry/issues/1083
