### ISSUE TITLE
SQL related issues "Unable to execute SQL query"

### ISSUE THREAD

**Issue by bug-df** [strawberrymusicplayer/strawberry#1038]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Series of SQL error messages along the lines of :
A) "Unable to execute SQL query: unable to open database file Unable to fetch row<br />Failed query: INSERT INTO playlist_items (playlist, type, collection_id, title, album, artist, albumartist, track, disc, year, originalyear, genre, compilation, composer, performer, grouping, comment, lyrics, artist_id, album_id, song_id, beginning, length, bitrate, samplerate, bitdepth, source, directory_id, url, filetype, filesize, mtime, ctime, unavailable, fingerprint, playcount, skipcount, lastplayed, lastseen, compilation_detected, compilation_on, compilation_off, compilation_effective, art_automatic, art_manual, effective_albumartist, effective_originalyear, cue_path, rating) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
B) a crash
C) "Unable to execute SQL query: unable to open database file Unable to fetch row<br />Failed query: UPDATE songs SET lastseen = ? WHERE directory_id = ? AND unavailable = 0"
D) "Unable to execute SQL query: unable to open database file Unable to fetch row<br />Failed query: UPDATE songs SET lastseen = ? WHERE directory_id = ? AND unavailable = 0

Unable to execute SQL query: unable to open database file Unable to fetch row<br />Failed query: DELETE FROM playlists WHERE ROWID=?

Unable to execute SQL query: unable to open database file Unable to fetch row<br />Failed query: UPDATE playlists SET ui_order=-1"
**To Reproduce**"
E) "Unable to execute SQL query: unable to open database file Unable to fetch row<br />Failed query: UPDATE songs SET playcount = playcount + 1, lastplayed = ? WHERE ROWID = ?"
Steps to reproduce the behavior.
A) From collections, add a track via right click append to current playlist or play an item in a play list (it plays but displays this error)
B) If you attempt to append to a new playlist it crashes (error message dies not complete display before crash) or to open a new playlist from the 
C) Start Strawberry
D) Close a temporary (i.e. unsaved playlist by clicking on the X on the tab
E) When track ends
**Expected behavior**
A, B, track to be added to the relevant play list
C Strawberry to start without error messages
D Playlist tab to close without error messages
E Track to end without error messages
**Screenshots:**

**System Information:**
 - Operating system: Lubuntu 18.04 fully updated
 - Strawberry Version: 1.0.9 recently updated (problems not occurring with previous version: probably 1.08, but might have been 1.07)

**Additional context**
libqt4-sql-mysql version no: 4:4.8.7+dfsg-7ubuntu1

**Comment by jonaski** [comment]
>A) "Unable to execute SQL query: unable to open database file Unable to fetch row

"unable to open database file" sounds like a permission issue. What file permissions for strawberry.db?

`ls -la ~/.local/share/strawberry/strawberry/strawberry.db`

A common issue for this fault is the database being corrupted. Did you integrity check check the database?

`sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db "pragma integrity_check"`

> Failed query: UPDATE playlists SET ui_order=-1"

Can you manually run this query?

`sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db "UPDATE playlists SET ui_order=-1"`

> 
> **Additional context** Add any other context about the problem here. libqt4-sql-mysql version no: 4:4.8.7+dfsg-7ubuntu1

libqt4-sql-mysql is not relevant to Strawberry, Strawberry does not use Qt 4 or MySQL.

**Comment by bug-df** [comment]
Jonaski,
Thanks for your reply - I've been out of circulation

The responses to your queries are as follows:
```
xxxxxxxxxxxx:~$ ls -la ~/.local/share/strawberry/strawberry/strawberry.db
-rw-r--r-- 1 xxxxxx xxxxxx 42520576 Sep 10 10:28 /home/xxxxxx/.local/share/strawberry/strawberry/strawberry.db
xxxxxxxxxxxx:~$ sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db "pragma integrity_check"
ok
xxxxxxxxxxxx:~$ sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db "UPDATE playlists SET ui_order=-1"
xxxxxxxxxxxx:~$ 
```
Which I think looks as it should.

Since posting my comment and updating other (unassociated applications) I have raise the amount of free disk space (now 2.7GB) and this seems to be "solving the problem" as I can no longer reconstruct the issues.

If that was the cause I am content to see the issue closed - although I might ponder why an "out of disk space" error was not produced - if indeed that was the issue.

Thanks

**Comment by jonaski** [comment]
Disk space seems like a likely cause since all update queries seem to have failed, but not any select queries.
