### ISSUE TITLE
I got a segfault in the last version 1.0.9

### ISSUE THREAD

**Issue by Juniorsnet** [strawberrymusicplayer/strawberry#1039]
- [X ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
strawberry not start
**To Reproduce**
run strawberry on console to show info
**Expected behavior**
program run
**Screenshots:**
```
16:09:02.482 INFO  main:166                         Strawberry 1.0.9 Qt "5.9.5"
16:09:02.482 INFO  main:167                         "Linux Mint 19.3 19.3 - (linux 5.15.65-xanmod1) [x86_64]"
16:09:02.598 DEBUG main:222                         Style: "fusion"
16:09:02.598 ERROR main:238                         Could not open settings file "/home/gsus/.config/strawberry/strawberry.conf" for writing: "No such file or directory"
16:09:02.602 ERROR unknown                          Database schema too old. 
[1]    32218 abort (core dumped)  strawberry
```

**System Information:**
 - Operating system:
 - Linux Mint 19.3 19.3 - (linux 5.15.65-xanmod1) [x86_64]
 - Strawberry Version:
 - Strawberry 1.0.9 Qt "5.9.5"

**Additional context**

**Comment by jonaski** [comment]
What version are you upgrading from?
What does this say?
`sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db "SELECT version FROM schema_version"`

**Comment by Juniorsnet** [comment]
Hello @jonaski I fixed in the "user way".

I delete ~/.config/strayberry (not work)
I delete ~/.cache/strayberry (not work)

I installed version 1.0.8 (not work)
I installed version 1.0.7 (not work)
I installed version 1.0.6 (not work)
I installed version 0.9.3 (its works!)
then I installed version 1.0.0 (its works!)
then I installed version 1.0.1 (its works!)
then I installed version 1.0.2 (its works!)
then I installed version 1.0.3 (its works!)
then I installed version 1.0.4 (its works!)
then I installed version 1.0.5 (its works!)
finally I installed version 1.0.9 and it working now

in any case, the command
`sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db "SELECT version FROM schema_version"`
returns 15

thanks

**Comment by jonaski** [comment]
Version 1.0.4 was the last release that had support for upgrading the very old database schemas that have not been in use for many years, so my guess is that you had a very old release. So upgrading to 1.0.4 first is probably what solved it.
