### ISSUE TITLE
Seek issues with FLAC files only

### ISSUE THREAD

**Issue by xfzv** [strawberrymusicplayer/strawberry#1044]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Seeking backward/forward with left/right arrow is fine since the jump is -5/+5 seconds. Likewise, when seeking with the mouse and the seek bar, no issue as long as I seek -5s/+5s.
However, if I try to seek forward/backward for more than 5 seconds, then the playback seems to continue (I see the seconds elapsing) but the audio output is gone for a few seconds. Then, it resumes but not from the current timestamp, it seeks a few seconds backward and I get some audio for like half a second, then it seeks a few seconds forward (see video with sound below).

- It only occurs with FLAC files (16bit / 24bit, 44100 Hz / 96000 Hz... doesn't make any difference). I don't have any issue with APE, mp3, opus, WavPack, or WAV files
- I'm using Pipewire (0.3.58) and Gstreamer. I had the issue with Pulseaudio before switching
- I can't reproduce the issue with other apps such as Cantata+mpd, DeaDBeeF, mpv...

**To Reproduce**
1. Play a FLAC file
2. Try to seek backward or forward for >5seconds with the mouse and the seek bar
3. The problem described above occurs

**Expected behavior**
Seeking for -5/+5s with FLAC files should work normally

**Screenshots:**
- "Backend" tab in Strawberry settings:
![image](https://user-images.githubusercontent.com/78810647/190989415-349bb016-8ee7-48d7-9297-ee891c414a75.png)

- Video (with sound, download it to get the sound) when seeking with left/right arrow (-5/+5 seconds - no issue):

https://user-images.githubusercontent.com/78810647/190992270-44569e8e-247c-485e-b688-ee6af4853fd7.mp4

- Video (with sound, download it to get the sound) when seeking with mouse for an extended period:

https://user-images.githubusercontent.com/78810647/190991714-49018d38-8ea4-436a-ac17-23bc4afe00ed.mp4

**System Information:**
 - Operating system: Arch Linux / Gentoo (occurs with both distros on the same machine)
 - Strawberry Version: 1.0.9

```
❯ eix -cI flac
[I] media-libs/flac (1.4.0-r1(0/10-12)@09/10/2022): Free lossless audio encoder and decoder

❯ eix -cI media-plugins/gst-plugins-flac
[I] media-plugins/gst-plugins-flac (1.20.3-r1(1.0)@09/10/2022): FLAC encoder/decoder/tagger plugin for GStreamer

❯ eix -cI gstreamer
[I] media-libs/gstreamer (1.20.3(1.0)@08/26/2022): Open source multimedia framework
[I] media-libs/phonon-gstreamer (4.10.0@09/11/2022): GStreamer backend for the Phonon multimedia library
```

**Comment by jonaski** [comment]
Could it be related to this bug: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/issues/420
I can't reproduce it. Can you test output to ALSA.

**Comment by xfzv** [comment]
Same issue with the following configuration:
![image](https://user-images.githubusercontent.com/78810647/192089560-bb7c8e59-162d-436d-9e5c-3e18a51a6107.png)

**Comment by jonaski** [comment]
There are almost no changes between 1.0.8 and 1.0.9, nothing that can cause this.
What version of flac are you using? There was a lot of changes in flac version 1.4.0 released on 9. September. Version 1.4.0 contains "Various seeking fixes" see: https://xiph.org/flac/changelog.html, maybe it actually broke something? While flac 1.4.1 only contain build fixes as far as I can tell.

**Comment by jonaski** [comment]
This is a flac bug. See https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1475 and https://github.com/xiph/flac/pull/472
It will be solved with the next flac release.
