### ISSUE TITLE
Unknown error on Tidal search

### ISSUE THREAD

**Issue by userofryzen** [strawberrymusicplayer/strawberry#1047]
- [x ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Search "Amber Van Day" on tidal tab Artist section
Getting an unknown error

**Expected behavior**
To search the artist and show them songs. Actually Amber wouldn't show the song artist either so.. A weird thing is happening here

**Screenshots:**
![imagen](https://user-images.githubusercontent.com/33232977/191954570-05c33963-fadc-41b4-a8f6-16c933916ed9.png)

**System Information:**
 - Operating system: Manjaro stable
 - Strawberry Version: The latest one Versión 1.0.9

**Comment by jonaski** [comment]
It occurs when Tidal returns one or more artists, but there are no albums for the actual artist. But the artist exists because the artist appears on other albums not returned when requesting actual albums for the specific artist. Strawberry just doesn't handle that search case properly

**Comment by userofryzen** [comment]
okey, will it get any improve in any point or better to close that issue?
I understand that maybe you can have another priorities or it's habe been reported before!

**Comment by rio-codes** [comment]
Would it be possible to provide a specific error message for this case, to inform the user why there are no albums? Maybe "Your search returned an artist that does not have any releases on Tidal." or something like that? What is the response from the Tidal API?
