### ISSUE TITLE
Display curruption when using Window Blinds 11 Beta

### ISSUE THREAD

**Issue by linuxdancer** [strawberrymusicplayer/strawberry#1048]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When using Window Blinds 11 Beta there is corruption in the album and control sections of the display.  ***Please Note I was Able to Fix By Using a different style**

**To Reproduce**
Run program and play music file.

**Expected behavior**
No display issue.

**Screenshots:**
Added

![2022-10-01_07-22](https://user-images.githubusercontent.com/98826704/193411784-a1095387-5162-4461-880f-76a09e8928e9.png)

**System Information:**
 - Operating system:  Win1  
 - Strawberry Version: 1.09

**Additional context**
This is the 1st Beta version of Window Blinds 11 software by Stardock.  So not sure if the problem may be on there side, I just wanted to make you aware of issue.  You can get around issue by choosing not to skin it, but would be nice if it worked.  I always like the fact that Strawberry allowed you to use system themes and not force you into it's own skin.

**Comment by linuxdancer** [comment]
*Please Note I was Able to Fix By Using a different style.  

![image](https://user-images.githubusercontent.com/98826704/193412090-47813a26-2da9-4da9-bce1-c6592f3d5967.png)

**Comment by jonaski** [comment]
Sorry, I can't help you with this, Window Blinds 11 is commercial software. I suggest to report it to them.
