### ISSUE TITLE
Playlist column text alignment bug has returned

### ISSUE THREAD

**Issue by clementine-user** [strawberrymusicplayer/strawberry#1049]
Playlist text alignment of columns is ignored in version 1.0.8.14.g407c128f-x86_64 and later.

macOS 10.15.6, macOS 11.7, macOS 12.6

**Comment by jonaski** [comment]
Qt 6.3.1 bug.

**Comment by clementine-user** [comment]
That's interesting because strawberry-1.0.7.6.g538c759f-x86_64 was the last dev build that worked and it was built with Qt 6.3.1:

<img width="757" alt="strawberry-1 0 7 6 g538c759f-x86_64" src="https://user-images.githubusercontent.com/6315176/194774105-cebae9f6-0ddd-43b9-af81-d5786f3d8a61.png">

And strawberry-1.0.9.28.g5c8e4929-x86_64 doesn't work and it was built with Qt 6.3.1, also:

<img width="756" alt="strawberry-1 0 9 28 g5c8e4929-x86_64" src="https://user-images.githubusercontent.com/6315176/194774116-071131d6-483f-459b-ac14-a87fa6230974.png">

**Comment by jonaski** [comment]
It's because in 1.0.7 I was building Qt 6.3.1 with patches, while later I switched back to using homebrew which was still using Qt 6.3.1 unpatched, they have since upgraded to Qt 6.3.2, but it takes a bit time before GitHub CI get's the changes.

**Comment by clementine-user** [comment]
Jonas, thanks for the explanation. I shall patiently await the fix then.

**Comment by jonaski** [comment]
Works now with the latest from https://builds.strawberrymusicplayer.org/macos/
