### ISSUE TITLE
Strawberry crashes KDE Plasma

### ISSUE THREAD

**Issue by damian101** [strawberrymusicplayer/strawberry#1052]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When I start Strawberry, my desktop environment (KDE Plasma) immediately crashes, and I'm at the login screen.

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.9

**Additional context**
Removing `~/.config/strawberry` did not solve the issue. The issue started after the latest system update.

**Comment by jonaski** [comment]
Strawberry shouldn't cause KDE Plasma to crash. I suggest to report this to KDE.

**Comment by damian101** [comment]
> Strawberry shouldn't cause KDE Plasma to crash. I suggest to report this to KDE.

It's probably some Strawberry dependency causing this issue, I just noticed that starting Handbrake also causes my desktop environment to crash...
