### ISSUE TITLE
Context and playing widget disappear on song change with VLC

### ISSUE THREAD

**Issue by McUberStein** [strawberrymusicplayer/strawberry#1054]
**Describe the bug**
Whenever a song ends and another starts playing, the "Context" screen shows "No song playing". This does not happen when I manually skip the song. Switching to the next song and back fixes the issue.

**To Reproduce**
1. Open Strawberry
2. Play a song
3. Skip to last 5 seconds of song
4. Wait for song to end
5. As soon as song changes, Context screen should say "No song playing"

**Expected behavior**
Context screen should probably show lyrics of the next song whenever the current song ends.

**Screenshots:**

**System Information:**
 - Operating system: Gentoo Linux
 - Strawberry Version: 1.0.9, built with Qt 5

**Additional context**
Not a huge bug. just pretty annoying to have to skip forward and the backwards to get the lyrics back.

**Comment by jonaski** [comment]
I can reproduce this using VLC, but not with GStreamer. Are you using Strawberry with VLC?
Most likely I'll remove VLC sooner or later, no-one has shown any interest in working on it, it's there merely for historical reasons at this point.

**Comment by McUberStein** [comment]
Yes, I am using the VLC backend, forgot to mention that. I much prefer it to GStreamer, because the audio seems much smoother with VLC, and sometimes, though rarely, the audio stutters a little with GStreamer, but nothing too dramatic. I will continue using VLC as long as it's supported by Strawberry and then switch to GStreamer.

**Comment by McUberStein** [comment]
Yes, that commit fixed the issue. VLC backend works exactly like GStreamer now.

**Comment by jonaski** [comment]
Nice
