### ISSUE TITLE
qobuz not working

### ISSUE THREAD

**Issue by ScherbakovAl** [strawberrymusicplayer/strawberry#1055]
I am using ubuntu. I managed to get a suitable id to connect with qobuz. But when I try to play the track, I encounter an error:

Invalid Request Signature parameter (request_sig) (Root=1-63516c36-67f506f44445eb33092a0918) (400)

I like the "Strawberry" app. it can play sound directly. Support for qobuz is declared, but it does not work(

**Comment by ScherbakovAl** [comment]
Yes, I can search for songs and add to a playlist. Also lists of albums and songs have been updated. But updating the list of artists gets stuck. Well, an error when trying to play tracks from qobuz (
Radio and local files - work.

**Comment by ScherbakovAl** [comment]
`Is the secret 33 characters long with lowercase hexadecimal string, or is it a base64 encoded string (longer with also uppercase letters and '=')?`
where can i watch?

**Comment by jonaski** [comment]
The App secret in the Qobuz settings, it's used in "request_sig", and is probably what's failing here.
