### ISSUE TITLE
strawberry mixes samename albums of different dates/cat# in library display

### ISSUE THREAD

**Issue by mikelpr** [strawberrymusicplayer/strawberry#1056]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The library view does not separate albums with the same name but different year (and catalogue number)

**To Reproduce**
Have two "untitled" albums by one same artist.

**Expected behavior**
The library picker shows the albums separately.

**Screenshots:**
[buggy non-separation](https://imgz.org/i8AetcrB.png)
[workaround attempt that sucks anyways because it will only use one album art and I don't even know which](https://imgz.org/i7QHwmnV.png)

**System Information:**
 - Operating system: openSUSE Tumbleweed
 - Strawberry Version: 1.0.9

**Additional context**
ideally, if there's more than one album by an (album) artist, strawberry should show the catalogue number next to the title. not many people use this field but not many people have untitled releases from the same artist and for those who do it is definitely the best field for separating untitled releases, with fallback to date/year

these are the discs I'm experimenting this bug with:
https://www.discogs.com/release/21930247-XI-Untitled
https://www.discogs.com/release/5076313-XI-Untitled

**Comment by jonaski** [comment]
As far as I can tell there is no standardized catalog tag.
Albums with the same album title can be separated by using a different grouping tag for different albums, and checking the "Separate albums by grouping tag" under the advanced grouping settings.

**Comment by mikelpr** [comment]
@jonaski looking at kid3 https://github.com/KDE/kid3/search?q=FT_CatalogNumber it is the same for mp3, ogg, flac and mp4. that should be standard enough for everybody. using the grouping tag in my case did work but `CATALOGNUMBER` logic could be added and it would not hurt but help. actually, many places in the program would benefit from having CAT#, like as a playlist column
