### ISSUE TITLE
Buggy seeking

### ISSUE THREAD

**Issue by geroyche** [strawberrymusicplayer/strawberry#1057]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Seeking in flacs (it's the only format i tried...) via seek bar has a new buggy behaviour: when clicking on a position first i have a few seconds silence, while playback time increases, then playback continues and the playback time jumps back to the position that i clicked to, and then playback time jumps a few seconds forward again. I also managed to freeze Strawberry once after a few seeks, though I am not able to reproduce that consistently.
I tried a number of builds to find out when exactly the issue was introduced. See "system information" and "additional context" below.

**To Reproduce**
play a Flac, click a position on the seek bar

**Expected behavior**
Playback should immediately continue at the desired position.

**Screenshots:**

**System Information:**
 - Operating system: macOS 12.6
 - Strawberry Version: Version 1.0.10-1-gad4d0e89 down to Version 1.0.9-33-gacf10622

**Additional context**
The issue did not exist in Version 1.0.9-32-g5d4dc9c9

**Comment by jonaski** [comment]
This is probably the flac 1.4.0 - 1.4.1 bug, most likely fixed if you try the latest release from https://builds.strawberrymusicplayer.org/ as homebrew just upgraded to flac 1.4.2.

**Comment by geroyche** [comment]
confirmed as fixed.
