### ISSUE TITLE
Server does not support seeking - blocking UI, please create quick workaround

### ISSUE THREAD

**Issue by Volodymyr-13** [strawberrymusicplayer/strawberry#1058]
**Describe the bug**
I know you know: https://github.com/strawberrymusicplayer/strawberry/issues/706 and https://github.com/strawberrymusicplayer/strawberry/issues/846

**To Reproduce**
Just pause internet radio and play it a bit later.

**Expected behavior**
No UI errors, just continue - force restart playback

Really, why you can't just force restart currently playing radio and not show this error dialog? 
You have event of this, just ignore it and play music... what the problem? :) 

**System Information:**
 - Operating system: macOS 13
 - Strawberry Version: 1.0.10

**Comment by jonaski** [comment]
If you don't think it's a problem, why don't you do it?
