### ISSUE TITLE
OSD custom background color not functional

### ISSUE THREAD

**Issue by jemail99** [strawberrymusicplayer/strawberry#1064]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Setting osd background color to custom does not actually do anything. The background remains the default image (grey with wavy lines on the right).

**To Reproduce**
Choose a custom background color for the osd and apply, then OK. Observe if the osd has changed.

**Expected behavior**
The osd should show the custom color chosen as the back ground color instead of the default image

**Screenshots:**
N/A

**System Information:**
 - Operating system: openSUSE Tumbleweed with KDE plasma: 5.26.2, KDE Framework: 5.99.0, Qt Version: 5.15.6
 - Strawberry Version: 1.0.10

**Comment by jonaski** [comment]
It works here
![image](https://user-images.githubusercontent.com/10343810/199086902-f34a5362-4c02-4c22-bd12-17b6e39a6649.png)

**Comment by jemail99** [comment]
Ah, so the color only applies to the border.
What I would like is for the the whole osd to be the solid custom color chosen in the settings with no default background image.
Is that possible?

**Comment by jonaski** [comment]
You can adjust the background opacity.
