### ISSUE TITLE
Playlist order is lost after sorting

### ISSUE THREAD

**Issue by cabo40** [strawberrymusicplayer/strawberry#1068]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Playlist order is lost after clicking one of the header attributes from which to sort, since clicking the sorting field more times just changes the sorting order by that same field

**To Reproduce**
Create a playlist with a custom sort

**Expected behavior**
After clicking three consecutive times the same sorting field, it recovers the original sorting

**System Information:**
 - Operating system: 6.0.7-arch1-1 x86_64 GNU/Linux
 - Strawberry Version: Strawberry 1.0.10

**Comment by jonaski** [comment]
There is a undo button for this

**Comment by cabo40** [comment]
Sorry, thank you!

**Comment by slrslr** [comment]
> There is a undo button for this

I have not expect that the arrow would be used for sorting history. What about doing the same as OP suggested. It seems to be common habit that clicking column header sorts one way, clicking again sorts opposite and clicking 3rd restores original order (and hides the arrow on the column).
