### ISSUE TITLE
Multiple albums (similar name) get the same cover

### ISSUE THREAD

**Issue by Jellby** [strawberrymusicplayer/strawberry#1069]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I have a multi-disc album, but I have it tagged as separate albums: "Star Wars Anthology Disc 1" to "Star Wars Anthology Disc 4". I try to set different covers for each "album", and it seems to work, but when I restart Strawberry, all four of them get the last-set cover.

**To Reproduce**
The albums are in separate folders, tagged with different "album" tags, no "disc" tag.
Set different covers in the cover manager (no cover file in the folder, no cover tag in the files).
Restart Strawberry.

**Expected behavior**
Each disc should get a different cover, because there's no reason Strawberry should believe these are all the same album (except if it's trying to be smart and interpret "Disc x" in the album name as something else)

**Screenshots:**
Example tags for one file, no "disc" tag:
![Screenshot_20221110_111526](https://user-images.githubusercontent.com/7943459/201064309-58777d22-0d10-4f09-b63d-573bc1030e92.png)

All covers are set equal:
![Screenshot_20221110_111311](https://user-images.githubusercontent.com/7943459/201063863-f42bdc32-2225-489d-847c-8bf9d0410adc.png)

**System Information:**
 - Operating system: Kubuntu 22.04
 - Strawberry Version: 1.0.10

**Comment by jonaski** [comment]
This is done intentional, "disc" is removed from the album title when creating the filename hash for the cover. Since users sometimes write Disc x and the end of album title to separate album titles with multiple discs.
You should be able to workaround this by using the "Save album covers in album directory" option, or manually placing the album cover in each album directory. But you need to also delete the currently set cover, or manually removing it from ~/.local/share/strawberry/strawberry/collectionalbumcovers/

**Comment by Jellby** [comment]
That doesn't work for me though (I mean, I don't want to store covers in my music directories), and it goes against the principle of "don't touch my files" that apparently Strawberry follows.

I'd rather manually assign the same cover to multiple albums "incorrectly" labelled with "disc" than be unable to assign different covers to different albums that just happen to have the word "disc" in their name. Is the word also removed in other languages?

**Comment by jonaski** [comment]
It's only Disc or CD optionally within () or []: https://github.com/strawberrymusicplayer/strawberry/blob/f10e928106094e31d91e7a003d5a0dfb14251e4c/src/core/song.cpp#L146
I think it should be possible to create an option for this in the collection settings, but it needs to be on by default as it's been the behavior for years.

**Comment by Jellby** [comment]
I'd be OK with a per-album setting (similar to "Don't show in various artists" perhaps), or a user-modifiable setting for regexes to "remove". Looking at the source code, is "Remastered" also removed? I have a couple of albums in my collection where I have both the original and remastered version, I'll have to check the covers for those too...

**Comment by jonaski** [comment]
no, the kAlbumRemoveMisc thing is used when requesting album covers, lyrics and sending scrobbles, otherwise you most often don't get a match... It's not used to strip the cover filename
