### ISSUE TITLE
"Always on Visible Workspace" is reset by opening playlist (Cinnamon desktop)

### ISSUE THREAD

**Issue by a-torgovitsky** [strawberrymusicplayer/strawberry#1070]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The window setting "Always on Visible Workspace" is reset by opening a playlist.

**To Reproduce**
1. Open Strawberry window.
2. Right click on window bar, select radio button for "Always on Visible Workspace."
3. Open a playlist (Playlist -> Load playlist, or `ctrl + shift + o`)
4. Right click on window bar, the radio button has been reset to "Only on This Workspace." The window only exists on the current workspace, consistent with the radio.

**Expected behavior**
Opening a playlist should not affect what workspaces the window is visible on.

**Screenshots:**
N/A

**System Information:**
 - Operating system: Linux Mint 20.2 Cinnamon
 - Strawberry Version: 1.0.10

**Additional context**
N/A

**Comment by jonaski** [comment]
This sounds like a bug with the window manager or Cinnamon. Does the same thing happen if you open the load playlist dialog and just cancel?
I don't have Cinnamon to test on, but XFCE got the same options for workspaces, and there is no such issue.

**Comment by a-torgovitsky** [comment]
> Does the same thing happen if you open the load playlist dialog and just cancel?

Yes, the same thing happens if the dialog is just cancelled.
It also happens if I do "Save playlist" and a dialog opens and is cancelled.

I have not been able to replicate this in any other applications with a file open dialog.
Any particular ones I should try? Perhaps QT ones?

**Comment by jonaski** [comment]
Probably not related to the file dialog at all, just any dialog, or any window.
Try QDirStat, kate, konsole, dolphin, kid3, etc. Opening file / settings, etc.

**Comment by a-torgovitsky** [comment]
In Strawberry it does not happen if I open the Settings dialog, for example.
It also does not happen in QDirStat with any dialog I tried.

I don't have the other KDE-based applications to try (this is all Gnome-based) but I haven't been able to find any other applications where this problem arises.

**Comment by jonaski** [comment]
I don't know what KDE does, but all Strawberry does is to open a file dialog using `QFileDialog`, so wherever the bug is, it's very unlikely to be in Strawberry, I doubt the bug is in Qt either since it works for me fine with XFCE. Could be Strawberry is using some window flags or system tray icon, or something that triggers the bug.  I suggest to report the issue to Cinnamon or Linux Mint.
