### ISSUE TITLE
Relative file paths in playlist files are generated incorrectly

### ISSUE THREAD

**Issue by mrblowntobits** [strawberrymusicplayer/strawberry#1071]
- [ x ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ x ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ x ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
File paths in a playlist file are not generated correctly, if the relative path option is enabled and the playlist file is not saved into the content containing directory itself.

**To Reproduce**
1. Enable relative playlist path in settings: Tools -> Settings -> Playlist -> When saving a playlist, file paths should be -> Relative
2. Drag audio file from the collection into the playlist
3. Save playlist into another directory as where the audio file is located

**Expected behavior**
The file paths in the playlist file should be relative to the location from where the playlist file is saved.

**System Information:**
 - Operating system: Manjaro
 - Strawberry Version: 1.0.10

**Additional context**
The problem is independent of the used playlist type (m3u,xspf,...) and is already present in clementine.

I think here is the place where the bug hides:

```
QString ParserBase::URLOrFilename(const QUrl &url, const QDir &dir, const PlaylistSettingsPage::PathType path_type) {

if (!url.isLocalFile()) return url.toString();

const QString filename = url.toLocalFile();

if (path_type != PlaylistSettingsPage::PathType_Absolute && QDir::isAbsolutePath(filename)) {
const QString relative = dir.relativeFilePath(filename);

 if (!relative.startsWith("../") || path_type == PlaylistSettingsPage::PathType_Relative) {
return relative;
 }
}

return filename;

}
```

**Comment by jonaski** [comment]
Relative paths for songs saved to playlists works as expected here.
What incorrect about them? Do you have some examples for paths?
See also https://github.com/strawberrymusicplayer/strawberry/issues/955

**Comment by mrblowntobits** [comment]
The directory where all my music is located is:
`/mnt/Data/Music/`

It contains the folders Artists and Playlists for example:
```
.
├── Artists
│   └── ACDC
│       └── Back In Black
│           ├── 01 - Hells Bells.mp3
│           ├── 02 - Shoot to Thrill.mp3
│           ├── 03 - What Do You Do for Money Honey.mp3
│           ├── 04 - Givin the Dog a Bone.mp3
│           ├── 05 - Let Me Put My Love Into You.mp3
│           ├── 06 - Back In Black.mp3
│           ├── 07 - You Shook Me All Night Long.mp3
│           ├── 08 - Have a Drink on Me.mp3
│           ├── 09 - Shake a Leg.mp3
│           └── 10 - Rock and Roll Ain't Noise Pollution.mp3
└── Playlists
        └── Rock_Relative_Paths.m3u
```

But for conveniences there is a LINK called Music in my home directory to my actual music directory:
`/home/User/Music -> /mnt/Data/Music/` 

When the collection path is added in the settings it is converted into an absolute path.
So despite of configuring a path containing a link (`/home/User/Music/`) as collection path 
it is converted and used as `/mnt/Data/Music/`. No problem so far.

The problem only arises, when the relative path option is enabled and you try to save a playlist 
into a location using the linked directory (`/home/User/Music/Playlists`).

An example m3u playlist (extension changed to txt) with relative paths enabled saved into the linked directory is appended.
[Rock_Relative_Paths.txt](https://github.com/strawberrymusicplayer/strawberry/files/10031716/Rock_Relative_Paths.txt)

BTW: Saving playlists into a linked directory with absolute paths are fine. The links are resolved to
absolute locations.

**Comment by mrblowntobits** [comment]
Thank you very much for your work.

**Comment by ASRSI** [comment]
The same problem still exists when I save a playlist in a separate folder below the absolute music path.
So the problem has not been fixed to this day! This means that the playlist cannot be used on another device!

Just an example of my playlist saved in m3u format.
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 01 - Galdra.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 02 - Halloween.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 03 - Gwydion.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 04 - Wainamoinen.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 05 - Tamlin.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 06 - Neun Welten.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 07 - Lord Randal.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 08 - Innisfree.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 09 - Ran.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 10 - Baldur.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 11 - Caer.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 12 - Willow Tree.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 13 - Zeit der Raben.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 14 - Anagin.mp3
../../../../../home/robby/Musik/Musik/Faun/Pagan/Faun - Pagan - 15 - Liam.mp3

That's not a "realative path"!
It should be ‘../Faun/Pagan/Faun - Pagan - 15 - Liam.mp3’ (as example!) if it were relative to the save path of the playlist!

The dir '/home/robby/Musik/Musik' is a symlink to a nfs mount and '/home/robby/Musik' is my (local) music library path.
Strawberry V 1.1.3
