### ISSUE TITLE
Regression of #366 in 1.0.10 - Weird tab ordering when in Edit Track Information window

### ISSUE THREAD

**Issue by posita** [strawberrymusicplayer/strawberry#1075]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/).  :point_left: I haven't fully verified this because searching the forum requires registration. I'm not doing that. That being said, I'm pretty sure this is a bug.

#366 is marked as fixed and (unless I'm misreading) [released in 0.6.9](https://github.com/strawberrymusicplayer/strawberry/blob/891182637e9314cffd6cf962b00dbc9bc1550279/Changelog#L600-L612). However version 1.0.10 still exhibits similar behavior. The tab-to-next-field order does not follow the layout. Further, the comment text area field is not last, but continuing to tab once reaching that field will add tabs to the comment field, not move focus to the next field. This, by itself, is not a bug, but is aggravating when the tab order continues to be strange.

**Comment by jonaski** [comment]
The release you are pointing is 2 and 1/2 years old, it was fixed, but since then the tag editor was re-designed, and I forgot to set the tab order. Fixed now.
