### ISSUE TITLE
Unable to set Performer/Compilation tags for some files

### ISSUE THREAD

**Issue by posita** [strawberrymusicplayer/strawberry#1076]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/).  :point_left: I haven't fully verified this because searching the forum requires registration. I'm not doing that. That being said, I'm pretty sure this is a bug.

I can't quite figure out why, but editing tags on some `.m4a` (AAC) files does not register changes to the Compilation boolean flag or the Performer tag. For others, blanking the Performer tag ends up with it being populated with whatever is in the Artist field at the time of saving. I can provide (copyrighted) material via another channel for reproducing this, if helpful.

Steps to reproduce files to which this applies:

1. Edit the track information
2. Check (or uncheck) the Compilation box
3. If the Performer field is set, clear it; if it is blank, set it
4. Click save

The Compilation flag will not remain set. If the Performer field was clear and you set it, it will be blank. If the Performer field was set and you cleared it, it will be set to whatever was in the Artist field.

The above happens with 1.0.10.

**Comment by posita** [comment]
Files that can be used to reproduce this behavior with 1.0.10 can be found by reconstruction the appropriate URL from `gist.github.com ... posita ... 23d9dbe4e8439bbcaf1088812a2020cb`.

**Comment by posita** [comment]
Perhaps the bug is that the Performer tag gets populated at all (at least in the UI), but not consistently?

**Comment by jonaski** [comment]
No, it shouldn't read or write performer at all for MP4, so not sure how that happened, I can check if it's possible to implement.
Compilation read/write is fixed now https://github.com/strawberrymusicplayer/strawberry/commit/67b503da445a2a814b368639204e26452105524c
It was not reading it at all, it was writing it, but incorrectly.

**Comment by jonaski** [comment]
Performer isn't supported for MP4. I also checked Kid3 and Amarok, they don't have it either.
What audio format was the songs that you had the issue with performer on?

**Comment by posita** [comment]
Upon further examination, you're right: Performer is only persisted with MP3 files, _**not**_ M4A/AAC files. I'm not sure if it's intentional that blanking/clearing the Performer field for MP3s should mean that it should take on the value of the Artist field, though. Is that intentional?

**Comment by jonaski** [comment]
TPE1 "Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group" is artist and TOPE "Original artist(s)/performer(s)" is performer.
However, Strawberry is incorrectly using TPE1, also for performer if TOPE is missing. I'm pretty sure that is something I've done unintentional while reading the ID3v2 speficiations as they call what everyone else calls artist performer, which is confusing. I'll fix that.
Most formats have performer, ie Vorbis comment tags used for ogg/flac, etc, the exception is MP4, AIFF and ASF. We should just disable the performer field for formats that don't support it.

**Comment by posita** [comment]
> We should just disable the performer field for formats that don't support it.

Would it be helpful if I filed a separate issue to track that? If so, in what form would be best?
