### ISSUE TITLE
Organizing files without tags results in data loss (i.e., the original file name, which was the only way to identify its contents)

### ISSUE THREAD

**Issue by posita** [strawberrymusicplayer/strawberry#1077]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/).  :point_left: I haven't fully verified this because searching the forum requires registration. I'm not doing that. That being said, this feels like a sharp enough edge case to warrant treating it as a bug.

When organizing files without any tagged information (many WAV files fall into this category), they are renamed to `<top-level-folder>/-.<ext>` with conflicts being disambiguated as `-(n).<ext>` (where `n` is an integer). This results in loss of the original filename. Normally, that is intended, but in this case, because there are no tags, the filename is really the _**only**_ way to get a hint as to its contents. The files show up in the collection under `Unknown` both before and after being organized, but are listed by their new filenames after being renamed, leaving the user to listen to each and then try to remember each old filename (or name it anew).

I think there are (at least) two options worth considering:

* Only allow organizing files for those with at least one tag; or
* Organizing files without any tags as if they had an Artist of `Unknown` and a Title of `<original-file-name-without-the-extension>`

**Comment by jonaski** [comment]
The preview should already show how the files will be named, so the user needs to check that and not continue if it's wrong. Files (data) is never lost anyway since it always makes sure that the file doesn't exist, and appends a number if a file already exists with that name.

**Comment by posita** [comment]
> The preview should already show how the files will be named, so the user needs to check that and not continue if it's wrong.

I don't know if it's reasonable to check everything where one is, for example, re-organizing an entire collection of 10k songs. Putting the burden on the user to inspect every line or be left to realize after the fact that the above case is "as expected" is pretty harsh. Is there a reason why neither of my suggestions appeal to you? I feel like either would be friendlier alternatives to the existing behavior.

> Files (data) is never lost anyway since it always makes sure that the file doesn't exist, and appends a number if a file already exists with that name.

My assertion is that file names **_are_** data. The importance and relevance of that data is elevated where such files don't also contain metadata. If that weren't the case, then users would merely save all of their files in a single folder with serial numbers instead of descriptive names. But users don't act that way. They encode information in the organization of their files in the form of folder names, hierarchies, and file names.  In this case, the file name is destroyed with little notice to the user. Sure, the bytes in the file are preserved, but the data encoded in the user-elected organization is lost.
