### ISSUE TITLE
`Shuffle tracks in this album` doesn't always play all tracks in the album when multiple albums occupy playlist with `Don't repeat`

### ISSUE THREAD

**Issue by posita** [strawberrymusicplayer/strawberry#1078]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**To Reproduce**
1. Load a playlist with multiple albums (at least a dozen or so).
2. Sort ascending by Track
3. Sort ascending by Album
4. Select `Playlist` -> `Shuffle mode` -> `Shuffle tracks in this album`
5. Select `Playlist` -> `Repeat mode` -> `Don't repeat`
6. Double click on an interior (not first or last) track in an album with more than three tracks
7. After it starts playing, click `Next track` a few times

**Expected behavior**
One should be able to use `Previous track` and `Next track` to navigate all songs in that album, and playback should stop only after every song has been navigated in the shuffled order. However, often, after only a few attempts, playback will stop without visiting all songs in the album.

**System Information:**
 - Operating system: Linux
 - Strawberry Version: Version 1.0.10

**Comment by jonaski** [comment]
I can't reproduce this, tested with several albums and it plays each track.
Maybe it's skipping a song because of a error?

**Comment by posita** [comment]
I can no longer repro this either with the latest release. I will reopen if I see this again.
