### ISSUE TITLE
Strawberry stops to play songs, sometimes

### ISSUE THREAD

**Issue by qarmin** [strawberrymusicplayer/strawberry#1080]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Sometimes randomly music stop to play.
Play button is still pressed, but time is not going forward.
Clicking Play/Pause not fix issue, but selecting again song and rerunning it works fine.

Logs shows that this may be driver/audio device issue, but still I think that this situation should be handled by app(of course if possible)
```
pulseaudio[3243]: ALSA woke us up to write new data to the device, but there was actually nothing to write.
pulseaudio[3243]: Most likely this is a bug in the ALSA driver 'snd_usb_audio'. Please report this issue to the ALSA developers.
pulseaudio[3243]: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
```
Not 100% sure, but probably same problem happened with pipewire on Ubuntu 22.10 

**To Reproduce**
Just listen songs for few hour, then problem should be visible(sometimes)

**Expected behavior**
Songs just should always play properly

**Screenshots:**

[Screencast from 02.12.2022 08:49:11.webm](https://user-images.githubusercontent.com/41945903/205242860-4444112d-a27e-4a10-a7f8-e37ecd041d78.webm)

**System Information:**
 - Operating system: Ubuntu 22.04
 - Strawberry Version: 1.0.10 but happens since I remember in older versions at least half/year ago

**Comment by glaubersm** [comment]
This happens sometimes with Strawberry 1.0.10 on my Arch Linux.
But on my system it only occurs after seeking a track repeatedly by clicking on the seek bar of Strawberry.

**Comment by jonaski** [comment]
Not much I can do about this. Most likely driver, or a PulseAudio or pipewire issue.

**Comment by glaubersm** [comment]
In my case it's an issue with pipewire. I see this output in the journal log when the playback stops:
```
dez 04 12:44:49 Arch-PC pipewire-pulse[1812]: mod.zeroconf-publish: error id:45 seq:3413 res:-2 (Arquivo ou diretório inexistente): enum params id:16 (Spa:Enum:ParamId:ProcessLatency) failed
dez 04 12:45:31 Arch-PC pipewire-pulse[1812]: mod.protocol-pulse: client 0x55561afe9a80 [strawberry]: stream 0x5556196e87a0 OVERFLOW channel:0
dez 04 12:45:31 Arch-PC pipewire-pulse[1812]: mod.protocol-pulse: client 0x55561afe9a80 [strawberry]: stream 0x5556196e87a0 OVERFLOW channel:0
dez 04 12:45:31 Arch-PC pipewire-pulse[1812]: mod.protocol-pulse: client 0x55561afe9a80 [strawberry]: stream 0x5556196e87a0 OVERFLOW channel:0
dez 04 12:45:31 Arch-PC pipewire-pulse[1812]: mod.protocol-pulse: client 0x55561afe9a80 [strawberry]: stream 0x5556196e87a0 OVERFLOW channel:0
dez 04 12:45:31 Arch-PC pipewire-pulse[1812]: mod.protocol-pulse: client 0x55561afe9a80 [strawberry]: stream 0x5556196e87a0 OVERFLOW channel:0
dez 04 12:45:40 Arch-PC pipewire-pulse[1812]: mod.zeroconf-publish: error id:45 seq:3466 res:-2 (Arquivo ou diretório inexistente): enum params id:16 (Spa:Enum:ParamId:ProcessLatency) failed

```
