### ISSUE TITLE
Strawberry on KDE Plasma: volume adjusted via Media Player applet is not continuously updated in the OSD

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1083]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When we adjust the volume via Media Player applet (mpris), KDE Plasma shows
the volume level in an OSD that appears in the middle of the screen.
If Strawberry is the player and we adjust the volume quickly from 0% to 100%
or vice-versa, the volume level shown in the OSD is not continuously updated according to.

**To Reproduce**
1. use Strawberry in a linux distribution running KDE Plasma DE
2. play a song with Strawberry
3. hover over the Media Player applet that appears in the system tray during playback
4. adjust the volume of Strawberry by scrolling up/down once quickly - an OSD appears in the middle of the screen and the percentage of the volume on it reflects the volume change as expected
5. now change the volume of Strawberry from 0% to 100% or vice-versa by scrolling several times

**Expected behavior**
the volume percentage is not updated continuously while we change the volume
in the last step. The volume shown in the OSD only changes when we scroll for the first time and then when the volume reaches 100% or 0% (the OSD says 'Strawberry Muted')

**Screenshots:**

**System Information:**
 - Operating system: neon unstable, based on Ubuntu 22.04
 - Strawberry Version: strawberry_1.0.10-42-gb2073df3

**Additional context**
I think this is a Strawberry bug because I can't reproduce with VLC player installed on the same system.

**Comment by jonaski** [comment]
I don't understand what's wrong, Strawberry is sending the MPRIS2 volume notification correctly after each volume change.
Do you know if it has ever worked with the KDE Media Player applet?

**Comment by jonaski** [comment]
I see Strawberry is properly sending the MPRIS2 volume notifications continuously so I don't know why the applet isn't updating the volume in the OSD for Strawberry, while it does for programs.
I think someone familiar with the KDE Media Player applet needs to look into this.
Closing this as I can't spend more time on it, and there are no other contributors.

**Comment by glaubersm** [comment]
I have noticed something:
1. play something with another player controllable by the widget
2. stop playback but do not close the player
3. play something with Strawberry
4. click on the widget: notice the tabs on top - star, Strawberry and another player

If the 'Star' tab is selected, I can reproduce the bug. If Strawberry tab is selected instead,  I'm unable to reproduce the bug.

**Comment by jonaski** [comment]
Strange, thanks for the investigation, I will have another look.

**Comment by jonaski** [comment]
Same here, if "auto" is selected in the media player applet, then the notification is buggy, but when specifically selecting Strawberry as player, it works.
I can actually reproduce similar bug with Pragha now, updating of the volume is inconsistent when auto is selected, but perfectly fine when Pragha is selected. If only Pragha is open, it's buggy similar to auto.
I think this bug might be in the KDE media player applet.
Can you open a KDE bug report about this?

**Comment by glaubersm** [comment]
Reported: https://bugs.kde.org/show_bug.cgi?id=463759

**Comment by jonaski** [comment]
I assume this bug is in KDE, so closing this issue for now. I subscribed to the KDE issue too, I'll reopen this if any information is given that Strawberry is doing something wrong here.
