### ISSUE TITLE
The icon of some tabs in the sibebar overlaps the label if 'Use system theme icons' is checked in the settings

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1084]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The icon of some tabs in the sibebar overlaps the label if 'Use system theme icons' is checked in the settings.

**To Reproduce**
1. check 'Use system theme icons' in 'Appearance' section of the settings
2. set the sidebar to Plain mode
3. restart Strawberry

**Expected behavior**
the icon should not overlap the label

**Screenshots:**
![icons](https://user-images.githubusercontent.com/15967631/206718809-3e8f9ff8-0280-4a00-bcc6-e3d9cd8ffe85.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.10

**Additional context**
My Strawberry is built against Qt6.

**Comment by jonaski** [comment]
@glaubersm What icon set are these icons from?
