### ISSUE TITLE
Crash at the end of a track if the file behind the next track has been removed / doesn't exist 

### ISSUE THREAD

**Issue by dontfwiththestream** [strawberrymusicplayer/strawberry#1090]
- [ X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry crashes at the end of track when next track in playlist doesn't exist, song doesn't finish playback

**To Reproduce**
move/delete a track on your hdd/sdd/whatever thats in your playlist, attempt to play the preceding track

**Expected behavior**
Strawberry should finish playing out the track

**System Information:**
 - Operating system: Void linux
 - Strawberry Version: 1.0.9

**Additional context**
appears to be the same issue as upstream, https://github.com/clementine-player/Clementine/issues/7233

**Comment by jonaski** [comment]
I can't reproduce this issue. Since almost everything related to the engine code is rewritten and different, it's as likely it might be a different crash altogether. Can you do a backtrace with gdb?

I can into this: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1683 while debugging on Windows.
But I'm not getting a crash on Linux.

**Comment by jonaski** [comment]
If it's the same crash as Clementine, try with 6d05bb2de5c91e5a7fff57ece26b6fcf35c9181b

**Comment by jonaski** [comment]
Please report back if this is still an issue and I'll reopen.
