### ISSUE TITLE
"Organize files" : curly braces added to path if "album" tag is between braces

### ISSUE THREAD

**Issue by breversa** [strawberrymusicplayer/strawberry#1091]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When organizing files, using the "{%album}" tag adds braces to path

**To Reproduce**
1. Load a file in the playlist
2. Right-click on it and select "Organize files"
3. In "Naming options", use the "{%album}" tag (between braces)
4. Check the preview and see that braces have been added around the album name

Other tags do *not* display this behaviour.

**Expected behavior**
No brace should appear in the path

**Scr
![Capture d’écran du 2023-01-02 19-20-11](https://user-images.githubusercontent.com/2071276/210267531-207a1cf6-e844-4960-8b3d-d58a625b9679.png)
eenshots:**

**System Information:**
 - Operating system: Linux Mint 21.1
 - Strawberry Version: 1.0.11

**Comment by jonaski** [comment]
It's not specific to the album variable, it splits the filename from the path by the last slash, so it happens to whatever variable is the last. I made some changes a while back to avoid non unique filenames, so I split the parsing so it does path and filename separately, that created this bug
