### ISSUE TITLE
Cannot save playlists anymore

### ISSUE THREAD

**Issue by dave-theunsub** [strawberrymusicplayer/strawberry#1092]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
As of 1.0.12 (and maybe 1.0.11) I cannot save playlists anymore.  This seems like a bug.

**To Reproduce**
Either right-click on the playlist tab, ctrl-S, or Playlist->Save playlist.

**Expected behavior**
Saves playlists like it used to do.

**Screenshots:**

**System Information:**
 - Operating system:  Fedora
 - Strawberry Version: 1.0.12

**Additional context**
If I run it by command line, this pops up:  
01:23:24.412 WARN  unknown                          QFSFileEngine::open: No file name specified

I have definitely given it a name. This has always worked in the past.  Did not see anything related in the existing issues.

**Comment by PeterBBBBB** [comment]
I'm seeing the same issue on Debian.
It was OK in 1.0.10. Problem starts in 1.0.11

**Comment by PeterWenger** [comment]
The same issue on ubuntu 22.04. I cant save a new playlist. Hack create an empty playlist with any browser like test.xspf and then fill in a createt playlist. But it is not possible to save the createt playlist direct in strawberry. Problem starts in 1.0.11 and ist also in 1.0.12

**Comment by jonaski** [comment]
Saving playlists using absolute paths works, but not relative if the file doesn't exist.

**Comment by JoelOl751** [comment]
Can't save any playlists. Well I managed to save one, but every other locks Strawberry up solid, I tried deleting that one playlist and resaving but this didn't work. Need to kill Strawbeery and restart.
