### ISSUE TITLE
Sidebar icons discrepancy after update to 1.0.11

### ISSUE THREAD

**Issue by garuffalo** [strawberrymusicplayer/strawberry#1093]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Starting with version 1.0.11, sidebar icons no longer honor Qt5 Settings (using Qt version 5.9.5). Sidebar now using default Strawberry icons. All other icons continue to use Mint-Y-Aqua, selected in Qt5 Settings. Version 1.0.12 behavior is the same.

**To Reproduce**
Switching from "Icons on top" view to other views, e.g., "Large sidebar" also showed default icons. Tried switching to other icon sets in Qt5 settings and sidebar icons refused to change.

**Expected behavior**
Sidebar should honor selection in Qt5 Settings, as it did in versions 1.0.10 and previous.

**Screenshots:**
![strawberry_icons](https://user-images.githubusercontent.com/28717740/210410163-af24a1de-ab36-4298-b5cc-b761d95de7ca.png)

**System Information:**
 - Linux Mint 19.3 Cinnamon
 - Strawberry Version: 1.0.12

**Additional context**
I understand there are icon issues with Qt 6, but on my older system, using Qt 5, icon selection has worked perfectly using Qt5 Settings.

**Comment by jonaski** [comment]
I removed use of system icons in the tabbar because of #1084.

**Comment by garuffalo** [comment]
OK, thank you. Sorry, I should have dug a little deeper before posting. So, one man's gain is another man's loss, I guess. I have to say, I'm not crazy about the default icons; they look very dated and clunky. And I loved the look of the Mint-Y icons.

If this is something that can be fixed in the future, I'd appreciate it. For now, maybe I'll try something with a custom icon set. I think that would still work with Qt 5, if I'm not mistaken. Still love Strawberry, though!!!

**Comment by jonaski** [comment]
I added it back, I can't reproduce any issues myself.
