### ISSUE TITLE
Can not save playlist

### ISSUE THREAD

**Issue by eedfre** [strawberrymusicplayer/strawberry#1094]
- [ YES] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ YES] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ YES] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug:**

Saving the playlist **does not save a file with the specified filename** (or any other file) with my/the change from version 1.0.10 to 1.0.12. 
- Problem is with *.xspf and *.mu3 file types tested & reproduced
- Running strawberry in the terminal gives following warning:
_"WARN  unknown                          QFSFileEngine::open: No file name specified"_
- With version 1.0.10 saving the playlist in a *.xspf file was no problem.
- Downgrade to 1.0.11 does not remove the problem.

**System Information:**
 - Operating system: Kubuntu 22.04
 - Strawberry Version: 1.0.12
 - Filesystem: ext4 (for storage place for the playlist, OS, strawberry), audio files are stored on nfs4

Thanks in advance for the support !

**Comment by jonaski** [comment]
See #1092. Try the latest from https://builds.strawberrymusicplayer.org/

**Comment by eedfre** [comment]
Thanks, with latest version strawberry_1.0.12-10-gdb55f314-jammy_amd64.deb the problem is solved for me.
The issue is the same like #1092
