### ISSUE TITLE
Nothing happens when clicking on Playlist -> Add directory

### ISSUE THREAD

**Issue by ReIaxo** [strawberrymusicplayer/strawberry#1096]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
There is a menu entry "Playlist -> Add directory..." (Have german version installed, so english naming is only a guess). In german version it is called "Playliste -> Ordner hinzufügen ..."
Nevertheless, when i click on it, open directory dialog opens. When I select a directory and click open, nothing happens.

**To Reproduce**
see above

**Expected behavior**

- I expect, that all playlists in the chosen directory will be added to the favorite playlists maybe opened as a tab and maybe addid grouped in a directory. (Best option for me)
- Or maybe only open the playlists from the directory as tabs?
- Or at least add a directory to the favorite playlist view (No value for me)

**Screenshots:**
Not needed.

**System Information:**
 - Operating system: Ubuntu kinetic kudu
 - Strawberry Version: 1.0.12

**Additional context**
Please ask if you need more context.

**Comment by jonaski** [comment]
This is for adding all songs in a directory to to the current playlist, not playlist files.
