### ISSUE TITLE
Program can't handle CUE files with non-latin symbols

### ISSUE THREAD

**Issue by Antiwhore** [strawberrymusicplayer/strawberry#1098]
Hello!
I have a bug for you to fix.

**Describe the bug**
Despite the presence of russian translation the problem is unable to handle CUE files with russian symbols. If the name of the file is in russian, it doesn't fetch it when scanning library. And if I change the name of the CUE and the file that it points to to english, it fetches it, but the names of album and songs are shown in interface as black diamonds with question marks.

**To Reproduce**
Add a CUE and audio file with russian symbols to the library folder.

**Expected behavior**
The same as for CUEs with latin symbols.

**Screenshots:**
![Screenshot_20230108_132400](https://user-images.githubusercontent.com/121800962/211191066-8d856369-b17f-440c-a0f3-70b940917bcb.png)

**System Information:**
Linux (Debian 11 - based)
Strawberry Version: 1.0.11

**Additional context**
I haven't tried other languages, but I suspect the same would happen with any non-latin symbols (greek for example).
Single files (without CUEs attached to them) are handled fine.

**Comment by jonaski** [comment]
What local locale settings do you have? What encoding are the files in?
See also #931

**Comment by Antiwhore** [comment]
As for locale, I have separate sections in desktop environment settings for language and formats (of dates etc). The former is set to american english (strange) and the latter us set to ru_RU.
As for encoding, file -i says "charset=iso-8859-1". This is strange because names of single files encoded not in UTF-8 were shown in wrong symbols, but not diamonds.

**Comment by Antiwhore** [comment]
I checked again through a text editor and it says "cp1251". I think file -i lied to me.

**Comment by jonaski** [comment]
Strawberry assumes UTF-8, so the easiest is to just convert the files to UTF-8.

**Comment by PeterBBBBB** [comment]
Files can be converted using iconv, which is in the libc-bin package.

**Comment by jonaski** [comment]
I added detection of encoding using https://doc.qt.io/qt-6/qstringconverter.html#encodingForData commit 02f2b8b6f032399382f0be57887c5c681bc1c3b7, it's only available with Qt 6, I'm not sure how well it works though, I did not get it to detect ISO-8859 or windows-1252, only UTF.

**Comment by Antiwhore** [comment]
> Files can be converted using iconv, which is in the libc-bin package.

Yes, I've already done so and now the list is properly shown. But now another problem emerged - I'll describe it in another issue.

> I added detection of encoding using https://doc.qt.io/qt-6/qstringconverter.html#encodingForData commit [02f2b8b](https://github.com/strawberrymusicplayer/strawberry/commit/02f2b8b6f032399382f0be57887c5c681bc1c3b7), it's only available with Qt 6, I'm not sure how well it works though, I did not get it to detect ISO-8859 or windows-1252, only UTF.

So now it presumably can read CUEs with another encodings?

**Comment by jonaski** [comment]
> So now it presumably can read CUEs with another encodings?
Looking at the Qt source code, it looks like it currently only supports detecting different UTF encodings like UTF-8, UTF-16 and UTF-32.
This isn't an easy thing and almost everything is UTF-8 nowadays anyway, in the 5 years Strawberry has been available you are the only one that have reported this.
We could possibly use ICU directly (I have not looked much into it) to detect other encodings too, but that should not take any priority, there are too many other things to do.
