### ISSUE TITLE
Duplicate items for each song in the CUE

### ISSUE THREAD

**Issue by Antiwhore** [strawberrymusicplayer/strawberry#1099]
Hello again!
This is the continuation of issue #1098.

**Describe the bug**
Each song listed in the CUE file is displayed in the interface twice.

**To Reproduce**
Open the attached CUE file and look at the album in the interface.

**Expected behavior**
Each song is displayed once.

**Screenshots:**
![Screenshot_20230109_203043](https://user-images.githubusercontent.com/121800962/211375085-b3cc8325-058a-4084-86ae-b3c903727f64.png)

**System Information:**
 - Operating system: Linux
 - Strawberry Version: 1.0.11

**Additional context**
The CUE file: 
[Браво - Мода.zip](https://github.com/strawberrymusicplayer/strawberry/files/10375697/-.zip)

**Comment by jonaski** [comment]
I can't reproduce any duplicates here. Are you sure that you don't have more than one file?

**Comment by Antiwhore** [comment]
Absolutely. I've also tried a full rescan - it doesn't help.
Back when it still couldn't see this file, I tried to make the program discover it by adding its direct parent folder to the library in addition to the general folder where all music resides (the former is the child of the latter) - maybe this matters.

**Comment by jonaski** [comment]
That will create duplicate songs, if you have added 2 directories where one of them is the parent of the same directory.
So you should remove the directory that overlaps the other and it should resolve itself.

**Comment by jonaski** [comment]
I could do it if I worked on Strawberry full time, doubt I will get enough sponsoring for that, and I got too many other things that needs to be done.
Happy to give edit access to the Wiki for anyone interested.
