### ISSUE TITLE
 Error: pa_stream_writable_size() failed: Connection terminated

### ISSUE THREAD

**Issue by garuffalo** [strawberrymusicplayer/strawberry#1102]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
After update to Version 1.0.13, Strawberry occasionally stops playing with audio glitches and this error message:

pa_stream_writable_size() failed: Connection terminated

The only difference between the error descriptions is the number following the word "pipeline".

**To Reproduce**
Just play music for awhile. Seems fairly random.

**Expected behavior**
Music should play, interrupted.

**Screenshots:**
![strawberry_error](https://user-images.githubusercontent.com/28717740/211612485-9256dfee-646c-4bb9-ae1b-f2a9bb3bd7a4.png)
![strawberry_error_2](https://user-images.githubusercontent.com/28717740/211612491-7e750d5c-0b10-481d-afa8-9df16fa5b4cf.png)

**System Information:**
 - Operating system: Linux Mint 19.3 Cinnamon
 - Strawberry Version: 1.0.13

**Additional context**
Audio output is through a USB connected Audioquest Dragonfly 1.5 DAC.
Strawberry app stays open during these events; doesn't crash and close. Just the music stops playing.

**Comment by jonaski** [comment]
I don't think this issue is related to the new version, seems like an PulseAudio issue, solution seem to be to deleted configuration:
https://forums.linuxmint.com/viewtopic.php?t=278639

**Comment by garuffalo** [comment]
Thank you. Perhaps it was just a coincidence. But I had not seen it before and it occurred just after the update, so I thought it might be related. I deleted the files per the suggestions in the forum, and will test the results.

**Comment by garuffalo** [comment]
Nope...  It just happened again. I have switched to ALSA in the backend settings and will try that. However, when I do that, only Strawberry has audio. Other apps don't have audio.

**Comment by garuffalo** [comment]
Now my other apps are supporting audio (still using ALSA in Strawberry). I don't know why it was just Strawberry a few minutes ago.

**Comment by garuffalo** [comment]
Looks like when I have ALSA selected as Output - AND - the Dragonfly Black 1.5 DAC selected as Device, I can only have audio with one app at a time. If I set Device to "Automatically select", then all apps have audio.

**Comment by jonaski** [comment]
That's if you are using hw/hwplug, if you select pcm, it uses dmix and you will be able to play different applications simultaneously

**Comment by garuffalo** [comment]
Ahh, I see. Thank you. Any reason to use Pulseaudio instead of ALSA in Strawberry? Seems as if default settings use Pulseaudio, by way of "Wrapper audio sink for automatically detected audio sink."

**Comment by jonaski** [comment]
> Ahh, I see. Thank you. Any reason to use Pulseaudio instead of ALSA in Strawberry? Seems as if default settings use Pulseaudio, by way of "Wrapper audio sink for automatically detected audio sink."

It picks PulseAudio first when its available, because if you have PulseAudio running, that's where you configure the sound. In that case outputting to ALSA using the hw setting will of course block PulseAudio which is a bad idea. I don't think it is a problem when using the pcm device strings, but I'm not all that experienced with PulseAudio.
I have never used PulseAudio for anything on Linux, first thing I uninstall when I install my distro. Sometimes I have tested it for a day, but I always run into an issue and uninstall it again.
Anyway, closing this issue as it's seems to be a PulseAudio issue.
