### ISSUE TITLE
Weird "seek" function behavior in Subsonic mode

### ISSUE THREAD

**Issue by AlexKurisu** [strawberrymusicplayer/strawberry#1103]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Seeking in Subsonic mode behaves very weirdly. If you click the seek bar, then the song will start to play seconds or minutes before/after the place you expect it to start playing at.

**To Reproduce**
1) Connect Strawberry to a Subsonic server (I used Navidrome)
2) Switch to Subsonic mode
3) Play any song
4) Try to use the seek function

**Expected behavior**
The song must start playing right at the place it's expected to start, not before or after

**Screenshots:**
![image](https://user-images.githubusercontent.com/60626727/211623123-5d28c695-e11a-4337-b646-4a383d915c95.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.13

**Additional context**
Subsonic server used: Navidrome v0.48.0

**Comment by cproensa** [comment]
I also have navidrome 0.48, and haven't experienced that issue
is transcoding enabled?

**Comment by AlexKurisu** [comment]
> is transcoding enabled?No, not for the format that i use (Ogg Vorbis with -q9 quality)

**Comment by jonaski** [comment]
Seeking works fine here with AirSonic, and I know there are many users using the subsonic functionality in Strawberry.
I'm not sure where the issue it, but at least this isn't a Strawberry bug, I'm guessing either a Navidrome, codec or gstreamer issue, I suggest to try reporting it to Navidrome and see if they can help.
