### ISSUE TITLE
Drag-and-dropping a directory with an album in single file + cuesheet format to a playlist only adds the first track

### ISSUE THREAD

**Issue by xfzv** [strawberrymusicplayer/strawberry#1105]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

When drag-and-dropping a directory which contains an album in single file + cuesheet format, only the first track of the album is added to the playlist. It occurs with the following extensions I've tried: APE, FLAC, WAV, WV.

Drag-and-dropping the .cuesheet or the music files adds all the tracks, as expected.

**To Reproduce**
1. From a file manager, enter a directory with an album in single file + cuesheet format
3. Drag the .cuesheet file to the current Strawberry playlist: all tracks are added to the playlist :heavy_check_mark: 
4. Drag the album file to the current Strawberry playlist: all tracks are added to the playlist :heavy_check_mark:
5. Go back to the previous directory
6. Drag the album directory to the current Strawberry playlist: only the first track of the album is added to the playlist :x:

**Expected behavior**
Drag-and-dropping the album directory to the current Strawberry playlist adds all the tracks to it, just like when drag-and-dropping the .cuesheet or the album files

**Screenshots:**

https://user-images.githubusercontent.com/78810647/211905611-b0838e05-d4a6-4053-a79f-ca917ef57f90.mp4

**System Information:**
 - Operating system: Linux
 - Strawberry Version: 1.0.13

**Comment by jonaski** [comment]
The playlist doesn't have scanning, it's the collection that handles that, so it doesn't parse directories for CUE sheets. I suggest to use the collection instead.
