### ISSUE TITLE
Strawberry does not respect the bitrate settings when transcoding to .mp3

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1108]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When I transcode a .flac file to .mp3, Strawberry generates a .mp3 file whose bitrate is 280 Kbps
despite Strawberry is set to constant 320 Kbps bitrate.

**To Reproduce**
1. open Strawberry settings and click on 'Transcoding' in the left side
2. click on 'MP3' tab, select 'Optimize for bitrate", set 'Bitrate' to '320' and check 'Constant bitrate'
3. apply the settings by clicking on 'OK' button
4. click on 'Tools' menu and choose 'Transcode music'
5. add a .flac file and set 'Audio format' to 'MP3 (.mp3)'
6. click on 'Start transcoding' button

**Expected behavior**
A .mp3 file with constant 320 Kbps bitrate should be generated

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.13

**Comment by jonaski** [comment]
It works here. What does the log in the details button say?

```
Thu Jan 12 19:37:41 2023: Transcoding 1 files using 8 threads
Thu Jan 12 19:37:41 2023: Starting /home/jonas/Test-Music/FLAC/Test1/Acoustic Strawbs/Full Bloom/01 - Acoustic Strawbs - Full Bloom - Autumn.flac
Thu Jan 12 19:37:41 2023: Using 'lamemp3enc' (rank 256)
Thu Jan 12 19:37:41 2023: Adding xingmux and id3v2mux to the pipeline
Thu Jan 12 19:37:41 2023: Setting lamemp3enc property: target = 1
Thu Jan 12 19:37:41 2023: Setting lamemp3enc property: bitrate = 320
Thu Jan 12 19:37:41 2023: Setting lamemp3enc property: cbr = true
Thu Jan 12 19:37:41 2023: Setting lamemp3enc property: quality = 9.99
Thu Jan 12 19:37:41 2023: Setting lamemp3enc property: encoding-engine-quality = 2
Thu Jan 12 19:37:41 2023: Setting lamemp3enc property: mono = false
Thu Jan 12 19:37:58 2023: Successfully written /home/jonas/Test-Music/FLAC/Test1/Acoustic Strawbs/Full Bloom/01 - Acoustic Strawbs - Full Bloom - Autumn.mp3
```

**Comment by glaubersm** [comment]
The output says that the bitrate is 320. But when I add the generated .mp3 file to a playlist, the 'Bitrate' column of Strawberry says that the bitrate is 280 Kbps.

```
Thu Jan 12 15:46:40 2023: Transcoding 1 files using 2 threads
Thu Jan 12 15:46:40 2023: Starting /home/stalker/Músicas/06 - Take Up Thy Stethoscope And Walk.flac
Thu Jan 12 15:46:40 2023: Using 'lamemp3enc' (rank 256)
Thu Jan 12 15:46:40 2023: Adding xingmux and id3v2mux to the pipeline
Thu Jan 12 15:46:40 2023: Setting lamemp3enc property: target = 1
Thu Jan 12 15:46:40 2023: Setting lamemp3enc property: bitrate = 320
Thu Jan 12 15:46:40 2023: Setting lamemp3enc property: cbr = true
Thu Jan 12 15:46:40 2023: Setting lamemp3enc property: quality = 9.99
Thu Jan 12 15:46:40 2023: Setting lamemp3enc property: encoding-engine-quality = 2
Thu Jan 12 15:46:40 2023: Setting lamemp3enc property: mono = false
Thu Jan 12 15:46:49 2023: Successfully written /home/stalker/Músicas/06 - Take Up Thy Stethoscope And Walk.mp3
```

**Comment by jonaski** [comment]
280 sounds like it could be using variable bitrate, the cbr does not take affect.
Is it consistently doing the same each time? Is it 280 for all songs?

**Comment by glaubersm** [comment]
I have just transcoded some .flac files for test purposes, the bitrate varies: 286, 290, 288, 293, 285, 289, 284.
Audacious player reports variable bitrate in its status bar when I play these .mp3 files with it.

**Comment by jonaski** [comment]
Can you re-check with 1.0.14 if it has the same issue, I did some changes to the data type conversions when setting properties.

**Comment by glaubersm** [comment]
I can't reproduce with 1.0.14. :)

**Comment by jonaski** [comment]
OK. I assume I fixed it then. Thanks.
