### ISSUE TITLE
Strawberry permanently occupies volume control widget, prevents other media players from showing up

### ISSUE THREAD

**Issue by articice** [strawberrymusicplayer/strawberry#1109]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry doesn't play well with other players and permanently occupies Unity's volume control.

**To Reproduce**
Install Spotify app, Tidal web app or play media from browser.

**Expected behavior**
When Strawberry is not running or playing, it shouldn't prevent other clients from showing up in Unity volume control.
It should allow multiple players to show up in the control.

**Screenshots:**
![image](https://user-images.githubusercontent.com/6135211/212103201-116104b0-570f-4a1e-ab1a-514edd756fbc.png)

**System Information:**
 - Operating system: Ubuntu 20.04 LTS (Unity desktop)
 - Strawberry Version: 1.0.10

**Additional context**
Uninstalling Strawberry doesn't fix the problem.

**Comment by jonaski** [comment]
> **Expected behavior** When Strawberry is not running or playing, it shouldn't prevent other clients from showing up in Unity volume control. It should allow multiple players to show up in the control.

How can Strawberry be preventing other programs from appearing?
What is Strawberry doing wrong?

> **Additional context** Uninstalling Strawberry doesn't fix the problem.

Then why is it a Strawberry bug?
