### ISSUE TITLE
Rename "Various artists" -> "Various Artists"

### ISSUE THREAD

**Issue by MyXelf** [strawberrymusicplayer/strawberry#1112]
Hi:

After commiting #1082, I guess the category `Various artists` could be renamed to `Various Artists` (with capital "A"). IMHO this would make the UI more consistent.

**Screenshots:**
![strawberry---various-artists---20230115-150450](https://user-images.githubusercontent.com/4689660/212564363-83675d24-3e7b-47fc-8028-c0471e24988d.png)

**System Information:**
 - Operating system: KDE Neon 22.04
 - Strawberry Version: 1.0.14-jammy

HTH!

**Comment by jonaski** [comment]
> Hi:
> 
> After commiting #1082, I guess the category `Various artists` could be renamed to `Various Artists` (with capital "A"). IMHO this would make the UI more consistent.
> 
Consistent with what exactly? The commit has nothing to do with how various artists is displayed.
It's been like this for 5 years, if I rename it now, someone will complain.
