### ISSUE TITLE
Strawberry crashed after clicking on the button used to play the previous track twice

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1114]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I clicked on the button used to play the previous track twice and Strawberry crashed. I can't reproduce this crash consistently.

**To Reproduce**
1. play a song
2. click on the button used to play the previous track twice

**Expected behavior**
no crash

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.14

**Additional context**
the crash log generated with gdb:  
[backtrace.txt](https://github.com/strawberrymusicplayer/strawberry/files/10458499/backtrace.txt)

**Comment by jonaski** [comment]
Assuming that the crash is in thread 1, it's missing debug symbols (1-5), I think this will be very difficult to figure out without them. Perhaps this is strawberry debug symbols missing? Maybe check with Arch why they are missing.

```
Thread 1 (Thread 0x7fcf2f6b0100 (LWP 6940)):
#0  g_type_check_instance_cast (type_instance=0x7fcf0c2c1300, iface_type=0x50) at ../glib/gobject/gtype.c:4127
#1  0x000055d2e1306c1a in  ()
#2  0x000055d2e1040fc7 in  ()
#3  0x000055d2e12fa0cf in  ()
#4  0x000055d2e107bb2e in  ()
#5  0x000055d2e1077c04 in  ()
#6  0x00007fcf41180413 in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7ffc65178770, r=0x55d2e38cd500, this=0x55d2e43cb010, this=<optimized out>, r=<optimized out>, a=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.4.2/src/corelib/kernel/qobjectdefs_impl.h:363
```

**Comment by glaubersm** [comment]
Feel free to close. I have rebuilt Strawberry with debug symbols and I will update this report if the crash to occur again.

**Comment by jonaski** [comment]
This looks likely to be to be the same bug as #1123, except #1123 contains the debug symbols, so closing this.
