### ISSUE TITLE
[FR] Limit dynamic playlist to size/length

### ISSUE THREAD

**Issue by Offerel** [strawberrymusicplayer/strawberry#1117]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 

**Describe the bug**
Can you please add a option to limit a dynamic playlist not only in title count, but also in overall filesize (for example 10GB) or as an alternative whole playtime of the dynamic playlist (for example 12 hours)?

**Comment by jonaski** [comment]
I can't do that
