### ISSUE TITLE
A metadata edited inline is unexpectedly applied when I type something after pressing backspace key

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1121]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
A metadata edited inline is unexpectedly applied when I type something after pressing
backspace key.

**To Reproduce**
1. enable 'Enable song metadata inline edition with click' option in the 'Playlist' section of Strawberry settings
2. add some songs to your playlist
3. click on a metadata (artist, album, title) to edit it
4. delete the last character by pressing backspace key
5. type a character

**Expected behavior**
the metadata should remain in edit mode until the user applies the edited tag explicitly by pressing enter key

**Screenshots:**

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.14

**Additional context**

**Comment by glaubersm** [comment]
Another way to reproduce:
Click on the artist metadata and type "A-".

The edited metadata is applied after you type "-"

**Comment by jonaski** [comment]
I can't reproduce this, maybe you have some shortcuts configured that triggers keys?

**Comment by glaubersm** [comment]
I can only reproduce on Wayland session of KDE Plasma. Also tested on X11 session of KDE Plasma (on the same computer) and Wayland session of Gnome (on another computer also running Arch and the same version of Strawberry) and I'm unable to reproduce on them.

For some reason now I can only reproduce with the steps from my previous comment. The bug seems intermittent with the original steps.

**Comment by jonaski** [comment]
I can't reproduce this, I've tested on 4 different distros with KDE Plasma, two with Wayland. Since it only occurs with wayland it seem to indicate that the issue is not in Strawberry. Perhaps something taking focus from Strawberry.
