### ISSUE TITLE
Strawberry stealing internet bandwidth

### ISSUE THREAD

**Issue by gianlucapettinello** [strawberrymusicplayer/strawberry#1122]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When I start Strawberrry the internet connection becomes very slow as if there is something stealing all the band. After some seconds I close Strawberry the network restart working normally
**To Reproduce**
Open Strawberry

**Expected behavior**
No bandwidth reduction

**Screenshots:**

**System Information:**
 - Operating system: Archlinux
 - Strawberry Version: 1.0.14

**Additional context**

**Comment by jonaski** [comment]
When testing here with KSysGuard, Strawberry does not use any bandwidth when idle, it uses a few KB's at the start of each song for the lyrics and scrobbling. Also, testing with speedtest-cli, it gives me the same result with or without strawberry running.
This seems like a very strange claim. I suggest to give some more information providing this.

**Comment by jonaski** [comment]
Closing this as no more information is given and it does not seem likely to be a Strawberry bug.
