### ISSUE TITLE
[windows] Is there a way to use Strawberry with a dark theme in windows?

### ISSUE THREAD

**Issue by UndeadKernel** [strawberrymusicplayer/strawberry#1125]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
This is not a bug, but a question. Is there a way to use a dark theme in windows? Before the appearance pallete settings were removed, I was able to color the main playlist window with dark colors. This did the trick. Now that the pallete setting is gone, is there a way to use a proper dark theme in windows?

**System Information:**
 - Operating system: Windows
 - Strawberry Version: 1.0.14

**Comment by Lartza** [comment]
Via `qputenv("QT_QPA_PLATFORM", "windows:darkmode=2");` you can get a rudimentary dark mode working, that doesn't too bad (Fusion pictured)
![strawberry_CV03eQDtrc](https://user-images.githubusercontent.com/305616/215404691-279e3033-ed50-4f80-9d92-bb37e33f1f8b.png)

Someone just needs to take the time to properly make maybe a configurable option, or find a better way (custom qt style plugin?)

**Comment by UndeadKernel** [comment]
@Lartza, what you suggest is something that would have to be added at the source code level correct? I don't think windows environmental variables can be used for that purpose, or am I not right?

**Comment by Lartza** [comment]
Does have some bugs so maybe not usable until Qt 6.5 or some changes... 
![strawberry_pnuwhbrVy9](https://user-images.githubusercontent.com/305616/215632359-254c651a-3537-413b-9522-af355c4fe84f.png)

**Comment by jonaski** [comment]
Use the forum for questions (https://forum.strawberrymusicplayer.org/)
I might look into a dark mode setting when Qt 6.5 is released.

**Comment by jonaski** [comment]
The new version 1.2.22 released now has an option for dark mode under the appearance settings, you can also configure each individual color on the interface.
