### ISSUE TITLE
Space bar does not play/pause playback

### ISSUE THREAD

**Issue by wheelerlaw** [strawberrymusicplayer/strawberry#1126]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When the app is in focus (and focus isn't on a text box or some other situation like that) playback should play/pause when I press the space bar. 

I tried to workaround this by manually setting the shortcut key in the application setting, but then whenever I pressed the space bar when the app was not in focus, the shortcut key would still be activated. 

**To Reproduce**
1. Start playing some music. 
2. With the app in focus, press the space bar. 
3. Playback should pause (but doesn't). 
4. With the app in focus, press the space bar again. 
5. Playback should resume (but doesn't).

Trying the workaround:
1. Go to "Tools" -> "Settings" -> "User interface" -> "Global Shortcuts"
2. Set "Play/Pause" action to the space bar. 
3. With the app in focus, begin playback. 
4. Open up some other application, and inside that application, press the space bar. 
5. Playback will pause (but shouldn't).
6. In the other application, press the space bar again. 
7. Playback will resume (but shouldn't).

**System Information:**
 - Operating system: Fedora 37
 - Strawberry Version: 1.0.10

**Additional context**
I'm willing to see if I can try my hand at fixing this bug myself.

**Comment by jonaski** [comment]
Spacebar for play/pause works fine here without configuring global shortcuts. I dont think this is Strawberry bug, perhaps something is grabbing the space keypress.
Is this wayland or X11?

**Comment by wheelerlaw** [comment]
X11

**Comment by jonaski** [comment]
I can't reproduce any issues with space for play/pause on any system, and I've never heard anyone else has any issues, so this is most likely a system related, or configuration issue. If you want to debug it yourself you put a breakpoint in `PlaylistView::keyPressEvent`, and see what happens here: https://github.com/strawberrymusicplayer/strawberry/blob/143f72cf6b01b41660cda231f14070c0dc4e8de9/src/playlist/playlistview.cpp#L705

**Comment by mtfurlan** [comment]
I was inconsistently having the issue where I would tab to strawberry, press space, and sometimes nothing would happen in whatever version of strawberry is packaged by the debian repos.

I built the `master` branch, and figured out that the `PlaylistView::keyPressEvent` function is only called when the last thing that was clicked on was the playlist view.
So if I clicked on something in collection to add it to the playlist, space doesn't play/pause.

Interestingly, if I click on "Context", space will still trigger pause/play but with the `MainWindow::keyPressEvent` function.
None of the other things in the sidebar trigger that.

**Comment by Offlein** [comment]
I recently started using Strawberry and I have this issue. I wonder if it's Wayland related? I can only reliably play/pause with spacebar when my last click was in the scrubber.

If I had last clicked into the playlist view, space will pause playing but will not resume it. Last-clicking in the Collection view means spacebar does nothing. :shrug: 

FWIW, clicks into the play/pause button itself do not seem to affect the above. It still goes by what was "last clicked". So I am just leaving my player with last clicks in the scrubber for ease of access.

@jonaski I'm sorry that I don't have the ability to debug with a breakpoint at this time, and I wasn't sure whether to open a new issue or comment here, apologies if I'm not being fully helpful.

**Comment by shade-belisar** [comment]
I also have this issue under Nobara 43 (KDE Plasma 6.6.4, Wayland). I did not have it in Linux Mint (various iterations), so I'd count that as potentially Wayland related. I'm generally a bit confused by the shortcuts, because there seem to be only global shortcuts, I don't see any config option for in-app shortcuts. Does strawberry simply not have any?
