### ISSUE TITLE
Flatpak Refresh of Strawberry 1.0.14 fails with server 404

### ISSUE THREAD

**Issue by jphands** [strawberrymusicplayer/strawberry#1127]
- [ X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Trying to do a routine refresh of Strawberry from Flathub on KDE Neon aborts with the server saying the x86_64/stable app is not found, and throwing a 404 error.

**To Reproduce**
Run an update from KDE Neon using the Discover tool.

**Expected behavior**
App should update.

**Screenshots:**
![strawberry-update-error](https://user-images.githubusercontent.com/80360209/216131867-8187f43c-990b-4aff-aeeb-e75fb9903c03.png)

**System Information:**
 - Operating system:
KDE neon 5.26
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 5.15.0-58-generic (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 47.0 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: ASUS

 - Strawberry Version:
 1.0.14
**Additional context**

**Comment by reno-a** [comment]
Error also on Fedora.
Error: While pulling app/org.strawberrymusicplayer.strawberry/x86_64/stable from remote flathub: Server returned HTTP 404

**Comment by jonaski** [comment]
This isn't a Strawberry bug, but a flatpak issue.

**Comment by jphands** [comment]
> 

I'm sure it's a Flatpak issue, but that doesn't help us get an update.  As a software engineering manager, this kind of answer says that devs don't care about users...and if one of my deployment routes stopped my code getting to users, I'd be unhappy.  Looks like it's back to Clementine or Pragha for me.
