### ISSUE TITLE
strawberry --play-playlist <name> only working when playlist is open

### ISSUE THREAD

**Issue by wintermute-cell** [strawberrymusicplayer/strawberry#1128]
**Describe the bug**
Using the command line argument `--play-playlist` (or `-i`), a playlist can be started, but only if the playlist already exists in a tab, and not when the playlist is only saved under the "Playlists"  view.

**To Reproduce**
1) Create a new playlist, named `<name_of_playlist>`.
2) Right click the playlists tab, and press "Star playlist".
3) Close the playlists tab, or restart strawberry.
4) Run `strawberry -i <name_of_playlist>` in a terminal.

**Expected behavior**
Playlist is loaded and begins playing after running `strawberry -i <name_of_playlist>`.

**Comment by jonaski** [comment]
You can only play from an open playlist. This command line option was added in #608. It has to automatically open the playlist if it's closed if that was supposed to work.
