### ISSUE TITLE
How to handle multiple albumartist / artist

### ISSUE THREAD

**Issue by Offerel** [strawberrymusicplayer/strawberry#1129]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 

**Describe the bug**
This is more a general question as a bug or feature request. But how can i handle a song/album where i have multiple artists or albumartists? For example I have a lot of DJ mixes. Most are 1 file where multiple songs are mixed together. As such, I set albumartist to the name of the DJ and artist to "Various". In opposite, I have some compilations. There i set albumartist to "Various" and song artist to the real artist name. But sometimes, I have DJ Mixes where more than 1 DJ does the mix. We as DJ called this "PingPong". Most of the time there are 2 DJ's but sometimes more. Is there a way to arrange the same title/mix/album to more than 1 DJ without multiple copys of the song? If is sort the Library by albumartist, so that i have the same song sorted in for every DJ?

I'm not sure, but if i understand correctly, this is what ID3 2.4 gives, that i can add more than one albumartist or artist to a song.

**Comment by jonaski** [comment]
Use the forum for questions (https://forum.strawberrymusicplayer.org/)
