### ISSUE TITLE
Does not install  strawberry  under ubuntu 22.10

### ISSUE THREAD

**Issue by HDInfautre** [strawberrymusicplayer/strawberry#1131]
- [X ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

I have a failure message (lack of dependency) when installing strawberry_1.0.14-jammy_amd64.deb
Is there anything I can do?

**To Reproduce**
install with ubuntu 22.10

**Comment by PeterBBBBB** [comment]
You need to install the package dependencies first.
Try 
dpkg --info strawberry_1.0.14-jammy_amd64.deb
to list them.

**Comment by HDInfautre** [comment]
Thanks for the quick answer
I tried the directory where strawberry_1.0.14-jammy_amd64.deb is located
I get an error message with the command;
`cd Téléchargements
rv@Mot:~/Téléchargements$ dpkg --info fraise_1.0.14-jammy_amd64.deb 
dpkg-deb: erreur: impossible de lire l'archive « fraise_1.0.14-jammy_amd64.deb »: Aucun fichier ou dossier de ce type
`

Can you take into account that I am not a geek
If you could put in the help what to do? 
where I have to wait for the next release?

**Comment by millette** [comment]
Bonjour @HDInfautre 

fraise? ;-) Try literally:

```sh
dpkg --info strawberry_1.0.14-jammy_amd64.deb
```

**Comment by jonaski** [comment]
22.10 is kinetic, not jammy. So if you are using 22.10 you should use the kinetic package.
Closing this as this isn't a strawberry bug, I suggest to seek further help in Ubuntu forums.

**Comment by jonaski** [comment]
There is.: https://files.strawberrymusicplayer.org/strawberry_1.0.15-jammy_amd64.deb
