### ISSUE TITLE
Segmentation fault when playing directly to A2DP device(s)

### ISSUE THREAD

**Issue by ThoriumTextile** [strawberrymusicplayer/strawberry#1133]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry dumps a core after setting the audio output to a bluetooth device (headset, in my case).
https://gist.github.com/ThoriumTextile/845ed17547a50fb0f51a6a5da0d9110a

**To Reproduce**

1. Launch Strawberry.
2. Go to Settings.
3. Change the preferred audio output to a bluetooth device (headphones in my case).
4. Play any audio file.
5. Strawberry closes forcefully.

**Expected behavior**
Successful playback without any crashing.

**System Information:**
 - Operating system: OpenSUSE Tumbleweed
 - Strawberry Version: 1.0.14

**Comment by jonaski** [comment]
Can you do a GDB backtrace: https://wiki.strawberrymusicplayer.org/wiki/Backtrace

**Comment by ThoriumTextile** [comment]
> Can you do a GDB backtrace: https://wiki.strawberrymusicplayer.org/wiki/Backtrace

https://gist.github.com/ThoriumTextile/64b3ed3a580f36d23f82b15a17906fac
