### ISSUE TITLE
Icon Theme not respected, even if explicitly set by qt6ct

### ISSUE THREAD

**Issue by ThoriumTextile** [strawberrymusicplayer/strawberry#1134]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Icon Theme not respected, [even if explicitly set by qt6ct](https://wiki.strawberrymusicplayer.org/wiki/FAQ#Strawberry_does_not_respect_Qt_style,_KDE_theme_or_icons_on_Linux.)

**To Reproduce**
1. Launch Strawberry.
2. Go to Settings.
3. Set theme to qt6ct (preconfigured to use the system icon theme)
4. Confirm and restart
5. Icons remain unchanged.

**Expected behavior**
Icons updated to reflect and match the system theme (papirus-dark in my case)

**System Information:**
 - Operating system: OpenSUSE Tumbleweed with KDE Plasma
 - Strawberry Version: 1.0.14

**Comment by jonaski** [comment]
That icon theme probably do not have png icons, so you need the SVG imageformat plugin (libQt6Svg6).
In any case, this isn't a strawberry bug.
