### ISSUE TITLE
ReplayGain settings are completely ignored

### ISSUE THREAD

**Issue by ThoriumTextile** [strawberrymusicplayer/strawberry#1135]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Changing (or even enabling at all) the preferred RG settings changes nothing (with the proper metadata written, of course); audio remains the same (i've even tried setting the slider to the max).

**To Reproduce**
1. Go to Settings
2. Enable ReplayGain
3. Change the preferred gain
4. Play a track
5. Volume/normalization remains the same

**Expected behavior**
RG settings to be applied upon playback

**Screenshots:**
N/A

**System Information:**
 - Operating system: OpenSUSE Tumbleweed with KDE Plasma
 - Strawberry Version: 1.0.14 (native, not flatpak)

**Comment by jonaski** [comment]
What audio format is this? What type of audio tags?

**Comment by ThoriumTextile** [comment]
> What audio format is this? What type of audio tags?

FLAC. ReplayGain tags.

**Comment by jonaski** [comment]
Valid tags are those listed here: https://wiki.xiph.org/VorbisComment#Replay_Gain

Whats the output of `metaflac --list <filename>`

What's the output of when playing the specific file in strawberry:

`GST_DEBUG=2,rg*:6 strawberry`


It works perfectly fine here, ie.: I tested setting REPLAYGAIN_TRACK_PEAK to -42, and I can see and hear that this is picked up. Fallback gain also works.

**Comment by ThoriumTextile** [comment]
> Valid tags are those listed here: https://wiki.xiph.org/VorbisComment#Replay_Gain
> 
> Whats the output of `metaflac --list <filename>`

https://gist.github.com/ThoriumTextile/090932ea6d2936c07e990a2f62a5ecf4

> What's the output on the terminal when playing the specific file, if you start strawberry from the terminal with the following command:
> 
> `GST_DEBUG=2,rg*:6 strawberry`

https://gist.github.com/ThoriumTextile/481d5647b3cb6bfa48f0f1d0a88f19a3

**Comment by jonaski** [comment]
The debug output isn't showing anything related to replaygain at all. If replaygain is actually enabled in strawberry backend settings, then this seem like something is broken with the gstreamer installation.

Does this command show info about replaygain?

`GST_DEBUG=2,rg*:6 gst-launch-1.0 filesrc location=testfile.flac ! queue2 ! flacparse ! flacdec ! audioresample ! audioconvert ! rgvolume ! rglimiter ! audioconvert ! alsasink device=hw:0,0`

Replace testfile.flac with the actual file, and 0,0 with a existing device listed in `aplay -l`.

If replaygain is working, it should show something like this:

If replaygain tags are found:

`0:00:02.316580300 26011 0x5601b58fbe40 INFO                rgvolume gstrgvolume.c:616:gst_rg_volume_update_gain:<rgvolume0> result gain is -40,00 dB (0,010000), matching target`

If no tags are found:

`0:00:00.012354011 25413 0x55768fde4630 DEBUG               rgvolume gstrgvolume.c:647:gst_rg_volume_determine_gain:<rgvolume0> using fallback gain`

**Comment by ThoriumTextile** [comment]
> The debug output isn't showing anything related to replaygain at all. If replaygain is actually enabled in strawberry backend settings, then this seem like something is broken with the gstreamer installation.
> 
> Does this command show info about replaygain?
> 
> `GST_DEBUG=2,rg*:6 gst-launch-1.0 filesrc location=testfile.flac ! queue2 ! flacparse ! flacdec ! audioresample ! audioconvert ! rgvolume ! rglimiter ! audioconvert ! alsasink device=hw:0,0`
> 
> Replace testfile.flac with the actual file, and 0,0 with a existing device listed in `aplay -l`.
> 
> If replaygain is working, it should show something like this:
> 
> If replaygain tags are found:
> 
> `0:00:02.316580300 26011 0x5601b58fbe40 INFO rgvolume gstrgvolume.c:616:gst_rg_volume_update_gain:<rgvolume0> result gain is -40,00 dB (0,010000), matching target`

Can confirm; here's the output I got:
https://gist.github.com/ThoriumTextile/1c9a893dc225f3fa5024e3c64cec2b04

FWIW, I switched to the Flatpak version for less overall trouble with possible missing or conflicting libraries.
The FP version works fine.

**Comment by jonaski** [comment]
Very strange. Try deleting `~/.cache/gstreamer-1.0/registry.x86_64.bin`, and check that you have gstreamer installed from the official openSUSE OSS repos, maybe try reinstalling the packages.

**Comment by ThoriumTextile** [comment]
> Very strange. Try deleting `~/.cache/gstreamer-1.0/registry.x86_64.bin`, and check that you have gstreamer installed from the official openSUSE OSS repos, maybe try reinstalling the packages.

Clearing the cache seems to have done the trick.
