### ISSUE TITLE
"Organize Files" causing Title to be duplicated if a '.' character appears in certain parts of the Naming Options

### ISSUE THREAD

**Issue by manofsticks** [strawberrymusicplayer/strawberry#1136]
Not sure when this started but I believe it's recent.

See example below: First screenshot has a '.' character after Track, and in the Preview you can see the title is duplicated

![image](https://user-images.githubusercontent.com/5444847/217666407-21466d16-9d1c-450c-b646-19aaca8aeb2b.png)

Second screenshot does not have a '.', and the preview does not duplicate the title

![image](https://user-images.githubusercontent.com/5444847/217666608-42eb0f11-ce53-48d1-ad09-05f580bb742d.png)

It does also write the files like this; not just a "preview" bug. 

**System Information:**
 - Operating system: Arch
 - Strawberry Version: 1.0.14 (though the bug appeared before this I believe)

**Comment by manofsticks** [comment]
Looking at recent files I've organized, the earliest I'm seeing this appear is Jan 9th 2023. I do not have any files prior to January which have this. So that narrows down which version this started on.

**Comment by manofsticks** [comment]
I'm guessing it's somehow related to commit [7c0c9fc](https://github.com/strawberrymusicplayer/strawberry/commit/7c0c9fccdbcfb7bc1f5b48446a45e666e1aa18f5)

My original assumption was something along the lines of "a . character makes the Unique_Filename bool incorrectly return false", and therefor it sets it to the string it normally would plus the filename, but I renamed a file to 'test' and tried it and it still did the "title" twice. 

![image](https://user-images.githubusercontent.com/5444847/217968578-1dbd56c9-12b6-4be7-a552-3261367dd89d.png)

**Comment by manofsticks** [comment]
Looking further, I think possibly related to commit [[bd94503](https://github.com/strawberrymusicplayer/strawberry/commit/bd945039f14201b4ca61931d4b2a38ddcc1d039e)](https://github.com/strawberrymusicplayer/strawberry/commit/7e3cb3de89deeab85dd93476b9345d849ec61e9f). 

I'm not very familiar with c++ so apologies for being a little all over the place with my comments, but partially documenting for myself to learn. 

I saw the following

`   if (path.right(1) != '/') {
          filepath.append('/');
        }`

And noticed that when I add a slash after the '.' character, the behavior works as expected. 

![image](https://user-images.githubusercontent.com/5444847/217977967-52e693ba-1c88-4e8d-a125-daf5ae289209.png)

**Comment by manofsticks** [comment]
I see the following as well

``` // Fix any parts of the path that start with dots.
  QStringList parts_old = filepath.split("/");
  QStringList parts_new;
  for (int i = 0; i < parts_old.count(); ++i) {
    QString part = parts_old[i];
    for (int j = 0; j < kInvalidPrefixCharactersCount; ++j) {
      if (part.startsWith(kInvalidPrefixCharacters[j])) {
        part = part.remove(0, 1);
        break;
      }
    }
    part = part.trimmed();
    parts_new.append(part);
  }
  filepath = parts_new.join("/");```


If I'm understanding this right, it breaks apart the parts of the filepath, and removes any parts that are prefixed with a '.' (expecting it to be the file extension I assume); in this case however because I have the '.' as a prefix to %title, it removes the title entirely. 

Then later, we have

```
    QFileInfo fileinfo(filepath);
    if (fileinfo.completeBaseName().isEmpty()) {
      // Avoid having empty filenames, or filenames with extension only: in this case, keep the original filename.
      // We remove the extension from "filename" if it exists, as song.basefilename() also contains the extension.
      QString path = fileinfo.path();
      filepath.clear();
      if (!path.isEmpty()) {
        filepath.append(path);
        if (path.right(1) != '/') {
          filepath.append('/');
        }
      }
      filepath.append(song.basefilename());
    }
  }
```

We're now checking if the basename is empty (which it is because we just cleared it). We clear the filepath, and append the filepath (Which has the track), and then append basefilename (which has the track.mp3 at the end).

**Comment by manofsticks** [comment]
Having tracks with '.' characters within it also causes funky behavior; also some oddities if you were (for some reason) trying to organize your files into a hidden path in Linux.

![image](https://user-images.githubusercontent.com/5444847/217983154-a92cc1d8-5c05-4841-b121-d24dcc13c3af.png)

Since the main goal of this (to my understanding) is to remove file extensions, I think we could get away with only doing this where the final invalid prefix character is found?

**Comment by jonaski** [comment]
The problem was that I was using "completeSuffix" instead of "suffix", https://doc.qt.io/qt-6/qfileinfo.html#completeSuffix so it was taking everything after the first dot as extension, but I was also using completeBaseName, https://doc.qt.io/qt-6/qfileinfo.html#completeBaseName, so it that's why the filename was duplicated. Fixed now.
