### ISSUE TITLE
Most Irritating - intermittent errors in the audio interface are stopping audio playing for good

### ISSUE THREAD

**Issue by uvwild** [strawberrymusicplayer/strawberry#1137]
I have set my strawberry player to always playing.
Bu also I have a setup with some _aged_  cables. So sometimes, there is a hickup when I touch the cables and the connection is interrupted for a moment.

Of course, the player stops the audio interface when there is no connection.

But it shows a MODAL error window and does not try again!

I have to close the window and press play.

This is very irritating and not necessary because it would be totally sufficient to 

- log the error
- retry the audio interface after xxx msec

Which would be a very much better behaviour for a music player which has a setting to keep on playing under all circumstances ;)

If somebody points me to the class handling the audio interfaces i could fix it myself, 
but my focus is currently on catching the deployment logs of a failed pod when installing a helm chart.

Thank you

**Comment by jonaski** [comment]
> 
> Which would be a very much better behaviour for a music player which has a setting to keep on playing under all circumstances ;)
> 

I guess that's your opinion. Error messages are there for a reason.

> If somebody points me to the class handling the audio interfaces i could fix it myself, but my focus is currently on catching the deployment logs of a failed pod when installing a helm chart.
> 
GstEnginePipeline

> Thank you
