### ISSUE TITLE
App not been added into Now Playing

### ISSUE THREAD

**Issue by Volodymyr-13** [strawberrymusicplayer/strawberry#1138]
- [x ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
App not been added into Now Playing.

**To Reproduce**
Run app, play some music, notice app missing from Now Playing.

**Expected behavior**
App presented with current track name in Now Playing

**Screenshots:**
Play music in Strawberry: 
<img width="307" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/219644030-7e85c143-0c0c-4110-b57c-1be850a3e5a2.png">

**System Information:**
 - Operating system: Ventura 13.2
 - Strawberry Version: 1.0.14

**Additional context**

VLC for example, adds this if playing: 

<img width="308" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/219644199-f7f06788-c938-4bac-a770-2cebe4bc0a61.png">

**Comment by jonaski** [comment]
This is MPNowPlayingInfoCenter (https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter?language=objc), Strawberry does not have this.
Very unlikely that this will be added unless someone volunteers to do it.
It's possible to copy the class from VLC and modify it for Strawberry, it's here: https://code.videolan.org/videolan/vlc/-/blob/master/modules/gui/macosx/os-integration/VLCRemoteControlService.m

**Comment by Volodymyr-13** [comment]
It's tough, just like that closed.. maybe someone someday improves this..
