### ISSUE TITLE
Output filename pattern preferences missing

### ISSUE THREAD

**Issue by Xorgeo** [strawberrymusicplayer/strawberry#1139]
I would like the output filename set to include the following:
\<album> / \<track> - \<title>
\<artist> / \<album> / \<track> - <title>

It would be best if the output filename format could be customized as a part of the General settings setup.

**Comment by jonaski** [comment]
I have no idea what "output filename format" you are talking about here. I assume you opened this issue in the wrong repo?

**Comment by Xorgeo** [comment]
You were exactly correct.  I don't know why or how I made the mistake and posted the issue for strawberry by mistake.
Sorry
