### ISSUE TITLE
App doesn't remember/restores it's previous position and window size

### ISSUE THREAD

**Issue by Volodymyr-13** [strawberrymusicplayer/strawberry#1141]
- [x ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Just doesn't save/restore window size/pos.

**To Reproduce**
Run app, change window size/position. Close app. Open it again. App just placed with default size in the center of the screen. 

**Expected behavior**
Window position restored as was before app close.

**Screenshots:**

**System Information:**
 - Operating system: Ventura 13.2
 - Strawberry Version: 1.0.14

**Comment by jonaski** [comment]
This probably means that Strawberry is crashing on exit before it reaches the function that saves the window position.
You need to do a backtrace to see where it crashes: https://wiki.strawberrymusicplayer.org/wiki/Backtrace
For me, saving/restoring window position works fine both on Linux, Windows and macOS BigSur x86_64.
Probably worth to mention also that the dmg provided might not work reliable on arm based machines, it's for Intel x86_64.

**Comment by Volodymyr-13** [comment]
I have MacBook Pro M1 2021... maybe someone can test this on the latest macOS, but not some 3y old big sur?

**Comment by jonaski** [comment]
The crash probably has something to do with the Rosetta compatibility layer, I don't think it's very stable, and we should not support M1 macs at all unless we have contributors to support that.
But my guess is that it would work if you build strawberry on a M1 mac according to the instructions : https://wiki.strawberrymusicplayer.org/wiki/Compile_macOS_using_homebrew
If it still crashes then strawberry needs to be compiled and debugged by someone with a M1 mac.
Either that or live with the problem as it is using the x86_64 dmg release.
Unfortunately I can only give limited support for macOS, as is written both on the website and the README in the repository. I can only fix problems that can be be reproduced on a Intel x86_64 based mac.
There are no other contributors active so not much point in keeping issues open for something that I can't fix anyway.
