### ISSUE TITLE
Music transfer to iPod corrupt the iTunes DB

### ISSUE THREAD

**Issue by vnourdin** [strawberrymusicplayer/strawberry#1143]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Transferring songs to my iPod Classic works, but once unmounted, the iPod say it has zero song (corrupted database from what I understand).

**To Reproduce**
* [Windows] format the iPod (tried vFAT and ntfs)
* [Windows] reset from iTunes
* [Windows] sync some songs from iTunes (to init the db, but same result without)
* [Linux] sync some songs from Strawberry
* => The iPod say it has no song or any content, but songs are seen from Strawberry

**Expected behavior**
The iPod see songs as if they come from iTunes.

**System Information:**
 - Operating system: Arch 6.1.12-arch1-1 with Wayland
 - Strawberry Version: 1.0.14-2

**Comment by vnourdin** [comment]
I tested and have the same problem with Rhythmbox, so it probably comes from libgpod.
It is fixed by running rePear, but it is not perfect (breaks some albums, need a second read of every file, ...)

**Comment by vnourdin** [comment]
This is really sad news !
Mine is a 6th generation iPod (first "classic", 2007), you’re probably right about the source of the problem.
I haven't worked with C for a really long time, I don't feel confident digging that stuff alone, but I'm willing to help if there are some other people interested.

**Comment by elliotwesoff** [comment]
My 6th gen got corrupted :(

**Comment by oliverpool** [comment]
I am late to the party, but I think I found a workaround/fix!! Maybe this report can help to find a proper fix.

I first looked at [repear](https://repear.sourceforge.net/), converted the python2 code to python3 and could see that the checksum for the database wasn't correct.

So I adjusted the python tool to write the correct checksum: the library was then recovered and readable by my iPod!

---

Then I dived into https://github.com/strawberrymusicplayer/strawberry-libgpod and compiled it locally (was relatively easy, given my lack of experience with C and CMake).

I adjusted the various tests and was able to gather that:
- the resulting checksum is the same as repear
- the library could not get proper device information (no serial id and no model number)
- the device information is required to properly compute the checksum
- **the device information can be written to the `iPod_Control/Device/SysInfo` text file like this:**
```
FirewireGuid: 000A27001XXXXXXX
ModelNumStr: MB754
```
 🕵️  You can find the `ModelNumStr` under Settings > Information > 3rd screen.
For the `FirewireGuid`, look at the properties of the device or the logs of `strawberry --verbose`, in reads `Device added: "Udisks2/000A27001XXXXXXX/Apple/iPod` at some point.

---

With the proper file written, quit and restart strawberry, modify the library on your device (add or remove a song). Safely eject the device and everything should work! (I even have the album covers).

@jonaski thank you sooo much for this software!

**Comment by bedlingt0n** [comment]
> With the proper file written, quit and restart strawberry, modify the library on your device (add or remove a song). Safely eject the device and everything should work! (I even have the album covers).
> 

I just tried your approach and just adding the file has worked perfectly. Thank you so much for your detective work and providing this workaround ❤️
