### ISSUE TITLE
Compilations do not appear in the collection

### ISSUE THREAD

**Issue by Sonickyle27** [strawberrymusicplayer/strawberry#1144]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Any music I have that has the "Compilation" tag set to `1` does not appear in the collection in Strawberry.
This is noticeable for Compilation albums that have been downloaded with iTunes, as they come tagged with the "Compilation" tag set on them.

**To Reproduce**
In the Collection, set the Group By settings to be the following:

- First Level: Album
- Second Level: Disc
- Third Level: None
- Separate albums by groping tag: disabled

Then, right click any album and click "Edit track information...". Tick the Compilation box and save the changes.

The album in the Collection view will then lose its album art and become inacessible. If you perform a full collection scan, the album will disappear entirely.

**Expected behavior**
Compilation albums should appear alongside all other albums.

**Screenshots:**
This is an example of an album that I see this issue with. If I tick the "Compilation" tickbox, the files are saved successfully with the tag set to `1`, but in Strawberry they become inaccessible with a blank album entry
![image](https://user-images.githubusercontent.com/4775038/221424120-745cdd83-4bc2-4d2f-8616-a78b2951d512.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.14

**Comment by jonaski** [comment]
This bug is already fixed, see #1140

**Comment by Sonickyle27** [comment]
Great thank you!
