### ISSUE TITLE
Album missing from collection

### ISSUE THREAD

**Issue by monochromec** [strawberrymusicplayer/strawberry#1145]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
An album is not detected in the collection although the corresponding mp3 files  are correctly tagged / do contain the correct metadata.
**To Reproduce**
1) Add folder containing an album to collection
2) Perform a full collection re-scan.
3) Album not detected

**Expected behavior**
Album would be inserted under the corresponding artist in the collection overview.

**Screenshots:**

**System Information:**
OSX 13.2.1 running on an M1 MBA 

**Strawberry Version:**
Tried 1.0.12, 1.0.13, 1.0.14, 1.0.14.52

**Additional context**
Happy to provide additional info, just let me know.

**Comment by jonaski** [comment]
Drag the file over to the playlist from Finder, or Playlist / Add file, do you get an error message?

**Comment by monochromec** [comment]
No. Files were correctly added including their metadata.

**Comment by jonaski** [comment]
On the collection toolbutton settings, is "Entire Collection" selected in "Show"?
What "Group by" do you have set?

I suggest to check if the song is in the database and not marked unavailable, if it's not in the database.

See: https://wiki.strawberrymusicplayer.org/wiki/Accessing_the_database

`select url, unavailable from songs where album like '%example%';`

Replace "example" with something in the album title that would match the song you are looking for.

**Comment by monochromec** [comment]
The album is in the database, and the URLs are correct (I had the player recreate the DB just to be on the safe side by renaming the .db file and adding my original Music folder to the now empty collection which caused a full rescan) and all songs have ```unavailable```set to 0.  But the album / its songs still don't show in the collection.

**Comment by jonaski** [comment]
On the collection toolbutton settings, is "Entire Collection" selected in "Show"?
What "Group by" do you have set?
What is different with the tags on this album?
Is Album artist set for the songs on the album, and if so, is it set to the same?
Is Artist set, and is it the same for all songs?
Is compilation set?

**Comment by monochromec** [comment]
"On the collection toolbutton settings, is "Entire Collection" selected in "Show"?    Yes
What "Group by" do you have set?                                                                                   Album Artist/Album
What is different with the tags on this album?                                                                 Nothing. ID3v2 tags are correct.
Is Album artist set for the songs on the album, and if so, is it set to the same?           Yes / Yes
Is Artist set, and is it the same for all songs?                                                                   Yes
Is compilation set?                                                                                                               Yes for the songs that were not displayed but clearing this part of the ID3v2 tags doesn't cause the issue to disappear.

**Comment by jonaski** [comment]
It has to be something different about the tags that causes this, it's very unlikely that one album is just coincidentally missing.
If you don't mind, could you send me the album, share it on dropbox and send me the link on jonas AT jkvinge.net. I will just use it for debugging and delete it once it's solved.

**Comment by jonaski** [comment]
Alternatively you can send me the "strawberry.db" database (or both), it might actually even be just as good with the database.

**Comment by monochromec** [comment]
Just sent you mail with more info, please let me know if you got this.

**Comment by jonaski** [comment]
The MP3 song you sent me is shown here, it's under "Various artists" because compilation (TCMP) is set.

**Comment by monochromec** [comment]
Confirming that deleting this non-standard IDv2 frame does indeed solve the issue. As this frame needs to be completely removed (simply setting the content to an empty string does **not** solve the issue) and as this is not a standard ID3v2 frame (originally defined by Apple for their iTunes product): Why not ignoring this frame all together? It would simplify the code and eliminate the possibility of similar issues in the future.
