### ISSUE TITLE
Internal data stream error: Streaming stopped, reason error (-5) playing HTTP streams

### ISSUE THREAD

**Issue by Volodymyr-13** [strawberrymusicplayer/strawberry#1148]
Just updated to Version 1.0.15 and one of my radios is not playing anymore.  

http://stream.rhr.fm/

<img width="600" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/223244273-09cb9a60-e580-419a-8370-e6451db29123.png">

VLC plays this without issues.

**Comment by brianredbeard** [comment]
This same type of error is occurring with other streams as well (e.g. SOMA.FM - https://ice6.somafm.com/defcon-256-mp3):

![image](https://user-images.githubusercontent.com/57542/223267001-6a63e2b6-0fe7-471f-a186-05e1a6eb7119.png)

**Comment by jonaski** [comment]
Both stream URLs works fine here, tested both on Linux, Windows and macOS. What OS is this?

**Comment by jonaski** [comment]
How long after starting playback does this occur? I tested 30 minutes no issues.
This looks like a playbin3 libsoup specific issue. Is the HTTP/2 option enabled or disabled in the backend settings?
I changed from playbin2 to playbin3 in 1.0.15, if you compile from source try changing playbin3 to playbin, here: https://github.com/strawberrymusicplayer/strawberry/blob/a6d10b1fa767031043d17ed254e2de3aca56b6f7/src/engine/gstenginepipeline.cpp#L294

**Comment by Volodymyr-13** [comment]
Playback is not even started, just this error blocks playback. 
HTTP/2 enabled/disabled - same error. 
I just downloaded .dmg file.. didn't compiled ever.. sorry.

**Comment by bboles** [comment]
Same error for me as well, MacOS 12.6.3 and Strawberry 1.0.15.

**Comment by jonaski** [comment]
Try with the latest from https://builds.strawberrymusicplayer.org/macos/
It has GStreamer 1.22.1 while the 1.0.15 release has 1.22.0.

**Comment by Volodymyr-13** [comment]
https://builds.strawberrymusicplayer.org/macos/strawberry-1.0.15.18.g312c5cbc-x86_64.dmg

Just this warning .. 
<img width="366" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/223828880-a80b23a1-b530-4154-8f6a-d65c6519edeb.png">

Anyway - bug is not fixed.

**Comment by Volodymyr-13** [comment]
By the way - why after some error playback completely stops? 
I have other radio station in my list of radio, so player just should try to play next another one.
VLC player does so, the main principle - music should never stop! 

Same behaviour should be for this error - https://github.com/strawberrymusicplayer/strawberry/issues/1058

**Comment by jonaski** [comment]
> By the way - why after some error playback completely stops? I have other radio station in my list of radio, so player just should try to play next another one. VLC player does so, the main principle - music should never stop!

Because whenever there is an issue like this, or similar to this preventing playback of the stream, it would be pointless to retry since it would just result in the same error over again. Playing a different stream would be a very strange behavior, since these are live streams that are continuous. Another reason is, if we don't stop, or worse don't show an error dialog whenever these errors occur, then it would be almost impossible to diagnose the problem because we got nothing to go on. The user will say: "Why did Strawberry start playing another stream".
And you can't expect a user to take the time to look in a log file, or on the console, most of the time they won't.
If you like VLC so much better, just use that.

> 
> Same behaviour should be for this error - #1058

Not really.

**Comment by Volodymyr-13** [comment]
1. Show error dialog
2. Try to play another one.
3. KISS.

Here I tried to play, got error and then it played next station. 
![giphy](https://user-images.githubusercontent.com/3391456/224139648-978546f7-461b-4cb2-8a7b-c4a382849949.gif)


And regarding https://github.com/strawberrymusicplayer/strawberry/issues/1058 yep, you right, not the same. It should just retry to play the same radio station without any error dialogs, same as VLC does. 


> If you like VLC so much better, just use that.

I use both.

**Comment by brianredbeard** [comment]
Issue persists using the latest build:  Version 1.0.15-25-g1bf1c4ac

Also, as @Volodymyr-13 pointed out the compilation is not happening using the native architecture.  In this case it's compiled for `x86_64` as opposed to `aarch64 `.

**Comment by jonaski** [comment]
Can you check if the stream works with gst-launch-1.0 using playbin3?
For example: `gst-launch-1.0 playbin3 uri=https://ice6.somafm.com/defcon-256-mp3`
If that doesn't work try with "playbin" instead of "playbin3".

**Comment by Deckweiss** [comment]
@jonaski Both ways (playbin3/playbin) worj just fine

**Comment by dani-carbonell** [comment]
Same issue here:

Strawberry 1.0.15-40-g0c621475

Hardware Overview:
 MacOs 13.2.1 (22D68)
 Chip:	Apple M2
 Memory:	8 GB

Tested with this file: 
https://gist.github.com/tvercaut/618310ba1bd5b853017b787924a921b4

Some radios work some do not.

**Comment by jonaski** [comment]
@Deckweiss
If you start strawberry from the terminal you should be able to see the URL from the debug messages.

**Comment by Deckweiss** [comment]
@jonaski 

Thanks, I was able to get the URL with  `GST_DEBUG=2,soup*:5 strawberry` and running it through `gst-launch-1.0 playbin3 uri="..."` returns the same error as you point to on the gstreamer gitlab.

My nextcloud is locally hosted and uses a selfsigned cert and I guess thats whats throwing it off.

In `strawberry > Tools > Settings > Subsonic` I have "Verify server certificate" disabled, but as far as I understand, this currently does nothing?

**Comment by jonaski** [comment]
One thing I see now is that with playbin3, the "notify::source" signal is never emitted so it's always using strict ssl mode.
So that could definitively explain the issue with self-signed certificates not working.
As for macOS, I think there is an issue with the tls database not being properly set up that might explain why it's not working with some streams, it probably worked before because we had turned off strict ssl mode.

**Comment by jonaski** [comment]
Possible fix b16bec704a33e3d034f1dd11e53b4d807dd33457

**Comment by jonaski** [comment]
@Deckweiss 
> In `strawberry > Tools > Settings > Subsonic` I have "Verify server certificate" disabled, but as far as I understand, this currently does nothing?
That option is for receiving data from the Subsonic API, not the actual streaming itself. I've added a setting to the backend settings now that allows you to turn on or off strict SSL mode.

**Comment by Deckweiss** [comment]
@jonaski It works like a charm for me now on the most recent commit

Thank you very much! You are awesome

**Comment by dani-carbonell** [comment]
Its working also for me with the last build. Thank you!
