### ISSUE TITLE
Multilanguage installer

### ISSUE THREAD

**Issue by bovirus** [strawberrymusicplayer/strawberry#1152]
@jonaski 

- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

Instalelr noiw is mono language (english).
I woiuld helpo to switch it to multilanguage.

**To Reproduce**

**Expected behavior**

Have a multilanguage installer.

**Screenshots:**

**System Information:**
 - Operating system: Windows 10 64bit 22H2
 - Strawberry Version: 1.0.15

**Additional context**

Thanks.

**Comment by jonaski** [comment]
I know how to do this. English only is a decision I've made.

**Comment by bovirus** [comment]
@jonaski

Can I ask why decide to leave in english when you can switch easiliy in multilanguage?
Why installer is in english when GUI is multilanguage?
I can do the job for you about multilanguage installer.
