### ISSUE TITLE
How to test a new/revise transaltion

### ISSUE THREAD

**Issue by bovirus** [strawberrymusicplayer/strawberry#1153]
@jonaski 

- [X] have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

I revided/coimpleted the italian translation.
I'd like to know how camn test a new&/revsied translation.
I have .po/.o file but I don't know how to use with program installed.

**To Reproduce**

**Expected behavior**

Instruction how to use new language file.

**Screenshots:**

**System Information:**
 - Operating system: Windows 10 64bit italian 22H2
 - Strawberry Version: 1.0.15

**Additional context**

Please consider if you can to use external language files for your program.

Thanks.

**Comment by jonaski** [comment]
You build Strawberry with `-DINSTALL_TRANSLATIONS=ON`, for Windows you need to modify the `TRANSLATIONS_DIR` in the source code. Or you can just rebuild Strawberry whenever you modify the .po.

**Comment by bovirus** [comment]
@jonaski 

Then the language file are embeeded in the exe file?

Is there a way to put some language file in some folder of installed program to test a new language?
Because the longer job is not to translate but to check the translation in the context.
And to avoid many changes and update in the repsoitory waiting you that rebuild the application could be useful to have a way to test a new language without recompile the build.

**Comment by jonaski** [comment]
> @jonaski
> 
> Then the language file are embeeded in the exe file?

Yes using Qt resources.

> Is there a way to put some language file in some folder of installed program to test a new language? Because the longer job is not to translate but to check the translation in the context. And to avoid many changes and update in the repsoitory waiting you that rebuild the application could be useful to have a way to test a new language without recompile the build.

I've already explained this.

**Comment by bovirus** [comment]
@jonaski

If I understood well you explained how  build the application including a new language file.

My question if it's possible to run current exe (installed in C:\Programs\Strawbeery Musci Player) asking via command line to load an external language file.

**Comment by jonaski** [comment]
If you build with `INSTALL_TRANSLATIONS`, translations in resources are excluded, so you do not have to rebuild whenever you change the .po file. Hope that makes it clearer.
Here is where the translations loaded: https://github.com/strawberrymusicplayer/strawberry/blob/0f575f46393c6c18244f73947b1bb640f7818628/src/main.cpp#L286
It might be possible that the .po from the application directory is picked up even when building with `INSTALL_TRANSLATIONS`, but I didn't test that.

**Comment by bovirus** [comment]
@joansky

Sorry but I didn't have the knowldge to compile the build.

May I have a debug build (compiled by you) for this purpose?
