### ISSUE TITLE
/src/translations/header - Use of this file

### ISSUE THREAD

**Issue by bovirus** [strawberrymusicplayer/strawberry#1156]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

In **/src/translations** between .po files of different language there is a file **header** updated 4 years ago

What's the scope of this file?
Is it right that stay in this folder?
 
**To Reproduce**

**Expected behavior**

**Screenshots:**

**System Information:**
 - Operating system: Windows 10 22 H2 64bit
 - Strawberry Version: 1.0.15

**Additional context**

**Comment by jonaski** [comment]
It's used in https://github.com/strawberrymusicplayer/strawberry/blob/master/cmake/Translations.cmake
Anyway, GitHub issues is for bugs, not questions.

**Comment by bovirus** [comment]
@jonaski 

I'm not sure if was a bug a file that is unqiue in middlle of other different file.

Thanks.
