### ISSUE TITLE
[REQ] Don't jump to next item on errors not related to file/stream, attempt to restart instead

### ISSUE THREAD

**Issue by Trinity3e** [strawberrymusicplayer/strawberry#1157]
When a file can't be found, or if a stream buffers too much etc, Strawberry switches to the next item, that's very good.

However, on other unrelated errors, Strawberry also switches to the next item, which can be annoying. For instance "Jack server shutdown/restart" which happens intermitently on the pipewire-jack client.

Here it should not jump to the next item but instead attempt to restart, (like when it attempts to restart a buffering stream, those ~5 attempts should suffice). And of course only show the error window if it ran out of attempts and if the error remained the same.

Thank you!

**Comment by jonaski** [comment]
Strawberry stops on fatal errors, it only continues on resource/stream errors. It is possible that a pipewire/jack error is reported with the same scope as a resource error by gstreamer.
There is a issue template here for a reason, and you do not even provide the error code so I'm closing this.

**Comment by Trinity3e** [comment]
Sorry for not explaining correctly, this is not in any way related neither to pipewire/jack nor to the gstreamer backend, and since this is not a bug but a **cosmetic** annoyance I cannot use the issue template.

If error types are sorted only by fatal and resource/stream then what sense does it make to skip the track on a fatal error?

Just for the sake of it, this is what hapens in my case: I start a stream or a song, it keeps iterating through the list until the jack client wakes up, and I end up near the bottom of the playlist with that playing correctly, of course the error window is covering every program until now (at least make it always underlayered)

```
Resource not found.

../gstreamer/subprojects/gst-plugins-good/ext/jack/gstjackaudiosink.c(308): jack_shutdown_cb (): /GstBin:audiobin/GstJackAudioSink:pipeline-4-jackaudiosink: Jack server shutdown

Resource not found.

../gstreamer/subprojects/gst-plugins-good/ext/jack/gstjackaudiosink.c(308): jack_shutdown_cb (): /GstBin:audiobin/GstJackAudioSink:pipeline-5-jackaudiosink: Jack server shutdown

Resource not found.

../gstreamer/subprojects/gst-plugins-good/ext/jack/gstjackaudiosink.c(308): jack_shutdown_cb (): /GstBin:audiobin/GstJackAudioSink:pipeline-6-jackaudiosink: Jack server shutdown

Resource not found.

../gstreamer/subprojects/gst-plugins-good/ext/jack/gstjackaudiosink.c(308): jack_shutdown_cb (): /GstPlayBin3:pipeline-7-pipeline/GstPlaySink:playsink/GstBin:abin/GstBin:audiobin/GstJackAudioSink:pipeline-7-jackaudiosink: Jack server shutdown
```
Then something at the very bottom of the playlist starts to play.
If this is because of gstreamer, at least make it try to restart rather than keep switching tracks.
