### ISSUE TITLE
Search-as-you-type unpleasant on large collections

### ISSUE THREAD

**Issue by jeanrajotte** [strawberrymusicplayer/strawberry#1162]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When typing in the filter search control, with a large collection, the "search as you type" "feature" freezes all between keystrokes. The "convenience" isn't worth the aggravation.

**To Reproduce**
With a large collection type a search phrase and be patient

**Expected behavior**
Stop "search as you type". Wait for the user to press Enter to launch the search. And/or make it a setting one can change based on experience with one's collection.

**Screenshots:**

**System Information:**
 - Operating system: Win 10
 - Strawberry Version: 1.0.15

**Additional context**

**Comment by jonaski** [comment]
This isn't normal, how many songs? What "group by" do you have set? Approximately many entries are there for the first group by level, ie artist or album?

**Comment by jeanrajotte** [comment]
Group by Album

Re: Counts. Wasn't there a footer widget that gave those counts, or am I thinking of a different app?

~2,398 top-level entries (albums)

The bulk of the collection is on a removable USB drive that I plug and unplug often. Would that impact this aspect of performance? 

Physically, it's:      31,331 Files,     5,808 Folders,    211 GB

**Comment by jonaski** [comment]
That's expected since you group by album, it does not perform well because it's resetting the model on each search. It's not really the search itself that takes time, and the search itself is done in a non GUI thread. What takes time is populating the model which is why it's laggy.
So this is basically the same as #392. This will be resolved when I've finished rewriting the model.
