### ISSUE TITLE
Sidebar resets at every boot

### ISSUE THREAD

**Issue by niels0n** [strawberrymusicplayer/strawberry#1169]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I'm trying to enlarge the album cover and set the sidebar to "Plain sidebar". I can do it, but everytime I reboot my pc it goes back to the default (smaller album cover and "Large sidebar").

**To Reproduce**
Change some sidebar settings. Reboot.

**Expected behavior**
To have the customizations of the sidebar preserved across reboots.

**Screenshots:**

**System Information:**
 - Operating system: Void Linux
 - Strawberry Version: 1.0.9

**Comment by jonaski** [comment]
If Strawberry is forcefully shutdown, it won't save things like window positions. I suggest close Strawberry manually before rebooting to make sure it exits cleanly.

**Comment by niels0n** [comment]
I'm sorry, I think I haven't explained clearly the problem.
I do always close manually Strawberry, I mentioned the reboot because the sidebar seems to reset itself after the reboot of the computer, and not of Strawberry.

If I change the sidebar's size, then close Strawberry and re-open it, the sidebar is exactly as I left it.
But when I reboot it resets itself undoing the changes I made.

I hope this is more clear now!
