### ISSUE TITLE
It is detected that Strawberry is running under Rosetta strawberry-1.0.16

### ISSUE THREAD

**Issue by Volodymyr-13** [strawberrymusicplayer/strawberry#1170]
**Describe the bug**

I can't see a _.dmg_ file for 1.0.17 version, so I installed this
(https://github.com/strawberrymusicplayer/strawberry/releases/download/1.0.16/strawberry-1.0.16-x86_64.dmg)
Upon running I got warning: It is detected that Strawberry is running under Rosetta

**To Reproduce**
Run on any device with M1 macOS.

**Expected behavior**
Not using Rosetta.

**Screenshots:**
<img width="366" alt="Screenshot" src="https://user-images.githubusercontent.com/3391456/228628683-ce60bd5b-0551-4416-aa08-9a69a81ad75f.png">

**System Information:**
 - Operating system: 13.3 
 - Strawberry Version: 1.0.16

**Comment by Volodymyr-13** [comment]
Same message for file https://github.com/strawberrymusicplayer/strawberry/releases/download/1.0.17/strawberry-1.0.17-x86_64.dmg

**Comment by jonaski** [comment]
See https://forum.strawberrymusicplayer.org/topic/1092/macos-support

**Comment by Volodymyr-13** [comment]
I'd suggest some things: 

 - for macOS version attach somewhere on a sidebar a big donate button
 - show a message about donation and problems
 - then buy a used and cheapest Apple Mac Mini 2020 M1 256 GB (MGNR3)

**Comment by jonaski** [comment]
I've added a message about sponsorship on startup.
