### ISSUE TITLE
(Windows) Add dbus for Discord Rich presence

### ISSUE THREAD

**Issue by rickychii** [strawberrymusicplayer/strawberry#1173]
Hello,
for rich presence in Discord (current player playing song) in Linux it's easy to achive, with dbus and Discord Rich presence you can simply obtain and display on Discord current user status Strawberry current status.
On Windows dbus it's not working, and I can't figure out how to obtain current player status. It's something implementable?

Ricky

**Comment by jonaski** [comment]
Use the Discord API I guess. Anyway, use the Forum or the discussions for questions.
