### ISSUE TITLE
Volume adjusted while nothing is playing resets when playback starts

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1174]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Volume adjusted while nothing is playing resets when playback starts.

**To Reproduce**
1. open Strawberry
2. adjust the volume level using the volume slider of Strawberry
3. play a song

**Expected behavior**
the volume level remains the same

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.17

**Additional context**

**Comment by jonaski** [comment]
This should hopefully fix it https://github.com/strawberrymusicplayer/strawberry/commit/b59aa0827e46ccd0be876436013c62d6aef3c21f
