### ISSUE TITLE
FEAT: Allow Playlist Font Size Change in Preferences > UI > Appearance

### ISSUE THREAD

**Issue by 589290** [strawberrymusicplayer/strawberry#1177]
- [✅] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [✅] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 

**System Information:**
 - Operating system: Mac 13.3.1
 - Strawberry Version: 1.0.17

**Additional context**
It would be nice to be able to change the playlist font size independent of the app / desktop resolution.

**Comment by clementine-user** [comment]
@jonaski, this would be a nice feature update.

**Comment by jonaski** [comment]
I've already answered this before, and it's written in the README that I can't take feature requests now, only fix bugs.
Also, I might be forced to drop macOS support, unless I get more donations to cover costs, see: https://forum.strawberrymusicplayer.org/topic/1092/macos-support

**Comment by jonaski** [comment]
> @jonaski do you need help setting up a build pipeline for arm64 Mac builds? I've just recently learned that you can build apps in a MacOS environment entirely inside docker : https://github.com/sickcodes/Docker-OSX

That would be nice
