### ISSUE TITLE
Strawberry steals internet bandwidth

### ISSUE THREAD

**Issue by gianlucapettinello** [strawberrymusicplayer/strawberry#1179]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When I open Strawberry internet download speed goes very low as if it is stealing most of the bandwidth
**To Reproduce**
Open Strawberry while downloading a file and play a song

**Expected behavior**
No internet bandwidth stealing

**System Information:**
 - Operating system: Linux - Archlinux kernel 6.2.10
 - Strawberry Version: 1.0.17

**Comment by gianlucapettinello** [comment]
It is while playing a local song. Is it possible that there is a service for instance getting the album art?
I'm not so expert as to make a video of the screen to show you the difference. Normally if I update my system (Archlinux, I run pacman), the download speed from 2.1 MB/s (my internet connection is not that brilliant) falls to 20 kB/s. 
I can't be of more help for the time being I'll try to see if I can record a video and show you

**Comment by jonaski** [comment]
Closing this as it's not likely a bug in Strawberry.

**Comment by gianlucapettinello** [comment]
Hello,
sorry for coming back late. The phenomenon seems disappeared. So it was not related to Strawberry. I apologize for having created unnecessarily the bug.
Thanks for the support anyway
Gianluca
