### ISSUE TITLE
Strawberry can't properly save playlists with songs from CUE sheets

### ISSUE THREAD

**Issue by OlegAckbar** [strawberrymusicplayer/strawberry#1181]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry don't save positions offsets for source file when songs added from CUE sheets when saving playlist. It only saves path to source image without specifying offsets in that file, so entire playlist consists of just one file.

**To Reproduce**
1. Create playlist
2. Import CUE sheet
3. Save playlist
4. Try to load that playlist
5. Get a playlist consisting of one file duplicated multiple times

**Expected behavior**
Time offset for each entry from CUE sheet.

**System Information:**
 - Operating system: Kubuntu 22.10
 - Strawberry Version: 1.0.17-kinetic APT-Sources: https://ppa.launchpadcontent.net/jonaski/strawberry/ubuntu kinetic/main

**Additional context**
Here's example of such playlist. As you can see it even when it saved with metadata it only contains path to original CD image with no information about position inside that image.
[persona5cd1.xspf.txt](https://github.com/strawberrymusicplayer/strawberry/files/11241753/persona5cd1.xspf.txt)

**Comment by OlegAckbar** [comment]
Yet it possible to save playlists with positions inside CUE sheet. Here's how AIMP doing this: 
[Default.m3u8.txt](https://github.com/strawberrymusicplayer/strawberry/files/11241770/Default.m3u8.txt)

**Comment by jonaski** [comment]
As far as I can tell there is no field in the XSPF specifications (https://www.xspf.org/spec) for saving index/position, there is trackNum, so in that case we have to map by url and trackNum to the collection, or read the CUE file to find the position.
