### ISSUE TITLE
Album cover disk cache cannot distuingish between album names #4 and #5

### ISSUE THREAD

**Issue by MausGames** [strawberrymusicplayer/strawberry#1183]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I have two albums in my collection named [#4](https://en.wikipedia.org/wiki/Number_4_(album)) and [#5](https://en.wikipedia.org/wiki/Number_5_(Ling_Tosite_Sigure_album)). When the album cover disk cache is enabled, both albums cannot have separate covers. Looking at the cache files, it seems the album name is used as key and points to the same file for both albums.

**To Reproduce**
Enable disk cache, have two separate albums named [#4](https://en.wikipedia.org/wiki/Number_4_(album)) and [#5](https://en.wikipedia.org/wiki/Number_5_(Ling_Tosite_Sigure_album)), and give them separate album covers. Initially the covers are separate, but after some time using the application (cache refresh ?) both covers become identical.

**Expected behavior**
Both albums have separate covers.

**Screenshots:**
![image](https://user-images.githubusercontent.com/6109189/232766534-2bb7475f-4142-4043-a992-95b5b6bd9003.png)

**System Information:**
- Operating System:
 Fedora Linux 37
 KDE Plasma Version: 5.27.4
 KDE Frameworks Version: 5.104.0
 Qt Version: 5.15.8
 Kernel Version: 6.2.9-200.fc37.x86_64 (64-bit)
 Graphics Platform: X11
 Processors: 12 × AMD Ryzen 5 3600XT 6-Core Processor
 Memory: 31,2 GiB of RAM
 Graphics Processor: AMD Radeon RX 5600 XT
- Strawberry Version:
 1.0.16 (Qt 5.15.8)

**Additional context**
Show: Entire Collection
Group by: Group by Album
no cover providers are enabled, covers are manually in album folders
it seems to work with disabled disk cache

**Comment by jonaski** [comment]
I can't reproduce this, but I'm pretty sure it's related to disk cache keys not being URL encoded, so b0b8ff2d494e8ba5c9b33bd28acbba54e6868cd3 should probably fix it.

**Comment by MausGames** [comment]
Thank you! I will give you an update when I get the fix. (which might take a bit, as I use the Fedora build)

**Comment by MausGames** [comment]
I did not know that there are experimental developer builds available, so I've downloaded 1.0.17.144 and was able to confirm that the issue is fixed. 

The disk cache became a bit bigger at first (4.7 MB), but after clearing it and using the software for some time, everything was back to normal and still worked (2 MB).

Thank you!
