### ISSUE TITLE
Font size for context pane is ignored on macOS 13

### ISSUE THREAD

**Issue by JustThat70** [strawberrymusicplayer/strawberry#1184]
**Describe the bug**
On macOS 13, changing the font size of the context pane font for either headline or data and lyrics has no effect. The font can be changed, but all fonts ignore the font size setting

**To Reproduce**
Try to change the font size in the Context area in preferences

**Expected behavior**
Font size should change

**System Information:**
 - Operating system: 13.3.1
 - Strawberry Version: 1.0.17

**Additional context**
This has been an issue since, I think, 1.0.11 or 1.0.12

**Comment by jonaski** [comment]
Can you try the latest from https://builds.strawberrymusicplayer.org/macos/ and check if this is fixed now (dates from 03.05.2023 or later).

**Comment by geroyche** [comment]
does not work.
i have no experience with Qt, so pardon if that's plain wrong, but my general intuition is that this might be an issue:
https://github.com/strawberrymusicplayer/strawberry/blob/master/data/style/strawberry.css#L68

you moved away from explicit stylesheets, so now maybe the code is implicitly overwritten by the general stylesheet?

**Comment by jonaski** [comment]
I think the stylesheet font size hack was added because fonts were too large, I removed it now, it's an awful hack.

**Comment by clementine-user** [comment]
This is working now on macOS 13.3.1 on Intel with dev build strawberry-1.0.17.85.g7c7724e4-x86_64. Mac users should take note that the default font for Strawberry is Noto Sans which is not installed as part of the default macOS install. Users will have to download and install it so the os does not substitute a different font. [Noto Sans download](https://fonts.google.com/noto/specimen/Noto+Sans).

**Comment by jonaski** [comment]
@clementine-user Thanks

**Comment by geroyche** [comment]
I just want to point out that this fix does indeed make all the font sizes bigger on macOS as a side effect. I do not have Noto Sans installed, so macOS default font is used.
hard to say for me whether the sizes are now closer to how other OS show it, or farther away from it.

<img width="1361" alt="Screenshot 2023-05-06 at 14 12 07" src="https://user-images.githubusercontent.com/1317144/236623349-66de2275-ffff-44db-bea6-b063a977ec22.png">
<img width="1363" alt="Screenshot 2023-05-06 at 14 10 08" src="https://user-images.githubusercontent.com/1317144/236623352-925cd7ce-1e15-4d04-976a-abd6809f415e.png">

**Comment by llucps** [comment]
Thank you for the change @jonaski .

I don't want to be picky, but now that font is coming from the OS, and by default is 13pt. It would be great to add 2px margin to the main playlist view. By default the Finder uses 13pt and every row is 20px height, whereas Strawberry is 18px.

Check this mockup:
![list](https://github.com/strawberrymusicplayer/strawberry/assets/25823659/69000d30-9b38-4e13-a020-da7b763beba7)

I know it's barely visible.. but the list on the right (Finder) breathes a little bit more, and now the Strawberry main view looks a tiny bit cramped 

Can you point me out where I could control that on the code? Is it possible the fiddle a bit and add 2px of margin per row?

Thanks!

**Comment by jonaski** [comment]
https://github.com/strawberrymusicplayer/strawberry/blob/master/src/playlist/playlistview.cpp

I think it has to be done with CSS, but there is some manual draw code in the playlist for the currently playing track.

https://stackoverflow.com/questions/29005296/add-padding-to-qtreeview-columns

**Comment by geroyche** [comment]
personally i downgraded to a built without this fix. the issue itself was not in any way important to me, but the increased font size in relation to everything else feels off.

**Comment by llucps** [comment]
Thank you @jonaski
