### ISSUE TITLE
Not scrobbling if music in a external drive

### ISSUE THREAD

**Issue by Jakeukalane** [strawberrymusicplayer/strawberry#1185]
- [V ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [V ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [V ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When using scrobblers if the song if the collection is in a external drive, the song doesn't get scrobbled.

**To Reproduce**
Have a external drive with music, add that music as the library, play. No scrobbles.

**Expected behavior**
The song get scrobbled.

**System Information:**
 - Operating system: Linux Manjaro 22.1.0 Talos
 - Strawberry Version: 1.0.17

Possible workaround (not working): naming a folder as ~/Music but then making it a soft link to the place in the external drive.

**Comment by jonaski** [comment]
External hard-drive should not matter. What matters is song length, title and artist. Does it show length, and does it have artist and title tags?
In the Scrobbler settings, is both the top "Enable" and the enable checkbox for the individual service (Last.fm, Libre.fm and Listenbrainz checked? And make sure the "Work in offline mode" is not checked.
Start strawberry on a terminal to see more debug output for scrobbling.

**Comment by Jakeukalane** [comment]
Ok, don't know where that "Work in offline mode" got activated... That is unfortunate that something like that exists. What is the use of a function that prevents scrobblings?
