### ISSUE TITLE
Unable to select groupings, clicking on any grouping opens the `Collection Advanced Grouping` dialog

### ISSUE THREAD

**Issue by kevenwyld** [strawberrymusicplayer/strawberry#1189]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Selecting "Group By" -> And then some predefined group opens the `Collection Advanced Grouping` dialog but doesn't change the view or activate the grouping.

**To Reproduce**
Select "Group By" -> And then some predefined group.

**Expected behavior**
Should activate the grouping (I think?) in the collection view.

**Screenshots:**

https://user-images.githubusercontent.com/11936535/234376556-33890d31-f03f-4b85-a2ce-10f4b5fb82e5.mp4

**System Information:**
 - Operating system: Archlinux
 - Strawberry Version: 1.0.17

**Additional context**
It's not clear in the dialogue what should be happening and the wiki doesn't seem to have any information about how to activate a grouping, so I'm just guessing that this is how one should do it.  However getting the `Collection Advanced Grouping` dialogue and the same advanced grouping options no matter what I click on seems like a bug.

EDIT:  Sorry had some trouble with the video formatting for github.

**Comment by jonaski** [comment]
I see the same problem on openSUSE Tumbleweed with Qt 6.5.0 with the distro package. However if I compile Strawberry from source against the same Qt version installed on the system to actually debug it, everything works. Very strange.
I see this on the terminal, but only with the distro package:
`21:54:25.636 WARN  unknown                          QVariant: Provided metatype for 'CollectionModel::Grouping' does not support destruction and copy construction`

**Comment by kevenwyld** [comment]
I also compiled it locally using the arch pkgbuild [here](https://github.com/archlinux/svntogit-community/blob/packages/strawberry/trunk/PKGBUILD).  I made no changes at all and I also see that it is working in that locally compiled version.  Very odd.

**Comment by jonaski** [comment]
I think this is a binary incompatibility between Qt 6.4 and 6.5. The package in opensuse was built 30.03.2023, while Qt 6.5 was released 3.4.2023. The upstream devel package (https://build.opensuse.org/package/show/multimedia:apps/strawberry) works which is identical to openSUSE factory except it's been rebuilt.

**Comment by jonaski** [comment]
Qt 6.5 is supposed to be binary compatible with Qt 6.4, but i looks like something broke.
Can you see when the official package in Arch was built?

**Comment by kevenwyld** [comment]
strawberry v1.0.17: `Build Date      : Thu 30 Mar 2023 12:06:45 AM MDT`
qt6-base v6.5.0: `Build Date      : Mon 10 Apr 2023 03:06:24 AM MDT`

**Comment by kevenwyld** [comment]
If it would be helpful I can report this to the maintainer of the community repo strawberry package.

I'm not sure what the normal process for notifying maintainers of incompatible dependencies is though.  I suppose a version bump would also solve this but seems unnecessary since nothing has changed.

Anyway happy to help in any way I can.

**Comment by jonaski** [comment]
https://bugs.archlinux.org/task/78311

**Comment by jonaski** [comment]
Looks like Qt is already aware of this, and a fix is on the way: https://bugreports.qt.io/browse/QTBUG-113227
