### ISSUE TITLE
Tooltip when hovering on items in the collection menu bugs out when moving mouse between collection items

### ISSUE THREAD

**Issue by Absolutely-Free** [strawberrymusicplayer/strawberry#1190]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
If you hold your mouse on an item in the collection menu, you get a tooltip that contains the text of the item in the collection list that you are hovering over. If you move your mouse up or down to the next item in the collection list, the tooltip remains open but gets mangled when the tooltip box resizes to accommodate the text of the new item. This results in a tooltip that isn't the correct size for the new text and also has a weird graphical glitch where the animation of the tooltip box resizing keeps repeating in a portion of the tooltip box.

**To Reproduce**
-In the collection menu portion of Strawberry, hover your mouse over a collection item so that the tooltip text displays. The collection item can be anything (artist, album, track, etc.)
-Move your mouse up or down to the next item in the collection list. You should see the graphical glitch occur as the tooltip box attempts to resize.

**Expected behavior**
The tooltip box should resize and display the text of the next item you are hovering your mouse over.

**Screenshots:**
![Screenshot_20230425_131241](https://user-images.githubusercontent.com/93813924/234384891-d6ff2208-a647-4720-a945-a5bfe9e2601e.png)

**System Information:**

I have reproduced this issue on two systems.

### System 1
Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.1.25-1-lts (64-bit)
Graphics Platform: X11
Processors: 6 × Intel® Core™ i7-8700 CPU @ 3.20GHz
Memory: 31.2 GiB of RAM
Graphics Processor: AMD FirePro W5100
 - Strawberry Version: Version 1.0.17

### System 2:
Operating System: Arch Linux
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.2.12-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 1030/PCIe/SSE2
 - Strawberry Version: Version 1.0.17

**Comment by jonaski** [comment]
I suspect this is a Qt bug.

**Comment by Absolutely-Free** [comment]
It seems like you are correct. I was looking for other Qt programs that display tooltips the same way that Strawberry does and I found an example of the same bug in Kate, the KDE text editor. If the sidebar on the left is collapsed so only the icons are showing, you mouse over one of those icons to display a tooltip, and then move your mouse up/down to other icons, you can see the same issue with resizing.

I took a look at Qt's bug tracker and could not find a currently open or recent case regarding this issue. It seems like they understandably want more technical information regarding how the bug manifests in Qt, but I am not experienced with Qt development so I can only really say "here's two programs where this bug occurs". If you were to create a bug with the technical information, I would be happy to add examples of the problem manifesting in applications. Or vice-versa.

**Comment by PeterBBBBB** [comment]
I'm wondering if this is a KDE bug, as my tooltips are fine in Xfce4

**Comment by jonaski** [comment]
@PeterBBBBB What Qt version?

**Comment by PeterBBBBB** [comment]
I'm using the official disto packages in Arch & Debian.
Arch is 6.5.0
Debian is 5.15.8

**Comment by jonaski** [comment]
I recently switched to KDE on both my home and work computer after using XFCE for many years. I definitely never seen the bug until recently. So you might be right, maybe it's a KDE bug.

**Comment by jonaski** [comment]
Anyway, I removed all the custom delegates, tooltip paint code strawberry uses just to check if the bug could be related to that code but the bug still persists so at least I'm pretty sure the bug isn't in Strawberrry's code.

**Comment by jonaski** [comment]
I can reproduce it with both Qt dev, Qt 6.5.0 and 6.2.2...

**Comment by PeterBBBBB** [comment]
Also, I'm using Fusion style and Liberation fonts,
in case that might be relevant.

**Comment by Absolutely-Free** [comment]
I created a bug within KDE's bug tracker:

https://bugs.kde.org/show_bug.cgi?id=469067

**Comment by Absolutely-Free** [comment]
This wound up being ruled as a Qt bug by the KDE team. Qt bug here: https://bugreports.qt.io/browse/QTBUG-113287
