### ISSUE TITLE
(Windows) Command line options not working with diacritics

### ISSUE THREAD

**Issue by ultr41337h4xor** [strawberrymusicplayer/strawberry#1191]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Trying to play a local file, when the file location contains a diacritic (for example - C:/Domaće) results in the player giving a file does not exist error. The player tries to find a file location that does not contain the diacritic (following the former example - C:/Domace).

**To Reproduce**
Try to play a local file in a location containg a diacritic in the name.

**Expected behavior**
The file should be found and played.

**Screenshots:**
![image](https://user-images.githubusercontent.com/86489731/234644496-964a974a-688a-4bdd-a485-dc237b81a4b6.png)

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 1.0.17

**Additional context**
/

**Comment by jonaski** [comment]
I can't reproduce this issue. Tested with both "Domaće" in the path and in the filename.

What settings do you have in Windows for Region? Make sure the Beta option is off, it is buggy:

![image](https://user-images.githubusercontent.com/10343810/234958167-27fb8d7f-8015-4de4-8e65-7071fb1dad97.png)

**Comment by jonaski** [comment]
This because Strawberry uses BSD getopt on Windows too, so no easy fix I think other than rewriting the command line options.
