### ISSUE TITLE
Appearance of Strawberry changes weirdly when it loses focus on Gnome DE

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1192]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
As we can observe in the attached video, the appearance of Strawberry running on Gnome DE changes weirdly when it loses focus. Also the labels of the playlists are always greyed out.

**To Reproduce**
1. use Strawberry on a linux distribution running Gnome desktop environment
2. open Strawberry and click on "Strawberry" on Gnome Shell top bar

**Expected behavior**
the observed result should not occur

**Screenshots:**
[strawberry.webm](https://user-images.githubusercontent.com/15967631/234705905-6cf11c1a-4a56-4447-aef1-5a8128e158ed.webm)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.17

**Additional context**
I noticed this bug after updating to Qt 6.5.

**Comment by jonaski** [comment]
Qt 6.5 introduced GTK3 theme support, I don't know if this is a bug in Qt, or it's the styling on Gnome that does this, but at least it's not a bug in strawberry.

**Comment by ProMarbler14** [comment]
setting the environment variable QT_QPA_PLATFORMTHEME to qt6ct or qt5ct, as suggested by qt6ct, restores sane theming to the application.

**Comment by glaubersm** [comment]
I have installed qt6ct package on my system and added the env variables below to /etc/environment file:

QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt6ct

After logout and login, the bug does not occur if I set Fusion style in qt6ct, but it does if Adwaita style
is set instead.

**Comment by jonaski** [comment]
Perhaps a Adwaita bug, maybe report it to Adwaita or Gnome.
