### ISSUE TITLE
Random pauses when playing back mp3s

### ISSUE THREAD

**Issue by monochromec** [strawberrymusicplayer/strawberry#1195]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The player pauses randomly when playing an mp3 and sometimes opens Apple Music. At first I suspected an issue with new mp3 added to the library recently but this issue also occurs with mp3 which used to play back without problems.

**To Reproduce**
Select an mp3 and start playback.

**Expected behavior**
Continuous playback without pausing.

**System Information:**
 - Operating system: OSX 13.3.1 running on Apple Silicon
 - Strawberry Version: 1.0.17

**Additional context**
More than happy to provide additional info such as logs (if I could find them).

**Comment by monochromec** [comment]
As Apple's Music app seems to have similar problems, this issue may be a symptom of Qt's internal mapping of the media API to Apple's AVFoundation (which apparently is used after Qt redesign in version 6 of this framework).

**Comment by mman** [comment]
Please post the link to the "broken" mp3 so that it can be analysed and provide more info which software has produced it...

**Comment by jonaski** [comment]
Try Apple support. Closing this as its not a strawberry bug.

**Comment by monochromec** [comment]
Issue seems to have vanished after the upgrade to OSX 13.4.
