### ISSUE TITLE
Play count does not increase

### ISSUE THREAD

**Issue by AlexanderRavenheart** [strawberrymusicplayer/strawberry#1197]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Play count does not increase.

**To Reproduce**
Play songs in a playlist with the **Play count** column visible.

**Expected behavior**
Play count should increase.

**System Information:**
 - Operating system: Pop!_OS 22.04 LTS (64-bit)
 - Strawberry Version: 1.0.17 (using the PPA)

**Additional context**
My config: [strawberry.zip](https://github.com/strawberrymusicplayer/strawberry/files/11419343/strawberry.zip)

**Comment by jonaski** [comment]
Is this local songs, and are they added to the collection?
Playcount works with collection songs only, since playcounts is stored in the database.
It works here.

**Comment by AlexanderRavenheart** [comment]
Yes, using local files present in the Collection.

I just started the app from terminal with --verbose to check for potentially useful debug messages but now it did update the play count.

I can't reproduce the issue. 🫤

**Comment by jonaski** [comment]
OK closing the issue then.
