### ISSUE TITLE
Dragging items to/within a playlist with a mouse doesn't work

### ISSUE THREAD

**Issue by eignatenkov** [strawberrymusicplayer/strawberry#1202]
**Describe the bug**
When I try to drag some album from the library to the playlist the mouse pointer changes to the hand with the stop sign and nothing is added to the playlist. The same happens when I select some tracks in the playlist and try to move them up or down.

**System Information:**
 - Operating system: Ubuntu 23.04
 - Strawberry Version: 1.0.17

**Comment by jonaski** [comment]
Thanks @joshstoik1. This is definitely a platform integration issue, not a strawberry bug.
