### ISSUE TITLE
Unable to lunch the installer

### ISSUE THREAD

**Issue by LinuxBoy-96** [strawberrymusicplayer/strawberry#1203]
So today I got a new Laptop and I tried to install Strawberry on it.
It does not matter if I choose MinGW or MSVC, Windows ask me if i'm looking for an app on the Microsoft Store.
I even tried to lunch that installer on my old laptop and it work while the old installer on my new laptop still don't works.

Excuse my french.
![20230517_071239.jpg](https://github.com/strawberrymusicplayer/strawberry/assets/128245725/9007ecf0-46e9-4648-80eb-41b03970317c)

**Comment by jonaski** [comment]
This does not look like a Strawberry bug, but a Windows issue. I suggest to seek Windows support, or use the forum (https://forum.strawberrymusicplayer.org/).
