### ISSUE TITLE
Track slider crashes on FreeBSD 13.2

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#1207]
I tried with both versions (qt-5 and qt-6) and in both the same error happens.

`sudo pkg install strawberry-qt5`

On FreeBSD 13.2 moving the track slider up and down, the song stops playing showing this error:

`../libs/gst/base/gstbasesrc.c(2775): gst_base_src_get_range (): /GstPlayBin3:pipeline-5-pipeline/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin4/GstCurlHttpSrc:curlhttpsrc4: Subclass GstCurlHttpSrc neither returned a buffer nor submitted a buffer list from its create function`

![image](https://github.com/strawberrymusicplayer/strawberry/assets/25823659/7357e524-543e-4c8b-bd59-c2be151565c2)

This is with a Navidrome installed an a VPS, therefore using Subsonic API. Let me say that this only happens on FreeBSD, on Debian or macOS it wall works just fine.

Any idea where to look at?
Thanks.

**Comment by jonaski** [comment]
This looks like a gstreamer or libcurl bug, maybe the same as this: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1120
Make sure you use the latest version of gstreamer (1.22.3). Or report the issue to freebsd.

**Comment by llucps** [comment]
Thanks @jonaski I will report the bug.

**Comment by llucps** [comment]
Just for follow up here is the question on the FreeBSD forums in case a solution is found https://forums.freebsd.org/threads/track-slider-crashes-on-strawberry.89308/

**Comment by jonaski** [comment]
Did you try installing gstreamer1-plugins-soup? Because the message indicates it's using curl instead of soup, maybe the curl plugin does not support seeking (never tested it).

**Comment by llucps** [comment]
Yes! that was it! thanks. :+1: 

I'll add the answer to the FreeBSD forum as well.
