### ISSUE TITLE
Album Art from PNG Images Will Not Embed Onto Music Files

### ISSUE THREAD

**Issue by RichCat6** [strawberrymusicplayer/strawberry#1209]
I've been dealing with this issue for about a week. Whenever I try to change the album art to song and the album art I want to use happens to be a PNG image, it will refuse to embed the album art to the music file.
Steps to reproduce:
1. Right click on a track, click "Edit track information"
2. Click "change album art", then click "load cover from disc"
3. Select any PNG image
4. Click save, and watch it unset the artwork you just set.

**Comment by jonaski** [comment]
Should be fixed by 331aa382f93d4e9c34cb8c871b7c30e5a40023d1

**Comment by RichCat6** [comment]
> Should be fixed by [331aa38](https://github.com/strawberrymusicplayer/strawberry/commit/331aa382f93d4e9c34cb8c871b7c30e5a40023d1)

Thx ; )
