### ISSUE TITLE
Right click menu, "Edit tag [tagname]" suggests F2 works on all tags but only works on Title 

### ISSUE THREAD

**Issue by SimonDedman** [strawberrymusicplayer/strawberry#1210]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug / To Reproduce**
Collection tab: right click on the data in any column and the right click menu will offer "Edit tag [columnname]  F2" but F2 does nothing if the right click menu is open, and if you left-click on a specific cell (column + row) then hit F2, it opens up the Title column for editing.

**Expected behavior**
Left click cell, F2 opens editing on that cell.

**System Information:**
 - Operating system: Xubuntu 23.04
 - Strawberry Version: 1.0.17

**Comment by jonaski** [comment]
This is a Qt 5 but, works fine in Qt 6.

**Comment by SimonDedman** [comment]
Hmmm... I'm on Qt6.4.2 though?

You're right, playlist not collection.

**Comment by jonaski** [comment]
Looks like the action shortcut is conflicting with some default shortcut in Qt. Removing the F2 shortcut from the action seem to fix it.

**Comment by jonaski** [comment]
Looks to be working now, tested both with Qt 5 and 6.

**Comment by SimonDedman** [comment]
Cheers bud. Quick one thought - not sure if this is something I can fix my side or if you're going to push a fix?

"Removing the F2 shortcut from the action" - what do you mean by this precisely? Thanks

**Comment by jonaski** [comment]
I've pushed a fix 5b60ea8. Apparently configuring F2 for the action (menu item), conflicting with a default shortcut, so you can still use F2 but it doesn't show that on the menu, and it works for all tags now.

**Comment by SimonDedman** [comment]
Gotcha, cheers chap!
