### ISSUE TITLE
Crash after "resource not found"

### ISSUE THREAD

**Issue by cproensa** [strawberrymusicplayer/strawberry#1214]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When trying to play a file that has been removed from the filesystem, an error shows showing "Resource not found", which is understandable. However, the program crashes a few seconds later.
![Captura de pantalla 2023-06-22 235719](https://github.com/strawberrymusicplayer/strawberry/assets/14123811/d069c83f-daf8-4162-97a2-5087c99bd702)

**To Reproduce**
Add a file to the playing list, whether from the collection or directly drag from the explorer window.
Remove, or rename the file, and then start play for that file.
The error is shown, and shortly after, the program closes.

**Expected behavior**
Not crashing :)

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version:  Versión 1.0.17-152-g354b55cb

**Comment by jonaski** [comment]
Might be this bug: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1683

**Comment by jonaski** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4936

**Comment by cproensa** [comment]
Hello
So i tried the latest build and looks good, no crash now... Thanks!

But, i have noticed, probably not related to this issue, but kept me worried:
- StrawberrySetup-1.0.17.164.g2a2663ee-msvc-x64.exe: i experience some stuttering audio when playing. Like some kind of buffering issue.
- StrawberrySetup-1.0.17.164.g2a2663ee-mingw-x64.exe: no issues, no stutter, all good.
- StrawberrySetup-1.0.17-msvc-x64.exe: no issues, no stutter, all good.

Any idea if this is something and how can i get more info and troubleshoot?
Looks like it happens with the current msvc builds (also tried other random daily build), but not in the stable 1.0.17 msvc release, not in any mingw daily build.

**Comment by jonaski** [comment]
With local files, or streams? What output do you have in Backend settings? DirectSound, WASAPI or WASAPI2?
Both MSVC and MinGW has the same version of gstreamer, but the MSVC release has WASAPI2, that's new since 1.0.17, if the output it set to auto, I think it picks WASAPI2, try WASAPI or DirectSound instead.

**Comment by cproensa** [comment]
> the MSVC release has WASAPI2, that's new since 1.0.17

Looks like you are spot on.
msvc 1.017 doesnt include WASAPI2, but the latest builds does have it included.
After switching to any other output configuration, WASAPI1, DrectSound, etc, everything is good.
