### ISSUE TITLE
Integrate Qobuz API

### ISSUE THREAD

**Issue by danir-de** [strawberrymusicplayer/strawberry#1218]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 

**Describe the bug**
Qobuz doesn't issue API keys for personal use anymore, as it was just confirmed to me by mail, so setting it up by using API credentials isn't something that's possible for new users.

**To Reproduce**
Don't have API access already. [Contact Qobuz](mailto:api@qobuz.com) for API access. Get denied.

**Expected behavior**
It should be possible to just log-in into Qobuz via a login form inside the app, you can use to log-in into Qobuz.

Strawberry itself could have a global API key itself or fetch data via the temporary grants given via the user login.

**Comment by jonaski** [comment]
QObuz do not give API access to open source software.
