### ISSUE TITLE
(Windows) Volume resets to 100%, sometimes without UI change

### ISSUE THREAD

**Issue by Lartza** [strawberrymusicplayer/strawberry#1220]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
After updating to 1.0.18, program volume slider seems to be tied to Windows application volume and behave badly. There are two issues of which I can only reproduce one of so far.

In addition to the reproducible scenario below, adjusting volume from Strawberry seems to work for a while (and is synced to Windows) but something causes it to reset to 100% without the visual slider changing, have been unable to reproduce so far.

**To Reproduce**
1. Start Strawberry and Windows app volume at 100% volume
2. Adjust Windows volume to a lower number (this is not reflected in Strawberry)
3. Change song, Windows app volume resets back to 100%

**Expected behavior**
Volume stays synced or the two sliders are separate again.

**System Information:**
 - Operating system: Windows 11
 - Strawberry Version: 1.0.18

**Additional context**
I do believe 1.0.17 had completely separate sliders. FAQ actually says volume SHOULD be separate but it certainly no longer is. Disabling volume control like hinted in the FAQ solves the volume resetting when adjusting from Windows.

**Comment by jonaski** [comment]
I don't have Windows 11 to test on, only Windows 10. But here are the results from my testing:
- directsound, volume sync, but not working at all, working as independent volume.
- wasapi - no volume sync at all.
- wasapi2 - Volume sync, syncs the volume from strawberry back to the windows volume control, but not from the windows volume control back to strawberry, so when you switch song, the windows volume resets back to the last volume set in strawberry.

Looks like gstreamer bugs to me.

**Comment by Lartza** [comment]
The second issue seems to be related to output device switching. With volume control disabled if I have my audio card at 20%, and my integrated audio at 100%, changing from card to integrated and back sets card's app volume to 100% too. My usual setup was to run with 20% card and 100% integrated which is why this is now surfacing on 1.0.18.

If BOTH are set to a value 100% they keep their correct value. This behavior is not replicated with Firefox so does not seem like a Windows bug.
