### ISSUE TITLE
(macOS) Search bars missing

### ISSUE THREAD

**Issue by pietro1704** [strawberrymusicplayer/strawberry#1221]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Qobuz search text bar not available after update to from 1.0.17 to 1.0.18

# On 1.017
<img width="816" alt="Captura de Tela 2023-07-04 às 14 32 11" src="https://github.com/strawberrymusicplayer/strawberry/assets/45739756/54ff9b95-4f0c-4af9-8419-4eda292d8c9a">

## On 1.0.18
<img width="1680" alt="Captura de Tela 2023-07-04 às 14 29 20" src="https://github.com/strawberrymusicplayer/strawberry/assets/45739756/0a72af31-94dd-4989-a68a-849316319408">
8

**To Reproduce**
Updated from official releases 1.0.17 to 1.0.18

**Expected behavior**
Qobuz song search bar shows as expected

 - Operating system: MacOS Ventura13.4.1 (22F82)
 - Strawberry Version: 1.0.18 official release

**Additional context**

**Comment by jonaski** [comment]
It works on Linux and Windows, on mac there is a native search field, I don't have a mac so won't be able to debug it.
The code is here https://github.com/strawberrymusicplayer/strawberry/blob/master/src/widgets/qsearchfield_mac.mm if someone else can to look into it.

**Comment by derwok** [comment]
`qsearchfield_max.mm` did not change in a year.
But the mac file includes `qsearchfield.h` - this was changed betweeen 1.0.17 and 1.0.18:
https://github.com/strawberrymusicplayer/strawberry/commits/master/src/widgets/qsearchfield.h

The above change was done on April, 9 with commit:
https://github.com/strawberrymusicplayer/strawberry/commit/aaa530e72bd7d6d48710bd5ca452da0c01c09997

Just an uneducated guess: could it be that the changes inside above commit ("Add const/references to all signal parameters ") was not reflected in the _mac implementation and now breaks the instatiation of the search bar on macs?

**Comment by clementine-user** [comment]
@jonaski, it seems to be working through strawberry-1.0.17.104.gb52ffd09-x86_64 but it breaks in strawberry-1.0.17.106.g145a8d5b-x86_64 and later.

<img width="1440" alt="strawberry-1 0 17 104 gb52ffd09" src="https://github.com/strawberrymusicplayer/strawberry/assets/6315176/f427506a-25c1-4495-b7af-367669e929d0">

<img width="1440" alt="strawberry-1 0 17 106 g145a8d5b" src="https://github.com/strawberrymusicplayer/strawberry/assets/6315176/5e687703-f75f-42f6-a6b4-4533c9002d49">

**Comment by jonaski** [comment]
It probably broke because of some change in Qt 6.5.1.
I did a bit of a hack because of an issue with the search field not working the cover search, so the search field is actually deleted and re-added each time the window is shown. Might be worth try removing that hack.
If someone builds from source, a possible fix is to move this line to the constructor (`QSearchField::QSearchField`), right before `[pool drain];`, then remove everything in `QSearchField::showEvent` except for `QWidget::showEvent(e);`.
https://github.com/strawberrymusicplayer/strawberry/blob/9fb15545bd10693b1de0b99aa3fd1c5fbbdb38b8/src/widgets/qsearchfield_mac.mm#L242C5-L242C110
Otherwise this have to wait till I get a mac to debug on.

**Comment by jonaski** [comment]
I managed to install macos monterey in a VirtualBox. Looks like this is a Qt bug, it looks to be fixed in the latest Qt from Git.
