### ISSUE TITLE
Ogg Vorbis streams with metadata stop playing after every metadata change

### ISSUE THREAD

**Issue by WildPenquin** [strawberrymusicplayer/strawberry#1224]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When playing Ogg Vorbis (and possibly other) streams with metadata, Strawberry will stop playback on song change (metadata change) with an error dialog.

**To Reproduce**
Play back streams such as: 
- Streams from https://kohina.com/
- Radioparadise ogg vorbis streams with metadata (there is one with and without).

and others.

**Expected behavior**
Playback should not stop. No error dialog should be shown. Song, artist name should be updated in the UI.

**Screenshots:**
The error message (in the dialog):
```
Internal data stream error.

../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesrc.c(3132): gst_base_src_loop (): /GstPlayBin3:pipeline-7-pipeline/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin6/GstSoupHTTPSrc:souphttpsrc12: streaming stopped, reason not-linked (-1)
```

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.18

**Additional context**
This is possibly a long-standing issue reported in Clementine years ago (yes, I have also commented on these bugs):
https://github.com/clementine-player/Clementine/issues/5114
https://github.com/clementine-player/Clementine/issues/5415

(it seems like clementine development has mostly stalled)

It was also established this issue is in the upstream - but there are players which can play said streams with GStreamer. Perhaps they use some ugly workaround despite GStreamer not being able to handle the streams properly? I have no idea since I know nothing about GStreamer and have never worked with it. Case may be this should be fixed upstream, but in the interim worked around in Strawberry - or confirmed the issue is indeed upstream.

At least Strawberry gives a sensible error message, whereas Clementine gets confused giving all kinds of weird behavior as described in the bug reports. So there has been some improvement in this fork!

Cheers!

**Comment by jonaski** [comment]
Looks to be a gstreamer  bug, try something like.:
`gst-play-1.0 --use-playbin3 --audiosink='alsasink device=hw:0,0' http://kohina.duckdns.org:8000/stream.ogg`

For me it stops after every song.

```
Press 'k' to see a list of keyboard shortcuts.
Now playing http://kohina.duckdns.org:8000/stream.ogg
Prerolling...
Redistribute latency...
Redistribute latency...
0:02:25.2 / 99:99:99.       
Buffering... 100%  
ERROR Internal data stream error. for http://kohina.duckdns.org:8000/stream.ogg
ERROR debug information: ../libs/gst/base/gstbasesrc.c(3132): gst_base_src_loop (): /GstPlayBin3:playbin/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin0/GstSoupHTTPSrc:souphttpsrc0:
streaming stopped, reason not-linked (-1)
Reached end of play list.
```

**Comment by jonaski** [comment]
The bug is already reported to gstreamer here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1651

Other players might work because they use the older "playbin2 instead of the new "playbin3" like strawberry does.

**Comment by WildPenquin** [comment]
Ah, that makes it clear then.

I believe it might make sense to close this bug, or perhaps leave open to track if/when the upstream gets fixed, perhaps with some appropriate tag.

**Comment by qarmin** [comment]
I have very similar error sometimes when changing played songs(probably all are mp3) 

```
Internal data stream error.

../libs/gst/base/gstbaseparse.c(3694): gst_base_parse_loop (): /GstPlayBin3:pipeline-37-pipeline/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin36/GstParseBin:parsebin36/GstMpegAudioParse:mpegaudioparse73: streaming stopped, reason not-linked (-1)
```

if problem occurs, second click in music file, properly open and play it.

This is quite random, but with previous versions of app I had no similar problems

**Comment by jonaski** [comment]
@qarmin It's not related to this. Open a new issue if it's still a problem.

**Comment by jonaski** [comment]
This issue is a blocker for a GStreamer 1.22 release (https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1740) so it should hopefully be fix soon.

**Comment by jonaski** [comment]
There is a fix for this here now: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/489f310881ea33ecb9606a6a24449f56250e75c7

**Comment by WildPenquin** [comment]
Hi,

This still seems to be an issue.

I'm not sure but it may have worked a few times over the year or so. But now it seems even worse in a sense, every song change causes Strawberry to crash (listening kohina.com).

This is on Arch, strawberry-1.2.7-2 and gstreamer-1.24.12-3 . I've double checked and gstreamer does have the commit linked above (the source arch PKGBUILD is based on).

Should I open a new issue or this one re-opened?

**Comment by jonaski** [comment]
I suggest to open a new issue since this one is years old. Please include a gdb backtrace and gstreamer debug log.
