### ISSUE TITLE
Collection search bar is invisible

### ISSUE THREAD

**Issue by derwok** [strawberrymusicplayer/strawberry#1225]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
On 1.0.18 (Max OS x86 build) the search bar is invisible

**To Reproduce**
Just launch strawberry

**Expected behavior**
There was a search bar in 1.0.17

**Screenshots:**
![grafik](https://github.com/strawberrymusicplayer/strawberry/assets/4393698/71da143d-5775-47d6-8034-2fb935472da5)

**System Information:**
 - Operating system: MacOSX 12.6.3 (21G419)
 - Strawberry Version: 1.0.18

**Additional context**
While the search bar is invisible, the search **tooltip**(!) shows up, if I hover on the search area
![grafik](https://github.com/strawberrymusicplayer/strawberry/assets/4393698/8637482a-fa04-4f4e-92af-1e1ad2973043)

**Comment by jonaski** [comment]
All search bars are missing 1.0.18 on macOS, this is the same issue as #1221
