### ISSUE TITLE
(Windows) Choppy audio with WASAPI2

### ISSUE THREAD

**Issue by dbolton** [strawberrymusicplayer/strawberry#1227]
**Describe the bug**
Choppy audio during normal playback.

**To Reproduce**
Play audio file from local computer using Strawberry. 

**Expected behavior**
Accurate playback of the audio file. 

For comparison, other audio players, all play the same file without choppy audio. I tested using Clementine, Exaile, foobar2000 and Groove.

**Screenshots:**
I recorded playback for the purpose of sharing with this ticket. 
[choppy audio.zip](https://github.com/strawberrymusicplayer/strawberry/files/11995875/choppy.audio.zip)
(3 second sample. Choppy audio starts at 1.0 seconds. Ends at 1.5 seconds)

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 1.0.18 (MSCV installer)

**Additional context**
In case it is important, my audio files happen to all be FLAC format. 

I opened the task manager to check CPU usage. It is never above 30% during the choppy audio.

**Comment by LebedevRI** [comment]
Is that using VLC engine by any chance?

**Comment by jonaski** [comment]
What output are you using in the Backend settings? Auto, Directsound, WASAPI or WASAPI2?
What buffer settings?
I can't reproduce any issues with any of the outputs even under CPU load.
What CPU and hard-drive do you have?

**Comment by dbolton** [comment]
I had been using the default "Wrapper audio sink for automatically detected audio sink". I switched to "Output to sound card via Direct Sound". After restarting Strawberry I no longer have issues. 

So it looks like this issue is limited to the wrapper? Also is it expected that restarting Strawberry is necessary after switching the backend? If so, maybe label that could be marked in the settings (like other setting changes that require restart). 

Processor: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz   2.19 GHz
Hard disk: Samsung SSD 850 EVO

**Comment by jonaski** [comment]
If Auto is selected, the MSVC version will pick WASAPI2. The MinGW will pick DirectSound if Auto is selected.
So it looks like WASAPI2 is buggy, even though I can't reproduce any issues here.
Same issue was reported in #1214 by @cproensa

**Comment by cproensa** [comment]
> Same issue was reported in https://github.com/strawberrymusicplayer/strawberry/issues/1214 by @cproensa

Right, For me WASAPI2 was also choppy and stuttering. 
It starts fine, but after some time playing (a couple of minutes, maybe), the chopper starts. Regardles of stopping and resuming playback or playing different files. Once it starts, its consistent and ongoing.

However, i dont have a very common or solid setup, to represent a good example. This is: its a firewire (presonus firestudio mobile) external soundcard (with custom drivers). Which already experiences some stuttering when a high load of network activity or file copying is happening. Probably some dma or latency shenanigans with the firewire bus.  (but not affected by cpu load though).


>  Also is it expected that restarting Strawberry is necessary after switching the backend

In my case. Only STOP playing was enough to change the output.

**Comment by jonaski** [comment]
The bug is probably in GStreamer, I will add an entry to the FAQ about it for now.

**Comment by Kissaki** [comment]
I have no issue with local playback, but when streaming my desktop/PC to Steam Link - so the audio output device changes to it - I hear chopped up audio too. May be on Opus files but not on mp3.

**Comment by jonaski** [comment]
Can someone test the latest from https://builds.strawberrymusicplayer.org/windows/msvc/, there is an utility `gst-play-1.0.exe`, check if the issue occurs also using this utility.:

    cd "c:\Program Files\Strawberry Music Player"
    gst-play-1.0 --use-playbin3 --audiosink='wasapi2sink' file:///c:/music/test.flac

Replace `c:/music/test.flac` with an actual file.

**Comment by jonaski** [comment]
I've changed the priority of the output/sinks so that directsound is picked first when Auto is selected (483b42d).
This issue is reported to GStreamer here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/2870

**Comment by dbolton** [comment]
@jonaski Thanks for looking into this. I downloaded the latest msvc-x64.exe. I followed your commands, but got the following error: 
`Failed to create 'playbin' element. Check your GStreamer installation.`

Do I need to install anything besides Strawberry Music Player? I do see gst-play-1.0.exe in the current directory.

**Comment by cproensa** [comment]
> I downloaded the latest msvc-x64.exe. I followed your commands, but got the following error:
> `Failed to create 'playbin' element. Check your GStreamer installation.`

same for me

**Comment by jonaski** [comment]
Run this command first:
`set GST_PLUGIN_PATH=c:/Program Files/Strawberry Music Player/gstreamer-plugins`

**Comment by dbolton** [comment]
I set the variable then reran the original command, but got the same error. Any other tips?

**Comment by cproensa** [comment]
With the env set, the command now plays the file.
But, still, crackling is reproduced after a couple of minutes.
If i retry the command, even with other files, its random. Sometimes the noise starts right away, other times the sound is good but only for some time until it goes bad again.

![imagen](https://github.com/strawberrymusicplayer/strawberry/assets/14123811/d115d85b-8cb4-48cb-a855-26039406103d)

**Comment by jonaski** [comment]
Thanks @cproensa

**Comment by jonaski** [comment]
I've removed WASAPI2 in the newest release, I will add it back when the issue is solved in GStreamer.
