### ISSUE TITLE
Album Covers not loading for tracks present before 1.0.18

### ISSUE THREAD

**Issue by Dakes** [strawberrymusicplayer/strawberry#1230]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Since the update to 1.0.18 album covers for previously existing tracks do not load any more. It doesn't matter if the album covers are embedded, or present in the album folder. Even if the filename corresponds to the filename pattern set in the settings. The order in the "Album cover types" setting also does not affect the issue. 
I have to manually reload the cover, either from disc, or from an online provider, for it to show again. After that it loads consistently again. 

Edit: I just noticed: For *some* albums the covers still load, but for most they are broken. But I don't see any pattern in, which covers load and which don't. For one artist one album seems to load the cover, the other doesn't. Both with the same audio file type and the cover saved to disk. Also it doesn't work both with flac files and mp3. 

**To Reproduce**
Try to play a song, that had a correctly loading cover  in a pre 1.0.18 version, after the update to 1.0.18. 

**Expected behavior**
The expected behavior is to look for covers in the album folder, or load the embedded cover, if no cover was found. 

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.18

**Additional context**
Calling it with `--verbose` does not give any error about album covers.

**Comment by jonaski** [comment]
Is this collection songs?
Right click on the song and check the summary tabs, what does it say for art at the bottom?
In Tools / Console, do.: `select url, art_embedded, art_automatic, art_manual, art_unset from songs;`
Does the album cover files show there?

**Comment by Dakes** [comment]
Yes I was referring to local songs from the collection, as part of normal playlists. 
I didn't know you could check this information on the summary page. 
I have seen a few different behaviors there:

1.
```
Cover displayed in summary, but not displayed in player.
Art Embedded: yes
Art Manual: None
Art Automatic: (embedded)
Art Unset: No
Once I click save and replay the track, the cover gets displayed as regular. 
When I click Discard, the cover does not get displayed. Even though it was shown on the summary page. 
```

2.
```
Cover loads correctly to begin with and is displayed in summary
Art Embedded: No/Yes  (I found both in this scenario)
Art Manual: path to correct cover.jpg / None
Art Automatic: path to correct cover.jpg
Art unset: No
```

3.
```
Cover not showing in Summary and not in player
Art Embedded: No
Art Manual: path to file in "~/.config/Clementine/albumcovers/" ¯\_(ツ)_/¯
Art Automatic: path to cover in album folder
Art Unset: No
```

4.
```
Cover not showing in Summary and not in player
Art Embedded: No
Art Manual: None
Art Automatic: path to cover in album folder
Art Unset: No
```

\
\
I executed the query, you provided for a specific track and I think I might have found the root cause of the problem. The shown cover points to the correct file, but it found 2 tracks and the cover is only set for one. This is also a weird issue I had for a while, but kind of ignored. In the Collection tab some tracks have duplicate entries. And a full collection rescan didn't help. 
```
> select url, art_embedded, art_automatic, art_manual, art_unset from songs where title = "Future" and album = "TOKYO NEO SWING";
file:///home/dakes/Music/DYES%20IWASAKI/DYES%20IWASAKI%20-%20TOKYO%20NEO%20SWING/01-05-Lily_Mizusaki-Future-LLS.flac|0|(embedded)||0
file:///home/dakes/Music/DYES%20IWASAKI/DYES%20IWASAKI%20-%20TOKYO%20NEO%20SWING/01-05-Lily_Mizusaki-Future-LLS.flac|1|file:///home/dakes/Music/DYES%20IWASAKI/DYES%20IWASAKI%20-%20TOKYO%20NEO%20SWING/tokyo-neo-swing-dyes-iwasaki.jpg||0
```
For this track the cover does not show in the player, but is displayed on the Summary page (as a Cover from embedded image.)
```
Art Embedded: Yes
Art Manual: None
Art Automatic: (embedded)
Art Unset: No
```

**Comment by jonaski** [comment]
art_automatic shouldn't have (embedded) anymore, so but use art_embedded instead, to fix that you can probably manually run the following queries in Tools / Console:
```
UPDATE songs SET art_embedded = 1 WHERE art_automatic = (embedded)';
UPDATE songs SET art_automatic = '' WHERE art_automatic = '(embedded)';
```

**Comment by jonaski** [comment]
A full collection rescan should fix both embedded art and automatic art (covers from the directory), but won't do anything with art_manual.

**Comment by Dakes** [comment]
These updates fixed it. Thank you so much.  🙏
