### ISSUE TITLE
Strawberry 1.0.18 not in PPA

### ISSUE THREAD

**Issue by joshstoik1** [strawberrymusicplayer/strawberry#1231]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

Hi there,

Last week's `1.0.18` release hasn't shown up in the stable [Ubuntu PPA](https://launchpad.net/~jonaski/+archive/ubuntu/strawberry) yet. I'm not sure if that's intentional or not, but wanted to flag it with you just in case.

Thanks!

**Comment by jonaski** [comment]
Fixed now
