### ISSUE TITLE
Preloading seems to not be working (as expected?)

### ISSUE THREAD

**Issue by LebedevRI** [strawberrymusicplayer/strawberry#1233]
(currently, preloading seems to be done by setting an `url`, and "hoping" it'll buffer)

If two songs that are to be played back-to-back
are also located back-to-back in their source (file),
then it does seem like the playback is virtually gap-less.

However, in other situations, the results are somewhat unexpected to me.
E.g. if there are 4 songs in the file, and we first play 3'th, and then 2'th,
i would expect us to just `Seek` to it, but a new pipeline is created instead.
(even when no fading is enabled)

But if we create a new pipeline, then our preloading efforts were wasted, weren't they?
Moreover, we can't really preload a specific Song, can we?

More generally, is it intentional that preloading isn't implemented as just creating a new pipeline,
letting it buffer, and then just starting it when we'd normally create it in `Load()`?

**Comment by jonaski** [comment]
Preloading is done by setting the next URL in `GstEnginePipeline::SetNextUrl`, it should create a new pipeline only when cross-fading.
For CUE, the song is switched in `BufferProbeCallback()`. Although I don't use CUE I don't regularly test that.

**Comment by jonaski** [comment]
By the way, it would be nice if you could have a look at #1123.

**Comment by LebedevRI** [comment]
> Preloading is done by setting the next URL in `GstEnginePipeline::SetNextUrl`,

Yep, i have stepped through all that in debugger multiple times.

> it should create a new pipeline only when cross-fading.

Ok, so that confirms to me that in principle preloading is considered a feature and not a happenstance.
(i.e. this is not a NOTABUG)

> For CUE, the song is switched in `BufferProbeCallback()`. Although I don't use CUE so I don't regularly test that.

I see. That is clearly not what is happening in CUE case,
and i don't think the current approach _can_ work for CUE's
(since it preloads at +0 seconds into the file, and song can be anywhere).
At least i'm not sure how it can work in that case.

**Comment by jonaski** [comment]
> I see. That is clearly not what is happening in CUE case, and i don't think the current approach _can_ work for CUE's (since it preloads at +0 seconds into the file, and song can be anywhere). At least i'm not sure how it can work in that case.

You are right, the way it is will only work when the next song in playlist is the next segment of the file.
To implement fully gapless for CUE, we probably can't use about-to-finish (https://gstreamer.freedesktop.org/documentation/playback/playbin3.html?gi-language=c#playbin3::about-to-finish), we probably have to create a new pipeline. If you you want to implement that, it would be great, but I probably won't do it.

**Comment by LebedevRI** [comment]
> To implement fully gapless for CUE, we probably can't use about-to-finish (https://gstreamer.freedesktop.org/documentation/playback/playbin3.html?gi-language=c#playbin3::about-to-finish), 

(There's also the question of gap-less playback between songs of two different CUE's.)

> we probably have to create a new pipeline.
> If you you want to implement that, it would be great, but I probably won't do it.

Aha! That's exactly what i hoped to hear :)

**Comment by LebedevRI** [comment]
Looking more into this, the current approach of noticing that CUE song has ended
via `BufferProbeCallback()` kind-of does not really work, because the segment we get
is not guaranteed whatsoever to **not** contain a few samples of the next CUE song,
and then there's latency between when we've noticed that the song has ended
and emit an event for it, and when we handle that event. It's not critical for HUD,
but annoying for loudness normalization purposes. (and may result in stopping playback too late)

There's apparently [`concat`](https://gstreamer.freedesktop.org/documentation/coreelements/concat.html?gi-language=c) element, which i *hope* will be able to help
retain perceived gap-less-ness in contiguous CUE case, and gain it in other cases,
*and* get rid of at least some of mentioned glitches.
