### ISSUE TITLE
Saving track information during playback causes delayed temporary pause/stutter

### ISSUE THREAD

**Issue by Kissaki** [strawberrymusicplayer/strawberry#1236]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When using the track information dialog or the Rating column to save track information the playback jumps and/or pauses - seemingly after the playback buffer has been played.

**To Reproduce**
Play file, CTRL+E, set rating, save.

**Expected behavior**
The audio playback continues without interruptions

**System Information:**
 - Operating system: Windows 11
 - Strawberry Version: 1.0.18

**Additional context**
The playback buffer (of 4 s) should give enough time to store the file to disk and reopen the file to continue playback.

**Comment by jonaski** [comment]
What format is this?

**Comment by wjandrea** [comment]
I'm having this issue with MP3s, but then, they're stored on a network drive so maybe the buffer isn't long enough.

**Comment by jonaski** [comment]
Unfortunately there is no easy way save tags to currently playing files without shutter, other than delaying saving tags to the file which causes other issues. But a solution could be to have an option to buffer the entire song, we already have issue #1333 for that.
