### ISSUE TITLE
Crashes when moving songs inside playlist

### ISSUE THREAD

**Issue by nokia8801** [strawberrymusicplayer/strawberry#1245]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When trying to organize and move songs inside the playlist with the mouse, as soon as you move a song from its original position, strawberry crashes.

**To Reproduce**
Try to move a song inside the playlist.

**Expected behavior**
Song should move to its new place.

**Screenshots:**
https://github.com/strawberrymusicplayer/strawberry/assets/136886711/a827c396-793e-4571-a7a6-d6eaa32d8626

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.18
 - QT Version 6.5.2 using qt6-wayland
 - GNOME 44.3 on Wayland

**Additional context**
[log.txt](https://github.com/strawberrymusicplayer/strawberry/files/12158833/log.txt)

**Comment by inemum** [comment]
I can confirm this bug. Seems to be Wayland-specific, no crashes on XWayland.

**Comment by jonaski** [comment]
This looks like a Qt bug. I can't reproduce this with Qt 6.5.2 using qt6-wayland on KDE Plasma with Wayland.

**Comment by jonaski** [comment]
Since I can't reproduce this on openSUSE, it could be specific to Arch or Gnome, at least it's not a strawberry bug. I suggest to report this to Arch, try triggering a rebuild of the wayland plugin to see if it fixes it, or report the issue to Qt if it persists.

**Comment by nokia8801** [comment]
I just want to update this bug. The update to qt6-wayland 6.5.2-2 has fixed this issue. Here is the full link to the commit that fixed it.

https://gitlab.archlinux.org/archlinux/packaging/packages/qt6-wayland/-/commit/d74589ff924611a20dca428a3bac30056b1ec669
