### ISSUE TITLE
Crackling/popping in the audio

### ISSUE THREAD

**Issue by SamuelBucher** [strawberrymusicplayer/strawberry#1247]
- [ + ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ + ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ + ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Crackling/popping in the audio.

**To Reproduce**
Seems to begin and end at random. When this starts, audio from other applications is unaffected. I'm sorry that I can't be more informative on reproducing this.

**Expected behavior**
Clear audio, obviously.

**Screenshots:**
Recording of this happening: https://files.catbox.moe/4h94mg.mp4

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 1.0.18

**Additional context**
N/A

**Comment by jonaski** [comment]
What output are you using in the Backend settings? Auto, Directsound, WASAPI or WASAPI2?
What buffer settings? Is it the msvc or mingw version?

**Comment by SamuelBucher** [comment]
Auto
4000ms, 0.33 LW, 0.99 HW
Probably MSVC, but I don't remember. How do I check?

**Comment by jonaski** [comment]
Maybe this a duplicate of #1227
In the MinGW version most installed DLL's start with "lib", while the MSVC almost all files start without "lib"
MinGW:  https://github.com/strawberrymusicplayer/strawberry/blob/f5a55abf58030bbcd65f36c16a0434cf1983543a/dist/windows/strawberry.nsi.in#L241
MSVC file list: https://github.com/strawberrymusicplayer/strawberry/blob/f5a55abf58030bbcd65f36c16a0434cf1983543a/dist/windows/strawberry.nsi.in#L397

**Comment by SamuelBucher** [comment]
I have the MSVC version.

**Comment by SamuelBucher** [comment]
Looks like this is, indeed, a duplicate. My apologies.
