### ISSUE TITLE
Ratings not shown in list

### ISSUE THREAD

**Issue by GrandeDominus** [strawberrymusicplayer/strawberry#1249]
Hello,

Why are some ratings not displayed for entire playlist? 

On another playlist they are displayed.

I´m still able to edit the rating through "Edit track information" in the context menu.

Thanks!

![image](https://github.com/strawberrymusicplayer/strawberry/assets/82435373/00d60e5a-38b6-4796-b126-21272a062a82)

![image](https://github.com/strawberrymusicplayer/strawberry/assets/82435373/f345baf9-8d9a-4675-89b1-f53e3588b89e)

**System Information:**
 - Operating system: Debian 11
 - Strawberry Version: 1.0.18

**Comment by jonaski** [comment]
What audio format, and rating tags is this? It's most likely a type that isn't supported by Strawberry.

**Comment by GrandeDominus** [comment]
> What audio format, and rating tags is this? It's most likely a type that isn't supported by Strawberry.

They are all MP3. I´m not sure how to check what type of rating tags they are. How would I change them and what is supported? It works going through context menu but not in the table.

![image](https://github.com/strawberrymusicplayer/strawberry/assets/82435373/fed416a0-35c1-473d-8c6b-f83d836e251e)

![image](https://github.com/strawberrymusicplayer/strawberry/assets/82435373/20361a88-cff3-4957-9852-3a1467db9bb4)

**Comment by jonaski** [comment]
For ID3v2, strawberry reads both POPM (Popularimeter) and `FMPS_Rating`.
When looking at your screenshots, it seems the songs are added from outside of the collection where ratings are not supported.
Add the playlist source column and check if there is vinyl (collection) icon, or a folder icon.

**Comment by GrandeDominus** [comment]
> For ID3v2, strawberry reads both POPM (Popularimeter) and `FMPS_Rating`. When looking at your screenshots, it seems the songs are added from outside of the collection where ratings are not supported. Add the playlist source column and check if there is vinyl (collection) icon, or a folder icon.

![image](https://github.com/strawberrymusicplayer/strawberry/assets/82435373/ceece429-f9e5-4e41-b925-3a5dd1c9fd7c)

What do you mean that they are added from outside of the collection?

**Comment by jonaski** [comment]
Instead of dragging files from a file manager or adding from the Files view, or Playlist / add file, drag or right click in the collection tree when you add songs. Usually songs that are in the collection should be linked to the collection anyway, but in case of symlinks it might not always be the case, or in case you added the folders to the collection after you added the songs to the playlist.
You probably have to re-create the playlist to make it work with ratings.

**Comment by shoalcreek5** [comment]
Yea. Thanks to this bug where it can't cross reference songs in a saved playlist with song in the collection, it lead to Strawberry wiping out thousands of song in my collection when trying to add them to the collection from a playlist...NEVER USING STRAWBERRY AGAIN!

**Comment by shoalcreek5** [comment]
That while the songs from the saved playlist WERE ALREADY IN THE COLLECTION.
