### ISSUE TITLE
[Feature Request] Add Group by Folder name in the Collection

### ISSUE THREAD

**Issue by alphonse-rms** [strawberrymusicplayer/strawberry#1251]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
This is not a bug but I d like to have a grouping by **folder name** since my entire music library is already organized by folders.

**To Reproduce**
Collection display options > Group by

**Expected behavior**
Having a group by Folder option.

**Screenshots:**
No need screenshot.

**System Information:**
 - Operating system: Ubuntu 22.04
 - Strawberry Version: 1.0.18

**Comment by jonaski** [comment]
We currently do not accept feature requests on GitHub due to lack of contributors.
