### ISSUE TITLE
"Desktop file name" window property doesn't match .desktop filename

### ISSUE THREAD

**Issue by haizaar** [strawberrymusicplayer/strawberry#1254]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Good day. On Wayland, the window icon is set by finding a `.desktop` file that matches window's `Desktop file name` property. For Strawberry, they mismatch - the shipped desktop file is named `org.strawberrymusicplayer.strawberry.desktop` while the the "Desktop file name" window property is set to `org.strawberrymusicplayer.`

Can you please update the app to make those match? I believe calling 
```cpp
a.setDesktopFileName("org.strawberrymusicplayer.strawberry");
```
somewhere after [this](https://github.com/strawberrymusicplayer/strawberry/blob/d2390473bcee2a0afc47913a93b1573f51c5c575/src/main.cpp#L191) line is all that is needed.

**To Reproduce**
Run Strawberry on Wayland observe no eye-candy
![image](https://github.com/strawberrymusicplayer/strawberry/assets/58201/523212d2-ceb2-48c4-bd41-ddb687eb077c)

**Expected behavior**
The strawberry icon should appear in the window title and task bar.

**Screenshots:**

**System Information:**
 - Operating system: NixOS 23.05
 - Strawberry Version: 1.0.17

**Additional context**
- [XDG ref](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id)
- [QT Snippet](https://bugreports.qt.io/browse/QTBUG-77182?focusedId=728535&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-728535)

**Comment by jonaski** [comment]
I read somewhere that if the desktop file isn't set, organization domain + application name should be used as desktop file. And organization domain is set to "strawberrymusicplayer.org" and application is set to "strawberry". So I'm not sure why that isn't working. Where do you see "org.strawberrymusicplayer." ?
