### ISSUE TITLE
Text is misrendered in QSearchField

### ISSUE THREAD

**Issue by jirislaby** [strawberrymusicplayer/strawberry#1255]
**Describe the bug**
The text I write to QSearchField in the top of the main window is misrendered as can be seen in the screenshot.

**To Reproduce**
 * start strawberry on primary monitor (on secondary, this does not happen)
 * maximize it (it doesn't happen on non-maximized windows)
 * type in the field

**Expected behavior**
The typed text can be seen. Note that it is re-rendered correctly upon minimizing->maximizing it. Also by moving to the other monitor and back. So I suppose there is some weird rendering while typing on screens configured some way (see below).

**Screenshots:**
![straw](https://github.com/strawberrymusicplayer/strawberry/assets/530775/32a25bf3-ae15-4894-9af2-37d975dcfebb)

**System Information:**
 - Operating system: Linux, qt6, wayland, screens are scaled up (the primary one is full HD at 125 %, secondary is 4k at 150 %)
 - Strawberry Version: 1.0.18

**Comment by jonaski** [comment]
I can reproduce this with 125% scaling, but only on the playlist search field, not the collection search field. I'm not sure why since they both use the same search widget.

**Comment by jonaski** [comment]
Took me many hours to figure this out, turns out it's the global stylesheet strawberry uses which has a specific style for QToolButton which is supposed to be used for the collection options (tool) button in the search, but the search field's clear button is also a QToolButton, since the style got applied there too things gets weird.

**Comment by jirislaby** [comment]
Thanks, but it does not help completely. While it is fixed for a maximized window, I still see that with a non-maximized one. This is with 1.0.23 and 6d52a2b4095b1ee13fe9806c2f7a9b223c4ef489, 72bccad82d0605b7de2c553657fc90cfd7aa12af applied.
![Screenshot_20240226_080247](https://github.com/strawberrymusicplayer/strawberry/assets/530775/540321f9-1742-4c47-94be-449624741700)

Another issue is that even if I type and can see it maximized, the list of songs is not redrawn (I have to hover with mouse or minimize+maximize the window to see it updated).
