### ISSUE TITLE
Current song restarts after click on the seek bar

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1258]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
After click on the seek bar, the current song restarts instead of playing from the point clicked in the seek bar.

**To Reproduce**
1. play a song
2. 5 seconds before the song ends, backward it by clicking on the seek bar
3. if the song did not restart after the previous steps, repeat the step 2 a few times. At some point the current song will restart.

**Expected behavior**
the song should always play from the point clicked in the seek bar

**Screenshots:**

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.18

**Comment by jonaski** [comment]
Possible fix 76fa4745d0a261d35fd517ac0e05bc3b8ddeb239
If possible try with the latest code from master including 76fa4745d0a261d35fd517ac0e05bc3b8ddeb239

**Comment by glaubersm** [comment]
I have just installed strawberry_1.0.20-22-g2a9b3269-jammy_amd64.deb.
The bug is still reproducible.

**Comment by glaubersm** [comment]
Cannot reproduce with "auto" output, but cannot with PulseAudio output.

**Comment by jonaski** [comment]
I could reproduce it with both. I suspect this might be a GStreamer bug, there was a problem with the seek being to fast when seeking after the next URI was set, I've fixed it by delaying the seek a bit (not noticeable).
