### ISSUE TITLE
I couldn`t change the language in the desctop app

### ISSUE THREAD

**Issue by Veatrix** [strawberrymusicplayer/strawberry#1269]
**Describe the bug**
When I open Strawberry today I found out that it`s in russian and I couldn`t switch the language at all.

**To Reproduce**
1. I open the desctop app today and found out that language is russian (it was Ukrainian before).
2. I tried to switch it to Ukrainian, English or Czech in the Settings.
3. It does not work after I click Apply and OK

**Expected behavior**
I expected my language will not change after update or due to some kind of bug.

**System Information:**
 - Operating system: Fedora Linux 38
 - Strawberry Version: 1.0.18

![ksnip_20230912-114812](https://github.com/strawberrymusicplayer/strawberry/assets/75695268/6549522d-a0fb-4406-9e5d-1e4c5d2f49e6)
![ksnip_20230912-115143](https://github.com/strawberrymusicplayer/strawberry/assets/75695268/ff95e966-f517-498a-af5d-782f88857827)

**Comment by jonaski** [comment]
The language does not take affect until you restart strawberry.
