### ISSUE TITLE
Symbol Lookup Error on latest OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by ve4grm** [strawberrymusicplayer/strawberry#1270]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
On OpenSUSE Tumbleweed, after a recent update, opening Strawberry fails silently.
Opening it through the terminal produces the following error:
`strawberry: symbol lookup error: strawberry: undefined symbol: _ZN6google8protobuf8internal17AssignDescriptorsEPFPKNS1_15DescriptorTableEvEPN4absl12lts_202301259once_flagERKNS0_8MetadataE`

**To Reproduce**
Using OpenSUSE Tumbleweed, attempt to open Strawberry.

**Expected behavior**
Strawberry opens.

**Screenshots:**
N/A

**System Information:**
 - Operating system: OpenSUSE Tumbleweed
 - Strawberry Version: Strawberry 1.0.18, from Tumbleweed repo

**Additional context**
It stopped working after I updated on Sept 8, 2023. I had last updated around Sept 1, 2023, at which point it was still working.
I assume this is a removed or changed dependency from OpenSUSE's side, but I'll probably need to know what dependency it is to report it to them.

**Comment by jonaski** [comment]
This is because of recent protobuf update and strawberry needs a rebuild. It's already reported to openSUSE here: https://bugzilla.opensuse.org/show_bug.cgi?id=1215227

**Comment by jonaski** [comment]
Strawberry works again now in the latest tumbleweed version (20230921).
