### ISSUE TITLE
Volume setting is not saved consistently, after program restarts

### ISSUE THREAD

**Issue by cproensa** [strawberrymusicplayer/strawberry#1272]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Volume setting is not saved consistently, after program restarts.
I suspect, that force closing the application, makes the volume setting not to be saved.
I notice this behaviour because usually once the app is started, i dont close it manually and is kept in the tray until it chrashes or the system restarts. On next startup, I usually find the volume setting is not remembered from the latest adjustment.

**To Reproduce**
Change volume setting in the widget, kill the application, e.g. from task manager.
After restarting the app the volume setting does not show the latest change.

**Expected behavior**
volume changes should be persist in shorter term

**System Information:**
 - Operating system:  windows 10
 - Strawberry Version: 1.0.18-140

**Comment by jonaski** [comment]
Volume is only saved on exit, so if you force-fully close strawberry then it won't be saved. This is intentional to prevent excessive writing to disk, it's the same thing with window positions and a few other things.

**Comment by cproensa** [comment]
> This is intentional to prevent excessive writing to disk

Right, i understand.
Could it be reasonable to save this data in a sufficient long interval? eg: 30 mins?
