### ISSUE TITLE
GStreamer could not create the element bs2b with name pipeline-**-bs2b.

### ISSUE THREAD

**Issue by SnootyInk8302** [strawberrymusicplayer/strawberry#1273]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 

**Describe the bug**
Hello, recently I wanted to try out the bs2b feature after seeing it in the settings, but it seems that whatever I try to do I just get this error: GStreamer could not create the element bs2b with name pipeline-**-bs2b. I usually output the sound directly to my Audio Interface using ALSA, so ofc I tried that setting first. Sadly it didn't work. I then proceeded to try sending the audio through PulseAudio, then with OpenAL but it still outputs the same error. I then tried to install all the gstream packages, but it looks like I already have all of them. Tools, bad, good, base, ugly. There doesn't seem to be an entry of how to configure it on the Strawberry wiki, so I'm confused. Is this error only on my part or is this a bug? I use Ubuntu Budgie 22.04 by the way. Thank you!

**To Reproduce**
Check the setting in the Backend tab

**System Information:**
 - Operating system: Ubuntu Budgie 22.04 LTS
 - Strawberry Version: Version 1.0.18

**Comment by jonaski** [comment]
Did you have `gstreamer1.0-plugins-bad` installed and the file `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstbs2b.so`?
if so check that is is detected with: `gst-inspect-1.0 bs2b`

**Comment by SnootyInk8302** [comment]
Yes I do seem to have `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstbs2b.so` and `gst-inspect-1.0 bs2b` seems to detect it. here is the output: https://pastebin.com/fYU3ZQqV

**Comment by jonaski** [comment]
Try removing the gstreamer plugin cache (Quit strawberry first):
`rm -rf ~/.cache/gstreamer-1.0`

**Comment by SnootyInk8302** [comment]
Still not working. If it helps, I get this output when I start Strawberry through the console: 
`00:32:28.765 ERROR GstEnginePipeline:282            GStreamer could not create the element "bs2b" with name "pipeline-4-bs2b"`
I also installed the app through flatpak. Maybe that could also help.

**Comment by jonaski** [comment]
If you are using the flatpak, it won't help to install gstreamer packages from the distribution.
This is likely an issue of missing flatpak gstreamer plugins
I suggest to try flatpak support https://flatpak.org/about/ or https://discourse.flathub.org/

**Comment by SnootyInk8302** [comment]
Oohhh, thank you very much and sorry for tge inconvenience.
