### ISSUE TITLE
ZIP archives are cataloged as songs which cannot be played

### ISSUE THREAD

**Issue by polsvoice** [strawberrymusicplayer/strawberry#1274]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
ZIP archives are added to the Collection as songs. When they show up in playlists, such as the smart playlist "dynamic random mix", these "songs" don't play. Instead, Strawberry just gets stuck buffering, and you have to manually switch to a different song.

If you manually try to play one of these archives (e.g. by double-clicking it in a playlist), you get this error:

```
Internal data stream error.

../gstreamer/subprojects/gstreamer/plugins/elements/gsttypefindelement.c(1257): gst_type_find_element_loop (): /GstPlayBin3:pipeline-5-pipeline/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin14/GstParseBin:parsebin16/GstTypeFindElement:typefind: streaming stopped, reason not-linked (-1)
```

**To Reproduce**
Add a ZIP file to one of the folders used for your Collection. Re-scan your Collection by going to **Tools > Update changed collection folders**. Open your collection and double-click one of the archive files to add it to a playlist, and then double-click it in the playlist.

**Expected behavior**
I expected archives to be ignored and not cataloged.

**Screenshots:**

**System Information:**
 - Operating system: Garuda Linux Soaring, kernel Linux 6.5.3-zen1-1-zen
 - Strawberry Version: 1.0.18

**Comment by jonaski** [comment]
I can't reproduce this. No zip files are added to the collection here.
What version of TagLib are you using?
Does the zip archives contain audio files, if so what format?

**Comment by tormol** [comment]
Thank you for fixing it despite marking it need-more-info!
I just experienced this issue with the strawberry version in Debian 12 (v1.0.14, with libtag1-dev v1.13-2), and building from master fixed it.

**Comment by jonaski** [comment]
I just added a workaround ignoring all known file extensions for compressed formats. The bug is really in the TagLib library, because Strawberry adds all files that TagLib can identify tags for independent of file extension. Because Strawberry doesn't hard-code any formats it supports anywhere since the supported formats really depends on GStreamer and what GStreamer plugins are installed, and GStreamer supports all formats TagLib support and much more.
