### ISSUE TITLE
[windows] dark mode breaks on category bar

### ISSUE THREAD

**Issue by back-lacking** [strawberrymusicplayer/strawberry#1275]
- [x ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When in dark mode, the bar for sorting the songs by name, album, etc, is just white. the text is unreadable. 
This is bar im talking about and what it looks like at the moment 
![image](https://github.com/strawberrymusicplayer/strawberry/assets/86173810/341b58a8-1606-4434-9320-c4ab5315007e)

**To Reproduce**
1. Set theme to Fusion
2. Set tabbar colors to follow system colors

**Expected behavior**
the bar should look like something like this. original image taken from this issue #1125 
![215404691-279e3033-ed50-4f80-9d92-bb37e33f1f8b](https://github.com/strawberrymusicplayer/strawberry/assets/86173810/c9b6bbb7-a988-4ddf-a4a3-3050207822db)

**System Information:**
 - Operating system: Windows 10 22H2
 - Strawberry Version: 1.0.18

**Comment by jonaski** [comment]
This is a Qt bug, needs to check if it is fixed or report to Qt.

**Comment by back-lacking** [comment]
> This is a Qt bug, needs to check if it is fixed or report to Qt.

which qt repo do i report it to? im looking at the github page and theres a bunch of repos for qtbase, qt5, qtwebengine, etc.

**Comment by jonaski** [comment]
I think the bug is in Strawberry, related to a custom style used.

**Comment by jonaski** [comment]
This should be fixed, you can try the latest from https://builds.strawberrymusicplayer.org/windows/ if you want the fix before the next official version.

**Comment by back-lacking** [comment]
> This should be fixed, you can try the latest from https://builds.strawberrymusicplayer.org/windows/ if you want the fix before the next official version.

![image](https://github.com/strawberrymusicplayer/strawberry/assets/86173810/3fccbaa3-3f60-4ddd-83d4-624f44561d43)
just installed mingw build. is there a way to easily grab the logs made by strawberry? there was a cmd window with some logging and i want to see if i can get that into a text file so that i can send over to you.

**Comment by back-lacking** [comment]
oop, found the cmd window, and just pt the text into a pastebin 
https://pastebin.com/PbaZ0FpQ

**Comment by back-lacking** [comment]
unable to run the msvc build. it will just spit out these errors
![WindowsTerminal_geYMEHriTe](https://github.com/strawberrymusicplayer/strawberry/assets/86173810/fd031aa3-aa9e-41ff-ba06-ba78e4aaa4db)

**Comment by jonaski** [comment]
You picked the oldest dev release without the fix, look at the dates, you should pick from the newest at bottom of the list that is for x86_64 without debug, the newest now is 1.0.20.31.geee0c401.
The MSVC debug ones require a full Visual Studio 2022 installation, not just Visual C++ redist, unless you really need to debug something pick the ones without debug.

**Comment by back-lacking** [comment]
oh, mb
testing with newest release now

**Comment by back-lacking** [comment]
![image](https://github.com/strawberrymusicplayer/strawberry/assets/86173810/d2c47ac8-d14f-430e-87c0-2daa649aae29)
it now works. i forgot to look at the date of the installers lol
ig i will use this version until there is a new release pushed onto winget.
