### ISSUE TITLE
macOS download links for 1.0.20 inaccessible

### ISSUE THREAD

**Issue by core-code** [strawberrymusicplayer/strawberry#1281]
both download links just lead to an authentication page instead of the expected binaries

<img width="383" alt="Screenshot 2023-09-27 at 11 21 17" src="https://github.com/strawberrymusicplayer/strawberry/assets/1261954/c156e35f-d609-412f-b5a3-cd24d4c77638">
<img width="512" alt="Screenshot 2023-09-27 at 11 21 57" src="https://github.com/strawberrymusicplayer/strawberry/assets/1261954/3807638e-fb70-497e-a82f-466262f78571">

**Comment by jonaski** [comment]
Access to macOS releases are currently given to sponsors only, see https://forum.strawberrymusicplayer.org/topic/1308/access-to-macos-downloads for more information.

**Comment by core-code** [comment]
thanks i'd recommend adding something like "(Sponsor Only)" to the download links to make this more obvious and not make it seem like a mistake
