### ISSUE TITLE
Wrong monitor options menu

### ISSUE THREAD

**Issue by tonyjdev** [strawberrymusicplayer/strawberry#1284]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

When I right-click on the icon (monitor 2) always shows the popup menu in the main monitor (monitor 1).
Monitor 1 is configured as the main monitor in the SO.
- Monitor 1 -> Right
- Monitor 2 -> Left

The same with the menus inside the application.

This behavior didn't occur in the previous version.

**To Reproduce**
Having the system tray icons in the secondary monitor, press right-click on the Strawberry icon. The popup menu shows in the main monitor.

**Expected behavior**
The popup menu should appear over the application menu, in the same monitor.

**Screenshots:**
![strawberry-monitors](https://github.com/strawberrymusicplayer/strawberry/assets/590183/20c05ec0-55f9-4447-9222-bba61e6ea2e2)

![Screenshot 2023-10-05 113334](https://github.com/strawberrymusicplayer/strawberry/assets/590183/ad25f2c8-a91d-4321-a78e-84aaffbc51e7)

**System Information:**
 - Operating system: Windows 11 Enterprise
 - Strawberry Version: 1.0.20

**Additional context**
---

**Comment by jonaski** [comment]
I can't reproduce this, but I only have Windows 10 to test on.
Could you do a screenshot of the Windows display settings?

**Comment by tonyjdev** [comment]
Of course.

![Screenshot 2023-10-07 172850](https://github.com/strawberrymusicplayer/strawberry/assets/590183/fe5ed6c9-d1c8-4936-adc1-2658a02af8dd)

![Screenshot 2023-10-07 172932](https://github.com/strawberrymusicplayer/strawberry/assets/590183/88eb4b94-f3ad-447f-82e9-d9bf7cf0e834)

**Comment by tonyjdev** [comment]
I downloaded [StrawberrySetup-1.0.20.44.g53e36647-msvc-x64.exe](https://builds.strawberrymusicplayer.org/windows/msvc/StrawberrySetup-1.0.20.44.g53e36647-msvc-x64.exe).
It works :)

**Comment by jonaski** [comment]
Nice, then the bug was in Qt.
