### ISSUE TITLE
Grouping by Year - Album - Artist

### ISSUE THREAD

**Issue by wennaspeedy** [strawberrymusicplayer/strawberry#1285]
Could you implement advanced grouping by Year - Album - Artist at first level?

"Year - Album" is not enought, because I don't see artist in first level.

![image](https://github.com/strawberrymusicplayer/strawberry/assets/10447994/2a199bf2-1cd0-4707-a04b-c46d094d8a86)

**Comment by jonaski** [comment]
I'm working on a rewrite of the collection, so I won't add anything new to the old, might consider better collection groupings when it's rewritten.
