### ISSUE TITLE
Option to save lyrics into tags

### ISSUE THREAD

**Issue by guidomz** [strawberrymusicplayer/strawberry#1287]
Some lyrics related options:
* "Save to tags" button in the lyrics display panel
* a setting to "Automatically save lyrics as tags if not yet there" or something
* an option to automatically save lyrics to tags when scanning audio files into library

**Comment by jonaski** [comment]
Is this something you plan to do?
We shouldn't save anything during scanning, it has to be a separate function.

**Comment by guidomz** [comment]
Sorry, I don't know coding in C. Those options are actually just suggestions for improvement, which I should have mentioned. I agree not saving during scanning.

**Comment by jonaski** [comment]
As stated in the README we can't take any requests now as I'm pretty much the only contributor, and I already have things that are still not finished after 2 years. Having issues open for suggestions/features on GitHub would potentially result in hundreds of issues, impossible to do, therefore it's strictly bugs for now. It might make sense if someone has already started to work on something, so we don't do the same things, but other than that it's pointless without more contributors.
