### ISSUE TITLE
Cant connect devices

### ISSUE THREAD

**Issue by rockrevenchy** [strawberrymusicplayer/strawberry#1288]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
In Devices > Ipod, double clicking on the ipod doesnt do anything nor does it load anything
it also wont let me send anything to my device and will just hang.

in the console it will generate these lines:
03:00:22.627 INFO  DeviceManager:597                Connecting QUrl("ipod:/media/rockrevenchy/DIEPOD PRO")
03:00:22.627 WARN  DeviceManager:649                Could not create device for "ipod:/media/rockrevenchy/DIEPOD PRO"

**To Reproduce**
Cant say if this is a specific issue to my system or not

**Screenshots:**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/28719650/02e037f8-32df-4ff7-a9b6-f9f061aa85b3)

**System Information:**
 - Operating system: 

> TuxedoOS (Ubuntu 22.04 LTS “Jammy Jellyfish”)
> KDE Plasma: 5.27.8
> KDE Frameworks: 5.110.0
> QT: 5.15.10
> Kernel: 6.2.0-10027-tuxedo (64-bit)
> Graphics Platform: X11
(Tuxedo is basically Kubuntu but with more stuff)

I've also made sure to first mount the ipod and access the folder from the OS itself
I've verified if all libraries that I know about to load a ipod were there (libgpod-common libgpod4)

the Ipod itself is a Nano Chromatic 4th gen 8GB

 - Strawberry Version: 1.0.20

**Additional context**
I can provide the entire log for starting strawberry and going to opening device then closing in a straight shot.
[Log.txt](https://github.com/strawberrymusicplayer/strawberry/files/12853900/Log.txt)

**Comment by jonaski** [comment]
This was fixed yesterday, can you try the latest from https://builds.strawberrymusicplayer.org/

**Comment by rockrevenchy** [comment]
ill give it a try now, lemme just install that stuff and ill get back to you

**Comment by rockrevenchy** [comment]
as of Version 1.0.20-39-g8ffef558
I am now capable of accessing my ipod and editing files

Thx a lot for the app and the maintenance :D
