### ISSUE TITLE
KDE Shortcut no longer works

### ISSUE THREAD

**Issue by deanrih** [strawberrymusicplayer/strawberry#1289]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I don't know since what version since I stopped listening music on my PC for quite a while (instead using my phone) due to work, but now when I tried to do it I notice that my global shortcuts no longer works, for example I use `CTRL+ALT+A` to Show/Hide the Strawberry window, and it's not showing up even though the app is opened (hidden with tray icon showing up), then I tried to open the app window manually, and try to trigger the shortcut again, which doesn't affect it and then I opened the Settings window showing the same setting as I remembered, with the shortcut still there, I **uncheck** the `Use X11 shortcuts when available` because it has warning saying `Using X11 shortcuts on KDE is not recommended...` so I disable it, but since now it doesn't work I tried to enable it and it works. The problem is it works previously with the settting disabled, and in KDE's Shortcut System Settings, there's `strawberry` section that have basically the same shortcut setting as in the strawberry app, but weirdly enough, it doesn't have an icon meaning it doesn't recognized as actual strawberry app?

Here's the screenshot:
![image](https://github.com/strawberrymusicplayer/strawberry/assets/16235605/ae76965f-f7b9-48e3-b328-511ddbf82d69)

Also when I tried to add Strawberry app shortcut manually to KDE Shortcut Settings, it only shows a fraction of shortcut options compared to previous one:
![image](https://github.com/strawberrymusicplayer/strawberry/assets/16235605/6f71a1de-fe35-4687-9b51-76a0019b7073)
At least this one is listening to the shortcut and work with the `Use X11 shortcuts when available` being disabled.

Also I tried removing the existing `strawberry` shortcut entry from the KDE Shortcut settings change some shortcut from Strawberry, enabling and disabling the `Use X11...` option hoping it will recreate the entry but it doesn't nor it fix the issue, so for now I have to enable the `Use X11...` option

**To Reproduce**
1. Open Strawberry
2. Go to Settings
3. Enable the `Use X11 shortcuts...` if it's disabled
4. Setup the shortcut
5. Disable the `Use X11 shortcuts...`
6. Try to trigger the shortcut

**Expected behavior**
The shortcut should trigger the function just like it was previously

**Screenshots:**
_Attached and provided above_

**System Information:**
 - Operating system:
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.5-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-8100 CPU @ 3.60GHz
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2
```
 - Strawberry Version: `1.0.20`
 - Installation Method: `Flatpak`

**Additional context**
_N/A_

**Comment by jonaski** [comment]
KDE Shortcuts works for me here. I'm pretty sure this is an configuration issue.

![image](https://github.com/strawberrymusicplayer/strawberry/assets/10343810/62b74171-6fd0-4bd5-b2f3-0d6b43c64270)

**Comment by jonaski** [comment]
Looks like you are missing KGlobalAccel, there should be an option for that on top:

![image](https://github.com/strawberrymusicplayer/strawberry/assets/10343810/1c1585d1-bc9c-4112-baac-e7a94189f543)

**Comment by jonaski** [comment]
On my distro (openSUSE) the package is called kglobalaccel5

**Comment by deanrih** [comment]
Unfortunately, it already installed

![image](https://github.com/strawberrymusicplayer/strawberry/assets/16235605/90281a42-6b55-4add-be23-36537996c8fc)

**Comment by deanrih** [comment]
> Unfortunately, it already installed
> 
> ![image](https://user-images.githubusercontent.com/16235605/274122093-90281a42-6b55-4add-be23-36537996c8fc.png)

I think there's something wrong with the Flatpak install, the Manjaro repository one seems fine and can detect the KGlobalAccel

**Comment by jonaski** [comment]
I suggest you open a new issue here: https://github.com/flathub/org.strawberrymusicplayer.strawberry/issues

**Comment by deanrih** [comment]
> I suggest you open a new issue here: https://github.com/flathub/org.strawberrymusicplayer.strawberry/issues

Will do
