### ISSUE TITLE
Strawberry can't play MPC files 

### ISSUE THREAD

**Issue by samodadela** [strawberrymusicplayer/strawberry#1291]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
MPC files won't play in strawberry, but can be played using `gst-launch-1.0`.
When a file is played in strawberry, the following is logged:
```
19:48:28.764 ERROR GstEngine:945                    Unknown mimetype "audio/x-raw"
19:48:28.764 ERROR GstEngine:957                    Unknown filetype "Raw 32-bit floating-point audio"
```

The file plays OK, with the following command line:
```
gst-launch-1.0 filesrc location="file.mpc" ! decodebin ! audioconvert ! alsasink
```
File prints:
```
file file.mpc
Musepack audio (MP+), SV 7.0, profile 'Unstable/Experimental', Alpha 1.15
```

**To Reproduce**
Try playing a MPC file in strawberry, Version 1.0.20.

**Expected behavior**
Play the MPC file

**Screenshots:**

**System Information:**
 - Operating system:
```
Linux c 6.4.16-5-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Sep 28 10:59:52 UTC 2023 x86_64 GNU/Linux
```
 - Strawberry Version: 1.0.20

**Additional context**
taglib: extra/taglib 1.13.1-1
tried also clementine: mpc plays fine

**Comment by jonaski** [comment]
It's a gstreamer bug, `gst-launch-1.0 playbin3 uri=file://` doesn't work...

**Comment by jonaski** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3033

**Comment by samodadela** [comment]
Thanks.

Is there a workaround while upstream is being fixed?

Is it possible to switch to some other back end? I noticed there is an option to choose a different back end, but only GStreamer is listed.

It's a bit inconvenient since when it tried to play a MPC it hangs there indefinitely.

**Comment by jonaski** [comment]
As a workaround you can remove the file `libgstmusepack.so`, on my system it's `/usr/lib64/gstreamer-1.0/libgstmusepack.so`, which makes it fall back to using libav for decoding instead (make sure you got the gstreamer libav package installed).
