### ISSUE TITLE
Album Cover cannot be set

### ISSUE THREAD

**Issue by evertvorster** [strawberrymusicplayer/strawberry#1293]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Unable to change the Cover image for a song. 

**To Reproduce**
1. Notice that the wrong album art has been set for a song on the playlist. 
2. On Context menu, right-click and select "Un-set Cover Art"
3. Select Search for album cover
4. Select the correct cover
5. Hit "OK"

**Expected behavior**
The new cover to be downloaded and embedded in the song

**Screenshots:**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/12045269/e1b5378f-b658-4830-9dda-b8fe50a840c5)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.20-1

**Additional context**
System Info:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.7-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: PD5x_7xSNC_SND_SNE
System Version: Not Applicable
```

**Comment by jonaski** [comment]
I can't reproduce this, what settings are set in the Covers options in the settings?

**Comment by evertvorster** [comment]
Playing with this a little more... 

If you "Delete Cover" in the context menu, you are then able to load another graphic for the Album Cover. I would have thought that just loading a new graphic would replace the old graphic. 

All graphics are embedded in the .mp3 files. 

When "Unset Cover" in the context menu of the context, it's not easy to set Cover art again, unless you go into "Edit track information" as described above.

**Comment by jonaski** [comment]
It sounds as the problem might have been that you had a different album cover associated with the songs that was either in the album directory, or in the album cache directory and it was picked before the new embedded cover you set.
