### ISSUE TITLE
always display playlist tabs - star button invisible, Playlists feature obscured

### ISSUE THREAD

**Issue by kolAflash** [strawberrymusicplayer/strawberry#1295]
When there's only one playlist loaded, no tabs are being displayed. So the favourite playlist star button isn't visible.

This makes the whole "Playlists" feature in the left sidebar very hard to understand. I spend 60 minutes wondering how this feature works out, creating "New folder"s in the "Playlists" area and trying other stuff. I tried to store the current playlist, so I didn't think of clicking _Playlist (menu) -> New playlist_ which finally made the playlists tabs show up.

&nbsp;

**To Reproduce**
Close all playlists tabs until there's just the current playlist being displayed. Then try to find a way to star a playlist.

**Expected behavior**
Either playlist tabs should always display, even when there's only one playlist. Or introduce an alternative way to star a playlist.

**Screenshots:**
<details>
<summary>screenshot</summary>

![grafik](https://github.com/strawberrymusicplayer/strawberry/assets/3355089/defb4d6f-90d3-4f69-ab6d-6d585ddf32c4)
</details>

**System Information:**
 - Debian-12 GNU/Linux
 - Strawberry Version: tested 1.0.14-1 by Debian-12 and 1.0.20 (compiled from sources)

&nbsp;

&nbsp;

**Additional context**

&nbsp;

Related:
- #574 _Star icon is not vertically centered in the tab_
- #782 _The favorite playlists feature no longer works._
- #1178 _Some custom icons not working_

&nbsp;

Side note:
Empty folders in the Playlists area just vanish when restarting Strawberry. Is this intended!?  
Back then in [Amarok](https://en.wikipedia.org/wiki/Amarok_(software)#Forks_and_variations)-1.4.10 empty Playlists folders did not vanish on program restart.  
https://cdimage.debian.org/mirror/cdimage/archive/5.0.10-live/amd64/iso-cd/debian-live-5010-amd64-kde-desktop.iso  
KDE Menu -> Utilities -> Konsole: `sudo apt-get update; sudo apt-get install amarok`  
_(apt-get should load from `archive.debian.org`)_

**Comment by jonaski** [comment]
I understand the inconvenience, but most who use the favorite playlist functionality tend to open more than one playlist, and for users who just use one playlist, the tabs are not needed.

**Comment by kolAflash** [comment]
@jonaski  
Sure so many users have multiple tabs opened?

It was really, really intuitive to find the star.
Consider you search for the star but you haven't even realized, that multiple tabs can be opened (exactly what happened to me).

What about introducing another way to star a playlist?
Maybe adding the star beside the icons `New playlist`, `Load playlist`, ... above the current playlist.
