### ISSUE TITLE
MP2 album not added to collection

### ISSUE THREAD

**Issue by Yodo13** [strawberrymusicplayer/strawberry#1296]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
An album consisting of MP2 audio files that are tagged appropriately is stored in a valid path, yet it does not appear in the Collection as selected on the left panel. According to VLC, the codec in question is "MPEG Audio layer 1/2 (mpga)". According to Audacious, it is "MPEG-1 layer 2", which may be the same.

**To Reproduce**
As described above.

**Expected behavior**
The album appears in the Collection and all songs play normally with their tags displayed correctly in the playlist.

**Screenshots:**
Probably not necessary.

**System Information:**
 - Operating system: Linux Mint 21.2
 - Strawberry Version: 1.0.20 (deb install)

**Additional context**
Dragging one of the MP2 files in the Strawberry playlist will show the song with title equal to the file name and all other entries (artist, album, ...) blank. Playing this file will result in all entries being filled with the correct information as tagged. The song then plays fine. After playing ends, the title in the playlist switches back to the file name with all other entries again blank. Possibly, Strawberry does not see tags like album and artist and therefore cannot add the album to the Collection. These files play normally in Audacious and info is shown correctly, as tagged, so the problem seems to be restricted to Strawberry.

**Comment by jonaski** [comment]
I can't reproduce. It works here, although MP2 is identified by Strawberry as MP3.
Check what version of TagLib you have, you need 1.12 or higher.
I know some older Ubuntu LTS releases still uses TagLib 1.11.1 (even though all newer relases are binary compatible), that's a 7 year old release which should not be used because it has critical bugs.

**Comment by Yodo13** [comment]
Yes, I believe that you correctly identified the problem. Many thanks for the advice!
