### ISSUE TITLE
Compilation error - `KDSingleApplication::Option` has not been declared

### ISSUE THREAD

**Issue by cmorgenstern** [strawberrymusicplayer/strawberry#1300]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Unable to compile and build from the latest commit when using system `kdsingleapplication-1.0.0`:
```
[100%] Building CXX object src/CMakeFiles/strawberry.dir/main.cpp.o
/build/strawberry-git/src/strawberry/src/main.cpp: In function ‘int main(int, char**)’:
/build/strawberry-git/src/strawberry/src/main.cpp:160:94: error: ‘KDSingleApplication::Option’ has not been declared
  160 |     KDSingleApplication single_app(QCoreApplication::applicationName(), KDSingleApplication::Option::IncludeUsernameInSocketName);
      |                                                                                              ^~~~~~
/build/strawberry-git/src/strawberry/src/main.cpp:201:92: error: ‘KDSingleApplication::Option’ has not been declared
  201 |   KDSingleApplication single_app(QCoreApplication::applicationName(), KDSingleApplication::Option::IncludeUsernameInSocketName);
      |                                                                                            ^~~~~~
make[2]: *** [src/CMakeFiles/strawberry.dir/build.make:76: src/CMakeFiles/strawberry.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:229: src/CMakeFiles/strawberry.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**To Reproduce**
Clean chroot compile with the following cmake build settings:
```
-DBUILD_WITH_QT6:BOOL='ON' \
-DCMAKE_BUILD_TYPE:STRING='None' \
-DCMAKE_INSTALL_PREFIX:PATH='/usr' \
-DENABLE_LIBGPOD:BOOL='OFF' \
-DENABLE_MOODBAR:BOOL='OFF' \
-DENABLE_QOBUZ:BOOL='OFF' \
-DENABLE_SUBSONIC:BOOL='OFF' \
-DENABLE_TIDAL:BOOL='OFF' \
-DENABLE_TRANSLATIONS:BOOL='OFF' \
-DENABLE_VLC:BOOL='OFF' \
-Wno-dev
```

**Expected behavior**
Strawberry compiles successfully.

**System Information:**
 - Operating system: Arch Linux 6.5.8-arch1-1 x86_64
 - Strawberry Version: [HEAD](https://github.com/strawberrymusicplayer/strawberry/commit/eec5b448b6e78ae4877626d5e1e2b654fa61968b) of master

**Comment by jonaski** [comment]
Try [5f02072](https://github.com/strawberrymusicplayer/strawberry/commit/5f02072bf396b4a5d27dd4d39e458d4209b9f20c)

**Comment by cmorgenstern** [comment]
Confirmed fixed, cheers.
