### ISSUE TITLE
Tidal Official API Client ID not working

### ISSUE THREAD

**Issue by Relms12345** [strawberrymusicplayer/strawberry#1301]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I am trying to log into Tidal with a client ID i got from the new developer dashboard. It does not work

**To Reproduce**
Steps to reproduce the behavior.
Go to https://developer.tidal.com/dashboard/
Login and create a new app
get client id and put into strawberry
tidal browser login does not work

**Expected behavior**
Able to log into Tidal 

**Screenshots:**

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: latest git revision

**Additional context**

**Comment by jonaski** [comment]
Strawberry does not use that API (https://openapi.tidal.com), it uses the closed API (https://api.tidalhifi.com/v1).
The open API is not compatible with the closed API and does not allow streaming only retrieving metadata, as is also explained on https://developer.tidal.com/apiref:

_The Catalogue API provides a set of endpoints for accessing the TIDAL metadata catalogue: albums, artists, tracks, videos, and search capabilities._
