### ISSUE TITLE
kdsingleapplication cmake error

### ISSUE THREAD

**Issue by dtl131** [strawberrymusicplayer/strawberry#1303]
**Describe the bug**

```
  CMake Warning at CMakeLists.txt:308 (find_package):
  By not providing "FindKDSingleApplication-qt6.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "KDSingleApplication-qt6", but CMake did not find one.
......
CMake Error at 3rdparty/kdsingleapplication/CMakeLists.txt:5 (add_library):
  No SOURCES given to target: kdsingleapplication
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

[strawbcmakelog.txt](https://github.com/strawberrymusicplayer/strawberry/files/13193615/strawbcmakelog.txt)

**To Reproduce**
git clone a fresh copy of strawberry code. Run cmake as per instructions.

**Expected behavior**
cmake runs correctly

- Operating system: Debian sid/unstable x86-64, updated as of time of report
- Strawberry Version: git master, updated as of time of report. Last commit: 5f02072bf396b4a5d27dd4d39e458d4209b9f20c

**Additional context**
The release tarball of 1.0.21 builds/works correctly for me.

**Comment by jonaski** [comment]
You need to clone the repository with submodules:
`git clone --recursive git@github.com:strawberrymusicplayer/strawberry.git`
After already cloned:
`git submodule update --init --recursive`

**Comment by dtl131** [comment]
Not working for me (I know, I'm probably using git incorrectly):
```
$ git submodule update --init --recursive
Submodule '3rdparty/kdsingleapplication/KDSingleApplication' (git@github.com:KDAB/KDSingleApplication.git) registered for path '3rdparty/kdsingleapplication/KDSingleApplication'
Cloning into '/home/denial/Downloads/strawberry/3rdparty/kdsingleapplication/KDSingleApplication'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I really wish there was just a -DENABLE-KDSINGLEAPPLICATION option to turn it off

**Comment by jonaski** [comment]
That looks like you are missing SSH keys, totally unrelated to the original issue. Try http instead:
`git clone --recursive https://github.com/strawberrymusicplayer/strawberry.git`

**Comment by dtl131** [comment]
Same issue with https. I tried recursive clone of another gh repo that I know has submodules (mozilla-vpn-client) and that worked okay.
*Shrug*
I'm giving up on this since strawberry 1.0.21 is working for me.

Thank you for your time and help.

**Comment by dtl131** [comment]
jonas, you were on the correct track.

https://github.com/strawberrymusicplayer/strawberry/blob/654a94fe3de4f3768794a70db52943a6a9b90550/.gitmodules#L3

I changed ^that line to:
`url = https://github.com/KDAB/KDSingleApplication.git`

Then, I ran the `git submodule update --init --recursive` command. All is well now.

**Comment by jonaski** [comment]
Ah, of course, thanks. I've changed the submodule the https 5d77eb1
