### ISSUE TITLE
Music playback frequently cuts out intermittently.

### ISSUE THREAD

**Issue by Tiara-11** [strawberrymusicplayer/strawberry#1304]
- [√ ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.

**Describe the bug**
When playing music using strawberry musicplayer, intermittent music interruptions often occur when running other programs, switching windows, or running the screen saver.
In the past, when using Winamp, the problem was solved by setting the cache, so even if the disk cache usage was set to a large amount, the status did not change.

So, I installed and used AIMP, which I had used in the past, and observed that such a phenomenon occurs extremely rarely.

I happened to learn about strawberry musicplayer while using Linux and liked it, so I tried to use it on Windows, but I ran into this problem.

Anyway, thank you for creating strawberrymusicplayer, a great music playback program, and I hope it develops further and makes you happy.
thank you

**System Information:**
 - Operating system : Windows 11 Home
 - Strawberry Version : 1.0.20
 - System :  Asus Zenbook Pro 16X OLED UX7602ZM-ME004W (i9-12900H RTX3060 32GB 1TB 16" 4K OLED
![스크린샷 2023-10-29 140920](https://github.com/strawberrymusicplayer/strawberry/assets/53861295/df6f0fff-50a2-4f02-8a4a-4b9bed185573)

**Comment by jonaski** [comment]
The album cover pixmap cache has nothing to do with playback buffering.
What you need to change is the Buffer settings under Backend settings.
Try increasing the buffer duration to 8000 ms.

I've done a lot of testing under stress on Windows 10, and I could only reproduce choppy audio under really high CPU load, although I am aware that some other players handle this better, but I've found no easy way to improve it.

**Comment by Tiara-11** [comment]
Thank you for your reply~
Even if I set it up as you described, the disconnection still occurs.

**Comment by jonaski** [comment]
Can you try one of the installers listed on https://github.com/strawberrymusicplayer/strawberry/actions/runs/6880692159 under artifacts and see if it resolved it.

**Comment by jonaski** [comment]
Closing this because of lack of feedback.
