### ISSUE TITLE
Winget upgrade uninstalls without installing new version

### ISSUE THREAD

**Issue by NotaInutilis** [strawberrymusicplayer/strawberry#1305]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Using Winget to update Strawberry to its latest version, the installer unistalls the installed version of Strawberry but does not install the latest version afterwards. It seems like both the uninstaller and the installer are launched at the same time, creating a conflict.

**To Reproduce**
From a previous version, update Strawberry via Winget.

**Expected behavior**
The installer should complete the upgrade process instead of stopping after the uninstallation of the previous version and the installation of the next.

**Screenshots:**
![Capture d'écran 2023-11-01 172707](https://github.com/strawberrymusicplayer/strawberry/assets/9675966/56b33170-d7c8-48ff-8424-0d6a80a64ed8)

![Capture d'écran 2023-11-01 172840](https://github.com/strawberrymusicplayer/strawberry/assets/9675966/52cd5b68-e2f8-44a8-ae0e-cc61f33146f8)

**System Information:**
 - Operating system: W11 22
 - Strawberry Version: 1.0.20 to 1.0.21

**Additional context**
n/a

**Comment by jonaski** [comment]
We have nothing to do with the winget package, I suggest to seek support directly from winget: https://github.com/microsoft/winget-pkgs/issues
The only official way of installing Strawberry is directly with the installer available on or website and Github page.
