### ISSUE TITLE
Actual release artifact for ubuntu 23.04 installs version 0.14

### ISSUE THREAD

**Issue by ReIaxo** [strawberrymusicplayer/strawberry#1312]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When I try to install a new version from Website or GitHub Releases for ubuntu-lunar 23.04, I end up with version 0.14 of Strawberry. Tested Artifacts from version 0.20 and 0.21

**To Reproduce**
Install with deb package.

**Expected behavior**
Installing the right version.

**Screenshots:**

**System Information:**
 - Operating system: Ubuntu 23.04
 - Strawberry Version: See above

**Additional context**

**Comment by jonaski** [comment]
There are no strawberry release with either of these versions 0.14, 0.20 or 0.21.
What's the URL for the file you installed? Where do you see version 0.14 after you installed the package?

**Comment by jonaski** [comment]
https://files.strawberrymusicplayer.org/strawberry_1.0.21-lunar_amd64.deb is the latest release listed on the website, it's identical to the one on GitHub.
I don't see any issues.

**Comment by ReIaxo** [comment]
Sorry again for messing up versions. Seems like i overlooked the leading "1". I mean 1.0.14, 1.0.20 and 1.0.21.

I see the version in Help -> About Strawberry. 

I used the URLs from GitHub releases. For example: https://github.com/strawberrymusicplayer/strawberry/releases/download/1.0.21/strawberry_1.0.21-lunar_amd64.deb
And from the Website: https://files.strawberrymusicplayer.org/strawberry_1.0.21-lunar_amd64.deb

Meanwhile I updated to 1.0.21 with apt, which works fine. I also updated to Ubuntu 23.10 today. I can check the installation again tomorrow.

Do you have a Ubuntu machine to test the installation? Maybe my system is messed up?

**Comment by jonaski** [comment]
I didn't have Ubuntu, but I installed Ubuntu 23.04 (Lunar) just to test your claim.
The version shown on the command line is the exact same as the one in About.
1.0.14 is the latest available in the Ubuntu repository, so it seems more likely you installed the repository package and not the package we distribute on the website and GitHub.

**Comment by ReIaxo** [comment]
Ah okay, makes sense.

I use to double click the .deb file which opens into "Ubuntu Software". Then i click install. I thought it will install the double clicked file.
