### ISSUE TITLE
sometimes crashes when opening a connected device

### ISSUE THREAD

**Issue by u6aab** [strawberrymusicplayer/strawberry#1313]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
when I plug a device into my laptop and try to open it with strawberry, it crashes

**To Reproduce**
- plug device into laptop
- open strawberry
- navigate to devices
- double click on the plugged in device
- double click again after its been mounted
- click "ok" on popup asking to scan for the first time
- crash

**Expected behavior**
the device should be opened

**Screenshots:**

**System Information:**
 - Operating system: Fedora 38 kde
 - Strawberry Version: 1.0.21

**Additional context**
using a sansa clip+ running rockbox with a 128gb microsd card formatted in fat32. i have the output from launching strawberry in the terminal:

`
[user@fedora Music]$ strawberry
18:32:51.459 WARN  unknown                          This plugin supports grabbing the mouse only for popup windows 
18:32:52.146 WARN  unknown                          This plugin supports grabbing the mouse only for popup windows 
/usr/include/c++/13/bits/shared_ptr_base.h:1349: std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::element_type& std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::operator*() const [with _Tp = ConnectedDevice; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic; bool <anonymous> = false; bool <anonymous> = false; element_type = ConnectedDevice]: Assertion '_M_get() != nullptr' failed.
Aborted (core dumped)
`

**Comment by u6aab** [comment]
update: I tried opening it again with strawberry and it worked, then crashed while i was trying to transfer songs to it and now it works when transferring songs. unfortunately I just opened it from the launcher this time so i dont have the console output

**Comment by jonaski** [comment]
I can't reproduce this, what libstdc++ (gcc) version?
Do: `ldd strawberry | grep libstdc++`
then `rpm -qf` on the returned lib, ie.: `rpm -qf /usr/lib64/libstdc++.so.6`.

**Comment by maxyvisser** [comment]
I'm experiencing the exact same issue as originally described: when I try to open my ipod with strawberry, it crashes with the same error.
```
/usr/include/c++/13.2.1/bits/shared_ptr_base.h:1349: std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::element_type& std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::operator*() const [with _Tp = ConnectedDevice; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic; bool <anonymous> = false; bool <anonymous> = false; element_type = ConnectedDevice]: Assertion '_M_get() != nullptr' failed.
```
Some additional info:
OS: Arch Linux
Strawberry version: 1.0.22-2 (the current package from the `extra` repository)
Device: iPod 5th gen

```
$ ldd /usr/bin/strawberry | grep libstdc++
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fc539a00000)
```

```
$ sudo pacman -Qo /usr/lib/libstdc++.so.6
/usr/lib/libstdc++.so.6 is owned by gcc-libs 13.2.1-3
```

Here is the complete output I get when running strawberry (I think most of it is useless, but I might be wrong):
[strawberry.log](https://github.com/strawberrymusicplayer/strawberry/files/13865817/strawberry.log)

Is this enough information to reopen this issue? I'll gladly provide more if necessary.

**Comment by daigennki** [comment]
Same issue here with Strawberry 1.0.22-2 on Arch Linux, except with a new USB flash drive instead of an iPod.
```
/usr/include/c++/13.2.1/bits/shared_ptr_base.h:1349: std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::element_type& std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::operator*() const [with _Tp = ConnectedDevice; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic; bool <anonymous> = false; bool <anonymous> = false; element_type = ConnectedDevice]: Assertion '_M_get() != nullptr' failed.
```

Some info about libstdc++ on my system:
```
$ ldd /usr/bin/strawberry | grep libstdc++
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f43a9200000)
```
```
$ sudo pacman -Qo /usr/lib/libstdc++.so.6
/usr/lib/libstdc++.so.6 is owned by gcc-libs 13.2.1-3
```

**Comment by jonaski** [comment]
When does it crash? Can someone do a full backtrack?

**Comment by jonaski** [comment]
Try with a4b7766

**Comment by daigennki** [comment]
If it helps at all, this stack trace got printed to journalctl: https://gist.github.com/daigennki/e92c6925b63c2aa05c9b80201715ced8

**Comment by jonaski** [comment]
@daigennki It's missing debug symbols.

**Comment by jonaski** [comment]
Thanks, I assume that fixed it then, if someone still experience the crash please report back and I'll reopen the issue.
