### ISSUE TITLE
Super slow filtering

### ISSUE THREAD

**Issue by jeanrajotte** [strawberrymusicplayer/strawberry#1319]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
On Windows 10, very often, but not always, typing in the filter jams the app for minutes (not responding). I have mentioned this before and was told I'm not sure what anymore.... 

**To Reproduce**
:)))

Have a (31,332 Files, 5,809 Folders) collection (211 GB) and type "b" for "blues" and watch keyboard stop and hourglass mouse icon appear and remain for minutes, nothing else working

**Expected behavior**
Finish typing and watch filter work.  IMO, the JIT filtering is malarkey. Type the whole word(s) and press Enter to fire the filter would be safer!

**Screenshots:**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/312996/ae48e56f-cc27-4245-a662-d2fdb25e3f05)

"T" for "tango" - jammed!

**System Information:**
Windows 10
Strawberry 1.0.21

**Additional context**

**Comment by jonaski** [comment]
I already answered this in #1162. Fixing this require a complete rewrite of the search, it will be fixed in time, but until it's done either don't use album grouping, or don't use the search.
