### ISSUE TITLE
Feature request: Dynamic Playlists

### ISSUE THREAD

**Issue by desputinski** [strawberrymusicplayer/strawberry#132]
Hi,
I read that strawberry doesn't have dynamic playlists yet. I think this is one of the key features an advanced Music Player should have. I know that Strawberry is a rather new project and that ressources are limited... But anyway would like to add this feature request...
best regards
desputinski

**Comment by jonaski** [comment]
Already asked: https://github.com/jonaski/strawberry/issues/85

**Comment by desputinski** [comment]
I'm not sure if this is a duplicate. I mean by playlist for example:
-50 Songs AND
-Genre contains "pop" AND
-Rating higher than 4 AND

**Comment by desputinski** [comment]
PS:
In Amarok 1.4 it was possible to even combine AND- and OR-querys in Dynamic Plalists. So for example:
These three aspects:
-Genre contains "pop" AND
-Rating higher than 4 AND
-Year is before 1979

combined with OR
-Comment contains "Party"

**Comment by jonaski** [comment]
This will be added as part of #264

**Comment by desputinski** [comment]
Hi, this is working now, right? Because when I create a dynamic playlist there is no icon or Header that tells me witch off the combined searches are AND and which are OR related to each other....
