### ISSUE TITLE
Scrobbling issues

### ISSUE THREAD

**Issue by kirk781** [strawberrymusicplayer/strawberry#1324]
Whenver I play music offline or the internet connectivity is very weak, Strawberry pops up with "Can't scrobble to Last.fm". I have scrobbling turned on but it plays havoc when playing music offline with the music player throwing the pop up every other song. Shouldn't it just cache scrobbles and submit later or just do nothing without any user interaction in case no network connection is found?

**System Information:**
 - Operating system: Void Linux
 - Strawberry Version: 1.0.17

**Comment by jonaski** [comment]
There is an option for working offline mode in the scrobbler settings, you can turn that on whenever you want to scrobble without or an unstable internet connection. We really need to show errors, otherwise it's impossible to diagnose the problem whenever an issue is reported.
