### ISSUE TITLE
Gui problem when selecting the next music

### ISSUE THREAD

**Issue by SzImre90** [strawberrymusicplayer/strawberry#1330]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When you select the next music, you can see that page also has the program come out outside the selection.

**To Reproduce**
Click on a next random music and you can see it side by side with the program outside the preview.

**Expected behavior**
Confusing factor

**Screenshots:**

[strawberry gui bug](https://github.com/strawberrymusicplayer/strawberry/assets/151575617/c1941684-b17d-4243-98f0-d271e3810cbe)

**System Information:**
 - Operating system: Windows 10 Home x64 22H2 19045.3693
 - Strawberry Version: 1.0.21

**Additional context**
Please use paint, because there you can see the error.

**Comment by jonaski** [comment]
I don't see anything wrong here. What preview are you talking about?

**Comment by SzImre90** [comment]
Please download screenshots, and view it with Windows paint app. Because otherwise you can't see the problem, because for some reason it makes that part disappear. I took a picture with my phone to see what it was about. Long jagged line.
"_What preview are you talking about?_" opps wrong translate, sorry. 
Click on a next random piece of music and you can see the selected part outside together with the programme.
![IMG_20231202_184424](https://github.com/strawberrymusicplayer/strawberry/assets/151575617/44603d9b-2624-400e-b6cb-670890ff0554)

**Comment by jonaski** [comment]
It might be a driver bug then, try updating to the latest graphics drivers.
I only have one Windows 10 PC and there I didn't see the issue, but I will do another check.

**Comment by jonaski** [comment]
I think this is most likely some sort of Windows or driver bug.
