### ISSUE TITLE
Artists are repeated if there's no capitalization.

### ISSUE THREAD

**Issue by TheArgentinian** [strawberrymusicplayer/strawberry#1331]
**Describe the bug**
Artists get listed multiple times if there's a difference in capitalization

**To Reproduce**
Edit an artist tag for a song and remove the capitalization. For example: Rage Against The Machine > rage against the machine

**Expected behavior**
Same artists get combined.

**System Information:**
 - Operating system: Ubuntu 22.04 LTS
 - Strawberry Version: 1.0.21

**Comment by jonaski** [comment]
This is intended behavior.

**Comment by TheArgentinian** [comment]
> This is intended behavior.

Shitty behavior that I haven't seen in other players. You gonna make people change a couple of letters in their music collection?
