### ISSUE TITLE
Strawberry not shows metadata of song after connecting disconnected disk with songs

### ISSUE THREAD

**Issue by qarmin** [strawberrymusicplayer/strawberry#1338]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Some time ago I added a lot of songs to playlist from one disk.
Yesterday system not mounted disk and I run strawberry
All results instantly become not available, because path to them not existed(expected behavior)
But when I properly mounted disk with this music, after restarting OS, I still not see metadata of song.
Only selected song is properly recognized, but after changing to different song, old song will prune its metadata from gui

**Screenshots:**

https://github.com/strawberrymusicplayer/strawberry/assets/41945903/f814e565-8024-40e6-a9e6-ea654cc8b82c

**System Information:**
 - Operating system: Ubuntu 23.10
 - Strawberry Version: 1.0.22

**Comment by jonaski** [comment]
Right click on the tracks and select "Rescan songs". For more reliable usage use the collection to add music.
