### ISSUE TITLE
Scrollwheel not working in Strawberry

### ISSUE THREAD

**Issue by pcppcp** [strawberrymusicplayer/strawberry#1339]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I can not use scrollwheel anywhere in the whole app! Other apps (browser...) do process scroll events properly.

**To Reproduce**
1) Open the app
2) create a long playlist
3) use scroll wheel with a cursor on the playlist frame
4) The playlist does not scroll!

This applies also for the file browser or collection lists

**Expected behavior**
Strawberry registers scrollwheel events and updates the GUI accordingly

**Screenshots:**
N/A

**System Information:**
 - Operating system: SuSE Leap 15.4
 - Strawberry Version: 1.0.17
 - DE: XFCE/Xorg

** Additional context **
[this thread](https://forum.strawberrymusicplayer.org/topic/1154/strawberry-stops-scrolling?lang=en-US) on the strawberry forums

**Comment by jonaski** [comment]
Works here on openSUSE 15.5 with XFCE. I suggest that you update your system, 15.4 is end of life in a few days anyway. In any case the bug isn't in strawberry as it does not handle scroll events directly.

**Comment by pcppcp** [comment]
Just in case anyone encounters this problem and googles for a update: There is [a bug](https://bugreports.qt.io/browse/QTBUG-56214) in some QT versions that prevents scrollwheel events from being registered by the app. This was fixed in QT 6.5 (I'm currently on Leap 15.5 which uses QT 6.2.2).
