### ISSUE TITLE
thanks but: debian 12, add-apt-repository ppa:jonaski/strawberry fails

### ISSUE THREAD

**Issue by UltimateSolar** [strawberrymusicplayer/strawberry#1342]
Hello,

thanks for the update of clementine (can not play aac?)

tried to install under debian 12 like this

`su - root
apt update
apt install software-properties-common
add-apt-repository ppa:jonaski/strawberry
apt install strawberry`

the result was:

`Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
`

**Comment by jonaski** [comment]
The PPA is for Ubuntu not Debian.

**Comment by UltimateSolar** [comment]
yes that is correct. thought ubuntu and debian SHOULD stay compatible :( !!!

(if not it's ubuntu's fault X-D)

so here is the debian 12 install howto:
```

su - root
apt update
apt install qt6-base-dev strawberry
# manual install
mkdir -p /home/user/software
cd /home/user/software
# Let's Encrypt cert has expired
wget --no-check-certificate https://builds.strawberrymusicplayer.org/debian/bookworm/strawberry_1.0.22-bookworm_amd64.deb
dpkg -i [strawberry_1.0.22-bookworm_amd64.deb](https://builds.strawberrymusicplayer.org/debian/bookworm/strawberry_1.0.22-bookworm_amd64.deb)
# if there are problems, ask apt to help fix dependency problems
apt -f install
```
