### ISSUE TITLE
Language changed on its own, from en to cz_CN 

### ISSUE THREAD

**Issue by jeanrajotte** [strawberrymusicplayer/strawberry#1343]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Out of the blue, after 3 weeks of stable use, the UI's language had changed from (en) to (cz_CN) - t'was fun changing it back haha!

**To Reproduce**
Dunno. I haven't gone anywhere near cz_CN in any app.

**Expected behavior**
The language that's set sticks unless it's changed in the Preferences' UI.

**Screenshots:**

**System Information:**
 - Operating system: pop!_os w/ KDE
 - Strawberry Version: Version 1.0.22

**Additional context**

**Comment by jonaski** [comment]
Please provide steps to reproduce this consistently, if it's a one-time occurrence which can't be reproduced then there is not much chance this can be fixed.

**Comment by jeanrajotte** [comment]
I know.  Too bad. Let this just be a report. If it happens again, ever, I'll revisit... Thanks.
