### ISSUE TITLE
[gnome] notification controlls don't show album art

### ISSUE THREAD

**Issue by andreyorst** [strawberrymusicplayer/strawberry#1348]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 
  (BTW, the forum forbids searching for unregistered users. Why?)

**Describe the bug**

When I play the music under the GNOME 45.2, the controls are shown in the notification area, however, the album art is not displayed there.
If I enable notifications, the notification itself contains the album art.
Sometimes, the control notification shows the artwork, but it doesn't change with the track, so it can show artwork from a different album.

**To Reproduce**

1. Launch Strawberry under the GNOME Shell
2. Hit play on any track with an album art
3. Open the notification area

**Expected behavior**

Correct album art is shown in the control notification.

No album art:

**Screenshots:**

![image](https://github.com/strawberrymusicplayer/strawberry/assets/19470159/8cdc186f-e590-4b13-82cb-03654da590cb)

Wrong album art is sometimes displayed (the correct one is in the notification):

![image](https://github.com/strawberrymusicplayer/strawberry/assets/19470159/1690c15c-ae79-425d-9ef5-0e1efb234e77)

**System Information:**
 - Operating system: Fedora Silverblue
 - Strawberry Version: 1.0.22

**Additional context**

Clementine 1.4.0rc1-901-g7b678f26e doesn't seem to have this problem

**Comment by jonaski** [comment]
I don't use Gnome, but it works fine on both KDE and XFCE, I haven't touched the OSD stuff in Strawberry in like 4 years or so, and no-one else has reported an issue in that time, so it makes me think it's more likely that the bug is in a newer version of Gnome.
Strawberry is using the new "image-data" property while Clementine is using the old deprecated "image_data" property (https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html), maybe that's why it works.
But I can test Fedora Silverblue in a VM and see if that's the case.

**Comment by jonaski** [comment]
I can't reproduce any issues on Fedora SIlverblue with Gnome either, covers appear in the notification each time.
Are you using embedded cover art or from files? What file format? JPEG or something else?

**Comment by andreyorst** [comment]
> I don't use Gnome, but it works fine on both KDE and XFCE, I haven't 
> touched the OSD stuff in Strawberry in like 4 years or so, and no-one 
> else has reported an issue in that time, so it makes me think it's more 
> likely that the bug is in a newer version of Gnome.

I tried some old music players, and some new ones, and none of them that 
have support for OSD stuff have this issue on this version of Gnome, so I 
don't know about that.

> Strawberry is using the new "image-data" property while Clementine is 
> using the old deprecated "image_data" property 
> (https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html), 
> maybe that's why it works.

Thanks, I just tried Clementine and it has the same behavior. Maybe 
that's because I'm running it from the fedora-toolbox container, as a 
main way to run user-installed software .suggested by the distrbution. I 
will try to run these as flatpaks as well for completeness. (I know 
flatpak isn't an offisial package)

> I can't reproduce any issues on Fedora SIlverblue with Gnome either, 
> covers appear in the notification each time.
> Are you using embedded cover art or from files? What file format? JPEG 
> or something else?

Interesting, thanks! can you tell me how did you install Strawberry? E.g. 
via rpm-ostree on the host, via dnf inside a toolbox, or as a flatpak?

I will try different cover formats and different embedding strategies, 
and return back to you. Thanks!

**Comment by andreyorst** [comment]
Huh, it appears, I somehow had a flatpak version, alongside with the toolbox version, and the .desktop for toolbox version was replaced with .desktop file of the flatpak. Running from toolbox manually the problem is gone. Only the flatpak version has this issue, and that's why clementine also had this this time around.

Sorry for the noise, seems like a flatpak problem. Closing.
