### ISSUE TITLE
Impossible to sort music by Original Year

### ISSUE THREAD

**Issue by LinuxBoy-96** [strawberrymusicplayer/strawberry#1349]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Bug Description**
Impossible to sort by Original Year (Year works fine however)

**To Reproduce**
1. Create any list of music.
2. Enable Original Year as a tag.
3. Try to sort them by Original Year.

**Expected behavior**
Would expect to see them get sorted from oldestt to newest or from the newest to oldest.
however they remain completely mixed, nothing move.

**System Information:**
 - Operating system: Win 11
 - Strawberry Version: 1.0.22

**Comment by LinuxBoy-96** [comment]
> Are you talking about the playlist? In that case it works fine for me.

Not for me... See below

https://github.com/strawberrymusicplayer/strawberry/assets/128245725/fdaf56f8-c5b8-4cd6-ab12-e2d40fcc4c81

**Comment by LinuxBoy-96** [comment]
> Are you talking about the playlist? In that case it works fine for me.


https://github.com/strawberrymusicplayer/strawberry/assets/128245725/f3440bc6-caee-451d-8fae-31cc3a420bbb

**Comment by LinuxBoy-96** [comment]
> Are you talking about the playlist? In that case it works fine for me.


https://github.com/strawberrymusicplayer/strawberry/assets/128245725/e260dab0-e808-484d-8dcb-1a4a687368ac

**Comment by jonaski** [comment]
I can reproduce a bug.: If the original year tag is not set, it will show year, but still sort after original year (which is empty), however it works if original year is set for the songs.
