### ISSUE TITLE
Connected device stuck updating

### ISSUE THREAD

**Issue by stem69** [strawberrymusicplayer/strawberry#1352]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
After connecting a OnePlus 9 Pro to my Linux Desktop, or double clicking on a Google Drive device, Strawberry only achieves ~40% update status. The devices never become available to browse. They are showing as mounted in Nemo.

**To Reproduce**
Open Strawberry;
Connect OnePlus 9 Pro by USB cable;
Set OnePlus 9 Pro to fIle transfer;
Click on Devices in Sidebar;
Double Click on device showing in Strawberry.

**Expected behavior**
Device updates and music files iare shown in Strawberry browser.

**Screenshots:**
![Screenshot from 2024-01-08 07-27-53](https://github.com/strawberrymusicplayer/strawberry/assets/6112148/75de9738-c953-4ca2-85aa-adcfa35d5b5c)

**System Information:**
 - Operating system: Linux Mint 21.1 / Kernel: 5.15.0-91
 - Strawberry Version: 1.0.22

**Additional context**

**Comment by R1D3R175** [comment]
Could you please attach logs?

**Comment by jonaski** [comment]
MTP is very slow, how long did you wait?
Starting strawberry from a terminal might be helpful to see debug output, it might give a hint on what's going on.

**Comment by jonaski** [comment]
Closing this since there is no reply back, I'll reopen if there is more information given.

**Comment by MDSvensson** [comment]
Compare Rhythm Box's performance using MTP against Strawberry's. Night and day. This affect everyone who uses music files with a phone device, since phones use MTP. Not only should this issue still be open, this should be a TOP PRIORITY to solve.
