### ISSUE TITLE
Add Search Filter Option.

### ISSUE THREAD

**Issue by LinuxBoy-96** [strawberrymusicplayer/strawberry#1357]
Hi! I have an idea that might be good an yet not too hard to do.

It should be possible in the search area to filter for different thing like Artist, Title, Album and other thing.
My personnal proble is that sometime, when I search something, I get unwanted results.

In my exemple I search “Alan”, thinking I will get anything related to Alan Walker but as you can see, I get also a song from David Guetta because a composer's name in the metadata is Alan. I never search that way and This is mildly annoying.
![strawb2](https://github.com/strawberrymusicplayer/strawberry/assets/128245725/4e39d0ee-cc55-488a-a67b-dd9fbcb7d4af)

**Comment by jonaski** [comment]
We already have this. Hover over the searchbar to get the tooltip with the details, use the forum if you have questions: https://forum.strawberrymusicplayer.org/

**Comment by LinuxBoy-96** [comment]
> We already have this. Hover over the searchbar to get the tooltip with the details, use the forum if you have questions: https://forum.strawberrymusicplayer.org/

With all due respect, although the current method is extremely powerful and work like a search engine, I do believe that it is too difficult to use for the casual user. Nothing is permanent and it's case-sensitive.

I do believe that the current method should remain but also that a proper filter menu be added.

**Comment by jonaski** [comment]
There is manly just me working on Strawberry, It's not possible for me to take on more work.
