### ISSUE TITLE
Pressing Enter with a multi-section

### ISSUE THREAD

**Issue by LinuxBoy-96** [strawberrymusicplayer/strawberry#1360]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
ENTER Key only put the last selected song in the playlist when used with a Multi-Selection.

**To Reproduce**
1. Select multiple song or album
2. Press Enter

**Expected behavior**
All selected song and album that are should be put in the playlist by pressing ENTER.

https://github.com/strawberrymusicplayer/strawberry/assets/128245725/4dad3aac-dee3-470a-9535-1a14169bcc45

**System Information:**
 - Operating system: Win11
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment]
We never had this implemented, but it makes sense.
