### ISSUE TITLE
Flatpak Metadata updating

### ISSUE THREAD

**Issue by firefoxlover** [strawberrymusicplayer/strawberry#1365]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

The App does not comply with (at least the useful parts of) the new Flatpak Metadata Guidelines.

- The Screenshots seem to be outdated and themed. I could provide one, or you do

The short description can be technical, but maybe put a break in between?

> Strawberry is free software released under GPL. The source code is available on GitHub. It's written in C++ using the Qt toolkit and GStreamer. Strawberry is compatible with both Qt version 5 and 6.

Also, the subtitle [may not comply](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#dont-start-with-an-article)

> A music player and collection organizer

If you agree, you could change it to

> Play music and organize your collections

But I think this is pretty opinionated by the Flathub People.

**Comment by jonaski** [comment]
We don't maintain or provide a flatpak. I don't want the extra work of having to comply to whatever guidelines Flatpak have.

**Comment by firefoxlover** [comment]
okay thanks, the flatpak linked to this site, which is sometimes done when projects officially support it.
