### ISSUE TITLE
Strawberry can open, play and edit metadata of m4b files, but are not listed in collection with other entries.

### ISSUE THREAD

**Issue by DavidPesticcio** [strawberrymusicplayer/strawberry#1372]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Perhaps not a bug, but would be nice to know either way. Why m4b files are functional in all other aspects in strawberry (except for editing the cover image due to not being in collection, even though the entry is in a collection directory) but don't show up the collection.

**To Reproduce**
Search for entry in collection - not listed.

**Expected behaviour**
Entry should be listed in collection?

**Screenshots:**
N/A

**System Information:**
 - Operating system: Linux
 - Strawberry Version: Version 1.0.23

**Additional context**
N/A

**Comment by jonaski** [comment]
m4b is not among the supported formats in TagLib which is probably why.
But if you could send me a file I can check to be sure.

**Comment by DavidPesticcio** [comment]
@jonaski - Sorry, I have no files to send. :unamused: 

Some files do not show up in a collection, but you can still use "Open with" then selecting Strawberry to open them - but you cannot edit the cover art, or enter a performer. This appears to be the same for other .m4b files also. Although _some_ .m4b files do show up in a collection, they have the same limitations as those that do not. :confused:

**Comment by jonaski** [comment]
The files that work might just be regular MP4/AAC files with an m4b extension, while we do not support m4b, anyway I can't find any file to test with so unless I can get a m4b file I can't do much.
