### ISSUE TITLE
No valid frames decoded before end of stream ~ "GstFlacDec:flacdec21: no valid frames found"

### ISSUE THREAD

**Issue by Valmar33** [strawberrymusicplayer/strawberry#1373]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When trying to play certain FLAC files, this error pops up:

No valid frames decoded before end of stream

../gstreamer/subprojects/gst-plugins-base/gst-libs/gst/audio/gstaudiodecoder.c(2492): gst_audio_decoder_sink_eventfunc (): /GstPlayBin3:pipeline-1-pipeline/GstURIDecodeBin3:uridecodebin3/GstDecodebin3:decodebin3-0/GstFlacDec:flacdec21: no valid frames found

**To Reproduce**
Try playing a FLAC file that triggers the error. Since that may or may not be difficult... I'll upload an example:
https://mega.nz/file/bYVSSAaa#_p_6lwzA015i0nWGgB5vmave3qwbizR8f_hV5kY89zs

**Expected behavior**
The file plays without issue.

**Screenshots:**
![Screenshot_20240207_114007](https://github.com/strawberrymusicplayer/strawberry/assets/5097518/4c6b1578-08ed-44f1-8c3f-69018bde542a)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.23 

**Additional context**
Example file works just fine in MPV, Audacity, Elisa, VLC, etc.

**Comment by jonaski** [comment]
Not sure if this is a bug in GStreamer, or the file is broken in some way. But I've reported it here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3281

**Comment by Valmar33** [comment]
> Not sure if this is a bug in GStreamer, or the file is broken in some way. But I've reported it here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3281
> 
> The error can be reproduced with `gst-launch-1.0 playbin3 uri=file:////path`

Hopefully they can get a fix in soon. :)

**Comment by jonaski** [comment]
One of the GStreamer developers replied, there is a bps mismatch between the meta and header issue with the file, if that's not allowed according to spec it won't be fixed as the behavior of not playing it is correct, but if it is allowed then it will probably be fixed sooner or later. Anyway just follow the issue at GStreamer to see what the conclusion will be, but closing this issue since this has to be fixed in GStreamer if something is to be fixed.
