### ISSUE TITLE
"delete from disk" action does not delete file from disk [solved]

### ISSUE THREAD

**Issue by jmsalvat** [strawberrymusicplayer/strawberry#1375]
- [x ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
"delete from disk" action does not delete file from disk.

**To Reproduce**
select from playlist  a son/file to be deleted 
right click on it to bring contextual menu
select delete from disk

**Expected behavior**
delete file from disk

**Screenshots:**

**System Information:**
 - Operating system: gentoo
 - Strawberry Version: strawberry-1.0.23
Linux-6.7.4

* dependency graph for media-sound/strawberry-1.0.23
```
  --  media-sound/strawberry-1.0.23  amd64 
   `--  dev-db/sqlite-3.44.2-r1  (dev-db/sqlite) amd64 
   `--  dev-libs/glib-2.78.3  (dev-libs/glib) amd64 
   `--  dev-libs/protobuf-21.12  (dev-libs/protobuf) amd64 
   `--  dev-qt/qtconcurrent-5.15.12  (dev-qt/qtconcurrent) amd64 
   `--  dev-qt/qtcore-5.15.12-r1  (dev-qt/qtcore) amd64 
   `--  dev-qt/qtdbus-5.15.12  (dev-qt/qtdbus) amd64 
   `--  dev-qt/qtgui-5.15.12  (dev-qt/qtgui) amd64 
   `--  dev-qt/qtnetwork-5.15.12-r1  (dev-qt/qtnetwork) amd64  [ssl]
   `--  dev-qt/qtsql-5.15.12  (dev-qt/qtsql) amd64  [sqlite]
   `--  dev-qt/qtwidgets-5.15.12  (dev-qt/qtwidgets) amd64 
   `--  dev-qt/qtx11extras-5.15.12  (dev-qt/qtx11extras) amd64 
   `--  media-libs/alsa-lib-1.2.10-r2  (media-libs/alsa-lib) amd64 
   `--  media-libs/taglib-1.13.1  (media-libs/taglib) amd64 
   `--  x11-libs/libX11-1.8.7  (x11-libs/libX11) amd64 
   `--  dev-libs/libcdio-2.1.0-r1  (dev-libs/libcdio) amd64 
   `--  media-libs/chromaprint-1.5.1-r3  (media-libs/chromaprint) amd64 
   `--  media-libs/gstreamer-1.20.6  (media-libs/gstreamer) amd64 
   `--  media-libs/gst-plugins-base-1.20.6  (media-libs/gst-plugins-base) amd64 
   `--  dev-libs/icu-74.2  (dev-libs/icu) amd64 
   `--  media-libs/libgpod-0.8.3-r6  (media-libs/libgpod) amd64 
   `--  sci-libs/fftw-3.3.10  (sci-libs/fftw) amd64 
   `--  media-libs/libmtp-1.1.21  (media-libs/libmtp) amd64 
   `--  media-libs/libpulse-16.1-r2  (media-libs/libpulse) amd64 
   `--  media-video/vlc-3.0.20-r3  (media-video/vlc) amd64 
   `--  dev-cpp/gtest-1.13.0  (dev-cpp/gtest) amd64 
   `--  dev-libs/boost-1.84.0-r3  (dev-libs/boost) amd64 
   `--  dev-qt/qttest-5.15.12  (dev-qt/qttest) amd64 
   `--  media-plugins/gst-plugins-meta-1.20.6  (media-plugins/gst-plugins-meta) amd64 
   `--  media-plugins/gst-plugins-soup-1.20.6  (media-plugins/gst-plugins-soup) amd64 
   `--  media-plugins/gst-plugins-taglib-1.20.6  (media-plugins/gst-plugins-taglib) amd64 
   `--  gnome-base/gvfs-1.52.1  (gnome-base/gvfs) amd64  [mtp]
   `--  sys-fs/udisks-2.10.1  (sys-fs/udisks) ~amd64 
   `--  dev-qt/linguist-tools-5.15.12  (dev-qt/linguist-tools) amd64 
   `--  sys-devel/gettext-0.22.4  (sys-devel/gettext) amd64 
   `--  virtual/pkgconfig-2-r1  (virtual/pkgconfig) amd64 
   `--  app-alternatives/ninja-1  (app-alternatives/ninja) amd64 
   `--  dev-build/cmake-3.27.9  (>=dev-build/cmake-3.20.5) amd64 
[ media-sound/strawberry-1.0.23 stats: packages (38), max depth (1) ]
```

```
app-misc/pax-utils:        1.3.7::gentoo
app-shells/bash:           5.2_p26::gentoo
dev-build/autoconf:        2.13-r8::gentoo, 2.71-r6::gentoo
dev-build/automake:        1.16.5-r2::gentoo
dev-build/cmake:           3.27.9::gentoo
dev-build/libtool:         2.4.7-r1::gentoo
dev-build/make:            4.4.1-r1::gentoo
dev-build/meson:           1.3.0-r2::gentoo
dev-java/java-config:      2.3.3-r1::gentoo
dev-lang/perl:             5.38.2-r1::gentoo
dev-lang/python:           3.10.13::gentoo, 3.11.7::gentoo, 3.12.1_p1::gentoo
dev-lang/rust-bin:         1.74.1::gentoo
sys-apps/baselayout:       2.14-r2::gentoo
sys-apps/openrc:           0.53::gentoo
sys-apps/sandbox:          2.38::gentoo
sys-devel/binutils:        2.41-r3::gentoo
sys-devel/binutils-config: 5.5::gentoo
sys-devel/clang:           15.0.7-r3::gentoo, 16.0.6::gentoo, 17.0.6::gentoo
sys-devel/gcc:             13.2.1_p20240113-r1::gentoo
sys-devel/gcc-config:      2.11::gentoo
sys-devel/llvm:            15.0.7-r3::gentoo, 16.0.6::gentoo, 17.0.6::gentoo
sys-kernel/linux-headers:  6.6::gentoo (virtual/os-headers)
sys-libs/glibc:            2.38-r10::gentoo
```

**Additional context**
this is odd
-used to works on same computer and setup
-doesn't work wither the file is in library or not.
-even after reindexing the whole library

it is build without KDSingleApplication

**Comment by jmsalvat** [comment]
same if build with KDSingleApplication
by the way what is KDSingleApplication for?

same for strawberry-1.0.22 qt5
 strawberry-1.0.23 qt6 and KDSingleApplication
 strawberry-1.0.23 qt5

**Comment by jmsalvat** [comment]
actually delete from disk does delete file only when file is playing.
this is odd 
I expect it to delete any file 
playing or not ,
in database or not
when file is in playlist...
Am I wrong to assume  this?

**Comment by jonaski** [comment]
> actually delete from disk does delete file only when file is playing. this is odd I expect it to delete any file playing or not , in database or not when file is in playlist... Am I wrong to assume this?

This does not make sense. The delete feature works fine here. This is most likely a system related issue, not a bug in strawberry. Check file permissions, etc.
When deleting files in strawberry, it uses the trash, if the trash on system is not working or is disabled it might cause an issue.

**Comment by jmsalvat** [comment]
> This does not make sense. 
agreed

>  The delete feature works fine here
on my laptop it does work fine too
on the desktop it used to work fine.. not anymore

file permissions ok 
inode ok
trash ok
no problemes on os/DE(KDE5)

but when strawberry start
it does complain about files which are no there anymore.
and yes there are not there because they have been moved previously.
`strawberry --verbose                                           
22:04:26.505 INFO  main:180                         Strawberry 1.0.23 Qt "6.6.1"
22:04:26.505 INFO  main:181                         "Gentoo Linux 2.14 - (linux 6.7.4-gentoojms-0.7.37) [x86_64]"
22:04:26.533 INFO  main:47                          TagReader worker connecting to "/tmp/strawberry_57367136"
22:04:26.536 ERROR GlobalShortcutsBackendKDE:161    KGlobalAccel returned QList() when setting shortcut QList(QKeySequence("Media Next"))
22:04:26.536 ERROR GlobalShortcutsBackendKDE:161    KGlobalAccel returned QList() when setting shortcut QList(QKeySequence("Media Play"))
22:04:26.536 ERROR GlobalShortcutsBackendKDE:161    KGlobalAccel returned QList() when setting shortcut QList(QKeySequence("Media Previous"))
22:04:26.536 ERROR GlobalShortcutsBackendKDE:161    KGlobalAccel returned QList() when setting shortcut QList(QKeySequence("Media Stop"))
22:04:26.622 INFO  Player:954                       Registered URL handler for "subsonic"
22:04:26.625 INFO  Player:954                       Registered URL handler for "tidal"
22:04:26.635 INFO  Player:954                       Registered URL handler for "qobuz"
TagLib: Could not open file /home/data/data2/Musitek/muzitek/Various_Artists/Rolling_Stone's_500_-2021/Various_Artists_-_Rolling_Stone's_500_-2021_-_Heart_Of_Glass.opus
22:04:27.548 INFO  TagReaderTagLib:255              TagLib hasn't been able to read "/home/data/data2/Musitek/muzitek/Various_Artists/Rolling_Stone's_500_-2021/Various_Artists_-_Rolling_Stone's_500_-2021_-_Heart_Of_Glass.opus" file
TagLib: Could not open file /home/jms/Downloads/musique/youtube/jms/Survivor - Eye Of The Tiger (Official HD Video) [btPJPFnesV4].opus
22:04:27.643 INFO  TagReaderTagLib:255              TagLib hasn't been able to read "/home/jms/Downloads/musique/youtube/jms/Survivor - Eye Of The Tiger (Official HD Video) [btPJPFnesV4].opus" file
TagLib: Could not open file /home/jms/Downloads/musique/youtube/jms/ZAYDE WOLF - SHOUT (Tears for Fears Cover) [zZUpsX3S1NA].opus
22:04:27.644 INFO  TagReaderTagLib:255              TagLib hasn't been able to read "/home/jms/Downloads/musique/youtube/jms/ZAYDE WOLF - SHOUT (Tears for Fears Cover) [zZUpsX3S1NA].opus" file
TagLib: Could not open file /home/jms/Downloads/musique/youtube/jms/Zebda - Le sud [20APRyJOQ7A].opus
22:04:27.644 INFO  TagReaderTagLib:255 `

could this be  a database related problem?

**Comment by jmsalvat** [comment]
> This does not make sense. The delete feature works fine here. This is most likely a system related issue, not a bug in strawberry. Check file permissions, etc. When deleting files in strawberry, it uses the trash, if the trash on the system is not working or is disabled it might cause an issue.

Thanks for pointing me to the right direction.
I finally nailed it
the trash was the issue.

other than the /home/user ,
I had another mounted filesystem as root and a user directory with music files in it.
strawberry can not create .trash directory then can not use it then do not delete

solution:
do not have top mounted directory as root but as strawberry user
or create a trash directory with good permission for strawberry user at the root dir of the mounted filesytem

I was only checking the home/user trash forgot that trash could be created on others filesytem.


I am closing this bug

opening a new one about as I think in accordance to freedesktop trash spec strawberry should issue a warning in such case
https://github.com/strawberrymusicplayer/strawberry/issues/1384
