### ISSUE TITLE
Songs skipping/rapidly playing(?) while Strawberry volume set to 0%

### ISSUE THREAD

**Issue by watermelvin** [strawberrymusicplayer/strawberry#1376]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Playback at 0% volume leads to a buffering status as Strawberry rapidly plays/skips(?) through all tracks in the playlist. Setting the volume to a nonzero value stops this skipping behavior.

**To Reproduce**
Begin playback with volume slider set to 0%.

**Expected behavior**
Playback continues as normal, rather than instantly skipping through tracks.

**Screenshots:**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/89646595/4dd44b2f-fc17-4919-90e8-64117dd67009)

**System Information:**
 - Operating system:  OpenSUSE Tumbleweed
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment]
I can confirm this bug, I think it's a GStreamer 1.22.9 bug.

**Comment by jonaski** [comment]
Same issue with alsasink, pulsesink on linux, but pipewiresink works. Same issue on Windows with directsoundsink, wasapisink and wasapi2sink.

**Comment by jonaski** [comment]
It works with GStreamer 1.22.8, but both version 1.22.9 and 1.22.10 are affected.

**Comment by jonaski** [comment]
Definitely a GStreamer bug:

`gst-launch-1.0 filesrc location=/home/jonas/Music/FLAC/Albums/Snowy_White/Highway_To_The_Sun/01_-_Snowy_White_-_Highway_To_The_Sun_-_Highway_To_The_Sun.flac ! decodebin ! audioconvert ! volume volume=0 ! alsasink device=hw:1,0`

```
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstAudioSinkClock
Got EOS from element "pipeline0".
Execution ended after 0:00:00.230159042
Setting pipeline to NULL ...
Freeing pipeline ...

```

**Comment by jonaski** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3303

**Comment by jonaski** [comment]
The change that caused this has been reverted in GStreamer, and I've also submitted the patch to openSUSE, so it is resolved in the latest tumbleweed release.
I've also asked arch linux if they can apply the patch: https://gitlab.archlinux.org/archlinux/packaging/packages/gst-plugins-base/-/issues/1
