### ISSUE TITLE
feature request: log

### ISSUE THREAD

**Issue by alekksander** [strawberrymusicplayer/strawberry#138]
are there plans to introduce simple event log viewer? played(completed) tracks, tracks deleted from playlist, queued tracks, successful/unsuccessful scrobbles, new items in collection(scanning). this could be very useful and hopefully not only for me. 

thank You for doing fantastic job so far

**Comment by jonaski** [comment]
Not sure why you would want that in a music player

**Comment by alekksander** [comment]
thought i might skip this one, but i daily lack info of which track was played before i stopped playback. selection on the playlist stays on the track that was played first. there is no way to know which one was played as last (ofc not in situation whole playlist went through). therefore need for log. perhaps some sort of mark, greyed–out selection, or option similar to what foobar has — to prefer if selection follows playback (btw foobar also has playback following selection. both are very useful) will fix this. 

for other events logs are just useful to know if there are any problems (like not scrobbling, decoding issues), to see what happens „behind the curtain” and generally to have better control of player.

what do You think?

**Comment by dermamred** [comment]
I think that a "history" tab could be very useful... in "gmusicbrowser" I got used a lot this type of log/history... and it could be useful too if it was saved what tab was selected on exiting so U could restart having the same tab yet selected... for me this 2 things, "History" tab & saved state selected tab, walk together.

**Comment by alekksander** [comment]
another example of usefulness of such a log is an issue https://github.com/jonaski/strawberry/issues/154 which remains undetected problem unless i specifically try to play this one album. if indexing tracks was visible error could be seen and diagnosed easily.

**Comment by jonaski** [comment]
I know there is a need for a way to show errors better, right now there is only the option between the intrusive error dialog or simply logging to terminal which most people dont see. Shouldn't be too hard to add an option to also log other events too if we implement a better error dialog.
It could be a log viewer accessible from the tools menu, but when errors occur there could be a flashing icon on the bottom with the scrobble icon, or a squeeze in 1 logline that can be clicked to show the whole dialog.

**Comment by alekksander** [comment]
how about new tab with flash/dot/highlight? this way there is no need for new ui element – just new tab

**Comment by jonaski** [comment]
I'm closing this since I don't have time to prioritize it. Someone else is free to make a proposal for this feature in a PR.
