### ISSUE TITLE
Mouse Scroll Wheel Unexpectedly Modifies Dropdown Values in Settings Window

### ISSUE THREAD

**Issue by illtellyoulater** [strawberrymusicplayer/strawberry#1380]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). _**By the way** I won't make a forum account just to be able to search a forum, as if this was 2003. Please open up the forum search feature to the public, while adding some anti-abuse protection to it, matching today's usability expectations. This would be beneficial to the entire Strawberry community._

**Describe the bug**
While navigating the settings window in Strawberry Music Player, using the mouse scroll wheel over dropdown menus unexpectedly modifies their values without any user input other than scrolling. This behavior diverges from the standard UI practices seen in most operating systems, where scrolling over a dropdown menu does not change its value unless the menu is actively expanded. This can lead to unintentional settings changes by the user.

**To Reproduce**
1. Go to 'Settings' in the Strawberry Music Player.
2. Hover the mouse cursor over any dropdown menu within the various settings subsections.
3. Use the mouse scroll wheel to navigate through the settings.
4. Observe that the value of the dropdown menu changes as the mouse wheel scrolls over it.

**Expected behavior**
The expected behavior is that scrolling over a dropdown menu should not change its value unless the menu is actively selected and expanded. This would prevent unintentional changes to settings by merely scrolling through the options.

**System Information:**
 - Operating system: Pop!_OS 22.04 LTS x86_64
 - Strawberry Version: 1.0.23

**Additional context**
This issue may lead to a frustrating user experience, as changes could be made without direct awareness, possibly affecting the application's performance or behavior unexpectedly.

**Comment by jonaski** [comment]
I agree with you, but it's the default behavior of QComboBox in Qt, changing is not just changing a property, we need to create custom combobox and override the scroll event, if it wasn't for that, it would have been done a long time ago. But it might be wroth doing anyway, the behavior is annoying.

**Comment by illtellyoulater** [comment]
Sure, let's see if I can help; I asked ChatGPT 4 to make an online search to see if anyone might have already addressed this, here's the answer:

Several approaches have been discussed and implemented by the Qt community to address the issue of disabling mouse wheel events on QComboBox widgets to prevent unintended value changes. Here are the summarized strategies from the forums:

1. **Event Filter Method**: You can install an event filter on the QComboBox. In the event filter, check if the event is a wheel event and simply return true to indicate that the event has been handled, effectively blocking it. This approach was detailed in the Qt Forum and Qt Centre discussions, demonstrating how to intercept and block wheel events specifically for combo boxes without requiring subclassing of the widget itself. This method involves overriding the `eventFilter` method in your class that contains the QComboBox and installing the event filter on the QComboBox instance.

2. **Custom Subclassing Method**: Another method involves subclassing QComboBox and overriding the `wheelEvent` method. Within this method, you can include a condition to only call the base class's wheelEvent method if the combo box currently has focus. This ensures that wheel events will only affect the combo box when it is explicitly focused, avoiding unintended value changes when scrolling over it. This approach requires a bit more code but offers more control over the behavior of the combo box.

Both strategies are aimed at enhancing user experience by ensuring that combo box values cannot be changed unintentionally through scroll wheel actions, especially when the combo box is not the current focus of the application.

For implementing these solutions, the key is to intercept the wheel event and decide whether to propagate it to the QComboBox based on the widget's focus state. These solutions provide a way to customize the behavior of QComboBox in your application to match user expectations and standard UI practices more closely.

References:
- Qt Forum discussion on disabling mouse wheel scrolling on a ComboBox: [forum.qt.io/topic/59191/combobox-disable-mouse-wheel-scrolling](https://forum.qt.io/topic/59191/combobox-disable-mouse-wheel-scrolling)
- Qt Forum on ignoring mouse wheel events when ComboBox is not in focus: [forum.qt.io/topic/25072/how-to-ignore-the-mouse-wheel-event-when-combo-box-is-not-in-focus](https://forum.qt.io/topic/25072/how-to-ignore-the-mouse-wheel-event-when-combo-box-is-not-in-focus)
- Qt Centre discussion on disabling wheelEvent: [www.qtcentre.org](https://www.qtcentre.org) 

These discussions and code examples should provide a solid foundation for addressing the issue in the Strawberry Music Player or any other application using Qt widgets.

**Comment by illtellyoulater** [comment]
Is this what they mean when they say godspeed? ;) I'm eager to see the change in action! Thank you.

**Comment by jonaski** [comment]
You can try the latest from https://builds.strawberrymusicplayer.org/ubuntu/jammy/ if you want to test (Jammy should be compatible with Pop Os).

**Comment by illtellyoulater** [comment]
I am currently using the flatpak version. Could you please push the update to that version too?
