### ISSUE TITLE
Shuffle order is always the same

### ISSUE THREAD

**Issue by nokia8801** [strawberrymusicplayer/strawberry#1381]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When clicking on a song, the same shuffle order is used for each song. If Song A goes like A>Z>K>D then if we click on Song A again it'll follow A>Z>K>D. If Song O is O>Y>T>R then it'll still be O>Y>T>R if clicked on again.

**To Reproduce**
Play Song A, it'll jump to Song Z, then Song K, then Song D. Now click on Song A again and it'll follow the same order of A>Z>K>D. This is the case for all songs in a playlist. The shuffle order of each song is the always same. For example, C>F>K>Z is always C>F>K>Z if clicked on C again.

**Expected behavior**
In other music players like iTunes, every time you click a song, you get a new shuffle order. Meaning if we click Song A and get A>Z>K>D, the next time we click on A we will get something completely different, A>F>U>L. Each click makes a new shuffle order.

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.23-40-g593a04d0

**Additional context**
Shuffle mode is shuffle all. Repeat mode is repeat playlist. There seems to be two ways to get a new shuffle order. One is to quit and reopen the app. The other is to click on another song and then click back on song A. This time Song A will get a new shuffle order.

**Comment by jonaski** [comment]
This is a behavior inherited from Clementine.
The reason it was done this way was to preserve play history for the back button, unfortunately this causes many issues including this, and others such as #707.
I doubt it was intentional, at least I consider it a design flaw, not a feature.
I've been wanting to address this for years, but since I never use the shuffle feature myself it just hasn't been prioritized yet.

**Comment by nokia8801** [comment]
I can confirm my issue is fixed. Now each clicks generates a new shuffle order for that song. Back button and history still works. Thanks.
