### ISSUE TITLE
Delete from disk crashes Strawberry in Win10

### ISSUE THREAD

**Issue by racuna** [strawberrymusicplayer/strawberry#1386]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
In Windows 10, sometimes with the right button on a song and select "Delete from disk..." crashes de entire app. 

**To Reproduce**
From the current playlist, delete from disk a song that is currently playing.

**Expected behavior**
Just delete the song and play the next. 

PS. This issue happens randomly, not always, but it is pretty frequent.

**Screenshots:**

**System Information:**
 - Windows 10
 - Strawberry Version: 1.0.23

**Additional context**
I installed it (and update) using chocolatey repos.

**Comment by jonaski** [comment]
Is this the MSVC or MinGW version of Strawberry?
Can you check the Windows Application log for entries after the crash and copy/paste it here.
Control Panel / All Control Panel Items / Administrative Tools / Event Viewer / Windows Logs / Application

**Comment by racuna** [comment]
> Is this the MSVC or MinGW version of Strawberry?
Msvc acording to chocolatey script:
"https://github.com/strawberrymusicplayer/strawberry/releases/download/$version/StrawberrySetup-$version-msvc-x64.exe"

log:
```
Nombre de la aplicación con errores: strawberry.exe, versión: 1.0.23.0, marca de tiempo: 0x65a05103
Nombre del módulo con errores: Qt6Core.dll, versión: 6.6.1.0, marca de tiempo: 0x659ef88c
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x00000000000e4619
Identificador del proceso con errores: 0x28b8
Hora de inicio de la aplicación con errores: 0x01da68c836a89fc1
Ruta de acceso de la aplicación con errores: C:\Program Files\Strawberry Music Player\strawberry.exe
Ruta de acceso del módulo con errores: C:\Program Files\Strawberry Music Player\Qt6Core.dll
Identificador del informe: 5125c3df-f1aa-49bd-aed6-448257c2c2fc
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores: 

XML: 
[-](https://github.com/strawberrymusicplayer/strawberry/issues/1386#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/strawberrymusicplayer/strawberry/issues/1386#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-02-27T19:28:44.2537291Z" /> 
  <EventRecordID>106004</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>NTB-RACUNA2.neuronetcl.local</Computer> 
  <Security /> 
  </System>
[-](https://github.com/strawberrymusicplayer/strawberry/issues/1386#) <EventData>
  <Data>strawberry.exe</Data> 
  <Data>1.0.23.0</Data> 
  <Data>65a05103</Data> 
  <Data>Qt6Core.dll</Data> 
  <Data>6.6.1.0</Data> 
  <Data>659ef88c</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000e4619</Data> 
  <Data>28b8</Data> 
  <Data>01da68c836a89fc1</Data> 
  <Data>C:\Program Files\Strawberry Music Player\strawberry.exe</Data> 
  <Data>C:\Program Files\Strawberry Music Player\Qt6Core.dll</Data> 
  <Data>5125c3df-f1aa-49bd-aed6-448257c2c2fc</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by jonaski** [comment]
Thanks, unfortunately I can't reproduce it, could you try the latest from https://builds.strawberrymusicplayer.org/windows/msvc and check if the issue is still there.

**Comment by racuna** [comment]
Thanks I will. I just installed the [StrawberrySetup-1.0.23.52.g04ba202e-msvc-x64.exe](https://builds.strawberrymusicplayer.org/windows/msvc/StrawberrySetup-1.0.23.52.g04ba202e-msvc-x64.exe) version.

But as I tell you, the bug doesn't always appear, so give me some time, and I'll back later to report (I already deleted two songs without issues) if the bug is still here or not. 

Thank you very much

**Comment by jonaski** [comment]
I'll reopen this if this is still an issue.
