### ISSUE TITLE
Scrobbler removes "(Remastered)" from song titles

### ISSUE THREAD

**Issue by SnootyInk8302** [strawberrymusicplayer/strawberry#1387]
**Describe the bug**
If I scrobble a track that has the word Remastered, (Remastered), Remastered) or any variation of this, it is sent without it to last.fm. Doesn't affect "Remaster".

**To Reproduce**
Play a song with the word in the title.

**Expected behavior**
It should scrobble the entire title

**System Information:**
 - Operating system: Ubuntu Budgie 23.10
 - Strawberry Version: Version 1.0.23

**Screenshots:**
![Screenshot from 2024-02-29 23-13-54](https://github.com/strawberrymusicplayer/strawberry/assets/79272501/f616f340-0596-4d70-9908-cdd7a2284448)
![Screenshot from 2024-02-29 23-14-26](https://github.com/strawberrymusicplayer/strawberry/assets/79272501/7177189f-46ae-4d51-8273-d9c7868f238c)

**Comment by SnootyInk8302** [comment]
Found it. It is line 172 from "strawberry/src/core/song.cpp" right? Can we get an option to toggle it on and off?

**Comment by SnootyInk8302** [comment]
Update: managed to fix it by replacing:

```
const QRegularExpression Song::kAlbumRemoveDisc(" ?-? ((\\(|\\[)?)(Disc|CD) ?([0-9]{1,2})((\\)|\\])?)$", QRegularExpression::CaseInsensitiveOption);
const QRegularExpression Song::kAlbumRemoveMisc(" ?-? ((\\(|\\[)?)(Remastered|([0-9]{1,4}) *Remaster|Explicit) ?((\\)|\\])?)$", QRegularExpression::CaseInsensitiveOption);
const QRegularExpression Song::kTitleRemoveMisc(" ?-? ((\\(|\\[)?)(Remastered|Remastered Version|([0-9]{1,4}) *Remaster) ?((\\)|\\])?)$", QRegularExpression::CaseInsensitiveOption);
```
with:

```
const QRegularExpression Song::kAlbumRemoveDisc("", QRegularExpression::CaseInsensitiveOption);
const QRegularExpression Song::kAlbumRemoveMisc("", QRegularExpression::CaseInsensitiveOption);
const QRegularExpression Song::kTitleRemoveMisc("", QRegularExpression::CaseInsensitiveOption);
```

before compiling. 

![Screenshot from 2024-03-02 17-27-37](https://github.com/strawberrymusicplayer/strawberry/assets/79272501/d8fcc32e-7d5e-41fb-86fb-82e5e7b615c5)

I don't know if I would call this solved though.

**Comment by jonaski** [comment]
It's supposed to strip of remastered from the album title to get better matches for cover, lyrics searches, and the scrobbler also uses it, does Last.fm or Listenbrainz have a match for the songs with "Remastered" in it? In that case we should create an option or not do it at all.

But I see it does not handle "(Mono / Remastered)" properly, stripping of half of it, and that's of course a bug.

**Comment by jonaski** [comment]
> ```
> const QRegularExpression Song::kAlbumRemoveDisc("", QRegularExpression::CaseInsensitiveOption);
> const QRegularExpression Song::kAlbumRemoveMisc("", QRegularExpression::CaseInsensitiveOption);
> const QRegularExpression Song::kTitleRemoveMisc("", QRegularExpression::CaseInsensitiveOption);
> ```
> 

This is a really bad idea, these constants are used for much more than just the scrobbler.

**Comment by SnootyInk8302** [comment]
Yes, it is a slipshoded way of doing it and I do NOT endorse this approach. However it works for me right now so I thought I should share it with others in the meantime. A toggle would definitely be preferred, but I don't know C/C++ so I sadly can't help.

**Comment by SnootyInk8302** [comment]
Can confirm the new commit fixed the (Mono / Remastered) problem. Thanks a lot!

![Screenshot from 2024-03-02 22-13-59](https://github.com/strawberrymusicplayer/strawberry/assets/79272501/7b19e947-05d9-4d35-a6a9-16d526ec161f)

**Comment by jonaski** [comment]
I've made an option for turning stripping of remastered off in the scrobbler settings now.

**Comment by SnootyInk8302** [comment]
Thank you very much. Glad this was officially added. I was stuck with my old modified version of the app.
