### ISSUE TITLE
Sidebar has "&" characters in text where it shouldn't

### ISSUE THREAD

**Issue by Sunspark-007** [strawberrymusicplayer/strawberry#1389]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The sidebar has the "&" character appear where it shouldn't.

**To Reproduce**
Open the flatpak.

**Expected behavior**
Normal text without the "&" showing up.

**Screenshots:**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/73711243/81d4e87a-90bf-402a-b5a3-bb896c9252b4)

**System Information:**
Operating System: SteamOS 3.4.11
KDE Plasma Version: 5.26.1
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 5.13.0-valve37-1-neptune (64-bit)
Graphics Platform: X11

**Additional context**
N/A

**Comment by jonaski** [comment]
This isn't a Strawberry bug, probably a KDE bug. I suggest to report this your distro, or try.:
`kwriteconfig5 --file kdeglobals --group Development --key AutoCheckAccelerators "false"`

**Comment by bravemenrun** [comment]
I see this is closed but I was having the same issue. The above command seems to have worked. I remember this started happening after updating from Plasma 5 to Plasma 6.

**Comment by Ryder17z** [comment]
it's not clear if it's KDE or Qt that's the actual culprit here. Link to the kde bug report: https://bugs.kde.org/show_bug.cgi?id=425410
