### ISSUE TITLE
New Smart playlist on Windows has inconsistent font and background using dark mode.

### ISSUE THREAD

**Issue by ryoukaip** [strawberrymusicplayer/strawberry#1399]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The color of the font and the background is both white when "Dark mode" option is enabled in Windows Settings.

**To Reproduce**
Click Smart playlists -> Click "New smart playlist" button

**Expected behavior**
Either black font + white background or white font + black background

**Screenshots:**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/55135799/299aceed-7c08-4769-8eff-c6fb885303dd)
![image](https://github.com/strawberrymusicplayer/strawberry/assets/55135799/61e5e362-88a3-4e82-bc99-882fe1ee2bbb)

**System Information:**
 - Operating system: Windows 11 Version 21H2 (OS Build 22000.318)
 - Strawberry Version: 1.0.23-mingw-x64

**Comment by jonaski** [comment]
https://bugreports.qt.io/browse/QTBUG-123853
