### ISSUE TITLE
Ampersand symbol erroneously displayed along with text in side panel 

### ISSUE THREAD

**Issue by Bulletdust** [strawberrymusicplayer/strawberry#1400]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry music player has ampersand symbols mixed with text in the LHS pane side panel. This happens if I install the latest stable release via PPA, or if I install the Flatpak. I believe the ampersand symbols are keyboard shortcut markers and shouldn't be visible.

**To Reproduce**
Install Strawberry Music Player Version 1.0.23 via either PPA or Flatpak, open Strawberry Music Player. _Possibly use an OS running Plasma 6._

**Expected behavior**
Text should be displayed without ampersand symbols in the LHS pane side panel.

**Screenshots:**
See attached screenshot below.

**System Information:**
 - Operating system: KDE Neon User Edition version 6.0.2
 - Strawberry Version: 1.0.23

**Additional context**
This problem may have started with the update to Plasma 6, although it must be emphasized that I'm not 100% certain of this.

![Strawberry corrupted font](https://github.com/strawberrymusicplayer/strawberry/assets/45522363/00d76642-399e-4f89-a9f5-f24abc6d633a)

**Comment by jonaski** [comment]
I can confirm this with Qt 6.6.2, it's probably a Qt bug already fixed, works using the latest Qt from the git development branch, you can workaround it with:
`kwriteconfig5 --file kdeglobals --group Development --key AutoCheckAccelerators "false"`
