### ISSUE TITLE
Closing file browser will close Strawberry unless system tray icon option is enabled

### ISSUE THREAD

**Issue by Mel34** [strawberrymusicplayer/strawberry#1401]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Qt6 introduced a behavior change in `QEventLoopLocker`: when the last `QEventLoopLocker` goes away (e.g. dismissing the file picker window) the event loop exits. On KDE platform `KFileWidget` internally uses `QEventLoopLocker`, so creating it triggers this behavior. Each `QEventLoopLocker` has a refcount in the `QCoreApplication` and when the counter hits zero the application quits. Using the system tray icon keeps this counter above zero, but with the option disabled it will cause Strawberry to quit. Qt6 behavior changed so that setting `quitOnLastWindowClosed` is no longer enough to address the issue. The fix is to use `QCoreApplication::setQuitLockEnabled(false)`. Kindly refer to the provided URLs listed under **Additional context.**

**To Reproduce**

1. Use Qt6 version of Strawberry
2. Disable 'Show system tray icon' option
3. Use Open file option in Music menu
4. Dismiss the file picker dialog (either pick something or close it)
5. Observe that Strawberry exits cleanly

**Expected behavior**
Strawberry doesn't exit when file picker is dismissed without system tray icon used

**Screenshots:**
N/A

**System Information:**
 - Operating system: Archlinux
 - Strawberry Version: 1.0.23

**Additional context**
https://bugs.kde.org/show_bug.cgi?id=483439
https://bugs.kde.org/show_bug.cgi?id=483757
https://bugs.kde.org/show_bug.cgi?id=471941

**Comment by jonaski** [comment]
Since https://bugreports.qt.io/browse/QTBUG-124386 was fixed, should `QCoreApplication::setQuitLockEnabled(false);` be removed?
