### ISSUE TITLE
support common lyrics tags like e.g. UNSYNCED LYRICS

### ISSUE THREAD

**Issue by elandorr** [strawberrymusicplayer/strawberry#1402]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

Sorry, I will not create YET ANOTHER account just for a quick note.

**Describe the bug**
The `UNSYNCED LYRICS` tag is common, as are others, and should be supported. Ideally let the user decide, like the "standard" music collector tools on foobar2000: https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components/OpenLyrics_(foo_openlyrics)

`LYRICS;SYNCEDLYRICS;UNSYNCEDLYRICS;UNSYNCED LYRICS`

**To Reproduce**
see above

**Expected behavior**
Read and display user-defined tags instead of forcing yet another arbitrary convention. 

**Screenshots:**

**System Information:**
 - Operating system:
 - Strawberry Version:

**Additional context**
It would be great if you could display RAW tags in general. Currently the tag display only shows fixed ones. In the GOAT foobar2000, many users create their own conventions for metadata, filter, etc. It works and is clean!

Thanks for reading.

**Comment by jonaski** [comment]
We already support it, is it not working? In that case, what tag type and audio format is it?

**Comment by jonaski** [comment]
Looks like we read both "LYRICS" and "UNSYNCEDLYRICS" for Ogg tags. The link you provided only specifies ID3v2 tags and is not official specifications.

Replay gain tags are read by GStreamer, and I don't think r128_album_gain / r128_track_gain is used, they are not listed on https://gstreamer.freedesktop.org/documentation/replaygain/rgvolume.html?gi-language=c
