### ISSUE TITLE
Starred playlist content is lost, when songs moved to a different path

### ISSUE THREAD

**Issue by AllKind** [strawberrymusicplayer/strawberry#1403]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

I moved some folders of my library to a different path. Now all my starred playlists (using these folders) are empty.
I tried to create symbolic links at the old locations, but that didn't help.
Question: Where are the "starred" playlists stored? Maybe I could restore them from a backup?

**To Reproduce**
Create a playlist with some songs in it.
Star it.
(Maybe close strawberry - not sure if that is needed).
Move the songs elsewhere.
(Start strawberry)
Result: starred playlist is empty.

**Expected behavior**
If "Mark dissapeared songs unavailable" is activated in settings -> Collection, then the unavailable songs should be greyed, as they are in "regular" playlists.

**System Information:**
 - Operating system: Linux Mint 21.3
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment]
I can't reproduce this if the "Mark disappeared songs unavailable" option is on (checked), with the behavior you describe it seems the option was off.
Could you check again and see if you can reproduce it consistently.
The database is in `~/.local/share/strawberry/strawberry/strawberry.db` it contains the collection and playlists, please backup this first.

**Comment by AllKind** [comment]
Ah, I now see the missing thing.
I also removed those folders from settings -> Collection. (I moved all the old folders into one directory and added that as collection folder.)
Adding a symbolic link and adding that as folder in settings -> Collection does not help, as strawberry resolves the link and adds the destination of the link to the list of collection folders.

So:
If the folder is missing the songs get greyed.
But if the folder is also removed from Settings -> Collection, the playlist becomes blank.

**Comment by jonaski** [comment]
If you remove a collection directory, those playlists with songs that point to that will be broken as it's linked with the collection database song IDs, that's the way it's structured, so no easy way to solve that.
I will look into creating an option for following symbolic links optional, but I need to check if that will be safe to do in regard to the watcher/scanner.

**Comment by AllKind** [comment]
Maybe a warning, about the starred playlists are about to be lost - on collection folder removal, would be helpful and may prevent others falling into the same trap as me?
