### ISSUE TITLE
"Save settings" of "Organize files" is broken

### ISSUE THREAD

**Issue by AllKind** [strawberrymusicplayer/strawberry#1404]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
If you right-click one, or multiple songs in a playlist and select "Organize files", a window pops up with a lot of options how to proceed with organizing.
Now change some of the settings and click "OK" (not clicking on "Save settings").
Open the "Organize files" again and you will see the changes you made before are (permanently) saved. With the exception of the "After copying" action - that setting is not saved (not even if you would have chosen "Save settings"). See https://forum.strawberrymusicplayer.org/topic/1328/remember-after-copying-action-in-organize-files.

**To Reproduce**
As above.

**Expected behavior**
Choosing "Save settings" should save ALL settings (including "After copying" action).
Just choosing "OK" should not permanently remember the "One time" settings.
Otherwise the "Save settings" button is just redundant.

**System Information:**
 - Operating system: Linux Mint 21.3
 - Strawberry Version: 1.0.23

**Additional context**
As a feature idea/request: It would be nice if "Save settings" would allow to save to different named profiles.
This would allow to have several profiles defined for different needs.

**Comment by jonaski** [comment]
The "After copying" is depending on which dialog is opened, so I'm not going to change it, changing it might lead to unexpected issues with deleting files when it shouldn't.
