### ISSUE TITLE
"Shuffle all" repeats songs after program restart

### ISSUE THREAD

**Issue by AllKind** [strawberrymusicplayer/strawberry#1405]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I have some large playlists and I like to activate "Shuffle all" for various reasons.
If strawberry is closed and restarted, songs that have been played before are played again.
This behavior makes my large playlists (multiple days of playtime) effectively never finish, as I have to shutdown/restart the PC once in a while.

**To Reproduce**
See above.

**Expected behavior**
It would be nice if strawberry could remember the songs already played in "Shuffle all" mode.

**System Information:**
 - Operating system: Linux Mint 21.3
 - Strawberry Version: 1.0.23

**Additional context**
Surely shuffled playback is much more complicated (lots of issues already open as I see), then "normal" ordered playback. But I guess saving some list internally and reloading it next time strawberry starts is doable.

Feature idea: Add the option to enable/disable shuffle mode per playlist, not just globally.

**Comment by jonaski** [comment]
It does not make sense to me since the shuffle feature should pick random songs anyway, but it is currently very broken, so the priority is to fix that.
