### ISSUE TITLE
Ampersands "&" are randomly inserted in Settings/Context newly added tags

### ISSUE THREAD

**Issue by b606** [strawberrymusicplayer/strawberry#1407]
- [*] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [*] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [*] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Spurious "&" are randomly inserted in Settings/Context newly added tags, resulting in buggy Context texts.

**To Reproduce**
Go to menu Tools/Settings and in the "Context" section, add new tags to personalize the displayed text.

**Expected behavior**
The added tag text should be the same as in the dropdown list on the right.

**Screenshots:**
 (see screenshot).

**System Information:**
 - Operating system: Debian Bookworm
 - Strawberry Version:  `flatpak info org.strawberrymusicplayer.strawberry` 
```
          ID: org.strawberrymusicplayer.strawberry
         Ref: app/org.strawberrymusicplayer.strawberry/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.23
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 248,4 Mo
     Runtime: org.kde.Platform/x86_64/6.6
         Sdk: org.kde.Sdk/x86_64/6.6

      Commit: 7b5e244fc2f038aa0d865e303683a19538da1898bdaf6deee45a802093cb6532
      Parent: 92eab1ea728f2b1379727fddf7d20fe2c06b4b43a93495c395d9b0462af048e1
     Subject: Update strawberry-1.0.22.tar.xz to 1.0.23 (74b13794)
        Date: 2024-01-12 06:55:07 +0000
```

**Additional context**
![strawberry-setting-context-editor](https://github.com/strawberrymusicplayer/strawberry/assets/7627533/a59ad3a2-6b32-47e1-b8d3-ce45fbc25ee3)

**Comment by jonaski** [comment]
The bug is either in Qt or KDE. As a workaround try:
`kwriteconfig5 --file kdeglobals --group Development --key AutoCheckAccelerators "false"`

**Comment by b606** [comment]
Thank you very much for the quick answer.
This solved the problem (until AutoCheckAccelerators is needed).
Now, I understand why ampersands were also automatically added when editing the name in the playlist tabs.

**Comment by jonaski** [comment]
This is already reported here: https://bugs.kde.org/show_bug.cgi?id=483488
