### ISSUE TITLE
 please explicitly install translation files to directory instead of bundled into the executable binary

### ISSUE THREAD

**Issue by Brli** [strawberrymusicplayer/strawberry#1408]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

Translation files would be in /usr/share/locale/<locales>/LC_MESSAGES/strawberry.qm (or whatever file type suffix it should be) under Linux.

Would be somewhere like C:\Program Files\Strawberry\locale\<locale>.qm under Windows

for better explicit test for translators without re-compile the full application.

please update cmake/Translations.cmake to have compile and install options for OSs and optionally compile the bundled version as portable app.

**To Reproduce**
check the released tarballs and installers, and find nowhere the compiled localization files.

**Expected behavior**
compiled translation files should be explicitly shown under released tarballs

**Screenshots:**

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.23-2

**Additional context**

**Comment by jonaski** [comment]
There an CMake option for this `INSTALL_TRANSLATIONS`, on Windows we do not use make install.
I won't make it the default, and I've already answered this at least one time before.
