### ISSUE TITLE
Integrate new platform for translators

### ISSUE THREAD

**Issue by Brli** [strawberrymusicplayer/strawberry#1409]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Welcome to Zanata

Zanata is a web-based translation platform for Translators to translate documentation and software online using a web browser.

**Maintenance-only Zanata Instance**

This service is in maintenance mode and new users and projects are not accepted, sorry.

Since the upstream Zanata project has been unmaintained for quite some 
time, we have decided to continue supporting existing projects as much 
as possible but refuse new projects. Adding new language coordinators is 
also not possible, although if you've been around for some time we might 
add you as reviewer to ease the situation.

Signing Up

We do not accept new users; please read the announcement above.

**To Reproduce**
[Steps to reproduce the behavior.](https://translate.zanata.org/)

**Expected behavior**
Able to translate things

**Screenshots:**

**System Information:**
 - Operating system:
 - Strawberry Version:

**Additional context**
Transifex has nicely integration method for auto pulling and updating.

Also, you may want to sync with Clementine's translation as they didn't separately license that.

**Comment by jonaski** [comment]
Looking at Transiflex, it looks to be a paid service, and I've already submitted a request for Weblate and https://care.weblate.org/#ticket/zoom/8129

**Comment by Brli** [comment]
IIRC it's free for foss devs

**Comment by Cwpute** [comment]
I've used Weblate and Crowdin in the past, both very good solutions for FOSS projects (although Weblate is FOSS itself, so that's a plus). I've heard not so good things about Transifex... cannot correlate as i've never been able to join a Transifex translation project (most of them are made private so only registered and approved member can participate).

**Comment by jonaski** [comment]
I've given up on Weblate and signed up forCrowdin instead where the project was accepted as open source within seconds after I registered. But I don't see how to easily set it up using a pot file.
https://community.crowdin.com/t/using-a-pot-file-as-source/8428

**Comment by jonaski** [comment]
Crowdin is now integrated: https://crowdin.com/project/strawberrymusicplayer/
