### ISSUE TITLE
Strawberry crashes when I try to start playback on Gnome 46

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1410]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I was using Strawberry without any problem immediately before upgrading to Gnome 46 on Arch Linux. However, after the upgrade, Strawberry is unable to play anything, and it crashes.

**To Reproduce**
1. upgrade to Gnome 46 and reboot
2. try to play an audio file with Strawberry

**Expected behavior**
Strawberry plays the audio file

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.23

**Additional context**
I'm unable to reproduce this crash on another computer running Arch Linux + KDE Plasma DE + the same version of Strawberry.

crash log generated with gdb:
[gdb.txt](https://github.com/strawberrymusicplayer/strawberry/files/14734197/gdb.txt)

**Comment by glaubersm** [comment]
The crash does not always occur. Sometimes Strawberry just shows the following error message:

![Captura de tela de 2024-03-24 00-07-44](https://github.com/strawberrymusicplayer/strawberry/assets/15967631/d152124b-b517-4c86-9207-6d2bcb7e2d00)

**Comment by jonaski** [comment]
This crash looks glib/pcre related, I suggest to report this to Arch.
Does this also crash?
`gst-discoverer-1.0 https://stream.radioparadise.com/flacm`

**Comment by glaubersm** [comment]
Here is the output of your command:

```
$ gst-discoverer-1.0 https://stream.radioparadise.com/flacm
Analyzing https://stream.radioparadise.com/flacm
Done discovering https://stream.radioparadise.com/flacm
An error was encountered while discovering the file
 Could not determine type of stream.

```

**Comment by glaubersm** [comment]
I have noticed that all Gstreamer apps are broken on my system.

https://bbs.archlinux.org/viewtopic.php?id=294166

Thanks for your help Jonas, have a nice day. :)

**Comment by glaubersm** [comment]
Strawberry and other Gstreamer apps sttopped working with main user account, but they worked with another user. Then I deleted ~/.cache/gstreamer-1.0 folder and the problem with main user was solved.
