### ISSUE TITLE
Strawberry does not conform to the MPRIS2 standard

### ISSUE THREAD

**Issue by hamelg** [strawberrymusicplayer/strawberry#1411]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

While playing songs, I see these errors in the system logs.

`kde.dataengine.mpris: mpris:trackid from "Strawberry" does not conform to the MPRIS2 standard. Please report the issue to the developer.`

**To Reproduce**
Playing songs

**Expected behavior**
Strawberry doesn't trigger these errors in the system logs

**System Information:**
 - Operating system: Archlinux
 - Strawberry Version: 1.0.23
 - KDE Frameworks : 6.0.0
 - QT : 6.6.2
 - Wayland windowing system

**Comment by jonaski** [comment]
This should already be fixed by #1397
