### ISSUE TITLE
Strawberry keeps on re-arranging my playlist.

### ISSUE THREAD

**Issue by HeathenHacks** [strawberrymusicplayer/strawberry#1415]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Upon loading my playlist, it would be using the right arrangements of tracks, however, after closing it and then re-launching it, the playlist arrangement would default to "Alphabetical" order or sorted via title and not my own mix and mash arrangement of tracks. I would then need to load the playlist again just for the tracks to be arranged correctly. But, it would reset again after closing Strawberry.

**To Reproduce**
Not sure if this is just an isolated issue or not, but, I guess you can try making a playlist, arrange the tracks according to your preference and not use any sorting methods, save the playlist, then close and re-launch Strawberry.

**Expected behavior**
It would load the tracks correctly.

**Screenshots:**
This screenshot shows how the tracks are arranged upon loading the playlist: 
![2024-04-06 22-31-23_0001](https://github.com/strawberrymusicplayer/strawberry/assets/43103175/9f2ab5e7-badb-4b85-932f-663f8ea3ec02)

This screenshot shows how the tracks are arranged after closing Strawberry and then re-launching it: 
![2024-04-06 22-31-23_0002](https://github.com/strawberrymusicplayer/strawberry/assets/43103175/6525f864-0ad2-4d54-b1e7-44649b973601)

**System Information:**
 - Operating system: ArcoLinux (Arch-derivative) with KDE Plasma 6.0.3
 - Strawberry Version: 1.0.23
 - Qt Version: 6.6.3
 - 
**Additional context**

**Comment by jonaski** [comment]
Have you checked the "Automatically sort playlist when inserting songs" in the Playlist setting? In that case this is expected behaviour.

**Comment by HeathenHacks** [comment]
> Have you enabled the "Automatically sort playlist when inserting songs" in the Playlist setting? In that case this is expected behaviour.

Upon checking, I do have it enabled. 

Must've done it when I was experimenting and forgot about it.

Does it work like that even when not adding new songs to the playlist?

In any case, that did solve it. 

Thanks for your time, I apologize.

**Comment by HeathenHacks** [comment]
This issue is SOLVED.
