### ISSUE TITLE
Does not monitor folder

### ISSUE THREAD

**Issue by renn0xtek9** [strawberrymusicplayer/strawberry#1416]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Song added into $HOME/Music do not appear in "added today" nor anywhere in the collection

**To Reproduce**
Add a song (mp3) to anywhere in the folder and it should auto appear in the collection

**Expected behavior**

**Screenshots:**

**System Information:**
 - Operating system:
 - Strawberry Version:

**Additional context**

**Comment by jonaski** [comment]
What OS, is it a local disk? What filesystem on the disk?

**Comment by jonaski** [comment]
Closing this since there is no reply here. If this is on Linux I suggest to check if you have enough inotify watches, or increase it. https://wiki.strawberrymusicplayer.org/wiki/Increase_inotify_watches
