### ISSUE TITLE
how can I help?

### ISSUE THREAD

**Issue by peddy22** [strawberrymusicplayer/strawberry#1426]
I have a degree in Electronics Engineering but would love to help with some programming projects, please guide me and I will do my best to help (y) got experience in C++

**Comment by jonaski** [comment]
You can pick up any issues you want. What do you need guidance for?
Please stop using GitHub for discussion, I plan to move away from GitHub issues, then all history will be gone. The official channel for discussions is the forum at: https://forum.strawberrymusicplayer.org/
