### ISSUE TITLE
Strawberry cannot correctly display russian names from flac after drag'n'dropping .cue file to queue

### ISSUE THREAD

**Issue by soredake** [strawberrymusicplayer/strawberry#1429]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry cannot correctly display russian names from flac after drag'n'dropping .cue file to queue

**To Reproduce**
Drag'n'drop .cue with russian names to strawberry.

**Expected behavior**
This:
![image](https://github.com/strawberrymusicplayer/strawberry/assets/5204968/d92cf697-4927-4885-bd29-eec6a5fcd39a)

**Screenshots:**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/5204968/0c5a184b-9258-43cd-8fe8-3ba6539925ac)

**System Information:**
 - Operating system: Windows 11 Pro
 - Strawberry Version: 1.0.23

**Additional context**

**Comment by jonaski** [comment]
What encoding is the cue file in? I suspect it only supports UTF-8.

**Comment by soredake** [comment]
Visual Studio Code displayed this encoding:
![image](https://github.com/strawberrymusicplayer/strawberry/assets/5204968/3fb98b45-63b1-4d09-822d-774745e7c42f)

**Comment by jonaski** [comment]
Can you paste the .cue file here and I will check if we can implement handling of more encodings, or at least show an error if it's not UTF-8.

**Comment by soredake** [comment]
[М.КРУГ - ЖИГАН - ЛИМОН.zip](https://github.com/strawberrymusicplayer/strawberry/files/15133110/-.-.zip)

**Comment by jonaski** [comment]
Qt only detects UTF encodings, so we need to write our own code, or use a another library (ICU or libmagic?) for that.
`QTextStream::setCodec` is gone in Qt 6, we need to use `QTextStream::setEncoding`, but it doesn't have support for all the encodings (https://bugreports.qt.io/browse/QTBUG-109254), looks like there is some work done for that here: https://codereview.qt-project.org/c/qt/qtbase/+/429820

**Comment by jonaski** [comment]
And I wonder how KDE does this? kate detects the encoding.
