### ISSUE TITLE
Playlists are broken and empty after latest commits

### ISSUE THREAD

**Issue by nokia8801** [strawberrymusicplayer/strawberry#1430]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Playlists are broken and empty after the latest commits. The tracks are still there but they have no information about them and can't be played.

**To Reproduce**
Clone the repo and compile from master.

**Expected behavior**
Should be visible and working like before. It was working with version 1.0.23.r116.gc30a39d2-1 which would be commit  c30a39d29a65d027e04d0b2858481077d68fe7c5.

**Screenshots:**
![image](https://github.com/strawberrymusicplayer/strawberry/assets/136886711/1fc88713-87cf-4566-8eaf-8bfb66ac5d5b)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.23.r145.g426de615-1 | commit 426de615256ab6c3e9500873370e6c8c07949bfa
 - Qt 6.7.0 with qt6-wayland
 - GNOME 46.1 on Wayland

**Additional context**
Not every playlist is broken like this for some reason, but more than half are empty. Either it is random or there is something I'm not understanding. But downloading normal 1.0.23 from official Arch repositories fixes the issue so it must be one the recent commits, probably between ac0926d40b94d752a6b3bd29ac6f417c5de0ecb8 and 5f9a83871de341fc3f1c5d0eff627dfdfad653fb (including them) cause it first broke with commit 5f9a83871de341fc3f1c5d0eff627dfdfad653fb and is still broken even with the latest commits.

**Comment by jonaski** [comment]
The position was wrong when loading streams and songs outside of the collection. Should be fixed now, but your playlists will probably already be wiped so you need to recreate them.

**Comment by jonaski** [comment]
I forgot that radio streams has it's own playlist item type, fixed now.

**Comment by cmorgenstern** [comment]
Sorry to necro-bump, but I don't think this has been resolved. Using the latest version of Strawberry compiled from master, playlists with local files do not correctly display, and I cannot save and load playlists either (M3U).

**Describe the bug**
Local tracks in playlists are not correctly linked to library items.
Loading a newly saved M3U playlist also produces the same result.

**To Reproduce**
1) Open Strawberry
2) Open an M3U playlist containing local track

Expected:
Playlist loads with the entries linked to tracks in the library

Actual:
Playlist entries are not linked and cannot be played.

1) Open Strawberry
2) Create a new playlist and and add some tracks
3) Save the playlist (.m3u) and close it
4) Load the saved playlist

Expected:
Playlist loads with the entries linked to tracks in the library

Actual:
Playlist entries are not linked and cannot be played.


**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.23.r174.g9f2e4ac3-1
