### ISSUE TITLE
Fedora 40 missing in repo and status on Rawhide builds

### ISSUE THREAD

**Issue by mmkthecoolest** [strawberrymusicplayer/strawberry#1431]
NOTE: I found a similar issue (#582) that was previously marked as resolved, so I am posting it here. Let me know if this isn't the correct place to post about this.

Fedora 40 is [now on stable](https://fedoramagazine.org/announcing-fedora-linux-40/) since the 23rd but I do not see builds for it in the [repo](https://download.opensuse.org/repositories/home:/jonaski:/audio/). I also noticed that Rawhide builds have not been updated since 20th December 2023. I would like for Fedora 40 builds to be available so I can upgrade my system (currently at Fedora 39).

Apologies for not following the bug template but I felt this technically isn't a bug with the program.

**Comment by jonaski** [comment]
I checked a while back and Fedora 40 was not available, openSUSE is very late to add new Fedora versions. But I see it's available now so it's fixed now.

**Comment by mmkthecoolest** [comment]
Not sure if I should report a new issue on this one, but now Fedora builds are being out of date again as they haven't been updated since July 25th. Fedora 41 has been branched (not released yet) and the versions for Fedora are stuck at 1.1.1

**Comment by jonaski** [comment]
Fixed now, but Fedora 41 is not available in openSUSE buildservice yet.
