### ISSUE TITLE
Collection view: Grouping by Genre/Artist/Album - Artist ignored for various

### ISSUE THREAD

**Issue by AllKind** [strawberrymusicplayer/strawberry#1433]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
If I group a sampler (Various artists) by Genre/Artist/Album in the Collection view the Artist is replaced by "Various artists", although the artist is known (tagged) and the "Album artist" field is empty (but that can also be set to "Various artists" - the outcome is the same).
The artist name is then put in front of the songs name.
Changing the grouping to Genre/Album artist/Album yields the exact same output. I only checked to see...
I don't actually know where Strawberry takes the "Various artists" from, as it's not in the fields tag.
See picture nr. 1.

I have another case similar (picture nr. 2):
This time the "Album artist" tag is set to "Various artists". Grouping behavior is the same as above, if the songs of the sampler are together in a folder. But if I export-copy a single song to another library folder, the grouping is as I would expect it with Genre/Artist/Album.

**To Reproduce**
As above

**Expected behavior**
Use the actual artist not "Various artists" when grouping by Genre/Artist/Album.

**Screenshots:**
![strawberry_grouping](https://github.com/strawberrymusicplayer/strawberry/assets/3242311/bd26947a-de2e-403a-b154-b83e94b060e4)
![strawberry_grouping2](https://github.com/strawberrymusicplayer/strawberry/assets/3242311/92b04d3b-8b15-4f94-ae89-91141ff42244)

**System Information:**
 - Operating system: Linux Mint 21.3
 - Strawberry Version: 1.0.23

**Comment by AllKind** [comment]
I just discovered that there is an option on right-click on the song "Don't show in various", which will remove the grouping by "various".
Seems like I need to do this for every song individually?
The odd thing is, after selecting above option, the collection view totally clears and I have to type the search filter again.
Both things are not really "comfortable".

**Comment by jonaski** [comment]
You should be able to disable "Various artists" for whole artists and albums by right-clicking, clearing the search will be fixed by #729, I've also added an option to disable "Various artists" altogether.
