### ISSUE TITLE
Error when playing multi-channel wavpack file: Expected framed input

### ISSUE THREAD

**Issue by auxym** [strawberrymusicplayer/strawberry#1437]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I am trying to play back a multi-channel wavpack file (specifically, a rip from a bootleg DVD-A release of a quadrophonic mix of Pink Floyd's Dark Side of The Moon. After playing for a few seconds, or attempting to seek forward, I get the following error and playback stops:

```
../ext/wavpack/gstwavpackdec.c(450): gst_wavpack_dec_handle_frame (): /GstPlayBin3:pipeline-3-pipeline/GstURIDecodeBin3:uridecodebin3/GstDecodebin3:decodebin3-2/GstWavpackDec:wavpackdec5: Expected framed input
```

**To Reproduce**
As described above.

I am currently not sure if the problem happens with other wv files, I unfortunately don't have any others. If you cannot reproduce, I can try to provide a short sample or another file that creates the problem.

I can say that I used `wvunpack -v` to verify the file, and it appears good. VLC plays it back without error. I also re-encoded it with a recent wavpack version, and the re-encoded file still gives the same error.

**Expected behavior**
Playback without errors :)

**Screenshots:**

**System Information:**
 - Operating system: OpenSUSE Tumbleweed
 - Strawberry Version: 1.0.23

**Additional context**

**Comment by jonaski** [comment]
Can you check if you get the same error with:

`gst-play-1.0 --use-playbin3 --audiosink="alsasink" file:///path/filename`

**Comment by jonaski** [comment]
If you get the error with gst-play too, please run gst-play with GST_DEBUG and GST_DEBUG_FILE, compress the logfile and attach the it here.
`GST_DEBUG=5 GST_DEBUG_FILE=/tmp/gst-debug.log gst-play-1.0 --use-playbin3 --audiosink="alsasink" file:///path/filename`

**Comment by jonaski** [comment]
This might be related to #1444. A regressions was found and fixed in GStreamer. (https://gstreamer.freedesktop.org/releases/1.24/#1.24.4). Please test 1.24.4 once available.

**Comment by jonaski** [comment]
Reply back if there is still an issue after GStreamer 1.24.4 and I'll reopen this.
