### ISSUE TITLE
Failed to play WavPack file: Could not determine type of stream

### ISSUE THREAD

**Issue by antonsoroko** [strawberrymusicplayer/strawberry#1444]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Failed to play WavPack file, but mpv and vlc can play it.

Error in Strawberry:
```
Could not determine type of stream.
../plugins/elements/gsttypefindelement.c(1186): gst_type_find_element_loop (): /GstPlayBin3:pipeline-31-pipeline/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin63/GstTypeFindElement:typefindelement63
```

gst-play-1.0 error:
```
$ LANG=C gst-play-1.0 --use-playbin3 --audiosink="alsasink" xxx.wv
ERROR Could not determine type of stream. for file:///.../xxx.wv
ERROR debug information: ../plugins/elements/gsttypefindelement.c(1186): gst_type_find_element_loop (): /GstPlayBin3:playbin/GstURIDecodeBin3:uridecodebin3/GstURISourceBin:urisourcebin0/GstTypeFindElement:typefindelement0
```

```
$ mediainfo xxx.wv'
General
Complete name                            : xxx.wv
Format                                   : WavPack
File size                                : 531 MiB
Duration                                 : 1 h 17 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 953 kb/s

Audio
Format                                   : WavPack
Format profile                           : 4.07
Format settings                          : Lossless
Duration                                 : 1 h 17 min
Bit rate mode                            : Variable
Bit rate                                 : 953 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression ratio                        : 1.480
Stream size                              : 531 MiB (100%)
Encoding settings                        : -h
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots:**

**System Information:**
 - Operating system: KUbuntu 24.04
 - Strawberry Version: 1.0.23

**Additional context**

**Comment by jonaski** [comment]
Do you have the wavpack plugin installed?
`gst-inspect-1.0 wavpack`

**Comment by antonsoroko** [comment]
@jonaski looks like i do:
```
$ LANG=C gst-inspect-1.0 wavpack
Plugin Details:
  Name                     wavpack
  Description              Wavpack lossless/lossy audio format handling
  Filename                 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstwavpack.so
  Version                  1.24.2
  License                  LGPL
  Source module            gst-plugins-good
  Documentation            https://gstreamer.freedesktop.org/documentation/wavpack/
  Source release date      2024-04-09
  Binary package           GStreamer Good Plugins (Ubuntu)
  Origin URL               https://launchpad.net/ubuntu/+source/gst-plugins-good1.0

  wavpackdec: Wavpack audio decoder
  wavpackenc: Wavpack audio encoder

  2 features:
  +-- 2 elements
```

**Comment by jonaski** [comment]
Please run gst-play-1.0 with GST_DEBUG and GST_DEBUG_FILE, compress the logfile and attach the it here.
`GST_DEBUG=5 GST_DEBUG_FILE=/tmp/gst-debug.log gst-play-1.0 --use-playbin3 --audiosink="alsasink" xxx.wv`

**Comment by antonsoroko** [comment]
@jonaski 
i found 2 more file with the same issue. thus 3 logs:

[gst-debug.log.gz](https://github.com/strawberrymusicplayer/strawberry/files/15433922/gst-debug.log.gz)
[gst-debug.log.gz](https://github.com/strawberrymusicplayer/strawberry/files/15433958/gst-debug.log.gz)
[gst-debug.log.gz](https://github.com/strawberrymusicplayer/strawberry/files/15433960/gst-debug.log.gz)

thanks.

**Comment by jonaski** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3569

**Comment by jonaski** [comment]
This issue is fixed in GStreamer so closing.
