### ISSUE TITLE
Some minor bugs with VLC engine

### ISSUE THREAD

**Issue by derVedro** [strawberrymusicplayer/strawberry#1446]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
As a temporary solution to #1443 I use VLC engine as backend. Two issues comes with that backend: the stop button is disabled and track position bar is disabled, so you can not seek into a specific part of the track.

**UPDATE:**
By the way, there is no scrobling with VLC engine. 

**System Information:**
 - Operating system: Ubuntu 24.04
 - Strawberry Version: 1.0.23

**Screenshot**
Strawberry is playing a track but: 
![strawberry is playing a track](https://github.com/strawberrymusicplayer/strawberry/assets/4129535/fcffc305-c529-4578-bd19-d43522678163)

**Comment by jonaski** [comment]
I can't reproduce any issues, tested both with alsa and pulseaudio as output. Progress bar works and stop is possible.

**Comment by jonaski** [comment]
I suggest to run strawberry in a terminal to see any debug output from VLC.

**Comment by derVedro** [comment]
> I suggest to run strawberry in a terminal to see any debug output from VLC.

There is nothing special in console log. At least I don't see anything there from VLC:
https://pastebin.com/j4pRnR9u

And a grep for VLC in the strace, if you are interested:
https://pastebin.com/uN7LxXyQ

**Comment by jonaski** [comment]
The issue is:

```
04:47:20.674 WARN  unknown                          QObject::connect: Cannot queue arguments of type 'State' 
04:47:20.674 WARN  unknown                          (Make sure 'State' is registered using qRegisterMetaType().) 
04:47:20.674 WARN  unknown                          QObject::connect: Cannot queue arguments of type 'State' 
04:47:20.674 WARN  unknown                          (Make sure 'State' is registered using qRegisterMetaType().) 
```

This is an issue with Qt 5, not Qt 6.
