### ISSUE TITLE
Player controls and seek bar are not updated, possible signal connection problem

### ISSUE THREAD

**Issue by martenjj** [strawberrymusicplayer/strawberry#1450]
- [ Y] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ Y] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ Y] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
This refers to a problem with Strawberry version 1.0.23 on Gentoo using Qt 5 (a Qt 6 build is not yet available).  It was originally reported as #1283 and said to be fixed, but it still appears to be present in this build.  Media will play, but the player controls and seek bar are not enabled or updated, and messages are seen in the debug log:

WARN  unknown  QObject::connect: Cannot queue arguments of type 'State' 
WARN  unknown  (Make sure 'State' is registered using qRegisterMetaType().)

**To Reproduce**
Start to play a media file, for example by dragging a track to the playlist and then double-clicking it.  Observe that the "play" button does not change to "pause" and the seek bar does not move.  Click on "play" or "stop" and observe that nothing happens.

**Expected behavior**
The player controls and seek bar should reflect the current state.

**System Information:**
 - Operating system: Linux hostname 6.1.53-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC x86_64 AMD Phenom(tm) II X3 705e Processor AuthenticAMD GNU/Linux
 - Strawberry Version: 1.0.23
 - Backend: VLC
 - Qt version: 5.15.13

**Additional context**
The patch here appears to fix the problem.  The warning messages are not seen, the player controls change state as expected and can be used.  GitHub doesn't seem to want to attach the patch file here, but it can be found at https://bugs.gentoo.org/attachment.cgi?id=893156 or attached to Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=915020

**Comment by jonaski** [comment]
Didn't I just fix this? d7cc52b

**Comment by jonaski** [comment]
The patch from the Gentoo issue is the same thing I just fixed.
