### ISSUE TITLE
No attempts to continue playback after "Server does not support seeking." error

### ISSUE THREAD

**Issue by derVedro** [strawberrymusicplayer/strawberry#1455]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
 
The playback ends if a "Server does not support seeking." error occurs. 

**To Reproduce**
Start playing a stream.
Pause it for a half minute.
Resume the playback.
Get an error popup.
Playback ends.

**Expected behavior**
It is clear to me that such a error is inevitable. But the handling of it is a bit disappointing. I would like if strawberry simply empties the buffers and reloads the stream, so strawberry should just play stream at the new position when `Server does not support seeking` error occurs.

**System Information:**
 - Operating system: Ubuntu 24.04
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment]
This is gstreamer issue: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/303

**Comment by derVedro** [comment]
> This is gstreamer issue: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/303

okay, that's a duplicate of #846 and #1058

**Comment by Nyanraltotlapun** [comment]
> This is gstreamer issue: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/303

But maybe Strawberry can properly  handle this error? Like just reconnect?
We cannot expect gstreamer mess will fix itself on some point in the future.

I constantly having this bug popup and radio stop playing.

**Comment by derVedro** [comment]
> > This is gstreamer issue: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/303
> 
> But maybe Strawberry can properly handle this error? Like just reconnect? We cannot expect gstreamer mess will fix itself on some point in the future.
> 
> I constantly having this bug popup and radio stop playing.

That would be great, I agree.
