### ISSUE TITLE
Command "strawberry -p" works only if...

### ISSUE THREAD

**Issue by nicoadamo** [strawberrymusicplayer/strawberry#1465]
- [ ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ +] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When there's no active instance of Strawberry Player and another application calls "strawberry -p", the applications starts from zero, but the play action is not called.  I've detected this because I use KAlarm with that command to start the music, and if after rebooting I didn't open Strawberry before the alarm is called, the the whole purpose of the alarm is not accomplished. 

**To Reproduce**
Close any active instance of Strawberry Player. Then from a terminal (or create a command alarm from KAlarm) call $ strawberry -p

**Expected behavior**
1) If not loaded already, the app Strawberry Player should load and the playing should be started. 
2) If loaded already, the playing action should start.
Note #2 already works. #1 is the issue I'm reporting.  

**Screenshots:**

**System Information:**
 - Operating system: Archlinux with kernel 6.6.33-1-lts, KAlarm 3.8.1.2 (KDE Gear 24.05.1)
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment]
The problem is that it tries to play before the playlist is loaded, so we need to delay the play until the playlists are loaded.

**Comment by nicoadamo** [comment]
I've just checked Strawberry v1.1.0 and the bug (/wish?) is still present.

**Comment by nicoadamo** [comment]
Thank you! I'm not sure when it will be available in Arch to test, but I appreciate the effort improving this great Strawberry music player!
