### ISSUE TITLE
Single clicking items in the collection list and settings menu does not select them under KDE Plasma 6.1.1 on Wayland

### ISSUE THREAD

**Issue by cjohn-afk** [strawberrymusicplayer/strawberry#1473]
### Describe the bug
When selecting a track or expanding an artist/album from the collection list you must double click to select the item. Once a list item has been selected, you can single click the title to expand/close it.

This same problem applies to the list of sub-menus in the settings window (double clicking to select).

### To Reproduce
Attempt to select items in collection list or settings window when running on KDE Plasma 6.1.1 with Wayland.

### Expected behavior
Items should be selected via a single click.

### System Information:
 - Operating system: OpenSUSE Tumbleweed
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment]
I can't reproduce this issue on Tumbleed with KDE and Wayland.
This does not sound like a Strawberry bug, but more of a Qt style or configuration issue.
Do you have the same behaviour if you set the style to Fusion in the Appearance settings?

**Comment by cjohn-afk** [comment]
Switching themes solved the issue for me, thanks for that suggestion. This issue seems to be a problem Kvantum (a QT/KDE theme engine). My apologies for not checking this first, I didn't realize the theme was integrated on a deeper level than visual.
