### ISSUE TITLE
rating does not update

### ISSUE THREAD

**Issue by 3052** [strawberrymusicplayer/strawberry#1475]
1. right click track
2. edit track information
3. tags
4. change rating
5. save
6. rating column still blank

- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**System Information:**
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment]
What audio file format is this?

**Comment by 3052** [comment]
FLAC

**Comment by jonaski** [comment]
The playlist rating column is only supported for collection songs not local songs added from outside the collection.
Make sure the source column shows an vinyl icon, not a folder icon, also the rating column should show blank stars like this if it's a song that supports showing rating for:
![image](https://github.com/strawberrymusicplayer/strawberry/assets/10343810/ed7e1d9c-ec98-41cd-ad98-00ba98f010ff)
