### ISSUE TITLE
Ampersands visible in left bar labels when built against Qt6

### ISSUE THREAD

**Issue by WOnder93** [strawberrymusicplayer/strawberry#1476]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When built against Qt6, some of the entries in the left menu bar are displayed with ampersands (&). When the same code is built with Qt5, there are no ampersands visible.

**To Reproduce**
Build Strawberry with Qt6 on Fedora and start it.

**Expected behavior**
No ampersands are shown in the left menu bar labels.

**Screenshots:**
![Screenshot_20240703_125301](https://github.com/strawberrymusicplayer/strawberry/assets/3041388/b7a41494-a385-4adb-a2d3-0c8abcc62a64)

**System Information:**
 - Operating system: Fedora Linux 40
 - Strawberry Version: 1.0.23

**Comment by jonaski** [comment]
This bug has been reported like 5 times already after KDE 6 was released.
Strawberry isn't adding this so Is supect it's a KDE bug, it has been reported here: https://bugs.kde.org/show_bug.cgi?id=483488
You can workaround it with:
`kwriteconfig6 --file kdeglobals --group Development --key AutoCheckAccelerators "false"`

**Comment by WOnder93** [comment]
Ack, thanks for the upstream bug report link and sorry for the duplicate report.
