### ISSUE TITLE
Cannot open Audio CD to rip

### ISSUE THREAD

**Issue by linuxosd** [strawberrymusicplayer/strawberry#1477]
I try to open an audio CD so I can rip the tracks but I get this error:
0: No URI handler for the cdda protocol found

 - Operating system: Ubuntu 24.04
 - Strawberry Version: 1.0.23 installed through Ubuntu repositories

**Comment by jonaski** [comment]
You are missing dependencies, most likely libgstcdio part of gst-plugins-ugly. You will be better off getting help through Ubuntu support.
