### ISSUE TITLE
Random freezes, when opening context menu with right click

### ISSUE THREAD

**Issue by qarmin** [strawberrymusicplayer/strawberry#1478]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When clicking at some music files with right mouse button, then I see strange ~1s freezes

**To Reproduce**
Change music files, randomly click at the with RMB

**Video**
Freezes(~0.5 - 1.5s) are visible on fading cover and mood bar at the bottom 

https://github.com/strawberrymusicplayer/strawberry/assets/41945903/6aaa5c5f-5f55-4e07-8a6a-f7a679eb27b3

**System Information:**
 - Operating system: Ubuntu 24.04
 - Strawberry Version: Version 1.0.23-157 geff6b75c

**Comment by jonaski** [comment]
What audio format and what GStreamer version are you using?

**Comment by qarmin** [comment]
Ubuntu 24.04
Gstreamer 1.24.2-1ubuntu1

I have only MP3 with bitrate 128kb/s - 320kb/s
```
  Duration: 00:03:36.48, start: 0.025056, bitrate: 133 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc57.24
```

this is probably related to big number of music files on list.
With smaller number, of items(128) I cannot reproduce problem.

It seems that sometimes when right-clicking, only the gui thread would freeze and the music would still play - maybe when right-clicking, some operations are performed on the whole list i.e. counting all the items on list?

**Comment by AllKind** [comment]
I noticed that happening with my very big playlist 15.000+ songs, when I add a couple of songs (somewhere in the middle of the playlist, to check duplicates - don't know if that's a relevant thing) and then right-click a track just below the ones I just added.
