### ISSUE TITLE
Fasttracker II files (.xm files, chiptune musics) can't be played on latest release

### ISSUE THREAD

**Issue by XutaxKamay** [strawberrymusicplayer/strawberry#1479]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Fasttracker II files (.xm files, chiptune musics) can't be played if playbin3 is taken since release 1.0.23.

This commit solves the issue though https://github.com/strawberrymusicplayer/strawberry/commit/8a27c6a52ffce63c5c7ae058ea3966bdf6543bc6#diff-7ffc8ab9614f3dc88e94916de48ffdd37e1ff0b1a1dfffd94a618896e6c4840c
but I'm afraid there is probably some regressions on gstreamer even on 1.24, I haven't tested.

**To Reproduce**
Build 1.0.23 release, play xm chiptune => gstreamer (1.22) says that it is not supported.

**Expected behavior**
The chiptune should play as it did before.

**Screenshots:**
N/A

**System Information:**
 - Operating system: Gentoo
 - Strawberry Version: 1.0.23

**Additional context**
This will be solved on next release, but I thought it may have been important to track the issue here.
For now I'm using a patch to fix the issue.

**Comment by jonaski** [comment]
Strawberry does have many issues with 1.22. Test with GStreamer 1.24, if you still can reproduce it we need a gstreamer debug log so it can be reported to GStreamer.

**Comment by XutaxKamay** [comment]
> Strawberry does have many issues with 1.22. Test with GStreamer 1.24, if you still can reproduce it we need a gstreamer debug log so it can be reported to GStreamer.

I just tested with gstreamer 1.24.5 (including plugins), I get the same issue.

Here is a log with GST_DEBUG=5

[Uploading log.txt…]()

**Comment by jonaski** [comment]
I don't think modplug works very well anymore, the library hasn't been update for years, I didn't even know distros were building gstreamer with modplug anymore. You should probably use openmpt (libgstopenmpt.so) instead (part of gst-plugins-bad). It plays XM fine here using opempt.
Check if you got it with: `gst-inspect-1.0 openmpt`

**Comment by XutaxKamay** [comment]
> I don't think modplug works very well anymore, the library hasn't been updated for years, I didn't even know distros were building gstreamer with modplug anymore. You should probably use openmpt (libgstopenmpt.so) instead (part of gst-plugins-bad). It plays XM fine here using opempt. Check if you got it with: `gst-inspect-1.0 openmpt`

Seems like my distro doesn't even have openmptdec plugin in its repo, no worries though I'll create an ebuild for it and check if it works
Thank you

**Comment by jonaski** [comment]
Reported this here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3722
