### ISSUE TITLE
Incorrect encoding used when importing files into collection with Czech characters

### ISSUE THREAD

**Issue by goliashcz** [strawberrymusicplayer/strawberry#1481]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
In my collection I am using UTF-8 for MP3 ID3 tag v2. When Strawberry imports into the collection such files with Czech characters, it doesn't use UTF-8 encoding anymore. I guess there is some auto-detection in place and it stopped working with 1.1.0 release. (it might use windows-1250?)

**To Reproduce**
Add to collection some MP3 file with ID3 tag v2 containing "ěščřžýáíé" characters (using UTF-8).

**Expected behavior**
Text is displayed in collection correctly. Not with question marks.

**Screenshots:**
![obrazek](https://github.com/strawberrymusicplayer/strawberry/assets/6495372/bf3108cb-eeaa-4e55-9822-15e3cea4ea18)

**System Information:**
 - Operating system: KDE Neon 6.0
 - Strawberry Version: 1.1.0 rc2

**Additional context**

**Comment by GistOfSpirit** [comment]
Same thing happens with Greek titles. It was OK in the previous version.

I have several such songs in my playlist, and they display OK until Strawberry actually plays them. Then their titles are changed to this, and even manually correcting them doesn't fix it.

![image](https://github.com/strawberrymusicplayer/strawberry/assets/104150585/4409b5a8-90dc-45b9-a3bb-8abd662cb7a6)

**Comment by jonaski** [comment]
Sorry about that, TagLib uses Latin by default and I forgot to specify UTF-8 in one place.
