### ISSUE TITLE
Ubuntu PPA missing `1.1.0`

### ISSUE THREAD

**Issue by joshstoik1** [strawberrymusicplayer/strawberry#1493]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

Hi there,

The [Ubuntu PPA](https://launchpad.net/~jonaski/+archive/ubuntu/strawberry) is still serving `1.1.0-rc4` instead of the latest `1.1.0` release from a few days ago.

I suspect the problem is version-related: `1.1.0-noble` is treated as lower than `1.1.0-rc4-noble`.

**Comment by jonaski** [comment]
Fixed now
