### ISSUE TITLE
searching for values of different tags (e.g. artist and song name) no longer works

### ISSUE THREAD

**Issue by mikelpr** [strawberrymusicplayer/strawberry#1495]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Using the library search box, typing an artist and then the song name shows no results. typing only the song name shows songs from all artists that are called like so, and searching for the artist shows the artist and all their releases, and searching for the album shows albums called like that. but you can no longer combine them

**To Reproduce**
1. search for artist - song. e.g.: machine girl ghost

**Expected behavior**
shows what I'm looking for

**Screenshots:**
on 1.1.0:
![Screenshot_20240718_150123](https://github.com/user-attachments/assets/f657460a-550b-4722-bf10-4852aa9285b1)
![Screenshot_20240718_150136](https://github.com/user-attachments/assets/59a5f579-94ef-41b6-b74f-ca5e886622cc)

whereas on 1.0.23:
![Screenshot_20240718_150647](https://github.com/user-attachments/assets/a12f3cea-f701-481f-9465-f51f0fd58a50)

**System Information:**
 - Operating system: Fedora 40
 - Strawberry Version: 1.1.0

**Additional context**
definitely doesn't happen on 1.0.23, I was thinking maybe I was having a mandela effect but just tried it

**Comment by jonaski** [comment]
This is already fixed.
