### ISSUE TITLE
Searching for a song title using multiple words doesn't work

### ISSUE THREAD

**Issue by wjandrea** [strawberrymusicplayer/strawberry#1497]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature request that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I want to listen to "Peach, Plum, Pear" by Joanna Newsom so I put `peach plum` into the search, but nothing comes up.

**System Information:**
 - Operating system: Ubuntu 20.04.6
 - Strawberry Version: 1.1.0

**Additional context**
I reverted to 1.0.23 to confirm that it worked previously. (I had to delete and rebuild the database to get it to work.)

I think the issue is caused by the comma. IIRC, before I reverted, I used `peach, plum` to find the song.

**Comment by jonaski** [comment]
This is already fixed.
