### ISSUE TITLE
Strawberry adds "&" when editing the name of a playlist

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1499]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
The name of the playlist changes to "Playlist &#" from "Playlist #" when entering in edit mode.

**To Reproduce**
1. press ctrl+n to create a playlist - a new playlist named "Playlist #" is created
2. double-click on the tab of the newly created playlist

**Expected behavior**
the name of the playlist should not change after the double-click on its tab

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.1.0

**Additional context**

**Comment by jonaski** [comment]
This is a KDE bug, `QTabBar::tabText` returns this text including the ampersand character `&`: https://bugs.kde.org/show_bug.cgi?id=483488

**Comment by glaubersm** [comment]
Weird. Supposedly the Qt bug is fixed in Qt 6.7...

https://bugreports.qt.io/browse/QTBUG-86407

 my system where the bug occurs is running Qt 6.7.2.

**Comment by jonaski** [comment]
That bug doesn't seem to be the same bug, this specific bug is related to `QTabBar` which is a different widget. The problem is that KDE adds accelerator shortcuts (Ampersands) to the name of the tab, and we use the original title to preset to the user for renaming.

**Comment by jonaski** [comment]
I made a fix for it by not using `QTabBar::tabText`.
