### ISSUE TITLE
Playback skips a few ms when replaying FLAC songs

### ISSUE THREAD

**Issue by Neutrovertido** [strawberrymusicplayer/strawberry#1513]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry skips a split second of sound after a few seconds of replaying a FLAC when looped.

**To Reproduce**
1. Play any FLAC song
2. Set repeat to "repeat track".
3. Wait until the song finishes playing.
4. Once the songs starts playing again you will notice it will skip a few ms around the 1s mark.

**Expected behavior**
It should replay the song as normal.

**Screenshots:**
N/A.

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.1.1-1

**Additional context**
None.

**Comment by jonaski** [comment]
Isn't this the same bug as https://github.com/strawberrymusicplayer/strawberry/issues/1422 ?

**Comment by Neutrovertido** [comment]
> Isn't this the same bug as #1422 ?

Yes, sorry for duplicate, will close now.
