### ISSUE TITLE
Strawberry crashed when starting to play the next song

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#1515]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry was playing one song repeatedly, then I dragged an audio file from my file manager and drop it in the playlist,
clicked in the seek bar near the end of the current song, then Strawberry crashed when starting to play the next song.
However, I was unable to reproduce the crash by repeating the same steps.

**To Reproduce**
1. play a song repeatedly for a while
2. drag an audio file from the file manager and drop it in the playlist
3. click on the seek bar near the end
4. wait until the next song starts

**Expected behavior**
no crash

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.1.1

**Additional context**
crash log generated with gdb:
[gdb.txt](https://github.com/user-attachments/files/16481210/gdb.txt)

**Comment by jonaski** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3664

**Comment by jonaski** [comment]
According to the GStreamer developer, this bug should be fixed in GStreamer version 1.24.6. Do you know what GStreamer version it crashed with?

**Comment by glaubersm** [comment]
The last gstreamer update (to version 1.24.6-1) on Arch Linux was on 30th July, this crash occurred on 3th August.

**Comment by jonaski** [comment]
New bug report here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3742

**Comment by jonaski** [comment]
There is a possible fix here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7401

I'm currently testing this. I have built gst-plugins-base with this patch here: https://build.opensuse.org/package/show/home:jonaski:branches:multimedia:libs/gstreamer-plugins-base

**Comment by jonaski** [comment]
I've been testing over night and this bug looks to be fixed with https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7401 which has also been merged in GStreamer, but it missed 1.24.7 so that version is still affected, I've opened a bug report in Arch here:
https://gitlab.archlinux.org/archlinux/packaging/packages/gst-plugins-base/-/issues/2 and asked if they can add the patch.
