### ISSUE TITLE
Strawberry icon disappears from MPRIS2 interface

### ISSUE THREAD

**Issue by sirlucidae** [strawberrymusicplayer/strawberry#1516]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Strawberry's application icon disappears from the MPRIS2 interface after launching the program, it then reverts to a generic media player icon (and also the name changes to all lowercase). The icon does however display correctly before launching the program for the first time during that user session.

**To Reproduce**
Start a new session. Check Strawberry's entry in the MPRIS2 interface. Launch Strawberry, then check again.

**Expected behavior**
Application icon (and name) remains the same.

**Screenshots:**
![strawberry](https://github.com/user-attachments/assets/28e33604-b2e0-4689-8669-5b49fc9d1f22)

**System Information:**
 - Operating system: Debian 12, XFCE 4.18
 - Strawberry Version: 1.1.1, deb package

**Additional context**
I am currently using the "Papirus" icon set, but I also tested the system default icon set "Tango", with the same result.

**Comment by jonaski** [comment]
What does `qdbus6 org.mpris.MediaPlayer2.strawberry /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.DesktopEntry`return?
Does the desktop file (`org.strawberrymusicplayer.strawberry.desktop`) in `/usr/share/applications`?

**Comment by jonaski** [comment]
Thanks, Strawberry returned `org.strawberrymusicplayer.strawberry.desktop` for `DesktopEntry`, turns out this is wrong according to the specifications (https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:DesktopEntry), it needs to be without the file extension, so just `org.strawberrymusicplayer.strawberry`, fixed now. I Also confirmed it works now on XFCE with the PulseAudio applet.
