### ISSUE TITLE
Strawberry doesn't play songs, stays at 0:00, then freezes after changing song

### ISSUE THREAD

**Issue by PaperShreds** [strawberrymusicplayer/strawberry#1517]
**Describe the bug**
Strawberry doesn't play any songs anymore, also freezes after trying to play other tracks.

**To Reproduce**
1 - Open Strawberry
2 - Choose & play song
3 - The play/pause button changes, suggesting that a song is playing, seekbar stays at 0:00, no audio playing
4 - Choose a different song twice, on the second song Strawberry freezes, Gnome pop-up asks to either force quit or wait for the program to respond

**Expected behavior**
Song plays.

**Screenshots:**
![image](https://github.com/user-attachments/assets/10b9a175-44a4-4599-b382-2a7e96a110c7)
(notice the pause button that suggests a playing song, but nothing is playing)
**System Information:**
 - Operating system: EndeavourOS Linux x86_64,  Linux 6.10.3-arch1-2, DE: Gnome
 - Strawberry Version: 1.1.1

**Additional context**
Might not be Strawberry's fault, still submitting bug just in case, and for others to test. If the issue resolves itself after I update my system, I will remove it / mark as resolved.

**Comment by jonaski** [comment]
Are you using ALSA, pulseaudio or pipewire? What settings do you have in Backend / Output and device?

**Comment by jonaski** [comment]
Closing this because of no reply.
If this is still an issue, provide a full debug log by running strawberry in a terminal:
`GST_DEBUG=5 GST_DEBUG_FILE=/tmp/gst-debug.log strawberry`

**Comment by dtl131** [comment]
> GST_DEBUG=5 GST_DEBUG_FILE=/tmp/gst-debug.log strawberry

What happens if the log grows to 15MB in a matter of seconds?
