### ISSUE TITLE
Skips every second song during the crossfade

### ISSUE THREAD

**Issue by MadLostSoul** [strawberrymusicplayer/strawberry#1518]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Since the upgrade to version 1.1.1-46-g548fa3f6 Strawberry skips every second song during the crossfade.

So track 1 plays completely and fades over to track 2. When the crossfade is finished, it immediately plays track 3. Track 2 is therefore not played.

**To Reproduce**
Play a playlist. My value for the fade time is set to 10000 ms. Let the playlist play. Every 2nd track is only played during the crossfade.

**Expected behavior**
That every track in the playlist is played including crossfades.

**Screenshots:**
N/A

**System Information:**
 - Operating system: Linux raspberrypi5 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
 - Strawberry Version: 1.1.1-46-g548fa3f6

**Additional context**
N/A

**Comment by jonaski** [comment]
Thanks for reporting that, I've made some huge changes so there might be some regressions, but at least it seems to work as far as I have tested now.
