### ISSUE TITLE
When editing a field in the track list, typing too fast switches to the filter bar

### ISSUE THREAD

**Issue by klndacdk** [strawberrymusicplayer/strawberry#1519]
**Describe the bug**
A bit of a weird one here. When editing any metadata field in the tracklist itself, typing too quickly results in control being shifted to the filter bar. For Example, changing genre to 'Rock', would enter 'R', then filter the whole playlist by 'ock'. Typing below a certain pace seems to avoid the issue but its still quite frustrating.

**To Reproduce**
See above, Seems to apply to any field and any combination of letters.

**Expected behavior**
Any letters entered stay within the field being edited.

**System Information:**
 - Operating system: Kubuntu Linux 24.04
 - Strawberry Version:  1.0.23

**Comment by jonaski** [comment]
Can't reproduce this here, and it doesn't seem likely to be a Strawberry bug, more likely keyboard or shortcuts configuration issue.

**Comment by klndacdk** [comment]
Thanks for checking. I had another quick trawl of my KDE settings to make sure I hadn't accidentally set up a shortcut and couldn't find anything. I did check again though and its not actually the pace of typing thats switching things. When I first edit a field, an autocomplete drop-down appears showing the existing items for that field in the library (so typing  'ra' shows 'Radiohead', 'Rancid' etc.). Its actually typing the first letter that doesn't correspond to an existing field that moves control to the filter ('eg 'rax'). 

I'm wondering if its a Kubuntu issue, but probably not a user-tweakable one sadly.

**Comment by jonaski** [comment]
So are you talking about the tag editor here, not the inline editor? Since you say "track list" I assumed you meant inline editor in the playlist.
