### ISSUE TITLE
Ampersands in the option labels

### ISSUE THREAD

**Issue by martynjlewis** [strawberrymusicplayer/strawberry#1524]
![After Accepting](https://github.com/user-attachments/assets/f0dd976f-c350-4db4-9a1a-c26d29f29a72)
![Before Accepting](https://github.com/user-attachments/assets/cf37a90c-9187-4671-a5c2-bbd45adb0a64)
- [Y] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [Y] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [Y] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When opening Strawberry, the text on the options going down the left side are fine, as soon as you close the popup box, their appear with & symbols in them

**To Reproduce**
Freshly install Strawberry (new OS install) or uninstall, remove all config files from .local, .config and .cache then reinstall.

**Expected behavior**
The labels on the options to not have & symbols in them

**Screenshots:**

**System Information:**
 - Operating system: OpenSUSE Tumbleweed
 - Strawberry Version: 1.1.1

**Additional context**
Installed from the main repo, I can't find this in the issues already so I apologise if it is a duplicate report.

**Comment by bkmo** [comment]
Already fixed. Just build from Git if you want it now.

**Comment by martynjlewis** [comment]
oh sorry, I didn't know. I'll wait for it to update in the repo. Thanks

**Comment by bkmo** [comment]
There is a fix for this according to this comment:
https://github.com/strawberrymusicplayer/strawberry/issues/1476#issuecomment-2206626494

**Comment by jonaski** [comment]
Yes, this is fixed.
