### ISSUE TITLE
TLS initialization issues

### ISSUE THREAD

**Issue by kirk781** [strawberrymusicplayer/strawberry#1529]
Whenever I am trying to scrobble to either Last.fm or Libre.fm or Listenbrainz, I am getting the error message TLS initialization failed(99). I tried re installing the software but to no avail. 
It used to work until atleast 2 weeks ago properly but has been giving continuous issues since then.

OS: Void Linux
Strawberry Version: 1.1.1 [the latest one from the repos]

**Comment by jonaski** [comment]
What Qt version, and is openssl linked or loaded at runtime? and did you check that the Qt TLS Backend is actually loaded?

**Comment by kirk781** [comment]
OpenSSL was fine but Qt TLS OpenSSL plugin wasn't installed. After installing it, things work as expected.
