### ISSUE TITLE
Regularly stuck on "Buffering..." when playing Opus files

### ISSUE THREAD

**Issue by bsduck** [strawberrymusicplayer/strawberry#1530]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When playing a playlist consisting of .opus files, Strawberry is regularly stuck buffering forever between tracks. I need to manually start the next track in order to resume playback. The problem seems to occur rather randomly, not always between the same tracks, but is frequent. It doesn't occur when playing other audio formats.

**To Reproduce**
Play any album encoded in Opus format.

**System Information:**
 - Operating system: FreeBSD 14.1-RELEASE amd64
 - Strawberry Version: 1.1.1

**Additional context**
Another user mentioned the same problem earlier this year in a comment to the closed bug report #1020:
> I'm having the same issue where Strawberry 1.0.23 gets stuck on Buffering - 0%. It only happens on Opus files. It's been happening to me for a long time, even back before I started using Pipewire, so please don't blame Pipewire. I've tried running Strawberry from the terminal in verbose mode, but I didn't see any useful error messages. It just outputs messages on the previous track and it doesn't look like it's trying to advance to the next track.

For context, I don't use PipeWire, nor PulseAudio (Strawberry outputs directly to FreeBSD's native OSS). I've also had this problem for years (it was about time to finally report it!), actually since I began using Strawberry instead of Clementine (which didn't have this bug).

**Comment by dtl131** [comment]
I was the "other user" having that issue. I can't remember when/how, but it went away. What version of gstreamer are you using?

**Comment by bsduck** [comment]
Interesting, thanks for the feedback.

I'm using gstreamer 1.22.10.

**Comment by jonaski** [comment]
The bug is most likely in GStreamer even if you can't reproduce it with Clementine, Strawberry uses GStreamer differently than Clementine so it's hard to compare a problem like this.
It would be good idea to try the latest GStreamer version first and see if the issue still can be reproduced.
If it can then run strawberry from a terminal with GST_DEBUG and attach the debug log here.
Command:
`GST_DEBUG=5 GST_DEBUG_FILE=/tmp/gst-debug.log strawberry`

**Comment by scottfurry** [comment]
Had a similar issue but not with OPUS files. My issue was definitely was definitely gstreamer related. An update and rebuild of gstreamer resolved the problem. IIRC, v1.23 fixes the buffering problem.

Until then, the workaround is to kill the strawberry instance, restart strawberry, and you may need to reload the playlist. If the problem persists a couple of tracks later, repeat. It's annoying behavior but it does go away eventually with the update.

**Comment by bsduck** [comment]
I now have gstreamer 1.24.8 and the problem is gone. Thank you all for your input.

**Comment by Wodsfort** [comment]
I have similar, but I use .mp3 files.It reproducible 1.2.26 
Operating System: EndeavourOS 
KDE Plasma Version: 6.7.3
KDE Frameworks Version: 6.28.0
Qt Version: 6.11.1
Kernel Version: 7.1.5-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i3-1005G1 CPU @ 1.20GHz
Memory: 8 ГиБ of RAM (7.5 ГиБ usable)
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Dell Inc.
Product Name: Vostro 3501

**Comment by guprobr** [comment]
I'm experiencing same thing but with Tidal too. Oopus and Tidal and Qobus. I don't have time lately to debug properly.

The playlists are huge. huge. +100k
It happens to me when resuming a previous sesssion that had an asset already playing. I have to kill -9 and then, without resume/autoplay, it does not happen. I didn't experience this at normal runtime, only while opening the library with a media about to be resumed. Program gets stuck, unresponsive.

This could be a threading issue.

**Comment by Wodsfort** [comment]
My plalist contain only 400 melodies
