### ISSUE TITLE
Sort by File Name column produces unexpected results

### ISSUE THREAD

**Issue by mdpenguin** [strawberrymusicplayer/strawberry#1538]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When sorting by the File Name column, the results don't really make sense.  See the example below where it jumps from a folder starting with S to one starting with X then back to one starting with B.

**To Reproduce**
Sort a large playlist by File Name with a lot of different folders involved

**Expected behavior**
Sorting should work the same way that it does in the file browser

**Screenshots:**
![image](https://github.com/user-attachments/assets/047dd7ae-a483-4b60-b52a-c5410746be19)

**System Information:**
 - Operating system: Linux Mint 22.0
 - Strawberry Version: Version 1.1.2-rc1-3-g3238e295

**Additional context**
This particular playlist has 6310 tracks that are all local files

**Comment by jonaski** [comment]
Your screenshot doesn't show the entire paths, so it's hard to know exactly, but my I guess is that's it's the number of /.

**Comment by jonaski** [comment]
af06f8e70a82c2657b51293d03f5f55f64fbdf15 should probably fix this

**Comment by mdpenguin** [comment]
Yep, that took care of it.  Thanks!
