### ISSUE TITLE
Strawberry shouldn't clutter temp dir directly with cover images

### ISSUE THREAD

**Issue by marcusmueller** [strawberrymusicplayer/strawberry#1540]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
It's discouraged to clutter the global temporary directory, especially on a multiuser system.

Instead, we should try to stick a few friendlier conventions:

- if set, the `XDG_RUNTIME_HOME` environment variable tells us the correct place. This is both user-specific (no other user's business how many albums I'm playing in short time), as well as managed as temporary directory (with guaranteed cleanup properties).
- if not set, at least `QDir::tempPath() + "/strawberry-{random}"` should be used as prefix, to take away the visibility of the change of album titles away from other users, and to de-clutter /tmp. (seriously. Don't clutter /tmp.)

**To Reproduce**

Run strawberry, play song with cover from database: /tmp/strawberry-cover-XYZABC.jpg gets created.

**Expected behavior**

adherence to desktop standards

**Screenshots:**

 n/a

**System Information:**
 - Operating system: Linux, but the "don't clutter `%TMP%`" applies to windows as well
 - Strawberry Version: git master as of today

**Additional context**

I'd like to write an MPRIS web frontend, but I have absolutely no intention of giving a service serving album covers file access to /tmp; that is risky, as Xauth and other confidential files end up in there as well. Constraining cover file creation to a specific directory is hence very desirable.

**Comment by jonaski** [comment]
There is no such thing as `XDG_RUNTIME_HOME` as far as I know, it's not documented on https://specifications.freedesktop.org/basedir-spec/latest/index.html,
I've changed it to use `QStandardPaths::writableLocation(QStandardPaths::TempLocation)`, it will then use the user profile temp directory on macOS and Windows, but it will still be `/tmp` on Linux because there isn't a user specific temp directory on Linux.

**Comment by marcusmueller** [comment]
Sorry, my typo; `$XDG_RUNTIME_DIR` *is* that per-user temporary directory for files that don't survive the user session.

**Comment by jonaski** [comment]
XDG_RUNTIME_DIR is mostly a directory for sockets and named pipes and smaller runtime files, I don't think placing the cover image there is a good idea.
I'll keep the default temp location from QStandardPaths for now.
