### ISSUE TITLE
Files from a removed directory are still shown in collection

### ISSUE THREAD

**Issue by braoult** [strawberrymusicplayer/strawberry#1545]
Version: Strawberry 1.0.14 on Ubuntu 23.10.

Situation:
I have music on a local file system (`/mnt/hd/external-1/Music/Music` directory). 
I also have the same music on a NFS mount (mounted as `/mnt/nfs/music/daily-01/Music` directory).
Only the local directory (`/mnt/hd/external-1/Music/Music`) was in use by Strawberry.

What I did:
I decided to switch to the NFS version, and stop using the local version.
To do so, I removed the local directory in Collection, and added the NFS one. The settings became:

![folders](https://github.com/user-attachments/assets/6e7a690f-288e-42eb-b469-ddb0e95da598)

I did a full collection rescan, but old collection files are still available:

![dups](https://github.com/user-attachments/assets/f452a418-2226-4b62-973a-3b7733730a18)

The respective results of "Show in file browser" give:
![local](https://github.com/user-attachments/assets/881751c7-cdcb-4c99-b01f-3d25eab82148)
![nfs](https://github.com/user-attachments/assets/4c88effb-3783-4672-aa5c-349a2eae3cef)

Expected result: The files from now unused directory should have disappeared from collection.

**Comment by jonaski** [comment]
If you right click on the song in the collection and select "edit track information", does it show the old path in the summary tab?
But why are you using 1.0.14? Even if this is a bug is in Strawberry, there isn't much point in debugging that on that old version unless it can be reproduced on the newest version, as the collection stuff is pretty much rewritten in newer releases.

**Comment by jonaski** [comment]
I'll reopen this if it's reported back that it's still an issue in the latest.
