### ISSUE TITLE
Mysterious compilation issue on Linux Mint 22 with missing sqlite3

### ISSUE THREAD

**Issue by Lefuneste83** [strawberrymusicplayer/strawberry#1547]
- [X ] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
While trying to compile the master branch on latest Linux Mint 22 I get the following missing dependency error:

```
❯ cmake ..                              
-- Strawberry Version:
-- Display:  1.1.2-20-g0decbdc2
-- Package:  1.1.2.20.g0decbdc2
-- RPM:      1.1.2-2.20.g0decbdc2
-- Found the following ICU libraries:
--   uc (required): /usr/lib/x86_64-linux-gnu/libicuuc.so
--   i18n (required): /usr/lib/x86_64-linux-gnu/libicui18n.so
-- Could NOT find Protobuf (missing: Protobuf_DIR)
-- Checking for module 'sqlite3>=3.9'
--   Package 'sqlite3', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - sqlite3>=3.9

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  CMakeLists.txt:157 (pkg_check_modules)


-- Configuring incomplete, errors occurred!

```

But I confirm that the requirement seems fulfilled:

```
❯ sqlite3 --version       
3.45.1 2024-01-30 16:01:20 e876e51a0ed5c5b3126f52e532044363a014bc594cfefa87ffb5b82257ccalt1 (64-bit)
```
Am I missing something or is there a specific library that should be added or setting to be modified ?

Thanks

**To Reproduce**
Not applicable

**Expected behavior**
Compilation should proceed

**Screenshots:**

**System Information:**
 - Operating system: Linux Mint 22
 - Strawberry Version: Master Branch

**Additional context**

**Comment by jonaski** [comment]
> ❯ sqlite3 --version       
> 3.45.1 2024-01-30 16:01:20 e876e51a0ed5c5b3126f52e532044363a014bc594cfefa87ffb5b82257ccalt1 (64-bit)

This doesn't show that you have the library, only the sqlite3 executable.

You need to check it with pkg-config, command:
`pkg-config sqlite3 --libs --cflags`

If that does not find it, you need to set `PKG_CONFIG_PATH` to where you have the sqlite3.pc file.

**Comment by AllKind** [comment]
`apt install libsqlite3-dev` ?

**Comment by Lefuneste83** [comment]
Yes that was it Thanks!!

**Comment by Lefuneste83** [comment]
Solved
