### ISSUE TITLE
win 11 version 1.1.2 crashes 2 seconds after Start

### ISSUE THREAD

**Issue by haraldok** [strawberrymusicplayer/strawberry#1553]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots:**

**System Information:**
 - Operating system:
 - Strawberry Version:

**Additional context**

**Comment by haraldok** [comment]
Name der fehlerhaften Anwendung: strawberry.exe, Version: 1.1.2.0, Zeitstempel: 0x66e33c7b
Name des fehlerhaften Moduls: MSVCP140.dll, Version: 14.29.30133.0, Zeitstempel: 0x60ff28cc
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000013020
ID des fehlerhaften Prozesses: 0x0x347C
Startzeit der fehlerhaften Anwendung: 0x0x1DB09A82DEA69EE
Pfad der fehlerhaften Anwendung: C:\Program Files\Strawberry Music Player\strawberry.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\MSVCP140.dll
Berichtskennung: be3752ac-80ed-48a5-9437-f9091c810148
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

![grafik](https://github.com/user-attachments/assets/abf6bb66-9986-43db-a5a6-d830ed8fc1b7)

**Comment by haraldok** [comment]
The same here: Thanks, to @jonaski: since repair-install it runs proper:
"The Visual C++ runtime (MSVCP140.dll), might be to old. According to the log, you have MSVCP140.dll, version: 14.29.30133.0.
Latest is 14.40.33810.0.
Can you try installing the latest from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
(Direct link to the setup is https://aka.ms/vs/17/release/vc_redist.x64.exe).
Since the MinGW version works, it might be the issue, since the MinGW version does not use Visual C++ runtime."

**Comment by jonaski** [comment]
@haraldok Good to hear, I was just going to reply you.
