### ISSUE TITLE
There does not appear to be any way to provide user data to log into genius.com

### ISSUE THREAD

**Issue by drkmc** [strawberrymusicplayer/strawberry#1554]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ x] spent hours looking for documention/user guide/ "How to use genius.com to get lyrics" etc
- -[x] read the man page _(oh, wait....no, doesn't look like you have one...")_
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When you try to use genius.com to get lyrics it tells you that authentication is required, and then the app just spins and spins.  My browser showed a URI that looked like it had an oauth key, but the web site said it was invalid.  I could not find any place in the config file, settings, etc. to enter my userId/passord.  I was logged into the web site at the time, and I had even generated a oauth key I could have used, but no place was evident to supply it.  

**To Reproduce**
Click on genius to get lyrics

**Expected behavior**
(1) enter my oauth info into the ~/.config/strawberry/strawberry.conf in the (nonexistent) [genius] section (either user id/pw or my oauth)
(2) enter my information into a section in the settings 
(3) be prompted for my information on first attempt to access genius.com (with a URL to the "sign up" page for users who don't have an account yet)

**Screenshots:**
![strawberry1](https://github.com/user-attachments/assets/a7596186-9d57-4c18-afb6-057b3a5856ba)
![strawberry2](https://github.com/user-attachments/assets/15b0ba54-54bc-4927-82df-2ce8c5f6e96a)
![strawberry0](https://github.com/user-attachments/assets/9e209b86-e96a-4a97-9c61-d3efe53ea12d)

**System Information:**
 - Operating system:  Kernel: 6.10.9-1-default arch: x86_64 bits: 64 compiler: gcc     v: 14.2.0   Desktop: KDE Plasma v: 6.1.5 Distro: openSUSE Tumbleweed 20240916    Display: x11 server: X.Org v: 21.1.12 with: Xwayland v: 24.1.2 driver: X:
    loaded: amdgpu,modesetting unloaded: fbdev,vesa gpu: amdgpu resolution:
Qt 
Version 6.7.2 (built against 6.7.2)
KDE Frameworks 
Version 6.5.0
Python 3.11.9

 - Strawberry Version:
Strawberry 1.1.1

**Additional context**
Can't think of any. Looking forward to figuring out the app.  A user guide or man page would not suck....

**Comment by drkmc** [comment]
PS:  For remote, why can't android users just use KDE Connect and the command line options?  Its pretty crude, but it is what I do for pianobar (it looks in a local file for volume, station, pause--not a huge suit  of ability but it is pretty easy to hack).

**Comment by jonaski** [comment]
Looks like I broke the login in 0c6872b

**Comment by jonaski** [comment]
You do not need to provide a client id or secret as it is coded into strawberry. The web browser should open and you login that way through OAuth which sends the access token back to Strawberry.
I did some manual string conversions on the whole code base earlier this year and looks like I accidentally missed a call to `QByteArray::fromBase64` in 3 places, it's fixed now.
