### ISSUE TITLE
Strawberry has a black box around "Expand", "Repopulate" and "Turn Off"; suspected QT issue? 

### ISSUE THREAD

**Issue by manofsticks** [strawberrymusicplayer/strawberry#1572]
Arch Linux
Strawberry Version 1.2.0-0-ge6607fef
QT Version (according to Strawberry): Qt version 6.7.3.

![image](https://github.com/user-attachments/assets/48fc0669-2ce7-42d4-ab84-b718ee35f663)

I do have that version of QT installed
![image](https://github.com/user-attachments/assets/8db2d6bf-284a-4423-ae40-1fd851e34134)

Running with -vvv does not give me much; attempted to look up RGB parameters out of range and got nowhere. 

![image](https://github.com/user-attachments/assets/bc3d669f-899c-49cc-89ce-371a5098610c)

I suspect this may be a QT issue, and not a Strawberry issue specifically, but unsure of where else to research. 

Thanks

**Comment by Npa972** [comment]
Hi I've never seen these buttons (expand...).
How do you make them appear ?
OS arch linux up to date
Strawberry Version 1.2.0-0-ge6607fef
![image](https://github.com/user-attachments/assets/f28190e3-c564-4618-aa78-637922b0b735)

**Comment by manofsticks** [comment]
> Hi I've never seen these buttons (expand...). How do you make them appear ? OS arch linux up to date Strawberry Version 1.2.0-0-ge6607fef ![image](https://private-user-images.githubusercontent.com/49346431/373439050-f28190e3-c564-4618-aa78-637922b0b735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTk3OTMsIm5iZiI6MTcyNzk5OTQ5MywicGF0aCI6Ii80OTM0NjQzMS8zNzM0MzkwNTAtZjI4MTkwZTMtYzU2NC00NjE4LWFhNzgtNjM3OTIyYjBiNzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIzNTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYTNjYjc2NTdhYWQ5NGU4ODVmMTA1N2MyNjFkOTExMmMyYzE2ZDQyNmEwNDAxMjQzMWRmZWJjOWEwMTI5OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.10Mb7uqCXQsphcFbBx6Hp5hwiPv_F17YQMSm1pt32fs)

When I go to "Dynamic Random Mix" in Smart Playlists, it appears. Essentially keeps a constantly running "Shuffle".

**Comment by Npa972** [comment]
Ok i confirm.

**Comment by jonaski** [comment]
I can confirm this, thanks for reporting. Bug created here: https://github.com/strawberrymusicplayer/strawberry/commit/4270b12cd1ea5764709a4563778c2194059f71dd#diff-797d2c4e4d323f42fdc34ed35565ea6e2dc94ff3a067b5db2acb746d4e79ffbaR50
`u'%'` should be `u"%"_s`
