### ISSUE TITLE
Cannot install Strawberry on Fedora from OpenSUSE build repo due to missing dependency

### ISSUE THREAD

**Issue by mmkthecoolest** [strawberrymusicplayer/strawberry#1580]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [ ] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Newer builds of Strawberry from the OpenSUSE build repo don't seem to be able to install on Fedora. I get an error that a dependency (libstrawberry_lib.so()(64bit)) is missing. Here is the full message:
```
Problem: cannot install the best candidate for the job
  - nothing provides libstrawberry_lib.so()(64bit) needed by strawberry-1.2.0.98.g28222b183-1.1.x86_64 from home_jonaski_audio
```

**To Reproduce**
1- Add the [OpenSUSE build repo](https://download.opensuse.org/repositories/home:/jonaski:/audio/) to the package manager
2- Install Strawberry on a terminal using `sudo dnf install strawberry`

**Expected behavior**
The latest build from home_jonaski_audio repo should be able to install

**System Information:**
 - Operating system: Fedora 40

**Additional Notes:**
I also noticed that the latest released version on the website and GitHub repo is 1.1.3 while the repo is offering 1.2.0. Is this intentional? If so, are the OpenSUSE builds supposed to be for testing or are they stable?

**Comment by jonaski** [comment]
1.1.3 is the latest stable release.
1.2.0 is the current development version.
