### ISSUE TITLE
Some recent "ends of songs" are played randomly

### ISSUE THREAD

**Issue by jirislaby** [strawberrymusicplayer/strawberry#1582]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Running strawberry for a couple of days. Sometimes, it plays the last ~ 10 seconds of some past song incl. fade-out. Strawberry needs not be playing currently. It just starts playing randomly. This is somewhat new bug, I updated like:
```
2024-07-17 07:05:45|install|strawberry|1.1.0-1.1|x86_64
2024-07-26 07:09:05|install|strawberry|1.1.1-1.1|x86_64
2024-08-15 14:28:49|install|strawberry|1.1.1-1.2|x86_64
2024-09-23 07:44:17|install|strawberry|1.1.2-1.1|x86_64
2024-10-07 06:28:22|install|strawberry|1.1.3-1.1|x86_64
```

**To Reproduce**
Just use strawberry for some time. Likely fade-out needs to be enabled? And using pipewire?

**Expected behavior**
To not play the ends randomly.

**Screenshots:**
Note these pipewire streams:
![straw](https://github.com/user-attachments/assets/6697d30d-835b-4a6d-b526-bfa31a5485a7)

Usually only one playing a song is present. All the other are to play these ends of songs.

**System Information:**
Operating System: openSUSE Tumbleweed 20241018
KDE Plasma Version: 6.2.1
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Kernel Version: 6.11.5-rc1-1.g8c2e67f-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics
Memory: 58.4 GiB of RAM
Graphics Processor: AMD Radeon 780M
Manufacturer: LENOVO
Product Name: 21K6S0A006
System Version: ThinkPad P14s Gen 4

 - pipewire: 1.2.5
 - Strawberry Version: 1.1.3

**Comment by jonaski** [comment]
I suspect this is the same bug as.:
https://github.com/strawberrymusicplayer/strawberry/issues/1535
https://forum.strawberrymusicplayer.org/topic/3379/music-fragments-play-over-other-music-randomly
https://forum.strawberrymusicplayer.org/topic/3212/randomly-playing-end-of-previously-played-track

I can't reproduce this.
What audio format does it happen with, and is cross fading enabled?

**Comment by jirislaby** [comment]
> Just a hint, maybe not relevant.

It **is** relevant. I played:

- Queen: Don't Stop Me Now -- fine
- Fleret: Na Kralovej Holi -- **error**: "No data in file"
- Iron Maiden: Still Life -- fine

Now pipewire has two sinks:
- `media.name = "„Still Life“ od „Iron Maiden“"` (currently playing)
- `media.name = "„Don't Stop Me Now“ od „Queen“"`

So I enqueued _Na Kralovej Holi_ once again (by Ctrl+D). After finishing the current song, I have now three sinks:
- `media.name = "„Don't Stop Me Now“ od „Queen“"` (played before first fail above)
- `media.name = "„Já su od Lidečka“ od „Fleret“"` (played before second fail)
- `"„Chord Sounds“ od „Moby“"` (currently playing)

**Comment by jonaski** [comment]
I've set up pipewire and set output to PulseAudio, tested playing for many hours a playlist on repeat containing MP3 and MP4 files, I still can't reproduce this, I've checked that no more than 1 file is open at a time.

`lsof -p $(pidof strawberry)` shows only 1 file open, and `pactl list sinks` shows only 1 sink.

If cross fading is disabled, it's hard to understand why several files are kept open at the same time.

But surely there must be a case where there is an error leading to the previous pipeline is stuck, I still don't understand why it's fading if automatic cross-fading is disabled, unless you manually switch track.

**Comment by guprobr** [comment]
I confirm this behaviour happening here too, but I could not reproduce.
After disabling EBUR normalization it seems to stop, but I'm not sure about this.

**Comment by jonaski** [comment]
@jirislaby Do you have any of the features replay gain, ebur128 or bs2b enabled in the backend settings?

**Comment by jirislaby** [comment]
> @jirislaby Do you have any of the features replay gain, ebur128 or bs2b enabled in the backend settings?

I have "No Audio Normalization" set.

> for many hours a playlist on repeat containing MP3 and MP4 files

Have you enqueued a bad file as I wrote above? Like the attached [file.zip](https://github.com/user-attachments/files/17686340/file.zip) (sorry, I had to pack the file due to github restrictions)?

**Comment by jonaski** [comment]
Can reproduce with that file

**Comment by jonaski** [comment]
The playbin pipeline is unrefed and the engine pipeline is deleted, so unless I'm missing something basic here this seems like a GStreamer bug.

**Comment by jonaski** [comment]
I see the issue now, the problem is that the pipeline isn't set to NULL correctly before unrefing because `state()` returns `GST_STATE_NULL` when it's getting `GST_STATE_CHANGE_FAILURE`...

**Comment by jonaski** [comment]
Could you please test the latest master branch and check if the issue is gone?
For Tumbleweed you can either build from source or use my repository here:
https://build.opensuse.org/projects/home:jonaski:audio/packages/strawberry/repositories/openSUSE_Tumbleweed/binaries

**Comment by jirislaby** [comment]
Yes, seems to be fixed. Thanks!

**Comment by jirislaby** [comment]
> https://build.opensuse.org/package/show/home:jonaski:audio/strawberry

BTW, are you aware of `_service` files [1]? And OBS+github integration [2]?

[1] https://en.opensuse.org/openSUSE:Build_Service_Concept_SourceService
[2] https://linuxkamarada.com/en/2019/03/19/integrating-the-open-build-service-with-github/

**Comment by jonaski** [comment]
@jirislaby I'm aware of it, but haven't studied it enough yet.

**Comment by jonaski** [comment]
Will make a release candidate this weekend, and hopefully a stable release next week.
