### ISSUE TITLE
.cdg file karaoke player

### ISSUE THREAD

**Issue by rlucian** [strawberrymusicplayer/strawberry#1583]
Hi, Checked the faq, repo and forum and couldn't find any reference to either cdg or karaoke.
I have used winamp with a plugin that recognized .cdg files to play karaoke files (mp3+cdg).
It would be really nice to have such a feature in strawberry, so i can finally give winamp it's proper burial.

**Comment by jonaski** [comment]
This isn't supported and there are no plans to add it. This project has only 1 developer, so adding specific features users want isn't possible.
