### ISSUE TITLE
Outdated Windows build instructions strawberry-msvc/README.md

### ISSUE THREAD

**Issue by Erriez** [strawberrymusicplayer/strawberry#1586]
**Describe the bug**
The Windows build instruction is outdated and broken:

The [README.md](https://github.com/strawberrymusicplayer/strawberry-msvc/blob/master/README.md) refers to `copy-deps-msvc-x64-debug-qt6.bat` and `copy-deps-msvc-x64-release-qt6.bat` which are removed in this commit [Remove copy deps files](https://github.com/strawberrymusicplayer/strawberry-msvc/commit/47dd966512acacb1e7d10433a7202b8332d12dff).

However, these build are required before starting the NSIS setup build. Additionally, several dependencies are missing.

**To Reproduce**
Follow instructions `README.md`.

**Expected behavior**
Clear build description for Windows, no errors.

**Screenshots:**
N.A.

**System Information:**
 - Operating system: Windows
 - Strawberry Version: github.com/strawberrymusicplayer/strawberry-msvc 367396afc61f9731b34c98a935d7b98be70eaa6f

**Additional context**
N.A.

**Comment by jonaski** [comment]
I've removed the references to those batch files. build.bat already copies everything needed.

**Comment by Erriez** [comment]
The build instructions in `README.md` are incorrect and I'm trying to create and test a PR to fix it.

- Issue 1: The `README.md` still refers to the removed `.bat` files.
- Issue 2: The `build.bat` tries to build all dependencies from source which fails for several packages and could not find a solution for yet. It is a completely different build process compared with [Github Actions](https://github.com/strawberrymusicplayer/strawberry-msvc-dependencies/blob/master/.github/workflows/build.yml).
- Issue 3: There are two build methods: 1) Build from full source using `build.bat`. 2) Build from binaries from [strawberry-msvc-dependencies/releases](https://github.com/strawberrymusicplayer/strawberry-msvc-dependencies/releases). Option 2 is no longer possible with the removal of the `.bat` files.

Keeping this issue open is appreciated.

Did you test `build.bat` recently on a fresh Windows installation? Then I'll investigate further.
