### ISSUE TITLE
Windows gstspotify.dll missing in strawberry-msvc-dependencies releases

### ISSUE THREAD

**Issue by Erriez** [strawberrymusicplayer/strawberry#1587]
**Describe the bug**
The Windows NSIS installer [strawberry.nsi.in](https://github.com/strawberrymusicplayer/strawberry/blob/b106e944940ec5eee5e5e17e9db861c01b8546fd/dist/windows/strawberry.nsi.in#L719) contains a reference to `gstspotify.dll` which is not included in the MSVC binaries.

**To Reproduce**
Generate NSIS installer from generated `strawberry.nsi` cannot find `gstspotify.dll` using [strawberry-msvc-x86_64-debug.tar.xz](https://github.com/strawberrymusicplayer/strawberry-msvc-dependencies/releases/download/release-11510794555/strawberry-msvc-x86_64-debug.tar.xz) or [strawberry-msvc-x86_64-release.tar.xz](https://github.com/strawberrymusicplayer/strawberry-msvc-dependencies/releases/download/release-11510794555/strawberry-msvc-x86_64-release.tar.xz).

**Expected behavior**
 `gstspotify.dll`  included in the `tar.xz` binaries.

**Screenshots:**
N.A.

**System Information:**
 - Operating system: Windows
 - Strawberry Version: [strawberry-msvc-dependencies](https://github.com/strawberrymusicplayer/strawberry-msvc-dependencies) 180fda1

**Additional context**
N.A.

**Comment by jonaski** [comment]
Spotify is disabled because it doesn't currently build.

**Comment by Erriez** [comment]
Thanks for your confirmation. I could not apply the patch as described on https://wiki.strawberrymusicplayer.org/wiki/Installing_GStreamer_Spotify_plugin, so that confirms build issues.

No problem, it can be disabled with `ENABLE_SPOTIFY` for the time being. NSIS [strawberry.nsi.in](https://github.com/strawberrymusicplayer/strawberry/blob/dfcf7152911cd2732f2411badcd73cb33002daae/dist/windows/strawberry.nsi.in#L719) should be manually commented out at two places for install and uninstall.

**Comment by jonaski** [comment]
The patch isn't necessary because the MR has been merged to main, I've removed it now.
But I still couldn't build it, you can add back gst-plugins-rs in build.bat if you want to try, but you need to install rust and rustc.
