### ISSUE TITLE
Please provide distro agnostic binaries or a flatpak pkg

### ISSUE THREAD

**Issue by Twig6943** [strawberrymusicplayer/strawberry#1591]
![image](https://github.com/user-attachments/assets/773c5456-a0ab-4ffa-a9f5-4b32698bc6fc)
I've already seen this ⬆️.

Providing distro agnostic binaries shouldn't be that hard ( [Universal media server](https://github.com/UniversalMediaServer/UniversalMediaServer/releases) does this )

![image](https://github.com/user-attachments/assets/87aa4564-fd9b-4266-a336-46bfa8d05989)

(A flatpak would also be appreciated)

**Comment by jonaski** [comment]
Since this project has only one developer there isn't anyone who can work on this here.
UniversalMediaServer is written in Java, so not comparable at all.

**Comment by Twig6943** [comment]
Turns out a flatpak exists (https://flathub.org/apps/org.strawberrymusicplayer.strawberry) please put this to https://www.strawberrymusicplayer.org/#download

**Comment by Twig6943** [comment]
but specify that its unofficial. e.g. Flatpak (Unofficial)
![image](https://github.com/user-attachments/assets/b2d42c86-a847-46fe-ab3b-1930a8d843a7)

**Comment by jonaski** [comment]
Why is it unofficial?

**Comment by Twig6943** [comment]
Umm cuz the readme.md says so? (even tho its verified on flathub which kinda doesnt make any sense)
