### ISSUE TITLE
Flatpak image uses outdated libraries.

### ISSUE THREAD

**Issue by JYPDWhite** [strawberrymusicplayer/strawberry#1597]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [ ] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
When updating the application via flatpak `flatpak update` flatpak complains about end of life component for Strawberry
`` 
Info: runtime org.kde.Platform branch 6.6 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   org.strawberrymusicplayer.strawberry
```

**Expected behavior**
Strawberry is no longer using end of life components.


**System Information:**
 - Arch Linux (Linux whites-nb4 6.11.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000 x86_64 GNU/Linux)
 - Strawberry Version: 1.1.3

**Comment by jonaski** [comment]
We do not maintain the flatpak. Report the issue here: https://github.com/flathub/org.strawberrymusicplayer.strawberry/issues
