### ISSUE TITLE
No visual difference between starred and not starred playlists

### ISSUE THREAD

**Issue by AllKind** [strawberrymusicplayer/strawberry#1600]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
I don't know exactly when this was introduced. I just noticed it recently. Maybe it was my recent update from Linux Mint 21.3 to 22. Or the new strawberry version. I don't know.
However there no longer is a visual difference in the playlists tabs between playlists that are starred to those which are not.

**To Reproduce**
Have starred and not starred playlists open and look.

**Expected behavior**
The star for starred playlists should have a visual difference to those which are not starred

**Screenshots:**
The playlists PL8 and New_Stuff are not starred:
![strawberry-starred_playlists](https://github.com/user-attachments/assets/70507066-9c01-4cea-a5c4-9d456c8e21aa)

**System Information:**
 - Operating system: Linux Mint 22 (Cinnamon)
 - Strawberry Version: 1.1.3
 - QT version: 6.4.2

**Comment by jonaski** [comment]
Looking at the screenshot, the icons are not strawberry's standard icons, they either have been replaced, or the system theme icons are enabled, the icon name is "star-grey".
In Appearance settings, check that "Use system theme icons" is off.

**Comment by AllKind** [comment]
Thanks that resolves this.
I didn't change that setting, so it must have been the system update.
Closing.
