### ISSUE TITLE
Strawberry 1.1.3 crashes on launch (Paid)

### ISSUE THREAD

**Issue by insec404** [strawberrymusicplayer/strawberry#1603]
So I tried to compile this project and got pretty far but just decided to buy it to save time
Well the program crashes on launch on macOS
It runs in sudo though but how can i make it run normally?
I've been working with a.i. and the developer but so far nothing seems to work
I'll post the error message here. running it from my terminal to get the output.

/Applications/Strawberry.app/Contents/MacOS/Strawberry

07:02:26.378 WARN unknown KDSingleApplication: unable to make the primary instance listen on kdsingleapp-username-Strawberry: QLocalServer::listen: Name error
07:02:26.379 INFO main:166 Strawberry is already running - activating existing window (1)
07:02:31.380 WARN unknown Connection timed out
07:02:31.381 ERROR main:169 Could not send message to primary instance.

I've checked tmp no lock files there
I've cleared cache directories, uninstalled/reinstalled the app, restarted my computer
deleted anything that had to do with the compile project.
Idk I'm stumped. if anyone can help. i'd appreciate it.

**Comment by jonaski** [comment]
I've fixed the issue now, but I need to wait for the dependencies are built using the patch for KDSingleApplication (https://github.com/strawberrymusicplayer/strawberry-macos-dependencies/pull/328), I'll try to make a release candidate once it's finished.

**Comment by jonaski** [comment]
New release candidate available on Patreon now: https://www.patreon.com/posts/strawberry-1-2-1-116105907

**Comment by insec404** [comment]
Thanks mate! It loaded straight up!

**Comment by jonaski** [comment]
Good!

**Comment by insec404** [comment]
You're a bloody legend to have sorted that straight out!
I def will stick around your patreon to catch future updates!
