### ISSUE TITLE
Mouse scrolling doesn't work

### ISSUE THREAD

**Issue by a3kov** [strawberrymusicplayer/strawberry#1614]
- [*] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [*] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [*] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Mouse scrolling (in collection and generally) doesn't work

**To Reproduce**
Mouse over and scroll

**Expected behavior**
As collection can be a long list, mouse scrolling is expected to work

**Screenshots:**
-

**System Information:**
 - Operating system: Kubuntu 24.04 (upgraded from 22.04)
 - Strawberry Version: 1.1.3 installed from apt

**Additional context**
I'm not sure if it's an issue in Strawberry or in my OS installation, but mouse scrolling works just fine in other programs

**Comment by a3kov** [comment]
Seems to be similar to #1339 but in this case the OS is recent and the package is provided by the author, so if it depends on broken Qt version I consider it a bug and the package must have its dependency bumped to a working version

**Comment by a3kov** [comment]
Installing latest version from PPA fixes it.
Note that there's no visible link to PPA on the main website (at least I couldn't find it) - only here on github, so users may miss the information and install from the main ubuntu repo.

**Comment by jonaski** [comment]
> Seems to be similar to #1339 but in this case the OS is recent and the package is provided by the author, so if it depends on broken Qt version I consider it a bug and the package must have its dependency bumped to a working version

You are probably right, it's most likely the same bug. The Qt installation is not included with the strawberry deb package, the Qt installation on Linux distribution is used, so this issue needs to be reported to Ubuntu.
