### ISSUE TITLE
[FEATURE REQUEST] Remember last playing position for every playlist

### ISSUE THREAD

**Issue by Uhter** [strawberrymusicplayer/strawberry#1619]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

Hi everybody,

**Example**

We have multiple opened playlists, playing a podcast in playlist1 and close Strawberry. The player will remember the playing position next time.
But, if the next time we play a song track in playlist2, we lost the podcast playing position in the first playlist. It's a shame.

**Expected behavior**

Add a way to memorize playing position in every playlists.

**System Information:**

 - Operating system: Manjaro (Arch Linux based)
 - Strawberry Version: 1.2.2

*I hope you understand. I'm not english fluent.

**Comment by jonaski** [comment]
Currently not taking feature requests on GitHub because of lack of developers.

**Comment by Uhter** [comment]
So sorry to hear about it. Strawberry is the best audio player in my opinion.  
But, why not put on hold instead of closing?
