### ISSUE TITLE
Nice to have feature: Entire Collection Summary

### ISSUE THREAD

**Issue by NucleaPeon** [strawberrymusicplayer/strawberry#183]
I have a large collection of music, but I don't see an easy way to display statistics on it, such as:

1. number of unique artists
2. number of songs
3. total duration of all songs
4. number of unique genres
5. total size on disk
etc.

I was thinking of something like Tools -> Summary menu item and then showing a basic QWidget or whathaveyou with some labels and text.

Does this seem like something you would be interested in implementing?

**Comment by jonaski** [comment]
I think this could be useful and an nice improvement.

**Comment by jonaski** [comment]
I'm closing this since I don't have time to prioritize it. Someone else is free to make a proposal for this feature in a PR.
