### ISSUE TITLE
Migrate database from Clementine or Amarok 2.x

### ISSUE THREAD

**Issue by sten0** [strawberrymusicplayer/strawberry#248]
A recent email to debian DASH kde AT lists DOT debian DOT org made me aware of Strawberry.  Thank you very much for carrying the Amarok 1.x banner into the future :-)

**Is your feature request related to a problem? Please describe.**
Several users in the above noted list have expressed their dissatisfaction with being stuck having to migrate from Amarok 2.x to something else, while losing various metadata (maybe more than just playcount and loved?  Maybe things things # of times a track was skipped?)  It seems to me like Strawberry can do better than Clementine.  Of course it would easy to add Clementine-to->Strawberry.

**Describe the solution you'd like**
First run database import/migration wizard.

**Describe alternatives you've considered**
I'm not familiar with database traversal algorithms, and am not sure if this particular case is an easy or hard problem.  Sorry...

**Comment by jonaski** [comment]
It's easy, we could add import data dialog in the tools menu.
This is a nice job for new contributors.

**Comment by sten0** [comment]
Jonas Kvinge <notifications@github.com> writes:

> It's easy, we could add import data dialog in the tools menu.
> This is a nice job for new contributors.
>

Yeah, that would be even nicer! :-) From a Debian user perspective, the
ideal deadline for this one would be a stable Strawberry release that
includes the feature before 2021.  Ubuntu (and derivatives) will
probably ship a stable release without qt4 before then (meaning without
Amarok 2.x), so sooner might be better if they're the primary target
audience.

**Comment by v1993** [comment]
That would be great! I'd like to try strawberry out at some point, but manually migrating all my stuff from Clementine is too much.

**Comment by jonaski** [comment]
I think I spoke too soon.
For importing song statistics from Clementine we can add a import wizard directly in the tools menu, that's pretty easy.
But for converting the entire DB from Clementine including playlists, it needs to be an external program done when Strawberry is closed. While the collection view is updated from SQL, the playlists operate the exact opposite way, they are saved from the model to the DB. (the whole purpose of importing an entire DB would be to migrate playlists). The collection is better rescanned, but the playlists depend on the same database rowid's as the collection, so it needs to be migrated together for users who needs to keep playlists.
As for as I amarok 2, I thought they were using sqlite too, like Amarok 1.x did, but I see now that they now use mysql by default, so I don't want to make an integrated import wizard for that in any case. It needs to be entirely separate binary or script so we don't have to make the strawberry executable link to the mysql library.

**Comment by v-fox** [comment]
> For importing song statistics from Clementine we can add a import wizard directly in the tools menu, that's pretty easy.

Does that includes Clementine's star-ratings ? That would be nice. I've been using them to manually create playlists because those ratings make "approved" tracks stand out in collection lists. After migrating to Strawberry it's been a major hassle to search for all the "good" tracks.

**Comment by a-torgovitsky** [comment]
Is there a procedure for importing from Clementine before the wizard is implemented?

**Comment by jonaski** [comment]
I made a guide now to manually do it:

https://github.com/strawberrymusicplayer/strawberry/wiki/Import-collection-library-and-playlists-data-from-Clementine

**Comment by a-torgovitsky** [comment]
Thanks, it appears to have worked perfectly

**Comment by a-torgovitsky** [comment]
One thing that doesn't work is searching the collection.
I haven't been able to determine what the pattern is, but searches just don't return the correct album/artist/song!
Is it possible this is related to migrating the database from Clementine?

**Comment by jonaski** [comment]
Sorry, I forgot about the FTS tables in the guide. I will add it now.

**Comment by jonaski** [comment]
Fix the FTS table so search works. You don't need the clementine db.

`sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db`

```
DELETE FROM songs_fts;
INSERT INTO songs_fts (ROWID, ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsperformer, ftsgrouping, ftsgenre, ftscomment)
SELECT ROWID, title, album, artist, albumartist, composer, performer, grouping, genre, comment
FROM songs;
```

**Comment by a-torgovitsky** [comment]
Worked for me. Thanks again!

**Comment by lassana** [comment]
On macOS you need to use these paths:

```
ATTACH '/Users/user/Library/Application Support/Strawberry/Strawberry/strawberry.db' AS strawberry;
ATTACH '/Users/user/Library/Application Support/Clementine/clementine.db' AS clementine;
```

I also had issues with sqlite3 CLI tool (installed from homebrew):

```
sqlite> DELETE FROM 'songs_fts';
Error: no such module: fts5
```

So I ran these last commands in [DB Browser for SQLite](https://sqlitebrowser.org), it worked just fine:

```
DELETE FROM songs_fts;
INSERT INTO songs_fts (ROWID, ftstitle, ftsalbum, ftsartist, ftsalbumartist, ftscomposer, ftsperformer, ftsgrouping, ftsgenre, ftscomment)
SELECT ROWID, title, album, artist, albumartist, composer, performer, grouping, genre, comment
FROM songs;
```

**Comment by jmbreuer** [comment]
I have playlists put together from plain media files and streams in Clementine. I don't really use library/collection functionality.

I followed the `sqlite` database migration page, now the playlist tabs themselves show up in Strawberry, however, they are all empty. What can I do to get them imported correctly?

**Comment by atroxix** [comment]
> I made a guide now to manually do it:
> 
> https://github.com/strawberrymusicplayer/strawberry/wiki/Import-collection-library-and-playlists-data-from-Clementine

At importing playlist items the following error was thrown: ```Runtime error: NOT NULL constraint failed: playlist_items.url (19)```
I replaced ```filename``` with ```ifnull(url, '')``` - not sure if this is OK?

Also, any ideas how to import smart playlists from Clementine?

**Comment by ggiedke** [comment]
just as a hint for those brought here by search: the guide has been migrated to 
https://wiki.strawberrymusicplayer.org/wiki/Import_collection_library_and_playlists_from_Clementine
(as I just found out thanks to the internet archive).
