### ISSUE TITLE
Make icons bigger/easy to resize

### ISSUE THREAD

**Issue by echeloni2p** [strawberrymusicplayer/strawberry#250]
I do run strawb 0.6.3 from the strawb.org website as debian buster package. all good so far except one annoying useability issue:
the buttons for play/pause/stop are to small on a bigger screen (4k).
Please make the buttons bigger, or far better: resizeable.

thank you,
echeloni2p

**Comment by jonaski** [comment]
I don't have a 4K screen so I have not looked to much into this, but Qt has some Hi-DPI options.
I got a standard HD TV 1080p, and works fine there. I will probably look more into this when I purchase a new TV.

**Comment by Jaki143** [comment]
Would be great if all icons would be resizable (maybe use KDE settings as default). This is especially important for people with sight issues (e.g. my "small" icons are set to 32). The Play/Pause etc. buttons and the playlist icons are way too small and even the sidebar icons in "big" mode could really be bigger (font size too).

**Comment by jonaski** [comment]
I'm working on this now.
I'll make individual icon size setting for both play control buttons, playlist buttons, and all the different ones in the left panel.
It looks to be working pretty good, even the analyzer scales nicely. It's just ridiculous that it hasn't been done before.
Think maybe we could at least bump the default size of the playlist buttons a bit, they are only 16 now.
