### ISSUE TITLE
Playlist song number

### ISSUE THREAD

**Issue by TarsolyGer** [strawberrymusicplayer/strawberry#253]
Hi, I am just transitioning from Winamp (yeah, in 2019), and I am really missing the ability to show the number of the track on the playlist from the start of the row.
It would be much more informative for me (especially that I like to prepare extensively long playlist) to see what's the place of a track in the playlist than seeing what place it takes on its original album (which the current 'Track' option does).

**Comment by jonaski** [comment]
You can queue the entire playlist with CTRL + A, then CTRL + D. Don't know if that helps or not.
