### ISSUE TITLE
Strawberry closes unexpectedly after refocusing on Wayland (Sway)

### ISSUE THREAD

**Issue by xPMo** [strawberrymusicplayer/strawberry#254]
**Describe the bug**
If Strawberry's window is unfocused for an extended period of time, then refocused, Strawberry will crash.

**To Reproduce**
1. Launch Sway
2. Launch strawberry
3. Play a track
4. Switch from the workspace strawberry is on
5. Do not focus the workspace for about 3 minutes (2m30s was too short, 2m40s is about the threshold)
6. Switch back to strawberry (either `swaymsg '[app_id=strawberry]' focus`, or switch back to the workspace).

**Expected behavior**
Strawberry is focused on the workspace.

**Actual behavior**
The window is briefly shown before disappearing. The process exits.

**System Information:**
 - Operating system: Arch Linux, sway version 1.2-rc1-19-gff7d979d (Aug 20 2019, branch 'makepkg')
 - Strawberry Version: Strawberry 0.6.3

**Additional context**
This seems to only happen if a track is playing, hence why I added it in the reproduction steps.

[Strawberry and Sway log files](https://gist.github.com/xPMo/8b4ea1c1136a8bc77529ade7b0364449). Sway was launched with the default config: `-c /etc/sway/config`. Strawberry was called with `--verbose`, and it and `env` were piped to `ts -s` for timestamps.

**Comment by jonaski** [comment]
Can you run it with gdb and do a backtrace when it crashes?

**Comment by xPMo** [comment]
I get `No stack.` It doesn't crash, it catches the error, cleans up and exits (albeit with return code 1).

**Comment by jonaski** [comment]
I think this is a Qt / wayland issue, there is nothing in the strawberry source that should cause it to exit with 1. It doesn't exit cleanly, as then you would see a different output at the end.

**Comment by xPMo** [comment]
Alright, I'll forward this to Sway and see if they have any insight. It's odd that Strawberry is the only Qt app I have problems with.

**Comment by ascent12** [comment]
I'll post a link to my comment here: https://github.com/swaywm/sway/issues/4506#issuecomment-575015824
It should be relevant.

**Comment by jonaski** [comment]
I doubt very few programs does the same continuous updating in the way that a music player does, album cover fading, track progress, moodbar, metadata updating, etc. We override paintEvent() in a lot of places. We also emit the dataChanged() signal from the model to update the view in the playlist when metadata is changed. That's all I can think of.

**Comment by jonaski** [comment]
https://bugreports.qt.io/browse/QTBUG-81504

**Comment by xPMo** [comment]
Now that since Qt5 is commercial-only, either individual users or some fork of the project will need to fix this.

The following is a script to patch qt5-wayland which I got from @progandy.

```sh
sed -i '/::handleUpdate/{n;n;n; s/^/if(mWaitingForFrameCallback) return;/ }' src/client/qwaylandwindow.cpp
```

[Or as a prettier .patch](https://github.com/swaywm/sway/files/5976312/0001-Fix-surfaces-updating-without-a-frame-callback.patch.gz)

Currently it seems to fix the issue.

**Comment by NotHanSolo1** [comment]
a similar issue occurs on the cider apple music client
