### ISSUE TITLE
Add support for www.radio-browser.info

### ISSUE THREAD

**Issue by stefano-b** [strawberrymusicplayer/strawberry#257]
Adding support for [radio-browser.info](https://www.radio-browser.info) would be a nice feature to have.
It is a service that collects radio streams from all over the world.

A couple of example of apps that use this service are [Gradio](https://github.com/haecker-felix/gradio) and [this plugin](https://github.com/fossfreedom/radio-browser) for Rhythmbox.

**Comment by jonaski** [comment]
I'm closing this as I can't prioritize this now and no-one else has shown interest doing it.

**Comment by Cwpute** [comment]
Just showing my interest for such a feature !
