### ISSUE TITLE
Playback halts due to TIDAL stream expiration

### ISSUE THREAD

**Issue by RomanHargrave** [strawberrymusicplayer/strawberry#270]
**Describe the bug**
When resuming playback after some wait, or starting the next (prebuffered) track after having played a long track (in excess of ten minutes, give or take), the TIDAL API closes the stream and responds with error 403.

**To Reproduce**
1. Create a playlist with at least two tracks.

2. Play the first track for a moment, pause, wait ten to fifteen minutes, and resume playback. Playback will continue briefly before completely halting and notifying the user that TIDAL responded with error 403. No further details are given.

**Expected behavior**
Strawberry should re-request the audio and seek to the position if the underlying stream has expired.

For situations where the next track has already expired, tidal should re-request the track and begin playing.

An even more robust solution would be to eagerly cache audio track-at-a-time (in the same manner that DSub does with \*sonic) instead of portions of that track so that Strawberry does not have to rely upon the TIDAL to keep streams fresh.

**Screenshots:**
I will see about collecting some when I am home.

**System Information:**
 - Operating system: Debian Buster, Debian Bullseye
 - Strawberry Version: development, 0.6.4, 0.6.3

**Additional context**
I am using the API token for what I believe is android - `P5X...Dy6`

**Comment by jonaski** [comment]
Do you know how long they last?

**Comment by RomanHargrave** [comment]
It seems like about ten minutes. I haven't measured exactly.

**Comment by RomanHargrave** [comment]
Here's a screenshot of the issue. I had paused this and then gone for about an hour long conference call. Though I should stress that this has happened after much less time has elapsed in the past.

![forbidden](https://i.imgur.com/Zi8TRrY.png)

**Comment by jonaski** [comment]
I notice that "-1" is returned for "playTimeLeftInMinutes" in the stream url request, which is sort of weird considering that it's actually expiring.
So we have to make it a setting, or hard-code it in the source.

**Comment by RomanHargrave** [comment]
I wonder if that is a peculiarity the Android client ID - strange behavior has certainly been observed with certain IDs. When you observed that response, what API Client ID were you using?

**Comment by zeddyblue** [comment]
I am not sure if this is the same issue, but I started getting a "Host requires authentication (204)" error when streaming from tidal, randomly, regardless of song length. When i check in settings it still shows logged in. Logging out and then back in sometimes fixes the issue sometimes it doesn't. This only started happening after upgrading to 0.6.8.

**Comment by jonaski** [comment]
I've removed tidal support. Login does not work anymore, see https://github.com/strawberrymusicplayer/strawberry/issues/369

**Comment by gbrauen** [comment]
I think this should still be an open issue. The removal of Tidal support was reversed and this problem persists.

When the forbidden response is received, the alert is shown and when you click ok (the only option), strawberry crashes. Is avoiding a program crash really just an enhancement?

Version 0.8.3 on Ubuntu 20.04

**Comment by jonaski** [comment]
I don't think this is a problem anymore if you use OAuth. I can't reproduce this.
This bug report does not say anything about a crash. If it crashes you need to do a GDB backtrace and open a issue for it.

**Comment by jonaski** [comment]
I just realized that it was when pausing a track, it should be able to send a new stream url request in that case.

**Comment by gbrauen** [comment]
Thanks for the update. Running with 0.8.3 now, Strawberry does not always shut down when the "forbidden" alert is closed. That was consistent behaviour before and I have seen it with 0.8.3 but have had a couple of occurrences more recently with Strawberry continuing to run.

**Comment by jonaski** [comment]
I hard-coded re-requesting the stream URL after 30 seconds when resuming playback, it doesn't hurt to re-request the stream URL anyway. But I was able to resume playback and play the rest of the song even after 30 minutes with Tidal, but it's better to be safe.
