### ISSUE TITLE
(Windows) WASAPI support

### ISSUE THREAD

**Issue by ghost** [strawberrymusicplayer/strawberry#283]
Hi,

I absolutely love Strawberry's interface, it's so far the best I've found to manage my library. However, I have a big problem with the output, I use a DAC/AMP and I get very bad clicks/pops if I don't use WASAPI with any software, I had the same problem with foobar2000 before I started using the WASAPI component. It's heartbreaking for me because this software looks really good but I badly need a WASAPI output.
Is there any hope for that kind of option in the future?

Best regards.

**Comment by jonaski** [comment]
WASAPI was just added in GStreamer 1.16.0. It's a bad plugin, meaning they don't have the same quality.
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-plugin-wasapi.html
I added the plugin to the Windows builds. So if you try 0.6.5.31 or later it should have the option in the settings. I didn't get it to work though.
https://builds.strawberrymusicplayer.org/windows/

**Comment by dulcifer** [comment]
Thanks a lot for trying and sorry for the delay, I wasn't home. 
Unfortunately, I can't make it work either, I get this error message: "could not open resource for writing".
Is your WASAPI tweak in exclusive mode or shared mode? I don't know if it has anything to do with my error message but the exclusive mode is the one that works great with my AMP/DAC.

**Comment by jonaski** [comment]
I found the problem. The problem is a missing call to CoInitialize in the main thread, because gst_init() is done in a concurrent thread to speed up startup, CoInitialize won't called for the main thread which is necessary for the WASAPI plugin.

**Comment by jonaski** [comment]
I applied a patch adding CoInitialize() to gst_wasapi_util_get_device_enumerator() in gstwasapiutil.c.
Playing using wasapi now works, but any second state change after play blocks.
Looks like a gstreamer issue to me. gst_element_set_state is done in concurrent runs too, but I've tried to run everything in the main thread and the issue persists.

**Comment by jonaski** [comment]
I was hoping to fix this before a new release, but I will remove the plugin from the release, and readd it so we can do more testing after the release.

**Comment by jonaski** [comment]
Looks like there is a bug in when using "exclusive" mode, issue is here:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/868

**Comment by jonaski** [comment]
I removed exclusive and it seem to work now.
However, it seems that the wasapi support in gstreamer is a bit unstable yet, see related issues here:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues?scope=all&utf8=%E2%9C%93&state=opened&search=wasapi

**Comment by jonaski** [comment]
Windows releases 0.6.6, 0.6.7 and 0.6.8 had some stability issues caused by the GStreamer WASAPI plugin, version 0.6.8 has been rebuilt and repackaged as 0.6.8.11.g3791d11 with the WASAPI plugin removed and a added Qt style plugin, this solves the stability issues and also adds a nicer GUI appearance.
It can be downloaded now from https://www.strawberrymusicplayer.org/
The problem can also be solved by setting the Output in the backend setting to "Output to a sound card via Direct Sound" or by deleting libgstwasapi.dll from the gstreamer-plugins directory.

**Comment by jonaski** [comment]
WASAPI is still too unstable to be added back. Someone needs to do a backtrace on Windows and report it to GStreamer.

**Comment by jonaski** [comment]
I think I found the problem now.

**Comment by jonaski** [comment]
Looks like it's working fine now!

**Comment by jonaski** [comment]
It seem to be still crashing, even though it's much better. ie: it crashes when switching from a local file to a http stream.

**Comment by jonaski** [comment]
Looks like the registry fix might have fixed the remaining problems.

**Comment by jonaski** [comment]
I still get crashes, but pretty rarely.

**Comment by tomatgithub0** [comment]
Sorry for replying to an old thread, is the exclusive mode stable enough for re-enablement now?
