### ISSUE TITLE
last.fm information in context tab

### ISSUE THREAD

**Issue by martouss** [strawberrymusicplayer/strawberry#289]
In clementine in the "**Song Info**" tab, we can see last.FM **total listeners**, **total plays**, and **your scrobbles**. In addition, we can see the song's **tags** in last.FM as you can see below.  

![Screenshot_20191101_191238](https://user-images.githubusercontent.com/5202895/68036847-bc60ab00-fcdb-11e9-9f38-0d69536fdd08.png)

**Comment by jonaski** [comment]
I'm closing this since I don't have time to prioritize it. Someone else is free to make a proposal for this feature in a PR.
