### ISSUE TITLE
Get album tagged as "Explicit" when showing Tidal results

### ISSUE THREAD

**Issue by Fef0** [strawberrymusicplayer/strawberry#291]
**Is your feature request related to a problem? Please describe.**
When searching for some albums, I have no idea how to notice what album is the "Explicit" version and what isn't. 

**Describe the solution you'd like**
It would be great to just show something like [E] after the album's name, you can grab those information through Tidal API.

As always, I love this project!

**Comment by jonaski** [comment]
Done now https://github.com/jonaski/strawberry/commit/b7d360d850a661fb83a81969892652807cf44897

**Comment by jonaski** [comment]
I've removed tidal support. Login does not work anymore, see https://github.com/strawberrymusicplayer/strawberry/issues/369

**Comment by pnomolos** [comment]
@jonaski As Tidal support is working again, is this still supposed to work?  If so, it isn't properly.  

I'd also like to extend this suggestion to differentiate "Master" albums.  For example, search for "in the name of gee still most hated" - there are four results for each disc.  In the official Tidal client there's only three results, so I'm not sure what the fourth is, but the three listed are "clean, explicit, explicit master"

I'm not sure what your "tidal subscription status" is, but if you need my help please let me know and I'll get you any information you need.

Thank you!

**Comment by jonaski** [comment]
No, it the explicit change was reverted, I can redo it.

As far as I can see,  "Master" isn't shown in the API data for Tidal.
As an example, for Pink Floyd - Endless Rivers. Tidal returns 3 different versions, 2 deluxe ones and one regular. All 3 of them show as "High res", 2 of them plays at 48/24, while one of them plays just at 44/16.

Here are the 3 versions, as you can see there isn't anything useful to distinguish them by that can be appended to the album title, only the "id" differs.

`{"allowStreaming":true,"artist":{"id":9706,"name":"Pink Floyd","type":"MAIN"},"artists":[{"id":9706,"name":"Pink Floyd","type":"MAIN"}],"audioModes":["STEREO"],"audioQuality":"HI_RES","copyright":"© 2014 Pink Floyd (1987) Ltd under exclusive licence to Parlophone Records Ltd, a Warner Music Group Company","cover":"4775090d-9ffa-4a31-9acf-22802deedffd","duration":3907,"explicit":false,"id":37550882,"numberOfTracks":21,"numberOfVideos":0,"numberOfVolumes":1,"popularity":37,"premiumStreamingOnly":false,"releaseDate":"2014-11-07","streamReady":true,"streamStartDate":"2014-11-10T00:00:00.000+0000","title":"The Endless River (Deluxe)","type":"ALBUM","upc":"825646202553","url":"http://www.tidal.com/album/37550882","version":null,"videoCover":null}`

`{"allowStreaming":true,"artist":{"id":9706,"name":"Pink Floyd","type":"MAIN"},"artists":[{"id":9706,"name":"Pink Floyd","type":"MAIN"}],"audioModes":["STEREO"],"audioQuality":"HI_RES","copyright":"2014 Pink Floyd (1987) Ltd under exclusive licence to Parlophone Records Ltd, a Warner Music Group Company","cover":"d38f7182-0db6-4242-82b6-aaccd08935ab","duration":3907,"explicit":false,"id":68733189,"numberOfTracks":21,"numberOfVideos":0,"numberOfVolumes":1,"popularity":34,"premiumStreamingOnly":false,"releaseDate":"2014-11-07","streamReady":true,"streamStartDate":"2014-11-10T00:00:00.000+0000","title":"The Endless River (Deluxe)","type":"ALBUM","upc":"825646202393","url":"http://www.tidal.com/album/68733189","version":null,"videoCover":null}`

`{"allowStreaming":true,"artist":{"id":9706,"name":"Pink Floyd","type":"MAIN"},"artists":[{"id":9706,"name":"Pink Floyd","type":"MAIN"}],"audioModes":["STEREO"],"audioQuality":"HI_RES","copyright":"2014 Pink Floyd (1987) Ltd under exclusive licence to Parlophone Records Ltd, a Warner Music Group Company","cover":"2232242c-e437-445f-a4ee-43820f0b95cf","duration":3177,"explicit":false,"id":68732950,"numberOfTracks":18,"numberOfVideos":0,"numberOfVolumes":1,"popularity":25,"premiumStreamingOnly":false,"releaseDate":"2014-11-07","streamReady":true,"streamStartDate":"2014-11-10T00:00:00.000+0000","title":"The Endless River","type":"ALBUM","upc":"825646184729","url":"http://www.tidal.com/album/68732950","version":null,"videoCover":null}`
