### ISSUE TITLE
Sort song titles in alphabetical order

### ISSUE THREAD

**Issue by PatGoup** [strawberrymusicplayer/strawberry#295]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]I have a lraeg library of music and I find it easier to look for a specific song for an artist by scrolling down the artist/song library panel

**Describe the solution you'd like**Sort the songs in alphabetical order

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here.Being visually impaired, very near sighted, having the songs in alphabetical order helps me find what I want

**Comment by jonaski** [comment]
I don't think I want this, I think the best way to sort is by track like we have it.

**Comment by PatGoup** [comment]
If I do a "Group BY" "Artist" only there is no album detail.  So why not sort by song title instead of track.  Especially if there are multiple albums.  Then there are multiple track 01, track02, track 03, etc_

**Comment by jonaski** [comment]
I agree that that would make more sense.
