### ISSUE TITLE
Spectrum-based fingerprinting as the main track identification in database and playlists

### ISSUE THREAD

**Issue by v-fox** [strawberrymusicplayer/strawberry#296]
### Is your feature request related to a problem? Please describe.

The biggest hassle in a music collection and in the clementine in particular is tethering to file paths and names: rename or move one directory and mess up all your playlists containing any of affected files.

### Describe the solution you'd like

This can be completely solved by going semantic: using spectral meta-data as fingerprinting stamps instead of names, tags and encoding formats. In particular, the glorious moodbar can double for that. IF it could guarantee reproducible stamps for the same file under all circumstances.

### Describe alternatives you've considered

There was [a Clementine pull request](https://github.com/clementine-player/Clementine/pull/5135) for limited type of fingerprinting but it does not account for whole content and only tracks renames of files under unchanged directory structures.

### Additional context

This would also allow for copying files at will while preserving original playlist ordering. Adding a tag as secondary identifier may allow tracking "relations" between files such as down-converted transcodings for mobile devices (like FLAC->AAC/OPUS) inheriting ID of their original in a tag, so they could be put in the same spot in a playlist on a different device. That would immensely help with sharing playlists as new age gigantic high-quality alternatives to "mix tapes" of the past.

Especially if a compatible Android player would manifest or at least a script for generating legacy playlists out of that meta-data after "settling" files in whatever silly directory structure mobiles have (like being unable to use ':' in file-paths or forcibly lumping gigabytes of tracks together by artist/title in an incomprehensible mess).

**Comment by v-fox** [comment]
I probably should have elaborated more on the proposed implementation:
* Instead of filename use unique hash (with diverse enough algorithm, ideally, one that could be changed in future, so having "algorithm ID" or "protocol version" somewhere would be nice) of moodbar "file" (not actual file, a "binary tag" in the database that is cached as a file and/or as tag in supported formats). Moodbar-generation algorithm also could be changed in the future that would change hashes, so particular pair of moodbar function and hashing algorithm would constitute a "protocol version".
    * In addition to moodbar as primary defining characteristic hashed data may also include other defining informations, such as format (PCM, DSD, MIDI, etc.) and format-specific parameters (bit-depth, sampling rate, exact MIDI type, etc.), but NOT any changeable information, such as other meta-data (name, tags, filesystem properties, etc.). Although it would be nice to know if 2 files result in bit-perfect or near-perfect spectrum recreation.
    * In case of synthesize-able music such as MIDI (old console rips, composition master-copies, etc.), spectrum would depend on synthesis settings, so notes should be used instead.
* Use that hash as main identifier in the database but also cache it in "primary" fingerprinting tag inside files where it's possible. Also use "secondary" tag with copy of the hash for "source file".
    * Maybe by using these pairs or even adding 3rd tag for "list of copies/versions for the same composition", player could show "related" files and percentile comparison of their "spectral similarity" by comparing them after such identification. That could allow finding duplicates and determining "superior version".
* Format playlist files as \<position>:\<primary>:\<secondary or null>.
    * It's unclear how to include data for tag-less files or if it's necessary. But having the option to copy other meta-data from the database for files, that are unable to contain it within themselves, would be nice. That meta-data may include moodbar cache-files themselves, ratings, playback statistics, lyrics/comments and cover art.

**Comment by b4n4n4p4nd4** [comment]
Can agree. Fingerprinting would be useful for finding duplicates of a song in different locations and formats.

**Comment by RomanHargrave** [comment]
I'd like to add that in some cases, music collectors may encounter a scenario where two albums contain identical tracks. In this case, some people may find it desirable to have duplicate tracks.

**Comment by b4n4n4p4nd4** [comment]
> 
> 
> I'd like to add that in some cases, music collectors may encounter a scenario where two albums contain identical tracks. In this case, some people may find it desirable to have duplicate tracks.

Yes, it would be imprudent to take automatic actions on the duplicates. Just having the knowledge of the duplicates would be enough to let the user make a judgement themselves.

**Comment by RomanHargrave** [comment]
> > I'd like to add that in some cases, music collectors may encounter a scenario where two albums contain identical tracks. In this case, some people may find it desirable to have duplicate tracks.
> 
> Yes, it would be imprudent to take automatic actions on the duplicates. Just having the knowledge of the duplicates would be enough to let the user make a judgement themselves.

Of course, of course. I think my primary concern was to warn against the use of fingerprint as a unique index.

**Comment by b4n4n4p4nd4** [comment]
A composite key between the fingerprint and metadata about where the song purports to be from may be enough for uniqueness. In absence of adequate discretionary detail, it would just flag potential duplicates.

**Comment by Victor239** [comment]
This would be extremely useful for syncing playlists across multiple devices also.

**Comment by jonaski** [comment]
I stated implementing fingerprinting in the database now, it takes much longer time to scan the collection, so I guess it should be optional and off by default since I imagine lot's of users will complain oherwise. I guess it takes 10 times longer or something to do a full scan.
I also ran into the problem pointed out by @RomanHargrave when running it on my collection, so I guess combining it with some tags would be necessary, it will still solve the problem with losing playcounts, ratings and playlists when files are moved on disk.

**Comment by jonaski** [comment]
There is a PR open for this now if anyone can test.: https://github.com/strawberrymusicplayer/strawberry/pull/721
I have not done any testing with CUE yet.

In the case where there are duplicate audio files in the collection, ie.: different albums with identical songs and the fingerprint is identical, it won't use the existing song in the DB unless the file no longer exists in the different path, so that's not a problem. Didn't think of it when I wrote about it earlier.
