### ISSUE TITLE
Make context scalable and adjustable

### ISSUE THREAD

**Issue by v-fox** [strawberrymusicplayer/strawberry#299]
**Is your feature request related to a problem? Please describe.**

Album art is small and not prominent enough. Option to show full size is too hidden and too close to "unset" button.

**Describe the solution you'd like**

* Scale for entirety of width of the left panel.
* Show full-size on single or double click.
* Allow enlarging "pretty" notifications and sys-tray pop ups to show art better.
    * Maybe even add moodbar line on bottom edge (full-length or width between end of art and end of notification area).

**Describe alternatives you've considered**

Clementine scales art in panel better and shows full-size on click. With song info overlay too but I prefer keeping them separate.

**Comment by jonaski** [comment]
I've added a separator between unset cover and show full size.
Also, you can now show full size on double click. I don't really want the single click.
The reason the playing widget can't be made smaller is due to the context being fixed size (if I remember correctly).
The whole context needs to be rewritten to be scalable and customizable.

**Comment by v-fox** [comment]
For me, no amount of clicking shows it.

Well, the widget is small enough for me. I would prefer it to be larger. Both, screen overlay and sys-tray pop-up. But I get that it's old legacy code that is easier to replace then to modify.

By "context" you mean Context menu in left panel ? Unlike other menus, it does not use full width for art. But squeezing panel's menu-selection buttons would be nice, indeed.

Moreover, a friend of mine likes to use "vertical" layout in style of AIMP and WinApm, especially when he flips the monitor 90 degrees, so he was asking to add request for bettering such layout. For example: options to hide left panel altogether and using more than 1 line per track.

**Comment by jonaski** [comment]
You can select the option fit "cover to width" that will make it larger using the large album cover mode.

**Comment by v-fox** [comment]
"Cover to width" does not work for "Context" menu, only others.

**Comment by jonaski** [comment]
I've made the context album cover scale to the width now. https://github.com/strawberrymusicplayer/strawberry/commit/3fdbe8457375caf5a06a89e2ae23e06390243588

**Comment by alekksander** [comment]
thanks!
