### ISSUE TITLE
New analyzer

### ISSUE THREAD

**Issue by v-fox** [strawberrymusicplayer/strawberry#300]
**Is your feature request related to a problem? Please describe.**

As expressed previously, like https://github.com/jonaski/strawberry/issues/155#issuecomment-492394320
Current "analyzer" may look pretty at first but it doesn't actually analyze much, it takes up a lot of width with little purpose.

**Describe the solution you'd like**

I'm not sure what would actually be "better". Maybe:
* Scale its size better and recolour blocks either by volume or by frequency ranges.
* Reallocate moodbar in its stead and make it heftier.
* Use something more "scientific" or prettier.

**Describe alternatives you've considered**

I use [Calf](https://calf-studio-gear.org/)'s built-in analyzer and it has its own shortcomings.
[LSP](https://lsp-plug.in/?page=video) is much fancier.
And then there is [Sonic Visualiser](https://sonicvisualiser.org/).

**Additional context**

My calf-analyzer setting (translucent due to desktop compositing):
![Calf-analyzer](https://user-images.githubusercontent.com/362763/68630219-6cb68680-0508-11ea-911f-dc5cd3ac72a2.png)

**Comment by alekksander** [comment]
i already once suggested waveform seekbar would be probably best way to go, but what i also miss is peak meter (doesn't have to be fancy, even simple few pixel wide symbol could indicate clipping) and real (informative) spectrum analyzer. this one is probably the best i've seen in regular desktop music player:
![Screenshot_20191114_131733](https://user-images.githubusercontent.com/3148302/68856603-308a4e00-06e1-11ea-9a94-5194778e0410.png)

**Comment by jonaski** [comment]
I have fixed the analyzer we have now, we don't have resources/contributors to write a new one at this time, so unfortunately I'm closing this.

**Comment by Michele64** [comment]
maybe something like "Waveform Seekbar" as in DeaDBeeF?
https://github.com/cboxdoerfer/ddb_waveform_seekbar

**Comment by jonaski** [comment]
Looks nice
