### ISSUE TITLE
Down/up-mix when sound system does not

### ISSUE THREAD

**Issue by v-fox** [strawberrymusicplayer/strawberry#301]
**Is your feature request related to a problem? Please describe.**

I launched game-rip of [famous](https://en.wikipedia.org/wiki/Jeroen_Tel) [Title theme from Robocop 3 on NES](https://www.youtube.com/watch?v=bq-9-GcVM_o) only to have my left ear violated by the lack of remixing of a mono stream into a stereo stream. In JACK mono streams only create one port to remap, so intermediate stereo mixer processing has to be used to "remix to midrange".

**Describe the solution you'd like**

PulseAudio may remix by itself, [ALSA require explicitly stating type of channel layout at runtime](https://github.com/jonaski/strawberry/issues/262) but JACK does not define its current layout and can't support several, apps are required to do everything themselves, at best they could check number of available output channels that can be remapped at will.

So, option for explicitly stating desired layout and/or use number of DAC"s output channels instead of track's channels might help.

**Describe alternatives you've considered**

Clementine has does it somehow but it's probably just always forcing stereo.

I'm hoping to replace JACK with [PipeWire](https://github.com/PipeWire/pipewire) soon but I will probably just use its JACK/PA/ALSA compatibility to mix things the same way. But it may provide PA's simplifications with JACK's utility, so even while posing as PA, with its layouts and internal remixing, it may allow redirecting streams for intermediate processing without loss in quality. With GStreamer Strawberry may even support it natively without much work.

**Comment by jonaski** [comment]
This should be done as part of #262.

**Comment by v-fox** [comment]
I've noticed that mono issue can be worked around by opening Tools->Equalizer and enabling "stereo balancer" with default, neutral balancing. I doubt that this will have much influence with more complex setups but at least mono streams can be listened fine with JACK.
