### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by gerroon** [strawberrymusicplayer/strawberry#303]
Hi

It would be very good if it is possible to change the font sizes for the playlist, ui items etc. This is especially important for people with sight issues, like elderly folks. For instance my mom never can use thisa pp at all because the fonts are insanely small for people with sight issues and there does not seem to be a way to change them in the settings.

Thanks

**Comment by alekksander** [comment]
what os? isn't this configurable in system wide settings?

**Comment by gerroon** [comment]
This is on Linux and Windows.  

I am sure there are ways to set systemwide (which assumes that fonts should be set by the system at all times which cant be useful in all cases) but apps generally offer font scaling in their settings.

**Comment by jonaski** [comment]
If you are using a non-KDE distro you usually need to use an utility called qt5ct to change theme settings, styles, fonts etc. But I'm not sure the font settings there will affect the playlists.
On Windows I don't know how it works.

**Comment by gerroon** [comment]
Thanks I will take a look at it.

**Comment by cipricus** [comment]
Lyrics font is the setting I miss most compared to Clementine. Or am I missing it (meaning failed to see it)?

**Comment by jonaski** [comment]
Changing font in qt5ct affects both playlist and lyrics (although I see there is a problem with the top title text over the album cover being fixed).

![image](https://user-images.githubusercontent.com/10343810/75717760-0ed5c680-5cd2-11ea-882b-fe9885ff843f.png)

**Comment by gerroon** [comment]
The thing is that what if the user does not want to change the font size for every QT app and only for single app?

**Comment by NucleaPeon** [comment]
Change the menu item/desktop file to include a variable assignment in bash or use a script to do so?
https://unix.stackexchange.com/questions/202588/how-can-i-set-the-default-font-size-for-all-qt5-apps

    QT_SCALE_FACTOR=... strawberry

**Comment by ClintEsteMadera** [comment]
@jonaski I need to increase the font size (specially at the playlist) in MacOS. Is this supported / planned at all?

**Comment by mirko77** [comment]
> @jonaski I need to increase the font size (specially at the playlist) in MacOS. Is this supported / planned at all?

Same issue here. The playlist and collection font is tiny on a 13" MacBook

**Comment by kostabekre** [comment]
> @jonaski I need to increase the font size (specially at the playlist) in MacOS. Is this supported / planned at all?

Same for Windows. I can change text font and size for "Context" window but playlist's text is small and Japanese symbols are not pretty. Plus when DPI is increased, the current song is blurry.
![изображение](https://user-images.githubusercontent.com/50672363/211153966-4dfecff2-672b-42e2-80a6-81d4dc311bc4.png)

**Comment by mercster** [comment]
Yeah, I was using Strawberry from Ubuntu 23.10's repos and the font was fine.  I added the PPA (looks like it pulled in some qt6 package as well?) and now the font is tiny.  Strawberry was previously using a font size that was in line with the rest of the desktop, now it's not.  None of my other QT apps (I don't know if I have any other qt6 apps) need a font adjustment, so... not sure what to do with Strawberry.

**Comment by mercster** [comment]
I tried using qt6ct to change the font size, but Strawberry isn't honoring that value for whatever reason.

**Comment by quidamphx** [comment]
I use system-wide font scaling in Fedora instead of Wayland Fractional Scaling to make things more usable at high DPI. Strawberry doesn't seem to honour these settings, while everything else in the OS does. Too bad there isn't a font size option, it makes Strawberry very difficult to use.

**Comment by klondikemarlen** [comment]
@quidamphx Setting `Exec=env QT_SCALE_FACTOR=1.5 strawberry` worked perfectly for me! I run my Ubuntu system with "large font" accessibility setting, but Strawberry doesn't seem to respect that. Hopefully, this will just be a UI setting someday.

**Comment by klondikemarlen** [comment]
Update on setting `Exec=env QT_SCALE_FACTOR=1.5 strawberry` on Ubuntu 24.10, this settings gets wiped when Strawberry updates.

**Comment by klondikemarlen** [comment]
Since this is still an issue for me, I wrote this script `~/fix-strawberry-font-scaling.sh`, that I can run each time Strawberry updates.
```sh
#!/usr/bin/env bash
cat $(basename "$0")
sudo sed -i 's/^Exec=strawberry %U$/Exec=env QT_SCALE_FACTOR=1.5 strawberry %U/' /usr/share/applications/org.strawberrymusicplayer.strawberry.desktop &&
  sudo update-desktop-database /usr/share/applications
```

(I'm concerned that more aggressive solutions will eventually result in breaking strawberry and me have no clue that I have some custom launcher or something that doesn't match new strawberry release)
Hopefully someday this'll be a configurable option.
