### ISSUE TITLE
Move the currently playing song to the top if the playlist manualy shuffled

### ISSUE THREAD

**Issue by gerroon** [strawberrymusicplayer/strawberry#304]
Hi,

Currnetly, if the user shuffles the playlist (Ctrl-H) the currently playing song may end up somewhere in themiddle or at the bottom, however if the list is manually shuffled it would make sense to put the currently playing song at the top so the list plays downward, although this might not be so important if the user also has play shuffle enabled also. In anycase it would be helpful if this was an optional thing.

thanks

**Comment by jonaski** [comment]
Makes sense I guess
