### ISSUE TITLE
auto scrolling lyrics

### ISSUE THREAD

**Issue by rickysarraf** [strawberrymusicplayer/strawberry#308]
**Is your feature request related to a problem? Please describe.**
Auto-scrolling of the lyrics is something I've used years ago in Amarok. I believe it was available in Clementine too. But I am not very sure because after Clementine went unmaintained, I lost interest in the feature.

**Describe the solution you'd like**
It would be nice to have auto-scrolling for the lyrics. Nicer would be if the current line is highlighted.

**Describe alternatives you've considered**
NA

**Additional context**
Amarok and Clementine may have had the feature in the past.
Some of the Android Music players have this feature too.
I am not sure of Microsoft Windows or Apple OS X

== Strawberry
Using version 0.6.6 AppImage bundle.

**Comment by jonaski** [comment]
I'm not sure how easy this can be done, I don't recall Clementine having it either.

**Comment by rickysarraf** [comment]
Yes. I must have mixed it with Kodi/XBMC, which does scroll :-)

But this got me curious to do a quick search and I came across:
https://github.com/naaando/lyrics
Not sure how mature this is. 

But now, there are 2 implementation that can be looked at. `naaando/lyrics` and `kodi`

**Comment by jonaski** [comment]
I don't have time to prioritize this, and due to few contributors I'm closing this.
