### ISSUE TITLE
Subsonic: Recently added (filter)

### ISSUE THREAD

**Issue by tmikaeld** [strawberrymusicplayer/strawberry#314]
There's a few built in filters in Subsonic, which I use frequently on mobile players and would love to have on the desktop too.

They are: Random | Recently added | Starred | Top rated | Most played | Recently played.

**Comment by jonaski** [comment]
I'm closing this since this is only a minor detail, and I don't have time to prioritize it. Anyone else is free to make a proposal for a change in a PR.
