### ISSUE TITLE
Strawberry crashes when editing track information

### ISSUE THREAD

**Issue by gianlucapettinello** [strawberrymusicplayer/strawberry#319]
**Describe the bug**
Strawberry crashes with segmentation fault when trying to edit the info of the currently playing track. Also when trying to complete tags automatically.

**System Information:**
 - Operating system: Archlinux
 - Strawberry Version: 0.6.7 (but also 0.6.6)

**Comment by jonaski** [comment]
I can't reproduce any crashes here

**Comment by jonaski** [comment]
Any specific tags that you change? Or does it happen with all?

**Comment by gianlucapettinello** [comment]
As long as I click the edit tags the program crashes

**Comment by jonaski** [comment]
Does it happen from the playlist menu or from the collection? What file format? Does it happen immediately before the dialog opens?

**Comment by gianlucapettinello** [comment]
It happens from the playlist, mp3 format and it happens before the dialog opens. Very rarely it doesn't crash but it is very seldom. Before the crash there is a console msg that says that a qtcontrol order is wrong. I can post the exact output before segmentation fault tomorrow

**Comment by gavinhoward** [comment]
After looking at the Arch `PKGBUILD` for `strawberry`, I noticed that it is using the system `taglib`. @jonaski, I would bet that is the reason you can't reproduce. The version is `1.11.1`. I am attempting to build `taglib` at that version and then reproduce.

**Comment by gavinhoward** [comment]
Hmm...I managed to build `taglib` at that version and couldn't reproduce it. I also tried applying the `ogg` file corruption patch, and that did not reproduce it.

**Comment by jonaski** [comment]
I suspected that too so I compiled using the system version, however I use opensuse tumbleweed and they use a commit from 25/07/2019 so thats what I tested. Worked fine.
However I doubt it has to do with taglib, as then then it would probably crash in other places too.
I think @gianlucapettinello needs to do a backtrace in gdb so we know more.

I did some changes to the tagreader a while back to remove use of deprecated functionality in taglib, the commit is here: 
https://github.com/jonaski/strawberry/commit/b0a2edf5fa5d54efb5614befcecc824a16ac190a#diff-e36c9ba0d29475927d2df5b9e4a62240

**Comment by gavinhoward** [comment]
Okay. Makes sense.

**Comment by gianlucapettinello** [comment]
I recompiled strawberry but I get this time not always the crash. In the command line the last message before crashing is:
WARN  unknown QSortFilterProxyModel: index from wrong model passed to mapToSource.
I don't know if it can be of help.
I'll try to downgrade taglib

**Comment by gianlucapettinello** [comment]
As you suggested I ran strawberry with gdb,
The debug is the following:
__logging_message__00:29:43.877 WARN  unknown                          QObject::connect: No such signal TrackSelectionDialog::Error(QString)
__logging_message__00:29:43.877 WARN  unknown                          QObject::connect:  (sender name:   'TrackSelectionDialog')
__logging_message__00:29:43.877 WARN  unknown                          QObject::connect:  (receiver name: 'MainWindow')
__logging_message__00:29:43.877 WARN  unknown                          QSortFilterProxyModel: index from wrong model passed to mapToSource

Thread 1 "strawberry" received signal SIGSEGV, Segmentation fault.
0x0000555555749800 in MainWindow::AutoCompleteTags()

**Comment by gianlucapettinello** [comment]
I found that if I double click a song and it start playing and then I click again and finally I right click to have tag autocompletion, it doesn't crash. If I don't left click after starting the song then upon auto completion click it crashes. It seems that an info is not passed to the dialog class

**Comment by jonaski** [comment]
The missing signal (Error) is a bug, but that's not the cause for the crash.
I can't reproduce this crash.
But it probably has something to do with `index from wrong model passed to mapToSource`.
When you run gdb you need to type `bt` and enter to get a backtrace, paste it here inside of `code brackets`.

**Comment by valerie-vanillaroma** [comment]
Running into the same issue with Strawberry 0.6.8 on Linux Mint 19.2:

When right clicking a song that is playing, Strawberry crashes immediately upon selecting 'Edit track information'.

Crash does not seem to happen with every song, but of the songs it has crashed on, it seems to happen 100% of the time.

Strawberry gdb output (I think I did this right):

QSortFilterProxyModel: index from wrong model passed to mapToSource

Thread 1 "strawberry" received signal SIGSEGV, Segmentation fault.
0x0000555555a91356 in std::__shared_ptr<PlaylistItem, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<PlaylistItem, (__gnu_cxx::_Lock_policy)2> const&) ()

**Comment by jonaski** [comment]
It's the mapToSource() in MainWindow::EditTracks() that fails, but I don't see the reason why.
I've made some changes that will probably fix the crash, but the edit tag dialog will probably not open https://github.com/strawberrymusicplayer/strawberry/commit/3a4107d903b146b482ec6040e96314fb0fad8929
Can someone who can reproduce the crash test and see if the dialog opens or not?

**Comment by jonaski** [comment]
It almost seem like app_->playlist_manager()->current() is set to the wrong playlist model to cause something like this.

I found a missing mapToSource() in PlaylistRightClick where it calculated how many songs are editable, etc. Should be unrelated to this though.

**Comment by gianlucapettinello** [comment]
I confirm that git build in Archlinux is now ok

**Comment by jonaski** [comment]
So it's fixed? The dialog opens too?

**Comment by gianlucapettinello** [comment]
Yes the git version is fixed.
Thanks
