### ISSUE TITLE
DR meter integration 

### ISSUE THREAD

**Issue by Retkid** [strawberrymusicplayer/strawberry#320]
As a music collector its sometimes required for me to measure the level of Dynamic range in the rip. And it would be really need if i could do it in a right-click "DR14 MEASURE" then spit the output in a sort able collume. 

I don't think D14 integration would be specifically hard...

**Comment by jonaski** [comment]
I don't have time to prioritize this, and due to few contributors I'm closing this.

**Comment by loxoron218** [comment]
Are there any options for this feature to still be implemented?  Me, also being a music collector who cares about having the best possible quality files, would also love to see this feature! :)

I don't know, maybe it is easier to implement if the program was able to read a log.txt (that for example DROffline creates) and just extracted the data from it instead of measuring the dynamic range by itself?

**Comment by albassort** [comment]
> Are there any options for this feature to still be implemented? Me, also being a music collector who cares about having the best possible quality files, would also love to see this feature! :)
> 
> I don't know, maybe it is easier to implement if the program was able to read a log.txt (that for example DROffline creates) and just extracted the data from it instead of measuring the dynamic range by itself?

I think perhaps moving to a different platform, maybe in NVIM would better achieve this than trying to add this feature to this program.

**Comment by loxoron218** [comment]
> > Are there any options for this feature to still be implemented? Me, also being a music collector who cares about having the best possible quality files, would also love to see this feature! :)
> > I don't know, maybe it is easier to implement if the program was able to read a log.txt (that for example DROffline creates) and just extracted the data from it instead of measuring the dynamic range by itself?
> 
> I think perhaps moving to a different platform, maybe in NVIM would better achieve this than trying to add this feature to this program.

What do you mean by "moving to NVIM"?

**Comment by albassort** [comment]
> > > Are there any options for this feature to still be implemented? Me, also being a music collector who cares about having the best possible quality files, would also love to see this feature! :)
> > > I don't know, maybe it is easier to implement if the program was able to read a log.txt (that for example DROffline creates) and just extracted the data from it instead of measuring the dynamic range by itself?
> > 
> > 
> > I think perhaps moving to a different platform, maybe in NVIM would better achieve this than trying to add this feature to this program.
> 
> What do you mean by "moving to NVIM"?

I like nvim, i want everything in nvim basically.
