### ISSUE TITLE
Option to move Clear playlist button to the bottom

### ISSUE THREAD

**Issue by MightyPork** [strawberrymusicplayer/strawberry#325]
I'm trying to move from Clementine to Strawberry and this is the thing I keep tripping over.

Note the Clear Playlist button in clementine, located at the bottom of the tracks list:
![Screenshot_20191214_233722](https://user-images.githubusercontent.com/2041118/70855427-fae8a880-1eca-11ea-9860-03168ae224cd.png)
I never used anything else from the playlists interface - I drag songs from the left menu and hit play.
When I reopen the player, I clear the list by this button, add new songs, etc.

In Strawberry, this button is tiny and moved to the top, I think it's more logical from the point of view that it's a playlist management button, but it's much less practical for my simple use.

![Screenshot_20191214_233718](https://user-images.githubusercontent.com/2041118/70855447-2d92a100-1ecb-11ea-9288-bccc4b4f866c.png)

I'd really like if there was a option to have the button back in its original location.

**Comment by jonaski** [comment]
I'm closing this since this is only a minor detail, and I don't have time to prioritize it. Anyone else is free to make a proposal for a change in a PR.
