### ISSUE TITLE
Multiple Tags Per Field (Song Metadata)

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [strawberrymusicplayer/strawberry#326]
**Is your feature request related to a problem? Please describe.**
I work on a few other music programs like Quodlibet and the like where multiple tags are supported for a tag entry. For example, Genre and Artist can be a composite of multiple tags working together. Additionally, Quodlibet has some features that allow for 'meta' tags that are tag hybrids ("people" represents a mix of composer, artist, performers, etc...)

It would be really nice if Strawberry or Clementine had this feature. Strawberry seems like a reset button for Clementine, so it's probably a good testing ground for re-doing the tag subsytem to support this. 

**Describe the solution you'd like**
It would require a tag-subsystem rewrite, but basically songs should carry a many-to-many relationship table to tags. So each song would need a few individual subtables that provide the actual tag information. 

I looked into this issue before when working a bit on Clementine and gave up on the project when I moved over to Quodlibet. While I still use Quodlibet on a daily basis, I do feel like Clementine/Strawberry could be improved for those who really have meticulous control over their own music library.

**Comment by jonaski** [comment]
I'm a bit hesitant with changing the whole DB schemas and tagreader to support this. I also lack the time to do it, and right now there are too few other contributors.

**Comment by Eoin-ONeill-Yokai** [comment]
That's a shame but 100% understandable. I might mess with it some more some time.
