### ISSUE TITLE
Support Subsonic playlists

### ISSUE THREAD

**Issue by aslmx** [strawberrymusicplayer/strawberry#327]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can not use the playlist I defined in Ampache on other devices, such as with Strawberry.

**Describe the solution you'd like**
I would like Strawberry to be able to fetch and play the playlists stored on Ampache. UltraSonic my favourite Android client can do it as well, https://github.com/ultrasonic/ultrasonic
Editing (i.e. adding/removing Songs to) playlists would be nice, but that can be discussed separately.

**Describe alternatives you've considered**
An alternative I think about is defining a Strawberry Playlist that i save as a file on my nextcloud. But then i have to maintain my Ampache Playlist + the Strawberry playlist... not very ideal. I installed Ampache to have all the media and playlists in one place actually.
Another alternative is to not use strawberry and use the Ampache WebUI again.

**Comment by jonaski** [comment]
Closing this because of lack of time.

**Comment by gitty323** [comment]
+1 on this - Strawberry is my favorite desktop music player but I have had to look elsewhere because it can't use the playlists that I create and sync with all of my other devices.
