### ISSUE TITLE
Chromecast output support

### ISSUE THREAD

**Issue by DerjeBoven** [strawberrymusicplayer/strawberry#328]
From the version 3.0, [VLC](https://www.videolan.org/vlc/releases/3.0.0.html) can stream to distant renderers, like Chromecast devices.

Many [others](https://en.wikipedia.org/wiki/List_of_apps_with_Google_Cast_support) do as well.

This should be very useful for Strawberry, as speakers for TV are often better than computer's (and more common).

**Comment by jonaski** [comment]
I don't have Chromecast or a need for it myself, so it's not possible for me to do it, and due to few contributors I'm closing this for now.
