### ISSUE TITLE
Airsonic playlists support

### ISSUE THREAD

**Issue by AryToNeX** [strawberrymusicplayer/strawberry#331]
**Is your feature request related to a problem? Please describe.**
I am really disappointed about this music player having Subsonic/Airsonic support but with no way to import playlists from the Subsonic/Airsonic server.

**Describe the solution you'd like**
When a Subsonic server is added or synchronized, every single playlist should be downloaded, parsed and then added to a playlist group called "Subsonic" on the playlist section. If there was already a Subsonic group, move it to Subsonic_old (this is for hacky people who managed to work around the problem by using the alternative below). Mark the Subsonic group with a special read-only flag of some sort, so people cannot mess around with playlists. Make playlist un-editable in the client, but redirect users to Subsonic/Airsonic's web UI (for now, at least). Discard every playlist in that group before every synchronization to get rid of duplicates and server-side deleted playlists.

**Describe alternatives you've considered**
Exporting playlists from Airsonic and modifying them to play music over SSHFS (not really cool)

**Comment by jonaski** [comment]
Same as #327
