### ISSUE TITLE
Support MPD (Music Player Daemon)

### ISSUE THREAD

**Issue by Fef0** [strawberrymusicplayer/strawberry#334]
**Is your feature request related to a problem? Please describe.**
Hi, I'm going to play some DSDs but GStreamer doesn't really like them, so it resamples them into PCM and send the result into the DAC, which is DSD-Capable.

**Describe the solution you'd like**
I'm wondering if you'd like to add MPD as Engine, because I tried DSD with that and it works, but it doesn't have the good features that Strawberry offers.

**Specs** 
OS: Arch Linux 5.4.7-arch1-1
GStreamer version: just compiled from source (gstreamer-git), nothing really changed.

**Comment by jonaski** [comment]
We support multiple engines so I think adding support for MPD should be pretty easy.

**Comment by Fef0** [comment]
Well, MPD is actually different, since it's a daemon that runs as a server and not an executable that you can interact with through an API. But yeah, it should be pretty easy since you just have to specify which file to play and MPD magically plays it for you.

**Comment by jonaski** [comment]
Yeah I know a bit about how MPD works, but have not used it myself. I think the engine base class can be overloaded to communicate over the network, so we override Play/Stop/Pause etc to communicate back and forth to the MPD server instead.

**Comment by Fef0** [comment]
Ok, great!
It should be even easier if you decide to use ```mpc```, as ```ncmpcpp``` actually does. You just have to call it from the shell and it does everything.

**Comment by Fef0** [comment]
Hey @jonaski, any news regarding this proposal? MPD seems the only way I can play my DSDs on Linux, Strawberry sadly force them into PCM using GStreamer

**Comment by jonaski** [comment]
I don't think we should add MPD just for the reason to able to play DSD if that's what you are suggesting.
There must be a way to get that accomplished using GStreamer.
As for adding MPD, it's not something I'm going to do, I simply can't prioritize something I have no use for over actual issues and other features we need, I left the issue open in cause someone else was interested in doing it, doesn't look like it though.

**Comment by buzuck** [comment]
Hello, I see other reasons to add MPD support, especially on Windows as I am not aware of any decent MPD client on this platform and this would be a great addition to Strawberry :)

I see two distinct usages :
1. Controlling a remote MPD server in my home
2. Streaming music from a MPD server (minor use case for me)
