### ISSUE TITLE
Add a selectable list of lyrics sources instead of automatic picking one

### ISSUE THREAD

**Issue by Fef0** [strawberrymusicplayer/strawberry#335]
**Is your feature request related to a problem? Please describe.**
I don't really like the automatic choosing of the lyrics source from the list of the available ones.
AudD, which is the preferred one of Strawberry as I see, has a lot of errors or lyrics that have been stucked in "Lyrics for this song have yet to be released. Please check back once the song has been released." for the past two years, while a lot of other websites have that one.

**Describe the solution you'd like**
It would be great to be able to choose a source from the "Context" tab, so I can change it for different songs, and also being able to select a "Default" one seems pretty useful.

**Comment by jonaski** [comment]
We can workaround the "Lyrics for this song have yet to be released" things by increasing the score for providers that return text above around 50-100 characters. So that's pretty easy actually.
It would be nice to be able to pick providers in the settings too, in case on of them has issues.

**Comment by Fef0** [comment]
Well, if you limit the lyrics length you can exclude some tracks that have a very short lyric (like "Instrumental" ones or songs that always repeat the same sentence over and over).
I think that it's ok to leave things as they are and let the user choose it's preferred lyrics source, don't you think?

**Comment by jonaski** [comment]
It won't exclude any, just pick the one with the highest score, and the ones with longer length than ie 60 characters will get a higher score. I already do that when matching artist / Song title with ones returned by the provider, a result where both artist and song title match gets a score of 2 while the ones where only match one of them get 1.

**Comment by Fef0** [comment]
Great, but what about the ability to change lyrics source from the Context tab (or Settings)?
It would be very convenient, because AudD sometime isn't the best even though it has the highest score.

**Comment by jonaski** [comment]
I agree but it's a bit more work so I don't have time for it now. I'll keep the issue open and see if anyone else wants to pick it up.

**Comment by gomera** [comment]
I agree with @Fef0, having a dropdown on Context for changing the source would be what I need. Obviously been able to add custom lyric providers would be incredible good. Another interesting idea to put on the table is about setting sources based on tags. For example, jpop will use X, Y sources only.
