### ISSUE TITLE
(macOS) MP3 GStreamer error

### ISSUE THREAD

**Issue by dayfuaim** [strawberrymusicplayer/strawberry#343]
**Describe the bug**
I get the error message when trying to play MP3. (See screenshot)
Any of AAC, FLAC, Opus – no error.

**To Reproduce**
1. Install Strawberry.
2. Try to play MP3.

**Expected behavior**
Strawberry is playing MP3.

**Screenshots:**
![Снимок экрана 2020-01-09 в 17 15 04](https://user-images.githubusercontent.com/1274699/72075120-2a40d880-3304-11ea-9b39-26788d802007.png)

**System Information:**
 - Operating system: MacOS 10.13.6
 - Strawberry Version: 0.6.8

**Additional context**
System GStreamer is untouched from the start.

**Comment by jonaski** [comment]
Some others have reported the same. I think it's because you got a system gstreamer installation that conflicts with the bundled gstreamer in strawberry.

**Comment by dayfuaim** [comment]
@jonaski Understood.
But what can we do to fix this?

**Comment by jonaski** [comment]
The paths needs to be replaced in the dymamic modules (gstreamer plugins).
https://gstreamer.freedesktop.org/documentation/deploying/mac-osx.html?gi-language=c
https://www.unix.com/man-page/osx/1/install_name_tool/

**Comment by jonaski** [comment]
I've removed the macOS bullds, we don't provide releases for macOS. If someone wants to fix this we can re-enable it, I dont have time to fix macOS issues.

**Comment by tmikaeld** [comment]
@jonaski Can you please add this to the readme, so people don't have to search the issues to find this little note about MacOS not being supported any more.

**Comment by jonaski** [comment]
My macOS Vm isn't working anymore so I can't really fix anything, and it's too much hassle for me to set it all up again. But I added back the builds in travis-ci again.
Maybe @MartinDelille can look into this.

**Comment by MartinDelille** [comment]
I don't have so much time to dedicate to this project neither but I did a quick test to try to compile the latest master version.

Unfortunately I had the following error:

```
/usr/local/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9: error: Failed to find "gl.h" in "/System/Library/Frameworks/OpenGL.framework/Headers;/System/Library/Frameworks/AGL.framework/Headers". /usr/local/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:202 (include) /usr/local/opt/qt/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:94 (find_package) /usr/local/opt/qt/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package) CMakeLists.txt:152 (find_package)
```

It might be due to the multiple version of Qt installed on my system.

Since I'm quite noob at cmake, could someone tell me how cmake guess the Qt version used?

**Comment by jonaski** [comment]
Set Qt5_DIR to point to the Qt5 Cmake dir, like:
`export Qt5_DIR=/usr/local/opt/qt5/lib/cmake`
or you can set CMAKE_PREFIX_PATH
There is some info here: https://doc.qt.io/qt-5/cmake-get-started.html

**Comment by jonaski** [comment]
I re-installed macOS in virtualbox now. I used a script from here: https://github.com/myspaghetti/macos-virtualbox - It made it pretty easy.
I tested playing and it works fine, but it's using libav, and not the lame plugin. It should still work.
I checked the paths on the files and I can't find anything wrong with it.

**Comment by jonaski** [comment]
Can you try running strawberry in a terminal and see if there are any errors related to gst plugins not loading.
Go in search / enter terminal. Type: `/Applications/strawberry.app/Contents/MacOS/strawberry`

**Comment by clementine-user** [comment]
@jonaski -

i hope this gives you some insight into theis issue. Here's the terminal output when starting 0.6.12.114:

`$ /Applications/strawberry.app/Contents/MacOS/strawberry
14:31:37.956 INFO  main:157                         Strawberry 0.6.12-114-gc5ae6407
14:31:37.957 INFO  main:158                         "macOS High Sierra (10.13) 10.13 - (darwin 17.7.0) [x86_64]"
14:31:37.957 DEBUG Utilities:810                    Max fd: 24576
14:31:38.068 DEBUG main:181                         Looking for resources in "/Applications/strawberry.app/Contents/MacOS/../PlugIns"
14:31:38.075 DEBUG Application:242                  Database(0x7fc00fcba1e0) moved to thread QThread(0x7fc00fcb04a0)
14:31:38.076 DEBUG SCollection:62                   CollectionBackend(0x7fc00fcba130) moved to thread QThread(0x7fc00fcb04a0)
14:31:38.115 DEBUG Application:242                  AlbumCoverLoader(0x7fc00fd4f270) moved to thread QThread(0x7fc00fccdeb0)
14:31:38.124 DEBUG SCollection:94                   CollectionWatcher(0x7fc00fd4cbd0) moved to thread QThread(0x7fc00fd5f5c0)
14:31:38.125 DEBUG Application:242                  TagReaderClient(0x7fc00fd60d40) moved to thread QThread(0x7fc00fd610b0)
14:31:38.126 DEBUG >:282                            Starting worker 0x70000834e848 "/Applications/strawberry.app/Contents/MacOS/../PlugIns/strawberry-tagreader" "/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_140573097"
14:31:38.127 DEBUG >:282                            Starting worker 0x70000834e848 "/Applications/strawberry.app/Contents/MacOS/../PlugIns/strawberry-tagreader" "/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_33115826"
14:31:38.172 INFO  main:56                          TagReader worker connecting to "/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_140573097"
14:31:38.172 INFO  main:56                          TagReader worker connecting to "/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_33115826"
14:31:38.176 DEBUG >:300                            Worker 0x7fc00fcd2080 connected to "/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_140573097"
14:31:38.176 DEBUG >:300                            Worker 0x7fc00fd62d50 connected to "/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_33115826"
14:31:39.027 WARN  unknown                          Populating font family aliases took 846 ms. Replace uses of missing font family "Verdana" with one that exists to avoid this cost.  
14:31:39.341 INFO  Player:809                       Registered URL handler for "subsonic"
14:31:39.350 DEBUG InternetServices:49              Added internet service "Subsonic"
14:31:39.350 INFO  Player:809                       Registered URL handler for "tidal"
14:31:39.374 DEBUG InternetServices:49              Added internet service "Tidal"
14:31:39.502 DEBUG MainWindow:262                   Starting
14:31:39.525 DEBUG CoverProviders:105               Registered cover provider "Last.fm"
14:31:39.525 DEBUG CoverProviders:105               Registered cover provider "MusicBrainz"
14:31:39.525 DEBUG CoverProviders:105               Registered cover provider "Discogs"
14:31:39.525 DEBUG CoverProviders:105               Registered cover provider "Deezer"
14:31:39.526 DEBUG CoverProviders:105               Registered cover provider "Qobuz"
14:31:39.526 DEBUG CoverProviders:105               Registered cover provider "Musixmatch"
14:31:39.526 DEBUG CoverProviders:105               Registered cover provider "Spotify"
14:31:39.526 DEBUG CoverProviders:105               Registered cover provider "Tidal"
14:31:39.539 DEBUG LyricsProviders:103              Registered lyrics provider "AudD"
14:31:39.540 DEBUG LyricsProviders:103              Registered lyrics provider "Genius"
14:31:39.540 DEBUG LyricsProviders:103              Registered lyrics provider "Lyrics.ovh"
14:31:39.540 DEBUG LyricsProviders:103              Registered lyrics provider "LoloLyrics"
14:31:39.540 DEBUG LyricsProviders:103              Registered lyrics provider "Musixmatch"
14:31:39.541 DEBUG LyricsProviders:103              Registered lyrics provider "ChartLyrics"
14:31:39.648 DEBUG MainWindow:306                   Initialising player
14:31:39.648 DEBUG MainWindow:316                   Creating models
14:31:39.649 DEBUG MainWindow:323                   Creating models finished
14:31:39.651 DEBUG DeviceLister:66                  MacOsDeviceLister(0x7fc013061280) moved to thread QThread(0x7fc013061340)
14:31:39.654 DEBUG MacOsDeviceLister:500            Interface class: 3
14:31:39.657 DEBUG Application:242                  PlaylistBackend(0x7fc0130a7d20) moved to thread QThread(0x7fc00fcb04a0)
14:31:39.662 DEBUG MacOsDeviceLister:500            Interface class: 255
14:31:39.662 DEBUG MainWindow:341                   Creating UI
14:31:39.663 DEBUG MacOsDeviceLister:500            Interface class: 9
14:31:39.663 DEBUG MacOsDeviceLister:500            Interface class: 3
14:31:39.671 DEBUG MacOsDeviceLister:500            Interface class: 8
14:31:39.672 DEBUG MacOsDeviceLister:500            Interface class: 3
14:31:39.679 DEBUG MacOsDeviceLister:500            Interface class: 14
14:31:39.680 DEBUG MacOsDeviceLister:500            Interface class: 9
14:31:39.688 DEBUG ScrobblerServices:49             Registered scrobbler service "Last.fm"
14:31:39.689 DEBUG ScrobblerServices:49             Registered scrobbler service "Libre.fm"
14:31:39.689 DEBUG ScrobblerServices:49             Registered scrobbler service "ListenBrainz"
14:31:39.702 DEBUG MainWindow:747                   Creating playing widget
14:31:39.704 DEBUG MacOsDeviceLister:500            Interface class: 9
14:31:39.727 DEBUG MacOsDeviceLister:500            Interface class: 9
14:31:39.859 DEBUG MainWindow:790                   Loading settings
14:31:39.992 DEBUG MainWindow:884                   Started QThread(0x7fc00fc7efe0)
14:31:58.684 DEBUG Player:599                       Playing song "Back In The Saddle" QUrl("file:///Volumes/Scratch/Aerosmith - Back In The Saddle.mp3")
14:31:58.684 DEBUG PlaylistBackend:329              Saving playlist 1
14:31:58.743 ERROR GstEnginePipeline:877            ErrorMessageReceived 1 "gsturidecodebin.c(988): void no_more_pads_full(GstElement *, gboolean, GstURIDecodeBin *) (): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0:\nno suitable plugins found:\ngstdecodebin2.c(4679): gboolean gst_decode_bin_expose(GstDecodeBin *) (): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin2:\nno suitable plugins found:\nMissing decoder: MPEG-1 Layer 3 (MP3) (audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2, parsed=(boolean)true)\n"
14:31:58.743 ERROR GstEnginePipeline:877            ErrorMessageReceived 1 "gstbaseparse.c(3634): void gst_base_parse_loop(GstPad *) (): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin2/GstMpegAudioParse:mpegaudioparse1:\nstreaming stopped, reason not-linked (-1)"
14:31:58.750 ERROR GstEngine:511                    Gstreamer error: 1468 12 "Your GStreamer installation is missing a plug-in."
14:32:40.591 DEBUG DeviceManager:222                MacOsDeviceLister(0x7fc013061280) successfully closed.
14:32:40.591 DEBUG Application:283                  TagReaderClient(0x7fc00fd60d40) successfully exited.
14:32:40.591 DEBUG Application:283                  AlbumCoverLoader(0x7fc00fd4f270) successfully exited.
14:32:40.591 DEBUG SCollection:136                  CollectionBackend(0x7fc00fcba130) successfully exited.
14:32:40.591 DEBUG Application:283                  PlaylistBackend(0x7fc0130a7d20) successfully exited.
14:32:40.592 DEBUG DeviceManager:210                DeviceDatabaseBackend(0x7fc013077ee0) successfully closed.
14:32:40.592 DEBUG Application:283                  DeviceManager(0x7fc01306f990) successfully exited.
14:32:40.592 DEBUG TidalService:229                 CollectionBackend(0x7fc0123630f0) successfully exited.
14:32:40.592 DEBUG TidalService:229                 CollectionBackend(0x7fc012363330) successfully exited.
14:32:40.592 DEBUG TidalService:229                 CollectionBackend(0x7fc012363470) successfully exited.
14:32:40.592 DEBUG Application:283                  InternetServices(0x7fc012621ce0) successfully exited.
14:32:40.593 DEBUG SCollection:136                  CollectionWatcher(0x7fc00fd4cbd0) successfully exited.
14:32:40.593 DEBUG Application:283                  SCollection(0x7fc00fcba070) successfully exited.
14:32:40.646 DEBUG LyricsProviders:124              Unregistered lyrics provider "LoloLyrics"
14:32:40.646 DEBUG LyricsProviders:124              Unregistered lyrics provider "Musixmatch"
14:32:40.646 DEBUG LyricsProviders:124              Unregistered lyrics provider "ChartLyrics"
14:32:40.646 DEBUG LyricsProviders:124              Unregistered lyrics provider "AudD"
14:32:40.646 DEBUG LyricsProviders:124              Unregistered lyrics provider "Genius"
14:32:40.646 DEBUG LyricsProviders:124              Unregistered lyrics provider "Lyrics.ovh"
14:32:40.647 DEBUG CoverProviders:126               Unregistered cover provider "Last.fm"
14:32:40.648 DEBUG CoverProviders:126               Unregistered cover provider "MusicBrainz"
14:32:40.648 DEBUG CoverProviders:126               Unregistered cover provider "Discogs"
14:32:40.648 DEBUG CoverProviders:126               Unregistered cover provider "Deezer"
14:32:40.648 DEBUG CoverProviders:126               Unregistered cover provider "Qobuz"
14:32:40.648 DEBUG CoverProviders:126               Unregistered cover provider "Musixmatch"
14:32:40.648 DEBUG CoverProviders:126               Unregistered cover provider "Spotify"
14:32:40.648 DEBUG CoverProviders:126               Unregistered cover provider "Tidal"
14:32:40.649 DEBUG >:178                            Closing worker socket
14:32:40.652 DEBUG >:178                            Closing worker socket
`
Also, just want to say thanks for working on the mac builds—you're crushing it!

You may wan to check out [dosdude's macOS patchers](http://dosdude1.com/software.html). I allows you to download the latest/last installers so you can create USB install media to use when you want to create a macOS VM.

Also on the announcement for 0.6.13, you should include the hide/show sidebar toggle you included as a feature.

Thanks again!

**Comment by clementine-user** [comment]
Update to previous post, same behavior on 0.6.13.

**Comment by jonaski** [comment]
Looks to be specific to macOS 10.13.6 high sierra, everyone who have had reported MP3 problems have had that macOS release.

**Comment by jonaski** [comment]
There are no errors related to loading plugins in the startup. It's a bit weird because there are 2 plugins that should both handle MP3, both gstlibav and gstlame, and it's strange that none of the 2 work.

**Comment by clementine-user** [comment]
It certainly is strange since there are no "native to macos" gstreamer libraries installed. Both Strawberry and Clementine both include their own in the builds. I searched through the /Library folder and found nothing. Unfortunately newer builds of Clementine, after 1.3.1 don't run on 10.13.6 and builds after Clementine-1.4.0rc1-211 don't run on anything less than 10.15.x.

**Comment by jonaski** [comment]
Clementine macOS builds are built in GitHub actions now and they use the newest macOS release in their CI so it's not backward compatible, that's why I still use Travis-CI because they use macOS high sierra.

**Comment by clementine-user** [comment]
One more thing that I did try when this first popped up was to copy the plugins from both a working version of Strawberry and a working version of Clementine into the non-working Strawberry version. That didn't solve the problem. I really didn't think it would work, but couldn't hurt.

**Comment by clementine-user** [comment]
> Clementine macOS builds are built in GitHub actions now and they use the newest macOS release in their CI so it's not backward compatible, that's why I still use Travis-CI because they use macOS high sierra.

That's most unfortunate that they felt the need to cutoff users with older macOS versions who still might want to repurpose an older servicable Mac to a single-purpose media device while still building for old versions of Windows.

**Comment by jonaski** [comment]
Windows is a horrible OS, but it's always been good with backward compatibility, I think you can build most things on Windows 10 and it will still work on Windows 7 and 8, it's much easier to cross-build from Linux too.

**Comment by clementine-user** [comment]
Poor Mac. Always the redheaded step child...

Still appreciate your work on the Mac builds. I switched from the old version of Clementine to Strawberry after you added the hide/show sidebar bit. Makes for a much easier interface to use.

Thanks.

**Comment by jonaski** [comment]
Try to remove the gst registry file then run strawberry again from the terminal to see if there are any new errors printed:

`rm /Users/$USER/Library/Application\ Support\Strawberry/Strawberry/gst-registry*`

**Comment by clementine-user** [comment]
Hopefully this won't be too unreadable, but contains interesting info:

$ /Applications/strawberry.app/Contents/MacOS/strawberry

13:25:49.359 INFO  main:165                         Strawberry 0.6.13-91-gb3d06c08

13:25:49.360 INFO  main:166                         "macOS High Sierra (10.13) 10.13 -
(darwin 17.7.0) [x86_64]"

13:25:49.360 DEBUG Utilities:799                    Max fd: 24576

13:25:49.468 DEBUG main:189                         Looking for resources in
"/Applications/strawberry.app/Contents/MacOS/../PlugIns"

13:25:49.475 DEBUG Application:242                  Database(0x7fe672da2110) moved to thread
QThread(0x7fe672d91e00)

13:25:49.476 DEBUG SCollection:62                   CollectionBackend(0x7fe672d99ff0) moved
to thread QThread(0x7fe672d91e00)

13:25:49.517 DEBUG Application:242                  AlbumCoverLoader(0x7fe672e1f130) moved
to thread QThread(0x7fe672c41180)

13:25:49.526 DEBUG SCollection:94                   CollectionWatcher(0x7fe672db8b40) moved
to thread QThread(0x7fe672dba610)

13:25:49.527 DEBUG Application:242                  TagReaderClient(0x7fe672dbba80) moved to
thread QThread(0x7fe672dbba40)

13:25:49.527 DEBUG >:282                            Starting worker 0x7000103e9848
"/Applications/strawberry.app/Contents/MacOS/../PlugIns/strawberry-tagreader"
"/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_611359708"

13:25:49.529 DEBUG >:282                            Starting worker 0x7000103e9848
"/Applications/strawberry.app/Contents/MacOS/../PlugIns/strawberry-tagreader"
"/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_1266520591"

13:25:49.533 DEBUG logging:83(GLib)                 posix_spawn avoided (fd close requested)




(gst-plugin-scanner:691): GStreamer-WARNING **: 13:25:49.577: Failed to load plugin
'/Applications/strawberry.app/Contents/MacOS/../PlugIns/gstreamer/libgstlibav.so':
dlopen(/Applications/strawberry.app/Contents/MacOS/../PlugIns/gstreamer/libgstlibav.so, 2):
Library not loaded: /usr/lib/liblzma.5.dylib Referenced from:
/Applications/strawberry.app/Contents/PlugIns/gstreamer/libgstlibav.so Reason: Incompatible
library version: libgstlibav.so requires version 8.0.0 or later, but liblzma.5.dylib
provides version 6.0.0




13:25:49.582 INFO  main:56                          TagReader worker connecting to
"/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_611359708"

13:25:49.582 INFO  main:56                          TagReader worker connecting to
"/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_1266520591"

13:25:49.586 DEBUG >:300                            Worker 0x7fe672f317e0 connected to
"/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_1266520591"

13:25:49.587 DEBUG >:300                            Worker 0x7fe672e42ce0 connected to
"/private/var/folders/zs/zk56gs8975x0z8p4_dy_ydwm0000gn/T/strawberry_611359708"




(gst-plugin-scanner:691): GStreamer-WARNING **: 13:25:49.704: Failed to load plugin
'/Applications/strawberry.app/Contents/MacOS/../PlugIns/gstreamer/libgstlibav.so':
dlopen(/Applications/strawberry.app/Contents/MacOS/../PlugIns/gstreamer/libgstlibav.so, 2):
Library not loaded: /usr/lib/liblzma.5.dylib Referenced from:
/Applications/strawberry.app/Contents/PlugIns/gstreamer/libgstlibav.so Reason: Incompatible
library version: libgstlibav.so requires version 8.0.0 or later, but liblzma.5.dylib
provides version 6.0.0




13:25:50.493 WARN  unknown                          Populating font family aliases took 901
ms. Replace uses of missing font family "Verdana" with one that exists to avoid this cost.

13:25:50.818 INFO  Player:800                       Registered URL handler for "subsonic"

13:25:50.827 DEBUG InternetServices:49              Added internet service "Subsonic"

13:25:50.827 INFO  Player:800                       Registered URL handler for "tidal"

13:25:50.852 DEBUG InternetServices:49              Added internet service "Tidal"

13:25:50.984 DEBUG MainWindow:272                   Starting

13:25:51.007 DEBUG CoverProviders:105               Registered cover provider "Last.fm"

13:25:51.008 DEBUG CoverProviders:105               Registered cover provider "MusicBrainz"

13:25:51.008 DEBUG CoverProviders:105               Registered cover provider "Discogs"

13:25:51.008 DEBUG CoverProviders:105               Registered cover provider "Deezer"

13:25:51.009 DEBUG CoverProviders:105               Registered cover provider "Qobuz"

13:25:51.009 DEBUG CoverProviders:105               Registered cover provider "Musixmatch"

13:25:51.009 DEBUG CoverProviders:105               Registered cover provider "Spotify"

13:25:51.009 DEBUG CoverProviders:105               Registered cover provider "Tidal"

13:25:51.023 DEBUG LyricsProviders:103              Registered lyrics provider "AudD"

13:25:51.024 DEBUG LyricsProviders:103              Registered lyrics provider "Genius"

13:25:51.024 DEBUG LyricsProviders:103              Registered lyrics provider "Lyrics.ovh"

13:25:51.024 DEBUG LyricsProviders:103              Registered lyrics provider "LoloLyrics"

13:25:51.024 DEBUG LyricsProviders:103              Registered lyrics provider "Musixmatch"

13:25:51.024 DEBUG LyricsProviders:103              Registered lyrics provider "ChartLyrics"

13:25:51.128 DEBUG MainWindow:316                   Initialising player

13:25:51.129 DEBUG MainWindow:326                   Creating models

13:25:51.129 DEBUG MainWindow:333                   Creating models finished

13:25:51.131 DEBUG DeviceLister:66                  MacOsDeviceLister(0x7fe676066a00) moved
to thread QThread(0x7fe676066870)

13:25:51.135 DEBUG MacOsDeviceLister:500            Interface class: 3

13:25:51.137 DEBUG Application:242                  PlaylistBackend(0x7fe676167250) moved to
thread QThread(0x7fe672d91e00)

13:25:51.142 DEBUG MainWindow:351                   Creating UI

13:25:51.143 DEBUG MacOsDeviceLister:500            Interface class: 255

13:25:51.144 DEBUG MacOsDeviceLister:500            Interface class: 9

13:25:51.144 DEBUG MacOsDeviceLister:500            Interface class: 3

13:25:51.152 DEBUG MacOsDeviceLister:500            Interface class: 8

13:25:51.153 DEBUG MacOsDeviceLister:500            Interface class: 3

13:25:51.163 DEBUG MacOsDeviceLister:500            Interface class: 9

13:25:51.169 DEBUG ScrobblerServices:49             Registered scrobbler service "Last.fm"

13:25:51.169 DEBUG ScrobblerServices:49             Registered scrobbler service "Libre.fm"

13:25:51.170 DEBUG ScrobblerServices:49             Registered scrobbler service
"ListenBrainz"

13:25:51.173 DEBUG MacOsDeviceLister:500            Interface class: 14

13:25:51.184 DEBUG MainWindow:756                   Creating playing widget

13:25:51.190 DEBUG MacOsDeviceLister:500            Interface class: 9

13:25:51.216 DEBUG MacOsDeviceLister:500            Interface class: 9

13:25:51.344 DEBUG MainWindow:799                   Loading settings

13:25:51.474 DEBUG MainWindow:915                   Started QThread(0x7fe672d12e10)

13:26:37.092 DEBUG Player:590                       Playing song "Back In The Saddle"
QUrl("file:///Volumes/Scratch/Aerosmith - Back In The Saddle.mp3")

13:26:37.092 DEBUG PlaylistBackend:329              Saving playlist 1



13:26:37.180 ERROR GstEnginePipeline:878            ErrorMessageReceived 1
"gsturidecodebin.c(988): void no_more_pads_full(GstElement *, gboolean, GstURIDecodeBin *)
(): /GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0:\nno suitable plugins
found:\ngstdecodebin2.c(4679): gboolean gst_decode_bin_expose(GstDecodeBin *) ():
/GstPlayBin:playbin-0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin2:\nno suitable
plugins found:\nMissing decoder: MPEG-1 Layer 3 (MP3) (audio/mpeg, mpegversion=(int)1,
mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2,
parsed=(boolean)true)\n"




13:26:37.180 ERROR GstEngine:512                    Gstreamer error: 1465 12 "Your GStreamer
installation is missing a plug-in."




13:26:43.624 DEBUG DeviceManager:222                MacOsDeviceLister(0x7fe676066a00)
successfully closed.

13:26:43.624 DEBUG Application:283                  AlbumCoverLoader(0x7fe672e1f130)
successfully exited.

13:26:43.625 DEBUG SCollection:136                  CollectionBackend(0x7fe672d99ff0)
successfully exited.

13:26:43.625 DEBUG Application:283                  PlaylistBackend(0x7fe676167250)
successfully exited.

13:26:43.625 DEBUG Application:283                  TagReaderClient(0x7fe672dbba80)
successfully exited.

13:26:43.625 DEBUG SCollection:136                  CollectionWatcher(0x7fe672db8b40)
successfully exited.

13:26:43.625 DEBUG Application:283                  SCollection(0x7fe672d9d730) successfully
exited.

13:26:43.625 DEBUG DeviceManager:210                DeviceDatabaseBackend(0x7fe67603cb40)
successfully closed.

13:26:43.625 DEBUG Application:283                  DeviceManager(0x7fe67603f490)
successfully exited.

13:26:43.625 DEBUG TidalService:229                 CollectionBackend(0x7fe672e80fb0)
successfully exited.

13:26:43.625 DEBUG TidalService:229                 CollectionBackend(0x7fe672e812b0)
successfully exited.

13:26:43.625 DEBUG TidalService:229                 CollectionBackend(0x7fe672e813f0)
successfully exited.

13:26:43.625 DEBUG Application:283                  InternetServices(0x7fe6755124a0)
successfully exited.

13:26:43.674 DEBUG LyricsProviders:124              Unregistered lyrics provider
"LoloLyrics"

13:26:43.674 DEBUG LyricsProviders:124              Unregistered lyrics provider
"Musixmatch"

13:26:43.674 DEBUG LyricsProviders:124              Unregistered lyrics provider
"ChartLyrics"

13:26:43.674 DEBUG LyricsProviders:124              Unregistered lyrics provider "AudD"

13:26:43.674 DEBUG LyricsProviders:124              Unregistered lyrics provider "Genius"

13:26:43.674 DEBUG LyricsProviders:124              Unregistered lyrics provider
"Lyrics.ovh"

13:26:43.677 DEBUG CoverProviders:126               Unregistered cover provider "Qobuz"

13:26:43.678 DEBUG CoverProviders:126               Unregistered cover provider "Musixmatch"

13:26:43.678 DEBUG CoverProviders:126               Unregistered cover provider "Spotify"

13:26:43.678 DEBUG CoverProviders:126               Unregistered cover provider "Tidal"

13:26:43.678 DEBUG CoverProviders:126               Unregistered cover provider "Discogs"

13:26:43.678 DEBUG CoverProviders:126               Unregistered cover provider "Last.fm"

13:26:43.678 DEBUG CoverProviders:126               Unregistered cover provider
"MusicBrainz"

13:26:43.678 DEBUG CoverProviders:126               Unregistered cover provider "Deezer"

13:26:43.679 DEBUG >:178                            Closing worker socket

13:26:43.682 DEBUG >:178                            Closing worker socket


The error about the Verdana font being missing is a bit odd as it is in OS X by default.

**Comment by jonaski** [comment]
That explains it. macOS has version 6 of liblzma but libgstav is linked to liblzma version 8 from homebrew. So macdeploy needs to be fixed to bundle liblzma.

**Comment by jonaski** [comment]
```
jonas@Jonass-MacBook-Pro build % otool -L /usr/local/lib/liblzma.5.dylib 
/usr/local/lib/liblzma.5.dylib:
	/usr/local/opt/xz/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
jonas@Jonass-MacBook-Pro build % otool -L /usr/lib/liblzma.5.dylib      
/usr/lib/liblzma.5.dylib:
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
jonas@Jonass-MacBook-Pro build % 

```

**Comment by jonaski** [comment]
Try with the new build when it's available.

**Comment by clementine-user** [comment]
Success! Excellent job!

Thanks so much for all of your hard work!
