### ISSUE TITLE
Strange behavior when loading audio file + cue sheet

### ISSUE THREAD

**Issue by sylphenix** [strawberrymusicplayer/strawberry#345]
**Describe the bug**
When I load an audio file which has a cue sheet(with the same name) beside it, strawberry will ignore this single audio file and directly load the cue sheet. When I load a whole folder which contains audio file + cue sheet, strawberry will ignore the cue sheet and just load the single audio file. I think these behaviors are a bit unnatural. I'd really like to deal with audio file + cue sheet in this way:  When I load an audio file, strawberry would just load it alone, even if there’s a cue sheet with the same name. When I load a folder,  strawberry would load cue sheet first.  And if the cue sheet is loaded successfully,  strawberry then ignore the single audio file.

**Screenshots:**
![bugs](https://user-images.githubusercontent.com/59789740/72222313-5b3c3a00-359e-11ea-954d-18ce08f5bc9e.jpg)

**System Information:**
 - Operating system: Debian 10
 - Strawberry Version: 0.6.8

**Additional context**

**Comment by RomanHargrave** [comment]
I think that this behaviour should be configurable, as I tend to prefer the collection manager rather than the file browser. As such, for the few albums that I have stored in this manner, it would make more sense to have the file transparently treated as if it were multiple tracks at all times.

**Comment by sylphenix** [comment]
Yes, it’s better to be configurable. But I think the default behaviors should be simple and predictable. When loading a file, the player would load exactly the one I selected. When loading a folder, the player would load all the files that it contains. And there might be options, ignore cue sheet, or ignore the single audio when cue sheet is loaded.

**Comment by jonaski** [comment]
The supposed behavior is to load the songs in the cue, not just the single audio file, but it probably works best with the collection, when adding single folders and files it doesn't use the same scanner and that's probably why (but I didn't look into the code right now).

**Comment by jonaski** [comment]
The file view doesn't work very well with CUE when adding a whole directory, there isn't an easy fix. You should use the collection for it instead.
