### ISSUE TITLE
Please add a PPA/repository.

### ISSUE THREAD

**Issue by SuperSentient** [strawberrymusicplayer/strawberry#346]
**Is your feature request related to a problem? Please describe.**
I wish I could update the Strawberry Music Player the same I do with my other apps through the update manager. Instead of always having to manually update it, this would make updating much easier.
**Describe the solution you'd like**
A PPA/repository would solve this issue.
**Describe alternatives you've considered**
I mean I could always ask the Linux distro I'm using to add Strawberry Music Player to their software center but I much prefer having a PPA.
**Additional context**

**Comment by jonaski** [comment]
I know nothing about PPA, can they be used on many distros, or just Ubuntu?
Can you create a repository?

**Comment by SuperSentient** [comment]
PPAs are used both by Debian and Ubuntu based distros only. No I cant create a repository I don't no how to code/program I only have a GitHub account to report bugs or make suggestions sorry.

**Comment by NucleaPeon** [comment]
This should answer how to go about creating one: https://askubuntu.com/questions/71510/how-do-i-create-a-ppa

@jonaski 
However, it's an additional step when it's pretty straightforward to install debs. With the dropping of macOS versions, I get the impression you may not have time to deal with these intricacies. I wouldn't mind setting one up if you don't feel inclined to. Plus you have to agree to a Code of Conduct (tm) which may be another way Canonical et all get to bludgeon smaller projects with their politics and ideologies.

**Comment by jonaski** [comment]
I have set up 2 PPA's here: https://launchpad.net/~jonaski
It will automatically update from buildbot.
Configuration is in `MakePPABuilder` here: https://github.com/jonaski/strawberry-buildbot/blob/master/config/master/strawberry/builders.py
It doesn't currently work though.
I'm unable to update the PGP key, it wont accept it even though it's listed on the server.

**Comment by jonaski** [comment]
I think it's working now.
But this is ubuntu only:
https://launchpad.net/~jonaski/+archive/ubuntu/strawberry

**Comment by jonaski** [comment]
From now on https://launchpad.net/~jonaski/+archive/ubuntu/strawberry will only be updated with each stable release.
For the latest revision from git use: https://launchpad.net/~jonaski/+archive/ubuntu/strawberry-unstable

**Comment by jonaski** [comment]
The stable PPA is still updated even when INCLUDE_GIT_REVISION is set to ON.
If someone knows Python and can look into it, the function is MakePPABuilder in https://github.com/strawberrymusicplayer/strawberry-buildbot/blob/master/config/master/strawberry/builders.py
My Python knowledge isn't great.

**Comment by NucleaPeon** [comment]
@jonaski I'm a Full Stack Python developer, you can assign it to me and I can look into it.
I've used buildbot a long time ago and I'm not familiar with your setup. Could you clarify the problem you want to solve?

For instance, is it that you **don't** want the stable PPA to update when INCLUDE_GIT_REVISION is set to ON?

**Comment by jonaski** [comment]
Yes, that if statement is supposed to exit the function early if INCLUDE_GIT_REVISION is set to ON, that's what I was trying, maybe it's a better way to do it.
