### ISSUE TITLE
tag editing fails if edited track is playing

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#348]
**Describe the bug**
tag editing only is applied after playback to be restarted

**To Reproduce**
play any track with Strawberry
use "metadata inline edition" feature to edit artist or album tags of the track that Strawberry is playing (apparently the editing is not saved after we press enter)
double click on the edited track to restart playback: now the edited tag is updated

**Expected behavior**
any edited tag should be saved and immediately updated

**System Information:**
 - Operating system: Neon unstable edition (based on Ubuntu bionic)
 - Strawberry Version: 0.8.3

**Comment by jonaski** [comment]
I already fixed this bug in version 0.6.8. See the Changelog: https://github.com/jonaski/strawberry/blob/master/Changelog#L9
0.8.3 isn't a version.
Can you confirm what version you use?

**Comment by glaubersm** [comment]
Sorry for my mistake, I use version 0.6.8.
I can't reproduce this behavior with the same version on Arch Linux.
On Arch Linux Stawberry takes ~2 seconds to update the edited tag though.

**Comment by jonaski** [comment]
I can't reproduce that, but I see that it's difficult to use the inline editing when the metadata like bitrate is continuously updated on the current played track, I'll look into stopping that if one of the columns is edited
