### ISSUE TITLE
Organise files doesn't remove old folders

### ISSUE THREAD

**Issue by menaechmi** [strawberrymusicplayer/strawberry#353]
**Describe the bug**
When organising folders, Strawberry creates a new folder and moves the files to the new folder, but the old folder stays there, leading to a lot of empty folders.

**To Reproduce**

1. Update metadata on an album/artist
2. Right click album/artist name.
3. Select "Organise files..."
4. Ensure "Delete the original files" is selected
5. Select OK

**Expected behavior**
The files are moved into a new folder, and the old folders are removed.

**Screenshots:**
![strawberry_bug](https://user-images.githubusercontent.com/18483935/72686798-2bd28380-3af0-11ea-8b73-e0b3206cb957.png)

**System Information:**
- Operating system: Fedora 31 (Kernel 5.4.10-200)
- Strawberry Version: 0.6.7

**Additional context**

**Comment by jonaski** [comment]
Fixed now
