### ISSUE TITLE
Feature Request:  Ability to sort "Files" sidebar section

### ISSUE THREAD

**Issue by prg318** [strawberrymusicplayer/strawberry#355]
Hello,

I would love the ability to be able to sort the "Files" section of the sidebar.  It would be particularly useful to have the ability to sort the "Files" sidebar by "modification date".

Just as a use-case example:  I often use a file browser sorted by "recently modified" so that I can directly drag and drop music that may not have been added to my collection in my last rescan. It'd be wonderful to be able to accomplish this from the sidebar instead of a separate window.

This could probably be handled in the UI via a context menu on the "Files" section of the sidebar

(edit) An alternative UI approach would be to have a button in between the 'home' button and the path QLineEdit that opens a dropdown to let the user choose between the different sort options (name, modification time, filesize)

Thanks for all your hard work on strawberry - I really appreciate the effort.

**Comment by prg318** [comment]
![kdevelop-sorter](https://user-images.githubusercontent.com/549291/72907923-bdb1da80-3d02-11ea-94bd-8cad511b60e8.png)
The sorter used in the kdevelop filesystem sidebar may be a good example of how to implement this.

A toolbar icon to handle sorting seems more appropriate than menu items in the context menu .  The context menu items all pertain to the file itself and not the view.

**Comment by jonaski** [comment]
The file view should be rewritten to use a tree view and requires a lot more work than I have time for.
Considering that the functionality of the player is based around the collection and that's what most users use, it's not prioritized.
