### ISSUE TITLE
Odd behaviour with album artist

### ISSUE THREAD

**Issue by Isaacson33** [strawberrymusicplayer/strawberry#357]
**Describe the bug**
Strawberry collection tab is not respecting the album artist data. The screenshot shows the collection tab organised as if the songs' album artist was 'Various Artists', when the song's information shows it to be the same as the artist.

I've restarted, and refreshed the database, and I've removed the scanned folder and re-added it.

I've attached a screenshot of a query on Strawberry's database '.local/share/strawberry/strawberry/strawberry.db' showing the database's idea of albumartist.

This occurred after I used the Organise Files option and, ignoring the actual song information, it organised the files under a 'Various Artists' directory.

It's probably something to do with https://github.com/strawberrymusicplayer/strawberry/issues/288#issue-515539769, but supposedly that exact problem was fixed back in November and I presume 0.6.8 is newer than that?

![Screenshot_20200127_171418](https://user-images.githubusercontent.com/37577337/73200043-f4865700-412d-11ea-878e-11af505ab807.png)
![Screenshot_20200127_171657](https://user-images.githubusercontent.com/37577337/73200097-0c5ddb00-412e-11ea-80fe-2ef73d6744b5.png)

**System Information:**
Kernel: 4.19.97-1-MANJARO x86_64
strawberry  0.6.8

**Comment by jonaski** [comment]
You emitted the relevant parts.
Same album and directory with different album artist = compilation. If Album artist isn't set, then it's using artist.
Are you not understanding what album artist is?

**Comment by Isaacson33** [comment]
> You emitted the relevant parts.
> Same album and directory with different album artist = compilation. If Album artist isn't set, then it's using artist.
> Are you not understanding what album artist is?

I'm not following you I'm afraid. Here's what I've got, two albums both called 'Live' but both by different artists (ie, **not** one album called 'Live' by various artists). I've tried to reflect that by telling the application that the artist for 'Tangled Up In Blue' on album 'Live' is 'K.T.Tunstell' and the album artists (the one whose album 'Live' is) for that song is also 'K.T.Tunstell'.

I'm not sure what other input I could have entered to get that result. The screenshot below shows a listing for a song in the album 'Live' (a different album). The artist is 'Kate Rusby', the album is 'Live' and the album artist is 'Kate Rusby'. Somehow, given these three bits of data, the collection has organised it under 'Kate Rusby' (my collection is organised by album artist>album, by the way).

It seems to me like this song has exactly the same format of metadata as the ones I'm having problems with - Album is 'Live' in both cases and Album Artist is the same as Artist in both cases. Yet in one the collection shows them as 'Various Artists', whereas the other is shown under album artist.

Even if the behaviour were consistent, it's not respecting the metadata. The collection tab clearly offers 'group by Album Artist/Album'. The 'Album Artist' in neither case is 'Various Artists', its the same as the Artist.

![image](https://user-images.githubusercontent.com/37577337/73246605-f17b7d00-41a6-11ea-8518-233547f60397.png)

**Comment by jonaski** [comment]
The compilation detection works independent of "group by", the purpose is if you have an album with multiple artists, you don't want each artist on the album to be listed individually in the collection.
Previously before my fix it detected compilations by album only, so I changed it to work on directory + album. This way it doesn't treat 2 albums with the same title by 2 different artists as a compilation. So the only way it gets detected as a compilation is if it's set as a compilation in the metadata tags, or if it's songs with same album title in the same directory.
So either compilation is set in the metadata or the 2 songs with the same album title are in the same directory.
(I realize that maybe it could always set compilation to off for song where album artist is set, but it's pretty rare that you have 2 albums with same same title in the same directory).

**Comment by Isaacson33** [comment]
> I changed it to work on directory + album. This way it doesn't treat 2 albums with the same title by 2 different artists as a compilation. So the only way it gets detected as a compilation is if it's set as a compilation in the metadata tags, or if it's songs with same album title in the same directory.

Brilliant, thank you. The songs were all just in my main 'Music' directory, unsorted, so that will be why it was picking them up that way.

One odd consequence of this behaviour though is that if the tracks are unsorted (as mine usually start off), I then edit the meta data to define the album artist, the 'Organise' Files' feature will ignore the meta data and put them in the same directory 'Various Artists' From then, it becomes a self-fulfilling prophecy they're in the same directory (therefore the same album), but only because the Organise Files feature put them there without me knowing it was going to - hence the confusion.

Easy to workaround though, I'll file my songs by directory first before doing any further meta data work or organising.

Thanks again.
