### ISSUE TITLE
Add option to increase lyrics font 

### ISSUE THREAD

**Issue by cipricus** [strawberrymusicplayer/strawberry#362]
That is available in Clementine under "Song info" tab, with right click on lyrics area

![x](https://user-images.githubusercontent.com/3447868/73611957-d1edb580-45e7-11ea-9689-02bc86708608.png)

Also under "Preferences", "Song information", "Font size"

![mmm](https://user-images.githubusercontent.com/3447868/73612573-25aecd80-45ed-11ea-84d6-1b7464738e0a.png)

Strawberry shows lyrics under "Context" tab, but there is no font setting for them.

It would be nice to have this option just  like in Clementine.

**Comment by jonaski** [comment]
On Linux you can increase the font sizes using qt5ct, it will affect both playlist and lyrics:

![image](https://user-images.githubusercontent.com/10343810/75717672-d59d5680-5cd1-11ea-980c-07fe83952404.png)
