### ISSUE TITLE
Last.FM Invalid API Key

### ISSUE THREAD

**Issue by dweee** [strawberrymusicplayer/strawberry#365]
**Describe the bug**
When linking my Last.FM up to my fresh build of the strawberry-full-git AUR package, I authorise the app on the tab that opens and it gives me the error Invalid API Key on the Last.FM website.

**To Reproduce**
1. Unlink any account already linked or use fresh install of Strawberry
2. Attempt to link Last.FM account
3. Recieve error on Last.FM website

**Expected behavior**
My account to link up as expected.

**Screenshots:**
![Screenshot_20200206_205337](https://user-images.githubusercontent.com/5091497/73977835-f668cb00-4922-11ea-8dea-945d4961eed0.png)

**System Information:**
 - Operating System: Manjaro KDE
 - Strawberry Version: https://aur.archlinux.org/packages/strawberry-full-git/ 0.6.8.r1.g04f43e77-1

**Additional context**
It used to work before I had to reinstall my OS.

**Comment by jonaski** [comment]
Works here. What browser do you use?

**Comment by dweee** [comment]
Firefox. Didn't think about that actually. I'll test it on surf and chromium/iridium.

**Comment by dweee** [comment]
Woah that's odd, I've just tried it on Firefox because I forgot to check if my extensions were blocking it, I didn't change anything and it started working all of a sudden? It's just really baffling because I've been trying for the past week as I thought someone else would run into it. Anyways, issue fixed I guess? Thanks :)

**Comment by NucleaPeon** [comment]
@dweee There was a point in time where Brave Browser did not implement `window.prompt` and I had to check for the presence of that function in my code. Glad to hear your browser issue is resolved; I use last.fm frequently.
