### ISSUE TITLE
Adding Files or Folders

### ISSUE THREAD

**Issue by lvsunz3748** [strawberrymusicplayer/strawberry#367]
**Describe the bug**
When adding files or folders to an existing Playlist I get message 'loading tracks 0%' - don't know if this is normal or a bug?
**To Reproduce**
Steps to reproduce the behavior.
Just try to add a file or folder to an existing Playlist.
**Expected behavior**
Expect file or folder to be added to existing Playlist.
**Screenshots:**
![image](https://user-images.githubusercontent.com/7585657/74377396-ab264080-4d98-11ea-8465-dab75dd396c3.png)

**System Information:**
 - Operating system: Win 10, 64 bit.
 - Strawberry Version:

**Additional context**

**Comment by lvsunz3748** [comment]
Now all of my Playlists say 'Loading Tracks 0%.'

**Comment by jonaski** [comment]
Usually occur if something is blocking strawberry-tagreader.exe
Check DEP, antivirus and system logs. Check that strawberry-tagreader.exe exists.

**Comment by lvsunz3748** [comment]
Thanks very much Jonas. Strawberry Tag Reader.exe exists but I did add Strawberry to AV 'white list' and it is definitely working to resolve problem. Again, much appreciated.
