### ISSUE TITLE
Support for Discogs

### ISSUE THREAD

**Issue by alekksander** [strawberrymusicplayer/strawberry#368]
This is a request for support of [discogs api](https://www.discogs.com/developers) in order to autocomplete albums from their database. For me it seems that their database is more complete. There are times i cannot find certain releases on musicbrainz. I don't see why these two services shouldn't complement each other by both being available in strawberry. Thank You

**Comment by jonaski** [comment]
I don't see any way to search for tags based on fingerprint or musicbrainz id's, so how is it done?
Also, the rate limiting is too strict, only 60 requests per minute.

**Comment by alekksander** [comment]
i've seen it working perfectly as plugin in which one have to login (OAuth) first. So having discogs accounts is mandatory, however i decided to ask for this feature since strawberry can already login into various music services. in this plugin searching was done by tags, or manually by entering release id from discogs. each release has it's own id (duh) which is visible in address bar.

![image](https://user-images.githubusercontent.com/3148302/75092134-31027280-5575-11ea-87c2-5bff2a19503c.png)

is this any help?

**Comment by jonaski** [comment]
That's manual searching for tags and can't really be compared to musicbrainz automatic tag fetching.
It would have to be implemented differently, you need to pick which files belong to which track # etc.

**Comment by jonaski** [comment]
I'm closing this since I don't have time to prioritize it. Someone else is free to make a proposal for this feature in a PR.
