### ISSUE TITLE
Add the Launchpad repo for installing Strawberry on Ubuntu to main site

### ISSUE THREAD

**Issue by NucleaPeon** [strawberrymusicplayer/strawberry#372]
On https://www.strawberrymusicplayer.org, you have links to strawberry packages for various distributions. I think it makes sense to also have steps to install via the Ubuntu launchpad repo on that page as well:

    sudo add-apt-repository ppa:jonaski/strawberry
    sudo apt-get update
    sudo apt-get install strawberry

It may also be desirable to have a link that allows users to have the repo added via a link:
https://askubuntu.com/questions/47850/is-it-possible-to-install-a-repository-via-a-web-clicking-in-a-webpage-link?noredirect=1&lq=1

**Comment by jonaski** [comment]
Done
