### ISSUE TITLE
Any files containing "MAC" recognized as Monkey Audio

### ISSUE THREAD

**Issue by ozzyan** [strawberrymusicplayer/strawberry#373]
Hello there and thanks for the great software. Been using Clementine and switched to Strawberry - happy camper except for this strange bug which annoys me somewhat :)

Strawberry recognizes text files which include the word MAC as Monkey Audio files. I store foo_dr txt files along with the music (FLAC exclusively) and if they include the word **MAC_** they get treated as Monkey Audio files. They get included in the library/collection and also appear in the playlist if you drag & drop a folder to the main playback window. If you open the files and change the word MAC to anything else the player now recognizes these as txt files and they get removed from the library. I have attached one such file (Fleetwood **MAC**) so you can try for yourselves.

[foo_dr.txt](https://github.com/strawberrymusicplayer/strawberry/files/4252509/foo_dr.txt)

It seems that the word MAC has to be uppercase and followed by an empty (space) character, just like in this file:

[just_mac.txt](https://github.com/strawberrymusicplayer/strawberry/files/4252552/just_mac.txt)

The issue is present on both Linux and Windows Strawberry versions, absent in Clementine.
Many thanks!

![mac](https://user-images.githubusercontent.com/11768278/75294134-f2481300-5827-11ea-91b5-e46822708998.jpg)

**Comment by jonaski** [comment]
The extension doesn't matter, it's identified by content, anything containing "MAC", the problem is here: https://github.com/strawberrymusicplayer/strawberry/blob/master/3rdparty/taglib/ape/apefile.cpp#L95

**Comment by plonibarploni** [comment]
> The extension doesn't matter, it's identified by content, anything containing "MAC", the problem is here: https://github.com/strawberrymusicplayer/strawberry/blob/master/3rdparty/taglib/ape/apefile.cpp#L95

This code is present in Clementine as well, so why doesn't this issue appear in Clementine? 

> The issue is present on both Linux and Windows Strawberry versions, absent in Clementine.

**Comment by jonaski** [comment]
![image](https://user-images.githubusercontent.com/10343810/78571559-9f9a4780-7826-11ea-8d78-e34b11dc568e.png)

**Comment by jonaski** [comment]
@plonibarploni  I can reproduce the exact same thing with Clementine. Are you sure you compiled Clementine with `-DUSE_SYSTEM_TAGLIB=OFF` and you are using an up-to-date source with updated taglib?

**Comment by plonibarploni** [comment]
I'm using the Clementine packaged with Ubuntu.

**Comment by jonaski** [comment]
I have removed the file detection by content, so it only detects the file by file extension, it fixes the issue and shouldn't be a big deal if it can't detect files by a different extension than .ape for just this format.
