### ISSUE TITLE
Refresh Subsonic Library

### ISSUE THREAD

**Issue by revswim** [strawberrymusicplayer/strawberry#374]
**Is your feature request related to a problem? Please describe.**
When I add music to my subsonic library and update it in subsonic, the new songs wont appear in Strawberry but in Clementine I am able to refresh the library.

**Describe the solution you'd like**
Ability to right click subsonic tab and select "refresh catalog"

**Describe alternatives you've considered**
In the preferences where you input your subsonic login, there could be a refresh button.

**Comment by jonaski** [comment]
What happens if you click the "refresh catalogue" button?
