### ISSUE TITLE
Support for MPEG-H part 3 (codec mha1) for music 3D (360 by deezer or tidal)

### ISSUE THREAD

**Issue by Superhackman** [strawberrymusicplayer/strawberry#375]
there will be some way that this player supports this codec and now what I have seen only supports deezer and tidal
Here is a half info:
Percy Faith & His Orchestra\Percy Faith & His Orchestra - Joy\Percy Faith & His Orchestra - Sunrise, Sunset _ Fiddler On the Roof.mp4
Format                      : MPEG-4
Format profile              : Base Media / Version 2
Codec ID                    : mp42 (mp42/isom)
File size                   : 28.7 MiB
Duration                    : 3 min 20 s
Overall bit rate            : 1 202 kb/s
Encoded date                : UTC 2019-10-09 00:06:03
Tagged date                 : UTC 2019-10-09 00:06:03

Audio
ID                          : 1
Format                      : mha1
Codec ID                    : mha1
Duration                    : 3 min 20 s
Source duration             : 3 min 20 s
Bit rate                    : 1 198 kb/s
Stream size                 : 28.7 MiB (100%)
Source stream size          : 28.7 MiB (100%)
Encoded date                : UTC 2019-10-09 00:06:03
Tagged date                 : UTC 2019-10-09 00:06:03

**Comment by Superhackman** [comment]
Will this help any?
https://hls-js-latest.netlify.com/api-docs/source.html
https://hls-js-latest.netlify.com/api-docs/function/index.html#static-function-isCodecSupportedInMp4
https://hls-js-latest.netlify.com/api-docs/file/src/utils/codecs.ts.html

**Comment by jonaski** [comment]
Whatever gstreamer or VLC supports. We don't have Tidal or Deezer anymore.

**Comment by Superhackman** [comment]
@jonaski you misunderstood me, the deezer or the tide or any other forget it, I didn't mean what you think
The request that I request is that if it is possible to add support to the mha1 codec (MPEG-H) which is a 3D music audio codec that was recently released by MPEG and also Fraunhofer Institute for Integrated Circuits IIS released the development kits or rather MHAPI plugins that I don't know if this could work for media players like this one to support that codec, so you can make the request here: https://www.iis.fraunhofer.de/en/ff/amm/dl/ software / mhapi.html
