### ISSUE TITLE
Album cover as big as Clementine and not scrolling

### ISSUE THREAD

**Issue by gianlucapettinello** [strawberrymusicplayer/strawberry#377]
It would be great if the album cover is resized as big as it was in Clementine and not scrollable so when you scroll the lyrics it is always visible.
Also with version 0.6.8 if you want to change the album cover of a song with an album cover defined by the album it was not possible. With the git it seems possible. Is it fixed?

BTW thanks for all the work you do
Cheers
Gianluca

**Comment by jonaski** [comment]
It's not possible to make the album cover visible when scrolling in the context.
As for the album cover not updating, if you got the option in collection settings checked for "save album cover in album directory", you need to also check the option for overwrite existing file.

**Comment by gianlucapettinello** [comment]
Is it possible to have the album cover at the bottom in a separate area vs the context? Sorry for bothering you again
