### ISSUE TITLE
Background color not applying

### ISSUE THREAD

**Issue by amithiel** [strawberrymusicplayer/strawberry#378]
Hi there!
Settings/appearence/use custom color set -» the background colors are not applying (and foreground) no matter what i chose.

Strawberry version: Version 0.6.8
OS: Manjaro XFCE 19.01
XFCE version: 4.14

What else do you need from logs?

**Comment by jonaski** [comment]
It works here. I also use XFCE, but on openSUSE tumbleweed, it has the newest version of Qt which also Arch has.
This has to be system related, probably theme settings, or something that is set with qt5ct overriding the settings.
I'm not sure logs will help in this case. So I would suggest to try different settings in XFCE Appearance settings and check qt5ct settings.

**Comment by amithiel** [comment]
Hi, you are right :).
In manjaro settings there's an app called "Kvantum Manager" which does manage QT theming.
i managed to get dark theme on strawberry.
thanks

**Comment by jonaski** [comment]
Cool!
