### ISSUE TITLE
Support more tags, especially "work".

### ISSUE THREAD

**Issue by Agrotsa** [strawberrymusicplayer/strawberry#379]
My pop music collection is nicely organized by Strawberry and searches and new track additions to the collections work flawlessly. But I have also a lot of classical/art (from the latest 1500 years, not only of the classical period) music, and for this, the usual categorizing scheme "Artist-Album-Song title" doesnt work very well. In a Renaissance motet ?who is the "artist", the choir, the choir director, the instrument players -if there were any-, the composer himself...? Lets not talk about classical or romantic double or triple soloist concertos or giant works like Beethoven's 9th or Mahler's symphonies or contemporary symphonic music or operas.
So, here the usual scheme here is "Composer/Work/Performers/Track tittle" (there are people who like to use also tags for the director, soloists and singers, but I think that would be too much for a general purpose player like Strawberry, and the paths in the collection would be neverending).
Strawberry supports all those tags but "work". So, could it be possible to add support for it? Not only to show the works' titles in the player columns but also when adding tracks to the collection.

I've been using a schema  "Composer/Album/Performers/Track tittle", using "Album" as an equivalent for "Work", but this is a dirty hack since usually there are several works in a classical music album and I have to renounce to the album's title, which is a pity.
For example, let me relate a scenario that has happened to me this very afternoon: I riped a CD of  Blasco de Nebra's six keyboard sonatas, and wanted to tag it to be able to search the sonatas individually in the search box, sonata no. 1, no. 2, etc, so I had to set "Keyboard sonata no. 1" in the "Album" field for the tracks that pertain to that work. The problem is that doing so I lose the possibility to search by the album title, and that's a non minor lose because maybe sometimes I want to play the entire disc and not only one sonata, thus I'd need to be able to search by the title of the CD, which unsurprisingly is ""Blasco de Nebra piano sonatas", not "Sonata no. X".

If Strawberry supported the "work" tag, which is a tag that advanced taggers like Kid3 or Picard support perfectly, the "Album" tag could be for the album title, that's what it was intended for, all in all, and the work title have its appropriate space.

Also, if this is not asking for too much, why not supporting much more tags like "language", "lyricist", "disctotal" and some other supported tags in ID3 and vorbis tags, and that would allow, for example, to search portuguese/german/whatever pop songs, or song written by some writer you like... The use scenarios are very numerous, I'm sure you can think in a lot by yourselves. Increasing the number of supported tags would make Strawberry more adaptable to each user preferences.

Cheers

**Comment by lineinthesand** [comment]
I am neither an expert for strawberry nor id3 tags but I had a quick look at the taglib source code which does not seem to implement a "Work" tag by default. I looked at the kid3 GUI and didn't find a "Work" tag there but I suppose the "Opus" tag is meant to be used for that. Looking for opus in taglib only gave references to the Opus codec as results.
I might be mistaken but to me it looks like supporting more/non-standard tags would not be as straightforward as it may seem.

**Comment by jonaski** [comment]
I see no "work" tag documented for either id3v2.3 or Vorbis comments, and I've never heard of it.
There is a "conductor" tag for both though. It might be considered to be supported.
I'd like to that there is a need for additional tags from the community too, not just 1 person. Where do you get music tagged like them, do music that is purchased come pre-tagged with these, do CD-rippers use them, etc.
We got limited resources and almost no contributors except for me, and we are maintaining taglib ourself at this point so we can't possible do everything everybody wants.

**Comment by Agrotsa** [comment]
Hi, thanks @lineinthesand and @jonaski for taking the time to review my feature request.

I use KID3 for taging, and, more scarcely, Musicbrainz Picard, both my KID3 and Picard interface are not in english thus I could be wrong about the real name of the tag I am referring to, I'd swear that I have seen a "Work" tag somewere, but maybe I'm imagining it.
Nevermind. I don't have a computer with Picard at hand now, but let me show you a screenshotof KID3, so I hope you can see what I am talking about:

![Pantalla_20200605_185256](https://user-images.githubusercontent.com/52545292/83902852-affa7000-a74c-11ea-93bb-3e945cfc7030.png)


In the lower right frame you can see under the tag "Compositor" (Composer), the tag "Nombre de la obra" (literally "Name of the work). I'd swear to have seen this tag name in english as "Work", maybe it was in Pickard or who knows, but maybe I'm just wrong. The matter is that such tag for regietering a work's title does exist.

I understand that this would not be very useful for the majority of the users, and if you think that i'd be small benefit and a lot of work, I supose it's a reasonable decision discarding the proposal. You do enough giving your free time for free. I was just doing a suggestion that I think that the listeners of classical, soundtrack, jazz, and other musics that create big works with small individual tracks, would thank. But I'm, aware that those listeners are probably a very little minority.

**Comment by Agrotsa** [comment]
One last comment.
I was thinkig that maybe the tag "work" is indeed standarized. I have reminded that the Android app "Unpopular Music Player" uses it, I don't think that many other players do, though:

https://gitlab.com/AndreasK/unpopular-music-player

I'm still aware of the fact that most people doesn't listen to classical music, and the majority is ok without having this tag in Strawberry or any other player, but I wanted to comment it anyway, just in case.

**Comment by jonaski** [comment]
What KID3 call "Work" is actually grouping (TIT1), we already support that, both reading/writing tags and in the collection grouping.
See: https://id3.org/id3v2.3.0

**TIT1**

_The 'Content group description' frame is used if the sound belongs to a larger category of sounds/music. For example, classical music is often sorted in different musical sections (e.g. "Piano Concerto", "Weather - Hurricane")._

You can see this if you edit the grouping in Strawberry it will show up as "Work" in KID3. No idea why they call it that.

Use the forum if you have requests for other tags or features.
