### ISSUE TITLE
Supporting for multi language

### ISSUE THREAD

**Issue by 210hcl** [strawberrymusicplayer/strawberry#380]
I think it is a google software, but it seems don't have the opinion to choose the language of the UI.
Just have a menu to choose language, such as Simplified Chinese, or other language. This software is written by Qt, maybe it will not be difficult to do.

**Comment by jonaski** [comment]
The option is in Behavior / Language if it was compiled with translations support.

**Comment by 210hcl** [comment]
If I want to help to add Simplified Chinese to the UI, how can I do it?
界面没有简体中文，我想帮助加入简体中文。

**Comment by jonaski** [comment]
See https://github.com/strawberrymusicplayer/strawberry/wiki/How-to-translate

**Comment by jonaski** [comment]
@210hcl Chinese is 50% complete, can you complete it so I can include it?
It's done on https://translate.zanata.org/iteration/view/strawberry/master
