### ISSUE TITLE
Tidal service

### ISSUE THREAD

**Issue by fiercebrake** [strawberrymusicplayer/strawberry#384]
Greetings everyone,

Is there any chance for Tidal to be re-added in the near future ?

**Comment by jonaski** [comment]
No. They they have declined access to their API. Also, I don't like their business practices.

**Comment by Fef0** [comment]
@fiercebrake if you have an old version of Strawberry (with Tidal enabled), just use the iOS app token **GvFhCVAYp3n43EN3** in the "API Token" field. [An user](https://github.com/MusicPlayerDaemon/MPD/issues/545#issuecomment-577450533) suggested it in the MPD github page and I can confirm that it totally works even for Strawberry.
@jonaski I don't know if you can implement it via software, maybe Tidal will complain.

**Comment by jonaski** [comment]
FYI: Tidal was added back as of 0.6.10 (only gone in one version: 0.6.9).
