### ISSUE TITLE
Certain tracks are missing from collection

### ISSUE THREAD

**Issue by adueppen** [strawberrymusicplayer/strawberry#385]
**Describe the bug**
Despite the fact that they're most definitely on my hard drive, certain tracks do not appear in my collection, even after a full rescan. Opening one of the missing tracks in Strawberry manually works fine, and all the metadata seems correct. Searching for the name of the song in the collection view returns nothing.

**To Reproduce**
I've had the most issues with [this album](https://gilvasunner.bandcamp.com/album/second-wind-siivagunner-king-for-another-day-tournament-original-soundtrack-vol-2) specifically. It has 249 tracks in it, yet only 174 of them appear in my collection. I've tried rescanning my collection, as well as moving the album to a different folder, with no success.

**Expected behavior**
Since all 249 tracks of the album are in its folder, and are all tagged with the appropriate metadata, they should appear in my collection.

**Screenshots:**
![image](https://user-images.githubusercontent.com/6982070/76689499-73632080-6604-11ea-9325-f147b016d922.png)
(screenshot was taken in 0.6.3, but the issue persists in 0.6.8 as well)

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 0.6.8

**Additional context**
The majority of the missing songs have been in GiIvaSunner albums, but it happens with albums from a variety of artists.

**Comment by jonaski** [comment]
Did you check windows logs? Do you got anivirus or firewall blocking communication between strawberry.exe and strawberry-tagreader.exe?

**Comment by adueppen** [comment]
It doesn't seem like any communication is being blocked between strawberry and strawberry-tagreader. I'm just using Windows Defender, and I have both applications whitelisted in the firewall config. Is there any sort of verbose logging mode for Strawberry? Trying to run it from the command line using `-v` did nothing. I have also noticed that the missing tracks are loaded fine when I manually open one via Music > Open file or Playlist > Add file, but when I attempt to open the album folder with Playlist > Add folder, the missing tracks appear with no metadata and file type unknown, and attempting to play one gives "Resource not found." Loading a single file manually causes the track info summary to show its 8.3 filename, so is this perhaps part of the problem?

**Comment by jonaski** [comment]
Can you send me one of the problematic files on e-mail? jonas@jkvinge.net

**Comment by jonaski** [comment]
Discussed on e-mail. Most likely because of too long path names.
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
