### ISSUE TITLE
Value of "Track" column is not vertically aligned with the values of other columns in "Tag fetcher" window

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#388]
**Describe the bug**
Value of "Track" column is not vertically aligned with the values of other columns in "Tag fetcher" window

**To Reproduce**
add a track to your playlist
right-click on the added track, choose "Complete tags automatically..."

**Expected behavior**
Value of "Track" column should be vertically aligned with the values of other columns

**Screenshots:**
![tagfetcher](https://user-images.githubusercontent.com/15967631/76802076-a7ca0e80-67b5-11ea-9124-954ef49f88f4.png)

**System Information:**
 - Operating system: Arch Linux, KDE Plasma desktop environment 5.18.3
 - Strawberry Version: strawberry-full-git from AUR

**Comment by jonaski** [comment]
I've made it center the track number in the track column.
