### ISSUE TITLE
Strawberry Log file

### ISSUE THREAD

**Issue by NucleaPeon** [strawberrymusicplayer/strawberry#389]
**Is your feature request related to a problem? Please describe.**
I'm requesting a feature which is a log file that can report potential problems, unimplemented features and system statistics so when a user files an issue, they can upload the log file which will help diagnose issues quickly.

**Describe the solution you'd like**
Something along the lines of QLoggingCategory with statements like

    #ifdef Q_OS_WIN
        qWarning() << "WARNING: Audio CD Playback is not implemented on this platform";
    #endif

and a menu item in Help for viewing the log file (so people know it exists and how to get it).

**Describe alternatives you've considered**
Not applicable

**Additional context**
In particular, this idea came after reading closed issues #385 and the one which spawned #386.

**Comment by jonaski** [comment]
We already have an open issue for this, see #138
