### ISSUE TITLE
GTK theme is not being used

### ISSUE THREAD

**Issue by DAMO238** [strawberrymusicplayer/strawberry#391]
**Describe the bug**
My GTK theme is set to Arc-Dark, yet strawberry doesn't read the colours used by the theme, or the icons from my icon theme

**To Reproduce**
1. Install strawberry
2. Install lxappearance
3. Install Arc-Dark theme
4. Use lxappearance to change gtk theme and check the change with your favourite method (eg neofetch)
5. Open strawberry gui with system colours set in the options

**Expected behavior**
Should set colours to gtk colours

**Screenshots:**
![image](https://user-images.githubusercontent.com/32229196/77454589-a53c6a00-6df0-11ea-9bc8-aebd7159ef61.png)

**System Information:**
 - Operating system: Arch
 - Strawberry Version: 0.6.8-1

**Comment by jonaski** [comment]
You need to use qt5ct and set it to gtk2.

**Comment by DAMO238** [comment]
Thank you that worked great! For anyone else with this issue, you need a couple of packages:
qt5ct and qt5-styleplugins (may have different names on other non-arch based distros). Then open up qt5ct and set the style to gtk2, and launch your qt5 application with the environment variable QT_QPA_PLATFORMTHEME="qt5ct" and then it should use the correct theme. For more info, see [https://wiki.archlinux.org/index.php/Qt](url)

**Comment by LetrixZ** [comment]
This worked for Clementime but I can't get it to work on Strawberry.
[strawberry.log](https://github.com/strawberrymusicplayer/strawberry/files/6602066/strawberry.log)

**Comment by jonaski** [comment]
Maybe you are using the Qt 6 version of strawberry? You then the qt6ct instead.

**Comment by LetrixZ** [comment]
Yep, that did the trick. I also installed qt6gtk2.
