### ISSUE TITLE
Hide Left-Hand Sidebar

### ISSUE THREAD

**Issue by EmberHeartshine** [strawberrymusicplayer/strawberry#393]
**Is your feature request related to a problem? Please describe.**
I use Strawberry on a playlist basis only, and largely do not need the library functionality. I would like to be able to hide the left-hand sidebar to make it feel a little more like Foobar2000 (but with much better crossfade handling). This will also allow us to resize the window to be smaller because there is a fixed lower limit.

**Describe the solution you'd like**
Perhaps a toggle or menu item could be added to hide the sidebar.

**Comment by NucleaPeon** [comment]
I'm not sure which program it was, some kde software, but it was as simple as selecting the active sidebar tab  that would hide the entire thing. (Amarok maybe?) That's what I'm familiar with.

**Comment by clementine-user** [comment]
This feature is in Clemetine:

Tools > Show sidebar

If you could, please add this feature.
