### ISSUE TITLE
Option to change the left sidebar text color

### ISSUE THREAD

**Issue by zoli111** [strawberrymusicplayer/strawberry#394]
If a light theme is used in the sidebar, the letters are not visible.
![screen](https://user-images.githubusercontent.com/57037245/77793372-35d1af00-706a-11ea-96a1-863c084abc08.png)

**Comment by jonaski** [comment]
I'm closing this since this is only a minor detail, and I don't have time to prioritize it. Anyone else is free to make a proposal for a change in a PR.
