### ISSUE TITLE
LMS: track numbers not displayed

### ISSUE THREAD

**Issue by abdulocracy** [strawberrymusicplayer/strawberry#395]
**Describe the bug**
When streaming via Subsonic API from an LMS instance, the track numbers of tracks are not displayed, and albums are played in seemingly random order.

**To Reproduce**
Stream music from an LMS server.

**Expected behavior**
Track numbers are displayed and albums are added to the playlist in track order.

**Screenshots:**
https://imgur.com/hOcATaV

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: strawberry-git from the AUR

**Comment by jonaski** [comment]
Try with this fix: https://github.com/strawberrymusicplayer/strawberry/commit/144ffbc4282d9d80005786dece0a3b8bb2201625
Does it show year correctly?

**Comment by abdulocracy** [comment]
> Try with this fix: [144ffbc](https://github.com/strawberrymusicplayer/strawberry/commit/144ffbc4282d9d80005786dece0a3b8bb2201625)

Tried, fixes the issue. Thanks a dozen. :)

> Does it show year correctly?

Year and Original year are not displayed.

**Comment by jonaski** [comment]
Try now with https://github.com/strawberrymusicplayer/strawberry/commit/c424b0c888a661909439a9d980d50614fb2904e2 and https://github.com/strawberrymusicplayer/strawberry/commit/5db8b743fee008adedca416d28e96fa6aac822c5
I've only tested the changes with Airsonic.

**Comment by abdulocracy** [comment]
Year, original year and length are properly displayed now.
