### ISSUE TITLE
Add equalizer for VLC backend

### ISSUE THREAD

**Issue by jonaski** [strawberrymusicplayer/strawberry#4]
Fix analyzer and equalizer

**Comment by jonaski** [comment]
This is fixed now. Committing the changes ASAP.
Analyzer and equalizer still does not work.

**Comment by jonaski** [comment]
Analyzer is not possible with VLC. Equalizer should be possible.

**Comment by alekksander** [comment]
isn't equalizer against „bit-perfect” idea? by the way i think the same principle stand for buit–in volume slider.

**Comment by jonaski** [comment]
Yes, but it doesn't affect anything unless it's enabled and removing it could possible lose lot's of users.
SW volume is in the engine even if it's visible in the player or not, even deadbeef which uses alsa directly has a sw volume. Of course there could be an option to disable it, that would probably just mean it would be at 100%.

**Comment by jonaski** [comment]
Don't have time to do this and will focus on GStreamer.
