### ISSUE TITLE
crash when opening notification settings if main window on non-primary monitor

### ISSUE THREAD

**Issue by edgimar** [strawberrymusicplayer/strawberry#402]
**Description**
See title.

**To Reproduce**
1. Run Strawberry - place main app's window on the primary monitor (Windows 10)
2. Open settings, and ensure that "notification type" is set to "Show a pretty OSD"
3. Click on a different settings tab (e.g. "Behavior")
3. Save/close settings
4. Move main app window to non-primary monitor
5. Quit (exit) main app (so it isn't running in the background)
6. Re-start main app
7. Open settings and go to Notifications tab  -- **CRASH**

**System Information:**
 - Operating system: MS Windows v 10.0.18363.693
 - Strawberry Version: 0.6.8-11-g3791d11

**Comment by jonaski** [comment]
I'm pretty sure this is already fixed. But I also did some changes to the OSD Pretty yesterday that could fix a potential null pointer crash. But I can't reproduce it with earlier builds either.
Can you try with the latest one on (0.6.8.114): https://builds.strawberrymusicplayer.org/windows/
Important that it is newer than 0.6.8.106

**Comment by jonaski** [comment]
Let me know if it still crashes with 0.6.9

**Comment by edgimar** [comment]
btw, just confirmed that the bug is fixed in 0.6.9-19-g6331a061.
