### ISSUE TITLE
Cannot move the "Title" column

### ISSUE THREAD

**Issue by breversa** [strawberrymusicplayer/strawberry#403]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
In the tracklist view, I can move/reorganise any column, except "Title", which stays in the first place.

**To Reproduce**
Load tracks
Try to move the columns order (i.e. Artist - Title- Album)
"Title" stubornly stays in the first place :-)

**Expected behavior**
"Title" can be moved like any other column

**Screenshots:**
None provided

**System Information:**
 - Operating system: Linux Mint 19.3
 - Strawberry Version: 0.6.8

**Additional context**
N/A

**Comment by breversa** [comment]
Fixed already ? :D

**Comment by jonaski** [comment]
Yes, but it will work only with Qt 5.11 or higher, it's a limitation in Qt. I will make a new release in a few minutes that will include the fix.
