### ISSUE TITLE
Some characters in filenames are omitted when copying/moving to collection

### ISSUE THREAD

**Issue by breversa** [strawberrymusicplayer/strawberry#404]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
When copying/moving ("organizing") tracks to my music folders, several special characters are simply omitted from the filename, such as :
- `<`
- `>`
- `_`
- `.`
- `:`
- `|`
- … and probably many others

**To Reproduce**
Have tracks with "problematic" characters
Select them to copy/move them to collection
Configure a naming option that uses those characters
Witness that those characters are missing from the filenames, even when "Limit to FAT/ASCII characters" is NOT checked

**Expected behavior**
All the characters are retained in filename when copying/moving to collection.
I listen to many bands/tracks that have unusual characters in them (very common in industrial music… or simply for russian/asian/whatever bands with non-latin characters) and missing those characters really messes up my collection. Also, except for `\`, Linux can take any character. :-)

**Screenshots:**
![image](https://user-images.githubusercontent.com/2071276/78899346-918e3600-7a75-11ea-9f66-c3a2175034cc.png)
Here's a sample of many unusual characters in artist or track names. See how some are problematic, while some are totally fine.

**System Information:**
 - Operating system: Linux Mint 19.3
 - Strawberry Version: 0.6.9

**Additional context**
Also, "Overwrite existing files" doesn't seem to work either, when you have duplicates (= same music/metadata in files having different filenames).

**Comment by jonaski** [comment]
It' true that it stripped problematic filename characters independent of the FAT option, those were '\', '"', '*', '\', ':', '<', '>', '?', '|', '/' and '.'. But not underscore. I've changed the behavior now to only strip slash and backslash unless the restrict to FAT characters isn't checked.

The overwrite existing files only works on filenames, not song metadata.

**Comment by breversa** [comment]
You're always so fast to reply ! :-)

However, as you might have noticed, I also have band/track names with `\` (much rarer, I concur, but still), so it'd be better to keep them too.
IMO, only `/`should be removed (at least for Linux systems).

As for the overwriting problem, it also happens with Clementine. I'll open a new issue with more details. :-)

**Comment by jonaski** [comment]
I know but there are so many file systems on Linux, and the files might be on FAT32 even on Linux, so I rather not allow / or \ at all.

**Comment by breversa** [comment]
But since you have a dedicated FAT option (which is good !), why strip more characters than strictly needed when this option is _off_ ?

**Comment by jonaski** [comment]
I actually stripped out all non-FAT characters from filenames in my entire music collection, this way I can easily copy the files over on a FAT32 HDD that I use in my car, since it does not read any other filesystems, the same for potable music devices, not sure you want special characters in filenames at all since a music player reads the tags anyway.

**Comment by jonaski** [comment]
I use ext4 and I can actually have both slash and backslash in both paths and filenames, not sure if it's a good idea though, and not sure how it behaves on other filesystems.

**Comment by jonaski** [comment]
I just realized why I made it strip those characters in the first place, NTFS does not handle /, \, :, *, ?, ", >, < and |. So either there needs to one more option, or we need to revert my changes.

**Comment by breversa** [comment]
Sure, I understand the use for a FAT-compatible character-stripping, but since I mainly use ext4 myself, I don't see why I should harmonize downwards.

Why not give a choice between :
1. Don't strip anything (default)
2. Strip non-FAT/ASCII characters (options)
3. Wait for another issue to pop here (= don't over-engineer)
? :-)

**Comment by breversa** [comment]
That makes sense !

I for one would love to have options for stripping non ASCII, FAT, and NTFS characters, and not strip anything (or maybe only `/`) by default. :-)
Anyway, thanks for taking the time to look into this issue !

**Comment by jonaski** [comment]
I'm not sure how it would behave code-wise if there are directory separators in the filenames, QDir::mkpath() and QFile::copy(), those have to be escaped somehow.

**Comment by breversa** [comment]
I'm no dev, but how did Clementine (which did a good job for that IMO) handle it ?

**Comment by jonaski** [comment]
Clementine doesn't allow slash and backslash either.

**Comment by breversa** [comment]
Well, I could go with that if you were to implement it. Thank you @jonaski !
