### ISSUE TITLE
Wrong jacket shown when playing tracks from Airsonic

### ISSUE THREAD

**Issue by KingDuckZ** [strawberrymusicplayer/strawberry#405]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Some albums from my Airsonic collection have been associated with the wrong cover image.

**To Reproduce**
I really can't see a pattern. Looking around it seems that only albums with unicode titles (Japanese, Russian) are affected, but only a few. I can give access to my server if it's useful for testing.
I can confirm that if I access Airsonic from Firefox and look at the "now playing" view on the right, the cover displayed there for the album being played by Strawberry is correct.

**Expected behavior**
The correct album cover should be displayed.

**Screenshots:**

**System Information:**
 - Operating system: Gentoo
 - Strawberry Version: 0.6.8

**Additional context**
Airsonic 10.5.0-RELEASE

**Comment by jonaski** [comment]
I got a pretty good idea why, but it would be nice to test it against a subsonic server with the affected albums, so could you send an e-mail with login to me, my e-mail address is listed on my github profile.

**Comment by jonaski** [comment]
Fixed now. The problem was that the cover filename is created from artist + album, and the filename is stripped for non-ascii characters and is too short in the case when there are Japanese characters, it will now fallback to using a SHA1 hash for the filenames in that case.

**Comment by KingDuckZ** [comment]
Thanks, I'll have to wait for the new version to hit gentoo, but it's good to know next version will fix this!
