### ISSUE TITLE
#include glib.h : No such file or directory 

### ISSUE THREAD

**Issue by HurricaneA** [strawberrymusicplayer/strawberry#407]
I'm getting an error saying that glib.h is not found and the compilation is terminated when I try to compile using make -j4. My glib is located on usr/include but the pkg-config --cflags --libs glib-2.0 is pointing to /usr/local/include, canany one help me with this? 

The error rises when compiling /ext/libstrawberry-common/core/logging.cpp

I'm using ubuntu 18.04

**Comment by jonaski** [comment]
Try adding
```
include_directories(${GLIBCONFIG_INCLUDE_DIRS})
include_directories(${GLIB_INCLUDE_DIRS})
```
In ext/libstrawberry-common/CMakeLists.txt below the existing include_directories lines.

**Comment by HurricaneA** [comment]
> Try adding
> 
> ```
> include_directories(${GLIBCONFIG_INCLUDE_DIRS})
> include_directories(${GLIB_INCLUDE_DIRS})
> ```
> 
> In ext/libstrawberry-common/CMakeLists.txt below the existing include_directories lines.

I'm getting the same error @jonaski

**Comment by jonaski** [comment]
Sounds to me like you got a different glib installation in /usr/local that it picks up the .pc file for.
Does this find more than one pc file? `sudo find /usr -name 'glib*.pc'`

**Comment by jonaski** [comment]
Closing this as this isn't a bug in Strawberry but a problem on your system.
