### ISSUE TITLE
Continue playlist where we left off when completing queue

### ISSUE THREAD

**Issue by Mershl** [strawberrymusicplayer/strawberry#408]
**Is your feature request related to a problem? Please describe.**
While playing an existing playlist and double clicking an intermission song (Add to the queue + Always start playing) Strawberry will report "Playlist has finished" after the playback of the intermission finishes.

**Describe the solution you'd like**
When playing an existing playlist I often like to immediatly switch to a double clicked file (the intermission track). After the playback of this file ended the playlist is continued where it left off - not necessary with the previously played track, but the one after the cut off track.

Example: 

- Playlist is consisting of 5 tracks: A, B, C, D, E. 
- We are currently in the middle of listening to C.
- Double clicking the intermission track F will immediatly start playback of F.
- After F is finished the playlist is continued with D.

**Describe alternatives you've considered**
I tried the "Add to Queue" behaviour. But it's not behaving as expected if immediate Playback is required. After the playback of the intermission Strawberry reports "Playlist finished".

**Comment by jonaski** [comment]
I think I understand what you mean, but I'm not exactly sure. You want to immediately play a song that isn't queued, then when that is finished you want it to resume the previous playing song, if that song wasn't finished. Right?

**Comment by Mershl** [comment]
> [...], then when that is finished you want it to resume the previous playing song, if that song wasn't finished.

This is debateable. Either the previously playing song is continued exactly where it was paused or we skip to the next track in the playlist.

To summarize the feature idea: There shall be a playlist playback and a queue playback. Once the queue playback is finished the playlist playback is continued where it left off (with the debateable topic above).

Example flow of the feature request:

    1.) Playlist is consisting of 5 tracks: A, B, C, D, E.
    2.) We are currently in the middle of listening to C.
    3.) Double clicking the intermission track F will immediatly start playback of F.
    4.) After F is finished the playlist is continued with D.

As of today Strawberry cancels playlist playback after the queue is finished - that's because the queue item is added to the end of the playlist and immediatly played (if requested) thus marking the playlist as finished after the queue track has finished.

Example flow today:

    1.) Playlist is consisting of 5 tracks: A, B, C, D, E.
    2.) We are currently in the middle of listening to C.
    3.) Double clicking the intermission track F will immediatly start playback of F and add it to the end of the playlist.
    4.) After F is finished the playlist is completed and the playback is stopped.

I would've expected the behaviour with the following setup:
![image](https://user-images.githubusercontent.com/520251/80821085-64e2bf80-8bd8-11ea-842a-76d3801083b6.png)

**Comment by Mershl** [comment]
I thought about this feature request some more. I think the issue can be summarized as:

There's an option in "Double clicking a song will..." to "Append to playlist" [meaning to the end of the playlist]. What I was looking for is append to playlist [after currently playing song].

Meaning in a playlist consisting of A [B] C D E (where B is currently playing) double clicking a song should insert it after B instead of after E.

**Comment by jonaski** [comment]
Closing this as this isn't a bug but rather user preference, and due to limited time and lack of other contributors I don't have time to do new features. Feel free to discuss it on the forum.
