### ISSUE TITLE
Long album names are cut off in cover manager

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#411]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Long album names are not entirely readable in cover manager.

**To Reproduce**
click on Tools menu > cover manager and observe the albums names.

**Expected behavior**
All albums names should always be entirely readable.

**Screenshots:**
![cover manager](https://user-images.githubusercontent.com/15967631/80306298-dcf45400-8798-11ea-9d2a-c85c4d9ec9ea.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.6.9

**Comment by jonaski** [comment]
I have no idea how this happened. Fixed now.
