### ISSUE TITLE
"Save cover to disk" feature of cover manager doesn't work as expected

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#412]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Strawberry always saves a generic cover instead of the right-clicked one.

**To Reproduce**
click on Tools menu > Cover manager
right click on the cover of any album, choose "Save cover to disk..."
and save the cover to your hd/ssd

**Expected behavior**
Strawberry should save the right-clicked cover to disk.

**Screenshots:**
Strawberry always saves this image:
![e5acd9dd0c09f039854d2d5c90cabb73e826eafc](https://user-images.githubusercontent.com/15967631/80306555-6d7f6400-879a-11ea-8cd7-8ffecb0e8d1f.jpg)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.6.9

**Comment by llucps** [comment]
This doesn't work on Subsonic panel. I can load from a cover disk or URL, and save it but next time I restart Strawberry it loads the default CD cover.

It's not a big deal but I wonder if there is an easy fix.

Thanks,
