### ISSUE TITLE
[linux] The same optical device is listed more than once in "Devices" tab

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#415]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
The same optical device is listed more than once in "Devices" tab

**To Reproduce**
open Strawberry
click on "Devices" tab in the left side

**Expected behavior**
optical devices should be listed once in "Devices" tab

**Screenshots:**
WH14NS40 optical device is listed three times when there is a disc inside it
![unreadable2](https://user-images.githubusercontent.com/15967631/80308557-167f8c00-87a6-11ea-96d6-de5bf6d8dfbc.png)

WH14NS40 optical device is listed twice when no disc is inside it.
![nodisc](https://user-images.githubusercontent.com/15967631/80308592-3fa01c80-87a6-11ea-8569-146174056a64.png)

**System Information:**
 - Operating system: Arch Linux, KDE Plasma 5.18.4 desktop environment
 - Strawberry Version: 0.6.9

**Comment by jonaski** [comment]
I cant reproduce this. Your optical device is probably listed somehow twice by your system. It could be picked up twice by two different listers, we use both CDDA, Udisks2 and GIO

**Comment by glaubersm** [comment]
I have just uninstalled GIO from my system.
Now partitions of internal hard disks are also listed in "Devices" tab.

**Comment by jonaski** [comment]
I got 3 computes with a DVD or bluray and they all list the optical drive just once, its possible that it's specific to your model. Some devices cant be identified as the same when unmounted and mounted.
This isn't possible to fix.
