### ISSUE TITLE
Use Subsonic's scrobbling instead

### ISSUE THREAD

**Issue by satcom886** [strawberrymusicplayer/strawberry#416]
When using Subsonic (or compatible server), a scrobbler can be configured in personal preferences. This means that you can configure the scrobbler once and supported clients will use it. The client-side configuration is as simple as checking a box. The client starts playing a song and the Subsonic server takes care of sending the info to the scrobbler service. In Airsonic, ListenBrainz and Last.fm are currently supported. I found how the scrobbling architecture in Airsonic works [here](https://github.com/airsonic/airsonic/issues/446)

I know that Strawberry already supports scrobbling but this would make configuration on multiple devices much simpler.

I would suggest adding a checkbox in Subsonic settings that would scrobble to Last.fm/ListenBrainz via Subsonic if scrobbling is not already enabled in Strawberry. This would have no effect if scrobbling in Strawberry is already enabled.

**Comment by jonaski** [comment]
We can create an option to select which type of songs that should to be scrobbled, based on the song::source enum.
