### ISSUE TITLE
Huge Gstreamer icon in "Context" tab

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#417]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
This bug only occurs on Arch + KDE Plasma.
I can't reproduce on Arch + Gnome.

**To Reproduce**
play something with Strawberry configured to use Gstreamer backend
click on "Context" tab in the left side

**Expected behavior**
size of Gstreamer icon should be normal

**Screenshots:**
![gstreamer](https://user-images.githubusercontent.com/15967631/80388123-e1476c80-887f-11ea-9b02-204e31e850f2.png)

**System Information:**
 - Operating system: Arch Linux, KDE Plasma 5.18.4 desktop environment
 - Strawberry Version: 0.6.9

**Comment by jonaski** [comment]
I can reproduce this when using the system tray icon option
