### ISSUE TITLE
Player doesn't play files from a NAS source

### ISSUE THREAD

**Issue by underlopex** [strawberrymusicplayer/strawberry#418]
**Describe the bug**
The Player is not capable to play music files from a NAS folder

**To Reproduce**
Open a music file from a NAS folder

**Expected behavior**
-the file must be played

**Screenshots:**
![imagen](https://user-images.githubusercontent.com/9980155/80661173-e3feb900-8a5b-11ea-89f7-6630d946f0a4.png)

**System Information:**
 - Windows 10
 - Strawberry Version 0.6.9

**Comment by jonaski** [comment]
The problem is non-ascii characters in UNC paths are not converted correctly when coverting to a bytearray, in your case `Música`. Should be fixed now, use the build with eb4ce1f in the name or newer when it's available, or rename your path.

**Comment by jonaski** [comment]
You can workaround the bug to by mounting a network drive.
