### ISSUE TITLE
Sometimes playback stops when a track ends

### ISSUE THREAD

**Issue by Gallaecio** [strawberrymusicplayer/strawberry#419]
Looks like #222, which was fixed in 0.6.1. However, I’m running 0.6.9, in Arch Linux.

**Comment by jonaski** [comment]
I completely changed the engine code in later versions, so it's possible that there is problem again.
Does it get stuck in play mode with the progressbar at the end? What file formats? Is there next song in the playlist a different format, or samplerate?

**Comment by Gallaecio** [comment]
> Does it get stuck in play mode with the progressbar at the end?

It gets stuck at 0% buffering of the following song.

> What file formats? Is there next song in the playlist a different format, or samplerate?

I did not though it may be reproducible with specific songs. I’ve now tried to catch it and reproduce it. I’ve seen it happen with two songs with the same bitrate, and also with songs with a different bitrate. More importantly, after it happens, if I copy those two song files into a separate folder, and create a new playlist only containing those two files, I cannot reproduce the issue.

If we assume 0.6.1 would work and build fine with the latest versions of dependencies, I wouldn’t mind trying to identify the version/commit where the issue was introduced. May that help?

**Comment by jonaski** [comment]
If it's stuck in buffering it might be because it's having issues reading the file from disk. Also, if it works when copying the files to a different directory I would suspect the HDD.

**Comment by Gallaecio** [comment]
I’ve been able to reproduce the issue with 0.6.1, so I guess it is not https://github.com/strawberrymusicplayer/strawberry/issues/222.

**Comment by jonaski** [comment]
Bitrate shouldn't matter, do you know if the songs have different sample rate or bit depth?

**Comment by Gallaecio** [comment]
```bash
[adrian@afonsox música]$ find . -print0 | xargs -0 mediainfo 2> /dev/null | grep -E '(Sampling rate|Bit depth)' | sort | uniq 
Bit depth                                : 24 bits
Bit depth                                : 8 bits
Sampling rate                            : 44.1 kHz
Sampling rate                            : 48.0 kHz
```

**Comment by jonaski** [comment]
This most likely a gstreamer problem or a system related issue. We don't use the same pipeline setup anymore that caused the issue in #222

**Comment by shawarden** [comment]
How does one go about troubleshooting gstreamer on Windows 10 when it's packaged with Strawberry?

This exact issue is happening on both Windows 10 and Ubuntu 20.04 for me, each accessing files different samba storage servers.
