### ISSUE TITLE
With shuffle all checked, clicking on next track button doesn't scroll to the playing song.

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#420]
**Describe the bug**
With the shuffle all button checked, after manually click to play the first song, and then clicking on the next track button, the playlist doesn't scroll to that next song. I have to click CTRL+J or Jump to the currently playing track.

This only happens the first time yo do it, if you click "Jump to the currently playing track." then clicking on next track button it does scroll to the playing song. So it only happens the first time.

**To Reproduce**
From a playlist click to play a song which starts playing. With the shuffle all button checked, then click on the next track button, the next song starts playing but the playlist doesn't scroll to playing song.

**Expected behavior**
Clicking on next track button should scroll to the playing song.

**System Information:**
 - Operating system: MacOS 10.15.4 Catalina
 - Strawberry Version: 0.6.10

Thanks.

**Comment by jonaski** [comment]
What do you mean by scroll to the playing song?

**Comment by llucps** [comment]
Look at this video https://cloud.squeakyhost.com/s/dx5HooitEAHMBAp

Starts playing the first second just fine, then I click next track and starts playing the next song but the platylist doesn't scroll to the song, I have to hit CTRL+J to jump to the playing song.. Then after doing this I can click the next song button and it scrolls just fine.

Thanks.

**Comment by jonaski** [comment]
Looking at the code there is a 30 second gap between the time you click a song to play it to the time auto scrolling is done, so auto-scrolling will work again fine after 30 seconds, this is is done not to intervene with the user clicking I assume. Not sure if we want to change this or not, maybe the code could be improved, but I'm a bit hesitant to changing it, afraid I might create a problem.

**Comment by llucps** [comment]
If I undertstood you correctly, after clicking the play button if I wait 30s it will autoscroll automatically to that playing song? If so, then it doesn't work for me. The song keeps playing but it doesn't autoscroll.

When this first song ends and jumps to the next one then yes it autoscrolls but not with the first song.

I mean if you think it could break something or it could be a big deal.. then don't bother.. I can live with it :)

Thanks.

**Comment by jonaski** [comment]
It won't autoscroll at all if you switch song before the current song has played 30 seconds or less.

**Comment by llucps** [comment]
What I do.

- Open Strawberry
- I double click on a song in the playlist (The shuffle is already active be default). And the song starts playing.
- Click on Next Track button. Next song is playing but the playlist doesn't scroll even waiting those 30s, and I touch nothing.. just waiting.

Basically if I do what I said above.. songs are playing, the first, the second , the third etc.. but never scrolls to the playing song. 

Only when I click CTRL+J (Jump to the playing song) then when I click on next track button it scrolls on every song.

**Comment by jonaski** [comment]
It works here, if I wait for 30 seconds into the song I can click next and it scrolls.
Are you sure you waited 30 seconds?
Seems strange that the bug should occur on mac only.

**Comment by llucps** [comment]
See video

https://cloud.squeakyhost.com/s/anoN5n8K9QHXYmC

**Comment by jonaski** [comment]
I think you misunderstood. It won't scroll by itself, it will scroll only if you play a song for at least 30 seconds, then press next.

**Comment by jonaski** [comment]
In the last video you play a song first that's too short, then it switches to a new song, and I don't see you press next after that, in that case it wont' scroll. But maybe we could improve this.

**Comment by llucps** [comment]
It doesn't matter it happens with a 3 min song. 

Anyway in my opinion the behavior of this last video feels wrong. I think after playing the first 4 second song it should automatically scroll down to the second song.

But if it's complicated just forget about it. it was just an idea :)

Thanks.

**Comment by gianlucapettinello** [comment]
I have the same issue. I think it feels more consistent if the next button automatically scrolls the list to the currently playing song. It is an odd behaviour present also in Clementine. If you fix it strawberry overcomes clementine :)

**Comment by jonaski** [comment]
If the song is manually switching by pressing next it makes sense to auto-scroll, I can agree with that. The intenion with the 30 second delay for auto-scrolling is if the user is scrolling manually and it switches songs it will be annoying to autoscroll intervening with the manual scrolling, but when switching song manually that does not make sense, but it currently does not differentiate between those.
