### ISSUE TITLE
"Collection" browser with Artist subfolders in different paths only shows albums from the last path

### ISSUE THREAD

**Issue by EeVee0** [strawberrymusicplayer/strawberry#421]
**Describe the bug**
In **Tools > Settings > General > Collection**, I have two folders:
```
/music/flac
/music/mp3
```

I have subfolders for many bands inside each of the **Collection** folders above, but two bands are in both:

```
/music/flac/Hepcat
/music/flac/The_Slackers
/music/mp3/Hepcat
/music/mp3/The_Slackers
```

When I browse the **Collection** and expand _Hepcat_ or _The Slackers_ or when I use the **Collection** filter bar and search for either of these two bands, only results from the `/music/mp3` path are displayed.

There are four _flac_ albums in `/music/flac/Hepcat` and one _mp3_ album in `/music/mp3/Hepcat` and the **Collection** browser only shows the one _mp3_ album.  The same is true for _The Slackers_; I have 23 _flac_ album folders and nine _mp3_ album folders and the browser only shows the _mp3_ results.

For Artist subfolders that only appear in one of  `music/flac` or `/music/mp3`, the expected albums are displayed in the **Collection** browser.

The `/music/mp3` folder was added to my **Collection** after the  `music/flac` folder and _mp3_ comes after _flac_ alphabetically.

**To Reproduce**
- Have identical Artist folders in two different **Collection** paths.
- Update the collection.
- Restart Strawberry.
- Use the **Collection** browser (with or without the filter bar) to display albums for one of the identical bands.
- Notice only albums from one **Collection** path are presented.

**Expected behavior**
I would like to see all album results from all paths when I browse or filter the **Collection**.  Thanks.

**System Information:**
 - Operating system: openSUSE Tumbleweed
 - Strawberry Version: 0.6.9

**Comment by jonaski** [comment]
I'm unable to reproduce this problem at all. It definitely works here. It makes no sense to me at all that it should filter out an artist directory from one of the directories if the other directory has the same artist directory.

**Comment by jonaski** [comment]
I suggest to run strawberry from the terminal. Remove the directory that isn't working and readd it, then watch for any errors.

**Comment by EeVee0** [comment]
Thank you for checking this.  I closed Strawberry, removed `.local/share/strawberry/`, opened Strawberry, then rebuilt the **Collection** and the issue is no longer present.
