### ISSUE TITLE
Tidal can't reproduce

### ISSUE THREAD

**Issue by RenatohRibeiro** [strawberrymusicplayer/strawberry#422]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
When I click on a tidal song it shows an error

**Expected behavior**
Should play the song

**Screenshots:**
![image](https://user-images.githubusercontent.com/49354525/80918855-68438b80-8d3d-11ea-9b86-fee4405aa58d.png)

**System Information:**
 - Operating system: Arch+Xfce
 - Strawberry Version: 0.6.10

**Additional context**
O URI "rtmp.stream.tidalhifi.com/cfx/st/mp4:e9fa50315a7151414264fcb07912dfc6_37.mp4?Expires=1588525070&Signature=edv~hC6dZV-2dyf-ZdOs1Ss0KOJLORfBd1YoZDjT-Vbvy-sIe8d9SsPxs9gVd2X~z8zcBUJi8yMIHeHSA949usvz~e-LGv8wbK2465Q5QaRu7v~Hstzn5sZp55Jk-G0MePO2mmJ3Y-v4DlXNrw5gMMWCSGPfLv5h2hRHxSKmKeat5oO3pE3FNa2Yi5zbJde3MdlowBxd3atDLrBi329-MSl~QHfN30sLSTCXtmGNFy9QhOKcilvhPA0YwJ600nlhmEXjjEW~CRMoUOFPdTAYTuKH4ydqEFdY4FdXdgEXERuXS-PFyIVeeDypkhqSoP-60bdEZ1uLdRJ9xk7Zz8VI3g__&Key-Pair-Id=APKAIZ3WPBE4R6SP555A" é inválido.

**Comment by jonaski** [comment]
It works fine here. This is probably specific to the login method or the token you use. OAuth does not currently work. See #369 for more info.
