### ISSUE TITLE
CUE Sheets causing album title issues

### ISSUE THREAD

**Issue by jorong1** [strawberrymusicplayer/strawberry#423]
**Describe the bug**
For some CUE sheets, the TITLE entry isn't read at all from the CUE sheet, resulting in the album being grouped into Unknown, and resulting in incorrect album titles being used. The album title only shows when playing a track.

FLAC Tags,
> Album: Album Title is Here (Original Edition Release 1999)
Performer: Artist Name

CUE Sheet,
>PERFORMER "Artist Name"
TITLE "Album Title is Here"
FILE "Artist Name - Album Title is Here.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Track 1 is Great!"
    PERFORMER "Artist Name"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "This is Track 2"
    PERFORMER "Artist Name"
    INDEX 01 03:30:00

For other groups of CUE sheets, the CUE sheet "TITLE" entry is read first. After changing the track, the FLAC Vorbis tags are being read and shown in the Album section as the album title, instead of the CUE tag being used. I can't seem to reproduce trhis one as often.

**To Reproduce**
1. Load a random CUE sheet associated to a FLAC file
2. Check if the album title is shown
2a. If it's shown, play the track and then skip to another.
2b. Check if the album title changes, only if the file tags and CUE tags differ

**Expected behavior**
Album titles are always read from the CUE sheet "TITLE" entry.

**Screenshots:**
For the blank album title issue, here's a visual
![blankalbumtitle](https://user-images.githubusercontent.com/64753532/80926881-70291d00-8d89-11ea-9dfb-220839cc5c9a.jpg)

 I can't seem to replicate the 2nd CUE sheet issue as often

**System Information:**
 - Operating system: Arch Linux, Linux 5.6.8-arch1-1
 - Strawberry Version: 0.6.10

Thanks

**Comment by jonaski** [comment]
For the first issue, cant you see any difference in the cue file that could cause it not to read the album title from the cue file? Can you send me an example cue file that doesn't work?
Also note that the cue file and matching flac file needs to have the same filename, it's case-sensitive, and the cue extension needs to be lowercase.

The second issue can be explained, if the metadata is missing and it is read by gstreamer, then it updates the song in the playlist with the metadata received through gstreamer.
