### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by plonibarploni** [strawberrymusicplayer/strawberry#424]
**Describe the bug**
I get the following error when compiling strawberry:
`ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/build.make:61: *** target pattern contains no '%'.  Stop.`

**To Reproduce**
1. Clone the repo (or download the ZIP from GitHub).
2. run `cmake`.
3. run make.
4. After it reaches `[ 14%] Built target libstrawberry-common`, make will stop with the above error.

**Expected behavior**
strawberry should compile properly.

**System Information:**
 - Operating system: Ubuntu MATE 20.04
 - Strawberry Version: git master

**Additional context**
I recently did a fresh install after Ubuntu 20.04 was released. Previously, I had a git clone on 19.10 which I would update daily. I had no issues compiling there.

**Comment by jonaski** [comment]
You need to install protobuf-compiler
