### ISSUE TITLE
Feature Request: Ability to set Files "home" folder path

### ISSUE THREAD

**Issue by mattiaswerner** [strawberrymusicplayer/strawberry#425]
**Is your feature request related to a problem? Please describe.**
When using the snap build, the Home button leads to (currently): ~/snap/strawberry/2964. For me personally, it's a useless shortcut.

![strawberry](https://user-images.githubusercontent.com/2061171/80963713-73fb8480-8e07-11ea-887a-818eeb9b823a.png)

**Describe the solution you'd like**
I'd like the ability to set the path to where my root library is, in my particular case it's on a samba share. It would be a nice simple quality of life enhancement.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jonaski** [comment]
We use what the HOME environment variable is set to.
The files view is just there for convenience but the program is intended to be used with the collection library.

**Comment by nourserry** [comment]
This is exactly what I was looking for
I have my music files organised in a way to make it easier to browse, as browsing a huge music collection grouped by whatever-tag is time consuming and harder to manage
Having the option to set home directory will be a great.. too bad it's not on your roadmap.
