### ISSUE TITLE
Cover art is not sent to the Plasma media player widget in tray

### ISSUE THREAD

**Issue by ShabazzKing** [strawberrymusicplayer/strawberry#426]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Starting with version 0.6.10 the cover of actually playing album isn't shown in the Plasma's media player widget in system tray and in window preview (which appears when one hover on window's button in task manager).

**To Reproduce**
Just launch the program and play some music with cover embedded.

**Expected behavior**
The cover art is shown in those places.

**Screenshots:**
I have added screenshot in attachment.

**System Information:**
 - Operating system: Ubuntu GNU/Linux Focal Fossa
 - Strawberry Version: 0.6.10
 - KDE Plasma 5.18.4
 - KDE Frameworks 5.68.0

**Additional context**
I have interface in Polish language, what you will see in screenshot.
![Strawberry](https://user-images.githubusercontent.com/25502034/80998128-b2626500-8e42-11ea-901b-f320c9554d93.png)

**Comment by jonaski** [comment]
It works here.
Can you try this command on the terminal:
`qdbus org.mpris.MediaPlayer2.strawberry /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata`
Does the file in mpris:artUrl exist?

Go on Tools / Console, enter the following + Run. What does the following output?
`select art_manual, art_automatic from songs where album = 'Kill At Will;`

**Comment by ShabazzKing** [comment]
First command produces following output:
Service 'org.mpris.MediaPlayer2.strawberry' does not exist.

The second operation produces following output:

> select art_manual, art_automatic from songs where album = 'Kill At Will'
|file:(embedded)
|file:(embedded)
|file:(embedded)
|file:(embedded)
|file:(embedded)
|file:(embedded)
|file:(embedded)

**Comment by ShabazzKing** [comment]
OK, I have noticed, that in the first example Strawberry must be launched first.
Here is the output in the first case:

bitrate: 894
mpris:length: 177000000
mpris:trackid: /org/strawberrymusicplayer/strawberry/Track/3510
xesam:album: Kill At Will
xesam:albumArtist: Ice Cube
xesam:artist: Ice Cube
xesam:composer: Chilly Chill / Ice Cube / Sir Jinx
xesam:contentCreated: 2020-02-05T21:29:50
xesam:genre: Hip-Hop
xesam:lastUsed: 2020-05-04T20:11:14
xesam:title: Jackin' For Beats
xesam:trackNumber: 2
xesam:url: file:///home/panlukasz/Muzyka/Ice Cube/Ice Cube - Kill At Will/2. Jackin' For Beats.flac
xesam:useCount: 3
year: 1990

**Comment by jonaski** [comment]
Thanks. I see the bug now.

**Comment by jonaski** [comment]
It should be fixed now

**Comment by ShabazzKing** [comment]
Thank you very much.
