### ISSUE TITLE
Can't turn off auto load cover from internet

### ISSUE THREAD

**Issue by 38569459** [strawberrymusicplayer/strawberry#427]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Wrong cover is loaded when song not have one. I can't turn off this.

**To Reproduce**
Play any song that don't have cover.

**Expected behavior**
Show default cover.

**Screenshots:**

**System Information:**
 - Operating system: arch linux 5.6.8-arch1-1
 - Strawberry Version: 0.6.10

**Additional context**

**Comment by jonaski** [comment]
You can right click on the album cover in context or the album popup and uncheck "Search automatically"

**Comment by 38569459** [comment]
I did that already. After that, I click on unset cover. And ply other song, then that song again, the cover reappear.
