### ISSUE TITLE
Visual Block Analyzer Stopped Working With 24bit Tracks - Linux 0.6.10

### ISSUE THREAD

**Issue by annoyingduck** [strawberrymusicplayer/strawberry#429]
New install of Strawberry on Arch XFCE machine, noticed the analyzer not working with 24bit files. With all 24bit FLAC files, the block analyzer (or the other styles) does not work, just shows a blank space. Works fine on all 16bit media (FLAC & mp3). Now here's the weird part: On another machine, the analyzer worked fine after upgrading to 0.6.10 (not a fresh strawberry install, but rather an update), but then failed to work after I toggled the setting "Use system theme icons" in the appearance section. That setting seemed to get reversed after the upgrade, which is why I had to re-toggle it in the first place. 

**To Reproduce**
Install cleanly, play 24bit file. Or update existing Strawberry, toggle "use system theme icons", close program, reopen, analyzer will fail to work on 24bit files, regardless of icon setting. Reverting back to not using system icons keeps analyzer broken on 24bit files.

**Expected behavior**
The block analyzer to work with any media playing.

**System Information:**
 - Operating system: Arch Linux, XFCE desktop
 - Strawberry Version: 0.6.10

**Comment by jonaski** [comment]
We already know about this issue, see #155
The analyzer currently only works with 16 and 24 bit.
Resampling can occur which is the reason that it doesn't work even if it's a 24 bit file. If you are not setting an output device, or you are using replay gain it will resample to a different bit depth that's not working with the analyzer.
The icon setting has nothing to do with it, it's probably a pure coincidence.
