### ISSUE TITLE
"Scrobbler not authenticated" warning is obtrusive

### ISSUE THREAD

**Issue by RomanHargrave** [strawberrymusicplayer/strawberry#430]
**Describe the bug**
When a scrobbler responds to strawberry in a manner that indicates the user's session is no longer valid (a ***frequent*** problem with the last.fm scrobbler - I'm not sure what their Oauth config is but surely there must exist the possibility of using a refresh token to extend the session), strawberry opens a modal dialog that will steal focus from the current task. As a music player is typically not the foreground application, this is frustrating and can interrupt important work. Because scrobbler authentication failures are not critical failures and do not prevent strawberry from functioning at it's most basic level, they do not deserve to be treated as critical errors that require immediate user attention.

I would propose that these errors be displayed as a notification rather than as a dialog.

**To Reproduce**
Authenticate with last.fm and wait between five and seven days.

**Expected behavior**
I am not interrupted by strawberry when my last.fm session expires.

**System Information:**
 - Operating system: Debian Sid
 - Strawberry Version:  0.6.10-5-g81ba63e2

**Comment by jonaski** [comment]
Last.fm doesn't use refresh token. Session keys are infinite.
See: https://www.last.fm/api/authspec

```
6.2 Session Lifetime
Session keys have an infinite lifetime by default. You are recommended to store the key securely. Users are able to revoke privileges for your application on their Last.fm settings screen, rendering session keys invalid.
```
As long as I have used last.fm I've had to authenticate 2 times or something.

**Comment by RomanHargrave** [comment]
Interesting. I find myself getting scrobbler authentication errors every few days. Nothing is changing. Same IP, etc...

**Comment by jonaski** [comment]
I can make a setting to chose to show the error popup or not. I find the error popup to be very useful as I primarily use my machine in the livingroom to play music that I dont actually sit in front of, and if it it was just a sys tray popup I wouldn't notice it immediately when I go to switch music. I also think we get a lot of complaints from other users if it was not there, but I can see that it can be intrusive, so an option to switch it off should be good.
As a side note I added renewing login for ListenBrainz, they use refresh token, although their "expires in" says 1 hour only, it never actually expires, but I guess it doesn't hurt to resend the login every hour in case they actually decide to expire the logins at some point.
