### ISSUE TITLE
Discs from the same album all show the same cover even when it's different (Airsonic)

### ISSUE THREAD

**Issue by KingDuckZ** [strawberrymusicplayer/strawberry#433]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
As per the title, I have an album made of 7 discs where each disc comes with a different cover. This is displayed correctly on Airsonic's web UI, but in Strawberry the image from the 1st disc gets displayed for the remaining 6 as well.

**To Reproduce**
Make a multi-disc audio folder where files have a different cover per-disc. Upload a it to Airsonic and bring it up in Strawberry.

**Expected behavior**
I expect to see the right cover from each disc.

**Screenshots:**
![](https://i.imgur.com/WGLZXgE.jpg)

**System Information:**
 - Operating system: 5.4.38-gentoo
 - Strawberry Version: 0.6.10

**Additional context**

**Comment by jonaski** [comment]
I have modified it to use album id's instead of artist and album titles as filenames.

**Comment by KingDuckZ** [comment]
Not sure I understand, but shouldn't it be something like artist+album+disc?

**Comment by jonaski** [comment]
Album ID's is a number reported by the API that is unique for each album. It's the only way to really be sure it doesn't use the same filename.

**Comment by KingDuckZ** [comment]
I see. Well feel free to test, your login should still be valid and the album name is as you see in my screenshot.
I know this is much of a corner case, so thanks for looking into this.

**Comment by jonaski** [comment]
Yeah, thanks a'lot I've already used it to test it, it's great because it has a lot of albums and can potentially find problems I don't find on my small test instance. It's great if you can leave it open, I will just occasionally use it to test.

**Comment by KingDuckZ** [comment]
Sure, feel free to use it as much as you like :) maybe just make sure you have a good enough password set and don't share the account with anyone, for the rest I'm happy if it's useful!

**Comment by KingDuckZ** [comment]
Is there anything I should do to refresh the covers? I've pressed the update button (the one on the left, below the search box) but discs still have the same cover for me

**Comment by jonaski** [comment]
Looks like my previous fix didn't really work because Subsonic is actually using the same album id for albums with the same title and a different disc, which I find really strange. I'm working on a fix now that will use "coverArt" ID's as filenames instead
