### ISSUE TITLE
Can't turn off auto load cover from internet

### ISSUE THREAD

**Issue by 38569459** [strawberrymusicplayer/strawberry#434]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Wrong cover is loaded when song not have one. I can't turn off this.

**To Reproduce**
Play any song that don't have cover.

**Expected behavior**
Show default cover.

**Screenshots:**

**System Information:**
 - Operating system: arch linux 5.6.8-arch1-1
 - Strawberry Version: 0.6.10

**Additional context**
I already uncheck search automatically but the issue still remain

https://github.com/strawberrymusicplayer/strawberry/issues/427#issuecomment-624196300

**Comment by jonaski** [comment]
It works fine here. Pretty pointless opening a new issue with as little details as this.
Check your database for corruption.
Collection songs should be updated with art_manual in the songs table set to `file:(unset)`.
Go to tools / console and run:
`select art_manual from songs where album = 'album title';`
