### ISSUE TITLE
make test errors

### ISSUE THREAD

**Issue by Menelkir** [strawberrymusicplayer/strawberry#440]
Since I'm trying to port strawberry to freebsd (which my port is here https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246342), I do some tests to make sure the quality of build. Since my first port attempt (0.6.10), everything builds pretty well, but the make test. Here's the list for a short reference, I'll attach the entire logs as well (build and make test)

.

```
[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (80 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 10 tests, listed below:
[  FAILED  ] CollectionModelTest.WithInitialArtists
[  FAILED  ] CollectionModelTest.CompilationAlbums
[  FAILED  ] CollectionModelTest.NumericHeaders
[  FAILED  ] CollectionModelTest.MixedCaseHeaders
[  FAILED  ] CollectionModelTest.UnknownArtists
[  FAILED  ] CollectionModelTest.UnknownAlbums
[  FAILED  ] CollectionModelTest.VariousArtistSongs
[  FAILED  ] CollectionModelTest.RemoveSongsLazyLoaded
[  FAILED  ] CollectionModelTest.RemoveEmptyAlbums
[  FAILED  ] CollectionModelTest.RemoveEmptyArtists

10 FAILED TESTS
ninja: build stopped: subcommand failed.
*** Error code 1

```

[make.txt](https://github.com/strawberrymusicplayer/strawberry/files/4638604/make.txt)
[make_test.txt](https://github.com/strawberrymusicplayer/strawberry/files/4638605/make_test.txt)

**Comment by jonaski** [comment]
It's no big deal, but fixed now. The tests have not been maintained that's why they didn't work anymore.

**Comment by Menelkir** [comment]
I see. Thanks.
