### ISSUE TITLE
AppImage not working on system with GLIBC < 2.28

### ISSUE THREAD

**Issue by azubieta** [strawberrymusicplayer/strawberry#441]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
The AppImage requires GLIBC 2.28 or greather to run.

**To Reproduce**
Run it on ubuntu Trusty or Xenial

**Expected behavior**
The application runs

**Screenshots:**

**System Information:**
 - Operating system: KDE neon User Edition 5.18 (based on ubuntu 18.04)
 - Strawberry Version: Strawberry-0.6.11-8-g24ac0e7b

**Additional context**
This is a common issue when the binaries are built on a modern system using tools such as linuxdeploy. This tool requires an older system (glibc) to be used at compilation time to ensure compatibility with older systems.

There is a new way of creating AppImage that doesn't have this restriction. It's [appimage-builder](https://appimage-builder.readthedocs.io/). It allows building an AppImage on a modern system keeping the backward compatibility. In the link, you will find the instructions to use this tool. In case of issues, I can help you.

**Comment by jonaski** [comment]
Thanks for the info. I will test it out when I get the time. The Appimages have been broken for the  last releases of Strawberry after I switched from CentOS 7 to 8 because of incompatibility between sqlite and the qt sqlite driver. Just fixed it yesterday, I also ended up building gstreamer with all plugins manually now too to get all audio formats working.
Would be nice to be able to use tumbleweed with the latest libraries.

**Comment by azubieta** [comment]
> The tool seem to be debian dependent.

That's correct. Please notice that linuxdeploy built AppImages need to be build on the oldest LTS available to ensure the final bundle compatibility with older systems.

There are plans to support other package managers and systems. In your case, which one would you like to use?

**Comment by jonaski** [comment]
I prefer opensuse, so zypper.
But if this new Python tool is able to do this so should linuxdeploy, does it bundle core libraries? Can't linuxdeploy just be updated to do the same?

**Comment by azubieta** [comment]
> does it bundle core libraries? 

It does bundle glibc, libstdc++ and others

> Can't linuxdeploy just be updated to do the same?

It can, also it's possible to support the linuxdeploy approach on appimage-builder. I chose using a package manager over following link dependencies for two reasons: 
- plugins are usually included as dependencies of packages, linuxdeploy depends on a handcrafted list to resolve plugins
- it's possible to cross-build AppImages using the same recipe
- also linuxdeploy already did that way so, why making duplicate

Notice that you can use appimage-builder in a docker container. For the generator to work you will have to allow the container to use your host X11 server. But feel free to use the tool that suits best to your needs.

**Comment by jonaski** [comment]
@TheAssassin can we update linuxdeploy to bundle core libraries?

**Comment by probonopd** [comment]
That'd be a question for @TheAssassin but from previous discussions I happen to know that he is not a fan of bundling those. So I dont know how likely it is that `linuxdeploy` will get this functionality.

[appimage-builder](https://appimage-builder.readthedocs.io/] and [go-appimage](https://github.com/probonopd/go-appimage/)'s `appimagetool -s deploy` can do it.

**Comment by jonaski** [comment]
New experimental Appimages are available now built with a modified version of go-appimage.
https://builds.strawberrymusicplayer.org/appimage/
There is both a Qt 5.15.1 and a Qt 6 version.
The Qt 6 version is built from the Qt 6 dev branch from my repo at openSUSE: https://build.opensuse.org/project/show/home:jonaski:qt6
Will switch it to use the official stable version once the final release of Qt 6 is ready in December.
