### ISSUE TITLE
Translations are read only?

### ISSUE THREAD

**Issue by satcom886** [strawberrymusicplayer/strawberry#443]
Hi! I'd like to help with translating. I registered a zanata account but the project is still read-only. Am I even supposed to use the website or should I download the `.po` file and submit a PR?

**Comment by satcom886** [comment]
![image](https://user-images.githubusercontent.com/28711937/82915188-ba5c8300-9f70-11ea-83f8-ed59314fef79.png)

**Comment by jonaski** [comment]
It's not set to readonly in the settings, others have successfully managed to edit the translations.
Open an issue in Zanata here: https://zanata.atlassian.net/projects/ZNTA/issues/?filter=allopenissues

**Comment by satcom886** [comment]
Turns out I had to join a language team. Pretty confusing interface... Thanks for the help!
