### ISSUE TITLE
No build target for Fedora 32 on the opensuse build service

### ISSUE THREAD

**Issue by lemonzest79** [strawberrymusicplayer/strawberry#444]
Hiya

Fedora 32 has been out for a number of weeks now, would it be possible to have a openSUSE Build Service target for Fedora 32? I had been using it for Fedora 31 but since I upgraded it stopped working.

Thanks.

**Comment by lemonzest79** [comment]
On the off chance I just checked the opensuse build service and noticed that Fedora 32 is now available, thanks, just updated from it and everything seems fine :) Thankyou

**Comment by jonaski** [comment]
Yeah it's added
