### ISSUE TITLE
Feature Request - support using a monochrome tray icon 

### ISSUE THREAD

**Issue by peterhoeg** [strawberrymusicplayer/strawberry#446]
**Is your feature request related to a problem? Please describe.**
When using a monochrome icon theme on KDE the strawberry tray icon sticks out like a sore thumb.

**Describe the solution you'd like**
It would be great if strawberry could automatically show a monochrome icon.

**Describe alternatives you've considered**
Alternatively, if auto-detecting is not an option, having a toggle in the application to prefer monochrome icons would work as well.

**Additional context**
![strawberry_tray_icon](https://user-images.githubusercontent.com/722550/83223242-fb40db80-a1ac-11ea-86c9-9687213141b8.png)

**Comment by cox34** [comment]
Would also like to see this.

**Comment by Sadi58** [comment]
That's why I don't tick "Show system tray icon" and get this:
![Screenshot_2020-06-17-11-14-16](https://user-images.githubusercontent.com/6375934/84873518-09876680-b08c-11ea-8154-e00241c041e2.png)

**Comment by jonaski** [comment]
You can use custom icons, see the Wiki.
I'm closing this since this is only a minor detail, and I don't have time to prioritize it. Anyone else is free to make a proposal for a change in a PR.

**Comment by Atrate** [comment]
I have been unable to find out how to change the tray icon in the wiki, could you provide a pointer as to where exactly I could find that?
