### ISSUE TITLE
Make queuing shortcuts work on collection items

### ISSUE THREAD

**Issue by lineinthesand** [strawberrymusicplayer/strawberry#447]
The queuing shortcut Ctrl+D/Ctrl+Shift+D is very useful, but it currently only works on the track/item(s) selected in the Playlist, regardless of whether the Playlist element has the focus or not. It would be very convenient if it could also work on an item selected in the Collection Browser, i.e. when the Collection Browser element (the interface on the left side) has the focus and something is selected there, hitting Ctrl+D should add the selected item(s) to the queue.

**Comment by jonaski** [comment]
That won't work since the collection right click uses a different menu, in any case I can't get shortcuts to work in the collection view, not sure why.
