### ISSUE TITLE
Analyzer motionless

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [strawberrymusicplayer/strawberry#448]
The analyzer doesn't move at all with either the Appimage or what I built from Slackbuilds. Actually I didn't have this problem on Debian if that means anything, this is on Slackware-current. Same with Gstreamer or Xine engines.

**Comment by sashaaaaaaaaa** [comment]
Oh so it seems to be an thing with ReplayGain. Indeed I turned off ReplayGgain and it works. #155

**Comment by jonaski** [comment]
Yes

**Comment by jonaski** [comment]
This is fixed now, development builds should be available in a few mintues.
