### ISSUE TITLE
Add option to preload mp3 files into RAM

### ISSUE THREAD

**Issue by morfikov** [strawberrymusicplayer/strawberry#451]
I noticed that the `strawberry [task*]` process constantly reads 128KiB from the disk in I think 2s interval. I compared the amount of data that it'd read with the size of the mp3 file, and it looks like that the whole mp3 is being read slowly till it gets read in full. 

Would it be possible to implement an option to  buffer the whole mp3 file in RAM? In this way strawberry would read a few MiB in one turn, and for the duration of the song it wouldn't bother with more reads, which would leave the disk in the IDLE state for a longer period of time. Also to avoid problems with reading the next song (the disk can be slow, some other processes can utilize the disk at the same time), the next song should also be buffered (possibly an option to configure how many songs to load would be nice to have too). What do you think about this feature? Is that doable?

**Comment by jonaski** [comment]
It might be doable, some info here: https://gstreamer.freedesktop.org/documentation/application-development/advanced/buffering.html
However I don't see a real need for this. It's not something I'm going to prioritize, and there are far too few contributors here.
