### ISSUE TITLE
Multiple versions of the same album are not divided

### ISSUE THREAD

**Issue by str3gatto** [strawberrymusicplayer/strawberry#455]
**Is your feature request related to a problem? Please describe.**
If I have multiple versions of the same album, for example the deluxe, the japan and the standard version, all tracks are organized in only one big album section in the tree on the left of strawberry. All albums are very well tagged with picard/musicbrainz using the correct asin and catalog number, the tags are perfect, but the problem is that there isn't a tag for the special version of the album in musicbrainz. Releasers uses the "comment" tag but it's not a proper way to do it.

**Describe the solution you'd like**
Multiple versions of the same album should be organized in different album icons in the tree, maybe with the correct special version name. The right way should be to use a tag to get the correct version name, I don't know if discogs or musicbrainz infos can be useful. I suppose an unique album identifier can be used, as the catalog number, asin or barcode.

**Describe alternatives you've considered**
An alternative way could be to use the folder structure of the library to split albums (but without breaking the multiple folder discs organization in the tree).

**Additional context**
![a](https://user-images.githubusercontent.com/63223659/83730258-1ac28300-a649-11ea-9202-5d092adfb18f.png)

**Comment by jonaski** [comment]
I usually add Deluxe Edition or the relevant thing for the release to the end of the album title.
Like you said yourself there isn't really a tag for this thing to separate it.

**Comment by jonaski** [comment]
catalognumber is something different and isn't a standardized tag either. Better to just create new custom tag if there isn't any that fits for it.

**Comment by RomanHargrave** [comment]
I'd like to chip in that the way I did this when using GmusicBrowser was to group albums by the directory they are stored in. This meant that I never had to alter album titles, etc... as different releases were in different directories.

**Comment by str3gatto** [comment]
Considering standard tags only, I suppose that the album splitting based on folder structure, is the cleanest/long-lasting way to do it.
