### ISSUE TITLE
Text is cut off in "About Strawberry" window

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#457]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
text is not entirely readable in about window
**To Reproduce**
open Strawberry and press F1

**Expected behavior**
text should be entirely readable

**Screenshots:**
![about](https://user-images.githubusercontent.com/15967631/84162030-4d53ed80-aa46-11ea-8b6e-b37552b422ad.png)

**System Information:**
 - Operating system: neon unstable edition linux distribution
 - Strawberry Version: 0.6.12

**Additional context**

**Comment by jonaski** [comment]
I just fixed it yesterday, see https://github.com/strawberrymusicplayer/strawberry/commit/033d56a4b332ded5b4e326bf060192ac1469d0d8
