### ISSUE TITLE
"Stop after this track" does not increase play counts

### ISSUE THREAD

**Issue by jfpen** [strawberrymusicplayer/strawberry#458]
**Describe the bug**
When the "Stop after this track" option is selected for a track, playing it does not cause the "Play count" to increase, or the "Last played" field to update. The play count and last played do update for tracks that are played last due to being at the end of a playlist (but only if "Stop after this track" is not selected for these).

**To Reproduce**
Right click on a track in a playlist and select "Stop after this track". Play either the track or a track before it in the playlist.

**Expected behavior**
When the track where "Stop after this track" is selected stops playing, the play count should increase by 1 for the track, and the "last played" field should update to show the current time.

**System Information:**
 - Operating system: Ubuntu 18.04.4 LTS
 - Strawberry Version: 0.6.12

**Comment by jonaski** [comment]
Thanks for reporting that, strangely I haven't noticed it before.
