### ISSUE TITLE
Option to "Always hide the main window" is greyed out

### ISSUE THREAD

**Issue by Sadi58** [strawberrymusicplayer/strawberry#461]
**Bug description**
When I first installed it was there, and I ticked it. However, it had no effect; next time it started by opening the main window, and then the option to "Always hide the main window" was greyed out.

**Expected behavior**
I would like to choose the option to "Always hide the main window" so that I can start the app minimized (and resuming playback as it does).

**Screenshot**
![image](https://user-images.githubusercontent.com/6375934/84874506-5a4b8f00-b08d-11ea-8a1e-0fc0a6afde74.png)

**System Information**
 - Operating system: Kubuntu 20.04
 - Strawberry Version:  0.6.12

**Additional context**
These might be related: Interestingly, even "Remember from last time" does not result in the application starting minimized after logging out and back in from minimized state. I can only achieve this by using a startup script that forces the app window to minimize a couple of seconds after startup.

**Comment by jonaski** [comment]
The keep running in background option / hide options depend on the system tray icon being visible, without that there will be no way to show the window when it's hidden, since the restore is done by clicking the icon in the tray.
The on startup options can do two things, either show the window, or hide it. See the third option to remember last time won't remember a minimized state, only the states listed as option 1 and 2.

**Comment by jonaski** [comment]
I see we can add an option to show minimized, should be pretty easy.

**Comment by Sadi58** [comment]
@jonaski Thanks!
I didn't realize hiding main window required enabling system tray icon to be able to control the app window.
On the other hand, minimized window option will be great in deed!
As you might know, some users including me think color icon of strawberry in KDE system tray odd anyway.
BTW I already have a monochrome media player widget in system tray with almost the same features.
![Screenshot_2020-06-18-12-13-47](https://user-images.githubusercontent.com/6375934/85003741-4b351180-b15f-11ea-9e9c-afc6610a1d27.png)
