### ISSUE TITLE
Cover manager doesn't distinguish file embedded images from downloaded covers

### ISSUE THREAD

**Issue by str3gatto** [strawberrymusicplayer/strawberry#462]
**Describe the bug**
When I delete a cover image using the Cover Manager, only the album cover "inside" strawberry will be deleted, so if the album has an embedded cover image too, I'll not see it inside strawberry anymore.

**To Reproduce**
I have two equal file with the same embedded image. I add them to strawberry library. I delete the cover of one file using the cover manager. The two files has the same cover image embedded but strawberry will show only the cover of one file. 

**Expected behavior**
The cover manager should let you choose if you want to remove the album cover "inside" strawberry or the album cover embedded in the file. And the Album info in the GUI should show if the image is embedded or not (if possible, without opening each file proprieties but at the album level or in an quick way "on the fly"). 

**System Information:**
 - Operating system: Debian GNU/Linux Stretch 9.12
 - Strawberry Version: 0.6.12

**Additional context**
- In my opinion there should be a cover manager option to show embedded covers only or downloaded cover only.
- There should be an option to not automatically download the cover if an album doesn't have one.

**Comment by jonaski** [comment]
There is no option to delete the album cover.

**Comment by str3gatto** [comment]
![1](https://user-images.githubusercontent.com/63223659/84934732-09ad5380-b0d8-11ea-9851-71fe4d5fca83.png)
This is what I mean

**Comment by jonaski** [comment]
That got nothing to do with deleting.
It's just marking the album that you have chosen to unset the album cover and won't show a cover until you set a new.

**Comment by str3gatto** [comment]
ok, I understood the concept of its behavior. Thanks. Could you add an option to not auto download a cover if an album doesn't have one?

**Comment by jonaski** [comment]
It's an option for it in the settings under Context / "Automatically search for album cover" (Or you can right click on the album in the popup or the context and there is the same option.

**Comment by str3gatto** [comment]
My bad, I hope I didn't take you too long, thank you for your patience and your time.
