### ISSUE TITLE
Auto Update?

### ISSUE THREAD

**Issue by fwd079** [strawberrymusicplayer/strawberry#463]
** Auto Update **

Hi there, could  someone please help me? 
I could not find "Auto update" or "check for updates" feature and now I am 5 versions behind. Please point me to correct direction, otherwise can this be added as a new feature?

Kind Regards.

**Comment by jonaski** [comment]
You don't mention what OS or Linux distribution you run.
Usually strawberry gets updated through the Linux distributions so an integrated auto update feature isn't necessary.
For Windows, we don't have resources to do it.
macOS - We don't make releases and have no developers working on it.

**Comment by fwd079** [comment]
> You don't mention what OS or Linux distribution you run.
> Usually strawberry gets updated through the Linux distributions so an integrated auto update feature isn't necessary.
> For Windows, we don't have resources to do it.
> macOS - We don't make releases and have no developers working on it.

Yes. My bad - Windows 10 and okay, put a watch on releases and will get notified that way now, thanks.

**Comment by jonaski** [comment]
I actually did this now, if you install version 0.7.1 it has check for updates.

**Comment by fwd079** [comment]
Cheers mate, will do it next time I'm on my machine.
