### ISSUE TITLE
"Resume playback on startup" and "Startup: Remember from last time"

### ISSUE THREAD

**Issue by Sadi58** [strawberrymusicplayer/strawberry#464]
**Describe the bug**
When the options "Resume playback on startup" and "Startup: Always hide the main window" are selected, and Strawberry is added to Autostart apps, it starts in the background, showing up in system tray, but it doesn't "Resume playback on startup", which works when the option "Startup: Remember from last time" is enabled.

**Expected behavior**
It seems some items at the top of the "Settings: Behavior" like  "Resume playback on startup" should better be merged into the Startup group below, and "Resume playback on startup" should probably be greyed out when "Always hide the main window" is selected.

**System Information:**
 - Operating system: Kubuntu 20.04
 - Strawberry Version: 0.6.12

**Additional context**
I didn't test if  "Resume playback on startup"  works with "Startup: Always show the main window" as I prefer Strawberry to resume playback on startup with a minimized window.

**Comment by jonaski** [comment]
I can guarantee you that the startup options got nothing to do with resuming playback on startup.
The state of the window can't affect the resume playback option. It simply does not matter if the window is visible or hidden.
When testing here resume playback on startup works with all the different startup options.
If you logout or reboot your computer while Strawberry is running and expect it to resume playback, that will never work as the closeevent won't be reached and thus no window position, playback position or anything else other than what is previously saved by the settings dialog will be saved.

**Comment by Sadi58** [comment]
@jonaski Sorry about the duplication due to some sytem error.
This issue however persisted quite some time here, but when I tried again now after seeing your reply above and it went away!
Sorry for taking your time unnecessarily, I'll wait at least 24 hours next time.

**Comment by Sadi58** [comment]
BTW, in my case "Resume playback on startup" does work after I log off or restart when playing.
