### ISSUE TITLE
"Resume playback on startup" incompatible with "Startup: Always hide the main window"

### ISSUE THREAD

**Issue by Sadi58** [strawberrymusicplayer/strawberry#465]
**Describe the bug**
When the options "Resume playback on startup" and "Startup: Always hide the main window" are selected, and Strawberry is added to Autostart apps, it starts in the background, showing up in system tray, but it doesn't "Resume playback on startup", which works when the option "Startup: Remember from last time" is enabled.

**Expected behavior**
It seems some items at the top of the "Settings: Behavior" like  "Resume playback on startup" should better be merged into the Startup group below, and "Resume playback on startup" should probably be greyed out when "Always hide the main window" is selected.

**System Information:**
 - Operating system: Kubuntu 20.04
 - Strawberry Version: 0.6.12

**Additional context**
I didn't test if  "Resume playback on startup"  works with "Startup: Always show the main window" as I prefer Strawberry to resume playback on startup with a minimized window.

**Comment by jonaski** [comment]
No.
