### ISSUE TITLE
[Mockup] A redesign of the interface

### ISSUE THREAD

**Issue by joaopauloalbq** [strawberrymusicplayer/strawberry#468]
**Is your feature request related to a problem? Please describe.**
The request is related to the look of the application that, in my opinion, could be more attractive.

**Describe the solution you'd like**
I made a minimalist mockup of the application at _Additional context_

**Describe alternatives you've considered**
at _Additional context_

**Additional context**
![mockup 1](https://user-images.githubusercontent.com/9905202/85234283-a591d480-b3e2-11ea-81ef-c04f8ec5401d.png)

![mockup 2](https://user-images.githubusercontent.com/9905202/85234285-a6c30180-b3e2-11ea-8b02-411e71060fc6.png)

Some widgets also don't look native in my system

![nat](https://user-images.githubusercontent.com/9905202/85234765-2bfbe580-b3e6-11ea-96c3-78dfe7cec4c2.png)

**Comment by jonaski** [comment]
The interface like it is, is why many users use Strawberry in the first place, including me.
I like the current interface better than this. I've seen other players for Linux that looks similar to your proposal.
One issue is that widgets and icons are too small on 4K displays, your proposal looks to be making the icons even smaller. I think we should solve this first.
However a playlist album view as an option would be nice. But it requires large rewrite to the playlist model and view.
