### ISSUE TITLE
Usage of move to collection

### ISSUE THREAD

**Issue by iranzo** [strawberrymusicplayer/strawberry#470]
Hi, due to limitations in my car audio system, I've used in the past media monkey to get files to this on disk schema:

first letter of artist / first two letters of artist / artist / song number - song name.mp3

Seen that strawberry has similar support, but didn't find a guide on just getting some of the letters from the string so that I could  achieve a similar folder organization.

Thanks in advance

**Comment by jonaski** [comment]
Not sure you can.
Use the forum for questions: https://forum.strawberrymusicplayer.org/
