### ISSUE TITLE
Choppy playback with tracks from Airsonic server

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#475]
**Describe the bug**
My server machine runs Arch Linux + Airsonic 10.6.2, playback of tracks from Airsonic music server is randomly interrupted for a few milliseconds. This problem doesn't occur when I play tracks from the same Airsonic server with Sublime Music installed on the same client machine.
https://sublimemusic.app/

**To Reproduce**
play tracks from Airsonic music server with Strawberry

**Expected behavior**
Strawberry should play tracks from Airsonic music server without any interruption.

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.6.12

**Comment by jonaski** [comment]
It works fine here even with severs over the internet. Several users are using Airsonic and have no issues. Just because it doesn't work for you doesn't make it a bug.
What file format? Did you change any backend settings, buffer min fill / duration, etc.

**Comment by glaubersm** [comment]
Format is MP3. I have never changed buffer settings, I don't even know as they work.
Should I increase the buffer duration?

**Comment by jonaski** [comment]
You can try

**Comment by glaubersm** [comment]
I have just increased to 8000ms.
I forgot to say that this problem wasn't happenng with Subsonic.
I changed to Airsonic when the trial period of Subsonic expired, then the problem began.

**Comment by jonaski** [comment]
The most likely issue is a connectivity issue, speed or latency. It's strange that it works with another player though.
I can't be of much more help. It works for me and everyone else, so I think you have better luck trying to get some help from Airsonic on this.

**Comment by glaubersm** [comment]
I have even set buffer to 12.000ms and moved the buffer min fill slider to right most position, but the issue persists.
Clementine 1.4 RC1 is also affected, despite the playback with it fails less frequently.
I will search for a solution adjusting airsonic settings.

Thank you Jonas.

**Comment by glaubersm** [comment]
Update on this issue: I have replaced airsonic with navidrome
https://www.navidrome.org/
and the problem disappeared from both operating systems (Arch + Gnome and Neon ustable + KDE Plasma) installed on my client laptop connected to the same wi-fi network. Playback no longer skips randomly. There is something wrong between Strawberry and airsonic.

**Comment by jonaski** [comment]
Many users are using Airsonic with Strawberry with no problems, I have also tested it on several Airsonic servers.
Could it be related yo your configuration? Do you use any transcoding?

**Comment by glaubersm** [comment]
Does airsonic transcode mp3 files by default? If I'm not mistaken, I have never changed any airsonic setting related to transcoding.
