### ISSUE TITLE
Title of a track from Airsonic music server containing parenthesis changes when playback starts

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#476]
**Describe the bug**
For example, if the title is "Title (Live)", initially Strawberry shows "Title" and then it shows "Title (Live)" when playback starts.
Furthermore, two notifications are triggered on KDE Plasma desktop environment (linux), one showing the correct title
(with "(Live)") and another one showing the incorrect title.

**To Reproduce**
Add a track from Airsonic music server with "Title (Live)" title to your playlist and observe the value shown by "Title" column
start to play "Title (Live)" track

**Expected behavior**
Strawberry should always show tags of tracks from Airsonic music server correctly.

**Screenshots:**
![notifications](https://user-images.githubusercontent.com/15967631/85871327-a04ad600-b7a4-11ea-9982-2eda8c9c7c4b.png)

**System Information:**
 - Operating system: neon unstable linux distribution, based on ubuntu bionic
 - Strawberry Version: 0.6.12

**Comment by jonaski** [comment]
This isn't a bug, strawberry reads the metadata from the stream and updates the song with the received metadata, if (live) is added then that means that the file is tagged with that.

**Comment by jonaski** [comment]
My bad, looks like we strip off some things including "live" from the song title when receiving songs from subsonic

**Comment by jonaski** [comment]
Fixed now
