### ISSUE TITLE
Can't load music onto iPod Nano 16GB Generation 7: Unsupported checksum type

### ISSUE THREAD

**Issue by marcelpaulo** [strawberrymusicplayer/strawberry#477]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
When I try to load an album onto an iPod Nano 16GB Generation 7, I get this error message:

`Unsupported checksum type`

The iPod is recognized correctly and mounted.

iPod model: MD481E (Nano 7th generation 16GB)

Running latest strawberry git version fc8a3be7 on Xubuntu 18.04.4.

Did the following:

1. Ran `strawberry --verbose &> >(tee strawberry.log)`
2. Connected iPod
3. Mounted iPod
4. Tried to load a single album onto the iPod

Here's [strawberry.log](http://paste.openstack.org/show/795546)

**To Reproduce**
1. Connect iPod
2. Mount iPod
4. Try to load an album onto the iPod

**Expected behavior**
Load the album onto the iPod without any error messages.

**Screenshots:**
![2020-07-05_02-25](https://user-images.githubusercontent.com/10074769/86526312-f4bb1900-be68-11ea-9d84-0ab78d5b66d5.png)

**System Information:**
 - Operating system: Xubuntu 18.04.4
 - Strawberry Version: fc8a3be7

**Additional context**

**Comment by jonaski** [comment]
It only works with the first iPod generations, for nano I think only first and second generation. Nano 7th generation will not work. Apple did things to prevent other software to be used with them, I think they encrypted the firmware, etc.

**Comment by marcelpaulo** [comment]
> It only works with the first iPod generations

Thanks for clarifying that, @jonaski!
