### ISSUE TITLE
"Show in file browser..." executes double-click function instead of opening file location

### ISSUE THREAD

**Issue by cmorgenstern** [strawberrymusicplayer/strawberry#478]
**Describe the bug**
Within a playlist, right-clicking on a track and selecting "Show in file browser..." does not open the file location in my file manager (PCManFM). Instead, it executes the set behaviour configured in the settings for "Double clicking a song will...". For example, if this is set to "Append to the playlist", then the track is appended to the playlist.

**To Reproduce**
1) Add tracks to a playlist
2) Right-click on a track and select "Show in file browser..."
3) Track is appended to the playlist instead of its location being opened in the file manager

**Expected behavior**
File manager should open to the location of the track selected.

**Screenshots:**
![strawberry-file-browser](https://user-images.githubusercontent.com/6384581/86595087-4cce5880-bfec-11ea-9cdb-c944555d2691.jpg)

**System Information:**
 - Operating system: Arch Linux - kernel `5.7.7-arch1-1`
 - Strawberry Version: Version 0.6.12-81-gfc8a3be7

**Additional context**
Custom PKGBUILD used for build/install:
[PKGBUILD.txt](https://github.com/strawberrymusicplayer/strawberry/files/4879014/PKGBUILD.txt)

Also tested and confirmed present in Strawberry when built/installed from the official Arch Linux [PKGBUILD](https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/strawberry).

This behaviour is NOT present when right-clicking on a directory under the file-system tab in the left sidebar and selecting "Show in file browser...". However, if the music file itself is right-clicked and "Show in file browser..." is selected, then the bug occurs and the file gets appended to the currently focused playlist.

**Comment by jonaski** [comment]
Whats the output of? `xdg-mime query default inode/directory`
I have not tested it with PCManFM, the probably reason is that it sees a music file and redirects to open it in Strawberry. Not sure what can be done to fix that since it's outside of the control of Strawberry.

**Comment by jonaski** [comment]
I tested it now and can confirm what I suspected. PCManFM does not support selecting file, so it instead opens the file in the associated program. I changed the behavior to open the directory instead, https://github.com/strawberrymusicplayer/strawberry/commit/26a8bfaac4681791c3da9b3ff26d75cadf569bc6

**Comment by cmorgenstern** [comment]
Thanks - here's the output from my system in case you are interested:

```
$ xdg-mime query default inode/directory
pcmanfm.desktop
```

I noticed that you are referencing `pcmanfm-qt` in the commit you authored. I am actually still using plain `pcmanfm`, so the fix is not yet working for me. Is it possible to pass multiple strings to `startsWith()` or does it accept regular expressions like `pcmanfm*`?

**Comment by jonaski** [comment]
Yeah of course, fixed now

**Comment by cmorgenstern** [comment]
Thanks, tested and confirmed working.
