### ISSUE TITLE
Internal data stream error when playing mp3 files from airsonic

### ISSUE THREAD

**Issue by KingDuckZ** [strawberrymusicplayer/strawberry#479]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
My airsonic server is set to transcode music to ogg, with most of my collection being already in that format. I have a specific album that is stored as mp3, and when playing that one from Strawberry I get an error box saying "Internal data stream error". I'm not sure this is a problem with airsonic or strawberry, but I can confirm I can play that album fine on UltraSonic (the Android app).

**To Reproduce**
* Set up your server to transcode to ogg
* Add some mp3 album
* Play from strawberry

**Expected behavior**
Songs should just play

**System Information:**
 - Operating system: gentoo kernel 5.4.48
 - Strawberry Version: 0.6.12

**Additional context**
Please ask in pvt for specific details

**Comment by jonaski** [comment]
I can confirm it, same problem when transcoding from FLAC to Ogg Vorbis.
Seem like GStreamer doesn't understand the stream.

**Comment by jonaski** [comment]
Command:
`gst-launch-1.0 souphttpsrc ssl-strict=false location=https://airsonic.jkvinge.net/rest/stream.view\?c=Strawberry\&v=1.11.0\&f=json\&u=admin\&p=xxx\&id=1052 ! decodebin ! audioconvert ! audioresample ! alsasink device=hw:0,0`

Error:
```
=1052 ! decodebin ! audioconvert ! audioresample ! alsasink device=hw:0,0
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
WARNING: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstOggDemux:oggdemux0: Could not decode stream.
Additional debug info:
../ext/ogg/gstoggdemux.c(4626): gst_ogg_demux_handle_page (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstOggDemux:oggdemux0:
unknown ogg pad for serial fe5df017 detected
```

**Comment by jonaski** [comment]
This problem is in GStreamer so I can't do much about it. I sent an e-mail to the gstreamer devel mailinglist:
https://lists.freedesktop.org/archives/gstreamer-devel/2020-July/075566.html
There is a upcoming release of gstreamer 1.8, maybe it's solved there.
