### ISSUE TITLE
There is 404 error when I try download Appimage from site

### ISSUE THREAD

**Issue by ashed** [strawberrymusicplayer/strawberry#480]
**Describe the bug**
There is 404 error when I try download Appimage from site [https://www.strawberrymusicplayer.org/](https://www.strawberrymusicplayer.org/)
[Strawberry-0.6.12-10-g8b86c79b.AppImage.](https://files.jkvinge.net/packages/strawberry/Strawberry-0.6.12-10-g8b86c79b.AppImage.)

**To Reproduce**
Try to download this Appimage on link

**Expected behavior**
Fix Appimage download link to [Strawberry-0.6.12-10.AppImage.](https://files.jkvinge.net/packages/strawberry/Strawberry-0.6.12-10.AppImage.)

Your's release numeration is from Strawberry-0.6.11-10--g8b86c79b.AppImage

**Comment by jonaski** [comment]
Fixed
