### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by beew** [strawberrymusicplayer/strawberry#482]
I may be missing something, but seems like the search box above the collection side panel doesn't work.

For example, I have a file "One Love _ Playing For Change _ Song Around The World.ogg" but typing in One Love" in the search box doesn't return anything but strawberry does put it in my collection under unknown . 

I have some random music downloaded from internet and they don't  have proper metadata such as artist, album etc. I think the search should just return based on the text entered in the box (like nightingale)

OS ubuntu 16.04

strawberry 0.6.13 compiled from source.

Thanks for the great work.

**Comment by jonaski** [comment]
The collection library is entirely based on tags.
