### ISSUE TITLE
Strawberry shows an apparently unnecessary warning when I use "Show in file browser" feature with 6 or more tracks

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#484]
**Describe the bug**
When I use "Show in file browser" feature with 6 or more tracks, Strawberry shows an apparently unnecessary warning.

**To Reproduce**
select "Collection" tab in the sidebar
right-click on any disc with 6 or more tracks
choose "Show in file browser..." (the warning that we can see in the screenshot below shows up)
click on "Open,,," button: just one instance of the file manager opens and shows all tracks of the right-clicked disc

**Expected behavior**
strawberry should open the file browser without any warning

**Screenshots:**
![warning](https://user-images.githubusercontent.com/15967631/87815189-8f3d3400-c83b-11ea-90d8-667a83d305d7.png)

**System Information:**
 - Operating system: neon unstable linux distribution
 - Strawberry Version: 0.6.13

**Comment by glaubersm** [comment]
This waning can be usefuul when we want to open tracks from 6 or more different discs because in this case Strawberry opens 6 or more instances of the file manager.

**Comment by jonaski** [comment]
So a check to see how many different paths there are for the songs, and show the warning of there are many should be sufficient

**Comment by NucleaPeon** [comment]
> Strawberry opens 6 or more instances of the file manager.

@jonaski Could you have strawberry attempt to open each instance in a file manager tab before having it create a new window, assuming that's what "instances of the file manager" mean? It looks like we both would be using dolphin and I know nautilus has a tab function too.
