### ISSUE TITLE
Please separate translation from the main executable in binary packages

### ISSUE THREAD

**Issue by peremen** [strawberrymusicplayer/strawberry#485]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Korean translator here. While translating Strawberry I found that it is very annoying to test the translations from the translator's point of view. Currently Strawberry's binary package seems to embed all .qm files into the .qrc file embedded inside the executable. As a result, when a translator wants to update and test a new translation a complete rebuild of the application is needed. While I can do that by myself, not all translators are capable of/willing to compile the Strawberry for just testing their translation. Even for those who can do that, it is very annoying to do so.

Note that VirtualBox ships .qm file separately on their binary packages. Please consider doing that so translators can test, update, and proofread translation without the overhead of compiling the entire app. This will of course change the build scripts, but in turn, I believe that this can lower the bar for translators to improve their work.

**To Reproduce**
1. Download Ubuntu package from the official site (not sure about other distros)
2. Check the installed file list using `dpkg -L strawberry`
3. No .qm files are there

**Expected behavior**
Translation files needs to be separate from the main executable but contained within the same package, to make testing of translations more easier without full application rebuild. Please note that not all translators are developers or capable of compiling Strawberry to test the translation.

**System Information:**
 - Operating system: Ubuntu 20.04
 - Strawberry Version: 0.6.13 (Ubuntu package)

**Comment by jonaski** [comment]
I think I'm in favor of having them in the resource file. But I think we can make an CMake option for it and that way package maintainers may chose and it allows some testing if we want to consider switching to it.
