### ISSUE TITLE
Search bar above playlist doesn't work

### ISSUE THREAD

**Issue by ShabazzKing** [strawberrymusicplayer/strawberry#486]
I use version 0.6.13-42-gd7f88cf3-focal. When I write some search terms in the search bar which is used to seek in the playlist, nothing happens.

Steps to reproduce:
1) Open Strawberry with a playlist loaded.
2) Try to search in playlist.

Expected behavior:
Strawberry filters playlist according to search terms.

 - Operating system: Ubuntu GNU/Linux Focal Fossa (Kubuntu)
 - Strawberry Version: 0.6.13-42-gd7f88cf3-focal (from official PPA)

**Comment by jonaski** [comment]
Thanks for reporting that. Looks like QSortFilterProxyModel::filterRegularExpression isn't working with Qt 5, it works with Qt 6. Perhaps a bug in Qt (?). I reverted the change so it still uses filterRegExp() with Qt 5.
