### ISSUE TITLE
Collection search crashes Strawberry

### ISSUE THREAD

**Issue by garuffalo** [strawberrymusicplayer/strawberry#487]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
When using the search field for "Collection", Strawberry crashes. (Version: 0.6.13-47-g638998a8-bionic)

**To Reproduce**
Re-open Strawberry, Begin typing in search field. Sometimes it crashes after typing only a few characters. Other times it completes the search, but crashes when clearing the search field. Occasionally, it will allow the selection of a song and clearing the search field without crashing, but will not show the selection in the collection as is normal. There does not seem to be a clear pattern.

I just noticed this after my last update. I am using the PPA as a source and update Strawberry as soon as the latest update comes. I haven't used the search function for awhile, so I don't know if the problem just started with this version.

**Expected behavior**
Previously, when searching "Collection", search results would appear, after which I could select the song I was searching for and then clear the search field, returning the Collection view to normal, but showing the selected item in the Collection list.

This is also the behaviour in the current version of Clementine, which I also have installed, and just tested as a comparison.

**Screenshots:**

**System Information:**
 - Operating system:
 Linux Mint 19.3 Cinnamon

-Hardware
 Dell Latitude D630; 2.4Ghz; 8GB RAM
 Graphics - Intel Mobile GM965/GL960 Integrated Graphics (driver: i915)

 - Strawberry Version: 0.6.13-47-g638998a8-bionic

**Additional context**
Searching playlists works OK.
Just after writing this, updated to version 0.6.13-53-ge043a03e-bionic and problem persists.

**Comment by jonaski** [comment]
It's related to commit https://github.com/strawberrymusicplayer/strawberry/commit/af67de8aa69ecb6a4c8028c6ea671e1073150588 yesterday. I reverted it now. Update to 54-gff73dd2 when it's available and the problem should be gone

**Comment by garuffalo** [comment]
Yes! That fixed it. Thanks!
