### ISSUE TITLE
Memory leak Debian Sid

### ISSUE THREAD

**Issue by RattusSolarus** [strawberrymusicplayer/strawberry#489]
On launching Strawberry, hard drive churns for about a minute gradually increasing reported memory use to about 32% (of 4GB). Works normally after that but doesn't release memory. Update collection when Strawberry starts is unchecked.
This is Strawberry 0.6.13 installed manually. Used the Bullseye package on Sid but has been fine in the past. I also tried 0.6.11 from Steve Passert's OBS repo and it had the same issue. Steve builds it for Sid.
Steve's Strawberry 0.6.11 does not exhibit the same behaviour on Debian Buster.

**Comment by jonaski** [comment]
I suggest you report this to debian. If there is a leak it sounds like it's caused by a library used by debian. Otherwise we need a detailed report showing a leak. I can't reproduce any problems on any distro.
