### ISSUE TITLE
"Overwrite existing files" does not overwrite destination files as it should

### ISSUE THREAD

**Issue by breversa** [strawberrymusicplayer/strawberry#497]
**Describe the bug**
Due to some files mismanagement, I ended up with many many duplicates in my music folder, such as :

- `/home/breversa/Musique/Ben Prunty/FTL/Ben Prunty - Space cruise (Title).flac`
- `/home/breversa/Musique/Ben Prunty/FTL/Ben Prunty - Space cruise (Title)(2).flac`
- `/home/breversa/Musique/Ben Prunty/FTL/Ben Prunty - Space cruise (Title)(3).flac`

I thought "_No problem ! I'll use Strawberry's "Organize files" feature with the "Overwrite existing files" option to squash those duplicates_". However, see below (in screenshot) what happens : duplicate files are organized as duplicates even if I check the "Overwrite existing files" option if I try to organize all of them in one go.

**To Reproduce**
1. Make duplicates of a music file (just change the name).
2. Add those files to a new playlist.
3. Select them.
4. Right-click on them and select "Organize files".
5. Check the "Overwrite existing files" option.
6. See in the preview that duplicates are NOT overwritten.

The weird thing is that if I try to organize the files one by one instead of all of them in one go, the organized file WOULD overwrite the existing one…

**Expected behavior**
Duplicate files should be organized according to their tags and overwrite same-tags files if the option is checked, NOT (re)create duplicates (as it totally defeats the option in the first place).

**Screenshots:**
![image](https://user-images.githubusercontent.com/2071276/89047593-eb7d7900-d34e-11ea-916c-489a1510f3a3.png)

**System Information:**
 - Operating system: 
`System: Kernel: 5.4.0-42-lowlatency x86_64 bits: 64 Desktop: Cinnamon 4.6.6 Distro: Linux Mint 20 Ulyana`

 - Strawberry Version:
Strawberry 0.6.13

**Comment by jonaski** [comment]
The overwrite existing files option is to overwrite existing files on disk that are not part of the organized songs shown in the dialog. What you are showing is intended behavior since you are organizing songs they should never be able to get the same filename. If someone makes a mistake with the tags this could lead to erasing lots of files so the added number to the files is a safely mechanism.

**Comment by breversa** [comment]
So that's a feature, not a bug ? :-)

For anyone in the same situation, I found a solution to my problem :

1. Use your favorite file manager to look for all music files with the duplicate pattern (in my case : `*(1)*`)
2. Select and load all those files into Strawberry
3. Use Strawberry's "Organize files" and "overwrite existing files" option to organize the files
4. If needed, start again with another duplicate pattern (e.g. `*(2)*`, `*(3)*`, etc.)
