### ISSUE TITLE
(macOS) No URI handler implemented for "https" starting on strawberry-0.6.13.74.g88000827.dmg build

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#498]
**Describe the bug**
Starting from build https://builds.strawbs.org/macos/strawberry-0.6.13.74.g88000827.dmg when I try to play any song from either local collection or Subsonic I get this error:

**Screenshots:**

![Screenshot 2020-08-02 at 11 26 58](https://user-images.githubusercontent.com/25823659/89120257-31545180-d4b5-11ea-9631-493c018a72a2.jpg)

**System Information:**
Mac OS X Catalina 10.15.5
Starting from 0.6.13.74 to the latest build

I saw this issue https://github.com/strawberrymusicplayer/strawberry/issues/142 but I already have gstreamer installed.. Anyway any build before strawberry-0.6.13.74.g88000827.dmg plays perfectly, so it must have been some commit I guess..

Thanks.

**Comment by jonaski** [comment]
The macOS builds stopped for a long time due to a problem in the macosdeploy script. Camparing otool -L outputs between the old and the new bundled dependencies, there are no differences. But I think by the time I had fixed the script homebrew have upgraded ICU to 67.1 and it now needs a file file called libicudata.67.dylib for the gst soup dependencies. That file isn't copied by the macos deploy script for some reason.

**Comment by llucps** [comment]
I found that library  libicudata.67.dylib on https://formulae.brew.sh/formula/icu4c

Could it be that icu4c library needs to be installed?

**Comment by jonaski** [comment]
It is installed but not picked up by the deploy script

**Comment by jonaski** [comment]
Try the new build when it's finished.

**Comment by jonaski** [comment]
Looks like the added libicudata dependency was the reason the script failed in the first place and my workaround in the python script only made it skip that file. So the script should be properly fixed instead my hack but I'm not really good at python.

**Comment by llucps** [comment]
It works :) 

sorry I don't follow you.. what python script?

**Comment by llucps** [comment]
oh I guess you mean this https://github.com/strawberrymusicplayer/strawberry/commit/0fa52bc64fc81f6e8dc1c55ed0580f016996b643
