### ISSUE TITLE
Sparkle Auto update

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#499]
Sorry if the auto-update hasn't been fully implemented yet. I just wanted to tell you that when I click on the new Check for Updates feature I get this message:

![Screenshot 2020-08-03 at 16 44 23](https://user-images.githubusercontent.com/25823659/89195883-b1f47a00-d5a9-11ea-8b13-19665df02f46.jpg)

I guess a edDSA is required.

Thanks.

**Comment by jonaski** [comment]
Yeah I'm aware, I just started looking into the code signing stuff. I added SUPublicEDKey to Info.plist now, looks like the error is gone https://github.com/strawberrymusicplayer/strawberry/commit/789ff9df5c2f407f478111ae079d9515ead5c1d4
The updater works for informing about new versions but I'm not sure it works for automatically installing a new version yet. The dmg should be code signed too and the appcast file needs to have some signatures too.

**Comment by jonaski** [comment]
Looks like code signing requires a Apple Developer ID, to get one we need to pay a fee to join the Apple Developer Program.
But at least Sparkle is working and should work for informing about a new version, not sure it will be possible to automatically install the update though.

**Comment by jonaski** [comment]
If you run an earlier version than 0.6.13-95-g3ff48859 and select check for updates now you should be able to download the new  and automatically install it. Tested it here and it's actually working.
I will update the available version again with the next stable release.

**Comment by llucps** [comment]
I tried to auto update with 0.6.13-92-ga2064ed1 build and I get en error when extracting the archive.

This is the workflow:

![Screenshot 2020-08-04 at 08 49 38](https://user-images.githubusercontent.com/25823659/89262633-2671fc00-d630-11ea-8be5-0f18b032d575.jpg)

![Screenshot 2020-08-04 at 08 49 46](https://user-images.githubusercontent.com/25823659/89262646-2b36b000-d630-11ea-9d00-a62375c9c0b2.jpg)

![Screenshot 2020-08-04 at 08 50 10](https://user-images.githubusercontent.com/25823659/89262660-2eca3700-d630-11ea-8577-9dce9c725dd7.jpg)

![Screenshot 2020-08-04 at 07 55 56](https://user-images.githubusercontent.com/25823659/89262664-31c52780-d630-11ea-95b4-d28602d6adce.jpg)

**Comment by jonaski** [comment]
The version you have installed was from the commit before I added the SUPublicEDKey to Plist.info, so you need to have 789ff9d or newer for it work. If you install the .93 release (789ff9d) you should be able to uprgade to the newest automatically.

**Comment by llucps** [comment]
silly me... :D yes it worked.
Thanks!
