### ISSUE TITLE
Some features are unnecessarily enabled in Playlists tab when no playlist is selected

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#500]
**Describe the bug**
"Delete" (context menu and button on top) and "Copy to device" features are enabled even when no playlist is selected.
Obviously they do not work without we select a playlist first.

**To Reproduce**
click on Playlists tab
make sure no playlist is selected
click on "Delete" button on top: nothing happens
right-click on an empty area of Playlists sidebar: nothing happens when we choose "Delete".
I can't test "Copy to device" because lack of a device (usb stick can not be used) but probably
it will also fail

**Expected behavior**
only enable features when they can be used

**System Information:**
 - Operating system: neon unstable linux distribution, based on ubuntu bionic
 - Strawberry Version: 0.6.13

**Comment by jonaski** [comment]
FYI, I did similar fixes to the queue buttons https://github.com/strawberrymusicplayer/strawberry/commit/c4f5363cdecfcedaf3916e092ea5d5eafe7c80d1

**Comment by glaubersm** [comment]
This issue persists with Strawberry 0.7.2.
