### ISSUE TITLE
Impossible to favorite a playlist when tab bar is not active

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#502]
**Describe the bug**
We can favorite a playlist by clicking on its star icon, but such icon does not exist when just 1 playlist is open and consequently the tab bar is not active.

**To Reproduce**
Have just 1 playlist open

**Expected behavior**
it should exist a way to favorite a playlist when the tab bar is not active

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.6.13

**Comment by jonaski** [comment]
It's not possible to lose the playlist when there is only 1, also there isn't a good place to put any option to favorite the playlist when the tab is hidden either. This has worked fine for most users for 10 years. If you or someone else want to change it please propose a change in a PR.

**Comment by glaubersm** [comment]
My objective is to favorite the only playlist to listen it later, not to prevent that it  be lost.
As I said before, I'm not a software developer. :(
Thank you again.
