### ISSUE TITLE
Play icon of the tab bar is almost invisible with dark desktop themes

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#504]
**Describe the bug**
play icon of the tab bar is black when a dark desktop theme is used, making it almost invisible.

**To Reproduce**
open two playlists
play some song

**Expected behavior**
play icon should have light color with dark themes

**Screenshots:**
![playbutton](https://user-images.githubusercontent.com/15967631/89712969-c39f9e00-d96a-11ea-94d7-c6aa51db15cb.png)

**System Information:**
 - Operating system: Arch Linux, KDE Plasma sesktop environment, Breeze Dark theme
 - Strawberry Version: 0.6.13

**Comment by jonaski** [comment]
This is only a minor detail, it works for most users. This is a community project so if you want to improve it please provide a change in a PR.

**Comment by glaubersm** [comment]
Unfortunately I'm not neither a software developer nor a designer.
Using system theme icons does not help.
Thank you anyway Jonas. :)
