### ISSUE TITLE
Mass tag editing in sequence fails

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#507]
**To Reproduce**
(I can reproduce with mp3 and flac files)
add several songs to your playlist
select all added songs
right-click on album of any selected song, choose "Edit tag album"
edit album name (Strawberry applies the change as expected)
right-click on artist of any selected song, choose "Edit tag artist"
edit artist: Strawberry doesn't apply the change

**Expected behavior**
mass tag editing should always work

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.6.13

**Comment by jonaski** [comment]
Good catch!
