### ISSUE TITLE
Feature Request: Allow more than 20 seconds maximum seeking

### ISSUE THREAD

**Issue by divisionbyzeroerror** [strawberrymusicplayer/strawberry#509]
**Describe the FEATURE**
Seeking is limited to 20 seconds. Technical reason for this number? I'd like to be able to seek in larger increments. For example: 25% of the track or up to 3 minutes.

**Screenshots:**
![Screenshot 2020-08-11 at 4 16 01 PM](https://user-images.githubusercontent.com/59974/89949924-3ec4b680-dbee-11ea-862c-be4725df0a32.png)

**System Information:**
 - Operating system: Debian 10 (Buster)
 - Strawberry Version: 0.6.13

**Additional context**
When crate digging over hundreds of tracks, it would be useful to be able to seek through the individual tracks much more quickly. With a percentage skip or a larger specific time period, it would enable this.

**Comment by jonaski** [comment]
Increased to 60

**Comment by divisionbyzeroerror** [comment]
@jonaski since this field is 2 digits... could you make it max 99 seconds?

**Comment by jonaski** [comment]
It's not limited to 2 digits. I'll just double it.

**Comment by divisionbyzeroerror** [comment]
@jonaski cheers! That should be all I need to dig through crates more quickly!
