### ISSUE TITLE
Feature Request: Allow hiding of UI elements to make player more minimal

### ISSUE THREAD

**Issue by divisionbyzeroerror** [strawberrymusicplayer/strawberry#510]
**Describe the FEATURE**
Allow the user to hide these individual elements of the UI:
- Playlist controls (buttons and search box), ie. the whole "row"
- Player controls (back/pause/stop/next buttons)
- Application Menu items

**Screenshots:**
Before...
![ss1](https://user-images.githubusercontent.com/59974/89951243-ac71e200-dbf0-11ea-9ed0-35aaa9809cf2.png)
...and after
![ss2](https://user-images.githubusercontent.com/59974/89951248-b1369600-dbf0-11ea-8df1-763984ce21aa.png)

**System Information:**
 - Operating system: Debian 10 (Buster)
 - Strawberry Version: 0.6.13

**Additional context**
- Playlist controls are not useful to all users and these users may always live in a single playlist which is just the currently active window and it's playlist contents.
- The Analyzer itself can currently be hidden from the UI and taking this a steap further to hide the control buttons would free even more space up from the UI.
- App menu items are hideable in a lot of Linux apps via the Alt+M keyboard combination. It would benefit Strawberry to also allow this part of the UI to be displayed or not. The keyboard combination to control this could be user configurable with a default as with other keyboard combinations.

**Comment by jonaski** [comment]
We don't have contributors or resources to do new features at this point. Use the forum for discussing new features.
