### ISSUE TITLE
Add option to automatically sort playlists

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#511]
**To Reproduce**
1. click on "Collection" tab
2. click on "Length" or "Title" columns of the playlist
3. right-click on any artist or album listed in "Collection" panel and choose "Append to current playlist" or "Replace current playlist" or "Open in new playlist" or "Queue track" or "Queue to play next"

**Expected behavior**
songs in the playlist should be sorted according to column clicked in the step 2.
Currently the songs are added to playlist in the same order as they appear in "Collection" panel.

**System Information:**
 - Operating system: neon unstable based on ubuntu 20.04
 - Strawberry Version: 0.6.13

**Comment by glaubersm** [comment]
Also reproducible when I open a playlist via "Music" menu > "Open file".

**Comment by jonaski** [comment]
There has never been automatic sorting in the playlist, you need to manually press the columns.

**Comment by glaubersm** [comment]
The arrow of the column points down/up before the songs be added to the playlist and remains in the same state after the songs be added. It looks weird GUI indicating a thing while we see another one.

**Comment by jonaski** [comment]
I agree, I turned it off the sort indicators now. Best I can do for now :)

**Comment by glaubersm** [comment]
Now there is no way to known what is the sorting mode in use. I think that the previous situation is preferable.

**Comment by garuffalo** [comment]
Yes, please restore the sort indicators!
