### ISSUE TITLE
Asian characters are not sorted in Library on 0.7.1

### ISSUE THREAD

**Issue by ShinyaOsen** [strawberrymusicplayer/strawberry#513]
**Describe the bug**
Asian characters are skipped in library so 鬱P(UtsuP) is put in P's instead of 鬱 and bands like 和楽器バンド and 妖精帝國 are put above Various artists instead of with there Kanji. Same goes for Chinese characters and Japanese hiragana and katakana.
This doesn't happen in the cover manager.

**Expected behavior**
The band names and album names to be sorted by there characters like in cover manager.

**Screenshots:**
0.6.13
![Screenshot_20200815_014630](https://user-images.githubusercontent.com/49567246/90306516-fb8f6f80-de9b-11ea-848a-65e18980226c.png)
0.7.1
![Screenshot_20200815_021144](https://user-images.githubusercontent.com/49567246/90306606-fd0d6780-de9c-11ea-9910-e73e3fb2e49e.png)
![Screenshot_20200815_021315](https://user-images.githubusercontent.com/49567246/90306608-00a0ee80-de9d-11ea-9f14-33caa44b0637.png)
![Screenshot_20200815_021039](https://user-images.githubusercontent.com/49567246/90306609-04cd0c00-de9d-11ea-8f90-fea36240b59d.png)
![Screenshot_20200815_021003](https://user-images.githubusercontent.com/49567246/90306611-0696cf80-de9d-11ea-8e62-18e51f62078e.png)

**System Information:**
 - Operating system: Linux and Windows 10
 - Strawberry Version: 0.7.1

**Additional context**
I guess non English characters are not sorted.

**Comment by jonaski** [comment]
Try 0.7.1-5-g414a4a97 from https://builds.strawberrymusicplayer.org/windows/ when ready, should be there in 1 an hour or so.

**Comment by ShinyaOsen** [comment]
Thanks for the fix
