### ISSUE TITLE
Currently playing song text is blurry on high DPI display

### ISSUE THREAD

**Issue by eggjoystick** [strawberrymusicplayer/strawberry#515]
For general technical questions and help with technical issues please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
Text for the currently playing song (with pulsating background) is blurry and pixelated on a 3840x2160 display with 2x scaling.

**To Reproduce**
Use strawberry on a high DPI display and Cinnamon desktop environment with user interface scaling set to Double (Hi-DPI). Play a track and notice the blurry text for the current song.

**Expected behavior**
Text should remain crisp as it does for all text

**Screenshots:**
![strawberry-blurry-text](https://user-images.githubusercontent.com/58571795/90688232-c5ebdd00-e233-11ea-9602-c36ea525efea.png)

**System Information:**
 - Operating system: MX Linux 19.2 64-bit
 - Strawberry Version: 0.7.2
 - Kernel: 5.4.0-3-amd64
 - Cinnamon 4.2.4
 - Resolution: 3840x2160~60Hz

**Additional context**
All text not pertaining to currently playing song remains crisp

**Comment by jonaski** [comment]
I don't have a hiDPI screen to test on here, but you can try the following:
Does disabling "show glowing animation" in the playlist settings change anything?
Do you know how to compile from source?
Remove these 3 lines from playlistview.cpp:
1. `style_(new PlaylistProxyStyle())` on https://github.com/strawberrymusicplayer/strawberry/blob/master/src/playlist/playlistview.cpp#L135
2. `setStyle(style_);` on https://github.com/strawberrymusicplayer/strawberry/blob/master/src/playlist/playlistview.cpp#L179
3. `delete style_;` on https://github.com/strawberrymusicplayer/strawberry/blob/master/src/playlist/playlistview.cpp#L215
Does that fix it?

**Comment by eggjoystick** [comment]
Hi, thanks for replying so quickly.

Disabling the "show glowing animation" playlist setting does not resolve the blurry text.

I've managed to delete the 3 lines from playlistview.cpp but I could use some instructions on how to compile from source. I am comfortable using the command line.

**Comment by jonaski** [comment]
https://github.com/strawberrymusicplayer/strawberry/wiki/Compiling-on-Debian

**Comment by eggjoystick** [comment]
Thanks for the instructions. I was able to follow them, compile from source, and run strawberry. Unfortunately, the blurry text remains.

**Comment by jonaski** [comment]
Then we need to look at the PlaylistView::drawRow function...

**Comment by eggjoystick** [comment]
I'm not a programmer but if you suggest some changes I'll be glad to try them out. Thanks.

**Comment by jonaski** [comment]
I can't see anything obviously wrong with it. How do you set the scaling?
I have fixed the playlist source icon which was pixelated for the currently playing song.

**Comment by eggjoystick** [comment]
I tried it out on both XFCE and Cinnamon. On XFCE, I am not scaling; it is set to 1x under Settings > Appearance. On Cinnamon, the scaling is set to 2x under Settings > General.

In both cases, the result is the same. All the text for the currently playing song is blurry like in the screenshot I uploaded.

**Comment by eggjoystick** [comment]
Here's a screenshot from XFCE
![strawberry-xfce](https://user-images.githubusercontent.com/58571795/91224273-78fe7f80-e6e7-11ea-9675-bf87c4b8d30d.png)

**Comment by fbugno** [comment]
This also happens with drag over playlist, screenshot attached. And in both cases, the fix is the same, just in a different place.

![Screenshot_20201109_220253](https://user-images.githubusercontent.com/42178763/98615043-8be12300-22d8-11eb-8dba-fdf5a7ff3291.png)

**Comment by jonaski** [comment]
This is most likely fixed now: https://github.com/strawberrymusicplayer/strawberry/pull/587
