### ISSUE TITLE
Native desktop notification does not show available cover art when Strawberry plays certain files

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#520]
**Describe the bug**
Native desktop notification does not show the cover art when Strawberry plays certain flac files despite the cover art appears in the side bar. "Pretty OSD" shows the covert art of the same files as expected.
Apparently it's a random issue as I see no pattern between the affected files.

**To Reproduce**
enable "Show a native desktop notification" in Strawberry settings
play flac files

**Expected behavior**
Strawberry notification should always show available cover art

**Screenshots:**
![strawberry](https://user-images.githubusercontent.com/15967631/90956018-2f006a00-e459-11ea-9a04-d264fb23431c.png)

**System Information:**
 - Operating system: neon unstable based on ubuntu 20.04, KDE Plasma desktop environment
 - Strawberry Version: 0.7.2-12-gc5d9a419

**Comment by jonaski** [comment]
I know about this. I've been debugging it and as far as I can see we are sending D-Bus messages with image each time, even though sometimes it's missing image for the same songs. I can't find any solution or explanation.
