### ISSUE TITLE
Strawberry shows an empty error dialog when computer is disconnected from local network during playback of songs from subsonic compatible media server

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#521]
**To Reproduce**
play songs from subsonic compatible media server (I use navidrome media server)
disconnect your client device from local network

**Expected behavior**
dialog with an error message

**Screenshots:**
![strawberry](https://user-images.githubusercontent.com/15967631/90984609-656ae180-e54c-11ea-94ea-fa78701be4af.png)

**System Information:**
 - Operating system: neon unstable
 - Strawberry Version: 0.7.2-12-gc5d9a419

**Comment by jonaski** [comment]
Works fine here:

![image](https://user-images.githubusercontent.com/10343810/90985124-1176f180-e57a-11ea-9e15-e046a6bf48ee.png)

**Comment by glaubersm** [comment]
humm, I have noticed that an addiitonal step is necessary: minimize and restore the error dialog

**Comment by jonaski** [comment]
I found a possbile cause why the error dialog shows empty sometimes, should hopefully be fixed with bfb95d503a2679db6ef09d74d6b3057e006d3114
