### ISSUE TITLE
feature request: plugins or events

### ISSUE THREAD

**Issue by ccoenen** [strawberrymusicplayer/strawberry#522]
I would like to automate a few things around my music player. A plugin interface would be amazing, but for now the most rudimentary tool I would need would be a few events that can be tied to actions. 

At the most basic level it could be a command the user could specify with a few variables like the ones used in `Context` or `Notification` settings. With this, I could solve almost everything I need. For example:

- call a custom script with currently playing song: whenever a song starts playing, run
  `/home/user/scripts/update.py "%artist% - %title%"`
- update a text file with currently playing song:  whenever a song starts playing, run
  `echo "%artist% - %title%" > now-playing.txt`
- same, but resetting whenever playback pauses
  `truncate now-playing.txt`

Of course, any of these could be much more elaborate, too. There could also be events for "each time the play timestamp advances", "every time the media library is changed" or "every time the playlist is changed" and so on and so forth. But all of this is less important to me.

If all of this is not warranting a fully new section, I'd even be happy with a Scrobble-like plugin, but instead of a http call it just calls a script.

**Comment by jonaski** [comment]
You might be able to use dbus/mpris for some of this: https://github.com/strawberrymusicplayer/strawberry/wiki/Using-MPRIS2-to-get-information-and-control-playback ,you should be able to get most of the info about the current playing track, etc.
If you want more than that you probably have to contribute that yourself to Strawberry in a PR. A plugin interface is a lot of work.
I don't have time to do more feature requests than the ones currently listed in the GitHub issues. Use the forum for feature discussion like described in the README.

**Comment by ccoenen** [comment]
Is there also a way that works on windows?

**Comment by jonaski** [comment]
No, that won't work on windows
