### ISSUE TITLE
Minor graphics glitch in Preferences in strawberry-0.7.2.30.gd18834b4 for macOS

### ISSUE THREAD

**Issue by clementine-user** [strawberrymusicplayer/strawberry#523]
@jonaski see the image below:

![glitch](https://user-images.githubusercontent.com/6315176/91374178-732e9a00-e7cc-11ea-8e95-cda987c66a74.png)

Probably something easy to fix.

Thanks!

**Comment by jonaski** [comment]
I have fixed the spacing between the checkboxes, however, it does not properly layout the forum layout to the left like it should on macOS, perhaps a qt bug.
