### ISSUE TITLE
Enhancement: Allow different views of the iPod library just like the normal library

### ISSUE THREAD

**Issue by gerion0** [strawberrymusicplayer/strawberry#525]
Currently, an iPod is listed as device, which is mainly a file tree. The iPod content itself is then displayed sorted by Interpret/Album/Track. It would be a nice feature if the user can choose this sorting exactly like in the normal library.

**Comment by jonaski** [comment]
That might be nice, but unfortunately I don't have time to prioritize it.

**Comment by gerion0** [comment]
I fully understand that but don't you want to leave this issue open then? Maybe someone sees this issue and implements it or at least can upvote.

**Comment by jonaski** [comment]
Currently there are no other contributors active, contributors mostly tend to do whatever features they want themselves. I have had feature requests open for over 2 years here, it hasn't helped, even very easy things I end up doing myself. We already have 18 other issues/features open, so I'm not planning anything more until most of those are solved. I have to be realistic about what's possible within reasonable time I dedicate to work on this project.
I moved the feature discussion to the forum, it is written in the README, so it's still possible to discuss what could be done in the future, but leaving issue open isn't a solution to anything, it just gives a false impression that we plan to do something.

**Comment by gerion0** [comment]
Ok, understand that. Thanks for your explanation.
