### ISSUE TITLE
Subsonic Listing/ordering options

### ISSUE THREAD

**Issue by DOFfactory** [strawberrymusicplayer/strawberry#526]
**Describe the bug**
I am using the Strawberry for its excellent Subsonic support. I tried to list the catalogue by using "Added today" "Added this week" etc. It seems none of them are working with Subsonic, except the "Show entire collection"

**To Reproduce**
Steps to reproduce the behavior.
![image](https://user-images.githubusercontent.com/10846169/91714888-ecdbd480-eb8c-11ea-9e30-c1838471c365.png)

**Expected behavior**
It should list by the selected option

**Screenshots:**
See above.

**System Information:**
 - Operating system: Wind 10
 - Strawberry Version: 0.7.2

**Comment by DOFfactory** [comment]
Apologies, I would re-open this issue, as there is no change regarding this bug:

![image](https://user-images.githubusercontent.com/10846169/95655071-1b8e8880-0b05-11eb-81cc-a6d310361655.png)

I am using Strawberry v 0.8.1
OS: Win 10
Subsonic backend: LMS - [https://github.com/epoupon/lms](https://github.com/epoupon/lms)

**Comment by jonaski** [comment]
You need to refresh catalogue.

**Comment by DOFfactory** [comment]
Thanks for the tip, I tried multiple times, but it is still not working.

**Comment by jonaski** [comment]
I only tested with Airsonic, and it's definitely working, however there are so many subsonic server forks that it is impossible for me to test on all of them. I think there was a LMS test server, I can test that one if I can still find it

**Comment by DOFfactory** [comment]
Yup, here is the demo: https://lms.demo.poupon.io/

I wonder whether I need to delete my current database to make the changes. I was really looking forward to this function :)

**Comment by jonaski** [comment]
Looks like LMS is sending "created" only for each album and not for individual songs, fixed now.

**Comment by DOFfactory** [comment]
Thanks @jonaski. Would it be please possible to make a new release to test it in a relatively short period of time, as the interval between releases last time was rather long. I know (read your blog) there were some issues, just kindly making an inquiry.

**Comment by jonaski** [comment]
You should be able to use the one that is automatically built when it is finished it's uploaded here: https://builds.strawberrymusicplayer.org/windows/
You can see the status here: https://buildbot.strawberrymusicplayer.org/#/console
When the commit with "Subsonic: Read created from album too " shows up there and is green for windows, then it's ready. It will take a few hours though.

**Comment by DOFfactory** [comment]
Thanks, this works!
