### ISSUE TITLE
App crash on Clearing Playlist of tracks added using Middle Click

### ISSUE THREAD

**Issue by Tibokan** [strawberrymusicplayer/strawberry#527]
**Describe the bug**
Using the middle click to quickly and easily add tracks to the playlist works great, however, after doing so, if you try to clear the playlist, the app crashes/force closes.

**To Reproduce**
Add a track or album from your collection using middle click, and then try to clear the playlist using the right click playlist options.

**Expected behaviour**
Should clear the playlist without crashing the app.

**Screenshots:**
![Screen Shot 2020-09-03 at 1 38 35 pm](https://user-images.githubusercontent.com/69946799/92068670-e0ed4e00-edea-11ea-95a2-0b6ee4ab687b.png)
![Screen Shot 2020-09-03 at 1 38 44 pm](https://user-images.githubusercontent.com/69946799/92068677-e5196b80-edea-11ea-9744-8fd783e25dda.png)

**System Information:**
 - Operating system: MacOS 10.13.6
 - Strawberry Version: 0.7.2.73 (though this happens with all Strawberry versions I've tried)

**Comment by jonaski** [comment]
It occurs when deleting queued songs, middle click queues the songs.
Possible fix: https://github.com/strawberrymusicplayer/strawberry/commit/ba34cf525806ef068e70fc696569a28c51ac45d1
Try the new build when available.

**Comment by Tibokan** [comment]
Just tested it now, works great, no crash anymore. Thanks! Very quick turnaround!

**Comment by madprops** [comment]
> middle click queues the songs.

I'm wondering why this is not the case inside the playlist, only in the Collection sidebar...
