### ISSUE TITLE
Tag Editing causes 'Various artists' tracks to shift away from the main album

### ISSUE THREAD

**Issue by Tibokan** [strawberrymusicplayer/strawberry#528]
**Describe the bug**
Having your 'Various Artists' albums sitting at the top of the Music Collection under 'Various artists' in Strawberry usually works great, however, the moment you edit a tag for a particular track for an album sitting in that collection, that track gets pushed back under a separate Various Artists category under V in the main Music Collection. To regroup that track back with its other album tracks under 'Various artists' sitting at the top of your Music Collection, you have to right click and select 'Show under Various artists' to bring it back up. However, it will then show up as a duplicate album with no tracks accessible underneath, until you close Strawberry and then reopen, and it is then grouped correctly with the other album tracks under 'Various artists'.

This issue also occurs if you edit the filename of a track from a 'Various artists' album stored on your hard drive and contained within your Strawberry Music Collection whilst Strawberry is open and has background music collection refresh on. That file you renamed will be moved down to its own entry under V, Various Artists, away from the rest of the album still residing under 'Various artists'. Using the right click, 'Show under Various artists' will do the same behaviour as mentioned in the other scenario above (duplicate album, track inaccessible, fixed with a Strawberry app close and restart).

**To Reproduce**
Add an album with Various Artists as the Album Artist to your music collection, and you'll find it under V, Various Artists, right click and select 'Show under Various artists', which will move it to the 'Various artists' collection at the very top of the Album Artist list. Then edit the tag of a track, and that track will get shifted back down by itself under V, Various Artists. Right click that album and select 'Show under Various artists' and you will then get it moved back up to the top 'Various artists' and show as a duplicate album item with no tracks. Close Strawberry and reopen to then find it has grouped itself correctly as a complete album under 'Various artists' again.

In the second scenario, edit the filename of a track from a 'Various artists' album stored on your hard drive and contained within your Strawberry Music Collection whilst Strawberry is open and has background music collection refresh on.

**Expected behaviour**
Should remain where it is the whole time, as per its original grouping under 'Various artists' at the very top of the collection. Changing tags or filenames should not cause this behaviour to occur, as it's a pain to constantly have to do the manual workaround and reopen Strawberry everytime you edit tags for a compilation album to keep them grouped together in the same place. I have provided a screenshot journey of this issue with the track 'Here With Me', which I renamed to 'Here With M' for the purposes of demonstrating this issue.

**Screenshots:**
![Screen Shot 2020-09-03 at 1 59 56 pm](https://user-images.githubusercontent.com/69946799/92070428-54915a00-edef-11ea-9693-4ecaec769195.png)
![Screen Shot 2020-09-03 at 2 00 14 pm](https://user-images.githubusercontent.com/69946799/92070437-58bd7780-edef-11ea-8e7b-bc5d07769066.png)
![Screen Shot 2020-09-03 at 2 00 36 pm](https://user-images.githubusercontent.com/69946799/92070441-59560e00-edef-11ea-850a-a2aa1b00fb95.png)
![Screen Shot 2020-09-03 at 2 01 56 pm](https://user-images.githubusercontent.com/69946799/92070442-59eea480-edef-11ea-9161-eeb34a7af9fa.png)
![Screen Shot 2020-09-03 at 2 02 20 pm](https://user-images.githubusercontent.com/69946799/92070443-5a873b00-edef-11ea-92a4-a79658358a15.png)

**System Information:**
 - Operating system: MacOS 10.13.6
 - Strawberry Version: 0.7.2.73 (applies to all versions of Strawberry I've used)

**Additional context**
I think this issue relates to the way that Strawberry has been setup to handle the distinction between 'Various artists' sitting at the top of the Music Collection, versus having an album with the Various Artists album artists sitting under V, Various Artists. My uneducated guess is that this distinction is handled within Strawberry, and not applied to the file itself (so when the file is effectively refreshed within Strawberry by being retagged, it 'forgets' that it was previously assigned by the user to 'Various artists').

To provide a counterpoint, iTunes for example, utilises a 'Compilation' tag/flag for this purpose, which is then written to the file tag and will store the album under 'Compilations, please see screenshot below:

![Screen Shot 2020-09-03 at 1 55 34 pm](https://user-images.githubusercontent.com/69946799/92070448-5eb35880-edef-11ea-8238-62672f2a18d8.png)

Strawberry doesn't appear to have a way of displaying, utilising or editing the compilation tag/flag, which otherwise would solve this problem permanently (ie. Use the compilation tag to place albums into 'Various artists' if present, or keep under V, Various Artists, until the compilation tag/flag is applied to the track files. If this full solution can be implemented, having the ability to edit this compilation tag/flag on and off would be very beneficial, such as within the Playlist Views (ie. with a displayable column that allows toggle on/off of this flag and display of the flag when it has already been applied to the file) and the Edit Tag Views (ie. maybe a tick box like in iTunes).

**Comment by Tibokan** [comment]
Did some additional testing with tagged/untagged files, and even with the album image reapplied into the file tag and made the same for all album tracks, duplicates of the same album are still showing up in Cover Manager.

**Comment by jonaski** [comment]
Fixed now so it keeps compilation flags when the files are rescanned.
In the case where you rename a file, it will lose the manually set data.

**Comment by Tibokan** [comment]
Great, thank you!

As a side note, would it be possible to include a 'Is Compilation' column as a toggleable column within Playlist View and as a tickbox in the 'Edit Tag' function? I currently have to use separate software to toggle this item on/off within my track tags, and it would be a very handy addition to Strawberry.

**Comment by jonaski** [comment]
Yes, I was thinking of doing that
