### ISSUE TITLE
Using Command+Q to close Strawberry with Cover Manager open will cause an app crash

### ISSUE THREAD

**Issue by Tibokan** [strawberrymusicplayer/strawberry#530]
**Describe the bug**
As per title, using Command+Q to close Strawberry in MacOS with the Cover Manager box open will cause an app crash.

**To Reproduce**
Open Strawberry, open Cover Manager, close Strawberry using Command+Q

**Expected behavior**
Whilst it's not the biggest problem as you're wanting to close Strawberry anyway, it should not cause a crash and generate a crash report in MacOS.

**Screenshots:**
![Screen Shot 2020-09-03 at 2 23 00 pm](https://user-images.githubusercontent.com/69946799/92071019-054c2900-edf1-11ea-8930-3db0b872fa87.png)
![Screen Shot 2020-09-03 at 2 23 11 pm](https://user-images.githubusercontent.com/69946799/92071024-0a10dd00-edf1-11ea-8821-ec12ba9753ae.png)

**System Information:**
 - Operating system: MacOS 10.13.6
 - Strawberry Version: 0.7.2.73 (happens on all Strawberry versions I've tried)

**Comment by jonaski** [comment]
I can reproduce this crash on macOS, but not on Linux. My guess is that the object is destroyed too early most likely we should use deleteLater() instead.
