### ISSUE TITLE
sort collection by album?

### ISSUE THREAD

**Issue by beew** [strawberrymusicplayer/strawberry#536]
Hi, 

I am wondering if there is a way to group music by album instead of just artists? There are albums with multiple artists and right now if there are several tracks by different artists in the same album it just goes under "unknown". There maybe some settings that I can set but I am not finding it.

Thanks.

**Comment by jonaski** [comment]
You can select "group by" on the "tools" button.
Use the forum for questions/help: https://forum.strawberrymusicplayer.org/

**Comment by beew** [comment]
I don't see any "group by" on the tools tab.

**Comment by Tibokan** [comment]
It's pretty straightforward, Strawberry is quite powerful in the number of display options you have available to you for displaying your music collection

![Screen Shot 2020-09-08 at 12 33 57 pm](https://user-images.githubusercontent.com/69946799/92427354-97787680-f1cf-11ea-9044-8ce770d00a38.png)

**Comment by beew** [comment]
Oh, saw it, I was looking at the tools tab on the top and didn't see the little wench icon that only shows in the Collection tab, I thought it was configured in Tools > Settings.

Thanks.
