### ISSUE TITLE
Japanese songs are only found if searches match from the start

### ISSUE THREAD

**Issue by KingDuckZ** [strawberrymusicplayer/strawberry#537]
For technical issues, questions and feature requests please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
In my collection I have many songs with a Japanese title. For example ルージュの伝言 (ruujyu no dengon). If I enter the whole string in the search bar, or a prefix of it for example ルージュ (ruujyu=lipstick) the song gets found normally. However if I look for 伝言 (dengon=message) no songs are found. This is in contrast with Latin alphabet songs, for example both searches "poker" and "face" yield "Poker Face".

**To Reproduce**
1. Get a song with a Japanese title
2. in the song search type a substring that is not a prefix of the title of that song
3. no songs are found

**Expected behavior**
Both searches "ルージュ" and "伝言" should yield the song "ルージュの伝言".

**Screenshots:**

**System Information:**
 - Operating system: Windows something
 - Strawberry Version: 0.7.2

**Additional context**

**Comment by jonaski** [comment]
You need to explain this one.
How does this have anything to do with Japanese characters?
You can match "poker" and "face" individually because there is a space between.
It will never have matched the end of a word like in your example of "伝言", just the beginning.

Query:
`SELECT DISTINCT effective_albumartist FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE fts.songs_fts MATCH 'You*' AND +compilation_effective = 0 AND unavailable = 0;`
Works for finding "Neil Young"

`SELECT DISTINCT effective_albumartist FROM songs INNER JOIN songs_fts AS fts ON songs.ROWID = fts.ROWID WHERE fts.songs_fts MATCH 'ung*' AND +compilation_effective = 0 AND unavailable = 0;`
Does not find "Neil Young"

**Comment by KingDuckZ** [comment]
Well that's the mistake then, in Japanese you don't use the space character to separate words! No one would write `ルージュ  の  伝言` but it's still 3 words. Have a look at some [wikipedia article](https://ja.wikipedia.org/wiki/%E3%83%91%E3%83%96%E3%83%AA%E3%83%83%E3%82%AF%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3) if you want to get a feeling for what it looks like. Yes, it's hard to read! :D

Probably what would fix this is to detect if the search string contains Japanese characters (or other languages that don't use spaces) and do a "substring" search for those.

On the "if the search string contains Japanese characters" part, I found [this](https://social.msdn.microsoft.com/forums/en-US/0d1888de-9745-4dd1-80fd-d3c29d3e381d/checking-for-japanese-characters-in-a-string) discussion where they say which unicode ranges are reserved for Japanese characters. They mention kanji-only text (eg: "伝言") to be indistinguishable from Chinese, it's probably true but I think Chinese also doesn't use spaces so imo it's not something to be worried about in this case. You'd actually fix two languages for the price of one :)

**Comment by jonaski** [comment]
I see.
It might be possible to improve it. I'm not sure I have time to prioritize it, but if you or someone else want to look at it,  the documentation is here: https://www.sqlite.org/fts5.html
The code is here: https://github.com/strawberrymusicplayer/strawberry/blob/master/src/collection/collectionquery.cpp

**Comment by lc-guy** [comment]
For what it's worth, this is still a bug and rather important for those with a sensible East Asian music collection

**Comment by jonaski** [comment]
I don't see any way to do it with the FTS search that is used for the collection search.
But I'm considering dropping FTS altogether, see: https://github.com/strawberrymusicplayer/strawberry/pull/729
