### ISSUE TITLE
(macOS) Switching Apps with a Pop Up Menu open keeps that menu open over other Apps

### ISSUE THREAD

**Issue by Tibokan** [strawberrymusicplayer/strawberry#538]
**Describe the bug**
Bit of a weird one, if you bring up a pop-up menu in Strawberry (ie. album options, album display options, playlist options etc.), and if you don't choose an available option, leave it open and bring up another app using the dock (ie. Chrome in my example below), that pop up menu remains visible over that app. This may be a MacOS specific issue.

**To Reproduce**
Bring up a pop-up menu in Strawberry and use your dock to bring up another app. You should continue to see the pop-up menu.

**Expected behavior**
That pop-up menu should close or disappear.

**Screenshots:**
![Screen Shot 2020-09-08 at 12 35 54 pm](https://user-images.githubusercontent.com/69946799/92427659-677da300-f1d0-11ea-91b4-1cd457ddbd03.png)

**System Information:**
 - Operating system: MacOS 10.13.6
 - Strawberry Version: 0.7.2.90

**Comment by jonaski** [comment]
This does not happen on Linux or Windows. Looks like a Qt bug too me.

**Comment by jonaski** [comment]
Maybe related to this: https://bugreports.qt.io/browse/QTBUG-30522

**Comment by jonaski** [comment]
@MartinDelille Have you seen this issue before?

**Comment by llucps** [comment]
@jonaski Yes it happens to me to.. but I didn't want to bother you for such small bug. This only happens when the pop-up menu is active and then changing to another application.

![Screenshot 2020-09-15 at 18 22 58](https://user-images.githubusercontent.com/25823659/93237518-88219c00-f780-11ea-8df2-710db116bc71.jpg)

**Comment by jonaski** [comment]
I created a small test program, it does not occur with the test program so it must be something specifically strawberry does.

**Comment by Tibokan** [comment]
If it helps, I did notice that Clementine 1.3.1 doesn't have this issue, so the fix is likely to be code-specific somewhere within Strawberry, rather than being one of those unsolvable QT bugs.

**Comment by Tibokan** [comment]
Interestingly, after having done some further digging around on this issue, I noticed that there is a QT bug that can be replicated in the current version of Strawberry, https://bugreports.qt.io/browse/QTBUG-77833
This bug was supposedly solved by the QT team last year (it's marked as 'Resolved'), yet if I open a right click menu and minimise Strawberry, the right click menu stays open, despite Strawberry running on a later version of QT, 5.15.1, than the version that was listed and solved in the bug report (5.12.4).

**Comment by jonaski** [comment]
The fix in https://bugreports.qt.io/browse/QTBUG-77833 isn't included in 5.15.1 (I've compared the source for 5.15.1 with the dev branch).
I have no idea why as the it was done a year ago. But this is most likely resolved when we upgrade to Qt 6.
