### ISSUE TITLE
Feature Request: Add Shortcut for 'Next Album'

### ISSUE THREAD

**Issue by divisionbyzeroerror** [strawberrymusicplayer/strawberry#540]
When listening to a ton of new music, sometimes it would be great to be able to skip to the next album instead of the next track. Could we bind a shortcut to jump ahead in the playlist to the first track of the next album? This track would be identified as the next track in the playlist with a different album title as compared to the currently playing track. 

For symmetry, there should probably also be a shortcut created at the same time that would jump to the previous album as well. But this is not required nor would it in my opinion be very useful.

**Comment by divisionbyzeroerror** [comment]
@jonaski is that a no? As in not even any discussion?

**Comment by jonaski** [comment]
Use the forum
