### ISSUE TITLE
Problem adding tracks with non-latin filenames/id3v2 tags

### ISSUE THREAD

**Issue by DOFfactory** [strawberrymusicplayer/strawberry#541]
For technical issues, questions and feature requests please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
There is a strange bug with adding files to the playlist (from Subsonic server) with some non-latin but UTF-8 filenames/id3v2 tags. In my case it is a group of songs with Icelandic characters

**To Reproduce**
Drag and drop some files with non-latin characters in filenames/id3v2 tags to the playlist. Only few of them will be added.

**Expected behavior**
All non-standard files should be added.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10846169/92915348-c4759500-f42c-11ea-9e34-cb2b15c5125e.png)

From the screenshot you can see that all files have been selected, but only 2 were added.

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 0.7.2

**Comment by jonaski** [comment]
I can't reproduce this issue. I tested to tag some Icelandic characters to 2 songs, one FLAC and one MP3 and I can add both to the playlist from the subsonic songs.
Maybe something else is causing this, I see in your example that "Gott Piano" does not have any special characters.

![image](https://user-images.githubusercontent.com/10343810/92954980-aa57a900-f464-11ea-9dd1-8d011e3c6162.png)

**Comment by NucleaPeon** [comment]
Can you reproduce this issue with other music players? I wonder if it might possibly be a subsonic issue and it would be nice to know if it is specific to strawberry.

**Comment by DOFfactory** [comment]
Something weird is happening, either server-side or in strawberry. Regarding the non-latin characters in filenames/id3v2 tags that the issue was a false alarm, as I refreshed the catalogue, and adding the files is working again. However, this makes me wonder what was wrong exactly, as **I did not do any changes on the server**. Did the catalogue database in strawberry got corrupted somehow? How can I check it in the future?

**Comment by jonaski** [comment]
Most likely something happened to the database, maybe it recovered by itself, but I recommend to do an integrity check of it.
See: https://github.com/strawberrymusicplayer/strawberry/wiki/Database-integrity-check
You need sqlite-tools from: https://www.sqlite.org/download.html
I'm going to bundle sqlite3.exe in the program files folder in the future, but currently you need to download it manually.
