### ISSUE TITLE
[Feature] I would like a way to add entire collection to playlist.

### ISSUE THREAD

**Issue by tholin** [strawberrymusicplayer/strawberry#543]
I'm trying to migrate from Clementine to Strawberry but there are a few regressions that prevent me from doing that. One of those are the removal of the "All tracks" smart playlist.

I like to keep my entire collection in the playlist. That way I can do shuffle play of the entire collection, I can list my collection by play count, I can sort the collection by mod time to find new and old tracks, and a lot of other things only possible with the entire collection in the playlist.

The only way I found to add the full collection to the playlist is by selecting everything from the collections tab (strawberry freeze for several minutes if I do that) or drag the collection's folder from files (that takes forever). Using "All tracks" in Clementine only took a few seconds.

Related issue: https://github.com/strawberrymusicplayer/strawberry/issues/392

**Comment by jonaski** [comment]
Why do you open an issue for this? Don't you see the bug template?
There is already work in progress to add back smart/dynamic playlists, it's almost finished and will be in the next release.
