### ISSUE TITLE
changing Jack output will cause error "Resource not found."

### ISSUE THREAD

**Issue by mxa** [strawberrymusicplayer/strawberry#546]
**Describe the bug**
Applications should handle a temporary unavailability of Jack such as happens when switching the soundcard. Stawberry doesn't handle it gracefully. 

**To Reproduce**
Play music in Strawberry and then change the soundcard in Jack (QjackCtl)

**Expected behavior**
Music will continue ti play but now from the new output.

**What actually happens**
Error "Resource not found." will pop up.

**System Information:**
 - Operating system: Kubuntu 20.04
 - Strawberry Version: 0.7.2

**Comment by jonaski** [comment]
Use a different player.

**Comment by mxa** [comment]
Going to bookmark this response, it's perfect for any issue.
