### ISSUE TITLE
Can't set same key as shortcut for two actions (play/pause)

### ISSUE THREAD

**Issue by n-o-o-b** [strawberrymusicplayer/strawberry#553]
I am trying to assign the spacebar to work as a toggle for play/pause. The settings interface will not allow me to set spacebar as a shortcut for both actions. As soon as I set it a second time, it gets removed as a shortcut for the first action.

 - Operating system: Windows 10
 - Strawberry Version: 0.7.2

**Comment by jonaski** [comment]
There is an action for play/pause. This is an odd issue to open, what is the problem with using the "play/pause" action?

**Comment by n-o-o-b** [comment]
Sorry, my Strawberry window was not focused and I percieved it as not working, and then I forgot to close this issue. Apologies.
