### ISSUE TITLE
Some UI settings not taking effect after relaunching application

### ISSUE THREAD

**Issue by linlinxza** [strawberrymusicplayer/strawberry#554]
**Brief Description**

Changes regarding the sidebar appearance and removing columns does not remain in effect after closing and then opening the media player.

**Steps:**

1. Change something in the UI like the sidebar appearance. Or change up the columns.
2. Close.
3. Open.
4. Columns and sidebar revert to default settings.

**What's expected**
Preferences for changing UI elements should be saved.

**System Information:**
 - Operating system: KDE Neon
 - Strawberry Version: 0.7.2

**Additional context**
It seems like the application is not writing those specific settings to the strawberry.conf file. Judging from the fact that I use Kate to check if the file had been changed in anyway. In which case, it doesn't show anything had been changed with the conf file after applying the desired settings in the Strawberry application.

**EDIT**

I think something is messed up with my system or something. I used a fresh install of focal version of KDE Neon in a VM and all it works. Must be something up with my system after upgrading to focal from Bionic. But this issue might be worth checking out if possible. Either case, I grabbed a copy of strawberry.conf from the VM with the settings I want, and it works. Strange.

**Comment by jonaski** [comment]
A few settings like window positions, playlist columns, sidebar, etc are only saved on exit. If Strawberry does not exit cleanly, ie. crashes before it get's a chance to save settings, this can be caused by package conflicts, incompatible library versions, etc, most of the time the problem is with the system, some package is still at the old version, or the distro package for strawberry has not been rebuilt updated libraries. Can also be caused by read only strawberry.conf, file system errors, etc.

**Comment by linlinxza** [comment]
I think it's due to me not having qt 5.8. How could I check on the system for 
this?

**Comment by jonaski** [comment]
If KDE Neon is based on Ubuntu 20.04 LTS then it has Qt 5.12.8
Qt 5.8 is pretty old now, 3 1/2 years old, no longer supported by Qt.
If you had an older version than that you would never have been able to launch strawberry at all.

**Comment by linlinxza** [comment]
Oh! Now I see in the info. It looked like it was an older version with the 
leading 1 after the 5. lol

I actually have 5.15. So which package could be the issue then? Because it is 
GUI related.

**Comment by jonaski** [comment]
Run strawberry from the terminal through gdb too see what happens when it exit.
Type
`
gdb strawberry
`
`
run
`
then exit strawberry like you would. If you get a segmentation fault, type: `backtrace` and paste the output here.

**Comment by linlinxza** [comment]
Here it is, attached. I don't think I saw anything out of the ordinary.

On Wednesday, October 7, 2020 12:48:56 P.M. MDT Jonas Kvinge wrote:
> gdb strawberry
Starting program: /usr/bin/strawberry 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
12:50:53.067 INFO  main:171                         Strawberry 0.7.2
12:50:53.067 INFO  main:172                         "KDE neon User Edition 5.19 20.04 - (linux 5.4.0-48-generic) [x86_64]"
[New Thread 0x7fffeb33e700 (LWP 1918719)]
[New Thread 0x7fffe8d4a700 (LWP 1918720)]
12:50:53.575 DEBUG Application:242                  Database(0x55555654add0) moved to thread QThread(0x555556550920)
[New Thread 0x7fffe354c700 (LWP 1918721)]
12:50:53.576 DEBUG SCollection:62                   CollectionBackend(0x555556549b00) moved to thread QThread(0x555556550920)
[New Thread 0x7fffe2d4b700 (LWP 1918722)]
12:50:53.640 DEBUG Application:242                  AlbumCoverLoader(0x555556594710) moved to thread QThread(0x5555565aeb60)
[New Thread 0x7fffe24d1700 (LWP 1918723)]
[New Thread 0x7fffe1cd0700 (LWP 1918724)]
12:50:53.644 DEBUG SCollection:94                   CollectionWatcher(0x55555659a5b0) moved to thread QThread(0x5555565c0690)
[New Thread 0x7fffe14cf700 (LWP 1918725)]
12:50:53.648 DEBUG Application:242                  TagReaderClient(0x5555565bc720) moved to thread QThread(0x5555562ef290)
[New Thread 0x7fffe0cce700 (LWP 1918726)]
12:50:53.649 DEBUG NetworkProxyFactory:55           Detected system proxy URLs: ("", "", "", "")
12:50:53.649 DEBUG WorkerPool<HandlerType>:282      Starting worker 0x7fffe0cccf10 "/usr/bin/strawberry-tagreader" "/tmp/strawberry_812542245"
[Detaching after vfork from child process 1918727]
12:50:53.655 DEBUG WorkerPool<HandlerType>:282      Starting worker 0x7fffe0cccf10 "/usr/bin/strawberry-tagreader" "/tmp/strawberry_897974892"
[Detaching after vfork from child process 1918728]
12:50:53.659 DEBUG WorkerPool<HandlerType>:282      Starting worker 0x7fffe0cccf10 "/usr/bin/strawberry-tagreader" "/tmp/strawberry_427446779"
[Detaching after vfork from child process 1918729]
12:50:53.664 INFO  main:56                          TagReader worker connecting to "/tmp/strawberry_812542245"
[New Thread 0x7fffb7fff700 (LWP 1918730)]
[New Thread 0x7fffb77fe700 (LWP 1918731)]
12:50:53.667 INFO  main:56                          TagReader worker connecting to "/tmp/strawberry_897974892"
12:50:53.670 DEBUG WorkerPool<HandlerType>:300      Worker 0x7fffb0006790 connected to "/tmp/strawberry_812542245"
12:50:53.670 DEBUG WorkerPool<HandlerType>:300      Worker 0x7fffb0007cc0 connected to "/tmp/strawberry_897974892"
[New Thread 0x7fffb6ffd700 (LWP 1918732)]
[New Thread 0x7fffb67fc700 (LWP 1918733)]
[New Thread 0x7fffb5ffb700 (LWP 1918734)]
12:50:53.671 INFO  main:56                          TagReader worker connecting to "/tmp/strawberry_427446779"
12:50:53.672 DEBUG WorkerPool<HandlerType>:300      Worker 0x7fffb0006360 connected to "/tmp/strawberry_427446779"
12:50:53.679 DEBUG GlobalShortcutBackendGSD:53      Registering
12:50:53.680 WARN  GlobalShortcutBackendGSD:65      Gnome settings daemon not registered
12:50:53.721 WARN  unknown                          Icon theme "Numix-Circle" not found. 
12:50:54.015 INFO  Player:799                       Registered URL handler for "subsonic"
12:50:54.021 DEBUG InternetServices:49              Added internet service "Subsonic"
12:50:54.021 INFO  Player:799                       Registered URL handler for "tidal"
12:50:54.033 DEBUG InternetServices:49              Added internet service "Tidal"
12:50:54.142 DEBUG MainWindow:292                   Starting
12:50:54.204 DEBUG CoverProviders:105               Registered cover provider "Last.fm"
12:50:54.204 DEBUG CoverProviders:105               Registered cover provider "MusicBrainz"
12:50:54.205 DEBUG CoverProviders:105               Registered cover provider "Discogs"
12:50:54.205 DEBUG CoverProviders:105               Registered cover provider "Deezer"
12:50:54.205 DEBUG CoverProviders:105               Registered cover provider "Qobuz"
12:50:54.205 DEBUG CoverProviders:105               Registered cover provider "Musixmatch"
12:50:54.205 DEBUG CoverProviders:105               Registered cover provider "Spotify"
12:50:54.205 DEBUG CoverProviders:105               Registered cover provider "Tidal"
12:50:54.214 DEBUG LyricsProviders:103              Registered lyrics provider "AudD"
12:50:54.214 DEBUG LyricsProviders:103              Registered lyrics provider "Genius"
12:50:54.214 DEBUG LyricsProviders:103              Registered lyrics provider "Lyrics.ovh"
12:50:54.214 DEBUG LyricsProviders:103              Registered lyrics provider "LoloLyrics"
12:50:54.214 DEBUG LyricsProviders:103              Registered lyrics provider "Musixmatch"
12:50:54.214 DEBUG LyricsProviders:103              Registered lyrics provider "ChartLyrics"
12:50:54.348 DEBUG MainWindow:336                   Initialising player
12:50:54.356 DEBUG MainWindow:346                   Creating models
12:50:54.356 DEBUG MainWindow:353                   Creating models finished
[New Thread 0x7fffb4a9a700 (LWP 1918743)]
[New Thread 0x7fff9bfff700 (LWP 1918744)]
12:50:54.377 DEBUG DeviceLister:66                  CddaLister(0x5555573830b0) moved to thread QThread(0x555557406c80)
[New Thread 0x7fff9b7fe700 (LWP 1918745)]
12:50:54.377 DEBUG DeviceLister:66                  Udisks2Lister(0x55555745b840) moved to thread QThread(0x55555740b9e0)
[New Thread 0x7fff9affd700 (LWP 1918746)]
12:50:54.378 DEBUG DeviceLister:66                  GioLister(0x5555572edaf0) moved to thread QThread(0x555557408070)
12:50:54.384 DEBUG Application:242                  PlaylistBackend(0x5555574783b0) moved to thread QThread(0x555556550920)
[New Thread 0x7fff9a7fc700 (LWP 1918747)]
12:50:54.390 DEBUG MainWindow:371                   Creating UI
[New Thread 0x7fff99ffb700 (LWP 1918748)]
12:50:54.411 DEBUG logging:83(GLib-GIO)             _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
12:50:54.414 DEBUG ScrobblerServices:49             Registered scrobbler service "Last.fm"
12:50:54.415 DEBUG ScrobblerServices:49             Registered scrobbler service "Libre.fm"
12:50:54.415 DEBUG ScrobblerServices:49             Registered scrobbler service "ListenBrainz"
12:50:54.460 DEBUG MainWindow:779                   Creating playing widget
12:50:54.762 DEBUG MainWindow:822                   Loading settings
12:50:54.906 DEBUG MainWindow:938                   Started QThread(0x555556231300)
12:50:54.946 INFO  DeviceManager:442                Device added: "/dev/sr0" ("/dev/sr0")

12:51:13.692 DEBUG SCollection:136                  CollectionBackend(0x555556549b00) successfully exited.
12:51:13.692 DEBUG Application:283                  PlaylistBackend(0x5555574783b0) successfully exited.
12:51:13.692 DEBUG DeviceManager:211                CddaLister(0x5555573830b0) successfully closed.
12:51:13.692 DEBUG SCollection:136                  CollectionWatcher(0x55555659a5b0) successfully exited.
12:51:13.692 DEBUG Application:283                  SCollection(0x555556539c30) successfully exited.
12:51:13.692 DEBUG Application:283                  AlbumCoverLoader(0x555556594710) successfully exited.
12:51:13.692 DEBUG DeviceManager:211                Udisks2Lister(0x55555745b840) successfully closed.
12:51:13.692 DEBUG TidalService:229                 CollectionBackend(0x555556ab2540) successfully exited.
12:51:13.692 DEBUG DeviceManager:211                GioLister(0x5555572edaf0) successfully closed.
12:51:13.692 DEBUG TidalService:229                 CollectionBackend(0x5555562fdfd0) successfully exited.
12:51:13.692 DEBUG Application:283                  TagReaderClient(0x5555565bc720) successfully exited.
12:51:13.692 DEBUG TidalService:229                 CollectionBackend(0x55555653bdc0) successfully exited.
12:51:13.692 DEBUG Application:283                  InternetServices(0x555556a50ca0) successfully exited.
12:51:13.693 DEBUG DeviceManager:199                DeviceDatabaseBackend(0x5555567ec2e0) successfully closed.
12:51:13.693 DEBUG Application:283                  DeviceManager(0x555557384d20) successfully exited.
12:51:13.695 DEBUG GlobalShortcutBackendSystem:67   Unregistering
[Thread 0x7fff9bfff700 (LWP 1918744) exited]
[Thread 0x7fff9affd700 (LWP 1918746) exited]
[Thread 0x7fff9b7fe700 (LWP 1918745) exited]
[Thread 0x7fffb4a9a700 (LWP 1918743) exited]
[Thread 0x7fffe24d1700 (LWP 1918723) exited]
[Thread 0x7fffe354c700 (LWP 1918721) exited]
[Thread 0x7fffe0cce700 (LWP 1918726) exited]
12:51:13.722 DEBUG LyricsProviders:124              Unregistered lyrics provider "ChartLyrics"
12:51:13.722 DEBUG LyricsProviders:124              Unregistered lyrics provider "Musixmatch"
12:51:13.722 DEBUG LyricsProviders:124              Unregistered lyrics provider "Genius"
12:51:13.723 DEBUG LyricsProviders:124              Unregistered lyrics provider "LoloLyrics"
12:51:13.723 DEBUG LyricsProviders:124              Unregistered lyrics provider "Lyrics.ovh"
12:51:13.723 DEBUG LyricsProviders:124              Unregistered lyrics provider "AudD"
12:51:13.723 DEBUG CoverProviders:126               Unregistered cover provider "Qobuz"
12:51:13.723 DEBUG CoverProviders:126               Unregistered cover provider "Discogs"
12:51:13.723 DEBUG CoverProviders:126               Unregistered cover provider "MusicBrainz"
12:51:13.723 DEBUG CoverProviders:126               Unregistered cover provider "Last.fm"
12:51:13.723 DEBUG CoverProviders:126               Unregistered cover provider "Deezer"
12:51:13.723 DEBUG CoverProviders:126               Unregistered cover provider "Musixmatch"
12:51:13.723 DEBUG CoverProviders:126               Unregistered cover provider "Spotify"
12:51:13.723 DEBUG CoverProviders:126               Unregistered cover provider "Tidal"
[Thread 0x7fffe1cd0700 (LWP 1918724) exited]
12:51:13.724 DEBUG WorkerPool<HandlerType>:178      Closing worker socket
12:51:13.726 DEBUG WorkerPool<HandlerType>:178      Closing worker socket
12:51:13.728 DEBUG WorkerPool<HandlerType>:178      Closing worker socket
[Thread 0x7fffe2d4b700 (LWP 1918722) exited]
[Thread 0x7fffb67fc700 (LWP 1918733) exited]
[Thread 0x7fffb6ffd700 (LWP 1918732) exited]
[Thread 0x7fffb77fe700 (LWP 1918731) exited]
[Thread 0x7fffb7fff700 (LWP 1918730) exited]
[Thread 0x7fffb5ffb700 (LWP 1918734) exited]
[Thread 0x7fffe14cf700 (LWP 1918725) exited]
[Thread 0x7fffeb33e700 (LWP 1918719) exited]
[Thread 0x7fffe8d4a700 (LWP 1918720) exited]
[Thread 0x7fff9a7fc700 (LWP 1918747) exited]
[Thread 0x7fffebf650c0 (LWP 1918707) exited]
--Type <RET> for more, q to quit, c to continue without paging--
[Inferior 1 (process 1918707) exited normally]

**Comment by jonaski** [comment]
That's a normal exit, no problems logged.
Will changes made in the settings dialog persist after restarting Strawberry?

**Comment by linlinxza** [comment]
Here's another without the use of gdb. I just simply run it from the terminal. 
And it said this: ERROR Database:91 Connection "1_thread_94544816194304" is 
still open!

On Wednesday, October 7, 2020 12:48:56 P.M. MDT Jonas Kvinge wrote:
> gdb strawberry
12:53:50.526 INFO  main:171                         Strawberry 0.7.2
12:53:50.527 INFO  main:172                         "KDE neon User Edition 5.19 20.04 - (linux 5.4.0-48-generic) [x86_64]"
12:53:50.643 DEBUG Application:242                  Database(0x55fcee60e1e0) moved to thread QThread(0x55fcee613d30)
12:53:50.643 DEBUG SCollection:62                   CollectionBackend(0x55fcee60cf10) moved to thread QThread(0x55fcee613d30)
12:53:50.696 DEBUG Application:242                  AlbumCoverLoader(0x55fcee65fa80) moved to thread QThread(0x55fcee671140)
12:53:50.699 DEBUG SCollection:94                   CollectionWatcher(0x55fcee68bbd0) moved to thread QThread(0x55fcee32d690)
12:53:50.699 DEBUG Application:242                  TagReaderClient(0x55fcee68d080) moved to thread QThread(0x55fcee673030)
12:53:50.699 DEBUG NetworkProxyFactory:55           Detected system proxy URLs: ("", "", "", "")
12:53:50.699 DEBUG WorkerPool<HandlerType>:282      Starting worker 0x7f96551c2f10 "/usr/bin/strawberry-tagreader" "/tmp/strawberry_1958335632"
12:53:50.704 DEBUG WorkerPool<HandlerType>:282      Starting worker 0x7f96551c2f10 "/usr/bin/strawberry-tagreader" "/tmp/strawberry_445452342"
12:53:50.707 DEBUG WorkerPool<HandlerType>:282      Starting worker 0x7f96551c2f10 "/usr/bin/strawberry-tagreader" "/tmp/strawberry_363193620"
12:53:50.715 INFO  main:56                          TagReader worker connecting to "/tmp/strawberry_1958335632"
12:53:50.716 DEBUG WorkerPool<HandlerType>:300      Worker 0x7f9624006590 connected to "/tmp/strawberry_1958335632"
12:53:50.716 INFO  main:56                          TagReader worker connecting to "/tmp/strawberry_445452342"
12:53:50.716 DEBUG WorkerPool<HandlerType>:300      Worker 0x7f9624007ac0 connected to "/tmp/strawberry_445452342"
12:53:50.720 INFO  main:56                          TagReader worker connecting to "/tmp/strawberry_363193620"
12:53:50.720 DEBUG WorkerPool<HandlerType>:300      Worker 0x7f9624006160 connected to "/tmp/strawberry_363193620"
12:53:50.731 DEBUG GlobalShortcutBackendGSD:53      Registering
12:53:50.735 WARN  GlobalShortcutBackendGSD:65      Gnome settings daemon not registered
12:53:50.776 WARN  unknown                          Icon theme "Numix-Circle" not found. 
12:53:51.063 INFO  Player:799                       Registered URL handler for "subsonic"
12:53:51.068 DEBUG InternetServices:49              Added internet service "Subsonic"
12:53:51.069 INFO  Player:799                       Registered URL handler for "tidal"
12:53:51.079 DEBUG InternetServices:49              Added internet service "Tidal"
12:53:51.194 DEBUG MainWindow:292                   Starting
12:53:51.254 DEBUG CoverProviders:105               Registered cover provider "Last.fm"
12:53:51.254 DEBUG CoverProviders:105               Registered cover provider "MusicBrainz"
12:53:51.254 DEBUG CoverProviders:105               Registered cover provider "Discogs"
12:53:51.254 DEBUG CoverProviders:105               Registered cover provider "Deezer"
12:53:51.254 DEBUG CoverProviders:105               Registered cover provider "Qobuz"
12:53:51.254 DEBUG CoverProviders:105               Registered cover provider "Musixmatch"
12:53:51.254 DEBUG CoverProviders:105               Registered cover provider "Spotify"
12:53:51.255 DEBUG CoverProviders:105               Registered cover provider "Tidal"
12:53:51.263 DEBUG LyricsProviders:103              Registered lyrics provider "AudD"
12:53:51.264 DEBUG LyricsProviders:103              Registered lyrics provider "Genius"
12:53:51.264 DEBUG LyricsProviders:103              Registered lyrics provider "Lyrics.ovh"
12:53:51.264 DEBUG LyricsProviders:103              Registered lyrics provider "LoloLyrics"
12:53:51.264 DEBUG LyricsProviders:103              Registered lyrics provider "Musixmatch"
12:53:51.264 DEBUG LyricsProviders:103              Registered lyrics provider "ChartLyrics"
12:53:51.396 DEBUG MainWindow:336                   Initialising player
12:53:51.403 DEBUG MainWindow:346                   Creating models
12:53:51.404 DEBUG MainWindow:353                   Creating models finished
12:53:51.424 DEBUG DeviceLister:66                  CddaLister(0x55fceea9bed0) moved to thread QThread(0x55fcef4c90d0)
12:53:51.424 DEBUG DeviceLister:66                  Udisks2Lister(0x55fcef520140) moved to thread QThread(0x55fcef4cbbd0)
12:53:51.424 DEBUG DeviceLister:66                  GioLister(0x55fcef43b0d0) moved to thread QThread(0x55fcef4c9280)
12:53:51.432 DEBUG Application:242                  PlaylistBackend(0x55fcef5413e0) moved to thread QThread(0x55fcee613d30)
12:53:51.438 DEBUG MainWindow:371                   Creating UI
12:53:51.442 DEBUG logging:83(GLib-GIO)             _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
12:53:51.464 DEBUG ScrobblerServices:49             Registered scrobbler service "Last.fm"
12:53:51.464 DEBUG ScrobblerServices:49             Registered scrobbler service "Libre.fm"
12:53:51.465 DEBUG ScrobblerServices:49             Registered scrobbler service "ListenBrainz"
12:53:51.514 DEBUG MainWindow:779                   Creating playing widget
12:53:51.819 DEBUG MainWindow:822                   Loading settings
12:53:51.971 DEBUG MainWindow:938                   Started QThread(0x55fcee2f4300)
12:53:52.004 INFO  DeviceManager:442                Device added: "/dev/sr0" ("/dev/sr0")
12:53:59.234 DEBUG GlobalShortcutBackendSystem:67   Unregistering
12:53:59.259 DEBUG LyricsProviders:124              Unregistered lyrics provider "Lyrics.ovh"
12:53:59.259 DEBUG LyricsProviders:124              Unregistered lyrics provider "LoloLyrics"
12:53:59.259 DEBUG LyricsProviders:124              Unregistered lyrics provider "Genius"
12:53:59.259 DEBUG LyricsProviders:124              Unregistered lyrics provider "AudD"
12:53:59.259 DEBUG LyricsProviders:124              Unregistered lyrics provider "ChartLyrics"
12:53:59.259 DEBUG LyricsProviders:124              Unregistered lyrics provider "Musixmatch"
12:53:59.259 DEBUG CoverProviders:126               Unregistered cover provider "Qobuz"
12:53:59.259 DEBUG CoverProviders:126               Unregistered cover provider "Discogs"
12:53:59.259 DEBUG CoverProviders:126               Unregistered cover provider "MusicBrainz"
12:53:59.259 DEBUG CoverProviders:126               Unregistered cover provider "Last.fm"
12:53:59.259 DEBUG CoverProviders:126               Unregistered cover provider "Deezer"
12:53:59.260 DEBUG CoverProviders:126               Unregistered cover provider "Musixmatch"
12:53:59.260 DEBUG CoverProviders:126               Unregistered cover provider "Spotify"
12:53:59.260 DEBUG CoverProviders:126               Unregistered cover provider "Tidal"
12:53:59.282 ERROR Database:91                      Connection "1_thread_94544816194304" is still open!
12:53:59.282 ERROR Database:91                      Connection "1_thread_94544819469616" is still open!
12:53:59.282 DEBUG WorkerPool<HandlerType>:178      Closing worker socket
12:53:59.285 DEBUG WorkerPool<HandlerType>:178      Closing worker socket
12:53:59.287 DEBUG WorkerPool<HandlerType>:178      Closing worker socket

**Comment by jonaski** [comment]
The database connection still open thing can safely be ignored, it's most of the time just because strawberry exited too quickly.

**Comment by linlinxza** [comment]
I don't know. Something is screwy. It's still not keeping those changes after a 
restart of the application. But for now, I can live with it.

**Comment by linlinxza** [comment]
Anyways, thanks for the help and for this Clementine fork. I hope it stays 
around for quite a while. Maybe also see if it can be added to the official 
Ubuntu repos.
