### ISSUE TITLE
Library list starting-letter grouping behaves in a weird way

### ISSUE THREAD

**Issue by FelixRilling** [strawberrymusicplayer/strawberry#556]
**Describe the bug**
Starting-letter based artist listing is displayed in a weird way

**To Reproduce**
- Have a collection where artists with different starting letters exists
- 'group by' -> artist

**Expected behavior**
The artists are listed under their corresponding starting letter

**Screenshots:**
The artists are all listed under the last letter:
![image](https://user-images.githubusercontent.com/3207763/95649624-a7d98500-0ade-11eb-876c-af9596a02d4d.png)
Interestingly, artists with numbers or special characters seem to be listed correctly:
![image](https://user-images.githubusercontent.com/3207763/95649686-0a328580-0adf-11eb-887d-69c4e8e4efd2.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.8.1

**Additional context**
I *think* this used to work and only broke recently, haven't tested it yet though

**Comment by jonaski** [comment]
What locale setting do you have? LC_COLLATE in locale.conf

**Comment by FelixRilling** [comment]
`LC_COLLATE` was not set, only `LANG`.
`LANG` was `C` when I had the described behavior, but after changing it to `en_US.UTF-8` strawberry sorts correctly again!
Is this intended behaviour? if so, please close this issue and sorry for wasting your time!

**Comment by jonaski** [comment]
It's still a bug, I can reproduce it when I set LC_COLLATE to C.

**Comment by jonaski** [comment]
The problem is that when collate is set to C, upper case letters will always show first, and the sort text items are always lowercase while the divider keys are always upper case. I created this bug a while ago when I changed the sort text for the dividers to upper case.
