### ISSUE TITLE
(Windows) IDirectSoundBuffer Issue on v0.81

### ISSUE THREAD

**Issue by denis-roy** [strawberrymusicplayer/strawberry#557]
Good day M. Kvinge,

**Describe the bug**
An error message appears (see screenshot) when powering off my bluetooth headphones during music playback.

**To Reproduce**
Power off bluetooth headphones during playback.

**Expected behavior**
No error message.

**Screenshots:**
![20201011T131453](https://user-images.githubusercontent.com/3801326/95685135-e0469500-0baa-11eb-87a3-63cbe2da68a5.png)

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 0.81

**Additional context**
Not much to add other than the previous version v0.72 did not produce this error. Let me know if I can help with extra troubleshooting steps (like how to export some kind of log file, etc) and thanks again for the great software :)

**Comment by jonaski** [comment]
Something changed in GStreamer, because we upgraded from 1.16.2 to 1.18.0.

**Comment by jonaski** [comment]
Looks like a GStreamer bug to me.

**Comment by jonaski** [comment]
It's a GStreamer regression, works fine when I revert back to 1.16.2

**Comment by jonaski** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/issues/793#note_651230

**Comment by denis-roy** [comment]
Thank you for the fix M. Kvinge
