### ISSUE TITLE
Proxy settings does not work for streaming

### ISSUE THREAD

**Issue by gerroon** [strawberrymusicplayer/strawberry#558]
**Describe the bug**
The proxy setting does not seem to make Strawberry to be able to stream online radioes. After adding the proxy and clicking on an online radio gives this error "Could not resolve server name."  

I tried both http (privoxy, shadowsocks)  and socks proxies (ssh socks proxy) Please bear in mind that all these proxies work fine with all the other apps (like web browsers or sync clients) on the same desktop. I dount that it is my proxies that are the issue here.

**To Reproduce**
Add an available http/socks proxy to proxy settings in the network proxy setting.

**Expected behavior**
Adding a working network proxy  should let Strawberry to be able to connect remote online radios

**System Information:**
 - Operating system: Windows 10 x64
 - Strawberry Version:  Version 0.8.1-1-g6dba40c6

**Additional context**

My desktop  does not have direct internet connection so I use proxies to be able to connect certain apps to the internet. I have multiple working proxies that I use with the web browsers on this desktop. None of those proxies are able to let Sb to stream from online radios

**Comment by jonaski** [comment]
You are right. Although the proxy settings work for covers, lyrics and services, they are not passed on to GStreamer so won't be used for streaming, it sort of was on my TODO list, but has ended up not being prioritized.

**Comment by gerroon** [comment]
Thanks for the reply. I actually tested this with Clementine, and that one has the same issue. As a side note the same proxy stuff works in AIMP and Vlc.

**Comment by jonaski** [comment]
Yeah, I know, it's never been implemented properly. I'll fix soon.
