### ISSUE TITLE
Alphabet inserted in Library. But it's all together, not as headings for the sections.

### ISSUE THREAD

**Issue by mxa** [strawberrymusicplayer/strawberry#559]
For technical issues, questions and feature requests please use the forum on https://forum.strawberrymusicplayer.org/

**Describe the bug**
There are these alphabetic headers for the letters from A to Z. I can only guess they are meant to lead the appropriate sections, however the whole alphabet is concentrated on top.

**Screenshots:**
![image](https://user-images.githubusercontent.com/1220707/95783043-51806800-0cd1-11eb-8d3c-fddd1920a148.png)

**System Information:**
 - Operating system: Kubuntu 20.04
 - Strawberry Version:  0.8.1

**Comment by jonaski** [comment]
Possible the same as #556
What LC_COLLATE setting do you have?

**Comment by mxa** [comment]
`LC_COLLATE="en_US.UTF-8"`

**Comment by jonaski** [comment]
Can you try the newest development build and see if it fixes this for you? https://builds.strawberrymusicplayer.org/
I need to make a new release anyway because of the CUE bug, but it would be nice to know for certain this issue is fixed too.

**Comment by mxa** [comment]
Confirmed fixed in Version 0.8.1-13-g0fd61945

**Comment by jonaski** [comment]
Thanks!
