### ISSUE TITLE
Can not add folders on mounted drives to collection

### ISSUE THREAD

**Issue by Matth3wW** [strawberrymusicplayer/strawberry#560]
**Describe the bug**
Can not add folders on mounted drives to collection

**To Reproduce**
1. Open settings
2. Click "Collection"
3. Click "Add new folder..."
4. Attempt to navigate to where the mounted drive is (/data in my case)

**Expected behavior**
When I go to add a folder to the collection, I should be able to select my music folder that is on a mounted drive.

**Screenshots:**
![image](https://user-images.githubusercontent.com/71298445/95923528-4aae2f80-0d7b-11eb-87c7-d91b75da7ce6.png)

**System Information:**
 - Operating system: Ubuntu 20.04, running KDE Plasma 5.18.5
 - Strawberry Version: 0.8.1

**Additional context**
I have Ubuntu installed on an SSD and all my media stored on a 4TB drive that I have mounted to /data.

**Comment by jonaski** [comment]
I mounted one of my HDD's to a mountpoint under / now and it works fine here. (not sure why you mount it directly to / and not to /mnt, but I don't see why it shouldn't work).
Are you using selinux or apparmor?
How is the mountpoint set up? Entry from /etc/fstab
Can you start strawberrry from a terminal and see if there are any errors shown?

**Comment by jonaski** [comment]
I just noticed the "writable" and "snap" folders in your root directory in the screenshot. In case you are running strawberry as a snap, then what you are seeing under root (/) is not your actual filesystem, you then need to mount your drive to /mnt so they can be seen by the snap system.

**Comment by Matth3wW** [comment]
Thank you, this was user error. Once I change my fstab to have data in mnt, I can now add my library.
I apologize for opening the ticket, i'm a linux newb.
