### ISSUE TITLE
Add shortcuts for ratings

### ISSUE THREAD

**Issue by rootwork** [strawberrymusicplayer/strawberry#561]
This is a feature request, not a bug.

Now that we have ratings (hooray!), it'd be great to have configurable keyboard shortcuts for them too.

**System Information:**
 - Operating system: Linux Mint 20.04
 - Strawberry Version: 0.8.2

**Comment by jonaski** [comment]
You need to use the forum for features: https://forum.strawberrymusicplayer.org/
It's explained in the README.
Thanks for sponsoring.
