### ISSUE TITLE
groovy gorilla gstreamer dependency mismatch?

### ISSUE THREAD

**Issue by slyrus** [strawberrymusicplayer/strawberry#563]
When I try to run cmake under ubuntu 20.04, I get the following:

```
The following components WILL NOT be built:
   Engine: GStreamer backend (missing gstreamer-1.0, gstreamer-base-1.0, gstreamer-app-1.0, gstreamer-audio-1.0, gstreamer-tag-1.0, gstreamer-pbutils-1.0)
   Moodbar (missing gstreamer)
   Sparkle integration (missing macOS, Sparkle)
   Translations (missing Qt5LinguistTools)
```
These specific packages don't seem to be available for linux 20.10 but a bunch of gstreamer packages are, including libgstreamer1.0-0.

Any ideas what packages need to be installed or if the dependency check needs to change?

**Comment by jonaski** [comment]
Did you install all the dependencies listed on https://github.com/strawberrymusicplayer/strawberry/wiki/Compiling-on-Ubuntu ?
Looks like you are missing libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev

**Comment by slyrus** [comment]
Indeed. Thanks for the pointer and apologies for the noise!
