### ISSUE TITLE
compile error when build without gstreamer

### ISSUE THREAD

**Issue by oldk1331** [strawberrymusicplayer/strawberry#568]
**Describe the bug**

When build without gstreamer support, compile fails at `src/widgets/fileview.cpp`.

I believe it's caused by https://github.com/strawberrymusicplayer/strawberry/commit/653a35496d5196d6ecfcefe1ca8569f1b770b95f.

The following part is relevant.  Not sure if this diff is enough to fix this.

````
--- a/src/widgets/fileview.cpp  2020-09-12 05:34:59.592107859 +0800
+++ b/src/widgets/fileview.cpp  2020-10-26 17:19:56.710168141 +0800
@@ -45,5 +45,3 @@
 #include "ui_fileview.h"
-#ifdef HAVE_GSTREAMER
-#  include "organize/organizeerrordialog.h"
-#endif
+#include "organize/organizeerrordialog.h"
 #include "settings/appearancesettingspage.h"
````

**Comment by jonaski** [comment]
The organize/delete stuff had ifdef HAVE_GSTREAMER by mistake, so I removed those ifdef's but looks like I forgot to remove the ifdef on the include itself.
