### ISSUE TITLE
Make context view top label selectable

### ISSUE THREAD

**Issue by yavuzmert** [strawberrymusicplayer/strawberry#570]
**Describe the bug**
Not a bug actually, I'd prefer the top label of context view to be selectable.
I occasionally want to copy song title and artist info to search externally (google), without entering "Edit track information" widget.
I suppose it wont harm anything to make so :)
Thanks.
src/context/contextview.cpp:154
label_top_->->setTextInteractionFlags(Qt::TextSelectableByMouse);

**Expected behavior**
Top label of context view to be selectable

**Comment by jonaski** [comment]
Can you make a PR to change this?
