### ISSUE TITLE
Tags are being automatically created when editing track information

### ISSUE THREAD

**Issue by yekteniya** [strawberrymusicplayer/strawberry#571]
**Describe the bug**
Whenever editing tags of a song through Edit track information, new tags are being automatically added to the song in fields that weren't modified.

Tags being added automatically in a song with ID3v2.4.0 tags:
- Compilation
- Composer
- Disc Number
- Original Artist
- Work

- ID3v1.1 tags are also being automatically generated out of the original ID3v2.4.0 tags

I only noticed this cause I was updating the lyrics to some songs and suddenly the Album Artist tag got messed up in several songs, so I'm certain something weird is going on when editing tags.

**To Reproduce**
Right click on any track (mp3 in my case), Edit track information -> Modify any tag and save.

**Expected behavior**
I wasn't experiencing this behaviour in older versions (can't tell when this started happening, but probably it's safe to say this didn't happen in 0.8.0 or previous.) As I see it, only tags that have been modified by the user should be added to the song and no tags should get automatically generated and inserted into the file unless it is a deliberate choice from the user. I see this as an issue since any small changes to a particular file will make that file's tags different in comparison to the rest of my music's collection.

**Screenshots:**
To illustrate this, I have a pre and post picture of a song's tag as shown in Kid3. 
Below is the song's tags before any action is taken through Straberry's Edit track information
![Screenshot_20201028_211242](https://user-images.githubusercontent.com/52610846/97492025-467d3700-1963-11eb-8f03-59b13d35b1a0.png)
After just adding a new line to the lyrics through Edit track information and saving, all the following tags are added automatically:
![Screenshot_20201028_211350](https://user-images.githubusercontent.com/52610846/97492070-54cb5300-1963-11eb-9e51-0f715e1069c1.png)

**System Information:**
 - Operating system: Debian - Bullseye
 - Strawberry Version: 0.8.3

**Comment by jonaski** [comment]
We have always done this.

**Comment by yekteniya** [comment]
Can't believe I just noticed now after this after all this time. Closing this then.

**Comment by jonaski** [comment]
I changed the behavior now to only save as ID3v2 tags, and only include tags that are not empty.

**Comment by yekteniya** [comment]
Appreciate it!

**Comment by Fritigern** [comment]
Please, give us the OPTION to save ID3v1, ID3v2.3/2.4 or both. 
I keep the ID3v1 tags in my files for some older software and the fact that Strawberry now DELETES my ID3v1 tags without asking when I alter a tag causes me extra work as I now have to re-add the ID3v1 tags that I actually use.
