### ISSUE TITLE
Add support for more global shortcuts on KDE using KGlobalAccel

### ISSUE THREAD

**Issue by Cqoicebordel** [strawberrymusicplayer/strawberry#572]
I'm on Kubuntu 20.04, with Strawberry 0.8.3 (through the PPA).

As I'm using KDE, the shortcuts interface recommends me to use dbus/mpris to create global shortcuts. The problem is that all functions are not available through dbus.  
In particular, for my use, there is two issues :   
* There is no "RaiseHide" function. There is only "Raise", but no way to have it back to the status bar icon. Having "Hide" would be helpful, but having "RaiseHide" would be perfect (⇒ raise if hidden, hide if raised). Of course, having the accompanying properties (isHidden, isRaised, canHide, and those I'm forgetting) would be a plus.
* There is no "ShowOSD" either.

There are others that could be added too but I think those above are the ones that are the most needed (at least, by me ;) ). Having a one to one equivalent with the shortcuts section of settings would be ideal, of course.

**Comment by jonaski** [comment]
We already implement CanRaise/Raise which is what is available according to MPRIS2 specifications on https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html
Test with; `qdbus org.mpris.MediaPlayer2.strawberry /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Raise`

But I think we can implement other shortcuts using KGlobalAccel. I can look into it.
https://api.kde.org/frameworks/kglobalaccel/html/index.html

**Comment by Cqoicebordel** [comment]
Yeah, as I said previously, I knew about "Raise", it was the others ("Hide", "RaiseHide") which were missing.  
I proposed MPRIS because of consistency : in the shortcuts settings of Strawberry, it directed the user to use MPRIS, so instead of directing the users to two different destinations, I thought one was better.

But if you propose to do it through KGlobalAccel, it's even better ! Having all the shortcuts there would help tremendously, including avoiding the users to fiddle with the command line for handling the D-BUS events :)  
Just make sure the text in shortcuts direct the users there, instead of MPRIS :)

**Comment by jonaski** [comment]
What is Hide and RaiseHide? It is not listed in the specifications on https://specifications.freedesktop.org/mpris-spec/2.2/Media_Player.html

**Comment by Cqoicebordel** [comment]
It's the features already present in Strawberry shortcuts. "Hide" hides the UI to the systray, "RaiseHide" hides if visible, raises if hidden.  
As I said, yes, they are not available through the mpris specification, but were needed. You added them to KGlobalAccess, so it's good.
