### ISSUE TITLE
Cannot add folder to a collection on Kubuntu 20.04.1 LTS - missing kioslave binary

### ISSUE THREAD

**Issue by dmatej** [strawberrymusicplayer/strawberry#575]
"cannot create io-slave: cannot find program kioslave in directories ..."

**Describe the bug**
Tools => Settings => Add New Folder => immediately shows two error windows as shown in the printscreen.

![image](https://user-images.githubusercontent.com/302904/97904644-1823a100-1d41-11eb-8640-186cc93e8f83.png)

**System Information:**
 - Operating system: Kubuntu 20.04.1 LTS
 - Strawberry Version: 0.8.3-27-g4cab7436

Strawberry was installed by the snap command.

**Comment by jonaski** [comment]
Something is broken with the snap system.
Use the PPA instead.

`snap remove strawberry`

```
sudo add-apt-repository ppa:jonaski/strawberry
sudo apt-get update
sudo apt install strawberry
```

**Comment by dmatej** [comment]
Thanks, that really helped! Finally it works :-)
