### ISSUE TITLE
Song progress on tray icon

### ISSUE THREAD

**Issue by yavuzmert** [strawberrymusicplayer/strawberry#577]
The only feature left that I personally miss from clementine is track progress on system tray icon. I see that most of the code is already there but commented out and grey icons were missing. I created grey icons from original strawberry icons.
I changed the direction to top-right to bottom left to better match the strawberry icon. (Going through the bottom of the strawberry). The result is acceptable I guess.
If you don't like the feature and intentionally commented it out, maybe we can make it optional.
If you approve the changes I will make a PR for this.
Thanks.
PS: I changed the mac source also but I cannot test that.
**Screenshots:**
![1](https://user-images.githubusercontent.com/19837772/97929591-92bce280-1d7a-11eb-95cf-cc4950ac55aa.png)
![2](https://user-images.githubusercontent.com/19837772/97929595-95b7d300-1d7a-11eb-869f-4756b5b56bac.png)
![3](https://user-images.githubusercontent.com/19837772/97929602-97819680-1d7a-11eb-9646-887aa1ff42b6.png)

**Comment by jonaski** [comment]
An option in the behavior settings is fine, it's correct that I just commented it out because I didn't think it looked good with the strawberry icon, and never bothered to deal with it.

**Comment by jonaski** [comment]
I can test it on mac if you make a PR.

**Comment by jonaski** [comment]
Thanks!
