### ISSUE TITLE
MQA Support

### ISSUE THREAD

**Issue by shaun-ba** [strawberrymusicplayer/strawberry#585]
Firstly I love the fork, was really needed!

So, I have downloaded a lot of my library from Tidal in Masters format, so they are all MQA encoded.

I would like to play these, and my understanding is the first "unfold" is done on the software level, does Strawberry support this?

**Comment by jonaski** [comment]
Thanks.
Sorry, MQA is a proprietary format and I don't think there is an open source decoder for it, we need a gstreamer plugin to play them. This has been asked before if you search the issues.
It is however possible to stream from Tidal in HD, if you use OAuth with an client ID, and set the audio quality to "Hi resolution" you can stream 48kHz/24bit in FLAC. You have to dig for a client id yourself.

**Comment by shaun-ba** [comment]
I'm playing the MQA in 24bit at the moment on Strawberry, they are WAY better than streaming through browser.

I guess a hardware DAC with MQA support would then work with Strawberry?

**Comment by shaun-ba** [comment]
@jonaski Until I do some more research and maybe buy some new hardware, I currently have a SMSL DAC, Strawberry is using "wrapper for audio sink", is this my best option currently ?

**Comment by jonaski** [comment]
As far as I know gstreamer does not understand MQA, so a native MQA DAC won't help as GStreamer will send it to the DAC as FLAC even if there is MQA data there. But I think what Strawberry get's from Tidal is just FLAC even with the Hi resolution option. Both the Tidal API and MQA is undocumented, so it's the best we can do.

Wrapper for audio sink will automatically pick an output, so if you got pulseaudio running, or jack, or alsa. If you got PulseAudio running it will pick that first. Specifically selecting an output will make sure it goes to that output. I never use jack or pulseaudio, it's not even installed on my computers, so I it goes to ALSA anyway.
But I always select ALSA and my device so I can play directly to the DAC without resampling everything to 48Khz. It will lock the device so nothing else can play while music plays too.

**Comment by shaun-ba** [comment]
@jonaski you've lost me a little there with the GStreamer transfer part.

When you download from Tidal (fully authenticated etc), you get MQA encoded files. I am playing these on Strawberry, here is an example: https://we.tl/t-v2SEjiCwFI

Why would sending the DAC a .flac matter? This seems to be the container for MQA files.

**Comment by jonaski** [comment]
I wrote that incorrectly, a FLAC is decoded before it is sent to the DAC of course. But as far as I know these MQA files contain a normal FLAC bit with some additional MQA part, but since gstreamer does not read/decode the MQA part all you have is a degraded FLAC. I have only tested a few albums from Tidal that are 48/24, but I suspect they are normal FLAC's without MQA.

**Comment by shaun-ba** [comment]
Would you be able to test with my attached MQA?

**Comment by jonaski** [comment]
When opening the file in a HEX editor I can see: "ENCODER=MQAEncode v1.1, 2.5.0+123"
It's identified as a normal FLAC 44.1khz / 24 bit, but I assume there is MQA encoded data there too and that it would play at a higher sample rate if that data decoded too. Like said earlier I don't think GStreamer is able to decode the MQA parts of the file, only MQA licensed software has the ability to decode that as far as I know.

**Comment by BlueManCZ** [comment]
Hello, sorry for bumping this. I'm trying to stream 48kHz/24bit FLAC from Tidal (as you mentioned above), but even when I have selected the "Hi resolution" option in settings, it seems to be streaming everything in 44,1kHz/16bit. Has something changed in those 2 years?
