### ISSUE TITLE
Feature? - Button to switch audio output device

### ISSUE THREAD

**Issue by shaun-ba** [strawberrymusicplayer/strawberry#586]
So I've change the setting to use ALSA, direct to my DAC.

However, YouTube in browser now doesn't play. I understand the device must be locked down or something, but can't Strawberry handle this in another way, nothing is playing so unlock it? Or just give the user a button in the UI to do it quickly?

**Comment by jonaski** [comment]
Use the forum for question: https://forum.strawberrymusicplayer.org/
You won't be able to play sound from different applications at the same time unless you configure alsa to use dmix so it will resample to 48khz, the alternative is to use PulseAudio or Jack.
