### ISSUE TITLE
Strawberry is not translated to system default language on Gnome

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#589]
**Describe the bug**
I use Strawberry 0.8.3 on Arch Linux running Gnome 3.38.1.
"Use the system default" is selected under "Language" in "Behavior" section of Strawberry settings, system default language
is brazilian portuguese on my system but Strawberry language is english.

Steps to reproduce the behavior.
use a distro with Gnome
set pt-br language as default in Gnome settings
open Strawberry

**Expected behavior**
Strawberry should respect system default language on Gnome desktop environment.

**System Information:**
 - Operating system: Arch Linux running Gnome 3.38.1
 - Strawberry Version: 0.8.3

**Additional context**
Other Qt apps like VLC player and qBittorrent installed on my system respect the default language (pt-br) as expected.

**Comment by jonaski** [comment]
We don't have brazilian
