### ISSUE TITLE
"Reset" button overlaps long tag in "Edit track information" window

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#594]
**Describe the bug**
"Reset" button overlaps long tag in "Edit track information" window

**To Reproduce**
1. in "Collection" tab, right click on any album with a long name
2. choose ""Edit track information..."

**Expected behavior**
"Reset" icon should not overlap anything

**Screenshots:**
![strawberry](https://user-images.githubusercontent.com/15967631/99803322-ffc0ce00-2b17-11eb-93df-b4f2e2ee053a.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.8.4

**Comment by jonaski** [comment]
The icon is transparent because it's borderless, but the alternative looks ugly. You can simply expand the window.

**Comment by glaubersm** [comment]
Expanded window loses its size when Strawberry is closed.
Could the window size to be permanently remembered?

**Comment by jonaski** [comment]
Yeah, I can fix that
