### ISSUE TITLE
No network control?

### ISSUE THREAD

**Issue by shaun-ba** [strawberrymusicplayer/strawberry#597]
Love Strawberry. The only player I can find on linux to output MQA untouched so it actually unfolds on hardware. Great Job.!!!

But.... this is a fork, why did you feel the need to remove network control? :)

**Comment by jonaski** [comment]
Use this forum for questions: https://forum.strawberrymusicplayer.org/

**Comment by shaun-ba** [comment]
Sure will do, but github is still nicer control for feature requests as you
can easily link to commits etc.

I have found my request in the feature forum so all good!
