### ISSUE TITLE
Equaliser does not work

### ISSUE THREAD

**Issue by Slater91** [strawberrymusicplayer/strawberry#601]
**Describe the bug**
Equaliser does not work, as enabling or disabling it makes absolutely no difference. Even doing extreme stuff (e.g. every bar down to -12) has no effect on sound.

**To Reproduce**
Enable equaliser and fiddle with it.

**Expected behavior**
The changes applied to the equaliser are reflected in the music being played. 

**System Information:**
 - Operating system: KDE neon (based on Ubuntu Focal)
 - Strawberry Version: 0.8.4

**Comment by jonaski** [comment]
It works fine here. Did you try to enable it while playing music by any chance? That won't work, you need to enable it before you start playback.

**Comment by Slater91** [comment]
Oh, that explains it. Yes, I was actually enabling it while playing music - I recently got back to using Strawberry after a period of using DeaDBeeF and enabling the equaliser while playing music works there. It's also a nice feature to see how much difference the equalisation makes. Is there any chance that this feature will be implemented in the future?
As far as I've seen with a quick test, it doesn't work even when you pause playback and then start it again, which is quite inconvenient. It might be a very specific use case, but I review headphones and being able to adjust EQ on-the-fly is really a pro. 
Thanks.

**Comment by jonaski** [comment]
You can still adjust the equalizer while playing, it just that the "Enable equalizer" needs to be enabled first. I don't want to link the equalizer element to the pipeline unless we use it, I've explained this before too. You can set it to Zero when you want it in neutral and leave the enable checkbox on.
