### ISSUE TITLE
[KDE][Shortcuts] Follow up issues

### ISSUE THREAD

**Issue by Cqoicebordel** [strawberrymusicplayer/strawberry#602]
Following up on #572, I confirm it's fixed but there are a couple remaining issues :  
* When a global shortcut is already used, Strawberry doesn't ask to replace it, it just doesn't save it  
* My media key doesn't seem to work. It might be already in use, but I don't think so, and Strawberry saves it, so it's not the issue above. BUT, it might be something more simple. When detecting it in the setting, its name appears as "Média lecture". So could either be an accent issue, or a space issue too.

Anyway, obviously, those bugs are very low priority. They even aren't an issue for me, as I found workarounds for them (for the first, remove all previous already set shortcuts, for the second, use dbus for that key, to tie it to play/pause). I just thought you should know :)

And BTW, thanks for the work you are doing !!!

**Comment by jonaski** [comment]
Media keys can't be registered through KGlobalAccel, it's a limitation in KGlobalAccel.
It's true that the key will replace the previous one, but it's easy to reset it back using the "default" radiobox. I'd rather not have an additional popup just for that.

**Comment by Cqoicebordel** [comment]
Ok for the limitation of the media keys. It's kinda weird though, because the media keys behave like keys (they appear in `xev`, for example), but OK.

For the other, you misunderstood me : if I have a global shortcut set on the OS level, and then try to affect the same one in Strawberry, it looks like Strawberry accepts it (it shows in the list, you can apply and close), but in reality, the shortcut is not set. If you reopen Strawberry's settings, the shortcut will have disappeared (went back to default, I think). Asking to preempt the previous affectation is the usage in KDE, I think. But in any case, it shouldn't look like Strawberry accepts the shortcut.

**Comment by jonaski** [comment]
Strawberry receive the supported media keys through MPRIS2, the ones that are part of the MPRIS2 specifications can't be configured KGlobalAccel.
I can't reproduce any problems with saving keys. However it's true that it is possible to configure keys that can fail to register.
