### ISSUE TITLE
[Feature Request] Show 'BPM' and 'ReplayGain' infos

### ISSUE THREAD

**Issue by Cqoicebordel** [strawberrymusicplayer/strawberry#603]
I'm using v0.8.4 from the PPA.

Showing BPM and ReplayGain infos would be nice to have in several places :  
* Playlist column
* Track info window
* Track context panel

Moreover, having them available in the smart playlists as a search 'term' would be really useful, at least for the BPM.

**Comment by jonaski** [comment]
We don't use GitHub for feature requests, it's written in the issue template and the README file.

**Comment by Cqoicebordel** [comment]
Sorry
