### ISSUE TITLE
[Smart playlist] Show which smart playlist is activated

### ISSUE THREAD

**Issue by Cqoicebordel** [strawberrymusicplayer/strawberry#604]
I'm using v0.8.4 from the PPA

It might be me, but I haven't found where I can check which smart playlist is currently playing.

Bolding the name of the current playlist used in the panel might be good. Having its name in the toaster at the bottom the playlist (with "Dynamic mode is activated [Grow] [Refresh] [Turn off]" (sorry for the approximation, I use the French translation, so I don't know the original strings)) would be good too.

Others solutions are also possible, of course. I let you decide what's best :)

**Comment by jonaski** [comment]
Smart playlists are just normal playlists that are generated from the smart playlist templates, it can be modified later and have no direct link to the smart playlists. Dynamic playlists are different but they already show a popup.

**Comment by Cqoicebordel** [comment]
So there is no way to know what Smart Playlist I'm currently listening to ?

**Comment by jonaski** [comment]
Just change the name of the playlist to what you want to call it (double click on the playlist tab).

**Comment by Cqoicebordel** [comment]
What ?

That's not the issue at all. If I double click on a smart playlist in the panel, what indicator is there to know what smart playlist I have activated (several days later, when I have forgotten) ?

**Comment by jonaski** [comment]
The smart playlists does not work the way you think they work so what you are asking for isn't possible.
