### ISSUE TITLE
Sound does not output to proper playback device when it's switched on Windows

### ISSUE THREAD

**Issue by sbstp** [strawberrymusicplayer/strawberry#609]
**Describe the bug**
Sound does not go to the right output device when the default playback device is switched in Windows. For instance, I have speakers and headphones. When I change the default playback device in Windows, Strawberry keeps outputting on the previous device. The only way to make it output to the right device is by restarting Strawberry. I tried playing with the backend settings, but nothing seems to work.

**To Reproduce**
Start to play a song, switch the playback device, song keeps playing on original playback device.

**Expected behavior**
The song should output on the newly selected playback device.

**Screenshots:**
![image](https://user-images.githubusercontent.com/862368/100953821-50a1d080-34e1-11eb-90cf-1245f3bd49e6.png)

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 0.8.4

**Comment by jonaski** [comment]
wasapisink does not support automatic switching. You need to use directsoundsink.
