### ISSUE TITLE
playing from different playlist than the one double-clicked

### ISSUE THREAD

**Issue by martinpescador** [strawberrymusicplayer/strawberry#610]
**Describe the bug**

Double-clicking a track in a playlist other than the currently active one, when the "Behavior" option "Double clicking a song in the playlist will..." is set to: "Add the the queue" starts a track in the active playlist.

**To Reproduce**

Set the "Behavior" option "Double clicking a song in the playlist will..." to: "Add the the queue" 

Open multiple playlists and play a song in one of them.

Then, you can get to the bug in two ways, either:

1: 
a: Start a track in a playlist.
b: Stop the player.
c: Double click a track in another playlist

and then: the track in the previously active playlist in the same position as the one you just double-clicked will start playing.

2:
a: Start a track in a playlist.
b: Double click on a track in a different playlist than the one that is playing
c: That track will be queued, but the track with the same position in the active playlist will start playing instead.

**Expected behavior**

In 1: You would expect the track that you double click to be played.
in 2: You would *not* expect the track in the playlist that you did *not* click on would start.

**System Information:**
 - Operating system: Mint 20
 - Strawberry Version: 0.8.4

**Additional context**

The same thing happens on different machine (also Mint 20).

**Comment by jonaski** [comment]
Thanks for reporting that. I can't figure out how that bug happened, it must have been there for a long time, but at least easy to fix.

**Comment by martinpescador** [comment]
Welcome.

Checked latest build. Works/solved. Well done!

There is however an open question about bug/feature in that context:

With the "Behavior" option "Double clicking a song in the playlist will..." set to: "Add the the queue", if you double-click a track in another playlist than the actively playing playlist, then the track will be queued.

That is intended behaviour, I assume. But the queued track will never play. The active playlist will continue to play.

This, of course, is the same whether or not the "Behavior" option "Double clicking a song in the playlist will..." is set to: "Add the the queue".

But is it the preferred result?
