### ISSUE TITLE
Amarok is BACK ?

### ISSUE THREAD

**Issue by sylvainsab** [strawberrymusicplayer/strawberry#614]
I can decently use the 2.9 version (2.9.70, Build Date: Jun 25 2019, Using KDE Frameworks 5.76.0) on my Manjaro distro release, which seems quite functional and up-to-date.

see https://amarok.kde.org/

**Comment by jonaski** [comment]
What does this have to do with Strawberry?

**Comment by sylvainsab** [comment]
Wasn't Strawberry intended as a fork for when Amarok (or the already forked Clementine) was no longer maintained ? I suppose much could be gained by sharing some effort back.

**Comment by jonaski** [comment]
Strawberry was forked from Clementine. It does not share any code with the current Amarok codebase. Clementine was mostly written from scratch, so to call it a fork of Amarok is a bit strange, it only used a few things from Amarok 1.x, some of the engine code, the analyzers, and few widgets such as the volume control. But all that code was from Amarok 1.x and is very different from the current Amarok codebase.
Amarok 2.9 was released in March 2018 but was still Qt 4 based. I didn't even know it was unmaintained. I know they have been working on porting it to Qt 5 and QML, and that releases are not being made very often. Development is very slow.
It would be very difficult to merge Strawberry into Amarok, and a huge job which I'm not willing to do, there would be to many compromises.
The Amarok code and the GUI is very different to Clementine and Strawberry.
Merging Strawberry back into Clementine would be technically possible, but even that would be a huge job, and it does not make much sense considering that the main author and most of the contributors are gone.
I'm fine with things like they are.
