### ISSUE TITLE
(Windows) Arranging songs

### ISSUE THREAD

**Issue by adamdb98** [strawberrymusicplayer/strawberry#616]
- On Windows, strawberry often crashes when trying to arrange songs in the tracklist after playing a song.

- Songs become stuck so that you cannot arrange them after you play a song.

**Comment by jonaski** [comment]
For the crash you need to attach the event from the application log as a minimum when you report an issue.

**Comment by jonaski** [comment]
I can reproduce the problem with dragging songs to rearrange them, occurs after you play a song like you said. I suspect it might be a Qt bug. It works one Linux.

**Comment by adamdb98** [comment]
> For the crash you need to attach the event from the application log as a minimum when you report an issue.

Hey Jonaski, sorry I missed that I'm pretty new to github. My family and I really like the software and use it all the time. Is there any way you could help me out finding the crash log on windows in case I find another bug? :)

**Comment by jonaski** [comment]
Control Panel / Administrative Tools / Event Viewer / Windows Logs / Application
There should be a event related to strawberry.exe showing the crash, paste it here within `code`

**Comment by adamdb98** [comment]
Got it. Thank you!

`Faulting application name: strawberry.exe, version: 0.8.4.0, time stamp: 0x00000000
Faulting module name: combase.dll, version: 10.0.19041.572, time stamp: 0x654b189d
Exception code: 0xc0000005
Fault offset: 0x0000000000030517
Faulting process id: 0x1ed8
Faulting application start time: 0x01d6ce8b1403c0d6
Faulting application path: C:\Program Files\Strawberry Music Player\strawberry.exe
Faulting module path: C:\WINDOWS\System32\combase.dll
Report Id: 91485e31-00d9-436b-9ecd-1d2e13200b65
Faulting package full name: 
Faulting package-relative application ID: `

`Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: strawberry.exe
P2: 0.8.4.0
P3: 00000000
P4: combase.dll
P5: 10.0.19041.572
P6: 654b189d
P7: c0000005
P8: 0000000000030517
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_strawberry.exe_59d9a6e34a698da58a794f738bf09c754f1d8157_3c84c382_95149cdb-d79c-45eb-a7ec-3d049eb168d7

Analysis symbol: 
Rechecking for solution: 0
Report Id: 91485e31-00d9-436b-9ecd-1d2e13200b65
Report Status: 4100
Hashed bucket: 
Cab Guid: 0`

`Fault bucket 1331893412949040001, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: strawberry.exe
P2: 0.8.4.0
P3: 00000000
P4: combase.dll
P5: 10.0.19041.572
P6: 654b189d
P7: c0000005
P8: 0000000000030517
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER99E3.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_strawberry.exe_59d9a6e34a698da58a794f738bf09c754f1d8157_3c84c382_95149cdb-d79c-45eb-a7ec-3d049eb168d7

Analysis symbol: 
Rechecking for solution: 0
Report Id: 91485e31-00d9-436b-9ecd-1d2e13200b65
Report Status: 268439552
Hashed bucket: 9084dbedbf212ce8827bd6009d829b81
Cab Guid: 0`

**Comment by adamdb98** [comment]
If there's anything else I can do let me know.

**Comment by jonaski** [comment]
Workaround: In Tools / Backend / Output - Change it to Output to a sound card via Direct Sound

**Comment by adamdb98** [comment]
> Workaround: In Tools / Settings / Backend / Output - Change it to Output to a sound card via Direct Sound

Beautiful, thank you very much!!

**Comment by jonaski** [comment]
This bug is most likely in the gstreamer wasapi plugin, I have reported it as a bug to gstreamer:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1482
I changed the priority of the outputs, so that directsounksink is used if it's set to automatic.
https://github.com/strawberrymusicplayer/strawberry/commit/e78bb1b29caece40f85b9c76b0b6d48379a66b86

**Comment by adamdb98** [comment]
> This bug is most likely in the gstreamer wasapi plugin, I have reported it as a bug to gstreamer:
> https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1482
> I changed the priority of the outputs, so that directsounksink is used if it's set to automatic.
> [e78bb1b](https://github.com/strawberrymusicplayer/strawberry/commit/e78bb1b29caece40f85b9c76b0b6d48379a66b86)

Excellent. Thank you again for making this app 
👌

**Comment by PrSunflower** [comment]
Hi, I am having the same issue, here is my Windows error log:

```
Faulting application name: strawberry.exe, version: 0.8.4.0, time stamp: 0x00000000
Faulting module name: combase.dll, version: 10.0.18362.1237, time stamp: 0xfd9cab5f
Exception code: 0xc0000005
Fault offset: 0x00000000000468b4
Faulting process ID: 0x10f4
Faulting application start time: 0x01d6d4c54f635432
Faulting application path: C:\Program Files\Strawberry Music Player\strawberry.exe
Faulting module path: C:\Windows\System32\combase.dll
Report ID: 9d685946-a140-426b-9139-f6a8f9992216
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1953778758868428386, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: strawberry.exe
P2: 0.8.4.0
P3: 00000000
P4: combase.dll
P5: 10.0.18362.1237
P6: fd9cab5f
P7: c0000005
P8: 00000000000468b4
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4808.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER64A9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER64E9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER64E7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6536.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_strawberry.exe_7bcb39fda15b8dce158f435292446d892e180_3c84c382_d9dc604a-8a28-44d3-bc8c-3d3634423383

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9d685946-a140-426b-9139-f6a8f9992216
Report Status: 268435456
Hashed bucket: 82fdbb47d89fdb58eb1d376dfc0e6662
Cab Guid: 0
```

**Comment by joelmandell** [comment]
@PrSunflower Did you try the workaround mentioned above?

**Comment by PrSunflower** [comment]
@joelmandell Yes I followed this workaround and I don't have the problem anymore:

> Workaround: In Tools / Settings / Backend / Output - Change it to Output to a sound card via Direct Sound

[My comment above](https://github.com/strawberrymusicplayer/strawberry/issues/616#issuecomment-747750080) was just to give some more details if needed 😄
