### ISSUE TITLE
Playlist export syntax wrong?

### ISSUE THREAD

**Issue by shaun-ba** [strawberrymusicplayer/strawberry#619]
Hi,

I'm trying to export a playlist so I can use it in Roon, however it isn't being recognised there.

I'm looking at some M3u files and this is the syntax:

```
#EXTM3U
#EXTINF:105, Example artist - Example title
C:\Files\My Music\Example.mp3
#EXTINF:321, Example Artist2 - Example title2
C:\Files\My Music\Favorites\Example2.ogg
```

In my exported M3U there are no #EXTINF lines above the path?

**Comment by jonaski** [comment]
In your example there are lines starting with `#EXTINF` which is the metadata, so not sure what the problem is here? There is an option in the playlist settings to turn this on or off.
What specifically is wrong with the syntax?

**Comment by shaun-ba** [comment]
@jonaski My example is from an online resource, the M3U from strawberry, I didn't know I could turn it on in settings! That's under metadata section right?

**Comment by jonaski** [comment]
Yes: "Write metadata when saving playlists"
