### ISSUE TITLE
Zanata could not be used to translate for strawberry

### ISSUE THREAD

**Issue by 210hcl** [strawberrymusicplayer/strawberry#622]
I tryed to join to translate strawberry to Simplified Chinese, but there is a red lock on the website. It makes that I cannot type any characters on the translation.
Is it set wrong? How can I join to translate strawberry?

**Comment by jonaski** [comment]
Same problem as reported in #443
You to file an issue to Zanata directly: https://zanata.atlassian.net/projects/ZNTA/issues/?filter=allopenissues
