### ISSUE TITLE
Last.fm last played date import is incorrect

### ISSUE THREAD

**Issue by esalgado** [strawberrymusicplayer/strawberry#624]
Hello! 

Sorry for my late reply... I have finally compiled using QT6, and the import last playcount made it to the end :+1: 

But I think that instead of this being the last played date, it is the first played date:
![Screenshot_20210102_122414](https://user-images.githubusercontent.com/977612/103456357-2fedb600-4ced-11eb-9d65-2be173145e78.png)

Can it be that the function is continously updating the play date for a particular song, in the order that the Last.fm API sends them? All those 51k plays, is all my play history since 2005, and maybe it is being sent by Last.Fm in reverse chronological order, or maybe random?

I don't know if I have to open a bug for this?

Thanks for the app, I love it :)

_Originally posted by @esalgado in https://github.com/strawberrymusicplayer/strawberry/issues/247#issuecomment-753462788_

**Comment by esalgado** [comment]
#625 This fixes it!

**Comment by jonaski** [comment]
The `user.getRecentTracks` API method returns all scrobble history instead of being unique for each song, there isn't a better API method to use, so maybe we should just remove the last played import, and just keep the play count, it's too much to retrieve the entire scrobble history.

**Comment by millette** [comment]
@jonaski Thanks for the tip, I'm an old-time last.fm user, new strawberry user and importing last player from last.fm doesn't work for me, too long a history I guess. Requesting only play counts seems to work, great!

I'd still like to import last played, even if it's not complete. Should I open another issue about my bug?
