### ISSUE TITLE
Only playing now is scrobbled

### ISSUE THREAD

**Issue by aldeano** [strawberrymusicplayer/strawberry#627]
As the title says, "work in offline mode" is unchecked as the image shows

![Screenshot_20210105_210057](https://user-images.githubusercontent.com/622453/103712942-cf36d580-4f99-11eb-8197-f4384c246012.png)

But only scrobbles "playing now" in last.fm and listenbrainz

Related debug info shows only this:
`21:03:41.875 DEBUG ScrobblerServices:49             Registered scrobbler service "Last.fm"`
`21:03:41.875 DEBUG ScrobblerServices:49             Registered scrobbler service "Libre.fm"`
`21:03:41.875 DEBUG ScrobblerServices:49             Registered scrobbler service "ListenBrainz"`
`21:03:41.875 DEBUG ScrobblerServices:49             Registered scrobbler service "Subsonic"`
`21:03:45.267 DEBUG AudioScrobbler:153               Sending now playing for song "artist" "album" "title"`

Using strawberry 0.8.5-1 in arch/plasma up to date.

**Comment by jonaski** [comment]
It works for everyone else, so something must be off with either the songs metadata or settings.
Is it local files, or streams? Does the songs show a valid artist, title, and length?

**Comment by jonaski** [comment]
Also, your screenshot does not show the settings for activating scrobbling for different sources, is the source checked for the type of song you are playing?

**Comment by aldeano** [comment]
I don't know why, but all tags have disappeared. Deleting and re-adding them solve the issue, now the songs are scrobbled. Marking as closed.
