### ISSUE TITLE
Separate artists even if they have the same name

### ISSUE THREAD

**Issue by KingDuckZ** [strawberrymusicplayer/strawberry#628]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
This is more of a feature request than a bug. I have two artists in my collection, "Emma Marrone" and "Emma Bunton", and the album artist is set to just "Emma" for both (tags from MusicBrainz). Of course they get grouped together in Strawberry, and it's mildly annoying.

**To Reproduce**
* Setup an airsonic server
* Add two albums with the artist and album artist fields all set to the same string
* In Strawberry, add the airsonic server and group the songs by album artist in the browser

**Expected behavior**
Well, right now I expect both albums to be grouped in the same artist group in the song browser, no surprise there.
What I'm asking for is if there's any extra tag set by MusicBrainz (artist id for example) that could be used to tell that the album artist is not the same even if the string name is identical. If so, I'd be ok with two "Emma" folders appearing in the list. I can just expand them to find the one I actually want to listen to, but at least albums are not mixed up.
In theory, if there's an internet connection (there must be for the airsonic use case) and a MusicBrainz ID, it should be possible to query their DB for the disambiguation text so that Strawberry could display something like "Emma (British singer)" and "Emma (Italian singer)" whenever there is an ambiguity. The string in parentheses would be fetched from MB and not from the song's metadata, and of course it'll only be there if there is one set in the MB DB at all.

**Screenshots:**

**System Information:**
 - Operating system: Gentoo
 - Strawberry Version: 0.8.4

**Additional context**

**Comment by jonaski** [comment]
I'm not so sure we can guarantee that all services provide artist ID's for album artist, and not the song artist, and how to differentiate which services use which ID. As for Subsonic there are a bunch of different subsonic compatible servers that seem to do things slightly different, so I'm afraid will break the album artist grouping.
Fetching artist name by MusicBrainz ID might be possible, but it's too much work for me to get into for something that has little use for most users, it's probably easier to just tag the different artists with a different album artist.
