### ISSUE TITLE
Equalizer not working when compiled with QT6

### ISSUE THREAD

**Issue by esalgado** [strawberrymusicplayer/strawberry#629]
Hello! I found out that equalizer does not work when compiled with QT6 in my system.

**Describe the bug**
Equalizer does not work with QT6

**To Reproduce**
Compile with QT5 (default): equalizer works fine
Compile with QT6: equalizer does nothing. Activating/deactivating it does not work, balancing stereo speakers does not work 

**System Information:**
 - Operating system: Arch linux
 - Strawberry Version: git latest

I don't know what kind of logs I could attach, I am using pulseaudio.

Thanks!

**Comment by jonaski** [comment]
It works here. I assume you stop and start playback after enabling or disabling the equalizer?

**Comment by esalgado** [comment]
Hello! it is strange... it is working now in both QT5 and QT6...

Sorry it appears something strange happened in my system :)

**Comment by jonaski** [comment]
Are you seeing high memory usage with Qt 6?
For me the memory usage grew up to almost 1 GB with Qt 6 in a few days, while with Qt 5.15.2 it's steady around 200 MB.
I suspect there are some memory leaks in Qt 6.0.0, however it looks to be freed on exit making it hard to pinpoint.

**Comment by esalgado** [comment]
It is like you say... If I open strawberry, and with equalizer enabled, it works. I can click on "enable" "disable" tick and it works fine (without pausing playback).

If I open strawberry with equalizer disabled, in order for it to work, I need to enable, stop, and play again the song. Then I can enable/disable it and it applies instantly.

THanks for the heads up!

**Comment by esalgado** [comment]
> Are you seeing high memory usage with Qt 6?
> For me the memory usage grew up to almost 1 GB with Qt 6 in a few days, while with Qt 5.15.2 it's steady around 200 MB.
> I suspect there are some memory leaks in Qt 6.0.0, however it looks to be freed on exit making it hard to pinpoint.

How do I do the test? I have to test after a certain amount of time? With the program recently open, both QT5 and QT6 use the same memory!

**Comment by jonaski** [comment]
It occurs over time, but I think a few hours of playback to see it grow up to around 400MB, at least over 200MB. I've played both local songs, tidal and streams, I have not been able to see exactly whats causing it.
I want to open a bug report to Qt as soon as possible so it can be fixed before the next minor version, but I have little info to give them.

**Comment by logological** [comment]
> If I open strawberry with equalizer disabled, in order for it to work, I need to enable, stop, and play again the song. Then I can enable/disable it and it applies instantly.

I am experiencing the same symptoms.  Perhaps this issue could be reopened?
