### ISSUE TITLE
High memory usage with Qt 6.0.0

### ISSUE THREAD

**Issue by jonaski** [strawberrymusicplayer/strawberry#630]
I'm experiencing very high memory usage with Qt 6.0.0 over time.
In a few weeks the program uses almost 1 GB of memory.
The only patch I have is for https://bugreports.qt.io/browse/QTBUG-89176 because without it, Qt 6.0.0 frequently crashes.
Compiled with Qt 5.15.2, the program uses steadily around 200 MB.
LeakSanitizer is showing no leaks (just few alsa and fontfconfig ones that have always been there, but nothing related to my code or Qt).
I can reproduce the same on both openSUSE LP 15.2 and tumbleweed.
Using Valgrind, I can see some leaks, but I suspect they are false-positives, and I see the same thing with Qt 5.15.2. I also have problems with Valgrind crashing. I normally use LeakSanitizer because Valgrind is so slow.
I suspect that Qt 6 is allocating some memory that isn't freed but is still ref'ed and free'ed on exit.
Anyone else seen this?
The program only uses base, but all modules.
I want to open a bug report to Qt, but I don't think I have enough to go on.

**Comment by esalgado** [comment]
Hello, I want to help. How do I monitor the memory usage? I am using Arch Linux.

Using htop I can filter by strawberry, but a lot of threads are shown and I can't see how much memory does it use in total without making some maths with the calculator :)

**Comment by jonaski** [comment]
Isn't each thread just showing the total memory anyway?
I use KSysGuard.

**Comment by jonaski** [comment]
After a few minutes of playback with no internet conenction:

![image](https://user-images.githubusercontent.com/10343810/104200439-f4f42c80-5428-11eb-9a9f-2c67bb851d22.png)

**Comment by jonaski** [comment]
Tested a few hours on Qt 6 on Windows earlier today, no increase in memory at all.

**Comment by jonaski** [comment]
If you can reproduce the problem try to disable all internet services: covers, lyrics and scrobbling. Play local files only and see if the memory stabilize.

**Comment by esalgado** [comment]
![16103837870078926693978261852154](https://user-images.githubusercontent.com/977612/104212416-7ea9f700-5435-11eb-8277-18172078b5d5.jpg)
I have been playing for 45 minutes and memory has increased from 180mb to 196mb only, with internet disconnected, I think the issue does not happen to me?

**Comment by jonaski** [comment]
I can reproduce the memory issue on both machines.
Do you have the patch for QTBUG-89176? https://codereview.qt-project.org/c/qt/qtbase/+/326060
If it's stock Qt 6 from Arch, then I guess no.
Maybe there is a regression in that fix.

**Comment by esalgado** [comment]
Is there an easy way to know if the package has the patch?

It is 6.0.0-2:
https://archlinux.org/packages/extra/x86_64/qt6-base/, appears compiled some 20 days ago:

https://github.com/archlinux/svntogit-packages/commits/packages/qt6-base/trunk

Memory was at 234mb after 1h24min. I started skipping songs clicking "next", I got mem to climb up to 350mb, it is stuck there!

I could try to compile QT6 from source if you want!

**Comment by jonaski** [comment]
I'm compiling Qt 6 without the patch now, I'll see then if the memory problems persist or not. Thanks for testing though.

**Comment by esalgado** [comment]
Mine is version without the patch, from 7th of December!

**Comment by jonaski** [comment]
Removed the patch and the problem is gone.
It's a regression in the fix for QTBUG-89176

**Comment by jonaski** [comment]
https://bugreports.qt.io/browse/QTBUG-89998

**Comment by jonaski** [comment]
I'm still seeing high memory usage with patched Qt 6 + fixed a memory leak in Strawberry related to the moodbar.

If anyone wants to help figure it out, install `heaptrack` and `heaptrack_gui`

You need to patch Qt 6 first. But Qt 6.0.1 is released on Monday, 1. February.

To run strawberry with `heaptrack`:

`heaptrack ./strawberry`

Open the produced file in heaptrack GUI after a few days, at least 24 hours.

**Comment by esalgado** [comment]
Hello! In Arch, still is version 6.0.0, maybe I need to wait some more days. You mean that I need first to download 6.0.1 and then patch it? 

`extra/qt6-base 6.0.0-3 (qt6) [installed: 6.0.0-2]
    A cross-platform application and UI framework`

I can't find a download source for qt6, it looks like in qt git repository:

https://code.qt.io/cgit/qt/qt5.git/refs/heads

Also, what patch do I need to download and where?

Thanks :D

**Comment by jonaski** [comment]
I mean you have to patch release 6.0.0. But If you wait until 6.0.1 is released then you don't need to patch. It was scheduled to be released today, but so far it's not released, you can see it here: https://download.qt.io/official_releases/qt/6.0/

**Comment by esalgado** [comment]
Thanks, then I will wait a couple more days for the release to come out, then I will test!

**Comment by esalgado** [comment]
Already compiled with QT 6.0.1 and using heaptrack! I have backed up my collection (so that playcounts can be reversed by restoring the backup) and disabled last.fm and I will let this runing overnight.

But, I don't see any huge usage after 1 hour of continous playback. With Ksysguard I only see 316mb usage:

`The process strawberry (with pid 10580) is using approximately 316.2 MB of memory.
It is using 279.0 MB privately, 11.3 MB for pixmaps, and a further 77.8 MB that is, or could be, shared with other programs.
Dividing up the shared memory between all the processes sharing that memory we get a reduced shared memory usage of 25.9 MB. Adding that to the private and pixmap usage, we get the above mentioned total memory footprint of 316.2 MB.`

`

218508 KB | [heap]
-- | --
16700 KB | /home/esalgado/Downloads/strawberry/build-qt6/strawberry
9280 KB | /usr/lib/libLLVM-11.so
6456 KB | /usr/lib/libQt6Gui.so.6.0.1
5948 KB | /usr/lib/libQt6Widgets.so.6.0.1
2484 KB | /usr/lib/libavcodec.so.58.91.100
1968 KB | /usr/lib/dri/iris_dri.so
1276 KB | /usr/lib/libQt6Core.so.6.0.1
1252 KB | /usr/lib/libgstreamer-1.0.so.0.1803.0
1244 KB | /usr/lib/qt6/plugins/sqldrivers/libqsqlite.so
1136 KB | /usr/lib/libsqlite3.so.0.8.6
1088 KB | /usr/lib/libavfilter.so.7.85.100
788 KB | /usr/lib/libQt6Network.so.6.0.1
712 KB | /usr/lib/libQt6DBus.so.6.0.1

`

**Comment by esalgado** [comment]
OK, I need to stop Strawberry now to boot into windows for Work.  I can share the heaptrack file if you want!

`The process strawberry (with pid 10580) is using approximately 484.2 MB of memory.
It is using 446.8 MB privately, 11.3 MB for pixmaps, and a further 78.4 MB that is, or could be, shared with other programs.
Dividing up the shared memory between all the processes sharing that memory we get a reduced shared memory usage of 26.2 MB. Adding that to the private and pixmap usage, we get the above mentioned total memory footprint of 484.2 MB.`

**Comment by jonaski** [comment]
![image](https://user-images.githubusercontent.com/10343810/107158187-9c14a700-6988-11eb-85b2-1eb9ac0b4133.png)
![image](https://user-images.githubusercontent.com/10343810/107158192-a33bb500-6988-11eb-9919-1cce6a94b6d5.png)

**Comment by jonaski** [comment]
Bottom-Up:

![image](https://user-images.githubusercontent.com/10343810/107158395-ecd8cf80-6989-11eb-9c85-fe5a886a80c0.png)
![image](https://user-images.githubusercontent.com/10343810/107158410-0aa63480-698a-11eb-9421-1031a7c7bf03.png)

**Comment by jonaski** [comment]
The above screenshots are from playing for around 40 hours until it reaches 800-900 MB, I'm using Qt from a recent commit from the Qt dev branch.

**Comment by jonaski** [comment]
Although I'm not an expert on heaptrack, but looking at top-down it looks to be coming from `QDateTime::toString()` from `logging.cpp`
Removing `QDateTime::toString()` in `logging.cpp`, relaunching and testing a few song changes for a few minutes the memory use is then in a `QDateTime::toString()` call related to the mpris code.

**Comment by esalgado** [comment]
Do you want me to send you my heap track capture file so that you can compare? 😊

**Comment by jonaski** [comment]
Sure.
I removed `QDateTime::toString()` calls in 3 places. That memory use is now gone. But I'm now seeing heavy memory usage by the `PlaylistChanged` signal in `Mpris2::PlaylistChangedSlot`.

**Comment by esalgado** [comment]
here you have:

https://mega.nz/file/jPInTa5Y#TyJ7FxSZwhFYNazwAPeoV0HGjdzhSxqlecscPQdfqYY

I hope you are able to fix it :D

**Comment by jonaski** [comment]
I'm not seeing too much memory consumption on yours. But the second biggest in Top-Down is `QDateTime` related too, from the playlist last played.
Did you run for 12 hours? Did you play music continuously?

```
main in strawberry (/home/esalgado/Downloads/strawberry/build-qt6/strawberry)
QCoreApplication::exec() in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
g_main_context_iteration in libglib-2.0.so.0 (/usr/lib/libglib-2.0.so.0)
<unresolved function> in libglib-2.0.so.0 (/usr/lib/libglib-2.0.so.0)
g_main_context_dispatch in libglib-2.0.so.0 (/usr/lib/libglib-2.0.so.0)
<unresolved function> in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
QTimerInfoList::activateTimers() in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
QCoreApplication::notifyInternal2(QObject*, QEvent*) in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
QApplicationPrivate::notify_helper(QObject*, QEvent*) in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
QFrame::event(QEvent*) in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
QObject::event(QEvent*) in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
PlaylistView::timerEvent(QTimerEvent*) in strawberry (/home/esalgado/Downloads/strawberry/build-qt6/strawberry)
QTreeView::timerEvent(QTimerEvent*) in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
QTreeView::updateGeometries() in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
QTreeViewPrivate::updateScrollBars() in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
QTreeView::doItemsLayout() in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
QTreeViewPrivate::layout(int, bool, bool) in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
QTreeView::indexRowSizeHint(QModelIndex const&) const in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
PlaylistDelegateBase::sizeHint(QStyleOptionViewItem const&, QModelIndex const&) const in strawberry (/home/esalgado/Downloads/strawberry/build-qt6/strawberry)
QStyledItemDelegate::sizeHint(QStyleOptionViewItem const&, QModelIndex const&) const in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
QStyledItemDelegate::initStyleOption(QStyleOptionViewItem*, QModelIndex const&) const in libQt6Widgets.so.6 (/usr/lib/libQt6Widgets.so.6)
LastPlayedItemDelegate::displayText(QVariant const&, QLocale const&) const in strawberry (/home/esalgado/Downloads/strawberry/build-qt6/strawberry)
Utilities::Ago(int, QLocale const&) in strawberry (/home/esalgado/Downloads/strawberry/build-qt6/strawberry)
QDateTime::currentDateTime() in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
QDateTime::fromMSecsSinceEpoch(long long, Qt::TimeSpec, int) in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
QDateTime::setMSecsSinceEpoch(long long) in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
<unresolved function> in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
qTzSet() in libQt6Core.so.6 (/usr/lib/libQt6Core.so.6)
tzset in libc.so.6 (/usr/lib/libc.so.6)
tzset_internal in libc.so.6 (/usr/lib/libc.so.6)
__tzfile_read in libc.so.6 (/usr/lib/libc.so.6)
__fopen_internal in libc.so.6 (/usr/lib/libc.so.6)
```

**Comment by esalgado** [comment]
Yes! More or less 12 hours non stop music, I muted the speakers and went to sleep with a smart playlist :D
