### ISSUE TITLE
Lyrics don't appear when streaming Tidal.

### ISSUE THREAD

**Issue by enezzolation** [strawberrymusicplayer/strawberry#631]
When I stream from Tidal, the lyrics don't appear.

**Comment by jonaski** [comment]
Works here.
What version, what OS? What songs?

**Comment by enezzolation** [comment]
Strawberry 0.8.5, Debian Buster and any song I play on Tidal.

**Comment by jonaski** [comment]
"Automatically search for song lyrics" needs to be enabled in Tools / Settings / Context.
If it still does not work, start strawberry from a terminal so you can see the log outputs.

**Comment by enezzolation** [comment]
I was not looking at context menu LOL I'm sorry for wasting your time
