### ISSUE TITLE
Subsonic Play All function while arranged 

### ISSUE THREAD

**Issue by DOFfactory** [strawberrymusicplayer/strawberry#634]
I know this might be of a low priority issue, but it frustrates me that I am able to build a catalog (database) of all the music files present on my SubSonic server by Strawberry, but I am unable to put _all_ songs on a playlist and shuffle between them whenever any type of `Grouping` is enabled (by Artist, Albums, whatever). 

Whenever I try drag and drop, Subsonic crashes (Not responding...).

Things are better when I switch to `None` in grouping, but it would be better to avoid this unnecessary trick and just move the files to playlist as they are grouped instead.

**Comment by jonaski** [comment]
I don't consider this a bug, but rather additional functionality you want, which we do not have resources or contributors to do right now. This is explained in the README and the issue template. These things has to come as contribution by someone.
Mass adding songs won't work very well with the lazy-loading implementation used for the models. This is explained before.
I'm not sure adding such a feature is a good idea anyway as there could be thousands of songs, adding all songs to the playlist is asking for trouble.
But subsonic and the other services should be integrated into the smart playlists which has such a feature, but that has to come as a contribution by someone.

**Comment by DOFfactory** [comment]
Thanks for the reply @jonaski. If I may comment, I believe it is indeed a bug. I currently have around 30.000 songs on my SubSonic server. I have the catalogue rebuilt and I want to import all the songs to the playlist. 

1. When I try doing so with the following Grouping enabled:  `Group by Album Artist/Album`, the albums are listed as folders, and under these folders are the albums. Now, if I hit Ctrl+A, Strawberry selects all the folders, and moving them to the Playlist ends in the aforementioned `Not responding...` issue. I think this is indeed a bug.
2. If I select Grouping as `None`, I can select all songs with Ctrl+A, and move them to the Playlist. It indeed takes a while but at least it gets done. Hence, I believe that there is a bug somewhere around the Grouping and moving the groups to the playlist. 

I hope this does make sense. I run the latest Strawberry on Windows 10. Memory should not be the issue, as I run on 32GB, and the CPU is also rather powerful i7-7700HQ.

**Comment by jonaski** [comment]
That's expected, since when you select None grouping it uses one SQL query to retrieve all the songs, while other groupings will use one SQL query per node as it walks down the tree, so possible hundreds of queries to retrieve all the songs.
It's a restriction in the implementation rather than a bug. Its not intended use-case to mark all songs.
To change this require large code parts to be completely rewritten, many things depend on the current design, and there will be possible other disadvantages of doing it another way too.

**Comment by DOFfactory** [comment]
I see thank you for the detailed explanation. Maybe a better option would be to introduce a button like "Add all to current playlist", or an option in the Preferences for Subsonic "Create All Music Playlist" with an On/Off button would be advisable, since the database is anyway on the PC. This may then mimic the iTunes and other player behavior, where all the songs are listed.

In addition, I would suggest disabling the drag&drop option for the SubSonic albums for the explicit cases when _any type of grouping_ is on. IMHO it is a bad design if a task can turn the software unusable and can lead to the collapse of the app. By disabling this (and I accept your arguments) the `Not responding` issue can be avoided.
