### ISSUE TITLE
Grouping tag in FLAC files not identified or searchable

### ISSUE THREAD

**Issue by metronidazole** [strawberrymusicplayer/strawberry#639]
**Describe the bug**
If you search for a grouping tag (e.g. "Grouping:Foo"), only music files with ID3 tags will be found - FLAC files with the grouping tag/comment are not returned by this search.

**To Reproduce**
1. Have two music files foo.mp3, bar.flac
2. Assign the same grouping tag to each using MusicBrainz Picard e.g. foobar
3. Add to strawberry
4. Search for "grouping:foobar"
5. Only the mp3 file will show.

**Expected behavior**
Both foo.mp3 and bar.flac should show

**Screenshots:**
N/A

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.8.5

**Additional context**
Doing further investigation, when I edit a flac file with strawberry it shows the grouping tag as blank. I assume it's probably pulling a different field than what is expected or not at all.

**Comment by jonaski** [comment]
We use `"CONTENT GROUP"`

**Comment by jonaski** [comment]
Try with this fix https://github.com/strawberrymusicplayer/strawberry/commit/1ea8b064cccf36bc7fb62ed8702dd8fadb338a38

**Comment by metronidazole** [comment]
Thanks that worked.
