### ISSUE TITLE
gstreamer plugin is missing

### ISSUE THREAD

**Issue by lvsunz3748** [strawberrymusicplayer/strawberry#641]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots:**

**System Information:**
 - Operating system:
 - Strawberry Version:

**Additional context**

**Comment by jonaski** [comment]
What gstreamer plugin is missing? Which package?

**Comment by jonaski** [comment]
Closing this as you did not fill in any information making it impossible to help you.
