### ISSUE TITLE
Strawberry Clears m3u Playlist File on Save

### ISSUE THREAD

**Issue by gavinhoward** [strawberrymusicplayer/strawberry#643]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
When I try to save an `m3u` file with Strawberry, it saves these contents to the file:

```
#EXTM3U
```

This happens despite the current playlist having songs in it. This happens whether or not there are missing files in the playlist.

**To Reproduce**
1. Create a playlist of songs.
2. Save the playlist.
3. Check the file contents.

**Expected behavior**
The actual playlist files should be in there.

**Screenshots:**

**System Information:**
 - Operating system: Gentoo Linux 5.10.12, `x86_64`.
 - Strawberry Version: Almost `master` (commit 60528525e0).

**Additional context**
None?

**Comment by gavinhoward** [comment]
I am starting to investigate, by the way.

**Comment by gavinhoward** [comment]
The same bug happens with `xspf` files.

**Comment by jonaski** [comment]
It's related to the signal/slot conversions I did in `PlaylistContainer::SetActions`.
It's passing 0 instead of the ID for the current playlist.
Looks at the changes I did for playlistcontainer.cpp and playlistcontainer.h.
https://github.com/strawberrymusicplayer/strawberry/commit/bf7c8df353d51426441a6b16c9724174b2905654

**Comment by jonaski** [comment]
I understand why it's not working, but I don't understand how it worked at all in first place.

**Comment by jonaski** [comment]
Ah, of course: `Save(id == -1 ? current_id() : id, filename, path);` in `PlaylistManager::SaveWithUI`
I think all you need to do to fix it, is to change the slot to `SaveCurrentPlaylist()`

**Comment by gavinhoward** [comment]
I will do so. Thank you!
