### ISSUE TITLE
dark theme on appimage QT5 

### ISSUE THREAD

**Issue by smikeblog** [strawberrymusicplayer/strawberry#645]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
Doesn't work when dark theme on linux
**To Reproduce**
Steps to reproduce the behavior.
kvantum+select+theme+arcdark+application straberry
**Expected behavior**

**Screenshots:**

**System Information:**
 - Operating system:
 - Strawberry Version:

**Additional context**

**Comment by jonaski** [comment]
Unfortunately there are restrictions with the AppImage such as not adapting styles and settings from the system. Use Strawberry as a regular package.

**Comment by smikeblog** [comment]
OK! Thanks.
