### ISSUE TITLE
"Play" starts with a song not in the search list

### ISSUE THREAD

**Issue by luke-jr** [strawberrymusicplayer/strawberry#646]
My general usage pattern is to keep an "All Tracks" playlist open and use the search to limit what songs play as desired. However, if I search and click Play, it chooses a song NOT in the search results.

Expected behaviour: choose a song at random from those displayed, like Clementine did.

**Comment by jonaski** [comment]
If you start with an empty playlist, then add two albums, then filter so you only see the songs from the last album in the playlist, then click play, it will always start from index 0, the first song in the playlist, unless you stopped playback and it saved the last played index.
You'll see this if you look at the `Player::PlayPause` function, it sets the index to 0 when starting playback from an idle state.
The behaviour you want only occurs when changing tracks, you can see this in the function `Playlist::NextVirtualIndex` which is called from `Playlist::next_row`.
This behavior is consistent with Clementine, and as far as I remember this behavior has never been different.

**Comment by luke-jr** [comment]
It's definitely different with Clementine.

A probably-related issue (let me know if I should open a new issue for it): Setting "Stop after this track" works, but then clicking "Play" jumps to another track. Clementine would reliably play the track it stopped after.

**Comment by jonaski** [comment]
Also "Stop after this track" works fine here, it continues the next song when you press play again.
You didn't even use the issue template. Without more info I will close this.
