### ISSUE TITLE
Volume control in linear(?) instead of normal (logarithmic?)

### ISSUE THREAD

**Issue by luke-jr** [strawberrymusicplayer/strawberry#647]
**Describe the bug**
Under ~70% volume, I hear nothing. At 100% it's very loud.

**Expected behavior**
Most volume controls "sound" more evenly gradual.

**System Information:**
 - Operating system: Gentoo
 - Strawberry Version: 0.8.5 (VLC engine)

**Comment by jonaski** [comment]
Use gstreamer, VLC is mostly there for testing purposes, not in development.
