### ISSUE TITLE
Errors playing songs halt playback entirely

### ISSUE THREAD

**Issue by luke-jr** [strawberrymusicplayer/strawberry#648]
**Describe the bug**
If Strawberry hits a song that it can't play, it displays an error dialog and stops. Neither "Play" nor "Next" resume.

**To Reproduce**
A file named .mp3 consisting only of several null bytes seems to do the trick.

**Expected behavior**
Clementine displays the error and keeps playing with another song. I'm not sure if that's the ideal, but at the very least it should be possible to resolve without manually picking something else to play. An option to just keep playing would be nice, but care is needed to avoid displaying many dialogs if suddenly the library disappears (and everything errors).

**System Information:**
 - Operating system: Gentoo
 - Strawberry Version: 0.8.5 (gstreamer backend)

**Comment by jonaski** [comment]
A MP3 file with null bytes can't be recognized by gstreamer as a valid stream and will generate a stream error, not a resource error.
Errors in this domain are almost always codec related, so it won't continue playing.
Most of the time these errors are generated when a user is missing a gstreamer plugin, so it should stop so the user is informed and can install the correct plugin.
The setting specifically says "_Continue to the next item in the playlist if a song is unavailable_".
A song isn't "unavailable" in the stream error related cases.
However I added GST_STREAM_ERROR_TYPE_NOT_FOUND as an exception, it should then be able to skip in the case for invalid files where it won't work installing a codec anyway.
