### ISSUE TITLE
Chocolatey inclusion issue

### ISSUE THREAD

**Issue by b16r05** [strawberrymusicplayer/strawberry#649]
Hello @jonaski 

I requested that Strawberry Music Player be included as a chocolatey package. The maintainer used the latest package at the time (v0.8.1) , and some checks failed. I hope someone reached out to you, but just in case, I am just writing here to let you know what is going on. 

Chocolatey page: https://chocolatey.org/packages/strawberrymusicplayer
RFP: https://github.com/chocolatey-community/chocolatey-package-requests/issues/739

Thanks!

**Comment by jonaski** [comment]
What checks failed? Is this something I should do something about?
I already commented on https://chocolatey.org/packages/strawberrymusicplayer

**Comment by b16r05** [comment]
@jonaski Thank you for the reply. I saw your comment on Chocolatey. The maintainer is not responsive. He was trying an older version from October as well. You are interested in having Strawberry published on Chocolatey. I think reaching out the maintainers of Clementine is a good idea: https://chocolatey.org/packages/clementine. I don't have an account over there... but can certainly create another RFP in Github.
