### ISSUE TITLE
How do I modify the "Title" column when I add an online radio station via the "Add URL" menu option? 

### ISSUE THREAD

**Issue by dln949** [strawberrymusicplayer/strawberry#655]
Strawberry 0.8.5 (AppImage) on Ubuntu 18.04.  

How do I modify the "Title" column when I add an online radio station via the "Add URL" menu option?  Right now it just shows the URL, so it is hard for me to know which station I am selecting.

**Comment by jonaski** [comment]
This needs to be done through SQL. Close strawberry while doing it to avoid overwriting the changes.

`sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db`

Find stream urls:

`select url from playlist_items where url like 'http%';`

Update title for a URL:

`update playlist_items set title = 'Radio Paradise Mellow FLAC' where url like 'http://stream.radioparadise.com/mellow-flacm';`
