### ISSUE TITLE
Font Rendering Issues

### ISSUE THREAD

**Issue by ralphee** [strawberrymusicplayer/strawberry#659]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
Fonts are not rendered properly (Nerdfont / Souce Code Pro)

**To Reproduce**
Open Application

**Expected behavior**
Fonts Rendering Issue

**Screenshots:**
[font rendering](https://i.imgur.com/GS9i3iE.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.8.5

**Additional context**

**Comment by jonaski** [comment]
This looks more like a system configuration issue.
How does it look in qt5ct?
"Souce Code Pro" font works fine here:

![image](https://user-images.githubusercontent.com/10343810/110697884-3caaf080-81ed-11eb-84cd-b592233344dc.png)
