### ISSUE TITLE
(macOS) Crashing frequently with GPU/lifecycle/memory managed errors

### ISSUE THREAD

**Issue by smchenrybc** [strawberrymusicplayer/strawberry#660]
In Big Sur, I'm seeing frequent crashes with the following errors reported in the console:

- [app<application.org.strawberrymusicplayer.strawberry.12976188910.12976189161(501)>:82384] Skipping AppNap state - not lifecycle managed
- [app<application.org.strawberrymusicplayer.strawberry.12976188910.12976189161(501)>:82384] Ignoring GPU update because this process is not GPU managed
- [app<application.org.strawberrymusicplayer.strawberry.12976188910.12976189161(501)>:82384] Ignoring suspend because this process is not lifecycle managed
- [app<application.org.strawberrymusicplayer.strawberry.12976188910.12976189161(501)>:82384] Ignoring jetsam update because this process is not memory-managed

Running the Crescendo event viewer, I get a bunch of `file::create`, `file::unlink` events prior to the crash. No surprise there, but could the crashes be related to disk access? I went to System Preferences > Security & Privacy > Full Disk Access and added Strawberry here. Seems to have stopped the crashes, but my guess is this isn't a proper solution.

Thanks!

**Comment by smchenrybc** [comment]
Nevermind. The app is still crashing. Generally, I can get this to happen by opening a playlist and just clicking to play one song after another. It can happen under normal use though and has generally made it so I can't have the app open for more than a couple minutes before it crashes.

**Comment by jonaski** [comment]
You don't mention what version you use even though we have a issue template for that exact reason.
The 0.8.5 release is Qt 5 based and the recent development builds are Qt 6 so there is a big difference.
It could be related the device listener picking up a removable device, network share or something connected to your mac, try disconnecting or umounting stuff, even though that's just guessing.
Try disabling moodbar in moodbar settings, album cover pixmap disk cache in collection settings, disable album cover search so no covers are written to disk, disable lyrics search so the network disk cache is not used.  Check if it happens with local files or with streams, if it only occurs with streams it could be related to network cache, no setting to disable that but can be disabled by removing one line in the code.

**Comment by smchenrybc** [comment]
Sorry about that! The version is 0.8.5. As of now moodbar is disabled. "Saving album covers" is disabled also. Album cover search and lyric search were enabled so I'm disabling those two as well. I'm only testing this with local files -- no streams. Finally, scrobbling is disabled as well. I'll test this configuration and see how it goes. Appreciate the suggestions!

**Comment by jonaski** [comment]
Can you try the new 0.9.1 release and see if it fixes it?

**Comment by smchenrybc** [comment]
Hey, it seems like with the 0.9.1 version, the crashes are fewer and more infrequent. I still have gotten a crash or two and this time, thankfully, I was able to get a crash report out of Mac's Console app. Here's a section of it:
```Process:               strawberry [65032]
Path:                  /Applications/Strawberry.app/Contents/MacOS/strawberry
Identifier:            org.strawberrymusicplayer.strawberry
Version:               0.9.1 (0.9.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           strawberry [65032]
User ID:               501

Date/Time:             2021-03-14 21:12:11.021 -0400
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        0D8427E7-2B9F-4E17-27BE-34C35FC5EC13

Sleep/Wake UUID:       CCB72F37-738A-4F27-A631-3F9AA29C01DC

Time Awake Since Boot: 210000 seconds
Time Since Wake:       170000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000010008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [65032]

VM Regions Near 0x10008:
--> 
    __TEXT                      10d8ef000-10e303000    [ 10.1M] r-x/r-x SM=COW  /Applications/Strawberry.app/Contents/MacOS/strawberry```

**Comment by smchenrybc** [comment]
I see on the Strawberry site that the project doesn't have an OSX developer, currently, so I understand this may be a hard one to diagnose and fix. I will note that I also use this software on Windows and it runs beautifully.

**Comment by jonaski** [comment]
I might be able to look into it if you get a backtrace because I can't reproduce the crash.
But if you don't get one, you need to compile and run Strawberry in debug with lldb.
Instructions here: https://github.com/strawberrymusicplayer/strawberry/wiki/Compile-and-install-on-macOS
To compile in debug you need to use the following cmake command instead of the one in the instructions:
`cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_WITH_QT6=ON -DUSE_BUNDLE=OFF -DENABLE_SPARKLE=OFF`
Then you can run Strawberry in debug with:
`lldb ./strawberry.app/Contents/MacOS/strawberry`

**Comment by jonaski** [comment]
Can you check if it is still a problem on macOS 11.3?

**Comment by smchenrybc** [comment]
Sure thing! Checking now...

**Comment by smchenrybc** [comment]
I think this looks fixed, Jonas. The player is running great now!
