### ISSUE TITLE
Album Cover to Ipod Classic

### ISSUE THREAD

**Issue by coelhofc** [strawberrymusicplayer/strawberry#663]
Hello, wondered if anyone could help with this.

The player is amazing, I find it even better than Clementine, but this same issue persists: when I add songs to my Ipod Classic, it doesn't load the covers. With Clementine there was no cover at all, with Strawberry it loads a question mark symbol cover. 

Still, in the player everything is set up fine, the covers work perfectly. I tried with the covers saved on cache, embedded or on the folder. Funny thing is, if I use gtkpod to add the same files to the ipod, the covers are loaded correctly.

Any suggestions?

**Comment by jonaski** [comment]
Strawberry copies album covers to the iPod, but I'm not sure why it doesn't work. I'm unable to help since I don't have a iPod that works with album art.
There was some discussion on it  and work being done here:
https://github.com/strawberrymusicplayer/strawberry/issues/519
I got 2 iPods, but only one of them works with libgpod, I suspect the other one is too new, the DB get's corrupted if I transfer music to it. The other one I suspect is too old to handle album covers.
I never got gtkpod to work.

**Comment by coelhofc** [comment]
Yeah, seems like something inherited from Clementine, as it happens there as well. For now, I have to use Rythymbox to transfer the files to the ipod with album art. It is ok, as both apps are synched to the music folder, so any change I make with Strawberry appears on Rythymbox in a matter of seconds. Still... it would be better to only use Strawberry.

**Comment by jonaski** [comment]
Not really. Clementine doesn't copy album covers to the iPod, and never have.

**Comment by jonaski** [comment]
What image format are your covers in?

**Comment by jonaski** [comment]
Looking at the source code for gtkpod, it's doing similar to strawberry, so I can't really see what's wrong.
Although rhythmbox is doing it different, using itdb_track_set_thumbnails_from_pixbuf()

**Comment by jonaski** [comment]
I take that back, I see a potential problem now.

**Comment by jonaski** [comment]
I got covers to work on my oldest iPod model now.
Turns out the file with the written cover was deleted too soon.

**Comment by coelhofc** [comment]
Hi Jonas, thanks for that. It is still inconsistent for me, some files moved over with the cover, other didn't. The covers are in jpg. If it helps, my ipod is the 7th gen, 160gb model. Cheers

**Comment by jonaski** [comment]
Does the audio files that is copied over without cover have embedded cover associated?
Could you check with the file command if the JPEG format is different than the others that work?

**Comment by jonaski** [comment]
It looks to be working stable on my iPod now.
So not sure why it doesn't work stable for you, what build version are you at?

**Comment by coelhofc** [comment]
Hi, I am on 0.9.1. It is actually not working for me. At first it showed the album cover on Strawberry for the files in the device, but after a while it doesn't anymore (goes back to the question mark image) and it is not on the ipod either. I tried using album cover manager to download a new album cover, save it as embedded and them add the song to ipod, but no success.

**Comment by jonaski** [comment]
You need to use a development version from https://builds.strawberrymusicplayer.org/ as I just fixed it.
You need 0.9.1.19.gc4a6d81c or newer.

**Comment by coelhofc** [comment]
Thank you, Jonas. It is working perfectly now!
