### ISSUE TITLE
Strawberry rejects common file extensions for supported formats.

### ISSUE THREAD

**Issue by damian101** [strawberrymusicplayer/strawberry#669]
Strawberry plays back raw AAC, AC3 and DTS streams without problems, but rejects the files when they have their most common extensions ".aac", ".ac3" or ".dts".

**Comment by jonaski** [comment]
https://github.com/taglib/taglib/blob/master/taglib/fileref.cpp#L112

Report it here: https://github.com/taglib/taglib/issues

**Comment by damian101** [comment]
> https://github.com/taglib/taglib/blob/master/taglib/fileref.cpp#L112
> 
> Report it here: https://github.com/taglib/taglib/issues

I don't think those raw stream formats support any metadata, at least not officially. Mp3tag can write ID3 metadata to raw AAC, but I don't think that's officially supported, and Strawberry can't read them.

**Comment by jonaski** [comment]
Okay

**Comment by jonaski** [comment]
I think we can specifically make exceptions for some formats.

**Comment by damian101** [comment]
@jonaski I just noticed that files with extension dsf are also rejected by Strawberry.
Weird thing about this is that the DSF format seems to be supported by taglib.

**Comment by jonaski** [comment]
TagLib does not have the DSF support in the latest release 1.12. There is dsf/dsdiff support in the taglib2 branch which is what the bundled taglib we had was using previously, however, most distros didn't use it anyway, and since there was a new taglib release I decided to drop it.
