### ISSUE TITLE
SID, NSF are treated as incorrect audio files

### ISSUE THREAD

**Issue by daxim** [strawberrymusicplayer/strawberry#671]
**To Reproduce**

Examples for testing, please download/unarchive to local disk first:

* https://hvsc.c64.org/download/sids/50112
* https://fi.zophar.net/soundfiles/nintendo-nes-nsf/castlevania-2-simons-quest-1987/Castlevania%202%20-%20Simon%27s%20Quest%20%28EMU%29.zophar.zip

Add the SID or NSF file into a playlist.

**Expected behavior**

Tracks are added and are playable.

**Actual behavior**

Strawberry shows error dialog complaining about an incorrect audio file.

**System Information**

* openSUSE Tumbleweed 20210307
* Strawberry 0.9.1-1.2 as packaged by distro

**Additional context**

Works fine in [deadbeef](http://deadbeef.sf.net) and [VLC](http://videolan.org).

**Comment by jonaski** [comment]
It does not support those formats.

**Comment by lihasika** [comment]
add support please?
