### ISSUE TITLE
Search in Tidal

### ISSUE THREAD

**Issue by RubyHuntsman** [strawberrymusicplayer/strawberry#672]
Hi, I want talk about search in Tidal. Some artist had many albums not as "album", but as EP or singles. Unfortunately search engine can't search in above resources. Any ideas to go around?

**Comment by jonaski** [comment]
No. In the unofficial documentation, only artists, albums and tracks is documented, and that's what implemented in the search.
Logically I thought EP's would show up in albums search, but maybe not.
