### ISSUE TITLE
Can't open file browser (Thunar)

### ISSUE THREAD

**Issue by staticssleever668** [strawberrymusicplayer/strawberry#674]
**Describe the bug**
When I use "Show in file browser..." action anywhere in the program, Thunar pops up with an error message: `Failed to open "%F".` 

**To Reproduce**
Install Thunar, select it as the default file manager and use "Show in file browser..." action.

**Expected behavior**
I expect the folder where selected song/album resides to open.

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.9.2 (from Arch Linux official repository) and 0.9.2-7-gf760b3f2 (compiled by hand and using strawberry-full-git AUR package)

**Additional context**
What's weird, for some time it began working, but after Thunar update on 2020-12-25 it stopped working again. Packages updated on that day: `thunar thunar-volman exo libxfce4ui libxfce4utils`.
I tried fiddling with the source code a bit, and here are some inelegant in my opinion solutions:
1. Pretend that `command` is empty, like with 'exo-open'. In Arch Linux Thunar depends on Exo anyway.
```c++
diff --git a/src/core/utilities.cpp b/src/core/utilities.cpp
index 08a9377f..42497e90 100644
--- a/src/core/utilities.cpp
+++ b/src/core/utilities.cpp
@@ -387,7 +387,7 @@ void OpenInFileManager(const QString path, const QUrl &url) {
     command = command.split("/").last();
   }
 
-  if (command.isEmpty() || command == "exo-open") {
+  if (command.isEmpty() || command == "exo-open" || command == "thunar") {
     QDesktopServices::openUrl(QUrl::fromLocalFile(path));
   }
   else if (command.startsWith("nautilus")) {
```
2. Add a special case for Thunar.
```c++
diff --git a/src/core/utilities.cpp b/src/core/utilities.cpp
index 08a9377f..04724a36 100644
--- a/src/core/utilities.cpp
+++ b/src/core/utilities.cpp
@@ -402,6 +402,9 @@ void OpenInFileManager(const QString path, const QUrl &url) {
   else if (command.startsWith("pcmanfm")) {
     proc.startDetached(command, QStringList() << command_params << path);
   }
+  else if (command.startsWith("thunar")) {
+    proc.startDetached(command, QStringList() << path);
+  }
   else {
     proc.startDetached(command, QStringList() << command_params << url.toLocalFile());
   }
```

**Comment by jonaski** [comment]
It's because the desktop file "Exec" entry contains `%F`, which means a list of files:
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
And we don't strip that out. We should probably strip everything off starting with a %

**Comment by staticssleever668** [comment]
Hi, the pattern you made strips only lowercase letters. Shouldn't it be case-insensitive? If so, the pattern should be `[%][a-zA-Z]*( |$)` (notice the 'A-Z').

**Comment by jonaski** [comment]
Yeah, of course, thanks!
