### ISSUE TITLE
Cannot use greek accents when editing track information

### ISSUE THREAD

**Issue by frontierpsycho** [strawberrymusicplayer/strawberry#675]
**Describe the bug**
When editing track information, I'm trying to add greek accents, and it doesn't work. Basic greek characters work fine, and the fields themselves take accented characters, though - I know because for example copy-pasting a word with an accent works, but typing in the same word does not. 

To explain further how it should work: to add an accent to a character in greek, one needs to press ; (ö on a Swedish keyboard) and then the character, so when I press ; and then α, the result is ά (see also [this](https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/KB_Greek.svg/1280px-KB_Greek.svg.png)).

I would guess that this isn't an issue that only affects greek accents, but it's possibly a misconfiguration of the fields and their encoding, so that combined characters do not work.

**To Reproduce**
1. Install the standard greek keyboard layout and switch to it.
2. Right click on a track in Strawberry, select Edit track information.
3. Go to the Artist field, and attempt to type in a character with an accent, for example ά, by pressing ; and then a.

**Expected behavior**
The accented ά should appear in the field. A simple α appears instead. The accent did not work.

**Screenshots:**
![Screenshot_20210328_215846](https://user-images.githubusercontent.com/1224087/112766166-cdb50080-9010-11eb-964a-4665504abf36.png)

**System Information:**
 - Operating system: Debian unstable, with Qt 5.15.2 (on KDE Plasma 5)
 - Strawberry Version: 0.9.2 (latest at time of writing)

**Additional context**
This might come in handy to copy-paste when testing this (but remember that copy-pasting works, typing doesn't): Αλκίνοος.

**Comment by jonaski** [comment]
If I type ALT GR + ; then a, I get: `á`, same behavior as in any other program, terminal and kate.
So I'm not getting a `ά`.

**Comment by frontierpsycho** [comment]
Thanks for the response! I'm a bit confused though. The _expected_ behaviour is that when you're using greek as the typing language, you should get an ά, but I'm actually getting an α (without the accent). How are you getting an á, with a latin a? That probably can't come with greek as the typing language. Or did I misunderstand?

**Comment by jonaski** [comment]
With Greek keyboard layout and typing ALT GR + ; then a, I get: ά, same in kate as in the edit tag dialog for strawberry.
Screenshots:
![image](https://user-images.githubusercontent.com/10343810/113174809-0c35ff80-924b-11eb-9755-cc29cae50f26.png)
![image](https://user-images.githubusercontent.com/10343810/113175026-4acbba00-924b-11eb-8d89-19e2fe17584c.png)

In any case this isn't a strawberry bug, so I suggest you get help in the appropriate mailing-list or forum for your distro, or perhaps the KDE forums.
I use XFCE, so it could be a KDE bug, but more likely a configuration issue.

**Comment by frontierpsycho** [comment]
Just tested in KID3, but it doesn't seem to have the same dropdown. Just typing accented chars worked fine.

https://user-images.githubusercontent.com/1224087/113195569-b8371500-9262-11eb-9848-10606a234cbc.mp4

**Comment by jonaski** [comment]
It's the tag completer that creates the popup, it looks it up in collection to find matches.
Not sure if there is a solution other than just clicking in the field to close the popup before you type an accented character.
Basically the fields are customized QLineEdit's with customized QCompleter: https://doc.qt.io/qt-5/qcompleter.html.

**Comment by frontierpsycho** [comment]
Interesting. So either this is a bug in QLineEdit/QCompleter, or in the Clementine/Strawberry specific customizations, right? Either way, at least there's a workaround. 

If you think this might be a Clementine/Strawberry issue that you can fix, leave the issue open, otherwise close it, I guess. Thanks for looking into it.

**Comment by jonaski** [comment]
Does not look to be a clementine/strawberry issue to me. I made a small program to reproduce it easily with both Qt 6.0.3 and Qt 5.15.2.
https://forum.qt.io/topic/125318/qcompleter-with-keyboard-accents

**Comment by frontierpsycho** [comment]
That's awesome, thanks for reproducing it! I'll register and comment as well, most likely. Closing.

**Comment by jonaski** [comment]
I reported it to Qt as a bug as I'm not getting much response in the forum:
https://bugreports.qt.io/browse/QTBUG-92464
