### ISSUE TITLE
The selected song highlight is confusing

### ISSUE THREAD

**Issue by madprops** [strawberrymusicplayer/strawberry#676]
I click, or double click a song, it gets highlighted.
This creates two highlights, the playing song, and the last selected song.
This means that at any given time there will be two items with the (blue in my case) highlight.
This is confusing to quickly scan what is the playing song.
If I could customize the selection highlight I would at least make it quite different to the playing song.
Or make it de-highlight automatically after some time or action.
What I do is go to the bottom of the playlist and click an empty space to de-highlight it.

**Comment by jonaski** [comment]
It's using `QPalette::Highlight` for both. I suggest that we change the color for the current playing song to something else, maybe a setting.
Do you have a suggestion for color? https://doc.qt.io/qt-5/qpalette.html
I've tried several alternatives based on the hightlight color without hard-coding the color, but it looked awful.

**Comment by jonaski** [comment]
The color for the selected song is here: https://github.com/strawberrymusicplayer/strawberry/blob/master/src/playlist/playlistview.cpp#L513

The color for the currently playing song is here: https://github.com/strawberrymusicplayer/strawberry/blob/master/src/playlist/playlistview.cpp#L458

**Comment by madprops** [comment]
>Do you have a suggestion for color?

I think the current color(s) for the playing song is alright, looks nice. What I would change is the color for the selected item. Either I would tweak its opacity to make it more subtle, or what might be better, de-highlight it automatically. There's no need really, to have it highlighted all the time, the only case where I think it would matter is if you need to know where the selected item is for quick keyboard navigation, but it could be tweaked to highlight again when using the arrows (highlight on demand, de-highlight on play or after x seconds).

**Comment by jonaski** [comment]
Well, the color for the selection should follow the system set color for highlight, it makes more sense, other users will complain if it's adjusted to something else.
But I've made a setting for changing the color for the currently playing song under the appearance settings, it's the best I can do.

**Comment by madprops** [comment]
@jonaski Ok I understand, and thanks. Btw, the setting "Automatically select current playing track" (kinda) solves the problem I had. It highlights the next song and dehighlights the selected track but not 100% for some reason
