### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by jonaski** [strawberrymusicplayer/strawberry#685]
Is there anyone interested in creating a new web site for Strawberry?
If not, I will start working on a new website pretty soon.

**Comment by Isma1306** [comment]
Hi! 
I love your program and it would be a pleasure for me to do a simple webpage for you with a little more of style. I don't know if you want something special to put on it or just to restyle it. Let me know what you are trying to do and I will make a demo for you!

**Comment by jonaski** [comment]
Something basic is fine, similar content to what's there now.
It will be mostly static content, only need to bump the version numbers and distro versions.
I plan to use a dedicated MediaWiki site for documentation as that is easier to get others involved with editing.
One think I'd like to have is some album covers in the background, I've seen some site somewhere that had that, and it looked very nice. I'd like to pick some covers to use.
We could also add some self-shot photos of strawberries, etc. But we can do that later so it doesn't delay the new website.
Apart from that, the content would be similar to what's there now:
- A short description of strawberry and the features
- Screenshots
- Sponsorship
- Downloads
- Links to the different sites:
1. GitHub, participate, report bugs
2. A new MediaWiki site with documentation
2. Forum, get technical help, discussion and suggest features

Maybe the only thing technical we need on the main website is how to install the PPA repository, since Ubuntu does not have Strawberry in their repo.

The current site is in PHP, no CMS or framework except for the screenshots popups uses jQuery.
I got some experience with Drupal and Wordpress, so I'm fine with anything written in PHP.
I'm also fine with anything JavaScript based like NodeJS, Vue, React, etc.
But I like to stay away from anything Python based as I don't really like the language.
I want to host it on Linux, and probably want to still self-host it too on the same server it's running on now.
I also like to stay away from MS stuff, like .NET Core except for perhaps Angular.

But it doesn't have to be using a framework, it can just be a basic HTML/CSS site too with some JS, but I'd like to keep jQuery or similar for the screenshots.

I can put the existing one on a GitHub repo and give you access.

**Comment by Isma1306** [comment]
Perfect, I will start working on the webpage tomorrow. I think that for the simplicity of the page it will be easier just to do it on HTML, CSS and JS later if we need to add something we can do it. I have experience with Wordpress but I think it is too bloated and heavy for something like this. 

> I can put the existing one on a GitHub repo and give you access.

Yes, that would be great.

> One think I'd like to have is some album covers in the background, I've seen some site somewhere that had that, and it looked very nice. I'd like to pick some covers to use.

Yes I like that, let me know which ones and I will think something to do with them.

>We could also add some self-shot photos of strawberries, etc. But we can do that later so it doesn't delay the new website.

For now we can find some free stock pics and then replace them when we find the right one.


One thing, I am new with github, it seems to me very straight forward, but if I make something silly, let me know.

**Comment by jonaski** [comment]
I have added you to this repo: https://github.com/strawberrymusicplayer/strawberry-website

**Comment by jonaski** [comment]
There is a nice old-school analog based webstat page here: https://www.strawberrymusicplayer.org/webstat/
I had completely forgotten about that one.

**Comment by Isma1306** [comment]
Nice, I will be checking everything today, and luckily start coding too.

**Comment by jonaski** [comment]
New website is now live! :partying_face: Thanks @Isma1306
