### ISSUE TITLE
Fix stream discoverer for Windows and macOS

### ISSUE THREAD

**Issue by DOFfactory** [strawberrymusicplayer/strawberry#689]
**Describe the bug**
This is not really a bug report rather a request for enhancement. I use Strawberry for playing songs from a Subsonic server. Currently, there is no way one can check in what format and bitrate is the song played in (in case it is transcoded on the server). Would it be please possible to introduce such a feature somewhere below the album art section of the player, or through right-click and Info section?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots:**
N/A

**System Information:**
 - Operating system: Win10
 - Strawberry Version: 0.9.2

**Comment by jonaski** [comment]
`0:00:02.347110500 24468    25b39bdb390 WARN              discoverer gstdiscoverer.c:2024:start_discovering: No URI to process`
