### ISSUE TITLE
Missing folder icons in Files pane

### ISSUE THREAD

**Issue by Perdu** [strawberrymusicplayer/strawberry#691]
**Describe the bug**
Since a few weeks ago, folder icons don't get displayed in the Files pane.
I don't know whether this is a strawberry, i3wm, qt or archlinux packaging issue, so I'm starting here.

**Screenshots:**
See: there are no icons next to folders: https://ploudseeker.com/files/tmp/Capture_d_____cran_du_2021-04-19_10-07-54.png

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.9.3-1
 - WM: i3wm
 - Theme: Fusion (doesn't work with windows them either)
 - Qt version: 6.0.3

**Additional context**
If I select "use system icons theme" in the parameters, I get dozens of similar warnings:

> 09:48:37.636 WARN  IconLoader:83                    Couldn't load icon "list-remove" from system theme icons.
> 09:48:37.637 WARN  IconLoader:83                    Couldn't load icon "dialog-ok-apply" from system theme icons.
> 09:48:37.639 WARN  IconLoader:83                    Couldn't load icon "dialog-password" from system theme icons.
> 09:48:37.639 WARN  IconLoader:83                    Couldn't load icon "dialog-warning" from system theme icons.
> 09:48:37.639 WARN  IconLoader:83                    Couldn't load icon "list-remove" from system theme icons.
> (etc)

If I don't select it, I don't get the warnings, but it doesn't work either (after restart).

**Comment by jonaski** [comment]
It works for with Qt 6.0.3 on openSUSE tumbleweed. But I see the problem on Windows with the Qt 6 version, while the Qt 5 version works.

**Comment by jonaski** [comment]
It's a Qt 6 bug: https://bugreports.qt.io/browse/QTBUG-91104
