### ISSUE TITLE
Cant launch the app in Arch Linux

### ISSUE THREAD

**Issue by ch92787830** [strawberrymusicplayer/strawberry#692]
Hello kind dev!

I just installed the strawberry package from the arch Linux official pacman repository. After installation finishes, the app cannot be launched upon clicking the app icon. Could this be a problem specific to the arch release due to the recent update?

OS: Arch with lts kernel
DE: Gnome
Version: 0.9.3

Problem: won't launch after successful installation 

Thanks for looking!

**Comment by jonaski** [comment]
Start it from a terminal and to see the error output.

**Comment by ch92787830** [comment]
Sp this was the error output:
```
$  strawberry
strawberry: error while loading shared libraries: libicui18n.so.69: cannot open shared object file: No such file or directory
```
But I have no idea how to fix it. Seems like it happened before on other apps too.

**Comment by ch92787830** [comment]
I suppose building from source can also be a solution?

**Comment by ch92787830** [comment]
Never mind, after updating the full system again, I was able to get the app working.
