### ISSUE TITLE
Filenames with certain Japanese characters directly preceding the period are not recognized as valid audio files.

### ISSUE THREAD

**Issue by Kerobyte** [strawberrymusicplayer/strawberry#693]
**Describe the bug**
Rename any audio file to "い" or "る"
For example "い.mp3" or "る.flac"

**Expected behavior**
The file should be played.

**Screenshots:**
![explorer_2021-04-20_03-45-39](https://user-images.githubusercontent.com/55901764/115329818-678c4b00-a182-11eb-9b17-9fc67a29db37.png)

**System Information:**
 - Operating system: Windows 10 Pro 20H2
 - Strawberry Version: 0.8.5 x64 and 0.9.3 x64
 - Qt Version: 6.0.3
 
 **Edit:**
 Slightly related, having "" in the file path didn't allow any file to play.
![explorer_2021-04-20_04-14-54](https://user-images.githubusercontent.com/55901764/115332027-95738e80-a186-11eb-9f2c-c3a83333dae7.png)

**Comment by jonaski** [comment]
It works fine here, both on Linux and on Windows, tested both with Qt 5 and 6.
Also '' in paths works.
What locale do you have set, and what filesystem is it?

**Comment by Kerobyte** [comment]
System locale is Japanese, file system is NTFS.

**Comment by jonaski** [comment]
I can reproduce it when setting "Language for non-unicode programs" to Japanese.

**Comment by jonaski** [comment]
This should fix the specific issue related to adding and playing the file from the Files tab, but there might be other places where it needs to be fixed too.
https://github.com/strawberrymusicplayer/strawberry/commit/9b60559855a06fb7371664a1b43a7361a8b18612

**Comment by jonaski** [comment]
I also tested adding the same folder with the file to the collection, and adding it from Playlist / Add File, those work fine too now.

**Comment by jonaski** [comment]
A new development version should be available on https://builds.strawberrymusicplayer.org/windows/ in an hour or so.
