### ISSUE TITLE
The buttons on the main window have hardcoded style

### ISSUE THREAD

**Issue by zoli111** [strawberrymusicplayer/strawberry#695]
**Describe the bug**
The title explains it.

**Expected behavior**
I think using the default button style of the widget would be a better practice.

**Screenshot**
![strawberry_screenshot](https://user-images.githubusercontent.com/57037245/115699088-9dd5f000-a365-11eb-85c1-352a8b48cd0d.png)

**System Information:**
 - Operating system: Linux
 - Strawberry Version: Latest Appimage

**Comment by jonaski** [comment]
There is no hardcoded style for these buttons
