### ISSUE TITLE
New feature: Shuffle albums in playlist

### ISSUE THREAD

**Issue by damian101** [strawberrymusicplayer/strawberry#696]
I really like the "Shuffle playlist" function, but I would often prefer my tracks to stick with other tracks from their album, in the correct track order. An additional shuffling option could deliver that.

**Comment by jonaski** [comment]
I think the "Shuffle Albums" option does this.

**Comment by yavuzmert** [comment]
Probably OP was looking at the playlist context menu for a "shuffle albums" option. Shuffle mode could be selected from the status bar. See the screenshot

![shuffle](https://user-images.githubusercontent.com/19837772/116014092-30afac80-a63c-11eb-9c17-c93c862c8df9.png)

**Comment by jonaski** [comment]
I guess a playlist option could be added to shuffle the songs by albums, I don't understand if this is something @damian101 wants to do, or asking someone to do.

**Comment by damian101** [comment]
> I guess a playlist option could be added to shuffle the songs by albums, I don't understand if this is something @damian101 wants to do, or asking someone to do.

Yes, that is what I had in mind. Not the already existing shuffle mode.

**Comment by damian101** [comment]
I very much prefer shuffling my playlist in advance over a shuffle mode. That way I can see in advance what's coming and remove music that I don't want to listen to at the moment.
But I would often prefer to keep tracks of one album together, in the right order.

**Comment by lc-guy** [comment]
This is an issue I had with old clementine as well, a shuffle-by-albums-in-advance option would be really neat.

**Comment by damian101** [comment]
@jonaski Please reopen. I would really like to see this feature someday.

**Comment by jonaski** [comment]
Open a PR.
