### ISSUE TITLE
Playing-song not getting metadata update (when metadata is changed)

### ISSUE THREAD

**Issue by madprops** [strawberrymusicplayer/strawberry#697]
Version 0.9.2

## How to reproduce
Go to a playlist.
Play one song.
Right click the song.
Click Edit Track Information.
Change the album name.
The album name is not reflected (neither in the highlighted item or the now playing information).
It's only reflected after changing to another song.

**Comment by jonaski** [comment]
Works fine here

**Comment by jonaski** [comment]
I see a problem with updating temporary metadata for reloaded songs that are outside of the collection.
Possible fix da83025
