### ISSUE TITLE
Mod bar not working in strawberry. 

### ISSUE THREAD

**Issue by linusrg1** [strawberrymusicplayer/strawberry#698]
**Describe the bug**
Modbar not working in strawberry
**To Reproduce**
Steps to reproduce the behavior.
Attempt to enable the mod bar in strawberry. It remains as the standard progress bar. 
**Expected behavior**
I expect the mod bar to appear and replace the standard progress bar. 
**Screenshots:**
**System Information:**
 - Operating system: KDE Neon
 - Strawberry Version:0.9.3

Maybe somehow my old clementine config is messing things up. Idk.

**Comment by jonaski** [comment]
Moodbar only works for local files.
What file format is it?
What setting do you got in Tools / Settings / Moodbar?

**Comment by linusrg1** [comment]
figured It out. Though just a suggestion. Why is it disabled on so many levels though? In clementine it was on by default, but in strawberry, you not only have to enable it in settings you have to enable it in the progress bar as well. If your teams  vision is to have a more simple progress bar with strawberry, why not have it enabled in the modbar section of the settings app of strawberry, but disabled in the right click menu of the progress bar? This way it would be more straight forward to enable the modbar and strawberry could still come with it disabled by default but it'll just be easier to enable.

**Comment by jonaski** [comment]
Then the option would be pointless since it would be on for everyone by default even if's not activated in the progressbar.

**Comment by linusrg1** [comment]
ok so remove the option in settings, and just make it an option in the progress bar itself. Idk why you guys made it so convoluted to activate it. In clementine it was easier to enable/disable.
