### ISSUE TITLE
Strawberry makes PulseEffects crash

### ISSUE THREAD

**Issue by KingDuckZ** [strawberrymusicplayer/strawberry#700]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
I have PulseEffects set up on my system. Whenever I start playing anything Strawberry gets stuck for a bit, then after what looks like a timeout it shows an error box ("Failed to connect to stream: Connection terminated"). At the same time I see the KDE notification that my audio device has been switched to my audio card, and I have to kill PulseEffects and restart it (PulseEffects creates its own PulseEffects(apps) audio sink which disappears when this problem occurs).

Usually a workaround for me is to play a youtube video in Firefox (which works immediately), then with the video playing I press play in Strawberry, and finally stop the Firefox video. After that Strawberry will work mostly ok, at least as long as I don't close and reopen it.

I suspect PulseEffects is not the most stable piece of software out there, but it would be good to at least figure out were the problem is coming from. I suspect Strawberry because everything else seems to work just fine, but if necessary, with more details I can open a bug report with PulseEffects.

**To Reproduce**
1. Install PulseEffects
2. Make sure it's running and its sink is selected as default
3. Open Strawberry
4. Play something in Strawberry

**Expected behavior**
Music plays through PulseEffects (audio visualisation should be visible in the PulseEffects window)

**Screenshots:**

**System Information:**
 - Operating system: Gentoo
 - Strawberry Version: 0.9.3

**Additional context**

**Comment by jonaski** [comment]
I don't understand how this can be a Strawberry bug

**Comment by KingDuckZ** [comment]
I don't know! Just wondering, since no other app causes that problem (firefox, mpv, system sounds, skype, chromium), but if it's PE then it's PE ;)

**Comment by jonaski** [comment]
I doubt there is a bug in Strawberry.
I suggest to open a bug report to PulseEffects about the crash.
Stop pulseeffects and run it in debug and report the log and backtrace to pulseeffects:
```
pulseeffects -q
export G_MESSAGES_DEBUG=pulseeffects
gdb pulseeffects
```
