### ISSUE TITLE
Weird behavior when scrobbling a song with "Live" in its title

### ISSUE THREAD

**Issue by nicemicro** [strawberrymusicplayer/strawberry#702]
**Describe the bug**
When I play the song "Dying To Live" from Poets of the Fall, it scrobbles as "Dying To" on Last.fm

**To Reproduce**
Load up the song "Dying To Live" from Poets of the Fall.
Start playing the song.
Observe the profile page on Last.fm

**Expected behavior**
Scrobbles the song to my Last.fm library as "Dying To Live".

**Screenshots:**
While playing the song:
![image](https://user-images.githubusercontent.com/63175285/116570087-f0567400-a944-11eb-890d-f70a1965c85d.png)
After the song got scrobbled:
![image](https://user-images.githubusercontent.com/63175285/116570293-1f6ce580-a945-11eb-8b93-b68667e6a97c.png)

**System Information:**
 - Operating system:
 Arch Linux
 - Strawberry Version: 0.9.3
 

**Additional context**
I guess this is might be a mechanism to properly scrobble songs that are live recording by removing the "Live" part from the title.

**Comment by jonaski** [comment]
It was something I did because Tidal annoyingly put "Live" after every single song title for some albums.
But I see that it causes problems so I'll just remove it.

**Comment by jonaski** [comment]
This should fix it: https://github.com/strawberrymusicplayer/strawberry/commit/2625d72818adea1673700fa5cd8aa54b6f7b38d9
