### ISSUE TITLE
Double click iPod in device report libgpod not compiled error(MacOS)

### ISSUE THREAD

**Issue by policeman0077** [strawberrymusicplayer/strawberry#703]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
libgpod is not compiled with MacOS version

**To Reproduce**
Plug an iPod on Mac and double click it in device tab.

**Expected behavior**
iPod should open and files should be drag and drop to iPod 

**Screenshots:**
<img width="1133" alt="Screen Shot 2021-05-01 at 10 58 52 AM" src="https://user-images.githubusercontent.com/982502/116769140-a36dbd00-aa6c-11eb-8460-feaa87bb401c.png">
<img width="1128" alt="Screen Shot 2021-05-01 at 10 58 58 AM" src="https://user-images.githubusercontent.com/982502/116769145-a9639e00-aa6c-11eb-8e74-aecbef92f218.png">

**System Information:**
 - Operating system: MacOS v11.3
 - Strawberry Version: 0.9.3

**Additional context**
I am using an iPod mini here. Don't know if iOS iPod touch have similar problem

**Comment by jonaski** [comment]
Homebrew does not have libgpod, do you want to add it?

**Comment by jonaski** [comment]
Try this one: https://builds.strawberrymusicplayer.org/macos/strawberry-0.9.3.23.ge4863c0d-x86_64-libgpod.dmg
I don't know if iPod Mini is supported. But iPod Touch definitely won't work.

**Comment by policeman0077** [comment]
> Try this one: https://builds.strawberrymusicplayer.org/macos/strawberry-0.9.3.23.ge4863c0d-x86_64-libgpod.dmg
> I don't know if iPod Mini is supported. But iPod Touch definitely won't work.

Thanks man! you rock. Now it works flawlessly. 
<img width="1133" alt="Screen Shot 2021-05-05 at 12 04 43 PM" src="https://user-images.githubusercontent.com/982502/117095870-2a3ad680-ad9a-11eb-964a-98b21d151142.png">
