### ISSUE TITLE
Tidal streaming stopped working

### ISSUE THREAD

**Issue by mroovaa** [strawberrymusicplayer/strawberry#704]
**Describe the bug**
Unable to use or log in to Tidal.
With API Token it says:
- Authentication failure: Client not found (401) (8003)  or:
- Error transferring https://api.tidalhifi.com/v1/login/username - server replied: Forbidden (201)
With OAuth:
- Your OAuth2 client configuration is not correct. Please check with TIDAL Partner Support.

**System Information:**
 - Operating system: Ubuntu 18.04
 - Strawberry Version: 0.9.3

**Comment by jonaski** [comment]
It works fine here. Tested both OAuth login, search and streaming.
Maybe a temporary problem at a Tidal mirror, or the client ID you use is expired.
