### ISSUE TITLE
Multiple requests to streaming server

### ISSUE THREAD

**Issue by KingDuckZ** [strawberrymusicplayer/strawberry#705]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
I've installed a Navidrome server (Airsonic-compatible) and set up my Strawberry to stream from it. I noticed in the server log stuff like this:

```
time="2021-05-02T15:49:44Z" level=info msg="Streaming file" artist=JYNXT bitRate=256 cached=false format=ogg originalBitRate=192 originalFormat=mp3 title="Perverted Mind" transcoding=true user=michele
time="2021-05-02T15:49:45Z" level=error msg="Error sending transcoded file" error="write tcp 127.0.0.1:4533->127.0.0.1:56930: write: broken pipe" id=b76b6327079b53d38505a9991e69535e requestId=<cut>/n4CjZEQH3S-000147
time="2021-05-02T15:49:50Z" level=info msg="Streaming file" artist=JYNXT bitRate=256 cached=true format=ogg originalBitRate=192 originalFormat=mp3 title="Perverted Mind" transcoding=true user=michele
time="2021-05-02T15:53:15Z" level=info msg="Streaming file" artist=JYNXT bitRate=256 cached=true format=ogg originalBitRate=192 originalFormat=mp3 title="Perverted Mind" transcoding=true user=michele
```

This doesn't seem to happen with Ultrasonic (the Android app).

**To Reproduce**
1. Setup a Navidrome server
2. Connect to it through Strawberry
3. Play some song
4. Check the Navidrome logs

**Expected behavior**
I think there should only be one entry in the Navidrome logs

**System Information:**
 - Operating system: Gentoo (client) / Archlinux (server)
 - Strawberry Version: media-sound/strawberry-0.9.3

**Additional context**
Some entries appear up to 4 times in the logs. With Ultrasonic this never happens, which makes me think of a Strawberry issue.

**Comment by jonaski** [comment]
What does the logs mean?

**Comment by jonaski** [comment]
If it's connections, then 3 seems correct when loading the next song.
I'm guessing the first one is the stream discoverer, the error is probably because this connection is dropped immediately since it's only used to detect the stream.
The second is the preloading, and the third could be the start of the streaming because it usually happen circa 5 seconds after the preloading.

**Comment by jonaski** [comment]
I'm closing this since I can't really answer questions about logging in a different application. Different applications might request the stream several times because of different features such as stream detection and gapless playback.
