### ISSUE TITLE
Subsonic Server Does not Support Seeking Error

### ISSUE THREAD

**Issue by DOFfactory** [strawberrymusicplayer/strawberry#706]
**Describe the bug**
Using Strawberry for connecting to my Subsonic server. Often I pause the song, and then after the connection is gone, I occasionally press the play button. This results in playing the remaining parts of the song that are in cache (2-3 seconds), and then an error window pops up (see below).

**To Reproduce**
Start playback on Subsonic, pause, leave it until the connection is dropped, start the playback.

**Expected behavior**
The aforementioned error window is super-annoying, besides the fact that it is not very informative. Would it be please possible to disable it in the Settings, or at least make it less obtrusive? Due to this window I always lose focus of the main windows app, and although I am well aware of the limitations of my Subsonic server, it is not informative anymore.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10846169/116970997-3438d880-acb9-11eb-833f-86a6a2aa0e64.png)

**System Information:**
 - Operating system: Windows 10
 - Strawberry Version: 0.9.3

**Comment by jonaski** [comment]
I agree that the dialog can be annoying and intrusive sometimes, but it is important to show errors like this for the user, we can't just ignore it. A better approach might be to use system notifications with some additional logging for all errors, however I don't have time to do that.

**Comment by DOFfactory** [comment]
Thank for your reply @jonaski, I did not want to question the relevance of **error** messages in general. However, I would still justify my request with the fact that I already _know_ that my subsonic server does not support seeking (I actually do not know any SubSonic on-the-fly playback implementation that supports it). Hence, this should be more of a **warning** than an error with no utility, meaning there should be an option like "do not show this error in the future". 

Is it possible to list it as a warning instead of an error and then be able to switch it off?
