### ISSUE TITLE
Shuffle prioritizes recently added songs 

### ISSUE THREAD

**Issue by madprops** [strawberrymusicplayer/strawberry#707]
v0.9.3

I guess this is by design. Shuffle mode will play more often the songs which I just added to the playlist. I don't really like this behavior, when I add songs to the playlist I just expect them to be played eventually sometimes instead of very frequently. Re-shuffling after adding music to the playlist could be considered. (Hopefully in an efficient way, i.e don't reshuffle 12 times after adding a 12 track album).

Some related discussion: https://github.com/clementine-player/Clementine/issues/5201

**Comment by jonaski** [comment]
Try with this fix  316a3d5

**Comment by jonaski** [comment]
Unfortunately that breaks the back button so I can't do it. I see now immediate easy fix for this.

**Comment by insunaa** [comment]
Can I request a `true random` shuffle as feature? Hearing the same song multiple times in a row on occasion is a feature, not a bug.
