### ISSUE TITLE
[Pipewire] "Fade in on resume" causes audible stutters

### ISSUE THREAD

**Issue by Mershl** [strawberrymusicplayer/strawberry#709]
**Describe the bug**
Using `Fade out on pause / fade in on resume` with the default value `250 ms` has audible stutters on pipewire (using pulseaudio or ALSA as backend in strawberry). The fade in stutters 2 times (2 slight cracks are audible), then plays back at full volume - a fade in effect is not noticable.

The stutter effect gets weaker and weaker by raising the Fade time. Raising the value to 2000 ms fades in and out correctly most of the time - the expected fade effect is audible on pause and resume.

Disabling the "Fade in on resume" feature perfectly pauses and resumes the track with no audible stutters.

**To Reproduce**
Enable `Fade out on pause / fade in on resume` with the default value `250 ms`.
Pause and Resume a track while using Pipewire with PA or ALSA backend.

**Expected behavior**
The fade in/out effect was very smooth on Fedora 33 with Strawberry 0.8.5 and Pulseaudio.

**System Information:**
 - Operating system: Fedora 34
 - Strawberry Version: 0.9.2
 - Pipewire Version: 0.3.27

**Comment by jonaski** [comment]
Similar problem reported here: https://github.com/strawberrymusicplayer/strawberry/issues/632
Did you try to report this to Fedora or pipewire?
If this is a bug in Strawberry, then I'd like to have some more details of why.

**Comment by jonaski** [comment]
I don't think this is a bug in Strawberry, since it works with ALSA and PulseAudio.
