### ISSUE TITLE
Ogg Opus files not listed in collection (but play fine otherwise)

### ISSUE THREAD

**Issue by Ambrevar** [strawberrymusicplayer/strawberry#712]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
Ogg Opus files are not listed in the collection.   They play fine when added via the "Files" tab.

**To Reproduce**
- Add an Ogg Opus file to your collection.
- Rescan the collection.

**Expected behavior**
See the Ogg Opus file listed in the collection

**System Information:**
 - Operating system: Guix
 - Strawberry Version: 0.9.3

**Additional details**

In the playlist view, the Ogg Opus file only shows its metadata when played.  As soon as another track is playing, the metadata disappear from the columns.

**Comment by jonaski** [comment]
It works fine here.
What extension does the files have?
Can you send me an example file?

**Comment by jonaski** [comment]
Btw, I just remembered. If they have .ogg extension, it won't work, since then TagLib will try to identify the files are Ogg Vorbis and reject them, they need to be .opus. In that case it's still possible to add them to the playlist, but without tags.
If you have a problem with this behavior you need to take it up with the TagLib project.

**Comment by Ambrevar** [comment]
Indeed, the problem is the extension, renaming to `.opus` works.

I've reported upstream: https://github.com/taglib/taglib/issues/1011.
