### ISSUE TITLE
Smart playlists with Subsonic

### ISSUE THREAD

**Issue by dbogdanov** [strawberrymusicplayer/strawberry#716]
Currently, smart playlists are not supported for Subsonic.

Clementine has similar functionality: https://github.com/clementine-player/Clementine/pull/5138

**Comment by jonaski** [comment]
The Subsonic implementation is very different from the one in Clementine.
I don't plan to add it, I don't even use Subsonic.
I'm not accepting more feature requests here due to lack of contributors.
