### ISSUE TITLE
right click triggers directly the first action

### ISSUE THREAD

**Issue by Michele64** [strawberrymusicplayer/strawberry#717]
**Describe the bug**
right click sometimes triggers directly the first action instead of showing list

**To Reproduce**
right click any item in any section of the sidebar

**Expected behavior**
should show menu

**Screenshots:**
no screenshot possible since it happens unecpectedly 

**System Information:**
 - Operating system: Kubuntu 20.10
 - Strawberry Version: 0.9.3

**Comment by jonaski** [comment]
I can't reproduce this behavior. What action does it trigger?

**Comment by Michele64** [comment]
that's the strange thing, I cannot reproduce it, it just happens irregularly

**Comment by jonaski** [comment]
I'm not really sure what to do with this, I've never seen this problem.
It might be a issue related to a specific Qt style.
Try setting the style to Fusion in Settings / Appearance and restart Strawberry.
