### ISSUE TITLE
Could NOT find Qt6LinguistTools (missing: Qt6LinguistTools_DIR)

### ISSUE THREAD

**Issue by martinkg** [strawberrymusicplayer/strawberry#720]
Hi,

compiling last commit  aa9f972ccfb0fa793fb3b99f73dc82f5016884fe on Fedora 34 with qt6 support

/usr/bin/cmake -S . -B x86_64-redhat-linux-gnu -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_WERROR=OFF -DUSE_SYSTEM_TAGLIB=OFF -DBUILD_WITH_QT6=ON

prints this error message:
Could NOT find Qt6LinguistTools (missing: Qt6LinguistTools_DIR)

but the necessary package qt6-linguist is installed.

# rpm -ql qt6-linguist
/usr/bin/lconvert-qt6
/usr/bin/linguist-qt6
/usr/bin/lrelease-qt6
/usr/bin/lupdate-qt6
/usr/lib64/lprodump
/usr/lib64/lprodump-qt6
/usr/lib64/lrelease-pro
/usr/lib64/lrelease-pro-qt6
/usr/lib64/lupdate-pro
/usr/lib64/lupdate-pro-qt6
/usr/lib64/qt6/bin/lconvert
/usr/lib64/qt6/bin/lconvert-qt6
/usr/lib64/qt6/bin/linguist
/usr/lib64/qt6/bin/linguist-qt6
/usr/lib64/qt6/bin/lrelease
/usr/lib64/qt6/bin/lrelease-qt6
/usr/lib64/qt6/bin/lupdate
/usr/lib64/qt6/bin/lupdate-qt6
/usr/share/applications/qt6-linguist.desktop
/usr/share/icons/hicolor/128x128/apps/linguist-qt6.png
/usr/share/icons/hicolor/16x16/apps/linguist-qt6.png
/usr/share/icons/hicolor/32x32/apps/linguist-qt6.png
/usr/share/icons/hicolor/48x48/apps/linguist-qt6.png
/usr/share/icons/hicolor/64x64/apps/linguist-qt6.png
/usr/share/qt6/phrasebooks/danish.qph
/usr/share/qt6/phrasebooks/dutch.qph
/usr/share/qt6/phrasebooks/finnish.qph
/usr/share/qt6/phrasebooks/french.qph
/usr/share/qt6/phrasebooks/german.qph
....

**Comment by martinkg** [comment]
Problem solved, qt6-qttools-devel was missing.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
For Debian it would be `qt6-tools-dev` package
