### ISSUE TITLE
SuSE Buildservice not building for Fedora 34

### ISSUE THREAD

**Issue by lemonzest79** [strawberrymusicplayer/strawberry#722]
OpenSuSE Buildservice is not building for Fedora 34 as it currently says "unresolvable: have choice for pkgconfig(openssl) >= 0.9.8 needed by libimobiledevice-devel: openssl-devel openssl1.1-devel"

If this could be fixed that would be wonderful :)

Many thanks.

**Comment by jonaski** [comment]
Fixed now, but might take a while to get published.
