### ISSUE TITLE
qt6 themes

### ISSUE THREAD

**Issue by Amaunator** [strawberrymusicplayer/strawberry#723]
app ver: 0.9.3-2
hello, I am on Garuda Kde (arch based) 
it is using kvantum-dark theme. 
qt6 compile of the app (from aur or community repos) are not using system icons/kvantum theme. 
I am unable to set pick it from the settings apperance menu. 
qt5 compile of strawberry got the theme visible in the menu.
qt6ct app shows: "The QT_QPA_PLATFORMTHEME environment variable is not set (required value: qt6ct) "
so i am not using it.

**Comment by jonaski** [comment]
You need to install additional styles for Qt 6 for them to be available in the appearance settings.
Ask Garuda about this.
