### ISSUE TITLE
Strawberry appears not to use ReplayGain for Musepack (MPC) files

### ISSUE THREAD

**Issue by MisterHenryDCase** [strawberrymusicplayer/strawberry#725]
**Describe the bug**
Strawberry appears not to use ReplayGain for Musepack (MPC) files, making most of them play much louder than non-MPC songs with ReplayGain information.

**To Reproduce**
Take a song that's been mastered way too loud, like most songs today.
Encode the song once as MP3 and once as MPC and apply ReplayGain tags to both of them (e.g. with foobar2000).
Set Strawberry's ReplayGain mode to "Radio", then play both songs in sequence.
The MPC song will be noticeably louder.

**Expected behavior**
Strawberry should apply ReplayGain tags embedded into the song, and play all songs at equal loudness.

**System Information:**
 - Operating system: Linux 5.10
 - Strawberry Version: 0.9.3

**Additional context**
-

**Comment by jonaski** [comment]
Strawberry does not read replaygain tags directly, it uses replaygain through gstreamer.
My guess is that gstreamer does not support replaygain for MusePack yet as it's a "Bad" plugin in gstreamer.

**Comment by MisterHenryDCase** [comment]
Thanks for the information.
I'd open an issue with gstreamer, but given that it already has 3700 open ones right now, converting the last few MPC tracks I have is probably a more realistic option...
