### ISSUE TITLE
Protecting the user from accidently deleting her library

### ISSUE THREAD

**Issue by gerion0** [strawberrymusicplayer/strawberry#726]
**Describe the bug**
When opening Strawberry while the library folder is _not_ present (e.g. because it resides on an external drive or a network drive, in my case autofs), Strawberry deletes the entire library together with all playlists and ratings. Reopening leads to a library rescan (long process), playlists are recovered but all ratings are lost.

**To Reproduce**
1. Load your library.
2. Close Strawberry.
3. Remove the library folder (unmount/unplug/network disconnect/...)
4. Open Strawberry (library goes away in seconds).

**Expected behavior**
Don't know. Strawberry's behaviour is technically correct. However, a warning etc. would be nice that the library folder itself is not present and if it should be deleted. Maybe it is even possible to change the root location of the library in this case.

**System Information:**
 - Operating system: Gentoo Linux
 - Strawberry Version: 0.9.3

**Additional context**
I'm pretty sure this is partly my fault: I have activated an automatic update scan on the start of strawberry.

I also see this changelog point for 0.9.3. This sounds like the solution I searched for, but I have experienced the above behaviour:
> Fix rescan when collection directory is removed and readded.

My whole point is that the user probably doesn't want to remove her entirely library at program start, so please let Strawberry ask in this case.

**Comment by jonaski** [comment]
There is a setting for this for that purpose: "Mark disappeared songs unavailable" under Tools / Settings / Collection.
