### ISSUE TITLE
Strawberry Fails RME "Bit Test" feature that checks for "bit perfect" audio.

### ISSUE THREAD

**Issue by NielsMayer** [strawberrymusicplayer/strawberry#730]
In evaluating RME Babyface PRO FS and ADI-2 FS R on Linux (fully compatible when placed in "class compliant mode") , I decided to run their "bit test" feature using their files http://www.rme-audio.de/download/bit_test_wavs.zip . (See "Bit Test"" section in https://www.rme-audio.com/adi-2-dac.html for details).

After  seeing success running the files via 
`mpv --audio-device=alsa/hw:Pro58840210 --no-audio-display *.wav`
which displays:
![20210706_123508_HDR](https://user-images.githubusercontent.com/6306083/124657000-c6469400-de56-11eb-9f66-0f058044a6d2.jpg)

I tried using strawberrry and was unable to get the above "success" indication at any of the provided sample rates (44.1k, 96k, 192k) or depths (16, 24, or 32 bits).

I am using Strawberry 0.9.3 on Kubuntu 20.04.2 with back-end pointing to exact same card and configuration as used for MPV above, "hw:Pro58840210" ...

The following is displayed on playback in the "Context" tab:
![image](https://user-images.githubusercontent.com/6306083/124658425-99937c00-de58-11eb-854e-68927d0191f7.png)

Each track produces output like the following from strawberry:

```
12:52:19.390 DEBUG GstEngine:969                    Got stream info for "file:///media/smb/Music/RME-BitTest/192_32_adi2pro_bittest%204s.wav:" "Wav"
12:52:22.932 DEBUG MainWindow:1313                  Song changed to "" "" ""
12:52:22.948 INFO  MoodbarLoader:120                Loading cached moodbar data for "/media/smb/Music/RME-BitTest/192_32_adi2pro_bittest 4s.wav"
12:52:22.948 DEBUG Player:623                       Playing song "" QUrl("file:///media/smb/Music/RME-BitTest/192_32_adi2pro_bittest 4s.wav")
12:52:22.948 DEBUG PlaylistBackend:325              Saving playlist 21
12:52:22.949 DEBUG MainWindow:1313                  Song changed to "" "" "192 kHz 32 bit ADI-2 Pro Bit Test 4s"
12:52:22.952 INFO  MoodbarLoader:120                Loading cached moodbar data for "/media/smb/Music/RME-BitTest/192_32_adi2pro_bittest 4s.wav"
```

Whereas MPV outputs the following for those files (indicating some details about ALSA parameters for this hardware). Note that the sound device is configured in "multichannel class compliant mode" so it presents an 8 channel output device, of which the first to used channels go to the mains outputs.

```
npm@zenrise:~/Music/RME-BitTest$ mpv --audio-device=alsa/hw:Pro58840210 --no-audio-display *.wav
Playing: 192_16_adi2pro_bittest 4s.wav
(+) Audio --aid=1 (pcm_s16le 2ch 192000Hz)
File tags:
Date: 17.03.2018
Title: 192 kHz 16 bit ADI-2 Pro Bit Test 4s
[ao/alsa] Asked for 2 channels, got 8 - fallback to fl-fr-na-na-na-na-na-na.
[ao/alsa] Asked for 2 channels, got 8 - fallback to fl-fr-na-na-na-na-na-na.                                                                 
AO: [alsa] 192000Hz fl-fr-na-na-na-na-na-na (stereo) 8ch s32
A: 00:00:03 / 00:00:03 (94%) Cache: 0.0s/19KB

Playing: 192_24_adi2pro_bittest 4s.wav
(+) Audio --aid=1 (pcm_s24le 2ch 192000Hz)
File tags:
Date: 17.03.2018
Title: 192 kHz 24 bit ADI-2 Pro Bit Test 4s
A: 00:00:03 / 00:00:03 (95%) Cache: 0.0s

Playing: 192_32_adi2pro_bittest 4s.wav
A: 00:00:03 / 00:00:03 (95%) Cache: 0.0s
(+) Audio --aid=1 (pcm_s32le 2ch 192000Hz)
File tags:
Date: 17.03.2018
Title: 192 kHz 32 bit ADI-2 Pro Bit Test 4s
A: 00:00:03 / 00:00:03 (94%) Cache: 0.0s/43KB

Playing: 441_16_adi2pro_bittest 4s.wav
(+) Audio --aid=1 (pcm_s16le 2ch 44100Hz)
File tags:
Date: 17.03.2018
Title: 44.1 kHz 16 bit ADI-2 Pro Bit Test 4s
[ao/alsa] Asked for 2 channels, got 8 - fallback to fl-fr-na-na-na-na-na-na.
[ao/alsa] Asked for 2 channels, got 8 - fallback to fl-fr-na-na-na-na-na-na.                                                                 
AO: [alsa] 44100Hz fl-fr-na-na-na-na-na-na (stereo) 8ch s32
A: 00:00:03 / 00:00:04 (95%) Cache: 0.0s
```

**Comment by jonaski** [comment]
Is the stereo balancer, equalizer and replaygain off?
Strawberry uses gstreamer, not mpv. So I'm not sure why you compare with mpv and not gst-launch?
Something like this should resemble the pipeline used in Strawberry:
gst-launch-1.0  filesrc location="file.wav" ! decodebin ! audioconvert ! alsasink device="hw:0,0"

**Comment by jonaski** [comment]
Closing this because of lack of feedback, and no way to test it myself without having the same DAC.
