### ISSUE TITLE
Add radiobrowser provider to Radios new feature

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#732]
First of all thank you for adding Radios into Strawberry, it's a good start. I actually have a curated playlist just for radios, so I use strawberry to listen radio stations very much.

I would encourage to add https://api.radio-browser.info/ . I don't know how difficult it would be, but it was recently added into Clementine this is the pull request https://github.com/clementine-player/Clementine/pull/6920

Thanks!

**Comment by jonaski** [comment]
This has been asked previously: https://github.com/strawberrymusicplayer/strawberry/issues/257
I had a look at the API but didn't find a way to query by quality, so you have to parse thousands of channels.

**Comment by segler-alex** [comment]
But even just letting the use query the api for specific names is useful in itsself, even if you get back a stream with lower bitrate. some streams do not have high bitrate available, some streams on the earth are located in coutries that have bad network.
therefore querying by bitrate should only be an option for the user. not mandatory.
