### ISSUE TITLE
there is no sound with strawberry 

### ISSUE THREAD

**Issue by Heny67** [strawberrymusicplayer/strawberry#733]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
No sound is heard during playback. The music starts to see this also in the attachment, the process is signaling the progress, but there is no sound. Next to it you can hear Vlc.
Everything is fine with the sound settings. With the same settings, Vlc can be heard without any problems. Web content can only be heard on the stawberry without making any sound. 

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots:**
![Vágólap01](https://user-images.githubusercontent.com/80578702/126036500-b4964e9b-63c6-4283-b78d-144b94780c33.jpg)

**System Information:**
 - Operating system:ubuntu mate 20.04
 - Strawberry Version:0.9.3-267-ge0bb79b2

**Additional context**

**Comment by Heny67** [comment]
Hi!
Deleting strawberry.conf solved the problem.

**Comment by jonaski** [comment]
You probably had the wrong output device set in the backend settings.
