### ISSUE TITLE
[Feature request]: Combine AND and OR in dynamic playlists

### ISSUE THREAD

**Issue by desputinski** [strawberrymusicplayer/strawberry#734]
Hi, I think it is not implemented in Strawberry, so I'll just post the following feature request here:

In Amarok 1.4 it was possible to combine AND- and OR-queries in Dynamic Playlists. So for example:
These three queries in combination:
-Genre contains "pop" AND
-Rating higher than 4 AND
-Year is before 1979

And in addition this one OR-query
-Comment contains "Party"

**Comment by jonaski** [comment]
I don't do feature requests, I usually do whatever I feel inspired to do myself.
If someone wants to participate and need something to do, and for some reason can't look at the forum to find something, then I guess I'm willing to change the policy.
