### ISSUE TITLE
Hi, strawberry support MQA?

### ISSUE THREAD

**Issue by Lunatic1985** [strawberrymusicplayer/strawberry#736]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots:**

**System Information:**
 - Operating system:
 - Strawberry Version:

**Additional context**

**Comment by jonaski** [comment]
No. This has been asked plenty of times before.
