### ISSUE TITLE
Strawberry crashes when trying to play MP3 files

### ISSUE THREAD

**Issue by damian101** [strawberrymusicplayer/strawberry#742]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
When trying to play back an MP3 file, Strawberry just crashes. FLAC works fine.

**System Information:**
 - Operating system: RebornOS (Arch Linux)
 - Strawberry Version: 0.9.3

**Additional context**
This strawberry version worked just fine before I updated my system. With `strawberry-git`from the AUR I have the same issue.

**Comment by jonaski** [comment]
It works here.
Do a backtrace with GDB, see: https://github.com/strawberrymusicplayer/strawberry/wiki/Backtrace

**Comment by damian101** [comment]
```
Thread 76 "mpegaudioparse0" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffea5ffb640 (LWP 16915)]
0x00007ffff4fcfd22 in raise () from /usr/lib/libc.so.6
```

**Comment by jonaski** [comment]
That's not a backtrace, but at least it shows that it's aborting in gstreamer mpegaudioparse0, does not look like a strawberry bug to me.
Does this work?
`gst-launch-1.0 filesrc location=file.mp3 ! mpegaudioparse ! mpg123audiodec ! alsasink device=hw:0,0`

**Comment by damian101** [comment]
@jonaski yes, that command works

**Comment by damian101** [comment]
same issue with AAC

**Comment by jonaski** [comment]
I installed rebornOS in a Virtualbox, still can't reproduce the issue with MP3.
Can you send me MP3 file that doesn't play?

**Comment by damian101** [comment]
> I installed rebornOS in a Virtualbox, still can't reproduce the issue with MP3.
> Can you send me MP3 file that doesn't play?

none of them play, I can encode a new MP3 file with LAME and it doesn't play.

But it's good to know that the issue doesn't affect all Arch or RebornOS systems.

**Comment by jonaski** [comment]
Well I know there are many users of Strawberry on Arch, but I don't know about RebornOS, you are the only one who reported this.
So it's either specific to your MP3's, or it's specific to your installation, inconsistencies in packages.
Are you using the Reborn LTS or the rolling release? I only tested with the rolling release and installed strawberry from the regular package.

**Comment by damian101** [comment]
> Well I know there are many users of Strawberry on Arch, but I don't know about RebornOS, you are the only one who reported this.
> So it's either specific to your MP3's, or it's specific to your installation, inconsistencies in packages.
> Are you using the Reborn LTS or the rolling release? I only tested with the rolling release and installed strawberry from the regular package.
> 

RebornOS is just Arch Linux with an additional repository and a graphical installer. The LTS option in the GRUB menu just boots RebornOS with the LTS kernel. Kernel choice shouldn't make a difference here.

I too have installed Strawberry from the Arch Linux Community repository. I also tried building Arch Linux from git trough the AUR, but it had the same issue.

I think I have an idea what could cause the issue...

**Comment by damian101** [comment]
Found the problem, replacing `ffmpeg` with `ffmpeg-full` somehow causes it.

**Comment by jonaski** [comment]
OK. Then I'm guessing that the gstreamer livav plugins are probably built with the ffmpeg package, and there are compatibility problems with the ffmpeg-full package when using gstreamer.
In any case it isn't a strawberry bug, so report this issue to rebornos, or arch.
