### ISSUE TITLE
Right click menu selects on second click - Same issue as clementine's #6321

### ISSUE THREAD

**Issue by daniellga** [strawberrymusicplayer/strawberry#747]
Hi,

Just to report I am having the same issue as seen on Clementine. I am using MX Linux.

https://github.com/clementine-player/Clementine/issues/6321

System:    Host: <filter> Kernel: 5.8.0-3-amd64 x86_64 bits: 64 compiler: N/A 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.8.0-3-amd64 
           root=UUID=<filter> ro quiet splash 
           Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 
           Distro: MX-19.4_ahs_x64 patito feo November 11  2020 
           base: Debian GNU/Linux 10 (buster) 

Strawberry version 0.9.3

**Comment by jonaski** [comment]
This sounds like system-related issue, Qt style related issue, or a defective mouse.
Try setting the Qt style in the appearance settings to fusion.

**Comment by daniellga** [comment]
Changing the appearance to fusion didn't seem to work. Also tried another mouse (a different type) to no avail. It seems related with right clicking and moving the pointer right after.

**Comment by daniellga** [comment]
It seems this problem is reproducible outside of clementine and strawberry as well (clementine and strawberry are way more sensible to it). I will ask the OS forum to see what they say about it.

**Comment by daniellga** [comment]
Seems to be a XFCE configuration after all. I am putting the link here so other people can find when they have the same problem.

https://forum.mxlinux.org/viewtopic.php?f=104&t=65988&p=648810#p648810
