### ISSUE TITLE
Subsonic Update runs but no albums appear (large database)

### ISSUE THREAD

**Issue by megalithicportal** [strawberrymusicplayer/strawberry#750]
Hello, I can connect to my Subsonic server OK (via http:// port 8080) and run Refresh catalogue 
It says Retrieving songs for 10840 albums (yes rather a lot!)
and Retrieving album covers for 1861 albums.
This runs through to 100% and seems to complete OK but no albums appear. 
It says 'Your Internet Collection is Empty'

But looking in 
/home/asb/.local/share/strawberry/strawberry/
I now have over 1800 album covers downloaded into the album covers folder and the strawberry.db is 43.5MB (!)

I haven't used Strawberry to play local files at all.
I'm on OpenSuse 15.2 (fresh install)
Strawberry 0.9.3 instelled from the OpenSuse packages
Qt version 5.12.7.

What debug can I provide to help with this?
Have I overloaded it with too many albums?
Many thanks
Andy

**Comment by jonaski** [comment]
This is currently no progressbar or status for updating the database so when the progress bar is finished it's updating the DB.
It can take a while for such a large collection. Nothing will be added to the DB before it finishes since SQL transaction is used. How long did you wait?

**Comment by megalithicportal** [comment]
Thanks very much for the efforts on this
