### ISSUE TITLE
"Global Shortcuts" is grayed out on linux

### ISSUE THREAD

**Issue by CodeCubeNeo** [strawberrymusicplayer/strawberry#753]
The title says it all. Is there a way to turn this on, or is this limited or what??
An answer will be well appreciated.

**Comment by jonaski** [comment]
It depends on the desktop environment, it support Gnome, KDE and Cinnamon, and requires that the appropriate backend is installed. MATE should work with the Gnome backend.
You can install the KDE backend (kglobalaccel) on any desktop environment to enable shortcuts (I use this on XFCE).
X11 shortcuts can be enabled too if you use another desktop environment, but on a wayland session this option is always disabled.
But this isn't a support forum, so use: https://forum.strawberrymusicplayer.org/ for any more questions.
