### ISSUE TITLE
Fix clang-tidy issues

### ISSUE THREAD

**Issue by EmmanuelMess** [strawberrymusicplayer/strawberry#758]
There are quite a few clang-tidy warning in my IDE (CLion), should these be fixed?

**Comment by jonaski** [comment]
Which warnings specifically?

**Comment by EmmanuelMess** [comment]
There are a lot, but `modernize-loop-convert`, `cppcoreguidelines-pro-type-static-cast-downcast`, `cppcoreguidelines-narrowing-conversions`, `modernize-pass-by-value` seem to be most of the issues that have an impact on the execution, other issues seem to be purely visual, like using auto instead of the type when initialize a variable by calling an object constructor.

**Comment by jonaski** [comment]
I know about loop-convert, but I prefer to have the loops like they are in those places. Also, I prefer not to use auto.
But you can fix `static-cast-downcast` and `narrowing-conversions` if you want. I know there is a couple of integer/math related ones that probably should be fixed too, divide by zero at least one place.
I'm not sure about `modernize-pass-by-value`, let's wait with that for now.

**Comment by jonaski** [comment]
There is a few `bugprone-incorrect-roundings`, fix for those are welcome.
