### ISSUE TITLE
can't input  chinese character into Strawberry's search box

### ISSUE THREAD

**Issue by strongWei** [strawberrymusicplayer/strawberry#759]
Strawberry version: AppImage 0.9.3-Qt5
Qt version: 5.15.2
Linux versoin: 5.11.0-27-generic
System version: Ubuntu 20.04.2 LTS

I can't input  chinese character into Strawberry's search box, but I can paste chinese character into search box
My keyboard input method system is ibus, I can switch input method in other Qt Appimage Program, such as qBittorrent,
except Strawberry.
![2021-09-11_17-24](https://user-images.githubusercontent.com/11831357/132943147-027208e3-7f66-442a-870c-959997e7a2fc.png)
 
How can I fix it? tx

**Comment by jonaski** [comment]
ibus support is in a separate plugin in Qt and the AppImage does not have that plugin. Try the deb package or PPA repo.
