### ISSUE TITLE
Muffled, low-quality sound output despite the file's bitrate/sample rate

### ISSUE THREAD

**Issue by ThoriumTextile** [strawberrymusicplayer/strawberry#763]
**Describe the bug**
Whenever i try to play any music/audio file, the sound output sounds compressed, although clear.
Other media players like mpv do not have this issue.

**To Reproduce**
On Fedora 34, this didn't happen, but i'm not sure if this is an OpenSUSE issue.
To reproduce, simply install Strawberry and play any audio file (i should probably specify that i'm also using Pulseaudio).

**Expected behavior**
Sound should be clear, and follow the bitrate/sample rate/overall quality.

**Screenshots:**
N/A

**System Information:**
 - Operating system: Opensuse Tumbleweed, running 5.14.0-1-default x86_64 x86_64 x86_64 GNU/Linux
 - Strawberry Version: 0.9.3-1.4

**Additional context**
Additionally, Strawberry does not follow the system's icon theme (papirus-dark in my case). It did on Fedora 34.

**Comment by jonaski** [comment]
This almost certainly is a configuration issue and not a bug in strawberry.
The only thing that could cause this in strawberry would be if the analyzer is configured to some strange setting.
I also use openSUSE and do not have this issue.
This is more likely a configuration issue with either alsa, pulseaudio or pipewire.
I suggest that you try to disable pipewire and pulseaudio and see if the same issue occurs directly to ALSA.
If you don't figure it out, try seeking help in the openSUSE forums or mailinglist.

**Comment by ThoriumTextile** [comment]
> This almost certainly is a configuration issue and not a bug in strawberry.
> The only thing that could cause this in strawberry would be if the analyzer is configured to some strange setting.

I looked into it and i can't find anything about the analyzer

> I also use openSUSE and do not have this issue.
> This is more likely a configuration issue with either alsa, pulseaudio or pipewire.

Might be, i have a /home partition that i shared between fedora and opensuse. If that's the case, do i have to just delete strawberry's config folder?

> I suggest that you try to disable pipewire and pulseaudio and see if the same issue occurs directly to ALSA.

Not sure if it matters but i set gstreamer to use that ALSA output, and i also installed all gstreamer plugins. Also i'd like to mention that this doesn't happen in other music players like mpv or DeadBeeF.

**Comment by jonaski** [comment]
Sorry, meant the equalizer of course.

**Comment by ThoriumTextile** [comment]
> Sorry, meant the equalizer of course.

I didn't touch anything on it.
Guess i'll use deadbeef in the meantime.

**Comment by jonaski** [comment]
If pipewire is enabled, it will still be used even if you select ALSA as the output
Disable pipwire: https://en.opensuse.org/openSUSE:Pipewire
Disable pulseaudio: https://en.opensuse.org/SDB:Pulseaudio

**Comment by ThoriumTextile** [comment]
> If pipewire is enabled, it will still be used even if you select ALSA as the output
> Disable pipewire: https://en.opensuse.org/openSUSE:Pipewire
> Disable pulseaudio: https://en.opensuse.org/SDB:Pulseaudio

Alright, this is really weird: turns out that for some reason, OpenSUSE has both pipewire and pulseaudio installed, so i removed pipewire (which wasn't enabled anyway) and enabled pulseaudio instead.
This didn't solve anything, but then i thought: "what if strawberry is still reading Fedora's config?". So i deleted strawberry's .config folder and now it works!
Sorry for being mean, this is a great player too!
Though for some reason, strawberry still insists on using another icon theme, instead of the system's Papirus-Dark (i checked the "use system icons" setting).
