### ISSUE TITLE
Mood bar and album cover background disappear when automatically switching to next track in playlist

### ISSUE THREAD

**Issue by e3bc54b2** [strawberrymusicplayer/strawberry#767]
**Describe the bug**
I usually play smart playlists (newest/Dynamic random) with dynamic mode ON. I have mood bar and album cover as background settings enabled as shown in screenshot. When I start/switch to a track manually, either by clicking on track or using next/prev buttons, mood bar and  background album cover appear fine (screenshot no. 1), However, if the next track on playlist starts automatically after previous track is complete, the mood bar disappears (normal OS progress bar appears) and album cover background disappears (switches to no background (screenshot no.2)

**To Reproduce**
1. Enable mood bar and album cover as background settings
2. Prepare any playlist
3. Let one track complete and move automatically on to next track

**Expected behavior**
Mood bar and background cover should switch over to those for next track instead of disappearing.

**Screenshots:**
![image](https://user-images.githubusercontent.com/24254289/133110989-78797e20-34c0-4c5d-96aa-5a388a98f380.png)

![image](https://user-images.githubusercontent.com/24254289/133111103-99585be9-3774-4636-a847-65278aa8f36a.png)

**System Information:**
 - Operating system: NixOS Unstable channel + KDE Plasma5 desktop
 - Strawberry Version: 0.9.3

**Additional context**
N/A

**Comment by jonaski** [comment]
I can't reproduce this problem.
Can you try to set the style to fusion in the appearance settings and see if the same issue occurs.

**Comment by e3bc54b2** [comment]
Can confirm the same issue occurs with Fusion style. This issue has been present ever since I switched to strawberry, so 6 months at least. I recently switched from Xorg to Wayland for Plasma session and can confirm the issue is present in both. Anything else I can test against?

**Comment by jonaski** [comment]
Can you try with a new configuration, backup `strawberry.conf` and `strawberry.db`, then delete them, add a folder to the collection, and a few songs with different albums to the playlist to check what configuration triggers this.

**Comment by e3bc54b2** [comment]
Apologies for not responding early, I wasn't able to put much attention here.

I found and backed up ~/.config/strawberry/strawberry.conf and ~/.config/strawberryrc, but did not find strawberry.db. I tried looking into preferences but I don't see it there either. Can you please help me where this file is usually located?
