### ISSUE TITLE
Unit tests require GTest, but installing it the recommended way doesn't work

### ISSUE THREAD

**Issue by EmmanuelMess** [strawberrymusicplayer/strawberry#771]
Google [recommends](https://google.github.io/googletest/quickstart-cmake.html) adding GTest like this:

```cmake
include(FetchContent)
FetchContent_Declare(
  googletest
  URL https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip
)
# For Windows: Prevent overriding the parent project's compiler/linker settings
set(gtest_force_shared_crt ON CACHE BOOL "" 
```

But doing this doesn't work for the project, is this because I may be missing QtTest, or because another installation is needed for this project?

**Comment by jonaski** [comment]
I'm not sure what you mean by "doesn't work".
Strawberry requires both gtest, gmock and QtTest. You should check that they are detected when you run cmake. Then you should be able to build the test with `make strawberry_tests`.

**Comment by EmmanuelMess** [comment]
> I'm not sure what you mean by "doesn't work".
> Strawberry requires both gtest, gmock and QtTest. You should check that they are detected when you run cmake. Then you should be able to build the test with `make strawberry_tests`.

Adding that code (the fetch content) doesn't make the gtest and gmock checks pass afaik, also it was not added on the existing CMakeLists.txt, does this mean that it should be installed another way?

**Comment by jonaski** [comment]
I'm not familiar with cmake FetchContent, I have never used it before (it also requires CMake 3.11). I can't help you with that. I suggest that you seek help with that in another place related to CMake or Google Test.
I also don't understand the need since all major Linux distros have both gtest, gmock and Qttest in their repositories.
There is a `find_package(GTest)` line for GTest, there is a `find_library` line for gmock, and Qttest is an `OPTIONAL_COMPONENTS` to find_package for Qt in CMakeLists.txt.

**Comment by EmmanuelMess** [comment]
>  I also don't understand the need since all major Linux distros have both gtest, gmock and Qttest in their repositories.

I thought that the wiki for this repo would have downloaded the package if it were installable from apt.

**Comment by jonaski** [comment]
googletest, libgmock-dev and libqt5test5 (Ubuntu doesn't have Qt 6?).

**Comment by EmmanuelMess** [comment]
> googletest, libgmock-dev and libqt5test5 (Ubuntu doesn't have Qt 6?).

None of those are in here https://github.com/strawberrymusicplayer/strawberry/wiki/Compiling-on-Ubuntu
