### ISSUE TITLE
Playing tracker/mod files results in extremely distorted sound and high CPU load

### ISSUE THREAD

**Issue by knochenhans** [strawberrymusicplayer/strawberry#772]
**Describe the bug**
Playing tracker files (ProTracker, Scream Tracker …) results in extremely and increasingly distorted sound and sometimes a high CPU load that only ends when quitting Strawberry. Playing tends to work right after starting Strawberry but distortion sets in when switching to another file. The files I tested with play fine in other audio players. Regular audio files are playing without problems for me in Strawberry.

**To Reproduce**
Play tracker files. 

**Expected behavior**
Playing tracker files without distortion :)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.9.3

**Comment by jonaski** [comment]
This looks like a gstreamer bug to me. It occurs when preloading the next URL.

**Comment by jonaski** [comment]
A workaround:
In the backend settings tick all options for cross-fade including "Cross-fade when changing tracks automatically" and un-tick "Except between tracks on the same album or in the same CUE sheet".
This will disable gap-less playback and pre-loading, instead each song and create new pipelines for each track change.
