### ISSUE TITLE
(macOS) Incorrect playlist alternating row colors with dark theme on macOS

### ISSUE THREAD

**Issue by foss-** [strawberrymusicplayer/strawberry#778]
As Clementine development is slow and strawberry seems to be the new fork to use moving this open issue to strawberry

- Operating System: macOS 10.15 + 11
- Strawberry version: 0.9.3

### Actual behaviour
Strawberry dark mode list view for tracks looks restless. That is due to the high contrast difference for the two grey tones used in that view.

### Expected behaviour
Why not take a hint from Apples music app, which uses two darker greys which results in a calmer list view and much improved text readability. This is an easy fix that should help make Clementine look much better.

Strawberry colors currently: 1E1E1E, 5B5B5B
Strawberry colors expected: 1B1B1B, 272727 (see Apple music app)

![list view clementine   apple music app](https://user-images.githubusercontent.com/5708172/83970941-c8979100-a8d8-11ea-9b16-6b1d09dd47d2.png)

I know there are some customize options  in settings but why not have great defaults right away?

**Comment by jonaski** [comment]
Strawberry doesn't use fixed colors for the alternating rows in the playlist. I'm not sure how you got that idea.
If you think there is an easy fix, then feel free to propose it in a pull request.

**Comment by foss-** [comment]
Sorry, no coding here. If that is a requirement for a feature request, then please close the issue. Maybe it does not use fixed colors but it uses default colors and this is what this issue would be about.

**Comment by foss-** [comment]
Looking much better <3
macOS 11.6, Version 0.9.3-415-g2b445fb5
<img width="628" alt="post fix" src="https://user-images.githubusercontent.com/5708172/135127064-6af32dee-377a-446f-90f8-989a96d04803.png">
