### ISSUE TITLE
Need keyboard shortcut to start searching collection

### ISSUE THREAD

**Issue by keyb0ardninja** [strawberrymusicplayer/strawberry#779]
Currently there is no way to start searching the music collection by keyboard. I suggest introducing a conventional shortcut such as `Ctrl + F` or `Ctrl + Shift + F` for this purpose.

**Comment by jonaski** [comment]
It's fine with me if you are willing to do it. I don't have time to take up any additional work.

**Comment by keyb0ardninja** [comment]
I don't have the technical ability to implement it. I just submitted this issue as a feature request, as a user of the application. I hope someone in the future with the time and capability can implement the feature.
