### ISSUE TITLE
XM music module file hangs Strawberry while reaching end of song

### ISSUE THREAD

**Issue by kokosowy** [strawberrymusicplayer/strawberry#787]
First of all thanks for strawberry development!

**Describe the bug**
Once XM music module playing is reaching the end, strawberry hangs, nothing can be done than killing the window.

**To Reproduce**
- start Strawberry 0.9.3
- download and extract sample music file https://files.scene.org/get:nl-http/music/disks/recover.zip
- put Msx/02.xm on playlist and play
- wait until end of song is reached or fast forward just before 4:46 and wait

**Expected behavior**
Strawberry should continue playing playlist items, not hang.

**Screenshots:**
https://imgur.com/TyJTgV3

**System Information:**
Operating System: KDE neon 5.22
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-37-generic (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-4700HQ CPU @ 2.40GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600

**Comment by jonaski** [comment]
This bug is in GStreamer, I opened an issue in gst-plugins-bad here: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/issues/1676
