### ISSUE TITLE
question + feature

### ISSUE THREAD

**Issue by boistordu** [strawberrymusicplayer/strawberry#789]
Hi,

since I'm not sure it is actually a feature of this software I'm going to ask the question first,

Is this program capable of analyze any music files, send it to one of the analyzing song services and retag the song appropriately? 
I'm asking that simply because I've tried with the files extracted from my iphone library. 

By the way to bounce back on the https://github.com/strawberrymusicplayer/strawberry/issues/212
I could tell you it's very simple to extract songs from an iphone new generations. You just need to mount the iphone with the `ifuse /mountdir` and that's it. Then the different folders concerned by the music files are Itunes and Music or something alike. 
In those you will have your old mp3 files that you have exported to your iphone previously and you will have the files you've bought from the itunes store with their appropriate plist files and cover. But of course those files are m4a and without any tags inside. 
Whcich leads me to my question, is strawberry capable to analyze those files and detect which songs is it? BEcause it has not been able to do it on my setup apparently.

**Comment by jonaski** [comment]
We have a forum for this purpose: https://forum.strawberrymusicplayer.org/
