### ISSUE TITLE
Rating does not work

### ISSUE THREAD

**Issue by bartdbx** [strawberrymusicplayer/strawberry#790]
![Screenshot_20211011_121705](https://user-images.githubusercontent.com/92305755/136777725-d7f36c89-e4d4-4313-b5c1-b119b57f6d7a.png)
![Screenshot_20211011_121747](https://user-images.githubusercontent.com/92305755/136777728-33b50c27-40f9-476f-998e-91dd7c199b27.png)

RATING doesn´t work at all in Strawberry when I compare it to clementine. It seems like the tag (in file ID3v2) is skipped. I also tried ID3v1, ID3v2.3, ID3v2.4, UTF-8, UTF-16 and ISO. The tags are correctly saved to file, as I can see in Dolphin. A library reload with clementine works as expected, but not in Strawberry. This is annoying (for me) because I create my playlists based on my own rating, so I´m forced to stick with clementine.
In attachement comparison of both applications with same library.

**Comment by foss-** [comment]
Will there be another commit about writing rating to file tags? The recent commit closing this issue only mentions read capabilities. Should we file a separate issue for writing?
