### ISSUE TITLE
Arrow of stop button is missing from Strawberry built against Qt6

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#795]
**Describe the bug**
Strawberry from Arch Linux repos is built against Qt6 and I noticed
that its stop button does not have an arrow. Strawberry-qt5 available in AUR
has said arrow.

**To Reproduce**
use Strawberry built against Qt6
observe the stop button below the playlist

**Expected behavior**
stop button of Strawberry built against Qt6 should have an arrow too

**Screenshots:**
Strawberry built against Qt5, stop button with arrow, as expected:
![qt5](https://user-images.githubusercontent.com/15967631/137538554-ae5de26e-11b6-4d02-a277-d465a61c5f49.png)

Strawberry built against Qt6, missing arrow:
![qt6](https://user-images.githubusercontent.com/15967631/137538693-069c6d01-3186-4d73-b494-2673b43888e8.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0

**Additional context**

**Comment by glaubersm** [comment]
If I click on the rght most position of the stop button of Strawberry-qt6,
a menu with 'Stop' and 'Stop after this track' options opens.

**Comment by jonaski** [comment]
I've also noticed this. Thought it was an easy fix, but I think it might be a Qt bug. If I set the arrow, the icon disappears.

**Comment by jonaski** [comment]
Looks like it work fine if I add a QToolButton to a new UI, but it does not work even if I add a new QToolButton to the controls in mainwindow UI, so it might have something to do with the layouts it in.

**Comment by buckmelanoma** [comment]
Removing these lines from data/style/strawberry.css seems to restore the arrow (and likely fixes issue #796 ):

QToolButton {
  border: 2px solid transparent;
  border-radius: 3px;
  padding: 1px;
}`

QToolButton::menu-button {
  width: 16px;
  border: none;
}

QToolButton[popupMode="1"] {
  padding-right: 16px;
}

QToolButton:hover {
  border: 2px solid %palette-highlight;
  background-color: %palette-highlight-lighter;
}

QToolButton:hover[popupMode="1"] {
  padding-right: 16px;
}

QToolButton:pressed {
  border: 2px solid %palette-highlight-darker;
  background-color: %palette-highlight-lighter;
}

QToolButton:pressed[popupMode="1"] {
  padding-right: 16px;
}

A side effect is that you lose the cursor hover/highlight on mouse-over.

**Comment by jonaski** [comment]
I'll reopen the issue since it still isn't perfect.
I added the css border styles back for macOS only because it looks awful otherwise, on other platforms the arraw is back, but not sure I like the borders when hovering over the buttons.

**Comment by jonaski** [comment]
https://bugreports.qt.io/browse/QTBUG-99642

**Comment by Lartza** [comment]
On Windows this still isn't fixed, and I'd argue it's worse now since there is an empty ga
![strawberry_mkrjHm6p2f](https://user-images.githubusercontent.com/305616/148923403-0927b45e-20d8-4bf8-b53d-cf04c847ca20.png)
![JJkPC1u6Fg](https://user-images.githubusercontent.com/305616/148923412-05bcb232-2f11-4341-8cb3-aa62767e9bfe.png)

p

**Comment by jonaski** [comment]
The arrow is missing, it's a Qt bug present in Qt 6.2.2 that is already fixed, so it will resolve itself when the next Qt release is available.
I can see if I can add the patches so it's fixed in the strawberry builds until the next Qt release is available.

**Comment by Lartza** [comment]
Oh apologies I didn't put one and two together since the issue was closed. At least anyone else stumbling to this issue will know too now 😅
