### ISSUE TITLE
Error message while scanning my music

### ISSUE THREAD

**Issue by gmipf** [strawberrymusicplayer/strawberry#815]
Error message:

Unable to execute SQL query: NOT NULL constraint failed: songs.mtime Der Datensatz konnte nicht abgeholt werden<br />Failed query: INSERT INTO songs (title, album, artist, albumartist, track, disc, year, originalyear, genre, compilation, composer, performer, grouping, comment, lyrics, artist_id, album_id, song_id, beginning, length, bitrate, samplerate, bitdepth, source, directory_id, url, filetype, filesize, mtime, ctime, unavailable, fingerprint, playcount, skipcount, lastplayed, lastseen, compilation_detected, compilation_on, compilation_off, compilation_effective, art_automatic, art_manual, effective_albumartist, effective_originalyear, cue_path, rating) VALUES (18 - Telly Tellz - Mir steht es besser, Flowvater Mixtape, Telly Tellz, Flowvater Mixtapeartist, 18, -1, 2017, -1, Other, 0, , Telly Tellz, , , , Telly Tellz_id, Flowvater Mixtape_id, , 0, 131474000000, 320, 44100, -1, 2, 1, file:///media/Daten/Musik/Rattos%20Locos/Telly%20Tellz%20-%20Flowvater%20Mixtape%20(Mp3)/18%20-%20Telly%20Tellz%20-%20Mir%20steht%20es%20besser.mp3, 8, 5261362, , 1627151052, 0, , 0, 0, -1, 1635547682, 0_detected, 0_on, 0_off, 0_effective, , , Telly Tellz, 2017, , -1)

**System Information:**
 - Operating system: Kubuntu 20.04
 - Strawberry Version: 1.0

**Comment by gmipf** [comment]
I have fixed it, changed the file "18 - Telly Tellz - Mir steht es besser.mp3" using mp3tag (changed the Genre) which fixed the issue. I can scan again fully.

**Comment by jonaski** [comment]
Very strange. According to the query, the mtime isn't set, but ctime is, that doesn't make much sense to me.
