### ISSUE TITLE
Keep Jack client always alive

### ISSUE THREAD

**Issue by mxa** [strawberrymusicplayer/strawberry#828]
**Describe the bug**
Strawberry opens a Jack client when music is played and kills it when music stops. This isn't how Jack clients are intended to operate.  One of the reasons is because users may want to add a different routing which may get lost when the stop button is pressed if the client is recreated on the next play.

**Expected behavior**
Always keep the Jack client alive once Strawberry is opened.

**System Information:**
 - Operating system: Kubuntu 21.10
 - Strawberry Version: 1.0

**Comment by jonaski** [comment]
This isn't possible in GStreamer as far as I can tell, it only opens the connection on `GST_STATE_PAUSED` or `GST_STATE_PLAYING` states, even if it was possible with GStreamer, it requires a major rewrite of the whole engine code in Strawberry to do, switching between pipelines when fading, etc.
I also don't see much use-case for this. I doubt many users use Strawberry with Jack.

**Comment by falkTX** [comment]
> I also don't see much use-case for this. I doubt many users use Strawberry with Jack.

Hey I do, all the time! Has always been a fan of old amarok, then clementine then strawberry.

One alternative would be to use https://github.com/guysherman/jack-passthrough/ in between strawberry and jack system ports, but sadly there are options in the JACK output device through either clementine or strayberry that allow us to set up the target ports. Gstreamer allows to setup such a thing, see https://gstreamer.freedesktop.org/documentation/jack/jackaudiosink.html

This would solve the situation, not in the best way but personally I would be quite fine with this.

**Comment by falkTX** [comment]
To be clear, the implementation would be to expose the `port-pattern` as a JACK device option.
We can figure out the rest.

**Comment by jonaski** [comment]
Making a setting where you can enter a port-pattern isn't a problem, I guess we can just use the existing device string textbox.

**Comment by mxa** [comment]
Oh, maybe this one gets solved magically as well: https://github.com/strawberrymusicplayer/strawberry/issues/546

**Comment by jonaski** [comment]
I fixed so the device string textbox is enabled with jack and can be used to set port-pattern.
Alternatively I can add a dedicated groupbox at the bottom to set more properties for jack suck as client-name, port-names, low-latency and server, see: https://gstreamer.freedesktop.org/documentation/jack/jackaudiosrc.html?gi-language=javascript
Is it necessary, or is it enough with just port-pattern?

**Comment by falkTX** [comment]
for me port-pattern is enough, there is no point for low-latency on a music player. taking half second to pause playback is not an issue, specially with fade-out enabled anyway.

**Comment by jonaski** [comment]
OK

**Comment by PeterWenger** [comment]
Hello falkTX and jonaski, how can I find the right port-pattern for calf-plugins eq? or x42-eq ?

**Comment by PeterWenger** [comment]
Sorry but it is not working with the port pattern.
Any solution?

**Comment by PeterWenger** [comment]
Hello falkTX, is now strawberry and clementine working direct with jack? For me not. I had to bridge pulseaudio to jack. But there is pipewire comming, and at the moment cadence is not working with pipewire.
Is there any solution?
