### ISSUE TITLE
Extended Latin characters not showing in lyrics for MP4 AAC

### ISSUE THREAD

**Issue by iteqla** [strawberrymusicplayer/strawberry#830]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
Strawberry does not show some special character of the Latin alphabet when editing the track information, although they are shown correctly in the context window.

**To Reproduce**
Type the leters ä, å or any other of the extended Latin alphabet and you'll obtain Ã¤, Ã¥ etc. after saving the lyrics.

**Expected behavior**
Characters ä, å etc. should be shown as such everywhere

**Screenshots:**
see attached

**System Information:**
 - Operating system: Windows 10 Pro - Version 21H1 - OS Build 19043.1348
 - Strawberry Version: 1.0

**Additional context**
![strawberry 1 0](https://user-images.githubusercontent.com/38462266/141656005-4d2cca96-8d7f-41c5-b733-d410c0666cd3.jpg)

**Comment by jonaski** [comment]
Can't reproduce this problem here on Windows 10.
What audio file format?
What system locale settings do you have configured in Windows?

**Comment by iteqla** [comment]
File Extension: m4a
File Type: MP4 AAC
Windows display language:  English UK
Added Keyboards: Italian, German

Interestingly, other alphabets work perfectly fine (see screenshot).
It seems to affect only certain character of the extended Latin..
![2021-11-23 17_33_11-Window](https://user-images.githubusercontent.com/38462266/143075412-71501001-c25f-45c5-bb35-55539134e2a7.jpg)
.
