### ISSUE TITLE
audiofiles get corupted

### ISSUE THREAD

**Issue by Marees213** [strawberrymusicplayer/strawberry#832]
**Describe the bug**
audiofiles get corrupted. .OGG and MP3. 

**To Reproduce**
if i let the player play on shuffle playlist with about 250 songs it start to "not recognize files" and the metadata dissaperes.
i made the files read only and now when it happens it shows only the path of the file.

**Expected behavior**
maybe its a buffer or a codec failure, i myself are not an programmer, just an enthusiast.

**Screenshots:**
-

**System Information:**

strawberry Version 1.0

System:    Kernel: 5.13.0-21-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.7 
           wm: muffin dm: GDM3, LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 

Machine:   Type: Desktop Mobo: Motherboard by ZOTAC model: ZBOX-EN1070/1060 v: Rev.00 
           serial: <filter> UEFI: American Megatrends v: B333P009 date: 11/08/2016 

CPU:       Topology: Quad Core model: Intel Core i5-6400T bits: 64 type: MCP arch: Skylake-S 
           rev: 3 L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 17599 
           Speed: 900 MHz min/max: 800/2800 MHz Core speeds (MHz): 1: 900 2: 900 3: 900 4: 900 

Graphics:  Device-1: NVIDIA GP106M [GeForce GTX 1060 Mobile] vendor: ZOTAC driver: nvidia 
           v: 470.82.00 bus ID: 01:00.0 chip ID: 10de:1c20 
           Display: x11 server: X.Org 1.20.11 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: NVIDIA GeForce GTX 1060/PCIe/SSE2 v: 4.6.0 NVIDIA 470.82.00 
           direct render: Yes 

Audio:     Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: ZOTAC 
           driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:a170 
           Device-2: NVIDIA GP106 High Definition Audio driver: snd_hda_intel v: kernel 
           bus ID: 01:00.1 chip ID: 10de:10f1 
           Sound Server: ALSA v: k5.13.0-21-generic 

Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ZOTAC 
           driver: r8169 v: kernel port: d000 bus ID: 02:00.0 chip ID: 10ec:8168 
           IF: enp2s0 state: down mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ZOTAC 
           driver: r8169 v: kernel port: c000 bus ID: 03:00.0 chip ID: 10ec:8168 
           IF: enp3s0 state: down mac: <filter> 
           Device-3: Intel Wireless 3165 driver: iwlwifi v: kernel port: c000 bus ID: 04:00.0 
           chip ID: 8086:3165 
           IF: wlp4s0 state: up mac: <filter> 
           Device-4: Realtek RTL8153 Gigabit Ethernet Adapter type: USB driver: r8152 
           bus ID: 4-1.4:3 chip ID: 0bda:8153 
           IF: enx00e04caab18d state: down mac: <filter> 

Drives:    Local Storage: total: 476.94 GiB used: 389.77 GiB (81.7%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: MZVKW512HMJP-00000 size: 476.94 GiB 
           speed: 31.6 Gb/s lanes: 4 serial: <filter>

**Additional context**
copied my list double because realy like the strawberry player. props!

best regards
ramon

**Comment by Marees213** [comment]
![Screenshot from 2021-11-19 01-16-11](https://user-images.githubusercontent.com/25182881/142517151-8a3baaec-2059-4ef1-8d31-5b4d370fffcd.jpg)

**Comment by jonaski** [comment]
I don't find it very likely that Strawberry corrupted your files. Strawberry does not write to the files unless the "save album covers as embedded cover" option is checked in the collection settings and a new cover is set, or you use the tag editor to edit tags for the files. But in that case it's done by taglib.
No-one else has reported issues with corrupted files. How you know that the files are corrupted and why do you think Strawberry caused this? What file-system do you use where the music is stored?
"Resource not found" usually means that the files no longer exists, or can't be accessed in the path. If the file could be accessed a different error would be shown.

**Comment by Marees213** [comment]
had a trip tio italy this weekend...

exactly, I'm also very confused and to be sure i made them read only now.
They are stored in a sub map in the Music dir.

what makes it more strange is that the song played before  and after
the file is unusable (see screenshot after importing it as raw data in
audacity, audacity doesn't recognize it otherwise)

i use ext4

the file is still in the same ditr but unfindable with add file option. I
only see the file in the file manager....

**Comment by jonaski** [comment]
Can you send me one of the files that no longer works I can take a look at it.

**Comment by jonaski** [comment]
Hard for me to tell what's causing this, but I find it very unlikely that strawberry causes corrupt files, it doesn't write to the files when playing them and no-one else has reported similar problems.
I suggest that you check your harddrive and filesystem for failure.
