### ISSUE TITLE
[Feature] Possible to import popularity information from Spotify?

### ISSUE THREAD

**Issue by arsaboo** [strawberrymusicplayer/strawberry#839]
I just started using Strawberry and am loving it so far. One of the features that I am looking for is importing track popularity from Spotify. Strawberry already uses Spotify integration for cover art. It would be great to include the popularity information and save it in Rating. Spotify directly provides track popularity information in its [Track](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-track) or [Tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-several-tracks) API.

This would greatly improve smart/dynamic playlists.

**Comment by jonaski** [comment]
We don't take feature requests.
