### ISSUE TITLE
Strawberry doesn't recognize ReplayGain values stored in cue sheet

### ISSUE THREAD

**Issue by magicgoose** [strawberrymusicplayer/strawberry#840]
**Describe the bug**
CUE sheets may contain ReplayGain values, and foobar2000 for example may write such values.
Strawberry seems to ignore them completely. It clearly uses "fallback-gain" for such files, as if they didn't have ReplayGain values.

There doesn't seem to be any workaround to let it use ReplayGain information for music albums stored as a single audio file + cue sheet.

**To Reproduce**
1. find any music CD stored as FLAC + CUE
2. add ReplayGain information to the CUE file, so it would have these values at the top level (example):
```
REM REPLAYGAIN_ALBUM_GAIN -5.53 dB
REM REPLAYGAIN_ALBUM_PEAK 0.994629
```
and something like this before first INDEX of every track:
```
    REM REPLAYGAIN_TRACK_GAIN -3.46 dB
    REM REPLAYGAIN_TRACK_PEAK 0.994629
```
3. Set fallback-gain to -60 dB (just to make it obvious if RG info was used)
4. Start playback, music will be almost inaudible, because it doesn't see RG values and thus uses fallback-gain
5. Try the same steps with FLAC files where RG tags are written into individual tracks (and each track is in its own file), then ReplayGain works as expected, and not using fallback-gain

**Expected behavior**
ReplayGain gets properly used, like in e.g. foobar2000 or any other music player supporting this syntax.

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0

**Additional context**

**Comment by jonaski** [comment]
Strawberry does not read replay again entries from CUE sheets. I had no idea about it either.
I can't find any documentation for it either, for example https://wiki.hydrogenaud.io/index.php?title=Cue_sheet mention nothing about it.

**Comment by magicgoose** [comment]
Yeah I'm afraid it's not really documented :crying_cat_face:

**Comment by jonaski** [comment]
I won't be adding support for ReplayGain from CUE sheets, and unfortunately it does not seem likely that anyone else is willing to contribute it either considering the low contribution interest in the past 4 years.
