### ISSUE TITLE
Playback halts at the end of the buffer of online streaming when resuming

### ISSUE THREAD

**Issue by dmcbride** [strawberrymusicplayer/strawberry#846]
**Describe the bug**
When pausing an online radio station and then later restarting, Strawberry says "Server does not support seeking." and then stops instead of continuing the stream.  Restarting the playback works.

**To Reproduce**
Start streaming an online stream.  After a while, pause it (I use "strawberry -t" on the command line).  Wait long enough that the buffered data is significantly out of sync with the stream.  Restart (again, I use "strawberry -t" on the command line).  Strawberry will play through its buffer, and pop up this message.

**Expected behavior**
I expect strawberry to do at least what clementine did, as well as amaroK before it, which is that it would play through its current buffer and then abruptly switch to the current-in-time stream music.  Better would be to detect that the buffer is from a live stream and simply discard the entire buffer and resume playback from where the stream is now.

**Screenshots:**
![The pop-up](https://forum.strawberrymusicplayer.org/assets/uploads/files/1637971157276-e8137782-feee-4078-a41e-c1d575f4e592-image.png)

**System Information:**
 - Operating system: Gentoo Linux
 - Strawberry Version: 1.0

**Comment by jonaski** [comment]
This is a gstreamer bug, probably related to https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/303

**Comment by dmcbride** [comment]
According to https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/issues/763 this is not a gstreamer bug, but is something the application should handle.  Specificially, [the comment by the owner](https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/issues/763#note_565125) saying, "The problem here is that it would restart streaming at a different position than before, which might be undesired by the application. IMHO this should be handled at the application layer to restart the stream on network errors. The [fallbacksrc/fallbackswitch](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/tree/master/utils/fallbackswitch/) elements can make this relatively easy for applications."

Could we get this added to strawberry for live streams?

**Comment by jonaski** [comment]
Strawberry doesn't read the HTTP headers. Restarting is more of a workaround than a fix.

**Comment by jonaski** [comment]
I'd rather see this solved at a lower level in gstreamer when that's fully possible than creating a "fix" in Strawberry which will be more of a workaround. I don't have the time to dig into it myself.

**Comment by Nyanraltotlapun** [comment]
But maybe Strawberry can properly  handle this error? Like just reconnect?
We cannot expect gstreamer mess will fix itself on some point in the future.

I constantly having this bug popup and radio stop playing.

**Comment by Nyanraltotlapun** [comment]
> I'd rather see this solved at a lower level in gstreamer when that's fully possible than creating a "fix" in Strawberry which will be more of a workaround. I don't have the time to dig into it myself.

But can you at least pretend that you care and leave bug open? So someone else can fix it?
