### ISSUE TITLE
Seek bar stops showing progress

### ISSUE THREAD

**Issue by geroyche** [strawberrymusicplayer/strawberry#847]
The seek bar stops tracking playback progress after a while, and once it is in that state, it does not recover until I restart Strawberry.
Once it that state, when I change songs, the bar updates itself to some seemingly random position on playback start, but won't move further.
The seek functionality itself still works.

Context: I'm playing Flac files.

I have not been able to create a reliable instruction how to reproduce this, but on my machine it only takes a few seconds of random seeking. Sometimes the bar gets stuck on the first seek already. I made a screen recording that is representative of the issue. First I thought it might happen after Strawberry loses focus, but it's not that.

[https://youtu.be/NQEprp0uYr4](https://youtu.be/NQEprp0uYr4)

I'm on MacOS Monterey 12.1 beta (M1 Max), and updated from 1.0.0 to  1.0.0-125-g4c6251bf before opening this issue, but the issue is still there.
This is a new mac. I don't recall having had this issue on my previous Big Sur intel machine.

**Comment by jonaski** [comment]
Can you check if it works if you set the style to "Fusion" under Settings / Appearance?
You need to restart strawberry for the setting to take affect.

**Comment by geroyche** [comment]
I changed to Fusion, restarted, and the first skipping stopped the seek bar. So, no, does not work in Fusion style either.

**Comment by bgunnink** [comment]
FWIW, I was having this issue after updating to Monterey, but the most recent update to Strawberry (1.0.1) appears to have fixed it.

**Comment by jonaski** [comment]
It was probably a Qt bug that has been fixed, since 1.0.1 has the latest Qt release (6.2.2).
