### ISSUE TITLE
Song playback results to OS freezing

### ISSUE THREAD

**Issue by Sens1t1ve** [strawberrymusicplayer/strawberry#850]
**Describe the bug**
Attempting to play a song results in the whole OS freezing, requiring a restart using the power button.
**To Reproduce**
Double click a song on a playlist to attempt playback.

**Expected behavior**
Expecting audio playback to occur, instead entire system freezes.

**Screenshots:**
Screenshot has my neofetch info for context.
![neofetchscreenshot](https://user-images.githubusercontent.com/94155244/145442372-96490fe2-28f7-43a1-8615-60adc7610076.png)

**System Information:**
 - Operating system: Pop!_OS 21.04 x86_64
 - Strawberry Version: 1.0.0

**Additional context**
My Strawberry is a Flatpak installed directly from the Pop!_Shop GUI.
One detail I noticed is after updating Strawberry, it seemed to clash with my OS's dark theme, displaying a white theme (which previously detected my dark theme and worked with it.)

**Comment by jonaski** [comment]
I tested installing Pop OS in a virtual box and just installed strawberry through "popshop", I see no issues.
It's probably either related to your configuration, or you device.
Try setting a device manually in Tools / Settings / Backend, select alsa or pulseaudio as output and the device.

**Comment by jonaski** [comment]
Doesn't magic syskeys work since you had to use the power button?

**Comment by Sens1t1ve** [comment]
I installed it from the PPA repository instead and did the backend settings
and it works now. So it probably had to be a config/hardware related issue
maybe in relation to the flatpak install. You've done good work with this
project, thanks!

su 12. jouluk. 2021 klo 1.29 Jonas Kvinge ***@***.***)
kirjoitti:

**Comment by jonaski** [comment]
Nice, and thanks! Closing the issue then.
