### ISSUE TITLE
Global Menu Doesn't Appear on Plasma Wayland

### ISSUE THREAD

**Issue by sonic2kk** [strawberrymusicplayer/strawberry#852]
**Describe the bug**
Global menu doesn't appear for Strawberry on the Plasma Wayland session.

**To Reproduce**
Start a KDE Plasma Wayland session and open Strawberry (may require installing Qt6 package). No Global Menu will appear.

**Expected behavior**
Global menu should appear as it does on X11.

**Screenshots:**

**System Information:**
 - Operating system: Arch Linux KDE Plasma 5.23.3
 - Strawberry Version: 1.0.0-1 (Official Repos)

**Additional context**
Perhaps this is a general Plasma Wayland/Qt6 Wayland issue, but was unable to find information specifically pertaining to Qt5/6 applications. It is well known that Plasma Wayland has Global Menu issues with GTK applications, so perhaps this is not specifically a Strawberry issue.

**Comment by jonaski** [comment]
This isn't a strawberry bug as far as I can tell.
