### ISSUE TITLE
Universal package for version 1 missing

### ISSUE THREAD

**Issue by docop** [strawberrymusicplayer/strawberry#854]
Hi  So the player is quite well made. Great project !.   I might wonder, if you will also put the appimage for the version 1 ? look the v.093 is the last.
thank in advance

**Comment by jonaski** [comment]
Probably not.
There are instructions on how to build from source in the Wiki:
https://github.com/strawberrymusicplayer/strawberry/wiki/Compile-and-install-on-linux

**Comment by docop** [comment]
thanks.  i will just stay in previous version .93 .

**Comment by jonaski** [comment]
See https://forum.strawberrymusicplayer.org/topic/1094/appimages-for-linux
