### ISSUE TITLE
Transcode to MP3 nor work

### ISSUE THREAD

**Issue by aaaaadrien** [strawberrymusicplayer/strawberry#856]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
When i try to convert OGG to MP3 with the software, it fails at each time. No explicit error message

**To Reproduce**
Tools -> Transcode -> Add an OGG file
Select Audio Format MP3
Start transcode

**Expected behavior**
The transcoding works :)

**Screenshots:**
Not applicable

**System Information:**
 - Operating system: Windows 10 pro
 - Strawberry Version: 1.0

**Additional context**

**Comment by jonaski** [comment]
Fixed with https://github.com/strawberrymusicplayer/strawberry/commit/94561e6815ac706bfafc247cda48009b6c122913
