### ISSUE TITLE
Strawberry MacOS builds cannot be verified 

### ISSUE THREAD

**Issue by jamesmcguirepro** [strawberrymusicplayer/strawberry#859]
**Describe the bug**
Strawberry releases are not signed, so MacOS cannot verify the app is free from malware.  

**To Reproduce**
* Download & install dmg
* Open strawberry in Applications folder
* Observe prompt disallowing Strawberry from opening.

**Expected behavior**
* I should be able to open Strawberry

**Screenshots:**
![Screen Shot 2021-12-28 at 2 24 38 PM](https://user-images.githubusercontent.com/46612003/147611480-eda64c47-6143-46ad-b7eb-c3dc45c071ea.png)

**System Information:**
 - Operating system: Mac OS Monterey
 - Strawberry Version: 1.0.0

**Additional context**
I am trying to use strawberry on my work computer, and I believe IT has locked out my ability to override the verified app block.

**Comment by jonaski** [comment]
Signing requires a paid Apple developer account so it won't be done.
