### ISSUE TITLE
QT_STYLE_OVERRIDE=gtk2 not respected

### ISSUE THREAD

**Issue by geckolinux** [strawberrymusicplayer/strawberry#864]
Hi there, on non-KDE systems (such as Gnome and Cinnamon) I always put `QT_STYLE_OVERRIDE=gtk2` in `/etc/environment` for proper theming support in Qt apps. However, Strawberry ignores this, when run from a command line it throws an error that the "gtk2" style is invalid and it loads a terrible default theme. Clementine properly respects the `QT_STYLE_OVERRIDE=gtk2` variable and therefore looks much better:

![Screenshot from 2022-01-03 20-13-36](https://user-images.githubusercontent.com/2692138/147996888-8f897cbe-4fe4-4de9-a318-2b972c5040d8.png)

**Comment by jonaski** [comment]
The error message you receive on the terminal clearly shows that you are missing the style you try to set.
The gtk style plugin needs to installed for the correct major Qt version that strawberry is compiled with.
Clementine is Qt 4 (Qt 5 if you use the git/master repository) while Strawberry is Qt 6 with the option to still compile with Qt 5.

Overriding style works fine here with both Qt 6 and Qt 5.
`QT_STYLE_OVERRIDE=style strawberry`
However the style needs to be set to "default" in the appearance settings for this to work.

**Comment by geckolinux** [comment]
Hi there, that's not correct. The environment variable is correctly set as described here:
https://wiki.archlinux.org/title/Qt#Appearance
It uses a Qt platform theme that is correctly installed, which imitates the current gtk2 theme:
![Screenshot from 2022-01-04 12-37-53](https://user-images.githubusercontent.com/2692138/148100940-1176748e-516c-4ddb-b369-66fe184f1903.png)
The style is set to "Default" in Strawberry, I didn't touch the settings.

**Comment by geckolinux** [comment]
My apologies, I didn't notice that Strawberry is QT6. That looks like it will be an entirely new mess for integration with GTK themes, but you're right that this bug is invalid.
