### ISSUE TITLE
Uppercase ReplayGain Vorbis comments not supported

### ISSUE THREAD

**Issue by Orthestral** [strawberrymusicplayer/strawberry#866]
**Describe the bug**
Strawberry only detects lowercase ReplayGain Vorbis comments and ignores uppercase comments

**To Reproduce**
Add uppercase Vorbis comments for ReplayGain (in ogg/flac/m4a/opus/any supported filetypes) instead of lowercase ones and play the file. (For example, use `REPLAYGAIN_TRACK_GAIN` instead of `replaygain_track_gain`)

**Expected behavior**
Uppercase ReplayGain Vorbis comments should be detected by Strawberry

**System Information:**
 - Operating system: EndeavourOS
 - Strawberry Version: 1.0

**Additional context**
Uppercase ReplayGain comments are supposed to be the standard, and many music players and loudness calculators apply/read this. However, many others apply/read only lowercase comments, so it would be best for Strawberry to support both

**Comment by jonaski** [comment]
Report it to gstreamer: https://gitlab.freedesktop.org/groups/gstreamer/-/issues

**Comment by mirko77** [comment]
I wondered why Replay Gain was not working on opus files, while it does on mp3.
Both formats are tagged with https://github.com/desbma/r128gain, but it has no effect when playing the opus files in Strawberry.

**Comment by Orthestral** [comment]
@mirko77 GStreamer is the backend Strawberry uses to play the music. This issue is out of Strawberry's control; the issue is present when using GStreamer alone.

Here is the issue in question on the GStreamer Gitlab
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/943
