### ISSUE TITLE
Cannot rate tracks in a subsonic server

### ISSUE THREAD

**Issue by cquike** [strawberrymusicplayer/strawberry#875]
**Describe the bug**
I cannot rate a track which is in a subsonic server. The rating column is shown empty and it doesn't seem to be anyway to rate it.

**To Reproduce**
Add a subsonic track to the playlist. The Rating column is shown empty.

**Expected behavior**
A five star row is shown like for tracks in the local collection and one can rate the song and the result is stored in the subsonic server so that other subsonic clients see the same rating. 

**System Information:**
 - Operating system: Linux
 - Strawberry Version: 1.0.1

**Comment by jonaski** [comment]
Strawberry does not support it. No plans to add it either.
