### ISSUE TITLE
Cant sync playlists/songs to Android phone

### ISSUE THREAD

**Issue by Offerel** [strawberrymusicplayer/strawberry#877]
**Describe the bug**
I try to sync playlists/songs with my Android phone. If i try to copy songs to my device, the process is stuck with the message "organize files" in the statusbar.

**To Reproduce**
- Plugin Android phone via USB
- Choose MTP mode on the phone
- In case the phone is automatically mounted -> unmount the phone in file manager (gnome)
- Start Strawberry 1.0.1
- The phone appears in the pane for devices
- Doubleclick the phone
- Phone is read (slowly, but it works)
- After some time it detects x songs on the device
- Rightclick a song in a playlist
- Choose "Copy to device"
- Click OK in the next dialogbox to accept the values
- Dialog disappears
- Message "Organize files" stays forever in the statusbar. No error message is shown

**Expected behavior**
Playlist (including songs) will be transfered or a clear error message is shown.

**Screenshots:**

**System Information:**
 - Operating system: Manjaro Testing
 - Strawberry Version: 1.0.1 (1.0.0 also)

**Additional context**
Transfering files file-manager (if mounted) is working fine.

**Comment by jonaski** [comment]
I wasn't even able to list the songs on the phone:
```
00:13:02.210 WARN  unknown                          QObject::connect: Cannot queue arguments of type 'MtpConnection*' 
00:13:02.210 WARN  unknown                          (Make sure 'MtpConnection*' is registered using qRegisterMetaType().) 
```
Might have occurred with Qt 6.

Fixing the metatype solved the problem and I'm able to copy songs just fine.

**Comment by jonaski** [comment]
MTP is usually very slow. How long did you wait?

**Comment by Offerel** [comment]
I have tried with a 5 minute mp3 file, there i waited more than 20 minutes, without an end. What do you mean with changing metatype? How can i do this?

In the meantime, i used a workaround:
I added a new and empty folder in Settings > Library. When i want to sync a song/album/playlist, i right-click the wanted songs > Organize files > Choose the empty folder as target / After copy = Keep the files. This created copy in the needed structure i the empty folder. Now i use grsync to sync this files to my Android phone. I'm not sure, if this doubles the songs in the library, but i don't think so. For 2GB music, the process takes 5 - 10 Minutes, which is is fine for me. The only downside i found so far is, that this is a little bit complicated.

I hope this has no negative side effect to the current library. I have no idea whats going on with the library if i do that.

**Comment by jonaski** [comment]
This is seem like a system related issue and not a bug in strawberry. I tested it here and it works fine.
I suggest to try mtp tools to copy the files and see if you get any more hints on what's going on:
http://manpages.ubuntu.com/manpages/trusty/man1/mtp-tools.1.html

**Comment by Offerel** [comment]
OK. MTP Tools is working so far. Can you please give me a hint, where to look for the system related issue? Any idea, what to report to Manjaro team and where? I really have no idea...
