### ISSUE TITLE
[feature request] gapless playback

### ISSUE THREAD

**Issue by peter-joo** [strawberrymusicplayer/strawberry#878]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
There is no feature like that implemented ever before in strawberry.

**To Reproduce**
Use two tracks where in between those two tracks there is no silence, fade out, etc. in the file.
Classical and jazz music often exhibits such tracks.
Listen to the 'gap' which occurs at the end of the first track, before playing the 2nd track.
It is a small time frame under which strawberry -as a decoder- reinitialize itself to play the 2nd track.
So listening to those genres often lead to unsatisfactory listening experience.

**Expected behavior**
No gap whatsoever between such tracks.

**Screenshots:**
screenshot is not required here

**System Information:**
 - Operating system: Ubuntu 18 LTS (engine: gstreamer, output: via ALSA)
 - Strawberry Version: 1.0.1

**Additional context**

**Comment by jonaski** [comment]
What audio format?

**Comment by peter-joo** [comment]
For mp3, for wav and for ape too, the same gap present.

**Comment by jonaski** [comment]
Strawberry implements gapless playback independent of audio format.
For MP3 is's a well-known gstreamer bug, already reported here https://github.com/strawberrymusicplayer/strawberry/issues/713. I have never tested APE and WAV.

**Comment by peter-joo** [comment]
I have been found something very interesting.

If you seek to the end of the 1st track, just 5 seconds before it finishes and then you press press play the problem comes.
If you seek to the end of the 1st track, just 10 seconds before it finishes and then you press play the problem DOES NOT come.
My Tools/Settings/Backend/Buffer duration is 8000 ms.

So it seems the problem comes when the remaining playback at the end of the first track is less then the Buffer duration.
(tested on Manjaro, will be verified on Ubuntu too, on Monday)

Fortunately it isn't a problem during normal listening conditions.

**Comment by jonaski** [comment]
If you seek 5 seconds before it finished it won't have time to pre-load the next track so that's normal, not a bug. Normally it should start pre-loading around 5 seconds before the end of the track. So if you want to test that it works make sure you seek so it still have at least 6 seconds remaining of the track.
However there is still a small glitch between tracks with MP3 (possible some other formats too), that's not an strawberry bug but a gstreamer issue.
I know gapless playback works perfectly with FLAC, I mostly play FLAC, but I think it should work perfectly with Ogg Opus and Vorbis too.

**Comment by peter-joo** [comment]
I agree. I'll check the behavior on Ubuntu 18 LTS then on Monday.
And thank you for your fast reaction :)

**Comment by peter-joo** [comment]
I have checked that even though I allowed 20 seconds at the end of the first track the gap present when Strawberry changes to the 2nd track.
I used exactly the same track (Monkeys Audio, APE) on Manjaro, where the problem does not exists.

So the problem still exists on Ubuntu 18.04 LTS, therefore you should reopen the issue, please.

**Comment by jonaski** [comment]
It's probably a gstreamer bug that has already been fixed. Ubuntu 18.04 uses gstreamer 1.14 while Manjaro uses the latest 1.18.

**Comment by peter-joo** [comment]
Okay then, let's keep it like that :)
