### ISSUE TITLE
Sort playlist by multiple criteria

### ISSUE THREAD

**Issue by Offerel** [strawberrymusicplayer/strawberry#880]
**Describe the bug**
Currently I miss the possibility to sort a playlist by different search conditions at the same time. I would like to sort by "Last played" in the first place, within this sorting by album and within the album by track number. Unfortunately, I can currently only sort by "Last Played". Sorting by album or track number per album is not possible afterwards. This causes albums to be split up in the order.

**To Reproduce**
- Create a (smart)playlist
- When asked for sort condition, choose "Last played"
- Not possible to add more columns

**Expected behavior**
- Create a (smart)playlist
- When asked for sort condition, choose "Last played"
- I can add another column for album
- I can add a column for track number

**System Information:**
 - Operating system: Manjaro Testing
 - Strawberry Version: 1.0.1

**Comment by jonaski** [comment]
This isn't a bug and not a critical thing for general use so I don't have time to prioritize it.

**Comment by Offerel** [comment]
I understand the problem with the time, this seems to be a one man show to develop this software. Hopefully you will find the time later. If you can help me to find the right place to start in the source files, maybe i can help and create a pull request. Currently I'm not sure, if I`m experienced enough for this, but i can try my best. Just need a little help to start...

**Comment by jonaski** [comment]
The UI is here: https://github.com/strawberrymusicplayer/strawberry/blob/master/src/smartplaylists/smartplaylistquerysortpage.ui
Have to create a widget for sort similar to the search term, see smartplaylistsearchterm.{cpp,h,ui}

**Comment by Offerel** [comment]
OK, i ill try my luck. Its ages ago, since i last played with cpp.

**Comment by Offerel** [comment]
Have installed QT creator and cloned the repo. Will do my best to find a solution. What i want to have at the end is the something like the following SQL QUERY (lastplayed should be something like 865 days):

```
SELECT album,
       artist,
       track,
	   title,
	   lastplayed
FROM songs
WHERE album IN (
   SELECT album
	FROM songs
	GROUP BY album ,disc
	HAVING lastplayed < strftime('%s', 'now') - 74736000
	ORDER BY lastplayed
)
ORDER BY lastplayed
;
```
