### ISSUE TITLE
Subsonic: suboptimal album cover query

### ISSUE THREAD

**Issue by cquike** [strawberrymusicplayer/strawberry#885]
**Describe the bug**
I have seen that retrieving the album covers from a subsonic server takes a lot of time. Looking into the server's logs it is clear that the album cover is requested for _all_ songs, even if they belong to the same album. Therefore, when updating a subsonic collection it takes a lot of time to retrieve all song covers.

**To Reproduce**
Click on Update Catalogue in the Subsonic collection. After updating the songs, the covers are requested. Already in the message appears "Searching covers..." of n albums, where n is actually the number of songs, rather than albums.

**Expected behavior**
It would be much better if the cover is retrieved only once for each album.

**System Information:**
 - Operating system: Debian 11
 - Strawberry Version: latest from master branch in github

**Comment by cquike** [comment]
I think that the problem arises when using a MD5 token for authentication. In that case the URL for the cover as set in line 639 of file subsonic/subsonicrequest.cpp is different for each song, even if the cover_art_id is the same.

**Comment by jonaski** [comment]
Yes you are right, it's fixed now.

**Comment by cquike** [comment]
Thank you very much! That's now almost ten times faster!
