### ISSUE TITLE
Volume change is not applied to buffer when unpausing?

### ISSUE THREAD

**Issue by dicer** [strawberrymusicplayer/strawberry#892]
When I change the volume and have a song paused, then the old volume is used for a fraction of a second after unpausing.
Especially with big volume changes this is very noticeable (even sometimes by someone sleeping in the next room ;))

Reproducing should be easy:
Set the volume to something high (90%) and play a song. Then click pause. Then lower the volume to a low value (90%->10%) and click play.

I would expect the unpause to use the volume that is set and not the previous one, even if it is just for some milliseconds.
I guess there is some buffer involved and that still has the old volume applied?

My system: OpenSuse Tumbleweed, KDE, Strawberry 1.0.1
![Screenshot_20220209_112341](https://user-images.githubusercontent.com/219524/153178968-1d1db90a-429a-42be-932d-e395772e7321.png)

**Comment by jonaski** [comment]
This isn't a bug as far as I can tell. Like you say yourself, it holds a buffer so that it can resume playback instantly after unpausing. (And even if it was a bug it's in gstreamer).
I suggest that you either use the system volume, or that you stop and start playback instead.
