### ISSUE TITLE
Global keyboard shortcuts only work if main window is in focus

### ISSUE THREAD

**Issue by maxigaz** [strawberrymusicplayer/strawberry#893]
**Describe the bug**
Using i3, global keyboard shortcuts don't work if Strawberry's main window is hidden or out of focus.

**To Reproduce**
1. In Settings → Behavior, check the options "Show system tray icon" and "Keep running in the background when the window is closed."
2. In Settings → Global Shortcuts, check the option "Use X11 shortcuts when available" and assign a few shortcuts (I used media buttons such as Play/Pause).
3. Close the main window while the panel icon is still visible.
4. Press one of the shortcut buttons.

**Expected behavior**
The action assigned to the media buttons should be performed, as long as Strawberry is running in the background.

**System Information:**
 - Operating system: Manjaro Linux x86_64 with i3
 - Strawberry Version: 1.0.1

**Additional context**
While browsing the issues, I found that KDE Plasma's system settings was mentioned as a place to set global shortcuts for Strawberry, so I can imagine that that might work better. However, since I'm using i3, I don't think that's a viable option for me.

**Comment by jonaski** [comment]
This is a bug was introduced when I switched to QX11Application, it affects Qt 6.2 and higher.

**Comment by jonaski** [comment]
Apparently I'm incorrectly using the connection instead of the application root window for XGrabKey(). There isn't a way to access the root window through QX11Application, I've submitted the following to Qt: https://codereview.qt-project.org/c/qt/qtbase/+/395275
In the meantime I'll revert to using private headers.

**Comment by maxigaz** [comment]
Thank you very much! I can confirm that it works now with your fix.
