### ISSUE TITLE
Crash on Wayland 

### ISSUE THREAD

**Issue by tneo** [strawberrymusicplayer/strawberry#895]
Launching Strawberry in a Plasma Wayland session crashes Strawberry.

1. Start KDE Plasma in Wayland session.
2. Open konsole
3. Launch Strawberry

Strawberry crashes with an error message:

```
09:23:43.862 INFO  main:171                         Strawberry 1.0.1
09:23:43.862 INFO  main:172                         "openSUSE Tumbleweed 20220206 - (linux 5.16.4-1-default) [x86_64]"
09:23:43.864 WARN  unknown                          Could not find the Qt platform plugin "wayland" in "" 
09:23:43.864 ERROR unknown                          This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. 
09:23:43.864 ERROR unknown                           
09:23:43.864 ERROR unknown                          Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb. 
09:23:43.864 ERROR unknown                           
Aborted (core dumped)
```

**System Information:**
Operating System: openSUSE Tumbleweed 20220206
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.4-1-default (64-bit)
Graphics Platform: Wayland

**Comment by jonaski** [comment]
This isn't a bug, you are missing the Qt wayland plugin. The package is `qt6-wayland` on openSUSE.
