### ISSUE TITLE
100% CPU usage interfering with playback when scrobbling: ""Last.fm" "The specified configuration cannot be used. (8)"

### ISSUE THREAD

**Issue by benjitz** [strawberrymusicplayer/strawberry#898]
Hi,

This issue has been annoying me over multiple versions of Strawberry, since installation, so I've decided to try and get to the bottom of it.

After Strawberry is open for a day or so (and my computer goes to sleep and wakes up again when I do), I have to close and reopen Strawberry in order to use it.

This is because, if I play anything the next day with the instance I left running, before long the CPU of the strawberry process hits 100% after a few minutes of playback, and interacting with my computer in any way starts glitching the music as a result.

I have discovered via running Strawberry on the terminal that this is due to this error occurring when the first track of the new day is scrobbled:

11:26:40.156 ERROR ScrobblingAPI20:1021             "Last.fm" "The specified configuration cannot be used. (8)"
11:26:40.156 DEBUG ScrobblingAPI20:578              "Last.fm" Submitting scrobbles.
11:26:40.157 ERROR ScrobblingAPI20:1021             "Last.fm" "The specified configuration cannot be used. (8)"
11:26:40.157 DEBUG ScrobblingAPI20:578              "Last.fm" Submitting scrobbles.
11:26:40.158 ERROR ScrobblingAPI20:1021             "Last.fm" "The specified configuration cannot be used. (8)"
11:26:40.158 DEBUG ScrobblingAPI20:578              "Last.fm" Submitting scrobbles.
11:26:40.159 ERROR ScrobblingAPI20:1021             "Last.fm" "The specified configuration cannot be used. (8)"
11:26:40.159 DEBUG ScrobblingAPI20:578              "Last.fm" Submitting scrobbles.
11:26:40.160 ERROR ScrobblingAPI20:1021             "Last.fm" "The specified configuration cannot be used. (8)"
11:26:40.160 DEBUG ScrobblingAPI20:578              "Last.fm" Submitting scrobbles.

etc. etc, scrolling on forever. When stopping playback, the errors continue to scroll, and the only solution is to restart Strawberry, as the code seems stuck in a loop somewhere trying to submit.

!Here is a Screenshot of my Scrobbler configuration(https://user-images.githubusercontent.com/9054222/154260686-cb53bf60-1cee-4cb4-8171-0ce405a6a0b9.png)

I've only just discovered the cause of this error, so I haven't fiddled with any configuration settings as yet. As the error only seems to occur after a day of Strawberry running (or once after my computer sleeps and wakes up? not sure) Due to the nature of this bug, it might take some time to test different configurations, if you need me to do so, but I'm happy to try anything you suggest. I assume disabling Scrobbling will fix it, but I would like my tracks to be scrobbled.

On the first day of playing music when starting a new instance of Strawberry tracks submit fine and appear on the last.fm website. The tracks don't submit after a day when this error occurs, instead they are cached and are sent (with no error) when I restart Strawberry.

This error is not audio file dependent and can happen when playing any type of audio or submitting any type of id3 tag or metadata as far as I can tell. It seems to have something to do with how long Strawberry has been running for.

I am running Strawberry 1.0.1, QT 5.15.2, Ubuntu 21.10 impish (x86-64)

Prior to using Strawberry I used Clementine and this particular error never occurred with that program, if that helps.

Thanks, and let me know if you can replicate this or you need any more information/need me to try anything.

And what the best workaround would be if it would take a while to fix.

**Comment by jonaski** [comment]
I don't know why last.fm sends the "The specified configuration cannot be used." error, but it's re-sending scrobbles immediately even on error which is obviously a bug.
As a workaround you can increase the "submit scrobbles every" in the settings in the meantime. It should prevent flooding the server and strawberry freezing up.
