### ISSUE TITLE
[KDE Plasma] Fails to Open with Qt6 error on Plasma 5.24.1

### ISSUE THREAD

**Issue by sonic2kk** [strawberrymusicplayer/strawberry#899]
**Describe the bug**
Strawberry does not open after updating to Plasma 5.24.1. It returns the error `strawberry: symbol lookup error: strawberry: undefined symbol: _ZN7QLocaleC1ERK7QString, version Qt_6`.

**To Reproduce**
Attempt to open Strawberry on Plasma 5.24.1.

**Expected behavior**
Strawberry would open as normal.

**Screenshots:**
N/A

**System Information:**
 - Operating system: Arch Linux w/ KDE Plasma 5.24.1
 - Strawberry Version: 1.0.1-1

**Additional context**
N/A

**Comment by jonaski** [comment]
This isn't a Strawberry bug but a problem with compilation or packaging issue. You need to report this to Arch.
