### ISSUE TITLE
Semantic album covers' filenames stored in directories need to be made filesystem-safe

### ISSUE THREAD

**Issue by aki42** [strawberrymusicplayer/strawberry#903]
**Describe the bug**
If you opt for letting album covers be stored in directories and the filename be built following a pattern (e.g. %albumartist - %album), storing fails if the resulting filename contains a slash.

**To Reproduce**
Choose storing album covers in directories following a pattern. If the pattern contains %albumartist: listen to AC/DC. If the pattern contains %album: listen to Saga's 20/20. ;-)

**Expected behavior**
The resulting filename ought to be cleaned of characters troublesome for filesystems.

**System Information:**
 - Operating system: openSUSE Leap 15.3.
 - Strawberry Version: 1.0.1

**Comment by jonaski** [comment]
It's already cleared for problematic filesystem characters, but mistakenly not for `/` and `\` because those are valid in paths.
