### ISSUE TITLE
(macOS) Dark Mode: Sidebar Theme only correct if Strawberry has no focus

### ISSUE THREAD

**Issue by geroyche** [strawberrymusicplayer/strawberry#908]
**Describe the bug**
In MacOS Dark mode, the sidebar (contents of files, collection, playlist etc) only has the correct styling if Strawberry has no focus.
once focused, the theme is that of the light theme.
the same goes for the preferences page

**To Reproduce**
enable dark theme, focus and unfocu Strawberry

**Expected behavior**
Dark Theme should be consistent regardless of the window state

**Screenshots:**
<img width="634" alt="Screenshot 2022-02-24 at 19 56 24" src="https://user-images.githubusercontent.com/1317144/155589214-0cb38527-63cc-4243-a061-a7a720b3a569.png">
<img width="574" alt="Screenshot 2022-02-24 at 19 55 55" src="https://user-images.githubusercontent.com/1317144/155589224-d220db28-9222-455a-b966-7a98f3967021.png">
<img width="486" alt="Screenshot 2022-02-24 at 19 55 43" src="https://user-images.githubusercontent.com/1317144/155589228-6ff16c31-d04f-4363-993b-fdd513accba5.png">
<img width="601" alt="Screenshot 2022-02-24 at 19 55 36" src="https://user-images.githubusercontent.com/1317144/155589231-0a2b078a-cf4b-4f16-9732-5a5cfc977637.png">

**System Information:**
 - Operating system: MacOS Catalina
 - Strawberry Version: Version 1.0.2-9-gdcd881ba

**Comment by geroyche** [comment]
Note: this behaviour is not new... i just never got around to opening an issue until now.

**Comment by geroyche** [comment]
forgot to mention one important aspect: this only happens if the theme is changed while Strawberry is open... for me that is always, since I have Strawberry open all the time, and automatic theme switching enabled based on the day.

if i quit Strawberry and restart, the issue is gone, until the next theme change.

**Comment by jonaski** [comment]
I can't reproduce this on macOS Big Sur with the latest code of strawberry and Qt 6.3.0
Try the latest from https://builds.strawberrymusicplayer.org/macos/ those have Qt 6.3.0 now.

**Comment by geroyche** [comment]
checks out.  i have been on Version 1.0.3-26-ge05e9ea1 for a few days now, and haven't noticed it. i hadn't gotten around to doing a really thorough test, but apparently it's gone indeed.
