### ISSUE TITLE
Playback stops when unplayable file is encountered in playlist

### ISSUE THREAD

**Issue by s-fleck** [strawberrymusicplayer/strawberry#909]
When an unplayable file is encountered in the playlist, the playback just stops with an error message. This is doubly annoying since it seems m3u files also cause an error to be displayed ("appears to be a text file") and are enqueud by default if you add a whole folder from the interface (or the cli). I haven't tested it for any other file types than m3u.

I think in such cases the next song should be played. The behaviour could also reflect the setting for the "Continue to the next item in the playlist if a song is unavailable" option.

**Comment by jonaski** [comment]
The error reported `GST_CORE_ERROR_MISSING_PLUGIN` by gstreamer is a fatal error, so it's correct to stop playback and not continue.
But it should not add playlist files, I can fix that.

**Comment by s-fleck** [comment]
Thanks! 

Still have to give my two cents: I understand that aborting might be logical behaviour from a programmers perspective, but from the UX perspective I find the behaviour pretty unintutive and ...not great... . Keep in mind that music might be playing in the background somewhere, not even necessarily with a user at the machine.
