### ISSUE TITLE
Fixed layout causing problems

### ISSUE THREAD

**Issue by evertvorster** [strawberrymusicplayer/strawberry#910]
**Describe the bug**
Latte-dock overlays the "next song" button and other music controls. 
On my screen layout, in conjunction with Latte-Dock and focus being away from Strawberry, the dock is overlaying the music controls. See the screenshot for details. 

The bottom screen is HD, from my laptop, and the 4K screen is above it on a stand. It's quite a nice setup that I do not want to change.

I have tried to change the layout to have the music control buttons and spectrum analyzer above the playlist, but it seems that the layout is fixed. 
There is also no button to put the playlist at the bottom. 

**Screenshots:**
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/12045269/156165612-4cfc23e2-438d-46e5-8869-77c2ccdfd03a.png">

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.2

**Additional context**
I know this is a corner case, but surely there are other people asking for a layout that is customizable?

**Comment by jonaski** [comment]
In the past 4 years this project has been on GitHub there have been around 800 issues filed and around 30 contributions from any other contributor.
So I obviously do not have the time or resources to adjust the UI to your preference or any other user.
Also please read the GPL license:
_This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details._

**Comment by evertvorster** [comment]
Fair enough. 

Everyone is busy, and this bug report was intended to be feedback, not a demand that it be fixed right now. Take your time, chill, and maybe someday when you do have time and are looking for something to improve, you can revisit this idea.

The bug report stated that the UI layout being fixed is annoying. I would happily move around the elements to my liking myself if I were able to, and indeed in other QT projects sort of thing is possible.

As examples, in the current codebase of Amarok it is possible to move UI elements, as well as Kdenlive. Kdenlive has probably the best implementation of this idea that I have seen, just in case you would like to check it out. 

In any case, take care and have a great day!
