### ISSUE TITLE
CTRL + NUM + x keyboard shortcuts doesn't work

### ISSUE THREAD

**Issue by El-Tacos** [strawberrymusicplayer/strawberry#911]
Hello,
I would like to be able to use the CTRL + NUM + x keyboard shortcuts (x = number from 0 to 9)
We can define these shortcuts in the parameters, but it doesn't work at all.

With my old reader (DéKiBulle) I don't have that worry.

Thank you.

**System Information:**
 - Operating system: Windows 10 64bits.
 - Strawberry Version: 1.0.2 
 - Keyboard AZERTY with digital keypad

**Comment by jonaski** [comment]
Should be fixed now https://github.com/strawberrymusicplayer/strawberry/commit/8f016880af95661b1bfe1056472d7acfdbf072d4

**Comment by El-Tacos** [comment]
Hello,
With Strawberry Version: 1.0.4 this does not work either.
And now I can't configure the CTRL+NUM+x keys in the settings.
