### ISSUE TITLE
Is it normal that Strawberry downloads only 50 of my favorite album list in Qobuz?

### ISSUE THREAD

**Issue by logon84** [strawberrymusicplayer/strawberry#922]
For technical issues, questions and feature suggestions/requests please use the forum on https://forum.strawberrymusicplayer.org/

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
When updating album collection from Qobuz, only 50 albums get downloaded (I can see the text "downloading tracks from 50 albums"

**To Reproduce**
Strawberry>Qobuz>Albums>update collection -----> the albums I see in Qobuz web player starting from #50 do not show up in Strawberry

**Expected behavior**
Show full album favorite list in Album section

**Screenshots:**

**System Information:**
 - Operating system: Linux Mint 20.3
 - Strawberry Version: 1.0.2

**Additional context**

**Comment by logon84** [comment]
Still happens to me in build  1.0.2-36-gd9c92c5d

**Comment by jonaski** [comment]
The fix is in 1.0.2-38-gda1815ac
