### ISSUE TITLE
(macOS) Strawberry won't start on Monterey 12.3 on Apple Silicon

### ISSUE THREAD

**Issue by monochromec** [strawberrymusicplayer/strawberry#924]
**Describe the bug**
- Strawberry won't start on 12.3 

**To Reproduce**
- Install 1.0.2 (x86_64 image) on 12.3
- Start the app and watch beach ball spinning

**System Information:**
 - Operating system: 12.3
 - Strawberry Version: 1.0.2

**Additional context**
Please find system logs excerpt at https://gist.github.com/monochromec/a50430e2829cc541e7854f6a8bf77fd4. Let me know if further information is required.

**Comment by jonaski** [comment]
Did you enable strawberry in Security & Privacy / Accessibility and Security & Privacy / Full Disk Access?

**Comment by monochromec** [comment]
Of course :-)

**Comment by monochromec** [comment]
Upon cursory inspection of the attached logs the issue seems to point at a threading issue in the Qt layer. If a packager is reading this with access to an Intel-based Mac running 12.3: Perhaps it's worth trying to reproduce this on Intel to eliminate Rosetta as a potential root cause?

**Comment by clementine-user** [comment]
Both 1.0.2 release and 1.0.2.44.ge81dcce5-x86_64 start just fine on macOS 12.3 Intel:

![1 0 2rel](https://user-images.githubusercontent.com/6315176/160037780-d6b69821-319c-4df2-b044-4dc0788933cb.jpg)


![1 0 2-44](https://user-images.githubusercontent.com/6315176/160037590-2039faea-aa63-430f-9239-e18ff20e0399.jpg)

**Comment by clementine-user** [comment]
@monochromec, go to:

`~/Library/Application Support/Strawberry/Strawberry`

and delete any files that start with 'gst-registry'.

Copy any .db and .db.bak files to another location.

Open Terminal.app and start Strawberry:

`/Applications/Strawberry.app/Contents/MacOS/strawberry`

and see what outputs.

@jonaski, anything else he can try?

Thank you and nice work keeping this available for Mac users.

**Comment by monochromec** [comment]
Here you go: 

```
[~]$ /Applications/strawberry.app/Contents/MacOS/strawberry ; exit;
08:24:42.170 INFO  main:171                         Strawberry 1.0.2 Qt "6.2.2"
08:24:42.170 INFO  main:172                         "macOS 12.3 12.3 - (darwin 21.4.0) [x86_64]"
08:24:42.280 INFO  main:57                          TagReader worker connecting to "/private/var/folders/rg/g0gsw0k92cx3z1w8mycbh9440000gn/T/strawberry_20531616"
08:24:42.280 INFO  main:57                          TagReader worker connecting to "/private/var/folders/rg/g0gsw0k92cx3z1w8mycbh9440000gn/T/strawberry_21886919"
08:24:42.284 INFO  main:57                          TagReader worker connecting to "/private/var/folders/rg/g0gsw0k92cx3z1w8mycbh9440000gn/T/strawberry_33275566"
08:24:42.287 INFO  GstStartup:53                    Creating GLib main event loop.
08:24:42.290 INFO  main:57                          TagReader worker connecting to "/private/var/folders/rg/g0gsw0k92cx3z1w8mycbh9440000gn/T/strawberry_49141144"
```
Same symptoms as before though.

**Comment by clementine-user** [comment]
This is the startup on Intel with the latest release and dev build respectively:

```
$ /Applications/strawberry.app/Contents/MacOS/strawberry
19:15:57.297 INFO  main:171                         Strawberry 1.0.3 Qt "6.2.4"
19:15:57.298 INFO  main:172                         "macOS 12.3 12.3 - (darwin 21.4.0) [x86_64]"
19:15:57.445 INFO  main:57                          TagReader worker connecting to "/private/var/folders/zt/b5g7q9994dq4vl0f61tv5h000000gn/T/strawberry_3840739"
19:15:57.454 INFO  main:57                          TagReader worker connecting to "/private/var/folders/zt/b5g7q9994dq4vl0f61tv5h000000gn/T/strawberry_36057343"
19:15:57.458 INFO  GstStartup:53                    Creating GLib main event loop.
19:15:57.622 INFO  Player:927                       Registered URL handler for "subsonic"
19:15:57.627 INFO  Player:927                       Registered URL handler for "tidal"
19:15:57.640 INFO  Player:927                       Registered URL handler for "qobuz"
19:15:58.556 WARN  applicationDidFinishLaunching:]:157 Failed to start media key monitoring
```

and

```
$ /Applications/strawberry.app/Contents/MacOS/strawberry
19:18:47.039 INFO  main:171                         Strawberry 1.0.3-3-g5b8e9066 Qt "6.2.4"
19:18:47.039 INFO  main:172                         "macOS 12.3 12.3 - (darwin 21.4.0) [x86_64]"
19:18:47.182 INFO  main:57                          TagReader worker connecting to "/private/var/folders/zt/b5g7q9994dq4vl0f61tv5h000000gn/T/strawberry_52994016"
19:18:47.184 INFO  main:57                          TagReader worker connecting to "/private/var/folders/zt/b5g7q9994dq4vl0f61tv5h000000gn/T/strawberry_5275282"
19:18:47.185 INFO  GstStartup:53                    Creating GLib main event loop.
19:18:47.330 INFO  Player:927                       Registered URL handler for "subsonic"
19:18:47.334 INFO  Player:927                       Registered URL handler for "tidal"
19:18:47.347 INFO  Player:927                       Registered URL handler for "qobuz"
19:18:48.243 WARN  applicationDidFinishLaunching:]:157 Failed to start media key monitoring
```

Hopefully this gives @jonaski some clues.

**Comment by jonaski** [comment]
Someone with a Apple Silicon mac needs to debug this. Although it's very likely the bug is in Qt itself or Rosetta. Probably better to provide a separate ARM release.
I made the following bounty, those that want the issue fixed can donate and someone might pick it up:
https://app.bountysource.com/issues/106516337-strawberry-won-t-start-on-monterey-12-3-on-apple-silicon

**Comment by monochromec** [comment]
Experimental build 1.0.4-2-gdeecafa0 seems to fix this. Closing this for now, if it surfaces again I'll reopen the issue.
Let me know if more info is needed for further RCA.

**Comment by monochromec** [comment]
Save the bounty :-).

**Comment by monochromec** [comment]
PS: A little bit of regression testing showed that this doesn't seem to be build-related as 1.0.4 works again after a recent upgrade of Monterey to 12.3.1.
