### ISSUE TITLE
Corrupted backgroung image strawbs.png if dark theme is enabled in KDE

### ISSUE THREAD

**Issue by adem4ik** [strawberrymusicplayer/strawberry#926]
**Describe the bug**
Background image strawbs.png gets corrupted if KDE has dark theme enabled

**To Reproduce**
- Switch to dark theme in KDE
- Set playlist's background image to `A taste of Strawbs`

**Expected behavior**
Same quality of background image as in light theme

**Screenshots:**
![image](https://user-images.githubusercontent.com/4707112/160150378-fd52f421-958a-4935-a9b4-e4e8c9646f71.png)

**System Information:**
 - Operating system: Manjaro with KDE Plasma 5.24.3
 - Strawberry Version: 1.0.3-1-g49726701 (latest git version from AUR)

**Additional context**
I guess the problem comes from the transparency of the original PNG - https://github.com/strawberrymusicplayer/strawberry/blob/master/data/pictures/strawbs.png After deleting transparency from this PNG, I got the following result: 
![image](https://user-images.githubusercontent.com/4707112/160153208-278a1af0-8cbb-40f9-9711-67f42c10c235.png)

And btw it looks corrupted on GitHub too, if it has dark theme enabled:
![image](https://user-images.githubusercontent.com/4707112/160153943-2447f6b9-ba09-4554-b14b-4692ef672662.png)

**Comment by jonaski** [comment]
I don't think there is an fix for this, the image doesn't work with a black background.
