### ISSUE TITLE
I can't get the tidal login working

### ISSUE THREAD

**Issue by ChrisOboe** [strawberrymusicplayer/strawberry#927]
The tidal login doesn't seem to work for me. 
I tried both logging in via OAuth and Token/Username/Password. Both with client id i get in the official tidal browser client as with ones i found in the internet. 

With OAuth the Browser opens a tidal webpage stating "Something went wrong. Please try again. If the error persists, contact customer support." 

With Token/Username/Password i get a message from Strawberry "Authentication failure: Client not found (401) (8003)"

**Comment by jonaski** [comment]
This isn't customer support. Login works when testing it here, so unless there is more information is provided proving this is a bug there is not much I can do.
