### ISSUE TITLE
[Feature Request] Ability to make smart playlists from existing regular playlists

### ISSUE THREAD

**Issue by quietmansoath** [strawberrymusicplayer/strawberry#933]
Feature request. Looks like you can make a smart playlist based on every aspect of the file _accept_ whether or not it sits in another playlist, like one I've saved and imported (for example, a manually made .m3u file). Can you consider adding this feature?

**Comment by jonaski** [comment]
I don't take feature requests or answer questions about new features. This doesn't mean I won't add new features, it just means I don't have time to take new feature requests.
