### ISSUE TITLE
audio output device switching

### ISSUE THREAD

**Issue by Heny67** [strawberrymusicplayer/strawberry#935]
For technical issues, questions and discussion please use the forum on https://forum.strawberrymusicplayer.org/
Any issues related to feature requests will be closed. See the README for more details.

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
The player sets which audio output device to play on. When the monitor turns off (switches to power save mode), the music continues to play. But when the monitor wakes up, the player switches to another audio output device, even though it is clearly specified in the settings.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

I don't think the player should switch output after the monitor wakes up..

**Screenshots:**

**System Information:**
 - Operating system:Ubuntu mate 20.04
 - Strawberry Version:1.0.4

**Additional context**

**Comment by jonaski** [comment]
Strawberry doesn't do automatic switching of devices, this is either in GStreamer, hardware level or other software related to audio. I'm not familiar if PulseAudio or Pipewire has something like this.
