### ISSUE TITLE
Strawberry fails on make deploy in macOS 12.3.1

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#936]
I'm following all the steps from https://github.com/strawberrymusicplayer/strawberry/wiki/Compile-and-install-on-macOS-using-macports

Everything goes well except on the last step make deploy it complains of the missing libgioopenssl module:

`Log:  to "@executable_path/../Frameworks/libgnutls.30.dylib"
"install_name_tool -id @executable_path/../Frameworks/libgnutls.30.dylib strawberry.app/Contents/Frameworks//libgnutls.30.dylib"
Log: Using otool:
Log:  inspecting "strawberry.app/Contents/Frameworks//libgnutls.30.dylib"
ERROR: Missing GIO module "libgioopenssl"
Missing GIO modules.
make[3]: *** [CMakeFiles/deploy] Abort trap: 6
make[2]: *** [CMakeFiles/deploy.dir/all] Error 2
make[1]: *** [CMakeFiles/deploy.dir/rule] Error 2
make: *** [deploy] Error 2`

Any idea of what we can do here?

Thanks.

**Comment by jonaski** [comment]
Strawberry now deploys both libgiognutls and libgioopenssl, but you only need one of them.
Change this line:
https://github.com/strawberrymusicplayer/strawberry/blob/master/3rdparty/macdeployqt/shared.cpp#L1230
to `const QStringList giomodules = QStringList() << "libgiognutls.so";`

**Comment by jonaski** [comment]
You probably have to remove some of the plugins from the gstreamer plugin list here: https://github.com/strawberrymusicplayer/strawberry/blob/master/3rdparty/macdeployqt/shared.cpp#L1272 too as macports does not have all of them.

**Comment by llucps** [comment]
OK I got it working at the end by removing as you said:

`const QStringList giomodules = QStringList() << "libgiognutls.so";` line 1230

And from `QStringList gstreamer_plugins = QStringList()` removing these:
```
libgiognutls
libgstbs2b
libgstdash
libgstfaac
libgstfdkaac
libgstmusepack
libgstopenmpt
```
I don't know it this could be addressed in the code by removing them or at least if using macports avoid to include them.. and also would this should be reflected on the https://github.com/strawberrymusicplayer/strawberry/wiki/Compile-and-install-on-macOS-using-macports ?

Thanks.

**Comment by jonaski** [comment]
Try this https://github.com/strawberrymusicplayer/strawberry/commit/edd088927da4cff3d23f4d7f553d648cca0d25bc

**Comment by llucps** [comment]
Yes it worked. It just complain of those missing plugins, but it compiled successfully, including creating the DMG and then I tried to play songs which it also worked.

`ERROR: Missing gstreamer plugins QList("libgstbs2b", "libgstdash", "libgstfaac", "libgstfdkaac", "libgstmusepack", "libgstopenmpt", "libgstopusparse")
Log: Created configuration file: "strawberry.app/Contents/Resources/qt.conf"
Log: This file sets the plugin search path to "strawberry.app/Contents/PlugIns"
Log: Using strip:
Log:  stripped "/Users/llucps/projects/strawberry/build/strawberry.app/Contents/MacOS/strawberry"
[100%] Built target deploy`

Thanks!.
