### ISSUE TITLE
Setting "Save ratings to song tags when possible" is not enabled, but Strawberry still wrote rating tags to the audio files

### ISSUE THREAD

**Issue by magicgoose** [strawberrymusicplayer/strawberry#940]
**Describe the bug**
Strawberry writes rating tags to audio files even if told not to do this. (FMPS_RATING)

**To Reproduce**
Ensure that setting "Save ratings to song tags when possible" is not enabled.
Set rating of a song.

**Expected behavior**
Rating is saved into Strawberry database and only it.

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.4

**Comment by jonaski** [comment]
Where do you set the rating?
I can't reproduce this. When setting the rating through the playlist rating column does not save the rating to tags unless the setting is enabled.
It's possible to set the rating in the tag editor too, which will of course save to tags.

**Comment by magicgoose** [comment]
> Where do you set the rating? I can't reproduce this. When setting the rating through the playlist rating column, it does not save the rating to tags unless the setting is enabled. It's possible to set the rating in the tag editor too, which will of course save to tags.

In the tag editor. I wasn't aware that it would work differently. This is very counter intuitive.
