### ISSUE TITLE
PulseAudio Stream and Strawberry Volume Control

### ISSUE THREAD

**Issue by J-J-Chiarella** [strawberrymusicplayer/strawberry#948]
**Describe the bug**

The volume control within the application does not move in tandem with the PulseAudio volume stream for Strawberry. This means that audio has to jump through an additional "hoop" of digital processing and that one cannot control the volume of Strawberry both on a mixer (e.g., pavucontrol) and in the program Strawberry itself.

I reported this bug to Clementine several years ago (before it was abandoned). It seems that this hasn't changed.

**To Reproduce**

Play any audio through Strawberry. Move the volume slider within the program Strawberry. Open a sound mixer for the entire desktop (e.g., pavucontrol).  Note that the two respective volume controls do not synchronize.

**Screenshot**

![Strawberry_volume_pulse](https://user-images.githubusercontent.com/12409848/166838212-2cb0c97a-40fe-4c28-8e34-35e2a9ddc184.png)

**Expected behavior**

The volume sliders should move in tandem for both the slider in the GUI of Strawberry and for the volume slider within a PulseAudio mixer. This is the behavior of Kodi, VLC, Firefox, and every other program I ever tried when investigating this.

**System Information:**
 - Operating system: Ubuntu 21.10
 - Strawberry Version: 1.0.4

**Comment by jonaski** [comment]
This isn't a bug. I already answered this in https://github.com/strawberrymusicplayer/strawberry/issues/473

**Comment by J-J-Chiarella** [comment]
I am sorry. I couldn't find my last report of this bug on Strawberry and I missed the follow-up that this is a gstreamer bug, closing that issue.
