### ISSUE TITLE
Raspberry Pi OS: Compile error: libSM.so and libICE.so not found

### ISSUE THREAD

**Issue by kjcole** [strawberrymusicplayer/strawberry#949]
**Describe the bug**

On a Raspberry Pi 4 with a fresh install or Raspberry Pi OS, and following the directions for [Compiling on Debian](https://github.com/strawberrymusicplayer/strawberry/wiki/Compiling-on-Debian), the `make` fails to find the libraries.

**To Reproduce**

```
$ make -j$(nproc)
...
make[2]: *** No rule to make target '/usr/lib/arm-linux-gnueabihf/libSM.so', needed by 'strawberry'.  Stop.
...
make[2]: *** No rule to make target '/usr/lib/arm-linux-gnueabihf/libICE.so', needed by 'strawberry'.  Stop.
```

**Expected behavior**
I expected it to find the libraries. :wink:

**Quick fix**
```
$ sudo -i
$ cd /usr/lib/arm-linux-gnueabihf/
$ ln -s libSM.so.6.0.1  libSM.so
$ ln -s libICE.so.6.3.0 libICE.so
$ exit
```

**System Information:**

 - Operating system:

```
$ lsb_release -a
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

$ uname -a
Linux xxxxxx 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
```
 - Strawberry Version:
```
$ strawberry --version

Strawberry 1.0.4-19-gedd08892
```

**Comment by jonaski** [comment]
Why is this a Strawberry bug?

**Comment by kjcole** [comment]
I'm hoping that either Strawberry maintainers or libice6 maintainers and libsm6 maintainers will recognize that something isn't right. I'm hoping that the maintainers don't just point their fingers at the others  and say "It's not OUR problem."

Since I did not encounter any problem until I attempted to build Strawberry, I filed a bug report here first. Two minutes ago, I filed bug reports against libice6 and libsm6. But if the maintainers there say "won't fix", then the problem remains that Strawberry won't compile without the symbolic links. (These bugs could affect other packages, but I reported where I encountered it.)

Perhaps the fix is something as simple as adding a caveat to the build instructions saying "If you encounter these errors, create the following symbolic link(s)."

**Comment by jonaski** [comment]
I just don't see how or why this is a library, or strawberry bug.
Strawberry links to X11 libraries. It uses the libraries returned by cmake's find_package, which is what's found on your system.
This sounds like either something is broken on your system, or it's a distribution/packaging specific issue.
If there are missing or broken symbolic links we should not be responsible for fixing that, or explain how to fix a system in the build instructions. We don't even have build instructions specific for Raspbian.
There is a CI here compiling on 14 different distros/versions including debian and ubuntu and none of those have this issue.
I think it's better to ask for help, or file a bug report to the specific linux distro where the problem occurs.

**Comment by kjcole** [comment]
I just got word from the Debian maintainers of the two libraries. According to them, there's a bug in your documentation:

The symbolic links required by the `make` are only provided in the development packages `libice-dev` and `libsm-dev`. However, [your documentation](https://github.com/strawberrymusicplayer/strawberry/wiki/Compiling-on-Debian) does not include those libraries in the list of required dependencies. So adding them to the `apt-get install -y...` list of dependencies would solve the issue.
