### ISSUE TITLE
Subsonic not scrobbling

### ISSUE THREAD

**Issue by tomatgithub0** [strawberrymusicplayer/strawberry#950]
**Describe the bug**
When using subsonic API to stream, played songs won't be scrobbled even with [Server-side Scrobbling] option turned on.

**To Reproduce**
1. Connect to a subsonic server.
2. Turn on [Server-side Scrobbling].
3. Start playing.

**Expected behavior**
Playback history logged in the subsonic server.

**System Information:**
 - Operating system: Ubuntu 22.04 LTS
 - Strawberry Version: Version 1.0.4

**Additional context**
I've tried several different subsonic servers but issue stays.

**Comment by jonaski** [comment]
The scrobbler needs to be enabled in the scrobbler settings and subsonic checked under sources. Also check the submit delay setting.
If it still doesn't work take a screenshot of the scrobbler settings.

**Comment by tomatgithub0** [comment]
Thanks for the feedback I'll try just that

**Comment by tomatgithub0** [comment]
Tried the settings and its still not working.
![Screenshot from 2022-05-07 18-24-25](https://user-images.githubusercontent.com/70781801/167241795-e71e5293-d711-46ae-9e55-60ad50d5ddfb.png)

**Comment by tomatgithub0** [comment]
Sorry, just realized that it is working now after rebooting my PC.

Thank you for your time!
