### ISSUE TITLE
Horizontal scrolling does not affect currently playing track

### ISSUE THREAD

**Issue by glaubersm** [strawberrymusicplayer/strawberry#952]
**Describe the bug**
All tracks of a playlist are horizontally scrolled, except the currently playing one.

**To Reproduce**
1. add some tracks to the playlist
2. play any track
3. scroll the playlist horizontally during playback

**Expected behavior**
all tracks of a playlist should be horizontally scrolled

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.4 built against Qt 6

**Additional context**
I have recored a video showing the bug:
https://youtu.be/DzCMQ2u_xUo

**Comment by jonaski** [comment]
Thanks for reporting that, the bug was introduced almost a year ago in https://github.com/strawberrymusicplayer/strawberry/commit/584f5e5935563df11cbdf496bf0792d69cf37dd5 (June 2021).

**Comment by glaubersm** [comment]
Thank you for your super fast fix, Jonas, You are an awesome software developer. :)
