### ISSUE TITLE
Saving CUE playlist generates empty file

### ISSUE THREAD

**Issue by Cknight70** [strawberrymusicplayer/strawberry#953]
**Describe the bug**
When pressing the save button to save a playlist, I select cue format. The resulting file on my file system is empty, reads 0 bytes and nothing is shown in text editor.

**To Reproduce**
I add a collection of songs to the main window (drag and drop from my file manager) and then click the "save playlist" button, in the save file dialog I select cue.

**Expected behavior**
Generated file should be in cue format with playlist information. I also exported in xspf and m3u and this generated a correct format for those.

**Screenshots:**
![image](https://user-images.githubusercontent.com/28763729/167787153-6b40872b-58e1-4ebe-8039-768f5618e41c.png)

**System Information:**
 - Operating system: Arch Linux (Kernel 5.17.5.arch1-2)
 - Strawberry Version: 1.0.4 (installed from AUR)

**Comment by jonaski** [comment]
Saving to cue has never been implemented, I can remove it from the extensions.
