### ISSUE TITLE
Blurry strawberry icon on KDE 5.24.4 (Debian Bookworm)

### ISSUE THREAD

**Issue by llucps** [strawberrymusicplayer/strawberry#954]
This is just cosmetic, but for some reason the icon on task switcher  on Debian Bookworm and KDE 5.24.4 looks blurry. It looks like is not using the right icon?

I'm using a custom task switcher called MediumDefault https://store.kde.org/p/1367158

![Screenshot_20220512_181611](https://user-images.githubusercontent.com/25823659/168126189-f399ab71-580b-4dd9-91d2-2bf73e0ba527.png)

As a side note I'm also using latte-dock, just in case it's important.

Thanks

**Comment by jonaski** [comment]
I have no idea.
There should be a 3 icons installed, 48x48, 64x64 and 128x128.
On my system they are in:
```
/usr/local/share/icons/hicolor/64x64/apps/strawberry.png
/usr/local/share/icons/hicolor/48x48/apps/strawberry.png
/usr/local/share/icons/hicolor/128x128/apps/strawberry.png
```
Do you have them?
If so can you check if the other applications have some additional icons, svg perhaps?

**Comment by jonaski** [comment]
Looks to me like the MediumDefault thing uses the application icon directly and not the installed icons. Most other applications other than KDE ones have the same issue.
But I can increase the icons to include the 128x128 ones.

**Comment by llucps** [comment]
Yep that was it :) thanks!
