### ISSUE TITLE
Global shortcuts through kglobalaccel kill ctrl F systemwide

### ISSUE THREAD

**Issue by quesada** [strawberrymusicplayer/strawberry#959]
**Describe the bug**
Global shortcuts through kglobalaccel kill ctrl F systemwide

**To Reproduce**
Set any global shortcut using kglobalaccel. You will notice that while it does as expected, it also nullifies ctrl F on all apps. Which is a big problem. Restarting plasma with strawberry not working doesn't fix it, only a reboot. So it's a 'nuclear' bug.

**Expected behavior**
get the global shortcut to work system wide

 - Operating system: Manjaro
 - Strawberry Version:Version 1.0.4

**Additional context**
I'm using openbox instead of kwin. Which does deal with global shortcuts

**Comment by jonaski** [comment]
CTRL + F works fine here both in Strawberry and in other applications with kglobalaccel enabled and custom shortcuts set.
I don't think this is a Strawberry bug.
