### ISSUE TITLE
Removing duplicates also removes missing songs.

### ISSUE THREAD

**Issue by poikilos** [strawberrymusicplayer/strawberry#960]
**Describe the bug**
Removing duplicates also removes missing songs.

**To Reproduce**
- Add 2 songs to a playlist. Add the second song twice.
- Move or rename the first song.
- Open the playlist.
- Remove duplicates.
- It will not only remove duplicates but also the renamed/moved song.

**Expected behavior**
The feature should only remove duplicates.
- There is already a separate feature for removing missing songs.
- There are at least a couple legitimate reasons for keeping missing songs in a playlist:
  - The song being having a gray font (as it does currently) indicates to the user that the song is missing or renamed, which may be an accident). Therefore, removing the missing song automatically is a form of data loss (metadata loss, specifically)--The user isn't informed of the missing song.
  - I keep a playlist of 0of5stars, so if a song is on there and is missing, I'll know not to re-download it if I sync from OCReMix or some bulk music site, etc.  

**System Information:**
 - Operating system: Devuan 4 Chimera (based on Debian 11 Bullseye)
 - Strawberry Version: 1.0.4 (Flatpak)

**Additional context**

**Comment by jonaski** [comment]
It removes duplicate songs based on tags, whether the artist/album/title is identical, not filenames. It has always been like that. It's the intended behavior.

**Comment by poikilos** [comment]
@jonaski What you are describing isn't the behavior I described. I didn't mention conditions for determining duplicates.

The "To Reproduce" steps would work even if you changed: ~~"Add 2 songs to a playlist. Add the second song twice."~~ to "Add 1 song to an empty playlist."

**Comment by jonaski** [comment]
Unable to reproduce any issues related to removing duplicates, it correctly removes only one playlist entry of the second song.

**Comment by jonaski** [comment]
If's possible that a song disappears from the playlist, if it's a collection song and both the "fingerprinting & tracking" and "Mark disappeared song" are turned off and there aren't any rowid's matching the playlist item anymore, but that has nothing to do with the remove duplicates feature.

**Comment by poikilos** [comment]
Ok, I can't reproduce the issue. I tried closing & reopening the program and still cannot. This happened a while back and may have been in a previous version. Thanks for the details.
