### ISSUE TITLE
(macOS) Context menus don't close after app switched focus

### ISSUE THREAD

**Issue by Volodymyr-13** [strawberrymusicplayer/strawberry#966]
**Describe the bug**
Context menus don't close after switched to other apps

**To Reproduce**
Right click to open any menu, switch from app to any other, notice menu stays on top of all windows. 

**Expected behavior**
Menu doesn't block other apps.

**Screenshots:**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/3391456/169329040-b4967c5c-7d69-485d-9579-00c5d7bd0f69.gif)

**System Information:**
 - Operating system: macOS 12.5
 - Strawberry Version: 1.0.4

**Comment by jonaski** [comment]
This is a Qt bug, same as https://github.com/strawberrymusicplayer/strawberry/issues/538, it was fixed previously, but looks like they have changed the code so it breaks again.

**Comment by jonaski** [comment]
Bug reported here: https://bugreports.qt.io/browse/QTBUG-105474
