### ISSUE TITLE
Compiling on Debian

### ISSUE THREAD

**Issue by jsmr1** [strawberrymusicplayer/strawberry#967]
Compiled it yesterday: https://github.com/strawberrymusicplayer/strawberry/wiki/Compiling-on-Debian
with no problems 

OS: LMDE 5 Elsie
 
 ...
 cmake ..
 make -j$(nproc) 
 sudo make install

Maybe my $nproc was empty. "make install" copies the whole source tree to /usr/local/bin/strawberry.

my workaround: copy binaries manual to /usr/local/bin

**Comment by jonaski** [comment]
It works fine in the CI
