### ISSUE TITLE
Cover for multiple disks of the same album

### ISSUE THREAD

**Issue by prestidigitonium** [strawberrymusicplayer/strawberry#969]
**Describe the bug**
If I have an album folder with more than one CD, I have to put the same cover in all folders in order to get the image in the strawberry library.

**To Reproduce**
Add an album with more than one CD to the library

**Expected behavior**
It should less expensive to automatically use the same image for all CD of the same album, so we don't have multiple copies of the same file in filesystem.

**Screenshots:**
![image](https://user-images.githubusercontent.com/63223659/170213544-cb265beb-f92d-4ffe-8fd0-dd0dee1f4cce.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 1.0.4

**Comment by jonaski** [comment]
Only images from the same directory where the audio files are picked, this is intentional and not a bug.
