### ISSUE TITLE
Dark theme isn't applied to menu bar

### ISSUE THREAD

**Issue by prestidigitonium** [strawberrymusicplayer/strawberry#971]
**Describe the bug**
When I choose a black color for background and white color for foreground, the menu bar fonts are black.

**To Reproduce**
Tools > Preferences > Appearance > Colors
Set Custom color set:
foreground -> white
background -> black

**Expected behavior**
When I choose a black color for background and white color for foreground, the menu bar fonts should be white

**Screenshots:**
![Istantanea_2022-05-29_14-18-08](https://user-images.githubusercontent.com/63223659/170867642-3ce75945-2aea-4d52-af76-dcb825707df9.png)

**System Information:**
 - Operating system: Arch Linux (system updated)
 - Strawberry Version: 1.0.4 (latest build in repositories)

**Additional context**
I tried to change style from default, to fusion, to window: the problem is not solved. I tested Clementine too and it seems it doesn't have this problem.

**Comment by jonaski** [comment]
The style controls this, so it depends on what Qt style is in use, it works with Breeze, not Fusion or most of the other styles, but setting a background color to black rarely works well with most styles.

**Comment by prestidigitonium** [comment]
I have breeze selected and any other Qt window is using correctly breeze but Strawberry can't apply/recognize breeze
![image](https://user-images.githubusercontent.com/63223659/170948559-85d83aa2-b9d2-41c0-a6d2-da581fa6fc54.png)
I installed the full breeze package (breeze-gtk, breeze-icons and breeze) and Strawberry is installed from official repository (so no snap/flatpak), I don't know why the breeze theme is not recognized. I also rebooted after installation.

**Comment by prestidigitonium** [comment]
**If it can help for future people**: the strawberry build in Arch Linux repository is based on Qt6, so I needed qt6ct to select the theme but the problem was that there isn't the breeze theme for qt6 yet (you can use Fusion but it produces some glitches), so if you need strawberry with black theme in Arch Linux you need the qt5 build from AUR and then you can use qt5ct to set Breeze dark theme.
