### ISSUE TITLE
Windows: Edit smart playlist window has visual glitch

### ISSUE THREAD

**Issue by bhankas** [strawberrymusicplayer/strawberry#976]
**Describe the bug**
On Windows 11 clicking on 'Edit Smart playlist' button creates a window that is functional but has visual glitch.

**To Reproduce**
Click on 'Edit smart playlist' button.

**Expected behavior**
The window should look like normal window without any artifact.

**Screenshots:**
![image](https://user-images.githubusercontent.com/24254289/173218377-639abffe-f3d0-418f-96e9-f18aef573338.png)

**System Information:**
 - Operating system: Windows 11
 - Strawberry Version: 1.0.5 MSVC

**Additional context**
My WIndows 11 is set to dark theme systemwide in system settings. No appearance settings are changed in Strawberry itself.

**Comment by jonaski** [comment]
Unable to reproduce this, tested both on Windows 10 and 11, no issues with any of the dark themes. It's probably something locally on your Windows installation.
