### ISSUE TITLE
Songs order loading from files

### ISSUE THREAD

**Issue by prestidigitonium** [strawberrymusicplayer/strawberry#977]
**Describe the bug**
When I open a list of songs from files, they are not queued in the right order. They are 1, 10, 11, 11111, 2 , 3 , 4.

**To Reproduce**
Go in File tab on the left menu, open a file list with right click as in the following image.

**Expected behavior**
Songs should be listed with number 10 after 9, and not 10 after 1

**Screenshots:**
![Istantanea_2022-06-12_09-28-08](https://user-images.githubusercontent.com/63223659/173222414-c0af998b-ece8-4dbb-b514-05421922ad24.png)

**System Information:**
 - Operating system: Arch Linux (kernel 5.15.45-1-lts)
 - Strawberry Version: 1.0.5

**Additional Information:**
Maybe it's not a problem of file renaming (because in linux filesystem they are ordered in the right way)
1-1
1-2
...
1-10
Maybe the way files are ordered is different from the way used by linux filesystem.

**Comment by jonaski** [comment]
They are added in the same order as they are listed, alphabetically. Normally you prefix the filenames with 01, 02, 03, etc to avoid this. It works fine here. Perhaps some locale settings are affecting how the files are sorted for you, but if the files are 1, 2, 3, etc then 11 will be before 2, so then that's your problem.

**Comment by prestidigitonium** [comment]
mm so

**Comment by prestidigitonium** [comment]
so, it's normal that they are listed correctly even inside strawberry in the file tab (but not on the right)?
![image](https://user-images.githubusercontent.com/63223659/173381711-4348c331-4901-41ac-8e6f-e72f9f72a17b.png)

**Comment by jonaski** [comment]
I can reproduce the issue when using the same filenames, when you use the right click options to add songs to the playlist it uses `std::sort` but not when dragging with mouse.
Basically `std::sort` sorts differently than the model, I wonder if we could just remove the `std::sort`.

**Comment by jonaski** [comment]
I did it in https://github.com/strawberrymusicplayer/strawberry/commit/1d5db1446d4cb4baeb302d43ee8265e78044e3f6 because of issue https://github.com/strawberrymusicplayer/strawberry/issues/449

**Comment by jcrben** [comment]
@jonaski it looks like you added `std::sort`?

I got this same issue in 1.07 when I tried to `Add folder` 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/5614134/184560356-e4e07688-022e-439a-b701-4a75390b2e0f.png">

I downgraded to 1.06 since that was the context of this bug and found a workaround by dragging from the file list over into the playlist.
<img width="1792" alt="strawberry-screenshot" src="https://user-images.githubusercontent.com/5614134/184560387-240b0368-7984-4a89-9c7b-74b78b91f873.png">
