### ISSUE TITLE
Strawberry can not access smb shares on Fedora 36

### ISSUE THREAD

**Issue by FireDumpster** [strawberrymusicplayer/strawberry#985]
For technical issues, questions and discussion please use the forum on https://forum.strawberrymusicplayer.org/
Any issues related to feature requests will be closed. See the README for more details.

Check the Changelog to see if the issue is already fixed:
https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog

If it's fixed, try the latest development build from: https://builds.strawberrymusicplayer.org/

**Describe the bug**
Strawberry can not access smb shares on Fedora 36.

**To Reproduce**
In Settings, go to Collection. Start the process of adding a location to the collection by clicking the "Add new folder" button. Browse through the mount / smb share, selecting the proper folder and click the Select button. The entry that appears in the Collection list just shows the blue folder icon, but where the location path would be shown is blank. Click Ok to go back to the main window and the collection is still empty and there are no messages at the bottom about updating the library/collection.

**Expected behavior**
After clicking the Select button, the Collection list should show the path you just gave it, and Strawberry should start updating the collection/library.

**Screenshots:**
Could provide one of the Collections list if what I described isnt understood, but not familiar with a good, safe, privacy friendly site to use.

**System Information:**
 - Operating system: Fedora 36 (all updates through today)
 - Strawberry Version: 1.0.5

**Additional context**
I've been using Strawberry since version 1.0.4 on Fedora 35 first, then 36 when it was released. Adding an smb share in Strawberry always worked for me until about a couple months ago when Fedora 35 (right before 36 was released) updated samba to 4.15.7. When that update was first released, Files/Nautilus and most software could no longer access samba shares until sometime later, some updates resolved the issue. This was days before Fedora 36 was released. Fedora 36 was released, Fedora itself (Files/Nautilus) does not have the issue, but the issue is back with Strawberry somehow. 

-Clementine has the same exact problem.
-Lollypop (music player) had the same problem when samba was updated to 4.15.7 until Lollypop was updated to I believe it was version 1.4.34.
-I've tried Strawberry 1.0.4 and 1.0.5 and still experience this problem on Fedora 36.
-This reddit post has four good links to bug reports on gitlab, bodhi, and bugzilla when the issue first happened in Fedora 35 and was resolved:
https://www.reddit.com/r/Fedora/comments/ufxnaa/cant_connect_to_your_samba_server/

I have machines running updated Fedora 35 and updated Fedora 36. Everything is fine on updated Fedora 35 now, but in Fedora 36 (new install or updated install) Strawberry has never been able to access smb shares using versions 1.0.4 and 1.0.5. And I believe the issue will be related to the changes necessary to other software regarding the samba update.

**Comment by jonaski** [comment]
Strawberry uses the standard native dialogs, so this is a bug in whatever native dialog you use. (gtk most likely). It's not the first time it's buggy.
You can probably workaround the bug by passing `QFileDialog::DontUseNativeDialog` to QFileDialog::getExistingDirectory here:
https://github.com/strawberrymusicplayer/strawberry/blob/master/src/settings/collectionsettingspage.cpp#L124

**Comment by FireDumpster** [comment]
Im guessing that would be changing code and recompiling? That sounds like a good test, but Im not familiar with that process and would need to research how to do that.

Im a little confused, because if something is wrong in gtk with the native dialog, I would think the Files program would have the same issue. It brings up the same dialog box with a Select button, but I can access and open files through it. It seems only Strawberry on my system has the issue, but I see what you are saying about Strawberry using the native system dialog. I followed your advice that the issue is with gtk, so I posted it to bugzilla here:
https://bugzilla.redhat.com/show_bug.cgi?id=2098295

First time doing that. As far as I can tell, nothing has been done to this report since it was opened five days ago. This must be a pretty common issue if the native dialog doesnt work right with smb, and this has been an issue for a couple months, so that seems odd. Can you check that post out and see if I posted it correctly?

**Comment by areksobiczewski** [comment]
@FireDumpster 
Your GTK bug about the native system dialog has been closed automatically by the Fedora team. Somehow you posted it when Fedora 36 went into end-of-life soon after your bug report. Bad luck.
Could you please open a new ticket for Fedora 38?* 

Did you manage to solve an issue with samba mounts thru Nautilus (Fedora's file manager for GNOME) and Strawberry according to jonaski's advices? I'm not sure whether I need to complie the player again or where to put the config line he's mentioned.
I need to resolve this somehow since I moved my whole music collection to an external NAS...

*) Im on Fedora 37 and the bug with GTK still exists. I conclude that it must be also the case in Fedora 38 and I too would like it to be resolved.

**Comment by areksobiczewski** [comment]
@FireDumpster 
I did some digging and found a good workaround. It should work on other thatn Fedora Linux OSes.

1) Unmount your regular samba share in Nautilus.
2) Mount your share via command line:
`sudo mount.cifs //XXX-your-samba-share-path  /XXX/SMB_Raspi -o user=XXX`
Nautilus will mount your share twice now. In it's window you'll see a share under the name Nautilus detecs (like always), and a new - in my case "SMB_Raspi".
3) The above new share "SMB_Raspi" can be used in Strawberry as a regular folder, beause it's just a part of your filesystem now. GTK issues gone this way.
