### ISSUE TITLE
 Smart playlists which plays whole albums instead of tracks

### ISSUE THREAD

**Issue by evmcl** [strawberrymusicplayer/strawberry#992]
Currently all the smart playlists operate on tracks only, and I don't think there is a way of making ones which add full albums to the playlist.

What I'd really love is to have a dynamic playlist that will continuously play random albums from the entire collection, similar to the _Dynamic random mix_ playlist, but adds a whole, randomly selected album to the playlist when it starts playing the last album in the playlist.

**Comment by jonaski** [comment]
Is this something you can do?

**Comment by robbat2** [comment]
This got marked as completed, but without any details about how to do it.
I'd like this, with a tweak as well: play albums I have in my (huge) collection but haven't listened to yet.
