### ISSUE TITLE
Searching online radio stations from within Strawberry

### ISSUE THREAD

**Issue by n-wissam** [strawberrymusicplayer/strawberry#997]
It would be nice to add a search feature for online radio stations since the links for radio stations provided are not a lot
This [website](https://www.radio-browser.info/) is free, the data license is public domain, the server software is open source too
They have API where you can search for online radio stations
[QMPlay2](https://github.com/zaps166/QMPlay2) has this functionality and it's written in QT.

**Comment by jonaski** [comment]
Is this something you can do?

**Comment by n-wissam** [comment]
> Is this something you can do?

No I am sorry I am not experienced in Qt
